### ISSUE TITLE
API Reference Documentation is empty

### ISSUE THREAD

**Issue by insanity54** [taskforcesh/bullmq#100]
https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api-reference.md

There is no content in the api-reference file. This makes using bullmq difficult for new users.

**Comment by seangenabe** [comment]
There are quite a few other empty pages in the documentation.

**Comment by manast** [comment]
it is still a WIP, we are trying to get them ready as fast as we can...

**Comment by pastelsky** [comment]
This has been empty for a year now. Is bull v3 still being maintained and expected to replace bull v2? Or is the recommendation to still use bull v2 in production setups?

**Comment by manast** [comment]
it is not empty at all: https://docs.bullmq.io/index

But I forgot to close this issue, thanks for reminding me.
