### ISSUE TITLE
[Feature Request] Proper pagination for `getJobs`

### ISSUE THREAD

**Issue by majidsajadi** [taskforcesh/bullmq#1007]
as noted in reference: 

```javascript
getJobs(['completed', 'active'], 0, 4)
```

may return 10 jobs. 5 for each `type`. which makes it impossible to list all jobs with proper pagination without considering ‍`type`.  

this feature is needed for a dashboard so we can see an overview of all jobs and their `state`.

**Comment by manast** [comment]
This is most likely not going to be implemented because the data structures used do not allow for this. In dashboards normally you just show one state at a time and so the pagination works with the current implementation.
