### ISSUE TITLE
I can't add the connection options with queue options at the same time in Typescript

### ISSUE THREAD

**Issue by ulasturann** [taskforcesh/bullmq#1015]
Hi everyone,

I'm trying to do a repeatable job in Typescript. But I can't add connection options besides queue options.
I can add queueOptions or Connection Options alone but it's not working together.

You can see the part of the code below.
```
import IORedis from 'ioredis'
const connection = new IORedis();
...
const sendMailQueue = new Queue("sendMail", {
  defaultJobOptions: { removeOnComplete: true },
  {connection} // It's not working
});
...
// I don't have issue when i added the connection option in the worker
const worker = new Worker("sendMail", async (job: Job) => {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, 3000);
  });
},{connection: connection});

```

If i don't add the connection string i am getting this warning message on terminal;

> "BullMQ: DEPRECATION WARNING! Optional instantiation of Queue, Worker, QueueScheduler and QueueEvents without providing explicitly a connection or connection options is deprecated. This behaviour will be removed in the next major release
> BullMQ: DEPRECATION WARNING! Optional instantiation of Queue, Worker, QueueScheduler and QueueEvents without providing explicitly a connection or connection options is deprecated. This behaviour will be removed in the next major release
> BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null and enableReadyCheck false. On the next versions having this settings will throw an exception
> BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null and enableReadyCheck false. On the next versions having this settings will throw an exception"
> 

So how can i add connection options with queue options(in this case as you can see this is defaultJobOptions).
i would be glad to be happy to your help.
Thanks for your time.

**Comment by roggervalf** [comment]
hi @ulasturann, it seems that your connection should not be inside of {}, could you try:
```js
const sendMailQueue = new Queue("sendMail",
        defaultJobOptions: { removeOnComplete: true },
        connection
      })
```

**Comment by manast** [comment]
@ulasturann consider using Typescript, to avoid this kind of errors in the future.

**Comment by JClackett** [comment]
Looking at the signature of the Queue type I see

```
constructor(name: string, opts?: QueueOptions, Connection?: typeof RedisConnection);
```

if you pass the redis instance as the third argument, the whole thing doesn't work

```
import IORedis from "ioredis"
const connection = new IORedis()

const queue = new Queue(key, undefined, connection)

// TS error: 
// Argument of type 'Redis' is not assignable to parameter of type 'typeof RedisConnection'.


// Runtime error:
// TypeError: Connection is not a constructor

the second argument accepts a connection property

const queue = new Queue(key, {connection: connection})

No ts error now, but I get the runtime warning:

// BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null and enableReadyCheck false. 
```

So unfortunately, typescript is no help here as there is clearly something wrong?

**Comment by manast** [comment]
> // TS error: 
> // Argument of type 'Redis' is not assignable to parameter of type 'typeof RedisConnection'.

But TS is giving you an error, you are passing an invalid argument as "typeof RedisConnection". Having said that, why would you mess with that argument? It is only useful for making extensions to BullMQ, which I assume is not your case :/.

**Comment by JClackett** [comment]
I was testing using the example given above ^

```
const sendMailQueue = new Queue("sendMail",
        defaultJobOptions: { removeOnComplete: true },
        connection
      })
```

However, a fresh install of node_modules has seemed to fix most of my issues!
