### ISSUE TITLE
Change in how repeatable jobs keys are stored on redis 

### ISSUE THREAD

**Issue by alietors** [taskforcesh/bullmq#1018]
Hi,

We have been using bullmq for a long time, on prod we use v1.14.7.

We have an scheduler service that add jobs to queues like this
`queue.add('my-queue-prefix-queue|job|job-id', data, {
        jobId: 'job-id',
        repeat: { tz: "utc", cron }
    })`

That code uses to produce an entry on redis like
`bull:my-queue-prefix-queue:repeat:my-queue-prefix-queue|job|job-id:1643110680000`

The format was bull:QUEUE: repeat :NAME_OF_JOB:NEXT_TIME

But now, for some reason the key added to redis is
`bull:my-queue-prefix-queue:repeat:a2cde7ea09c1e55202b3035390da2bac:1643110680000`

Instead of using the name I provided when adding the job to the queue it show a string that I'm not quite sure what it is but it is preventing us to find the key.

Any idea about what is that? When we use the getRepeatableJobs that id does not come with it.

Thanks!

**Comment by manast** [comment]
I cannot remember right now the reason for the change in the format, but the string in question is the md5 sum of the "repeat job key",  so I think a md5("repeat:my-queue-prefix-queue|job|job-id") would give you that number.
```ts
function md5(str: string) {
  return createHash('md5').update(str).digest('hex');
}
```
Let me know if this is of any help.

**Comment by alietors** [comment]
Hi! Thanks for the reply!

It was a md5 hash but the string was a bit more convoluted.
Looking into the code https://github.com/taskforcesh/bullmq/blob/master/src/classes/repeat.ts I got all the pieces to generate the md5.

Thanks!
