### ISSUE TITLE
Irregular use of lowercase "returnvalue" in `QueueEvents` listener interface (Low Priority)

### ISSUE THREAD

**Issue by prescience-data** [taskforcesh/bullmq#1022]
All other event interfaces use `camelCase` while the `completed` listener uses a fully lowercase `returnvalue` property.
 
https://github.com/taskforcesh/bullmq/blob/30a9bc6c3b719c469396c80f14e8249d7e7ce85b/src/classes/queue-events.ts#L43

**Comment by manast** [comment]
This is the same format as to how the return value data field is stored in Redis. Unfortunately, this design decision was taken many years ago and in order to not create a breaking change, it is better to leave it as is...
