### ISSUE TITLE
Allow access to Job#queue

### ISSUE THREAD

**Issue by bogdan** [taskforcesh/bullmq#1032]
I was surprised that `Job#queue` property is `protected`. 

https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L107

That is the limitation the doesn't allow some abstraction code around the job like:

``` typscript
const cloneJob = (job: Job) => {
  job.queue.add(job.name, job.data)
}
```

Is it possible to make `Job#queue` property public?

**Comment by manast** [comment]
It is easy to workaround this issue by just extending the Queue class...
