### ISSUE TITLE
Feature: Direct support for full redis URLs

### ISSUE THREAD

**Issue by hardcodet** [taskforcesh/bullmq#1039]
As discussed, a follow-up task for the question raised here:

_Originally posted by @dan003400 in https://github.com/taskforcesh/bullmq/issues/53#issuecomment-770271478_

> Is there any reason connection does not accept just a redis connection string without the need of importing ioredis?
> This seems very odd that you can pass in host / port but not only a string with full connection string...

Thanks for your consideration!

**Comment by manast** [comment]
After examining this feature more deeply we have realized that the kind of code changes required do not really motivate the change. In order to keep the API clean, we have decided to not support this feature. Instead, it is recommended to just create the redis instance first and pass it as a parameter:

```ts
import * as Redis from 'ioredis';

const conection = new Redis('redis:/qweqeqwe');

const queue = new Queue('test', { connection });
```

**Comment by highri5e** [comment]
Passing the connection does not work anymore?
"bullmq": "^4.12.0"
"ioredis": "^4.28.3"

Cannot pass the connection to Queue or Worker as shown in the docs.

const conection = new Redis('redis:/qweqeqwe');

const queue = new Queue('test', { connection });

Typescript is complaining about the { connection } object, and building would throw this:

```
15:39:30 worker.1   |  TypeError: Connection is not a constructor
15:39:30 worker.1   |      at new QueueBase (\node_modules\bullmq\dist\cjs\classes\queue-base.js:41:27)
15:39:30 worker.1   |      at new Worker (\node_modules\bullmq\dist\cjs\classes\worker.js:34:9)
```

**Comment by manast** [comment]
@highri5e I wonder if that is the correct code considering you misspelled connection (conection)

**Comment by highri5e** [comment]
Sorry. The code was copied from your comment, which had the misspell in it.

This is my code:

```
import IORedis from 'ioredis';

const connection = new IORedis(_config.REDIS_URL);

const queue = new Queue<T>('name', { connection });
```
