### ISSUE TITLE
Why can't the `volatile-lru` eviction policy be supported along with the `noeviction` policy? 

### ISSUE THREAD

**Issue by doronrk** [taskforcesh/bullmq#1046]
Hey there! The BullMQ docs state that `noeviction` is required "in order to avoid automatic removal of keys which would cause unexpected errors in BullMQ". This makes sense. However, the `volatile-lru` policy will "evict keys by trying to remove the less recently used (LRU) keys first, but only among keys that have an expire set, in order to make space for the new data added" according to the Redis docs. It seems to me that if BullMQ does not set expirations for keys that must not be evicted that this would allow the use of `volatile-lru`.

For context, our Redis instance also acts as a database cache for performance reasons. Using `volatile-lru` allows us to evict keys with out causing application errors in the event that we run out of memory. 

Can you shed some light on whether this approach is possible or whether I'm missing something? Thanks!

**Comment by manast** [comment]
We got reports of users with the volatile-lru policy enabled where the queues started to lose jobs and the like. I do not know the reason, in theory, according to Redis documentation it should not happen, but to play it safe it is better to use noeviction, and then you are 100% that keys will never be removed.

**Comment by doronrk** [comment]
Hey @manast  thanks for your answer. To clarify, is your point of view that BullMQ should never share a Redis instance with any other client? Would you consider having BullMQ share a Redis instance with another client a violation of best practices?

When you received reports of queues losing jobs, etc., was there an investigation to see what expiration keys were being used? I'd be happy to look into this further myself if you could point me to those issues or the relevant part of the code.

Thanks!

**Comment by manast** [comment]
> To clarify, is your point of view that BullMQ should never share a Redis instance with any other client? Would you consider having BullMQ share a Redis instance with another client a violation of best practices?

In general as long as BullMQ prefix is not shared by other clients I do not see any problem with sharing other than of course it could affect performance and space... it all depends on the budget I guess and the performance requirements of the queues and/or the other clients.




> When you received reports of queues losing jobs, etc., was there an investigation to see what expiration keys were being used? I'd be happy to look into this further myself if you could point me to those issues or the relevant part of the code.

No. Just that data was disappearing when the instance reached high levels of memory consumption and they were using volatile-lru. The report is somewhere in Bull or BullMQ issues I do not remember exactly, and after suggesting to change the eviction policy I have not received any other information of the outcome.

**Comment by autarchprinceps** [comment]
Hmm, I tried to set the maxmemory-policy to noeviction, but I still get this message, since bullmq version 2.
Has anyone got this to work with ElastiCache?

**Comment by manast** [comment]
That's strange, are sure that the instance really has noeviction as maxmemory-policy?

**Comment by manast** [comment]
I am closing this as this has already been answered.
