### ISSUE TITLE
Job.queueName is undefined in sandboxed processor

### ISSUE THREAD

**Issue by jgillick** [taskforcesh/bullmq#1050]
I'm trying to use a single processor script that will automatically route jobs from all queues to the correct handlers, however, it doesn't seem possible to get the queue name from the job.

**Launch Worker**
```js
const processorFile = path.join(__dirname, `processor.js`);
const worker = new Worker('comms', processorFile);
```

**Processor File**
```ts
export default async function (job: Job) {
    console.log(job.queueName);  // always returns undefined
});
```

I'm using BullMQ version 1.68.1

Any ideas why this would be happening?

**Comment by manast** [comment]
There is no queueName in the job class. Please consider using typescript to eliminate this issues in the future.

**Comment by manast** [comment]
UPDATE.
Yes, there is actually. However, it is not exposed to the sandbox processor. I will mark it as an enhacement.

**Comment by jgillick** [comment]
@manast Thanks. I've submitted a PR for this: https://github.com/taskforcesh/bullmq/pull/1051
