### ISSUE TITLE
Delay with timestamp

### ISSUE THREAD

**Issue by rogueturnip** [taskforcesh/bullmq#106]
I was wondering if there is the ability to create a delayed job using a calendar date or UTC based epoch.  My use case is to say so something on January 15, 2020. 

One option I see is to calculate the delay from the current time to the future time and set the limit to 1 but thought I'd ask the question if using an epoch timestamp is something that works or in the development plan.

Thanks!

**Comment by manast** [comment]
Can't you just use delayed jobs? https://docs.bullmq.io/guide/jobs/delayed

**Comment by rogueturnip** [comment]
I'm doing this right now.  I take future time-current time to get the delay but I was noticing in the way the delayed jobs are being stored that the timestamp of the delay is being set as an epoch in ms so thought being able to set this directly might be another option.

**Comment by polRk** [comment]
```
const timeInFuture = new Date(2021, 1, 1).getTime();
await myQueue.add('house', { color: 'white' }, { delay: timeInFuture - Date.now() });
```
