### ISSUE TITLE
Job  {Job_id} is not in the active state delayed

### ISSUE THREAD

**Issue by nrmohan** [taskforcesh/bullmq#1062]
We have flow defined with multi level children, Once in a while we receive this error  "Error: Job 249c581d-3c29-40e7-8a05-92693c1b5443 is not in the active state. delayed " . We are not changing the delay dynamically anywhere. 

on further inspecting the worker log we noticed this particular job is executed multiple times by two different pods/instances  without the backoff delay configured while adding the job.

options of the failed job
<img width="408" alt="image" src="https://user-images.githubusercontent.com/16112725/153235626-6b3d2501-3c52-4c59-bb4a-73f58c554dc2.png">

screenshot of the log
<img width="506" alt="image" src="https://user-images.githubusercontent.com/16112725/153237086-8fb5d1c8-77fc-4bc9-a05c-226f9b9bfb3f.png">

our understanding was, there is some kind of lock for the  job to stop another worker from processing the job. Is that not the case?

**Comment by roggervalf** [comment]
hi @nrmohan, could you please try to provide as a piece of code or test case to reproduce your case when you get some chance?

**Comment by nrmohan** [comment]
@roggervalf thank you for looking to this. though i was not able to reproduce this exact error. i was able to reproduce task being executed more or less than configured in the retry count. 

Is this something to do with the job name repeated in child and parent like below?

 ```
await flowProducer.add({
        name: 'task3',
        data: { status: "plan" },
        opts: { attempts: retry, backoff: { type: 'fixed', delay: delay } },
        queueName: TASK_QUEUE,
        children: [
            {
                name: 'task2',
                data: {},
                queueName: TASK_QUEUE,
                opts: { attempts: retry, backoff: { type: 'fixed', delay: delay } },
                children: [{
                    name: 'task3',
                    data: { status: "proposal" },
                    opts: { attempts: retry, backoff: { type: 'fixed', delay: delay } },
                    queueName: TASK_QUEUE,
                }]
            }]
    });
```

A sample worker and scheduler has been pushed below repo. on checking the log the child task 'task3' is executed correctly but the parent tasks are not. 
[https://github.com/nrmohan/bull_mq_bug](url)

**Comment by roggervalf** [comment]
hi @nrmohan, it seems like this is a different issue, also I could reproduce. I think I know where is this happening, let me address it in some minutes.
