### ISSUE TITLE
On failed jobs, why does it show "Failed reason" is null

### ISSUE THREAD

**Issue by gitChristian** [taskforcesh/bullmq#1063]
![image](https://user-images.githubusercontent.com/9953695/153273341-cb765f28-763b-4f22-9a7e-add6524acc8a.png)

Even though the error message is non empty, (`err == "SQL compilation error: Statement is blank"`) The failed reason shows null.
`
    worker.on("failed", async (job: Job<RefreshQuery>, err) => {
      console.log("err is " + String(err));
  }
`

**Comment by manast** [comment]
What about the error stacktrace? is that empty too? 
Btw, you can create a dummy worker with a processor that just throws an exception to see that the failed reason indeed is displayed, something must be different in the processor that generates this null reason. Maybe you are not throwing an Error object but just a string?

**Comment by gitChristian** [comment]
Error stacktrace was empty too.
You're right in that some of the processors throw just a string. I'll assume I must throw an error object.
Is this the only reason you can think of why the `Failed reason` would show up `null` ?
Thank you so much!
