### ISSUE TITLE
getJobCounts does not properly add default types to support omitting any type

### ISSUE THREAD

**Issue by brian715** [taskforcesh/bullmq#1067]
The Queue functionality for [getJobCounts](https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-getters.ts#L77-L93) does not properly add all the types by default when omitting passing a type. Here is the [old bull code for reference](https://github.com/OptimalBits/bull/blob/2f27faa410f70504f24df2ebd6bb7831df21660d/lib/getters.js#L58)

**Comment by roggervalf** [comment]
Hi @brian715, this issue was released in versión 1.71.0, please try it when you get some chance.
