### ISSUE TITLE
Stream event keys in redis takes too much memory 

### ISSUE THREAD

**Issue by nambirajan-goxai** [taskforcesh/bullmq#1070]
keys like bull:queue:events takes too much memory in redis . I had some event keys consuming several GB's of memory .

**Comment by bilalshaikh42** [comment]
Maybe related to #366

**Comment by manast** [comment]
Can you check in your queue what value you have for "opts.maxLenEvents" in your "meta" key for the queue? (the key should look something like this: ```bull:myqueuename:meta```

**Comment by roggervalf** [comment]
pretty sure, the last fix should address the main reason for this issue

**Comment by maximedupre** [comment]
What would be one downside of lowering the `maxLenEvents`?

Can I set it to 0? 🤔

What happens if I set it to `maxLenEvents` that is lower than the number of events that is currently on a queue?
