### ISSUE TITLE
Promote Job when limiter used

### ISSUE THREAD

**Issue by lucmerceron** [taskforcesh/bullmq#1083]
Hello :wave: 

I would like to be able to promote a job dynamically from delayed to waiting (and then active) while using limiter.max, limiter.duration & limiter.groupKey before the limiter.duration time.
When tried today, I believe the moveToActive script just put the job back into the delayed state.

Any chance to see a fix to that? This would open so many possibilities
Thank you very much!

**Comment by manast** [comment]
Not sure what you mean, but you can promote a delayed job to wait already: https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.job.promote.md

**Comment by lucmerceron** [comment]
It doesn't seem to work for delayed job related to the limiter attribute with a groupKey.
Promoting only put it back it the delayed Q. I believe this is what's happening: "delayed" => promote action => "waiting" => moveToActive script (that detect it as if it shouldn't be in waiting) => back to "delayed" (adding I believe the duration of the limiter configuration).
I'm using those attributes : https://docs.bullmq.io/guide/rate-limiting#group-keys

**Comment by lucmerceron** [comment]
This test in test_rate_limiter.ts illustrate the issue:
```

**Comment by manast** [comment]
It is promoting the job from delayed to wait, then it is processed again, if it is still rate-limited it goes back to delay.

**Comment by lucmerceron** [comment]
It's exactly what seems to happen yes.
It sounds to me that promoting a job should be used for that specific case. Meaning the delay (duration here) is not over yet but you want the job to be active.

**Comment by ebourmalo** [comment]
I recently used the rate limiter and faced the same behaviour described here.
any chance to see an update on this @manast 🙏 ?

**Comment by xiaoyu-tamu** [comment]
Facing the same situation here. Hope it can get fix/improve

**Comment by manast** [comment]
Not sure I understand what can be improved. Do you mean that if you promote a delayed job, you expect that the job do not respect the rate limiter anymore and is processed regardless if it should be rate limited or not?

**Comment by manast** [comment]
Well promote does what it says, it promotes a delayed job so that it is processed as quickly as possible, if this job gets processed and still the queue is rate limited, then yes it will be delayed. It is not that the functions is unusable with the limiter, it just works as designed.
