### ISSUE TITLE
Retrying job when limiter used

### ISSUE THREAD

**Issue by lucmerceron** [taskforcesh/bullmq#1084]
Hello again :wave:

I use a limiter with a groupKey and everything works fine until I try to retry a failed job that has no groupKey. This job will be placed in delayed instead of directly in waiting.

Thanks again!

**Comment by manast** [comment]
Can you please provide a test code that reproduces the issue?

**Comment by lucmerceron** [comment]
The thing is that I'm using those attribute : https://docs.bullmq.io/guide/rate-limiting#group-keys on a Queue & Worker with some job that with the groupKey and others without. The one without that fails will end up "delayed" when retried. I'm afraid it's hard to put this complexity in a test but I'll try

**Comment by lucmerceron** [comment]
This test in test_rate_limiter.ts is enough to show what I'm speaking about :)
`  it('should not put in delayed failed job when rate limit by grouping if groupKey is missing', async function () {
    const rateLimitedQueue = new Queue(queueName, {
      connection,
      limiter: {
        groupKey: 'accountId',
      },
    });

    const worker = new Worker(queueName, null, {
      connection,
      limiter: {
        max: 1,
        duration: 1000,
        groupKey: 'accountId',
      },
    });

    await rateLimitedQueue.add('rate test', {});
    const job = (await worker.getNextJob('0')) as Job;
    await job.moveToFailed(new Error('test error'), '0', true);
    const isFailed = await job.isFailed();
    expect(isFailed).to.be.equal(true);
    await job.retry();
    (await worker.getNextJob('0')) as Job;
    const isDelayed = await job.isDelayed();
    expect(isDelayed).to.be.equal(false);

    await worker.close();
  });
`
