### ISSUE TITLE
Decorator support?

### ISSUE THREAD

**Issue by goldcaddy77** [taskforcesh/bullmq#109]
Have you considered adding decorator support now that BullMQ is written using TypeScript? I’m thinking something like how [nestjs/bull](https://github.com/nestjs/bull) exposes them.

Example usage:
https://github.com/mylove132/automated-test-service/blob/master/src/api/task/queue.consumer.ts

**Comment by roggervalf** [comment]
Currently there are https://docs.bullmq.io/guide/nestjs and https://docs.bullmq.io/bullmq-pro/nestjs where decorators are supported
