### ISSUE TITLE
Add support for Node-Redis connection

### ISSUE THREAD

**Issue by Mon0Man** [taskforcesh/bullmq#1093]
Hey! seeing bullmq support ioredis connection, maybe you can also add support for node-redis connections ?

https://github.com/redis/node-redis
https://github.com/redis/node-redis/blob/master/docs/client-configuration.md

**Comment by manast** [comment]
No sorry. That's more stuff to maintain for basically zero gain for the users.

**Comment by jer-0** [comment]
@manast maybe this is worth a rethink now that node-redis has been rewritten by official redis employee and support all module in package and is more popular ioredis.

**Comment by manast** [comment]
I think it would be possible to write a class with the same interface as RedisConnection and implement it using node-redis, however this is not something we will do ourselves, since as mentioned I do not think it is important enough for spending resources on it.
