### ISSUE TITLE
Why not create a FlowJob with parent id?

### ISSUE THREAD

**Issue by swherden** [taskforcesh/bullmq#1097]
Context: Inside a main job, more complex sub jobs have to be created. The complex jobs would fit perfectly into a FlowJob Structure. 
The definite structure is unknown inside the main job. Hence, the FlowJob structure has to be created at runtime and the main job depends on it.
Problem Why is it not possible neither to put the new FlowJob structure as a child into the main job nor to create a FlowJob with the main job as parent?

`const flow:FlowJob = new FlowJob(..., parent: { id: string, queue: string})`

or 

```
const flow:FlowJob = new FlowJob(...);
job.addChild(flow);
```

**Comment by roggervalf** [comment]
hi @swherden, it seems like there is a pr that could handle this case https://github.com/taskforcesh/bullmq/pull/630, could you also elaborate your case a little more. Also it is probably that you should check this pattern https://docs.bullmq.io/patterns/process-step-jobs too

**Comment by swherden** [comment]
Thanks for the PR #630. It looks like that it is solving my demand. 

For the details. I have the requirements to divide a main into x child jobs dynamically at runtime. Furthermore, I would like to track the completion state of all children as well as of the parent job. Therefore, it would be great to add further FlowJobs dynamically as childs to a parent Job.

**Comment by swherden** [comment]
I try @roggervalf 's comment and it is a solution.
