### ISSUE TITLE
Queue.getJobs may return duplicates

### ISSUE THREAD

**Issue by Toilal** [taskforcesh/bullmq#1112]
I wrote this test to reproduce an issue I hit in my app and really confused me.

```typescript
  it('repro', async () => {
    const queue = new Queue('test')
    await queue.add('test', {})
    const jobs = await queue.getJobs(['completed', 'failed', 'paused', 'repeat', 'wait', 'active', 'delayed', 'waiting', 'waiting-children'])
    expect(jobs).toHaveLength(1)
   // Error:
   // Expected length: 1
   // Received length: 2
  })
```

It returns 2 items instead of expected 1, with the job instance duplicated. It is due to 'wait' and 'waiting' status beeing a duplicate ...

Problem is the same if you pass duplicates state in first parameter.

```typescript
  it('repro', async () => {
    const queue = new Queue('test')
    await queue.add('test', {})
    const jobs = await queue.getJobs(['waiting', 'waiting', 'waiting', 'waiting', 'waiting'])
    expect(jobs).toHaveLength(1)
   // Error:
   // Expected length: 1
   // Received length: 5
  })
```

To go further about this issue, I expect `getJobs()` to work without giving any state to return all jobs, as it's the behavior for `getJobCounts()`. Maybe there's a technical limitation due to Redis, but it would be easier to use.

**Comment by manast** [comment]
Yeah, we are not checking if you send duplicate statuses in the call... not sure we should do that kind of defensive programming. Normally you only call "getJobs" for a given status or maybe a couple of them, not sure either it gives so much value to implement a new short hand but sure it could be added if you want to submit a PR for it.

**Comment by Toilal** [comment]
When implementing a dashboard or an API that monitors execution of jobs, you may have to grab all jobs regardless the status.

As a new user of bullmq, and it's not easy to find out the list of all possible statuses either.

I'll open a pull request.
