### ISSUE TITLE
So many errors in typescript code

### ISSUE THREAD

**Issue by polRk** [taskforcesh/bullmq#112]
After clone, i see many errors and can't build project. 

<img width="1054" alt="Снимок экрана 2020-01-14 в 12 47 06 PM" src="https://user-images.githubusercontent.com/39828645/72332977-0eef1800-36cc-11ea-834b-956b7e1299f0.png">

I think, you should use eslnit + tsc with right configs.
tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "declaration": true,
    "outDir": "dist",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "lib": ["esnext"]
  },
  "include": ["src/**/*.ts", "tests/**/*.ts"],
  "exclude": ["node_modules"]
}
```

.eslintrc.js
```
module.exports = {
  parser: '@typescript-eslint/parser',
  extends: [
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
    'prettier/@typescript-eslint',
  ],
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
};
```

**Comment by manast** [comment]
This seems to be specific to your editor setup, there are no errors as demonstrated by the builds in travis.

**Comment by polRk** [comment]
No, it's not all ide setup errors. For example:

My variant ( valid typings )
```
export class Queue<T = any> extends QueueGetters {
  token = v4();
  limiter?: RateLimiterOptions;
  jobsOpts?: JobsOptions;
```

Your variant ( invalid typings )
```
export class Queue<T = any> extends QueueGetters {
  token = v4();
  limiter: RateLimiterOptions = null;
  jobsOpts: JobsOptions;

```
`TS2322: Type 'null' is not assignable to type 'RateLimiterOptions'.`

**Comment by manast** [comment]
You are probably compiling with different settings. As you see the library compiles just fine in Travis, otherwise the tests would not pass.

**Comment by manast** [comment]
For the record with latest code in master as now: 
![image](https://user-images.githubusercontent.com/95200/72381093-0b34b300-3717-11ea-85cf-f9a1592ed603.png)

**Comment by polRk** [comment]
You assign variable with type RateLimiterOptions the value null. In my opinion, this is a mistake

**Comment by polRk** [comment]
Pls, use `RateLimiterOptions | null` type. You mislead other developers with your code

**Comment by polRk** [comment]
In your typings, limiter - is always exists and can't be null. But it false

**Comment by manast** [comment]
you are welcome to submit a PR and then we can discuss if it can be merged.
