### ISSUE TITLE
BullMQ is interfering with process signal handling and prevents other graceful shutdowns (even when not running workers)

### ISSUE THREAD

**Issue by alexstrat** [taskforcesh/bullmq#1125]
As soon as BullMQ is imported in a process, this file [`src/classes/master.ts`](https://github.com/taskforcesh/bullmq/blob/013d6a5ee0c70266ae740abfa596ca9e506de71b/src/classes/master.ts) is imported and interferes with process signals.

It is especially harmful when other mechanism on this process are also trying to interfere with signals to make graceful shutdown (in my case, Apollo server and Socket.io). And it's even more too bad when this process is not even running workers.

I would suggest to at least wait for a Worker to start before interfering and/or make this optional (example [here](https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server/#stoponterminationsignals)).

I think a similar remark would apply to `uncaughtException` handling.

**Comment by ShaunLWM** [comment]
Didn't know this was a huge problem until my project crashed using nodemon for no reason, and then running the project with `node index.js` runs into an infinite crashes.
This happened when my app tried to import an ESM module -> app crashes -> infinite logs by bull.
My terminal literally just hang.

```
< -- normal crash log here -->

<-- start of infinite log -->
TypeError: proc.send is not a function
    at F:\Projects\server\node_modules\bullmq\dist\cjs\utils.js:115:14
    at new Promise (<anonymous>)
    at Object.exports.asyncSend (F:\Projects\server\node_modules\bullmq\dist\cjs\utils.js:114:12)
    at Object.exports.childSend (F:\Projects\server\node_modules\bullmq\dist\cjs\utils.js:125:44)
    at process.<anonymous> (F:\Projects\server\node_modules\bullmq\dist\cjs\classes\master.js:32:19)
    at process.emit (node:events:390:28)
    at process._fatalException (node:internal/process/execution:170:25)
```

**Comment by manast** [comment]
The best would be if you could provided a test code that reproduces the issue, then we can look into a proper fix.

**Comment by alexstrat** [comment]
@manast the leanest reproduction code looks like this:

```js
require('bullmq')

const graceFullyExit = () => {
  console.log('Doing something important before exiting..')
  setTimeout(() => {
    console.log('done. Exiting!')
    process.exit(0)
  }, 1000)
}

process.on('SIGTERM', graceFullyExit)
process.on('SIGINT', graceFullyExit)

// kill yourself after 1sec for the sake of demo
setTimeout(() => {
  process.kill(process.pid, 'SIGINT')
}, 1000)
```
Try commenting the `bullmq` import to see the difference.

**Comment by caoer** [comment]
this is extremely harmful to a project as this code get executed when imported. developer has no control over it. I would like to think that no library is granted to be execute anything during the importing process. This is not a good practice and extremely invasion to a project. 

More importantly, this also raise concerns about the security, which is deadly hard to trace. For example, normally we ensures that the process running worker node is unprivileged. Now this makes that any user requires the file will have to be run in a non-root process. Otherwise, if any root process imported this lib, and any none root process will be able to send 'message' to it to trigger a permission escalation.

**Comment by alexstrat** [comment]
I worked around the issue by doing this as soon as possible

```js
// BullMQ is interfering with process shutdown flow
// see https://github.com/taskforcesh/bullmq/issues/1125
// We want to avoid that so that we can do graceful shutdowns.
// This removes the process signals listeners introduced by
// bullmq.
const SIGINTListeners = process.listeners('SIGINT')
const SIGTERMListeners = process.listeners('SIGTERM')

require('bullmq')

process.listeners('SIGINT').forEach((listener) => {
  if (!SIGINTListeners.includes(listener)) {
    process.removeListener('SIGINT', listener)
  }
})

process.listeners('SIGTERM').forEach((listener) => {
  if (!SIGTERMListeners.includes(listener)) {
    process.removeListener('SIGTERM', listener)
  }
})


// do what you need to do now
// ...
```

**Comment by caoer** [comment]
another work around we do is changing all the importing statement from
```
import { Job, QueueEvents } from 'bullmq';
```
to 

```
import { Job } from 'bullmq/dist/cjs/classes/job';
import { QueueEvents } from 'bullmq/dist/cjs/classes/queue-events';
```

again, this is sad and frustrating

**Comment by caoer** [comment]
_sorry, my boss is harsh and our deadline is tight._  😭

**Comment by manast** [comment]
We discovered that ```master.ts``` is imported by mistake. This file should not be imported at all, it is a wrapper for child processes, and the issue was introduced in version 1.76.0, a fix is on the way.

**Comment by manast** [comment]
For the record, the error was introduced when using the automatic "barrel" function in VS studio that automatically exports all the modules, including master.ts.

**Comment by caoer** [comment]
thank you 👏
