### ISSUE TITLE
add child jobs to already existing parent job

### ISSUE THREAD

**Issue by jos-bek** [taskforcesh/bullmq#1126]
I have a case where I need to add child jobs to an existing parent job, that is still on the `waiting-children` state. 
Therefore I tried to add the children via the `addBulk`-method of the queue class. In the job options I added the parent job informations to the `parent`-object.
The method has run without any error. I also get the right return value with the correct parent job value, but the child jobs don't exists in Redis.
Then I tried to use the `add`-method of the queue class, with the same job options. After that I get the Error `Missing key for parent job {Some Key}. addJob`.
I also tried to remove the parent options and the job was normally added to Redis.

Is it generally possible to add child jobs later on to a parent job with a `waiting-children` state?
Thanks for helping 🙏

**Comment by roggervalf** [comment]
hi @jos-bek could you try to reproduce this case in a test case? Also there are 2 recommended ways that you can use for handling parent-child dependencies:
1. Use flow producer instance to add an entire flow.
2. If you need to add children in a dinamic way, probably you could check this pattern https://docs.bullmq.io/patterns/process-step-jobs

**Comment by bensenescu** [comment]
@jos-bek @roggervalf What do you mean by `I forgot to add the prefix to the parent queue name`? I'm looking at the example and don't see anything about a prefix. Maybe its changed since this post?

I'm running into an issue where a child task with dynamically added grandchildren is stalling. Can't figure out why its not being picked back up properly.

**Comment by manast** [comment]
@bensenescu the best would be to create a new issue with code that reproduces it, then we can help you much faster.
