### ISSUE TITLE
Why aren't we using Pipelining for getting jobs of a Queue?

### ISSUE THREAD

**Issue by ATheCoder** [taskforcesh/bullmq#1127]
Pretty much what the title says. If you look at https://github.com/taskforcesh/bullmq/blob/e37f6f8eed5589b69ed7a2ed27e951846fbfbb0c/src/classes/queue-getters.ts#L254 you can see that `Job.fromId` gets called for every single job inside the queue.

This seems very inefficient to me because according to [this](https://stackoverflow.com/questions/3329408/is-there-mget-analog-for-redis-hashes) stack-overflow question you can get the result of multiple `hgetall` commands using a [pipeline](https://redis.io/topics/pipelining). If we implement this, it will reduce latency drastically.

If @manast is okay with this. I can make a PR for it.

**Comment by manast** [comment]
If you can provide a solution that is much faster than the current solution, then sure we are OK with it. But we will need some numbers in order to be convinced :)

**Comment by manast** [comment]
I do not think "enableAutoPipelineing" will work in complex uses as in BullMQ. In any case, I think the processing jobs is pretty optimized right now, I don't think there are any easy optimizations to do. The most important that I have in the back of my head is to reduce the size of the jobs in different ways, for example reducing the length of the option fields to max 3 chars, allowing for better encoding (including compression) of the "data" payload (uses JSON now), etc.

**Comment by ATheCoder** [comment]
For some reason I feel like @manast has already tried this and has not seen an improvement.

If that is not true then, we could make a benchmark and check?

**Comment by manast** [comment]
Before closing this issue, I do not think there are easy performance improvements to do in the NodeJS code of the library, it is possible that using the official Redis npm module we can gain a bit more performance, as it seems like it is faster these days. However we can reach more than 100k jobs/sec using Dragonfly, so I think performance wise we are quite competitive for now... https://bullmq.io/news/101023/dragonfly-compatibility/
