### ISSUE TITLE
[bug] memory leak if throw inside event listener

### ISSUE THREAD

**Issue by xiaoyu-tamu** [taskforcesh/bullmq#1129]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/33362998/157706414-251b57cf-88ec-469c-bf33-2bd35dda80f3.png">

version: 1.76.3

```ts
import { Queue, Worker, QueueScheduler } from 'bullmq';

process.title = 'bullmq';

const queue = new Queue('Q1', { connection: {} });
const queueScheduler = new QueueScheduler('Q1', { connection: {} });
const worker = new Worker(
  'Q1',
  async () => {
    console.log('processing');
  },
  { connection: {} },
);

worker.on('completed', async () => {
  throw new Error('Oops');
});

queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});
queue.add('', {});

```

**Comment by manast** [comment]
How do you conclude there really is a memory leak?

**Comment by xiaoyu-tamu** [comment]
I'm not sure it's a memory leak or not. But eventually I'll get "heap out of memory" error and that process used 8gb memory. 

Correct me if i'm wrong.

**Comment by xiaoyu-tamu** [comment]
in 1.75.x, the exception will throw and process exit
in 1.76.x, the exception wont throw and memory keep increasing

**Comment by manast** [comment]
Can you provide a full example that reproduces the leak? also, what is the "x" in your versions numbers?

**Comment by xiaoyu-tamu** [comment]
sure, i use "1.75.x" here to refer any versions that >=1.75.0  <1.76.0  

https://github.com/xiaoyu-tamu/bullmq-issue-1129

**Comment by manast** [comment]
I run the test and I get the exceptions. How do I see the leak?

**Comment by xiaoyu-tamu** [comment]
what's your node version?

I get the exceptions in node 14, leak in 16 and 17

https://user-images.githubusercontent.com/33362998/157813450-dbe688b8-ef91-4d95-a167-cdabe53e4fe6.mov

**Comment by manast** [comment]
I do not know what to say about it... So node16 and node17 consume much more memory, I have no idea why, worker.on is just a standard listener from Node, we do not do anything special, it is just directly taken from Node EventEmitter...

**Comment by xiaoyu-tamu** [comment]
ok

**Comment by kuberlog** [comment]
My team also experienced "heap out of memory" errors on pretty much all our local dev machines after upgrading to 1.76.1. We downgraded to 1.75.1 to resolve the issue.

**Comment by kuberlog** [comment]
@manast since this is closed. Just want to FYI that this has now been experienced in a separate environment than OPs
