### ISSUE TITLE
How do I log a job that has failed all retries?

### ISSUE THREAD

**Issue by arcoraven** [taskforcesh/bullmq#1130]
I have a job with intermittent failures, but usually completes the job successfully within the 3 attempts configured on the queue. I'd like to log a job that has failed all of it's retries so I know to manually investigate it. I believe the `failed` event is emitted on each job failure, not just after the third attempt.

I'm currently doing this:
```javascript
worker.on('failed', (job: Job) => {
    // Get the # times the queue will attempt.
    // If attempts isn't set, the job tries only once. Is this a correct assumption?
    const maxAttempts = job.opts.attempts || 1;
    
    // Skip if the job will be retried.
    if (job.attemptsMade < maxAttempts) return;

    // Alert the team that a job failed after all attempts!
});
```

But was wondering if there was an event or more preferred pattern to do this.
Thanks in advance!

**Comment by ruckonic** [comment]
Hi @arcoraven, Do you need an instance of  `QueueEvents`

```ts
import {QueueEvents} from 'bullmq'

const queueEvent = new QueueEvents('queue-name', {connection})

queueEvent.on('retries-exhausted', async ({ jobId, attemptsMade }) => {
  // your code ....
})
```

**Comment by arcoraven** [comment]
Thanks, I wasn't aware of that event, but I guess it's fairly new (Jan '22).
