### ISSUE TITLE
Support repeat option in defaultJobOptions

### ISSUE THREAD

**Issue by neemanjabu** [taskforcesh/bullmq#1134]
> Issue:
- if **repeat** option is set in **defaultJobOptions**, this option is not taken into account when a new job is added to the queue.
```javascript
const myQueue = new Queue('foo', {
  defaultJobOptions: {
    attempts: 3,
    repeat: {cron: '*/10 * * * * *'}
  },
});

myQueue.add('newJob')  // this will not be added as repeatable job
```

> Problem in code:

` if (opts && opts.repeat) {` only the job options are checked and not merged with the **defaultJobOptions**
```javascript
async add(
    name: NameType,
    data: DataType,
    opts?: JobsOptions,
  ): Promise<Job<DataType, ResultType, NameType>> {
    if (opts && opts.repeat) {
      return (await this.repeat).addNextRepeatableJob<
        DataType,
        ResultType,
        NameType
      >(name, data, { ...this.jobsOpts, ...opts }, true);
    } else {
```
> Possible solution

**this.jobOpts** and **opts** should be merged before the **repeat** option check
(this is properly handled in bull https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L725)

```javascript
async add(
    name: NameType,
    data: DataType,
    opts?: JobsOptions,
  ): Promise<Job<DataType, ResultType, NameType>> {
    // firstly merge options
    const options = { ...this.jobsOpts, ...opts };
    // then check for the repeat option
    if (options.repeat) {
      return (await this.repeat).addNextRepeatableJob<
        DataType,
        ResultType,
        NameType
      >(name, data, options, true);
    } else {

**Comment by manast** [comment]
With the new API for Job Schedulers this feature request becomes irrelevant in the sense that you should only be able to create repeatable jobs with the new API: https://docs.bullmq.io/guide/job-schedulers
