### ISSUE TITLE
Is there an ignoreLock option for moveToCompleted?

### ISSUE THREAD

**Issue by Pro-Ton** [taskforcesh/bullmq#1138]
Hi, In the Bull3 I had a manual handling queue in which clients sent completed jobs to a REST endpoint and I could move them to completed like this: 
```
const id = req.params.id;
const returnValue = req.body;
const job = await tasksQ.getJob(id);
await job?.moveToCompleted(returnValue , true, true);
```

But in the BullMQ I wasn't able to produce such functionality:

I tried:

```
const job = await tasksQ.getJob(id);   // Also: await Job.fromId(tasksQ, id);
await job.moveToCompleted(returnValue, 'my-token', false);
```
But I get exception:
`Error: Missing lock for job 14. `

Clearly there was an option to ignoreLock in the previous version. I searched the docs but couldn't find similar option. Is there any options or other way of doing such functionality? 

Thanks for the amazing work.

**Comment by manast** [comment]
https://docs.bullmq.io/patterns/manually-fetching-jobs

**Comment by manast** [comment]
Then use the same token id for everything and it should work.

**Comment by Niek** [comment]
@Pro-Ton did you find a solution for this? I have the exact same use-case (manually processing jobs, given a specific ID), and the following code doesn't work:
```js
const job = await queue.getJob(id)
job && job.moveToCompleted('returndata', 'token', false)
```
It throws with the error `Error: Missing lock for job <ID>. finished`

**Comment by StringKe** [comment]
@Niek Did you solve this problem?

**Comment by Niek** [comment]
@StringKe not really - see https://github.com/taskforcesh/bullmq/discussions/1152 for a more extensive discussion.
