### ISSUE TITLE
Retry does not work with flows

### ISSUE THREAD

**Issue by mravey** [taskforcesh/bullmq#1148]
It looks like retries do not work with Flow. I have a queue with `defaultJobOptions.attemps = 4`, it does retry with a normal job but not with a job that is part of a flow.
Here is code to reproduce the issue:
```javascript
const { Queue, Worker, QueueScheduler, FlowProducer } = require("bullmq");

const myQueue = new Queue("test_bull", {
  defaultJobOptions: {
    attempts: 4,
    backoff: {
      type: "exponential",
      delay: 1000,
    },
  },
});

new QueueScheduler("test_bull");

const producer = new FlowProducer();

const addJob = async () => {
  // await myQueue.add("my_job");

  await producer.add({
    name: "my_parent_job",
    queueName: "test_bull",
    children: [
      {
        name: "my_job",
        queueName: "test_bull",
      },
    ],
  });
};

addJob().catch(console.log);

const w = new Worker("test_bull", async (job) => {
  console.log(job.id, job.data);

  throw new Error("TODO");
});

w.on("failed", (job) => {
  console.log(`job failed ${job.id}`);
});
```

**Comment by roggervalf** [comment]
hi @mravey, you should probably need to check https://docs.bullmq.io/guide/flows#provide-options

**Comment by C0rellana** [comment]
Hi, 
Is there any way to solve this problem?, I have the same problem, if the child job fails or stops, the parent job does not run

**Comment by abarbosa-godaddy** [comment]
Hey guys. Is it possible to retry a flow?  Either partially or complete? I have a flow and if one of the children fails I would like to retry the failed one and continue the flow.
