### ISSUE TITLE
Queue typings make no sense to me

### ISSUE THREAD

**Issue by ssipos90** [taskforcesh/bullmq#1156]
Hi,

I've been trying to use bullmq with TS and have issues properly typing stuff.

Given

```typescript
type SomeData = {
  some: number;
};
type OtherData = {
  other: string;
};
type DataType = SomeData | OtherData;
type ReturnType = void;
type Jobs = 'some-job' | 'other-job'; // as opposed to string

const myQueueName = 'my-queue-name';

const myQueue = new Queue<DataType, ReturnType, Jobs>(myQueueName);
const myWorker = new Worker<DataType, ReturnType, Jobs>(myQueueName, async job => {
  console.log(job.name); // either 'some-job' or 'other-job'
  console.log(job.data); // either '{ some: number }' or '{ other: string }'
});
```

By my understanding, you can't associate the job to it's data type, but rather it's gonna be a carthesian product between the two which doesn't make any sense to me.

*Am I using it wrong?* I assumed I could have a few job types in the same queue, but with different payloads.

If I'm supposed to use different queues, then `job.name` is kind of useles since all jobs in a queue ~should~**must** have the same payload.

Thanks.

**Comment by ssipos90** [comment]
The issue is that you could have, for example, two newsletters that have a difference in `DataType`, thus using an union type, and you wouldn't be able to tell them apart based on the job name because of the generated types.

How would you go about using this? Having different queues defeats the purpose of having a job name.

Not using types means `typeof job.data` would be `any` and defeats the point of using typescript. "Great" argument, though.

**Comment by nullndr** [comment]
The job name should be a string. 

I would suggest you using a different approach with the unions.

```typescript
type SomeData = {
  name: "some";
  some: number;
};

type OtherData = {
  name: "other";
  other: string;
};

type DataType = SomeData | OtherData;
type ReturnType = void;
type Jobs = "update"; // as opposed to string

const myQueueName = "my-queue-name";

const myQueue = new Queue<DataType, ReturnType, Jobs>(myQueueName);
const myWorker = new Worker<DataType, ReturnType, Jobs>(
  myQueueName,
  async (job) => {
    console.log(job.name); // either 'some-job' or 'other-job'
    switch (job.data.name) {
      case "some": {
        console.log(job.data.some);
        break;
      }
      case "other": {
        console.log(job.data.other);
      }
    }
  }
);

```

**Comment by ssipos90** [comment]
That's the way I have implemented in the meanwhile, to get production going.

For what's worth, I've patched up a demo on the issue and a fix, but it's backwards incompatible. If you wanna check it out: https://github.com/ssipos90/bullmq-types-inconsistency/tree/main/src

**Comment by danielr18** [comment]
@ssipos90 This is how I got it working (I skipped the data type and return type definitions, but left in comments how you would use them)

```typescript
export enum QueueNameType {
  HelloWorld = 'hello-world',
  Test = 'test'
}

export type HelloWorldJob = Job<
  { helloMessage: string },
  void,
  QueueNameType.HelloWorld
>;

export type TestJob = Job<
  { message: string },
  string,
  QueueNameType.Test
>;

type QueueJob = HelloWorldJob | TestJob;

const testQueue = new Queue<
  any, // Union of the different job data types: HelloWorldDataType | TestJobDataType
  any, // Union of the different job return types: HelloWorldReturnType | TestJobReturnType
  QueueNameType
>('test');

const worker = new Worker<
  any, // Union of the different job data types: HelloWorldDataType | TestJobDataType
  any, // Union of the different job return types: HelloWorldReturnType | TestJobReturnType
  QueueNameType
>(
  testQueue.name,
  async (job: QueueJob) => {
    switch (job.name) {
      case QueueNameType.HelloWorld:
        // job.data will be of type HelloWorldDataType
        break;
      case TasksQueueNameType.Test:
        // job.data will be of type TestJobDataType
        return 'test';
    }
  }
);
```

**Comment by xxRockOnxx** [comment]
> @ssipos90 This is how I got it working:
> 
> ```ts
> export enum QueueNameType {
>   HelloWorld = 'hello-world',
>   Test = 'test'
> }
> export type HelloWorldDataType = { helloMessage: string };
> export type HelloWorldReturnType = void;
> export type HelloWorldJob = Job<
>   HelloWorldDataType,
>   HelloWorldReturnType,
>   QueueNameType.HelloWorld
> >;
> 
> export type TestJobDataType = { message: string };
> export type TestJobReturnType = message;
> export type TestJob = Job<
>   TestJobDataType,
>   TestJobReturnType,
>   QueueNameType.Test
> >;
> 
> type QueueJob = HelloWorldJob | TestJob;
> 
> const testQueue = new Queue<
>   HelloWorldDataType | TestJobDataType, 
>   HelloWorldReturnType | TestJobReturnType,
>   QueueNameType
> >('test');
> 
> const worker = new Worker<
>   HelloWorldDataType | TestJobDataType, 
>   HelloWorldReturnType | TestJobReturnType,
>   QueueNameType
> >(
>   testQueue.name,
>   async (job: QueueJob) => {
>     switch (job.name) {
>       case QueueNameType.HelloWorld:
>         // job.data will be of type HelloWorldDataType
>         break;
>       case TasksQueueNameType.Test:
>         // job.data will be of type TestJobDataType
>         return 'test';
>     }
>   }
> );
> ```

This works but to me it looks tedious. I thought something like #1301 would work but for some reason it's not.

**Comment by marbemac** [comment]
Here's my solution. Basically just have to define the queue names (`DNQueueName` below) and queue input/outputs (`DNQueue` below), and then can use the `TypedQueue` and `TypedWorker` classes to get mostly typesafe everything.

```ts
export const enum DNQueueName {
  'raw_events_watcher' = '{raw_events_watcher}',
  'raw_events_processor' = '{raw_events_processor}',
};

/** Define the queue jobs and their input/outputs */
interface DNQueue {
  [DNQueueName.raw_events_watcher]: {
    jobs: {
      watchRawEvents: {
        input: {};
        output: void;
      },
      anotherJob: {
        input: { foo: string };
        output: { bar: string };
      },
    }
  };
  [DNQueueName.raw_events_processor]: {
    jobs: {}
  };
}

// @ts-expect-error ignore, works as of when this was written
type QueueData<T extends DNQueueName> = DNQueue[T]['jobs'][keyof DNQueue[T]['jobs']]['input'];

// @ts-expect-error ignore, works as of when this was written
type QueueReturn<T extends DNQueueName> = DNQueue[T]['jobs'][keyof DNQueue[T]['jobs']]['output'];

type QueueJobNames<T extends DNQueueName> = Extract<keyof DNQueue[T]['jobs'], string>;

type QueueJob<T extends DNQueueName, J = DNQueue[T]['jobs']> = {
  // @ts-expect-error ignore, works as of when this was written
  [K in keyof J]: JobPro<J[K]['input'], J[K]['output'], K>;
}[keyof J];

export class TypedQueue<T extends DNQueueName> extends QueuePro<QueueData<T>, QueueReturn<T>, QueueJobNames<T>> {
  constructor(name: T, opts?: QueueProOptions) {
    super(name, opts)
  }
}

export class TypedWorker<T extends DNQueueName> extends WorkerPro<QueueData<T>, QueueReturn<T>, QueueJobNames<T>> {
  constructor(name: T, fn: <J extends QueueJob<T>>(job: J) => Promise<QueueReturn<T>>, opts?: WorkerProOptions) {
    super(name, fn, opts)
  }
}
```

Now use it:

```ts
const myQueue = new TypedQueue(DNQueueName.raw_events_watcher, { connection: '' });

void myQueue.add('watchRawEvents', {}); // OK
void myQueue.add('watchRawEventsXXX', {}); // NOT OK, invalid job name
void myQueue.add('anotherJob', { fooxyz: '' }); // NOT OK, invalid job parameters

const myWorker = new TypedWorker(
  DNQueueName.raw_events_watcher,
  async (job) => {
    switch (job.name) { // type-checked switch statement
      case 'watchRawEvents':
        return;
      case 'anotherJob':
        console.log(job.data.foo) // type-checked job data
        return { bar: '' }; // type-checked response
    }
  },
  { connection: '' },
);
```
