### ISSUE TITLE
changeDelay does not update job properties to reflect new expected execution time

### ISSUE THREAD

**Issue by hoangbn** [taskforcesh/bullmq#1160]
After fixing https://github.com/taskforcesh/bullmq/issues/787,  job executes correctly after changing delay now.
However,  I don't see the properties of the job updated to reflect the new execution time

For example, if I create a job:
```
  id: '123',
  name: 'someJob',
  data: { ... },
  opts: {
    delay: 20000,
    jobId: '123',
  },
  timestamp: 1648409394575
```
I calculate its earliest execution time to be: `1648409394575 + 20000`

After changing the job delay using changeDelay to say `40000`, I expect these properties to change so I can calculate the new execution time to be `now() + 40000` (currently nothing changes).

**Comment by wenq1** [comment]
Upon the time you call now () + 40000, now () has already deviated from the calling time of changeDelay ().

I think delay is just an "suggestion". Maybe it is better for something like job._expected_start_date which is always fixed to be exposed. That doesn't prevent the 'delay' opts in this question to be changed thou.
