### ISSUE TITLE
Error passing in ioredis v5 instance to connection

### ISSUE THREAD

**Issue by JClackett** [taskforcesh/bullmq#1167]
The new ioredis package bundles its own TS types now and when passing in the redis instance to the connection of the Queue I get:

```
Type 'Redis' is not assignable to type 'ConnectionOptions | undefined'.
  Type 'Redis' is missing the following properties from type 'Cluster': nodes, rpushBuffer, lpushBuffer, hsetBuffer, and 2 more.ts(2322)
```

Investigating I see that the connection property is expecting a Redis type based off the @types/ioredis package, and it doesn't seem to match the with the new one.

bullmq v1.78.1
ioredis v5.0.2

Reverting to old ioredis fixed ts issue

**Comment by manast** [comment]
Can you provide a complete code snippet that reproduces the error?

**Comment by JClackett** [comment]
There must have been some issue with may node_modules as a fresh install stopped the errors!

**Comment by soulchild** [comment]
This seems to become an issue when you have dependencies installed which bring in `@types/ioredis`- in my case `@types/connect-redis`. This makes the TypeScript compiler pick up those types which probably clash with the now built-in types of ioredis >= 5.

**Comment by manast** [comment]
makes sense. ioredis 5 is quite new though, it may be safer to keep using the v4 until v5 gets more mature.
