### ISSUE TITLE
removeRepeatable is not working

### ISSUE THREAD

**Issue by ceroy-ak** [taskforcesh/bullmq#1169]
I'm exploring bullmq to create a repeatable job that repeats every minute for 20 times and polls an external endpoint to check status of a voice call and based on the response the job takes action, now in this one of the status is `completed` which means now the work on the polling job is complete and hence, of course, I don't want the job to continue the next time. 

So I experimented removeRepeatable using the following code

```typescript
import * as redis from "ioredis"
import { Job, Queue, Worker, QueueEvents, QueueScheduler } from "bullmq"


const redisInstance = () => {
    return new redis.Cluster(
        [
            {
                port: 30001,
                host: "localhost",
            },
        ],
        {
            scaleReads: 'slave',
            enableReadyCheck: false,
        }
    )
}
const key = "my_queue"
const myQueueScheduler = new QueueScheduler('test', {
    connection: redisInstance(),
    prefix: `{${key}}`,
})
const queue = new Queue("test", {
    connection: redisInstance(),
    prefix: `{${key}}`,
})

const worker = new Worker("test", async (job: Job) => {
    // Just to simulate that after two polls the status from external endpoint is `completed`
    if (job.opts.repeat?.count === 2) {

   //Remove Repeatable
        return queue.removeRepeatable(job.name,
        {
            every: 1000 * 2,
            limit: 4
        }, 
        job.id)
    }
    console.log(job.data, " ", job.opts.repeat?.count)
}, {
    connection: redisInstance(),
    prefix: `{${key}}`,
});

async function addToQueue() {
    queue.add("bird", "Hello World WOWOWOOW", {
        repeat: {
            every: 1000 * 2,
            limit: 4,
        }
    })
    return
}

addToQueue()
```

But the job is not getting removed after 2 counts and instead is completing the 4 repeats as per the RepeatOptions. I'm not sure which part I'm missing from the docs but my use case requires to remove the job.

**Comment by ceroy-ak** [comment]
@manast I know this issue might sound as dumb but can you help out in understanding where am I going wrong with this?

**Comment by roggervalf** [comment]
hi @ceroy-ak sorry for the delay https://github.com/taskforcesh/bullmq/blob/master/tests/test_repeat.ts#L739-L767 this test case could help on your question. So we provide jobId param in removeRepeatable when the jobId is also a custom one, in your case is not needed the third parameter

**Comment by lukepolo** [comment]
im having the same issue, unable to remove job 

```
await this.queue.removeRepeatable(job._job.name, {
          cron: job._job.cron,
        })
```

Using the 3rd param works (but it doesn't remove failed / completed) , 

also `removeRepeatableByKey` does work with the job key but still same issue about removing failed / completed. 


Once a repeat job is stuck like that you are unable to add them back.

**Comment by manast** [comment]
@lukepolo ok, so remove repeatable was not designed to remove also every completed/failed iteration produced by the repeatable job.
