### ISSUE TITLE
Retries not working?

### ISSUE THREAD

**Issue by Adam-Burke** [taskforcesh/bullmq#117]
Looking for help figure out why this never seems to retry. **attemptsMade** never gets above 1 and the console.log in the handler only gets called once.

_worker.ts_
```
export const handler = (job: Job) => {
  console.log(job.data);
  return Promise.reject(new Error('We failed yo'));
};

new Worker('Test',handler, { connection: CONFIG.adapters.redisConnection });
```
_testRunner.ts_
```
testQueue.add('test_message', {
  data: Math.random() * 40000,
}, {
  attempts: 5,
  backoff: {
    type: 'exponential',
    delay: 2000
  },
});
```

_queue.ts_
`const testQueue = new Queue('Test', { connection: CONFIG.adapters.redisConnection });
`

<img width="991" alt="Screen Shot 2020-01-23 at 1 54 53 am" src="https://user-images.githubusercontent.com/11741126/72904744-7e779e00-3d83-11ea-8786-c246a2f35163.png">

**Comment by manast** [comment]
remember that you need to have a ```QueueScheduler```  https://docs.bullmq.io/guide/queuescheduler

**Comment by Adam-Burke** [comment]
> remember that you need to have a `QueueScheduler` https://docs.bullmq.io/guide/queuescheduler

Thanks Manast. That was it!
