### ISSUE TITLE
Stalled/failed jobs stay in queue

### ISSUE THREAD

**Issue by CodingMeSwiftly** [taskforcesh/bullmq#1171]
We're seeing something very similar to [this issue](https://github.com/taskforcesh/bullmq/issues/977), where stalled/failed jobs remain in the queue, even when `removeOnComplete` and `removeOnFail` are `true` in the job's options.

#1042 claims to fix it by not allowing progress updates after a job was removed from the queue (missing job key). The PR was released in [v1.68.1](https://github.com/taskforcesh/bullmq/releases/tag/v1.68.1), we're on [v1.78.2](https://github.com/taskforcesh/bullmq/releases/tag/v1.78.2).

We can work around the issue as mentioned in #977 by periodically clearing the queue ourselves, but it definitely feels like a bug with job scheduler.

In either case, setting the `removeOnComplete` and `removeOnFail` flags in job options should make sure the job is removed, even if stalled. Effectively leaving an empty queue if no job is scheduled for a certain amount of time. We see failed jobs in the queue even after having a job scheduler connected and running for >5h:

![Image 31 03 22 at 19 38](https://user-images.githubusercontent.com/6830248/161130486-aacf2cb8-ac1d-4ce9-ae21-a80d8c6d2860.jpg)

I've noticed that the jobs in question have in common that they perform very long running http requests (>1min), but they're async so stalling should not be caused by that, right?

**Comment by CodingMeSwiftly** [comment]
I can confirm `moveStalledJobsToWait` is called in the scheduler, but that doesn't remove the stalled jobs either.

**Comment by manast** [comment]
Is there any code that reproduces this issue?

**Comment by CodingMeSwiftly** [comment]
Well our codebase :) - I'll try to put together an MVP over the weekend and will share it here.

**Comment by manast** [comment]
We can reproduce this. But I do not remember if this is actually a feature. It is possible I reasoned that we will never want to automatically remove stalled jobs, please try to convince me why is it a good thing to support?

**Comment by CodingMeSwiftly** [comment]
I can just speak for myself here:
Stalled jobs or the 'stalled' state in general seem not to live on the API surface (there is no `getStalled` on the `Queue` class).
The [QueueScheduler documentation](https://docs.bullmq.io/guide/queuescheduler) states that stalled jobs, 'are moved back or failed depending on the settings selected when instantiating the class.' That suggests that jobs cannot stay `stalled` indefinitely if we use a `QueueScheduler`, they have to end up either completed or failed.

Therefore, it seems counterintuitive to have failed jobs stay in the queue when you set `removeOnFail`.

I guess one option would be to introduce another flag (e.g. `removeOnStall`) to handle that scenario. As it stands, the more intuitive behavior in my opinion derived from the documentation would be to remove jobs if they fail (due to stalling or any other reason) - again, just speaking for myself.

**Comment by manast** [comment]
Ok, so your argument is more from a consistency point of view rather than a practical use case, I am assuming correctly?

**Comment by CodingMeSwiftly** [comment]
Mostly that, yes.
One thought I had about practical implications is that jobs in that particular state accumulate and never get cleared from the queue and with that never get cleared from Redis? If we run bullmq in a memory restricted environment (e.g. lower tiers of [heroku-redis](https://elements.heroku.com/addons/heroku-redis) only provide a few MB of memory), and jobs have large amounts of data associated with them, I can see these zombie jobs starting to accumulate quite a memory footprint, especially when their number reaches more than a few hundred.
Then again, if we set `removeOnCompletion` to `false`, all jobs are kept and we would end up running out of memory in these environments much sooner.
I guess in the case where you want to keep the jobs in the queue, it's up to you to make sure to run in an environment with enough memory, because the library can't very well reduce memory consumption if you tell it to keep all jobs.
However, if you really can't or don't want to increase the available memory, there is no way for you to make bullmq keep the lowest footprint possible (without workarounds like cronjobs).
I know it's a bit of a long shot, but it could actually invalidate _some_ use cases of bullmq. Do you agree?

**Comment by manast** [comment]
I think that normally what you want is to keep all failed jobs so that you can examine them one by one, and only keep a handful of completed jobs. Since stalled jobs are a rare occurrence, it is unlikely that you would exhaust the redis memory due to this particular type of failure.

**Comment by DanielNetzer** [comment]
@manast Jumping on this issue with a practical use-case, we use jobId's for deduplication and since this `failed` jobs that do have the `removeOnFail: true` set to true aren't removed we cannot push a new job with the same ID again.
We had to create a monitoring service that clean those up manually.

**Comment by owensbla** [comment]
@manast Is this change still part of 3.0.0? I'm upgrading from bull and running in to some errors.

We have a similar use-case as Daniel in that I make heavy use of custom jobIds and `removeOnFail: true`. I'm running in to a lot of `Missing lock for job  <T>: failed` errors that then result in (presumably) a stalled job that wasn't removed and the inability to add new ones until flushing redis.

Any help/insight would be appreciated!

**Comment by manast** [comment]
@owensbla It would be better to open a new issue with more information of your particular use case, as this one has been closed and resolved.

**Comment by djiktra** [comment]
Facing the same issue. We use custom job ids and need to make sure that on failure the jobs are removed from the queue but loks like that's not happening currently. I opened a new issue here: https://github.com/taskforcesh/bullmq/issues/1662

**Comment by stevenolay** [comment]
Experiencing the same problem in [bull](https://github.com/OptimalBits/bull) was this fixed over there too @manast and if so what version? Safe to assume I should be good to go if i upgrade to the latest version of Bull?
