### ISSUE TITLE
Prometheus / Grafana metrics

### ISSUE THREAD

**Issue by francescov1** [taskforcesh/bullmq#1178]
Is there a service for exporting Prometheus metrics from BullMQ? I found https://github.com/UpHabit/bull_exporter but this seems to be for legacy Bull.

**Comment by manast** [comment]
There is no such service AFAIK. Wouldn't be very hard to port the bull one though since the APIs are so similar.

**Comment by francescov1** [comment]
Sound good, I'm happy to look into this in the next few weeks.

**Comment by gottlike** [comment]
@francescov1 Did you look into it, yet? We need this for a project and it would be great to have it natively in BullMQ.

**Comment by gottlike** [comment]
@francescov1 Sorry to nag, but do you have an updated estimate? If you can't really say that's also valuable information : )

**Comment by francescov1** [comment]
Hey @gottlike, a teammate was recently looking into this, I'll see if they made any progress!

**Comment by lncramer** [comment]
Hey @gottlike, above mentioned teammate here 😄 

We ended up building a custom decorator around BullMQ to record our own Prometheus metrics via the various BullMQ worker and queue events. Of course your mileage may vary depending on how fine grained your metrics need to be, but it's a simple enough implementation to collect metrics on rates for added jobs, successful jobs, and failed jobs for each queue.

**Comment by gottlike** [comment]
Thanks for your quick reply! Okay, then we'll go with a custom implementation, too 😅

**Comment by StarpTech** [comment]
An integration with Prometheus would be the best option here. If BullMQ supported accepting a custom registry and filling it with all critical metrics for ops, that would be the best onboarding experience. A custom integration should only be required for advanced metrics.

**Comment by roggervalf** [comment]
hey folks, there is a work in progress to support Open Telemetry. Hope your tools have an integration with Open Tel.

**Comment by StarpTech** [comment]
Open Telemetry is great but prometheus is de facto standard and ignoring that would be a missed opportunity.

**Comment by manast** [comment]
It should be possible to use our OpenTelemetry implementation with Prometheus: https://prometheus.io/docs/guides/opentelemetry/
But not sure if spans and traces are something useful for prometheus, or we need to add some metrics too. In any case as we enhance the telemetry interface, this will become much more complete.

**Comment by StarpTech** [comment]
Not all people have the option to use the latest prometheus version. The OTEL SDK has support for prometheus https://opentelemetry.io/docs/languages/js/exporters/#prometheus It works without any code changes. Have you considered this option as well?

**Comment by manast** [comment]
> 
> The OTEL SDK has support for prometheus https://opentelemetry.io/docs/languages/js/exporters/#prometheus It works without any code changes. Have you considered this option as well?

This option will not require any change from out side either as far as I know. So basically the Otel integration we have would support Prometheus one way or the other.
