### ISSUE TITLE
worker.close() does not handle process exit correctly 

### ISSUE THREAD

**Issue by Keith-Hon** [taskforcesh/bullmq#1179]
Related to https://github.com/taskforcesh/bullmq/issues/652

Link to reproduce:
https://github.com/Keith-Hon/bullmq-demo

When the consumer is running and get terminated by ctrl-c, the tasks get stuck in active status and never get processed again

**Comment by manast** [comment]
This is by design, you need a QueueScheduler so that the job is moved back to wait and picked up by another worker: https://docs.bullmq.io/guide/queuescheduler

**Comment by Keith-Hon** [comment]
ok thanks. I have added QueueScheduler and it works. (The stalled tasks moved to waiting.)

I couldn't find any example with the QueueScheduler. Any pointer for this?

**Comment by roggervalf** [comment]
hi @Keith-Hon, you probably are looking for https://docs.bullmq.io/guide/queuescheduler
