### ISSUE TITLE
Bull 3 / BullMQ inter process compatibility

### ISSUE THREAD

**Issue by VictorGaiva** [taskforcesh/bullmq#118]
I'm working on a service that currently uses Bull3. There is another service that communicates with it using HTTP, but I have been thinking about migrating to using Bull/Redis instead.

My question now is, can a Bull3 Consumer work with BullMQ Producer jobs? 

I was not able to find documentation on it.

**Comment by manast** [comment]
BullMQ can take over a Bull queue, but it is not a good idea to mix the two.
