### ISSUE TITLE
Job cleanup or garbage collection

### ISSUE THREAD

**Issue by Philluxx** [taskforcesh/bullmq#1180]
Hey there,

couldn't find out from the documentation whether you have to take care of removing completed jobs yourself at some point? This is a question I ask myself, especially with repeatable jobs. Because many jobs accumulate there over the course of time.

Or does BullMQ do this itself? In Redis, noeviction should be selected as the key eviction policy. Therefore, Redis itself does not take care of cleaning up under memory pressure.

I would appreciate your thoughts on this. Perhaps it is also a point for the documentation.

Thanks a lot
Philluxx

**Comment by manast** [comment]
Thanks for the reporting this issue. Actually I thought we talked about this in the documentation, but I see it is not there. You can still find it in the API reference, the options removeOnComplete and removeOnFail: https://api.docs.bullmq.io/interfaces/JobsOptions.html#removeOnComplete
You use these options when adding a job to the queue:
https://api.docs.bullmq.io/classes/Queue.html#add

**Comment by kylecannon** [comment]
Could bullmq support the ability to remove jobs after a specific amount of time? I don't want to keep tens of millions of jobs in redis but would like to store either a maximum amount or a TTL for eviction

**Comment by manast** [comment]
@kylecannon https://api.docs.bullmq.io/interfaces/BaseJobOptions.html#removeOnComplete

**Comment by manast** [comment]
There are also some examples in the guide: https://docs.bullmq.io/guide/jobs/fifo#default-job-options
