### ISSUE TITLE
Scheduler stops after Redis reconnect

### ISSUE THREAD

**Issue by iamnafets** [taskforcesh/bullmq#1181]
Similar to #648 , schedulers stop and don't restart after redis failures. Can repro by setting up a scheduler with a 1 minute repeatable job, killing the redis instance behind it, waiting a moment, restarting Redis, and noting that the repeatable jobs are waiting for a date in the past to run. Workaround seems similar -- add a daemon process that looks for schedulers that aren't running and kicks them off.

```
    setInterval(() => {
        if(!metaQueueScheduler.isRunning()) {
            console.log('Restarting metaQueueScheduler');

            /* tslint:disable-next-line:no-floating-promises */
            metaQueueScheduler.run().catch(() => {
                console.log('Could not restart metaQueueScheduler')
            }).then(() => 
                console.log('Successfully restarted metaQueueScheduler')
            );
        }
    }, 10000);
```

Haven't dug into the code but are we failing to trap exceptions in QueueSchedulers?

**Comment by manast** [comment]
Hmm,  in theory, the queue schedulers should continue processing after a reconnection, maybe there is an issue that prevents them to do this. We will look into it.
