### ISSUE TITLE
Feature: Support worker sharding using index keys

### ISSUE THREAD

**Issue by fuchstim** [taskforcesh/bullmq#1182]
In some scenarios it is required for certain subsets of jobs to always be processed on the same worker (e.g. all jobs belonging to the same user should be processed sequentially, but jobs belonging to different users can be processed concurrently).

This is commonly implemented using sharding indexes (sharding keys / concurrency keys), guaranteeing that jobs with the same sharding index will always end up on the same worker (either using local concurrency or multiple worker deployments).

Given BullMQ's support for concurrent processing, I'm surprised to see this feature is missing. If there exists a different, intended solution to this problem kindly let me know. 

Example implementation in JS (for demostration purposes; there are better ways to do this that result in more even distribution):
```javascript
function getWorkerIndex(shardingKey, workerCount) {
  const workerIndex = shardingKey
    .split('')
    .reduce(
      (acc, c) => acc += c.charCodeAt(0), 
      0
    );

  return workerIndex % workerCount;
}
```

**Comment by manast** [comment]
We do not have plans to implement a feature like this. All workers will always process all jobs that are available to be processed at a given time. We do support max concurrency per group though on the Pro version:  https://docs.bullmq.io/bullmq-pro/groups/concurrency
