### ISSUE TITLE
Reuse postgres connection

### ISSUE THREAD

**Issue by ldemesla** [taskforcesh/bullmq#1187]
I have a worker running that make call to a Postgres database.

 Even though I'm initializing the connection to the database outside of the worker (with knex in a singleton),  the number of connection are going to the roof when there is a lot of activity (up to 20 instead of 2 : One for my main app and one for the worker)

**Comment by manast** [comment]
Please write a minimal use case and show us if there is any issue in bullmq that we can solve.

**Comment by wenq1** [comment]
Postgres? I don’t think Postgres is relevant in bullmq context.
