### ISSUE TITLE
QueueScheduler takes a long time to add a task

### ISSUE THREAD

**Issue by seawatts** [taskforcesh/bullmq#120]
When trying to add a scheduled job it takes a while for the actual job to be picked up and processed. It seems to hang at the `queue.add` line. Am I doing something wrong here?

```ts
// test.ts

import { Worker, Queue, QueueScheduler, QueueEvents } from 'bullmq';

(async () => {

  const queueName = `test-queue-1`;
  const queue = new Queue(queueName);
  const queueEvents = new QueueEvents(queueName)
  const queueScheduler = new QueueScheduler(queueName)

  const worker = new Worker(queueName, () => console.log('processed'));

  console.log('about to add job');

  await queue.add('hi', {
    repeat: {
      every:10000,
      startDate: new Date(),
    },
  });

  console.log('added job');

  await new Promise(resolve => queueEvents.on('completed', resolve));

  await worker.close();
  await queue.close();
  await queueEvents.close();
  await queueScheduler.close();
})();
```

```
$ tsc
$ node dist/test.js

about to add job
// here is where it waits
added job
processed
```

**Comment by manast** [comment]
and if you add a second one?  Consider that queues perform some initialization that can take some time depending on your redis instance.

**Comment by seawatts** [comment]
Add a second job? Same thing happens, it waits.

When I run a normal (non scheduled) job it runs immediately.

**Comment by manast** [comment]
what I mean is that when you add the first job, the queue waits for initialisation, but when you add the second one then initialisation is done and it works as fast as it gets.
Btw, I run the test above and it is working perfectly without any delays.

**Comment by manast** [comment]
a hint for debugging is to use ```redis-cli monitor```  it will how you the redis commands, maybe you can see if some command is taking a lot of time to execute.

**Comment by seawatts** [comment]
> what I mean is that when you add the first job, the queue waits for initialisation, but when you add the second one then initialisation is done and it works as fast as it gets.
> Btw, I run the test above and it is working perfectly without any delays.

I tried to add two and it still does the same thing. 

> a hint for debugging is to use redis-cli monitor it will how you the redis commands, maybe you can see if some command is taking a lot of time to execute.

I ran the monitor and didn't see anything suspicious 

I'm also running redis in a docker image
And I am running this code within a jest test

**Comment by manast** [comment]
so it must be something with Jest then?

**Comment by seawatts** [comment]
@manast Yeah it sounds like it. 🤔

**Comment by manast** [comment]
as a sanity check,  could you just run the same test using mocha to see if there is any difference?

**Comment by willoughby** [comment]
Sounds related to #174

**Comment by manast** [comment]
Will close then, re-open if still there or more insights are shared.
