### ISSUE TITLE
Missing lock for job error

### ISSUE THREAD

**Issue by C0rellana** [taskforcesh/bullmq#1202]
Hi, I have a problem,
I had recently created a flow with **bullmq**, but as of today I get the following error. For any job (the job takes 10 seconds).

```
Error: Missing lock for job 5ef6f494-2ed5-4121-9de0-244c8953dbe5. failed
|     at Function.finishedErrors (/var/www/node_modules/bullmq/src/classes/scripts.ts:353:16)
|     at Job.moveToFailed (/var/www/node_modules/bullmq/src/classes/job.ts:518:21)
|     at processTicksAndRejections (node:internal/process/task_queues:96:5)
|     at handleFailed (/var/www/node_modules/bullmq/src/classes/worker.ts:586:9)
|     at Worker.retryIfFailed (/var/www/node_modules/bullmq/src/classes/worker.ts:730:16)
```

some recent change that can cause this problem? 

I want to make it clear that no modifications have been made and this worked a week ago. Please help.

Thanks you!

**Comment by manast** [comment]
If the problem is consistent for all 10+ jobs, can you provide a test case that reproduces it?

**Comment by C0rellana** [comment]
I have fixed the problem by clearing the **redis** data (**FLUSHALL, FLUSHDB**), maybe it was a cache or version conflict? Thank you very much anyway!
