### ISSUE TITLE
Confusion Regarding Graceful Shutdown of Queue, Worker, and QueueScehduler

### ISSUE THREAD

**Issue by Trystan-C** [taskforcesh/bullmq#1205]
When unit testing with the BullMQ `Queue`, `Worker`, and `QueueScheduler` classes, I encounter `Error: Connection is closed` errors. It's unclear to me if these errors are expected, or if there is a graceful way to close these resources.

**Demo Code:**
```typescript
import { ConnectionOptions, Queue, QueueScheduler, Worker } from "bullmq";

describe.only("Redis Connection Issue Demo", () => {
    describe("closing the 'QueueScheduler'", () => {
        it("emits an unexpected 'Connection is closed' error", async function() {
            this.timeout(10_000);
            const queueName = "TheQueue";

            const queue = new Queue(queueName, {
                defaultJobOptions: {
                    removeOnComplete: true,
                    removeOnFail: true,
                },
                connection: redisConnectionOptions(),
            });

            const worker = new Worker(
                queueName,
                async () => {},
                {
                    concurrency: 1,
                    lockDuration: 30_000,
                    connection: redisConnectionOptions(),
                },
            );

            const scheduler = new QueueScheduler(queueName, {
                maxStalledCount: 3,
                stalledInterval: 30_000,
                connection: redisConnectionOptions(),
            });

            await queue.waitUntilReady();
            await worker.waitUntilReady();
            await scheduler.waitUntilReady();

            await queue.add(queueName, {});
            await new Promise<void>((resolve) => setTimeout(resolve, 5_000));

            await queue.close();
            await worker.close();
            await scheduler.close();
        });

        function redisConnectionOptions(): ConnectionOptions {
            return {
                host: "localhost",
                port: 6379,
                maxRetriesPerRequest: null,
                enableReadyCheck: false,
            };
        }
    });
});
```

**Demo Console Output:**
```
Redis Connection Issue Demo
    closing the 'QueueScheduler'
Error: Connection is closed.
    at RedisConnection.handleClientClose (/Users/.../node_modules/bullmq/src/classes/redis-connection.ts:86:26)
    at Redis.emit (events.js:314:20)
    at Redis.EventEmitter.emit (domain.js:483:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Error: Connection is closed.
    at RedisConnection.handleClientClose (/Users/.../node_modules/bullmq/src/classes/redis-connection.ts:86:26)
    at Redis.emit (events.js:314:20)
    at Redis.EventEmitter.emit (domain.js:483:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
      ✔ emits an unexpected 'Connection is closed' error (5072ms)
```

**Dependency Versions:**
* `node`: `12.22.7`
* `npm`: `8.7.0`
* `mocha`: `9.2.2`
* `bullmq`: `1.80.4`
* `redis`: `latest` (through `docker`)

Is there a way to prevent these `Connection is closed` errors?

**Comment by tatejones** [comment]
I am also seeing this behaviour.  The worker is listening on the error event and performing a console.error
https://github.com/taskforcesh/bullmq/blob/7a3206fe97cf801db4042cfe96a912c695037916/src/classes/worker.ts#L226
This line is providing no value.   Why a 'close' event is emitting an error is another issue.

In redis-connection.js

        this.handleClientClose = () => {
            this.emit('error', new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
        };

**Comment by ericellb** [comment]
I'm having the exact same issue on my end. Everything works as intended, however when attempting a graceful shutdown of the Queue and QueueSchedule I get this message also.

It seems like this shouldn't be throwing an error. I would imagine the intention would be to simply log that the close happened, but definitely should not be throwing an error in the case.

Running bullmq 1.80.4

**Comment by manast** [comment]
@tolgap Can you provide a simple test that reproduces it please?

**Comment by gerzson98** [comment]
I have ran in this issue during some performance testing. For me, it was superset running out of memory (I used 'gevent' worker class with multiple workers). It needed at most 1020MB of memory, and if I provided 1000, it almost ran fine, but closed some connections when the load arrived. Then worked fine again. Not sure if this is the same issue, but helped for us at least.
