### ISSUE TITLE
can I use job id on regular jobs to prevent duplicates  ? 

### ISSUE THREAD

**Issue by arkhamRejek** [taskforcesh/bullmq#121]
Long story short i have an app that publishes messages services. 

One of the services is load balanced so the message gets published to both instances so it's creating a duplicate job with a shared redis connection. 

My question is can i use jobId in the same way as repeatable jobs to prevent double processing of the same job ?

**Comment by arkhamRejek** [comment]
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

I see this in the docs, 

> // If you use this option, it is up to you to ensure the
  // jobId is unique. If you attempt to add a job with an id that
  // already exists, it will not be added.

Just making sure this holds true not just for repeated jobs

**Comment by manast** [comment]
Providing the jobId is allowed precisely to implement that kind of behaviour, i.e. to avoid job duplicates.

**Comment by arkhamRejek** [comment]
@manast this is one of the most well thought out libraries i've ever worked with. Please let me know if i can contribute to the docs or something. This work is great
