### ISSUE TITLE
[BullMQ Pro]: ERR Error running script (call to f_215bf405a5a0a694dae5966a9cd8b65f306174b5)

### ISSUE THREAD

**Issue by slavivanov** [taskforcesh/bullmq#1217]
Hello, we are migrating to BullMQ Pro, but we are seeing the following error when executing jobs: 
```
ReplyError: ERR Error running script (call to f_215bf405a5a0a694dae5966a9cd8b65f306174b5): @user_script:360: WRONGTYPE Operation against a key holding the wrong kind of value
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```

The jobs were created with the non-Pro version.
I'm unsure how to figure out which script is behind the hash above.
Here is the JSON dump of one such job:
https://gist.github.com/slavivanov/70e774ec115f5d0f69ec8c73f609cbf5

Another question: What will happen with jobs that have a Group assigned but are due to be processed by non-Pro workers (as we rolled back to non-Pro BullMQ)?

Version of @taskforcesh/bullmq-pro: 1.4.0

**Comment by manast** [comment]
@slavivanov you have hit this same issue: https://github.com/taskforcesh/bullmq/issues/1207
It is a small change on the "stalled" set, it is not a zset, but the latest version of bullmq pro should not raise this error as long as all your workers are pro workers and not mixed with standard bullmq workers.

**Comment by manast** [comment]
> Another question: What will happen with jobs that have a Group assigned but are due to be processed by non-Pro workers (as we rolled back to non-Pro BullMQ)?

They will be ignored, and just wait for ever in their respective groups.

**Comment by manast** [comment]
The last version is 2.0.2.

**Comment by slavivanov** [comment]
I swear I searched for this :D
Thank you for the update, is there a Changelog for the Pro version to avoid any issues from migrating to 2.0.2?

**Comment by slavivanov** [comment]
So, unfortunately, upgrading to 2.0.2 didn't fix the issue for us.
We drained all workers, updated to 2.0.2, and started the workers again. Jobs were stuck in "Active" with the following error:
```
ReplyError: ERR Error running script (call to f_dde527315aebb3334116ee52181655304a726369): @user_script:363: WRONGTYPE Operation against a key holding the wrong kind of value
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```
Is there a safe way to reset the stalled set manually?

**Comment by slavivanov** [comment]
It turns out the QueueScheduler that we were using wasn't the Pro version.
After moving to QueueSchedulerPro (and deleting the stalled set, for good measure), things are back on track.
Thanks for your help!
