### ISSUE TITLE
No event fired when Job added to Queue with no Worker

### ISSUE THREAD

**Issue by rhinodavid** [taskforcesh/bullmq#122]
Team,

I'm not sure if this is intended behavior or not, but I have a listener on a `QueueEvents` instance and I am trying to execute an event handler when a `Job` is added to the associated `Queue`. If there is a `Worker` instance assigned to the queue then a `waiting` event is fired from the `QueueEvents` instance when a new `Job` is added. However, with no `Worker` assigned, there is no event fired as far as I can tell. I threw the kitchen sink at it and am listening for the following on the `QueueEvents` instance:

```
    "global:waiting",
    "",
    "active",
    "wait",
    "waiting",
    "paused",
    "resumed",
    "active",
    "id",
    "delayed",
    "priority",
    "stalled-check",
    "completed",
    "failed",
    "stalled",
    "repeat",
    "limiter",
    "drained",
    "progress",
    "meta",
    "events",
    "delay"
```

**Comment by manast** [comment]
thats definitively not intended. However I do not understand how having a worker or not can affect it, could you paste a small test case that reproduces this?

**Comment by rhinodavid** [comment]
I don’t really understand either, but I can dig in some and make a little
test.  Q: what event is supposed to be issued when a job is placed in the
queue?

**Comment by rhinodavid** [comment]
Side note... from the example, don't the name of the Queue and the name of the Worker need to match?

If I name them different things, I don't get the event from the QueueEvents when a new job is added.

**Comment by rhinodavid** [comment]
Ok so now.. it seems that the reason it works when the key is set to `client` is because that key isn't valid and the default logic is being invoked.

**Comment by manast** [comment]
if you are able to write a minimal test case that I can run and demonstrates the issue I can debug it myself.

**Comment by andrisi** [comment]
so is there an event that is fired when a job is added?

**Comment by manast** [comment]
@andrisi there is an event called "waiting" that is emitted when the job is added to the waiting list.

**Comment by andrisi** [comment]
Ah, ok. And that is never fired later on. Failed jobs get stalled, but not in the waiting list, right?

**Comment by manast** [comment]
If they are stalled they will go back to the waiting list and emit the "waiting" event again.

**Comment by andrisi** [comment]
Then perhaps an "added" event would be helpful sometimes later on.

**Comment by roggervalf** [comment]
Hey guys, could you please try last version, added event was added xd

**Comment by manast** [comment]
@y-nk please open a new issue with the details of your particular case.
