### ISSUE TITLE
using timers in Worker.close

### ISSUE THREAD

**Issue by Heinan-Phau** [taskforcesh/bullmq#1221]
Hello,

It seems that since version 1.20.0 something has changed and now when I use `worker.close` it uses some kind of timer.
I ask this because when I use `sinon.useFakeTimers` my tests don't end till I release the timer.

I wonder if someone can shed light on this subject, why is it used? is there a way around it that doesn't involve using "force close"?

**Comment by roggervalf** [comment]
Hi @Heinan-Phau, this should be addressed in versión 3.12.1 https://docs.bullmq.io/changelog#3.12.1-2023-05-05. So those timers are used in order to check stalled jobs and locks
