### ISSUE TITLE
Add Bulk Fail Silently

### ISSUE THREAD

**Issue by DanielNetzer** [taskforcesh/bullmq#1222]
It seems like when pushing massive bulks of jobs (over 1K), nothing is pushed into redis at all and it fails silently.

```
    const result = (await multi.exec()) as [null | Error, string][];
    result.forEach((res, index: number) => {
      const [err, id] = res;
      jobInstances[index].id = id;
    });

    return jobInstances;
```
from https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L214 seems to be swallowing the errors.
or any error whatsoever.
if there is some sort of a limitation that might be good to document.
currently I'm slicing to chunks of 50 jobs per push.

**Comment by manast** [comment]
Hello @DanielNetzer. Thank you for reporting this. Yes, I see this code now and it does not look good, we will fix it ASAP.
