### ISSUE TITLE
BullMQ reusing redis connections

### ISSUE THREAD

**Issue by Lord-Jerry** [taskforcesh/bullmq#1236]
I am trying to add logic to re-use Redis connections with bullMQ using [this instruction from the bullMQ docs](https://docs.bullmq.io/bull/patterns/reusing-redis-connections).

I am using the most recent (1.81.1) BullMQ npm version.

I followed the instruction on the docs, to create an object that includes a createClient method.
But I get the following error TS2559.

```Type '{ createClient: (type: string, redisOpts: any); }' has no properties in common with type 'QueueOptions'.```

Code Sample

```
import Redis from 'ioredis'
import { Queue } from 'bullmq'

const sharedRedisClientConnection = new Redis(REDIS_URL as string, redisConfig)
const sharedRedisSubscriberConnection = new Redis(REDIS_URL as string, redisConfig)

const options = {
  createClient: (type?: string) => {
    switch (type) {
      case 'client':
        return sharedRedisClientConnection
      case 'subscriber':
        return sharedRedisSubscriberConnection
      default:
        return new Redis(REDIS_URL as string, redisConfig)
    }
  }
}

const userQueue = new Queue('users', options)
```

node version: v16.13.0
typescript version: v4.5.5

**Comment by manast** [comment]
The documentation you are pointing to is for Bull, not BullMQ. In BullMQ you do not need to use that pattern, just pass directly the redis connection that you want to reuse and if BullMQ can reuse it it will do so automatically:
https://docs.bullmq.io/guide/connections

**Comment by elovin** [comment]
@manast The documentation about reusing connections is on the bullmq docs website: https://docs.bullmq.io/bull/patterns/reusing-redis-connections 
so should this not be removed when it is no longer needed / supported ?

**Comment by RoyNelsonCondor** [comment]
@elovin @manast 
is it no longer need  / supported ?

**Comment by manast** [comment]
@RoyNelsonCondor what is not longer needed / supported?

**Comment by raghavbitqit** [comment]
I want to reuse redis connection in nestjs bullmq and I didn't find about that in their documentation . can anybody please help

**Comment by roggervalf** [comment]
to clarify this topic, https://docs.bullmq.io/bull/patterns/reusing-redis-connections is on the bull section. This part of our documentation is for bull package, legacy version of bullmq. For connections about bullmq you need to use https://docs.bullmq.io/guide/connections

**Comment by roggervalf** [comment]
@raghavbitqit I think you can use https://docs.nestjs.com/techniques/queues#async-configuration and return a redis connection instance
