### ISSUE TITLE
Jobs are always stalling in Redis

### ISSUE THREAD

**Issue by aniinprni** [taskforcesh/bullmq#1249]
Hi, I have integrated bull package for the executing batch of http requests (storing urls as job data). The integration is working fine in my local machine with node js v10.14.2 and redis 5.0. But after deploying to production, the jobs are getting added to queue but never executing. the process function is not at all triggered. what might be cause? 
Note: production we have 2 redis clusters.
Please help me on this. i stagnated for couple of days.
Thank you.

**Comment by manast** [comment]
Are your workers really connected to the production Redis instance? You may also get more insights if you use a dashboard like https://taskforce.sh

**Comment by aniinprni** [comment]
@manast, we have resolved the issue . actually it is the problem with redis master-slave configuration. we have downgraded the redis to standalone server.
