### ISSUE TITLE
Is there event for reaching rateLimit by groupKey?

### ISSUE THREAD

**Issue by fractalawareness** [taskforcesh/bullmq#1265]
We would like to have a statistics about users reaching their rateLimits by groupKey, is it possible to handle such event?

**Comment by manast** [comment]
There is no such an event and it is unlikely we will add it since we have much better groups support on the Pro version and that's where we are putting the effort.

However, I am curious about your use case, why would you need such event?

**Comment by fractalawareness** [comment]
We just gather it as a metric because our limiter rejects job creation requests instead of just delaying them + we can investigate users violating rate limits.
