### ISSUE TITLE
Job delay and jobId

### ISSUE THREAD

**Issue by mravey** [taskforcesh/bullmq#1287]
What happens if a job has both a jobId and a delay and it gets added more than once?
Is the delay pushed back or does it stays the same as the original?
For example if a job with `{jobId: 1, delay: '2 hours'}` is added and one hour later the same job is added again, will the 2 hours delay reset?

**Comment by manast** [comment]
If you add a job with the same job id as an existing job in the queue the new job gets ignored.

**Comment by mravey** [comment]
Ok thank you.
