### ISSUE TITLE
BaseJobOptions is missing timeout property in v1.86.2

### ISSUE THREAD

**Issue by david-sykora** [taskforcesh/bullmq#1289]
In [v1.86.2](https://github.com/taskforcesh/bullmq/commit/cdd2a20c2c4ca47042ecd1da525ecb72941e4910) has been removed timeout property from [BaseJobOptions](https://github.com/taskforcesh/bullmq/blob/master/src/interfaces/jobs-options.ts) interface. Is that intended? The property is still [referred](https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.jobsoptions.timeout.md) on API gitbook. Thanks a lot!

**Comment by cchepeau-mwb** [comment]
Question, how can we define timeout then? On the queue options directly?

**Comment by manast** [comment]
A proper timeout that cancels a job is only supported when using observables instead of promises in the worker, and this function is only available on the Pro version https://docs.bullmq.io/bullmq-pro/observables
