### ISSUE TITLE
Queue Scheduler doesn't close its redis client

### ISSUE THREAD

**Issue by dor272** [taskforcesh/bullmq#1298]
Hi,
I have a class wrapping both a queue and it's queue scheduler.
the code looks something like that:

```
    constructor({
        queueName, queueOptions, redisOptions,
    }: QueueMessengerOptions) {
        super(redisOptions);
        this.queueName = queueName;
        this.queue = new Queue(this.queueName, { ...queueOptions, connection: this.redisClient });
        this.scheduler = new QueueScheduler(this.queueName, { connection: this.redisClient.duplicate() });
    }


    async close() {
        await Promise.all([
            this.queue.close(),
            this.scheduler.close(),
        ]);  
        return super.close();
    }
```

Since the scheduler requires a dedicated redis connection I duplicate the redisClient from `super`.
But when I close the `scheduler` the redis client is still connected. Am I supposed to manage that connection outside the scheduler?

I tried it on the latest version of bullmq - `1.86.4`

Thanks.

**Comment by manast** [comment]
Neither the Queue or the QueueScheduler takes ownership of the Redis connection if you pass a Redis client, so you need to close the connection yourself. In the QueueScheduler case, you do not need to perform a duplicate, this is done automatically by the QueueScheduler if needed, and will clean up any new connections it creates when you close it.
