### ISSUE TITLE
RemoveOnComplete: [number] per job, not supported or not working?

### ISSUE THREAD

**Issue by augusto-joecoffee** [taskforcesh/bullmq#1299]
Hello! 
Wondering if this is not supported/bugged or if i'm missing something on my implementation.

Basically i'm trying to only keep 1 completed repeatable job per job  type.

Let's say i have the following repeatable jobs: 
- Cron 1
- Cron 2 

I'm attempting to keep on my completed list only the last time Cron 1 and Cron 2 ran.

I'm attempting this by passing `removeOnComplete: 1` when enqueuing a repeatable job.

```
 await queue.add('cron1', jobData, { removeOnComplete: 1 });
```

The problem i'm having is that when `cron1` runs it will clear the whole completed list and only leave the last `cron1`.
All other jobs are removed, It would seem that `removeOnComplete` is being set for the whole queue and not to this specific job.

Is this working as expected?

thanks!

**Comment by roggervalf** [comment]
hi @augusto-joecoffee, you are right, by design it is being set for the whole queue, not for specific job

**Comment by augusto-joecoffee** [comment]
Ok, thank you!
Wouldn't mind having that feature in the future 😉 

Closing!
