### ISSUE TITLE
Rate limiting and backoff strategy

### ISSUE THREAD

**Issue by LosTigeros** [taskforcesh/bullmq#1302]
Hey. I've noticed that if I set:
```typescript
limiter: {
  max: 2,
  duration: 1000
}
```
in the worker options, and
```typescript
defaultJobOptions: {
  backoff: {
    type: "fixed",
    delay: 1000 * 60 * 5
  }
}
```
in the queue options, then there are only 2 jobs running every 5 minutes.

I would like to have 2 jobs running every 1 second instead. In case a job fails, it should be delayed by 5 minutes.
Is it possible for the backoff strategy to apply only if the job has failed at least once and not when it was rate limited?

**Comment by manast** [comment]
The backoff strategy is only applied to failed jobs. So the behaviour that you are describing is incorrect. Can you provide a complete test snippet that shows the jobs running every 5 minutes instead of 2 per second?

**Comment by LosTigeros** [comment]
Here it is:
https://github.com/LosTigeros/bullmq-small-example

**Comment by manast** [comment]
AFAIC in the log the jobs are indeed running 2 every second, aren't they not?

**Comment by manast** [comment]
Now, the order of rate limited jobs is not guaranteed, it is only best effort. Is the order important for you?

**Comment by LosTigeros** [comment]
Check my log and their time, looks like they are not being promoted, only 2 first are processed right after they were added.

**Comment by manast** [comment]
ah ok, got it, I was too quick parsing the timestamps. They process every 30 seconds, this is because you are lacking a QueueScheduler instance to take care of the delayed jobs properly: https://docs.bullmq.io/guide/queuescheduler

**Comment by LosTigeros** [comment]
Oh. I'm sorry, I didn't notice that. It's clearly my fault...
