### ISSUE TITLE
Passing Set in job data param results in empty object

### ISSUE THREAD

**Issue by chaipedada** [taskforcesh/bullmq#1303]
`await sendQueue.add(
    jobID,
    {
      stringSet: testSet
    },
    { delay: delay, jobId: jobID }
  );`
  where testSet is Set<string>. Logging the job.data.stringSet in the processor shows an empty object `{}`

**Comment by roggervalf** [comment]
hi @chaipedada, could you please provide us a test case to replicate this

**Comment by manast** [comment]
@chaipedada you can only pass JSON serializable data, if testSet is a set, as it is not JSON serializable it will not work.
