### ISSUE TITLE
Multiple repeatable jobs scheduled to run at the same time but only one per minute is processed.

### ISSUE THREAD

**Issue by augusto-joecoffee** [taskforcesh/bullmq#1311]
Hello, 
I'm having an issue with repeatable jobs, not sure if it's a bug or not.

If I schedule multiple repeatable jobs to run at the same time.
Only one is being picked up per minute.

Let's say I schedule 5 jobs at 00:00:00 hours.

Job 1 will be picked up at 00:00:00 hours
Job 2 will be picked up at 00:01:00 hours
Job 3 will be picked up at 00:02:00 hours
Job 4 will be picked up at 00:03:00 hours
Job 5 will be picked up at 00:04:00 hours

I do not have this issue with delayed jobs
if I enqueue those same jobs with the `delay` option, they are all picked up and moved to the active queue at the same time.

All I have in the queue is those jobs, nothing else, and I have more than 5 workers.

Can you provide some guidance on this?

thanks!

**Comment by manast** [comment]
Can you write some example code? you need to provide either a different jobId or name so that BullMQ considers the repeatable jobs different from each other, otherwise is as if you are adding the same job several times so only the first one is considered.

**Comment by augusto-joecoffee** [comment]
Thanks @manast for the reply.
I believe  I'm indeed setting unique Ids and names fro the jobs.
I'll double check and create an example repo and update this issue soon.

thanks!

**Comment by augusto-joecoffee** [comment]
It was an issue with the rateLimiter I had implemented, for some reason crons with the same pattern where bieng rate limited to 1.
Removing the limiter from the worker solved it
