### ISSUE TITLE
UnrecoverableError in sandboxed processors

### ISSUE THREAD

**Issue by plus-** [taskforcesh/bullmq#1317]
It appears UnrecoverableError do not prevent new attempts from being made for sandboxed processors.

We've tested in a simple unit test and while it work for normal processors, sandboxed processors are retried.

**Comment by roggervalf** [comment]
hi @plus-, we had a test case that covers this case https://github.com/taskforcesh/bullmq/blob/master/tests/test_sandboxed_process.ts#L176-L220, could you please take a look and let us know if it works for you

**Comment by plus-** [comment]
Yes I've seen that test and it works indeed,

However I still have issue in my implementation, I've set up a [minimal repo](https://github.com/plus-/bullmq-unrecoverable-error) demonstrating the problem. You can see it the difference of behavior between normal and sandboxed processor test.

**Comment by plus-** [comment]
This is what I'm seeing in debug:

![Capture d’écran 2022-07-13 à 10 03 16](https://user-images.githubusercontent.com/841776/178682865-623311e0-8338-4847-9172-15d5b8c04171.png)

**Comment by plus-** [comment]
It seems the problem is located in sandbox.ts, creating an error and assigning the message value doesn't work with instanceof condition used in job.ts: https://github.com/taskforcesh/bullmq/blob/master/src/classes/sandbox.ts#L28-L29

You can see unit test [here](https://github.com/plus-/bullmq-unrecoverable-error/blob/master/unrecoverable.test.ts#L138-L147)

**Comment by roggervalf** [comment]
Thanks @plus- I could replicate it, you can try versión 1.86.7 with the fix

**Comment by plus-** [comment]
I can confirm it's working now
