### ISSUE TITLE
RepeatOptions - is 'endDate' and 'tz' supported?  

### ISSUE THREAD

**Issue by valeeum** [taskforcesh/bullmq#1327]
Curious if `endDate` and `tz` properties are officially supported for repeatable jobs.  I saw references to it in issues and in tests/test_repeat.ts but not in interfaces/repeat-options.ts.

**Comment by valeeum** [comment]
nevermind, I see RepeatOptions extends ParserOptions from https://www.npmjs.com/package/cron-parser.  for anyone else curious, the signature for ParserOptions can be viewed here - https://github.com/harrisiirak/cron-parser/blob/master/types/common.d.ts

**Comment by manast** [comment]
Yeah, for some reason typedoc does not fetch the type information from ParerOptions https://api.docs.bullmq.io/interfaces/RepeatOptions.html
