### ISSUE TITLE
Add "log" event to Queue and Worker

### ISSUE THREAD

**Issue by valeeum** [taskforcesh/bullmq#1328]
Would be a nice feature to be able to listen to "log" events generated in the worker processor.  

myWorker.on('log', row => {
  // do something with logged row
});

**Comment by manast** [comment]
What would be the use case for that? you can use "progress" for sending data from the processor to some listener already: https://docs.bullmq.io/guide/workers#progress

**Comment by valeeum** [comment]
thanks for your input!   i was looking for a (lazy) way for enabling my application logger to log items that were logged inside my sandboxed processor.   the "progress" approach can work.
