### ISSUE TITLE
Deprecation warning maxRetriesPerRequest

### ISSUE THREAD

**Issue by alko89** [taskforcesh/bullmq#1331]
Setting up a new BullMQ is throwing a deprecation warning

```
BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null. On the next versions having this settings will throw an exception
```

Checking the code it seems `maxRetriesPerRequest` is set to 20 by default. I'm reusing the Redis instance from the app. I did find some issues referencing this, but none specific for this warning, so I'm just creating one so that its documented.

```Typescript
    const client = new Redis(options.url);

    new Worker(
      BullQueues.USAGE_CREATE,
      async (job) => this.handleUsageCreate(job),
      {
        limiter: {
          max: 100,
          duration: 1000,
        },
        connection: client,
      },
    );
```

Setting `maxRetriesPerRequest` to null removes the warning.

I'm using bullmq 1.86.6 and ioredis 5.2.0

**Comment by GeoffreyPlitt** [comment]
Seeing this myself.

**Comment by manast** [comment]
You are creating an external Redis connection that does not conform with the recommended settings, so you get a warning, this is not an issue, it is to save yourself from future issues: https://docs.bullmq.io/guide/going-to-production#maxretriesperrequest
