### ISSUE TITLE
Support for ioredis v5

### ISSUE THREAD

**Issue by kaname-png** [taskforcesh/bullmq#1332]
Are there plans for bullmq to support ioredis v5?

**Comment by kaname-png** [comment]
The ability to pass a username in the connection URI, also not rely on @types/ioredis types and compatibility with redis v7.

**Comment by soulchild** [comment]
@manast I just happened to notice that the latest bullmq version still contains `@types/redis@4` in the [devDependencies](https://github.com/taskforcesh/bullmq/blob/master/package.json#L71), but ioredis@5 provides its own types now. I had some problems with that combination in the past and was just wondering whether it'd make sense to just remove `@types/redis` altogether? Or is there a specific reason why the types are still included?
