### ISSUE TITLE
Last Job Failed In Flow Results in Flow Parent not being called

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq#1333]
I was doing some testing and found that if you create a flow 

```
import { FlowProducer } from 'bullmq';

// A FlowProducer constructor takes an optional "connection"
// object otherwise it connects to a local redis instance.
const flowProducer = new FlowProducer();

const flow = await flowProducer.add({
  name: 'renovate-interior',
  queueName: 'renovate',
  children: [
    { name: 'paint', data: { place: 'ceiling' }, queueName: 'steps' },
  ],
});
```

And the last job `ceiling`  (in this case the only job), fails the parent will not be called.

I would at least expect the parent to called `failed`

**Comment by lukepolo** [comment]
as a temp fix for me i just added

```
.on("failed", async (job: Job, error) => {

        if(job.parent) {
          await job.remove();
        }
 
 ```

**Comment by manast** [comment]
The problem is, sometimes a child fails but you want to retry it manually after fixing the reason for failure, so you would probably want to wait before failing the parent.

**Comment by lukepolo** [comment]
I could see that , but not when you have millions of jobs , seems more like a `dev` type of thing rather than production thing.

**Comment by manast** [comment]
It could be a new option "failParentOnChild" or something like that, and in that case the parent would fail as soon as any of the children fails, however it would be not possible to skip processing the rest of the children even if the parent has failed. What do you think @roggervalf ?

**Comment by rosslavery** [comment]
This is a similar use-case to what we'd like.

Imagine a parent with 2 million children. There may be an acceptable number of failures that we'd like to continue running the parent, or we may want it to fail and also fail the parent.

Although @manast note about not being able to stop processing the remaining children isn't ideal for our use case 🤔

**Comment by lukepolo** [comment]
@rosslavery Yah same here , failures are `ok`  (internet goes out for 10 minutes or something odd)

**Comment by roggervalf** [comment]
> It could be a new option "failParentOnChild" or something like that, and in that case the parent would fail as soon as any of the children fails, however it would be not possible to skip processing the rest of the children even if the parent has failed. What do you think @roggervalf ?

it sounds good to me, this is still in my list
