### ISSUE TITLE
Cannot get children jobs of flow when using FlowProducer with rate limiting

### ISSUE THREAD

**Issue by venilinrm** [taskforcesh/bullmq#1334]
What I want to achieve:

I want to use FlowProducer to start flows with 1 level depth of children with rate limiting on the children queue worker by specific key (in my case by some customer id) and be able to get the flow later to check its status (parent & children).

What I actually get:
When I use getFlow() to get the parent job with its children, the method returns the parent job and array of undefined for each child. So if the job has five children, the array has five undefined elements.

Hint: From what have I debugged it seems like when using rate limiter an extra string with the rate limiting key is appended to the job key so it's something like **bull:queue-name:job-id:ratelimmitkey**. And when I fire the getFlow method of FlowProducer it does not take into account this extra appended rate limiting key and therefore it does not retrieve the children jobs of the flow.

Here is a reproducing the above mentioned example:
```
import { FlowProducer, Worker, QueueScheduler, Queue } from "bullmq";

const parentQueue = new Queue("parentQueue");
const childQueue = new Queue("childQueue");

const parentQueueScheduler = new QueueScheduler(parentQueue.name);
const childQueueScheduler = new QueueScheduler(childQueue.name);

const flowProducer = new FlowProducer();

const parentFlowJobId = "some-uuid";

async function addJobs() {
  await flowProducer.add(
    {
      queueName: parentQueue.name,
      name: "do-something",
      data: {
        test: "data",
      },
      opts: { jobId: parentFlowJobId },
      children: [
        {
          queueName: childQueue.name,
          name: "do-something-else",
          data: {
            test: "child-data",
            customerKey: "rate-limmiter-key",
          },
        },
        {
          queueName: childQueue.name,
          name: "do-something-else",
          data: {
            test: "child-data",
            customerKey: "rate-limmiter-key",
          },
        },
        {
          queueName: childQueue.name,
          name: "do-something-else",
          data: {
            test: "child-data",
            customerKey: "rate-limmiter-key",
          },
        },
        {
          queueName: childQueue.name,
          name: "do-something-else",
          data: {
            test: "child-data",
            customerKey: "rate-limmiter-key",
          },
        },
        {
          queueName: childQueue.name,
          name: "do-something-else",
          data: {
            test: "child-data",
            customerKey: "rate-limmiter-key",
          },
        },
      ],
    },
    {
      queuesOptions: {
        [childQueue.name]: {
          limiter: { groupKey: "customerKey" },
        },
      },
    }
  );
}

await addJobs();

const parentQueueWorker = new Worker(parentQueue.name, async (job) => {
  console.log(job.data);
});
const childQueueWorker = new Worker(
  childQueue.name,
  async (job) => {
    console.log(job.data);
  },
  { limiter: { max: 1, duration: 1000, groupKey: "customerKey" } }
);
export {};

const flow = await flowProducer.getFlow({
  queueName: parentQueue.name,
  id: parentFlowJobId,
});

// Children array of undefined
console.log(flow);
```

**Comment by manast** [comment]
> Hint: From what have I debugged it seems like when using rate limiter an extra string with the rate limiting key is appended to the job key so it's something like **bull:queue-name:job-id:ratelimmitkey**. And when I fire the getFlow method of FlowProducer it does not take into account this extra appended rate limiting key and therefore it does not retrieve the children jobs of the flow.

That's not how it works. First of all it is not the job-id but the groupKey, secondly it does not replace the job's key, this is an additional key that is used to determine if a group has been rate limited or not.

I could not spot any obvious error in the code above, I would need to run a test.

**Comment by manast** [comment]
Oh, actually you are right about the name of the job key, I was confused by how groups works in the Pro version.
To clarify, when using groupKeys, a new jobId is generated based on the groupKey for every added job, but other than that the job key in Redis should follow the same structure as any other job. It is possible that when using Flows we are missing somewhere to use the correct job key.
