### ISSUE TITLE
Error: Missing lock for job X. failed

### ISSUE THREAD

**Issue by docelic** [taskforcesh/bullmq#1343]
I have an issue manifesting as `Error: Missing lock for job X. failed` and it appears to be similar if not identical to  #1115.

It is in code that uses parent-children jobs (steps pattern), without using repeatable jobs or flows.
It triggers as soon as `parent: { ... }` is passed in child job's add() options, regardless of whether `parentJob.moveToWaitingChildren()` is called.

Version of bullmq in use is latest (1.86.10).

Excerpts from code:

```
/*
  Two queues:
  - Parent jobs in queueOne with processorOne() function
  - Child jobs in queueTwo with processorTwo() function
*/

queueOne.add( 'name', { ...args... })

...

async function processorOne(job, token) {
  await queueTwo.add(job.name, job.data,
    {
      // Error triggers when this option is present:
      parent: {
        id: job.id,
        queue: 'bull:queueOne'
      }
    });
  await job.moveToWaitingChildren(token);
}


async function processorTwo(job, token) {
  // ...
}
```

Backtrace:
```
Error: Missing lock for job 10. delayed
    at Scripts.finishedErrors (/node_modules/bullmq/dist/cjs/classes/scripts.js:205:24)
    at Job.moveToFailed (/node_modules/bullmq/dist/cjs/classes/job.js:340:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleFailed (/node_modules/bullmq/dist/cjs/classes/worker.js:320:17)
    at async Worker.retryIfFailed (/node_modules/bullmq/dist/cjs/classes/worker.js:455:24)
    at async Worker.run (/node_modules/bullmq/dist/cjs/classes/worker.js:140:46)
```
(Says "delayed" above because of the configured retries. But after that reaches max count, it gets moved to failed.)

Any hints/comments would be appreciated, thanks.

**Comment by lukepolo** [comment]
I get this a ton as well, 
`
 premise:BullMQQueue <5> worker error: Missing lock for job repeat:29fe3c39e8f782d803b105955178efeb:1659384600000. delayed +0ms
`

**Comment by manast** [comment]
@docelic my understanding on what is going on here is that, since the job is moved back to "waitingChildren" inside the processor, when the processor itself finalizes it tries to complete the job but it cannot do it since the job is not active anymore and neither there is a lock on the job. 

I am trying to come up with some design that could solve a requirement like this (manually moving the current processed job to a different status) without being hackish and without breaking backwards compatibility. 

One idea that comes to mind is the following: a worker is by default configured to call "moveToCompleted" as soon as the processor callback completes (unless some error has been thrown inside the function). So maybe, what we could do is add a new option, something like "autoComplete", which by default is "true", but that can be set to "false". In this case the jobs will never complete unless we explicitly call ```job.moveToComplete(...)```, and that would allow use-cases such as the one you are showing in this issue. 

What do you think?

**Comment by docelic** [comment]
Hey @manast thanks for the reply. If someone would set `autoComplete: false`, at which point in code later would they be able to call `job.moveToCompleted` (would it have to be done from a hook, or it'd be possible in any of the processor functions??

**Comment by manast** [comment]
You will need to call it from inside the processor, the same way you called ```job.moveToWaitingChildren(token)``` in your code above.

**Comment by docelic** [comment]
In my use case I have a parent task which expands into a variable number of child jobs. So it's not exactly the steps pattern because there doesn't exist a progression of states - it is just a parent job that needs to wait until all children (which it creates dynamically) are completed.

Wouldn't in such a use case be hard to know when/which child job needs to move the parent to completed state? (Asking this under the assumption that you were referring to calling `job.moveToWaitingChildren(token)` in the child's processor.)

**Comment by docelic** [comment]
But I guess that BullMQ's internals do know when all children tasks have been completed. How about adding two config options:

1. `autoComplete: <bool>`, like you proposed as the first step (could be useful in its own right!), and then
2. `autoCompleteAfterAllChildren: <bool>` which would auto-complete parent tasks when all children are done?

**Comment by docelic** [comment]
Heya, any new thoughts on this?

**Comment by docelic** [comment]
Heya, do we have any additional toughts on this one, or maybe a suggestion how to work around the issue?

**Comment by manast** [comment]
> 2\. `autoCompleteAfterAllChildren: <bool>` which would auto-complete parent tasks when all children are done?

That is how it works today by default. You create a flow with one parent and X children and when all children complete then the parent job will start processing. Not sure I understand your issue in full.

**Comment by manast** [comment]
So I think you need 3 queues. 1 queue creates a flow where it adds all the children (queue 2) for a certain parent (queue 3).

**Comment by AntiMoron** [comment]
@manast Hi, may I ask what's the best practice for worker tokens?

It seems like the token is related to the Redis lock name, if it's an uuid, will it lose its token in the scenario when the server restart? which results in the lock never unlock. (Don't know if I'm getting it right)

**Comment by manast** [comment]
If the server restarts you want to lose the lock as that would signal that the worker has started to process but died before completing, so you would like to start to process the job from the beginning by another worker. So, a UUID would be fine, that's what BullMQ uses internally.
