### ISSUE TITLE
Job.data can be undefined (modify typing)

### ISSUE THREAD

**Issue by maximedupre** [taskforcesh/bullmq#1349]
It appears that `job.data` can be undefined (as well as all the other job attributes as a matter of fact).

This seems to occur momentarily while a job is being deleted.

Take this piece of code:

```
async function getJobsFromQueueAndAndUser(queue, userId) {
  const allJobs = await queue.getJobs();

  return allJobs.filter((j) => j.data.userId === userId); // Cannot read properties of undefined (reading 'data')
}
```

This line: `return allJobs.filter((j) => j.data.userId === userId);` will throw an error if `j.data` does not exist. The `j` object is simply an empty object while the job is being deleted. The typings should reflect this and throw an error at compilation.

**Comment by manast** [comment]
Is it that data does not exist or that data === undefined? it is not really the same thing.

**Comment by maximedupre** [comment]
@manast 

I'm not sure what you mean.

if `j` is `{}`, then `j.data === undefined // true`

**Comment by manast** [comment]
it could also be ```{ data: undefined }```

**Comment by maximedupre** [comment]
@manast 

`j` seems to be `{}` according to my tests.

**Comment by manast** [comment]
The difference is that if your data type is "undefined" which is totally possible when you define your worker, then it is correct. But if the data property is missing altogether then it is incorrect.

**Comment by maximedupre** [comment]
@manast

Whether `data` is missing or `undefined`, it is still not typed correctly 😶

If your point is that `data` should be `undefined` and that also the typing should be updated to reflect that, got it 😁

**Comment by manast** [comment]
But did you define the data generic as undefined when you instantiated the worker? https://api.docs.bullmq.io/classes/Worker.html

**Comment by maximedupre** [comment]
@manast 

I did not. I use an interface I created as the data generic. Somehow `bullmq` should internally consider that the data generic is `D | undefined` (or something like that, I'm not sure if this union type makes sense)

**Comment by manast** [comment]
I do not understand. So data is undefined if you added a job with undefined data. What is wrong with BullMQ in this case?

**Comment by maximedupre** [comment]
@manast 

Let's say I add a job with this data `{ userId: 1 }`, as defined by the interface that I used for the data generic: `interface MyJobData { userId: number }`

And let's take my initial example:

```
async function getJobsFromQueueAndAndUser(queue, userId) {
  const allJobs = await queue.getJobs();

  return allJobs.filter((j) => j.data.userId === userId); // Cannot read properties of undefined (reading 'data')
}
```

`j.data.userId` can throw this error at runtime
> Cannot read properties of undefined (reading 'data')


As I said, `j.data` is undefined in some cases, probably when a job is being deleted. At that point, the job is an empty object (`{ }`). 

Either `bull` should make sure that `job.data` always of the type `D` (and therefore `j` should never be an empty object), or `j.data` should be flagged as optional (`D | undefined`).

Let me know if this makes sense.

**Comment by manast** [comment]
Let's see if I get it. The issue is that according to you data could be undefined, despite the job being added with a defined data? if that is the case it is not a question of typescript types. Can you provide code that reproduces such a case?

**Comment by maximedupre** [comment]
> The issue is that according to you data could be undefined, despite the job being added with a defined data?

That is correct. Not only is `job.data` is undefined (or inexistent), but so are all the other attributes `job`. Printing `job` shows and empty object `{}`. 

Unfortunately, I can't provide a full repro, so I understand if you don't want to spend more time looking at the issue, but here's some more info. As I said, `j` is only an empty object temporarily, for a relatively brief moment. It seems that it is in that state while it is being deleted.

In the following code, `j` can be `{}`:

```
async function getJobsFromQueueAndAndUser(queue, userId) {
  const allJobs = await queue.getJobs();

  return allJobs.filter((j) => j.data.userId === userId); // Cannot read properties of undefined (reading 'data')
}
```

This is most likely because it is being deleted with the following code:

```
export async function deleteRepeatableJob<D, T>(
    queue: Queue<D, T>,
    userId: string,
) {
    const repeatableJob = await getRepeatableJobFromQueueAndUser(queue, userId);

    if (!repeatableJob) return;

    await queue.removeRepeatableByKey(repeatableJob.key);
}

export async function deleteRepeatableJobAndChildren<
    D extends { userId: string },
    T,
>(queue: Queue<D, T>, queueEvents: QueueEvents, userId: string) {
    await deleteRepeatableJob(queue, userId);

    const allJobsCurrentUser = await getJobsFromQueueAndAndUser(queue, userId);

    for (const job of allJobsCurrentUser) {
        if (!job.id) throw new Error('FF');

        await job.waitUntilFinished(queueEvents);

        const isRemoved = await queue.remove(job.id);

        if (!isRemoved) throw new Error('FF');
    }
}
```

Please let me know what you think.

**Comment by manast** [comment]
Basically if there is an issue I need some specific code that reproduces it, otherwise I do not have time to do investigations based on user code.
