### ISSUE TITLE
MaxListenersExceededWarning with Concurrent Queue Instantiation

### ISSUE THREAD

**Issue by bobdercole** [taskforcesh/bullmq#135]
Hi,

My program creates 12 queues concurrently. All of these queues share the same Redis connection. I almost always see the following messages when my program starts:

```
(node:921) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
(node:921) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
(node:921) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
```

Here is a simple example. If you don't see the warnings, try increasing the count:

```typescript
import * as IoRedis from 'ioredis';
import {Queue} from 'bullmq';

const connection = new IoRedis();

for (let count = 0; count < 12; count++) {
	new Queue(count.toString(), {
		'connection': connection
	});
}
```

I can confirm that this only happens with shared connection. I can also confirm that the listener count drops to zero after a second or two.

Am I doing something wrong here? Or is this a bug?

Thanks!

**Comment by manast** [comment]
since listeners are added to the redis connections if you create many queues from the same connection it is to be expected this warning. Its just a warning that I think node would be better of, but in any case it can be safely ignored.

**Comment by bobdercole** [comment]
I see. Thanks for the clarification. Closing.
