### ISSUE TITLE
Timestamp handling

### ISSUE THREAD

**Issue by wenq1** [taskforcesh/bullmq#138]
In bullmqv4, Job.fromJSON () method, job.timestamp is not recovered (in fact commented out). 

````
// job.delay = parseInt(json.delay);
// job.timestamp = parseInt(json.timestamp);
````

This creates a problem for UI when trying to read jobs from IDs. The timestamp will always be set to Date.now () in the constructor, regardless of the timestamp stashed in RedisLayer.

````
this.timestamp = opts.timestamp ? opts.timestamp : Date.now();
````

Sounds like a bug?

**Comment by wenq1** [comment]
Anyone?

**Comment by jamesholcomb** [comment]
Running into this as well.  Have you tried uncommenting?

**Comment by wenq1** [comment]
uncommenting will work.

However I open a thread here so as to discuss the intention of this regression, or if it a feature rather than a regression.

**Comment by wenq1** [comment]
Is @manast still hiding?

**Comment by manast** [comment]
I am a bit confused too why these are out commented, should work to uncommented AFAICS.

**Comment by onehorsetown** [comment]
@manast - Do you want a pull request for un-commenting out those two lines of code?
