### ISSUE TITLE
Get Queue Name for Logging

### ISSUE THREAD

**Issue by bobdercole** [taskforcesh/bullmq#140]
Hi,

I like to use queue events for logging. I find it useful to log the queue name with each event.

In Bull v3 we had access to the queue name. However, it was marked protected in v4.

https://github.com/taskforcesh/bullmq/blob/36726bfb01430af8ec606f36423fc187e4a06fb4/src/classes/queue-base.ts#L11

At the moment I am working around the issue by calling `toKey` with an empty string, since `toKey` happens to contain the queue name.

Would you consider making the queue name publicly readable? Or perhaps there is another way to get the name that I'm overlooking?

Thanks!

**Comment by manast** [comment]
yes, actually I think public is better considering there is no getter for the queue name, no reason to make that property protected/private.
