### ISSUE TITLE
Update function not available when using sandboxed processor

### ISSUE THREAD

**Issue by all43** [taskforcesh/bullmq#1415]
Currently there are no easy way to update the job data inside sandboxed processor script, as update property of the job is not passed to the sandboxed script.
In many scenarios (like job Steps pattern) it is very useful to have update function available.
My guess there was a reason for not passing update (like saving resources or limiting scope), in this case we could have configuration option whether update should be available instantiating Worker.

**Comment by roggervalf** [comment]
hi @all43, please try version 1.91.0. Update method should be supported now
