### ISSUE TITLE
Events Documentation

### ISSUE THREAD

**Issue by Abhishek357** [taskforcesh/bullmq#1418]
Under [Read more](https://docs.bullmq.io/guide/events#read-more) section in Event docs. Wrong URL redirection at Queue Events API Reference. Currently its redirecting to this [link](https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.queueevents.md), according to me it should redirect to this [link](https://api.docs.bullmq.io/interfaces/QueueEventsListener.html)

**Comment by Abhishek357** [comment]
Let me know if this issue is valid, I can open a PR as well.

**Comment by roggervalf** [comment]
Hi @Abhishek357, thanks for submitting this issue. Docs were updated in last commit.
