### ISSUE TITLE
initial delay on repeat

### ISSUE THREAD

**Issue by rogueturnip** [taskforcesh/bullmq#142]
I was wondering, is it possible to do a delay on a repeatable job?

What I'm trying to do is start a repeatable job an hour in the future (or something like that).

Thanks!

**Comment by manast** [comment]
no, it is not possible. But you can create another queue where you add delayed jobs that creates the cron job itself.

**Comment by rogueturnip** [comment]
Thanks.  I took a look at the repeat options interface and see that startDate is available for Cron based items so that might do it for me 

Does endDate work only with Cron or with other repeat configurations?

**Comment by manast** [comment]
endDate works for both cron and every
