### ISSUE TITLE
A better job.getState

### ISSUE THREAD

**Issue by ccollie** [taskforcesh/bullmq#143]
For another project, I've written `lua` code for a more performant `job.getState` (makes a single roundtrip rather than the multiple in the current codebase). I'd contribute a PR for `bull` but I noticed that the tests are commented out

https://github.com/taskforcesh/bullmq/blob/master/src/test/test_job.ts#L347

Any plans to revisit this ?

**Comment by manast** [comment]
not sure if the tests are out-commented because the code is ugly or they do not work. You are welcome to contribute with a better getState, it would be very much appreciated.

**Comment by roggervalf** [comment]
@ccollie the pr was merged, are we safe to close this issue?

**Comment by ccollie** [comment]
> @ccollie the pr was merged, are we safe to close this issue?

Sure, go ahead
