### ISSUE TITLE
No exported member "QueueScheduler"

### ISSUE THREAD

**Issue by murbanowicz** [taskforcesh/bullmq#1432]
Hello,

I am on latest 2.0.1 version.
Docs shows required to use "QueueScheduler" while there is no exported member from the package.
Is something wrong with package or docs are outdated?

**Comment by manast** [comment]
I updated the docs a couple of hours ago, maybe I missed in some place, could you please tell me where if that is the case?

**Comment by itsjinendrajain** [comment]
i am also facing same issues
any update @murbanowicz

**Comment by roggervalf** [comment]
Hi @itsjinendrajain, there is a warning about QueueScheduler in https://docs.bullmq.io/guide/queuescheduler
