### ISSUE TITLE
Config Get maxmemory policy not possible on elasticache

### ISSUE THREAD

**Issue by autarchprinceps** [taskforcesh/bullmq#1437]
On Elasticache you cannot do a Config Get, so the check for noeviction vs volatile-lru always fails and breaks everything.
This is an issue going from 1.91.1 to 2.0.1. I have setup noeviction as policy, but in AWS ElastiCache Parameter Group settings.
Message: Eviction policy is volatile-lru. It should be "noeviction"
Could you provide a method to surpress this check, so we can use version 2?

**Comment by manast** [comment]
Ok. I guess the best, in this case, is to handle the error and in such case just output a warning that the" maxmemory" policy could not be determined. @roggervalf can you look into this?

**Comment by manast** [comment]
Error message could be something along the lines: "maxmemory policy could not be determined, please make sure you are using 'noeviction' to avoid issues"

**Comment by patrickrbc** [comment]
It looks like this issue is preventing all ElastiCache users from updating to BullMQ's latest version. Is there a workaround or does it needs to be fixed here?

Is there anything blocking the fix from #1440?

**Comment by roggervalf** [comment]
hi @patrickrbc, that pr should not address this issue, as it check the maxMemory policy presence and from the description of this issue, maxMemory policy is present but having volatile-lru. I'm wondering if elasticache is not reflecting this value and just showing volatile-lru as default, could someone clarify this behavior?
