### ISSUE TITLE
Is there a release timeline for this project?

### ISSUE THREAD

**Issue by moltar** [taskforcesh/bullmq#144]
Hi,

First of all, I want to say that the new version looks awesome! And a bunch of virtual bonus points for doing it in TypeScript! Hopefully these points will be redeemable for cash :)

I don't mean this to sounds like I am rushing, but I wanted to know if there is a timeline for a stable release?

The reasons I am asking:

 * I'd like to know when I should be checking in on this.
 * And whether I should start building on this now and could beta test with the hope to have it production ready when I am going to production with my project.

Thanks.

**Comment by manast** [comment]
As far as we know, this version is as stable as Bull. However there may be some small things missing, you can check in the issues to see what people have discovered so far.

**Comment by moltar** [comment]
Oh, great, glad to hear that!

I thought that undocumented sections are not implemented yet.

Thanks!
