### ISSUE TITLE
'recommeded to use a minimum Redis version of 6.2.0', orly?

### ISSUE THREAD

**Issue by antirek** [taskforcesh/bullmq#1442]
updated to bullmq@2.0.2
received warning message in console
`````
It is highly recommeded to use a minimum Redis version of 6.2.0
           Current: 6.0.8
`````
I use ioredis@5.2.3
also I check package-lock.json that project doesn't have any deps from redis, how it check and find 6.0.8?

**Comment by antirek** [comment]
read code again and understand ))

**Comment by manast** [comment]
6.0.8 is going to be ok, the issues start with versions lower than 6.0.0.

**Comment by manast** [comment]
@0x7357 I am all for making the messages as clear as possible, but which other Redis version could it be other than the one you are connecting to?🤔
