### ISSUE TITLE
Ability to ignore max-memory policy

### ISSUE THREAD

**Issue by kevcodez** [taskforcesh/bullmq#1443]
I am aware of the possible side-effects that come with a volatile memory policy. However, since other services write in Redis, we cannot simply edit our maxmemory policy for BullMQ to work.

It would be great to be able to ignore the error (i.e. a queue option that only considers it as a warning and does not throw an error) - otherwise, the queue cannot even be constructed.

**Comment by manast** [comment]
Which Redis host does not allow you to configure the memory policy? The problem is that if you do not use the correct policy, there are no guarantees the queue will work properly since stuff like lock keys can be expired without warning.

**Comment by kevcodez** [comment]
@manast It's not a technical limitation in terms of hosting, technically speaking, we could change it. However, other services write a lot of data into Redis and we want to be safe and evict old keys (LRU). So changing this setting would not just impact the BullMQ queue, but all other services, too. We barely ever run into this, however, if we do, a noeviction policy could greatly impact our performance, thus, we can't just flip the switch because of BullMQ processing.

The only solution on our side would be setting up a separate Redis instance for the queue, which I'd like to avoid, at least for the upgrade to V2.

I do understand the possible side-effect and I think throwing an error is a reasonable default behavior - it would just be great to ignore it or have it as a warning only. That would allow us to upgrade to BullMQ V2 and eventually set up a separate Redis for the queue in the future. Otherwise, we'll have to stay on V1 for now.

**Comment by manast** [comment]
If it was a warning only, many users will just ignore the warning, and then when issues arise (always in production on a Friday afternoon), they will file issues in GitHub and complain that there are some strange issues with BullMQ, making everybody lose time. 
If we had a flag to skip this enforcement, then some users will use it "temporarily" just to keep it on forever until issues start to arise (and by then you would have forgotten about this warning), and we will be back in the same situation as above, with new issues and most time wasted...
I fail to see why we would like to allow enabling a ticking bomb, that sooner or later will explode :/

**Comment by manast** [comment]
On a side note, it is ok to stay on 1.9, the whole point of a major version is to introduce breaking changes, and if some breaking change makes it difficult to upgrade then you can postpone it for later...
