### ISSUE TITLE
Can i pause current Job and start new job?

### ISSUE THREAD

**Issue by jackChauT** [taskforcesh/bullmq#145]
Hi all,
For example, 
There are 2 jobs. 1. queue.add('paint', { colour: 'red' });  2. queue.add('paint', { colour: 'blue' });
I would like to pause the running job (1.), then start (2.) Job.
When the 2. is finished, then I resume the 1. Job.

Is it possible? or Is there an existing function to handle it?
Thank you very much.

**Comment by manast** [comment]
It is not currently possible to pause running jobs.
