### ISSUE TITLE
Repeatable jobs do not start at the exact scheduled time after upgrade to v2.0

### ISSUE THREAD

**Issue by nemphys** [taskforcesh/bullmq#1451]
As the title says, after upgrading to v2 (and removing QueueSchedulers), all repeatable jobs start at seemingly random times, but pretty close to the cron schedule (sometimes +- a few seconds, other +- up to 15 minutes).

Please note that I have been using BullMQ for more than 1 year with the exact same configuration and repeatable tasks would always start at the exact scheduled times (to the second).

Is there something I missed in the configuration?

**Comment by manast** [comment]
@nemphys could you please provide a minimal snippet that shows this behaviour?

**Comment by nemphys** [comment]
What kind of snippet? I can give you the logs (jobs are logged to the db with start/end time) that prove the discrepancy, but otherwise I have no idea what to provide.

**Comment by manast** [comment]
I believe in that you get the discrepancy, but in my tests it is accurate so I need another test code that shows that this is not the case so that I can debug it.

**Comment by nemphys** [comment]
The codebase is quite complicated, so it is not possible to send you the actual code. 
We have 2 queues with 1 worker per queue per app instance (totally 12 instances running in 3 different hosts). Jobs are scheduled as repeatable jobs with the following options:
```
{
    repeat: {
        cron: '<some cron schedule>',
        utc: true
    },
    removeOnComplete: true,
    removeOnFail: true
}
```
Jobs are returned properly using getRepeatableJobs() and the next timestamps are correct.
Everything was working fine before the upgrade to v2, so it definitely has something to do with the upgrade.
Maybe you can point into something to test/check?

**Comment by manast** [comment]
Which version of Redis are you using?

**Comment by nemphys** [comment]
6.2.6

**Comment by manast** [comment]
Since I cannot reproduce the issue, I recommend you to downgrade again. If this problem is common then somebody will be able to provide a reproducible test case and we can fix the issue.

**Comment by nemphys** [comment]
OK, will do. I will try to reproduce it in a test environment when I have some time, in case I discover something.

**Comment by Rush** [comment]
We have the same issue. I also see the jobs scheduled to run at specific times to be running at seemingly random times.

Here's the job that is supposed to run every hour but is a total hit & miss:
```
helios1:6379> hgetall prod:cron:repeat:64a8a599e2969da239321b7a7ed5a7c9:1671048000000
 1) "opts"
 2) "{\"prevMillis\":1671048000000,\"timestamp\":1671045934457,\"jobId\":\"repeat:64a8a599e2969da239321b7a7ed5a7c9:1671048000000\",\"repeat\":{\"jobId\":\"cron-commitTeamsBilling\",\"pattern\":\"0 0 * * * *\",\"count\":9},\"delay\":2065543,\"attempts\":0}"
 3) "rjk"
 4) "commitTeamsBilling:cron-commitTeamsBilling:::0 0 * * * *"
 5) "name"
 6) "commitTeamsBilling"
 7) "priority"
 8) "0"
 9) "timestamp"
10) "1671045934457"
11) "data"
12) "[]"
13) "delay"
14) "2065543"
```

Here are the times it actually ran:
![image](https://user-images.githubusercontent.com/115926/207722676-5666ff90-8ab3-4c8e-8af0-f1fbdcf00a7a.png)

two of the entries are manual runs, but generally we never see it running at the scheduled time.

The biggest issue is that it can stall and never run for days.  Could another job stalling cause all other scheduled jobs to be messed up?
```
> xrange "prod:cron:events"
(...)
1053) 1) "1671045941674-0"
      2) 1) "event"
         2) "added"
         3) "jobId"
         4) "1204"
         5) "name"
         6) "teamsBilling"
1054) 1) "1671045941674-1"
      2) 1) "event"
         2) "waiting"
         3) "jobId"
         4) "1204"
1055) 1) "1671045941675-0"
      2) 1) "event"
         2) "active"
         3) "jobId"
         4) "1204"
         5) "prev"
         6) "waiting"
1056) 1) "1671046306588-0"
      2) 1) "event"
         2) "waiting"
         3) "jobId"
         4) "1204"
         5) "prev"
         6) "active"
1057) 1) "1671046306588-1"
      2) 1) "event"
         2) "stalled"
         3) "jobId"
         4) "1204"
```

How would we debug this issue? I can't seem to reproduce it at small scale in a dev environment.

**Comment by Rush** [comment]
I found the root cause.
1) On my side, `haproxy` was disconnecting the client after X seconds of inactivity - the fix was to increase `client timeout` to a large value
2) Basically reconnection logic in `bullmq` is not working at all when it comes to scheduled jobs. Any disconnect would cause schedules jobs to stop working. The fix is to rebuild the worker every time it happens. See below:

```ts
worker.on('ioredis:close', async () => {
  try {
    await worker.close(true);
   } catch (_err) {
    await delay(1000);
  }
  currentWorker$.next(buildWorker());
});
```

I think at least the docs should say not to rely on auto-reconnection logic.

**Comment by manast** [comment]
@Rush Do you have a code example that actually shows the case of scheduled jobs not working when there has been a disconnection/reconnection cycle?

**Comment by Rush** [comment]
> @Rush Do you have a code example that actually shows the case of scheduled jobs not working when there has been a disconnection/reconnection cycle?

Thanks for replying :) I'll flip the question. Is there a code example/integration test showing it's working?

**Comment by nemphys** [comment]
I just pulled the trigger and updated to the current version yesterday (was stuck in 1.91.1 for a ling time because of this issue).

No idea what could have fixed it (too much has changed in the meantime), but the issue seems to be gone and all works properly!

**Comment by crysislinux** [comment]
@nemphys Do you upgrade from 1.x to 4.x directly? Have you got any issues? We are also planning an upgrade. Thanks.

**Comment by nemphys** [comment]
@crysislinux yes, it was a direct upgrade and I didn't have any issues (running fine in production for a few months). Nevertheless, each use case is different and you should do some thorough testing first!

**Comment by Rush** [comment]
It seems to be running fine for us as well.
