### ISSUE TITLE
Job Chaining / Workflows

### ISSUE THREAD

**Issue by moltar** [taskforcesh/bullmq#146]
The docs are empty for this feature: https://docs.bullmq.io/patterns/chaining-jobs

I am wondering if this is implemented?

I did a search for these terms in the code / issues, but didn't find any references.

If it is implemented, could you maybe throw up a quick sketch / pseudo-code for how this works? I could then maybe document it better.

Thanks.

**Comment by manast** [comment]
It is a pattern that is possible to implement with current version of BullMQ, but i need to find some time to improve all the documentation, sorry for the delay.

**Comment by tiendq** [comment]
Docs are empty for many features and example code is often incorrect (they seems to be careless typed instead of copied from working ones).

**Comment by mgan59** [comment]
@moltar -- I've done some work here, been thinking of doing a write up, might be able to help @manast with some doc updates here if you like my approach/strategy...  Will see if i can get some simplified code-samples in place in the following days.

**Comment by manast** [comment]
@mgan59 that would be greatly appreciated!.

**Comment by coderapper** [comment]
I’m just curious to see more documentation on APIs ... would have loved to help if I could!

**Comment by sanjevraj** [comment]
Can you maybe give a brief outline how this could be achieved? Would be most appreciated.

**Comment by roggervalf** [comment]
As we have flows feature https://docs.bullmq.io/guide/flows and chaining file was removed we should be fine closing this issue
