### ISSUE TITLE
Add types for event emitters

### ISSUE THREAD

**Issue by moltar** [taskforcesh/bullmq#147]
In this kind of code, the `job` is not properly typed.

```ts
worker.on('completed', job => {
  console.log(job)
})
```

Would be ideal, if this had at least the `Job` type, but ideally propagate the type all the way from the worker generic to the `job`.

May also find the following modules interesting:

 * https://github.com/garronej/ts-evt
 * https://github.com/rogierschouten/ts-events

**Comment by manast** [comment]
yes, this is a know limitation. Not so trivial to do in practice at least I did not find a really good way to solve it.

**Comment by manast** [comment]
btw, won't add a new dependency only for events, but thanks for the reference to the modules, they can be used for inspiration.

**Comment by roggervalf** [comment]
@moltar please try last version, event listener typing was added
