### ISSUE TITLE
Repeatable jobs using CRON pattern are not proccesed, they stay in delayed state!

### ISSUE THREAD

**Issue by Gherciu** [taskforcesh/bullmq#1489]
So I have a repeatable job which should run once a day every day (0 0 0 * * *)... And it runs the first time perfectly (because it has `{immediately: true}`).... but on the second day it is not triggered... And it stays in the delayed state even if the time passed and it should be triggered many hours ago...... What is weird.. If I restart the docker container the job get processed....  
So I have the feeling that bullmq doesn't watch the repeatable jobs or the mechanism which detects when the job should be run doesn't work as it should.... because on server restart it start processing the job... any help??

BullMq: 2.3.1
Redis 7
Node 16

Is that a known issue? `should I continue using bullMq or move to bull?`... From the issues I read many had this problem and it is not resolved yet....?

**Comment by manast** [comment]
@Gherciu you should provide a complete test code that reproduces the issue, and also specify which version of BullMQ are you using.

**Comment by manast** [comment]
I noticed this issue is quite old. The poster probably found the issue. If not please reopen.
