### ISSUE TITLE
Backporting

### ISSUE THREAD

**Issue by wenq1** [taskforcesh/bullmq#149]
Is it possible to backport features to bull 3’x? As a few tests revealed that bullmq is by far not feature complete (in fact having a few regressions) and looks more like a typescript rewrite rather than a new product, is it possible to just backport a few features back to bull 3.x?

Maybe separating worker and queue, and clean up some bull 3.x code will suffice

**Comment by manast** [comment]
It is actually quite feature complete, and one of the main features of this new version is precisely the modularity, so there is not much to backport really.

**Comment by wenq1** [comment]
I know it is quite so. Your work is greatly appreciated. It is the not-so-feature complete-part that keeps getting in the way. Looks to me that you either get bull 3.x which is feature complete and old, or you get bullmq which is new and quite feature complete.

**Comment by manast** [comment]
which features are you lacking?

**Comment by wenq1** [comment]
#138 #136 , and amongst a few others that I haven’t reportrd

**Comment by wenq1** [comment]
Ignore me. I think I can implement/workaround these issues

**Comment by wenq1** [comment]
And #150
