### ISSUE TITLE
bad argument #1 to 'decode' (string expected, got boolean)

### ISSUE THREAD

**Issue by jstayton** [taskforcesh/bullmq#1496]
I'm pretty sure this error is coming from BullMQ (v2.1.1) – since it uses Lua scripts and [there seems to be a `decode` call](https://github.com/taskforcesh/bullmq/search?q=decode&type=code) – although it's not totally clear from the stack trace:

```
ReplyError: ERR Error running script (call to f_9264ff1dc3e7b8cac6b97354cfa0cfe4711839db): @user_script:199: user_script:199: bad argument #1 to 'decode' (string expected, got boolean)
  File "/srv/build/1663264836/node_modules/redis-parser/lib/parser.js", line 179, col 12, in parseError
    return new ReplyError(string)
  File "/srv/build/1663264836/node_modules/redis-parser/lib/parser.js", line 302, col 14, in parseType
    return parseError(parser)
```

Any idea if this is coming from BullMQ?

Thanks for your help!

**Comment by roggervalf** [comment]
Hi @jstayton, did you face this issue in newer versions?

**Comment by jstayton** [comment]
Hey @roggervalf – Sorry for the delay in responding. No, I haven't seen this in newer versions.
