### ISSUE TITLE
Shortened version of Queue.repeat.addNextRepeatableJob()

### ISSUE THREAD

**Issue by stansv** [taskforcesh/bullmq#15]
Need a method in a Queue class to wrap Queue.repeat.addNextRepeatableJob() call.

**Comment by manast** [comment]
Is this still relevant?

**Comment by stansv** [comment]
Hmm, I have overlooked that I need to just use Queue.add() when I was implementing the `nextRepeatableJob` method in compat class! :)(https://github.com/taskforcesh/bullmq/blob/feat/add-trim-option-%2321/src/classes/compat.ts#L252)

But the getRepeatableJobs method can only be called via Queue.repeat property, there's no such convenience methods as for removeRepeatable (https://github.com/taskforcesh/bullmq/blob/feat/add-trim-option-%2321/src/classes/queue.ts#L99)
