### ISSUE TITLE
Setting MAXLEN as an option with NodeJS

### ISSUE THREAD

**Issue by robk99** [taskforcesh/bullmq#1503]
Hello, 

I see by commit: 
https://github.com/taskforcesh/bullmq/commit/bc58a49fba1b6f4e3595a0371ecf8410000a9021 
that the MAXLEN of "events" stream is set to 10,000 by default if the "meta" key does not exist. 
I do have the key (created by Queue) and change it to like 50,000 but it keeps returning to 10,000.

Questions: 
1. Do you maybe know why this is happening? 
2. Did you think about allowing this option to be set as QueueOptions in NodeJS ?

Thank you

**Comment by f-w** [comment]
I set queue option `streams.events.maxLen` to 10, confirmed Redis `bull:<queueName>:meta`  key `opts.maxLenEvents` is 10. Still `bull:<queueName>:events` count exceeds 10.

**Comment by manast** [comment]
Unfortunately it is not possible in Redis to trim the streams to an exact value as that would be too slow, so we use "nearly exact trimming": https://redis.io/docs/latest/commands/xtrim/
