### ISSUE TITLE
Job is not retried when concurrency > 1 + repeatable job is scheduled

### ISSUE THREAD

**Issue by sebastienvillar** [taskforcesh/bullmq#1505]
Reproduction steps

```
const {Queue, Worker} = require('bullmq');

const connection = {
  host: 'localhost',
};

const queue = new Queue('myQueue', {connection});
const worker = new Worker(
  'myQueue',
  (job) => {
    console.log('In my handler', job.id, job.attemptsMade);
    throw new Error('test failure');
  },
  {
    connection,
    concurrency: 2,
  },
);

// Adding this job messes up retrial of the job named `retriedJob`
queue.add('repeatedJob', 'data', {
  repeat: {
    pattern: '0 * * * *',
  },
});

queue.add('retriedJob', 'data', {
  attempts: 5,
  backoff: {
    type: 'fixed',
    delay: 1000,
  },
});
```

Expected: retriedJob is retried after 1 second and 'In my handler' is logged 5 times in a row.  
Actual: Job retriedJob never retried unless the worker is restarted

Other issue:
If concurrency = 2 and no repeatable job is scheduled, retrial works but instead of retrying after 1 second, it often retries after 5 seconds

**Comment by manast** [comment]
Which version of BullMQ are you using?

**Comment by sebastienvillar** [comment]
I've tested this on both `2.3.2` and `3.0.0`

**Comment by manast** [comment]
I tried this code with 3.0.0 and it works without any issues (note that the code you posted has some syntax errors as well and will not run as is):
```
const { Queue, Worker } = require("bullmq");
const connection = {
  host: "localhost",
};
const queue = new Queue("myQueue", { connection });

const worker = new Worker(
  "myQueue",
  (job) => {
    console.log("In my handler", job.id);
    throw new Error("test failure");
  },
  { connection }
);

queue.add("name", "data", {
  attempts: 5,
  backoff: {
    type: "fixed",
    delay: 3000,
  },
});
```

**Comment by sebastienvillar** [comment]
@manast , I've updated the reproduction steps. There's 2 issues:

1) Most important issue:  retry does not work when these 2 are combined:
- concurrency > 1
- repeatable job is scheduled

2) Other issue: retry delay is not always respected even under no load when:
- concurrency > 1
