### ISSUE TITLE
rate-limiting by groupKey - new implementation?

### ISSUE THREAD

**Issue by doebi** [taskforcesh/bullmq#1510]
I was about to file a bug for the missing `groupKey`property in the Interface `RateLimiterOptions` when I discovered this commit:
https://github.com/taskforcesh/bullmq/commit/81f780aeed81e670107d01d01265d407a30e2a62

Where can I find information on the new implementation and how to use it?
Your docs are way out of date. :/

Thanks.

My original error message:
```
src/worker.ts:18:7 - error TS2322: Type '{ max: number; duration: number; groupKey: string; }' is not assignable to type 'RateLimiterOptions'.
  Object literal may only specify known properties, and 'groupKey' does not exist in type 'RateLimiterOptions'.

18       groupKey: 'foo'
         ~~~~~~~~~~~~~~~~~~~

  node_modules/bullmq/dist/esm/interfaces/worker-options.d.ts:26:5
    26     limiter?: RateLimiterOptions;
           ~~~~~~~
    The expected type comes from property 'limiter' which is declared here on type 'WorkerOptions'

```

**Comment by manast** [comment]
Motivations for this change are here: https://blog.taskforce.sh/bullmq-3-0-release/

**Comment by doebi** [comment]
Thanks for the link.

So you're saying this feature is not available anymore unless I upgrade to the pay-for PRO version?

**Comment by manast** [comment]
It is available on BullMQ version 2.x and on Bull, but removed in version >= 3. The feature in the Pro version is a superset of the group functionality in BullMQ that is much more robust and efficient as well.

**Comment by doebi** [comment]
Are you going to remove more features from BullMQ in the future?
Cause if so, I should highly reconsider another library.

**Comment by manast** [comment]
Obviously, it is not some kind of long-term plan to remove features, on the contrary more will be added. I hope I made a good explanation in the blog post of why this particular feature was removed, for most users this was an improvement, as the rate limiter works much better now.

**Comment by doebi** [comment]
I figured that for my usecase it made more sense to just create a separate queue per logical group and have a fine-tuned global rate limit for each group.

As for the docs, I am now only sticking to the code or the automatically generated API docs. But I really appreciate the Patterns and Guide section. They helped me a lot in my architectural decision making.
