### ISSUE TITLE
Add support for getJobState method in Queue class

### ISSUE THREAD

**Issue by LyzeOfKiel** [taskforcesh/bullmq#1532]
Feature request:
Now, the only way to get job's state is by calling `job.getState()`. And if I already know job id, but don't have the actual job instance in a function, it would be convenient to call `queue.getJobState(jobId)` without retrieving the job via `queue.getJob(jobId)` first.

**Comment by manast** [comment]
Ok, it would be a bit faster as you do not need to fetch the job first. Maybe an enhancement for a rainy day :)

**Comment by roggervalf** [comment]
hi @LyzeOfKiel, it should be available since version 3.5.0
