### ISSUE TITLE
Scheduler required for bullmq-pro?

### ISSUE THREAD

**Issue by Adam-Burke** [taskforcesh/bullmq#1538]
Can I remove schedulers from my infrastructure if I'm using pro version 2.4.1?

I noticed the docs saying that the scheduler was no longer needed in bullmq 2.0 and above. Is it required in bullmq-pro? Is there a general approach to determining which features apply to the pro package and from which version?

**Comment by manast** [comment]
We try to update the Pro version as soon as possible after BullMQ has been released, here you can see the changelog:
https://docs.bullmq.io/bullmq-pro/changelog
This should also answer your question, the QueueScheduler is not needed anymore in Pro either.

**Comment by Adam-Burke** [comment]
Turns out if your auth is broken it just tells you your current version is the latest when you try to update.
