### ISSUE TITLE
How to verify if a job was added to the queue?

### ISSUE THREAD

**Issue by ppedziwiatr** [taskforcesh/bullmq#1542]
Hey,

assuming that I'm adding jobs with custom jobIds (which can be duplicated) - how can I verify whether the job was actually added to the queue (after calling `queue.add`)?

The `await queue.getJob(jobId)` returns the job normally, even if the job should not be added to the queue (because of the duplicated id)

**Comment by roggervalf** [comment]
Hey @ppedziwiatr, there is an event "added" that is only triggered when a job is created without duplication

**Comment by ppedziwiatr** [comment]
Thanks!

**Comment by ppedziwiatr** [comment]
Btw., is there event that would allow me to determine that the queue rejected the job because of the duplicated jobId?
