### ISSUE TITLE
Undefined job appears when try to create a delay job

### ISSUE THREAD

**Issue by BohdanKov** [taskforcesh/bullmq#1546]
After creation of a delayed job, I see an `undefined` value in the list of all jobs. `Undefined` value disappears in 30 seconds, I believe it removes by something like stalled jobs checker.

Minimal reproducible case:
https://codesandbox.io/s/undefined-job-2tjv9r-2tjv9r

Bullmq version: 3.2.2

**Comment by manast** [comment]
![image](https://user-images.githubusercontent.com/95200/203521611-94581adc-0753-4342-a7ea-9346bd456703.png)

It would be much better if you can just post the code as a test case, where you assert the expected output and fails when it is not the case.

**Comment by BohdanKov** [comment]
```
it('should return no undefined jobs', async () => {
  await queue.add(
    'test',
    { foo: 1 },
    {
      jobId: `job-id`,
      removeOnComplete: true,
      removeOnFail: true,
      delay: 10000,
    },
  );

  setTimeout(async () => {
    const jobs = await queue.getJobs();
    const undefinedJobs = jobs.filter(job => job === undefined);
    expect(undefinedJobs.length).to.equal(0);
  }, 11000);
});
```
