### ISSUE TITLE
`worker.concurrency === undefined`

### ISSUE THREAD

**Issue by 0x7357** [taskforcesh/bullmq#1552]
https://docs.bullmq.io/guide/workers/concurrency

I cannot set the "concurrency" as described in the documentation. However, I can set the "concurrency" when I change `worker.opts.concurrency`.

Is this the way it is supposed to be?

**Comment by manast** [comment]
So what is the issue you have exactly?

**Comment by manast** [comment]
The documentation says: 
```
worker.concurrency = 5
```

is it not working?

**Comment by manast** [comment]
Are you sure it is not working? We have tests that suggest it works:
https://github.com/taskforcesh/bullmq/blob/master/tests/test_worker.ts#L1530

**Comment by manast** [comment]
Just write a test case that shows it is not working and we will look into it. The tests we have are working, so something you do is different from the current test cases.
