### ISSUE TITLE
Some of the errors are not properly set in the 'failedReason' of 'failed' listener

### ISSUE THREAD

**Issue by ppedziwiatr** [taskforcesh/bullmq#1557]
Hey,

some exceptions doesn't seem to be properly handled by the `failed` listener - i.e. the `failedReason` is empty.

This code works:
```
// sandboxed processor code

try {
      result = await warp.contract(contractTxId)
        .setEvaluationOptions(evaluationOptions)
        .readState();
    } catch (e) {
      console.error(e);
      throw new Error(e);
    }
```

\- the failed reason is set properly:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/84311757/204823744-584d6d7f-d02c-4251-973f-519a264a4e53.png">

But this code (for the exact same case - where an error is thrown):
```
// sandboxed processor code

result = await warp.contract(contractTxId)
        .setEvaluationOptions(evaluationOptions)
        .readState();
```        

or this one:
```
// sandboxed processor code
try {
      result = await warp.contract(contractTxId)
        .setEvaluationOptions(evaluationOptions)
        .readState();
    } catch (e) {
      console.error(e);
      throw e;
    }
```    

do not work properly - even though in the last example the catched error is properly logged in the console:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/84311757/204821730-102e534c-3e0a-471b-b4f5-64801f4a015c.png">

(but the failedReason in the listener is an empty string).

The listener code is simply:
```js
registerEvents.on('failed', async ({jobId, failedReason}) => {
    logger.error('Register job failed', {jobId, failedReason});
  });
```

Tested on versions `3.2.1` and `3.2.4`.

As a workaround, I will probably need to wrap the whole processor code into sth like:
```
try {
  // processor code
} catch (e) {
  throw new Error(e);
}
```
\- but the current behaviour looks like a bug to me.

**Comment by manast** [comment]
Are you sure the ```e``` in ```catch(e)``` is an actual Error object?

**Comment by ppedziwiatr** [comment]
I guess it is - since it is catched (and logged - as described in the original message) in the below code:
> try {
>       result = await warp.contract(contractTxId)
>         .setEvaluationOptions(evaluationOptions)
>         .readState();
>     } catch (e) {
>       console.error(e);
>       throw e;
>     }

.. but rethrowing it (i.e. `throw e`) does not set the `failedReason`.

**Comment by manast** [comment]
If I have to guess, it is not really an Error object. You can test like this:
```ts
try {
 throw new Error("foobar");
} catch(e){
 throw e;
}
```

**Comment by ppedziwiatr** [comment]
> If I have to guess, it is not really an Error object. You can test like this:
> 
> ```ts
> try {
>  throw new Error("foobar");
> } catch(e){
>  throw e;
> }
> ```

Ofc. that's the first test I did :-) and it works (and that's why I'm now wrapping the whole processor code in a try-catch and doing `throw new Error(e)` in a catch - which fixes the issue (as in https://github.com/warp-contracts/warp-dre-node/blob/main/src/workers/registerProcessor.js#L16)

Still not sure why sth that is being 'catched' is not being saved in to 'failedReason' for _all_ thrown exceptions.

Anyway, I can live with my workaround and close the issue :-)

**Comment by manast** [comment]
I guess whatever is being thrown inside your code is not the same kind of Error object as the one you get by manually creating the Error object.

**Comment by manast** [comment]
Btw, as failedReason takes the ```message``` property from the Error object.
