### ISSUE TITLE
Multiple Jobs not working on pm2

### ISSUE THREAD

**Issue by kevintprod** [taskforcesh/bullmq#1560]
Hi, I did deploy my web app in AWS ec2 Linux using pm2. However, Upon testing that runs multiple jobs, it only completely processes the latest jobs I've queued.  Other jobs have been automatically moved to "Finished".

Here's the screenshot from the Bull Board, As you can see 2 jobs have been processed simultaneously. However, the first job which is 0% has been moved to Finished automatically, and the latest got the process through. 
![image](https://user-images.githubusercontent.com/108579027/204984726-ddfb9f86-9565-434c-b8ba-9a14062865ad.png)

**Comment by manast** [comment]
This is not enough information to understand what is going on. Please provide some simple test code that reproduces an issue and we will look into it.

**Comment by manast** [comment]
What did not work? what is your expected result and what did you get?

**Comment by kevintprod** [comment]
I was expecting to run a job simultaneously. However, It only runs the latest job I've queued and skip the others. Here's the screenshot from the Bull Board. As we can see I've run 2 jobs supposed to run simultaneously but It skips the 1st job and automatically moved to "Finished"

![image](https://user-images.githubusercontent.com/108579027/205069290-e98a2ce2-286e-4f64-b81e-520cdc662a2e.png)

**Comment by manast** [comment]
I really cannot make sense of what you write above, please try to explain in a different way.
For example: "I was expecting to run a job simultaneously", one job run simultaneously to what?
" It only runs the latest job I've queued and skip the others", what do you mean with "skip the others"?

Btw, instead of screenshots of Bullboard you should provide actual code that shows an actual issue.

**Comment by kevintprod** [comment]
I mean, The above screenshot is supposed to run a job at the same time. But Job ID 5 got skipped.

**Comment by manast** [comment]
That screenshot does not say anything useful to me. It could be a bug in bullboard or something like that. Please provide the actual code that shows the issue instead so can we look into it.

**Comment by kevintprod** [comment]
I did provide the code, and it is above. Please check.

**Comment by kevintprod** [comment]
Hi, I found a solution on stackoverflow. This might help from the other that is using pm2 for the cluster setup. I'll leave a link
https://stackoverflow.com/questions/50259763/what-is-the-use-of-pm2-scale-option
