### ISSUE TITLE
New lssues2

### ISSUE THREAD

**Issue by wissanu1987** [taskforcesh/bullmq#157]
https://github.com/taskforcesh/bullmq/blob/4ea537e0d1c68d3120b7d24a91b6c5aee481d2f9/src/classes/queue-base.ts#L74-L79

**Comment by wissanu1987** [comment]
> [bullmq/src/classes/queue-base.ts](https://github.com/taskforcesh/bullmq/blob/4ea537e0d1c68d3120b7d24a91b6c5aee481d2f9/src/classes/queue-base.ts#L74-L79)
> Lines 74 to 79 in [4ea537e](/taskforcesh/bullmq/commit/4ea537e0d1c68d3120b7d24a91b6c5aee481d2f9)
>  close() { 
>    if (!this.closing) { 
>      this.closing = this.connection.close(); 
>    } 
>    return this.closing; 
>  }
Duplicate of #

**Comment by manast** [comment]
please stop creating dummy issues or you will be banned from this repo.
