### ISSUE TITLE
No way to expire Flow processed jobs stored in parent redis key

### ISSUE THREAD

**Issue by lavagri** [taskforcesh/bullmq#1572]
## Description
Hi 👋 
Our project use Flows a lot, thx for the great feature. 

Meantime, I discovered around >18k `*:processed` keys stored on production redis after a few months(+same amount of completed, like regular one).
Is there a way to have ttl on them? Or remove it using the same strategy as for completed(like `removeOnComplete`)?

## Minimal, Working Test code to reproduce the issue.
*any simple flow setup, f.e.*:
```
const flowProducer = new FlowProducer();

const parentQueueName = 'parent-flow-queue';
const childQueueName = 'child-flow-queue';

const childQ = new Queue(childQueueName, { defaultJobOptions: { removeOnComplete: true, removeOnFail: true }});
const parentQ = new Queue(parentQueueName, { defaultJobOptions: { removeOnComplete: true, removeOnFail: true }});

const childWorker = new Worker(childQueueName, () => true);
const parentWorker = new Worker(parentQueueName, () =>  true);

await flowProducer.add({
    name: 'test-flow',
    queueName: parentQueueName,
    children: [
        { name: 'test-child', data: {}, queueName: childQueueName },
    ],
});
```

Despite `removeOnComplete` set to true, flow task no removed: 1 completed in child, 1 completed in parent, 1 saved child(processed) in parent.

## Bull version
v1.50.5
(looks like the same story for the last v3 and prev v2)

**Comment by tracycollins** [comment]
I'm having the same problem.
`removeOfComplete` doesn't work for flows.

**Comment by roggervalf** [comment]
hi guys, currently you can provide queue options when adding a flow, please take a look https://docs.bullmq.io/guide/flows#provide-options
