### ISSUE TITLE
Can't add backoffStrategies to settings in the QueueOptions interface

### ISSUE THREAD

**Issue by anazar** [taskforcesh/bullmq#1579]
This documentation seems wrong: https://docs.bullmq.io/bull/patterns/custom-backoff-strategy
- backoffStrategies is not available as an option on settings in the QueueOptions interface.

See here: https://github.com/taskforcesh/bullmq/blob/master/src/interfaces/queue-options.ts#L56
- settings use AdvancedRepeatOptions
- which only contains: https://github.com/taskforcesh/bullmq/blob/master/src/interfaces/advanced-options.ts#L7

It would be great if we could add backoffStrategy as a settings option in QueueOptions. This appears to be a bug.

**Comment by roggervalf** [comment]
hi @anazar , you can provide backoff option into defaultJobOptions https://github.com/taskforcesh/bullmq/blob/master/src/interfaces/base-job-options.ts#L34 like:
```ts
    const defaultJobOptions = {
      attempts: 10,
      backoff: { type: 'fixed', delay: 100 },
    };
    const queue = new Queue('custom', {
      connection,
      defaultJobOptions,
    });
```
backoffStrategy is an option that should be provided in Woker, as this instance is the actual one that uses that function

**Comment by myknbani** [comment]
Hi @roggervalf :

Also ran into this problem, ![Screenshot_20230310_153614](https://user-images.githubusercontent.com/5841268/224252698-d9ba38dd-a673-4eb9-b600-2fbf649974e0.png)

I haven't dugged into the source code yet, but is it not possible to specify this option in `Queue`?  For context, I'm using `nestjs/bullmq`, and trying to set a custom backoff strategy in one place, which is `BullModule.registerQueue()`.

Changing `AdvancedRepeatOptions` to `AdvancedOptions` removes the TS error, so the question remains as to whether this option is supported.
