### ISSUE TITLE
Node process not exiting

### ISSUE THREAD

**Issue by onehorsetown** [taskforcesh/bullmq#159]
This is an standalone example of a change I proposed in PR #154.  See this comment:

https://github.com/taskforcesh/bullmq/pull/154#discussion_r387497584

https://github.com/taskforcesh/bullmq/blob/b96f5ba3e9c36182174300af629b34fe43c62ecd/src/classes/worker.ts#L375-L379

When the `force` parameter is `false`, the code calls awaits `this.whenCurrentJobsFinished` but does not close the blocking connection (the `else` path).  

You mentioned that:

> disconnect should not be needed when not using force since the current jobs must complete and since we are "closing" no new calls to the blocking command should be performed. 

However, in the example from the repo mentioned below, you can see that the Node event loop never exits.   However, if you modify the worker.ts code as in my PR, then the node process exits cleanly.

Related to #119

**Comment by onehorsetown** [comment]
Standalone example:   https://github.com/onehorsetown/bullmq-159

**Comment by wenq1** [comment]
@onehorsetown, I've done a simple test on IORedis and found that neither IORedis#quit nor IORedis#disconnect closes the connection. There is always a :6379 port hanging. 

Can you confirm whether it is the same on your side?


````
        process.on ('SIGINT', async function (err) {
                console.log (`- SIGINT received`);

                try {
                        await app.close ();
                }
                catch (err) {
                        console.error (`- err.message: ${err.message}`);
                        console.error (`- err.stack: ${err.stack}`);
                }

                if (wtfnode) {
                        wtfnode.dump ();
                        process.exit (0);
                }
        });

````

**Comment by wenq1** [comment]
Regarding your issue, the blocking connection is closed in whenCurrentJobsFinished ()

**Comment by wenq1** [comment]
Also quote redis doc:

> By default recent versions of Redis don't close the connection with the client if the client is idle for many seconds: the connection will remain open forever.
So even if the author of bullmq spends much time working around this issue by making RedisConnection#disconnect "robust", the closure of the redis connection is completely dependent on the redis connection itself.

The aforementioned issue by myself (redis connection hanging) can be "stupidly" worked-around by sleep 1 second before wtfnode.dump ().

**Comment by wenq1** [comment]
@manast do you have any comments on this one?

**Comment by rvanmil** [comment]
Any updates on this issue?

**Comment by manast** [comment]
I will try to reproduce and fix.
