### ISSUE TITLE
whenCurrentJobsFinished reconnect arg

### ISSUE THREAD

**Issue by wenq1** [taskforcesh/bullmq#160]
Reconnect = true is never true.

If worker is paused, upon resuming, the connection is gone.

https://github.com/taskforcesh/bullmq/blob/b96f5ba3e9c36182174300af629b34fe43c62ecd/src/classes/worker.ts#L354-L365

Relates to #155  but is not the root cause, so I'm creating a separate issue.

**Comment by thegedge** [comment]
I think we have the same issue, which was causing our CI to have some non-deterministic failures. I have a fix on the way.

**Comment by thegedge** [comment]
Trying to figure out how to write a test to capture this, but here's the fix: https://github.com/taskforcesh/bullmq/compare/master...gadget-inc:fix-160-reconnect-bug

**Comment by wenq1** [comment]
let needsReconnect = false;
 if (this.waiting) {
       await this.blockingConnection.disconnect()); 
       needsReconnect = true;
  }
  
   if (this.processing) { 
     await Promise.all(this.processing.keys()); 
   } 
  
   reconnect && needsReconnect && (await this.blockingConnection.reconnect()); 


Better fix should be like this.

This is exactly the fix we used to fix #155.

However, wrong fix in #391 is commited by @manast, who thinks the fix should be to "avoid the infinite loop" rather than "stop the cause to the infinite loop"
