### ISSUE TITLE
Ability to clear/limit job log

### ISSUE THREAD

**Issue by mariuszste** [taskforcesh/bullmq#1600]
It would be nice if we could limit the amount of lines saved in the job log. Essentially a first in, first out log with the ability to limit the maximum number of lines to some value.

This would be really useful when retrying completed jobs.

A simpler alternative like the ability to clear the log manually or automatically when a job is retried would also be nice.

**Comment by CodyTseng** [comment]
I think it might be nice to add an option like `keepLogs` to `JobOptions` to limit the number of logs.

```
const job = queue.add('bar', {}, { keepLogs: 100 });
```

I would be happy to get familiar with the BullMQ code and implement this feature if needed.

**Comment by mariuszste** [comment]
> I think it might be nice to add an option like keepLogs to JobOptions to limit the number of logs.
There is already some discussion about this on #1611. I'll try implementing this when i get the time for it but feel free to do it before me.

**Comment by CodyTseng** [comment]
Looks great, looking forward to your update!

**Comment by roggervalf** [comment]
This feature should be available on versión 3.6.0
