### ISSUE TITLE
Poor `remove()` performance

### ISSUE THREAD

**Issue by Niek** [taskforcesh/bullmq#1603]
I noticed the performance of `job.remove()` (or `queue.remove(jobId)` for that matter) is very poor. Especially when the number of jobs gets very large (for example a few million), redis really starts to struggle at 100% CPU during a batch delete. Retrieving 10k jobs with e.g. `queue.getCompleted()` takes just a few seconds, but removing them takes more than 10 minutes (!).

I haven't benchmarked in detail, but I guess this could be due to the dependency checks in the remove lua script.

As I'm looking for a workaround, would it be possible to manually (batch-)remove completed jobs from redis with `DEL queueName:jobId` if the jobs are simple jobs (no dependencies) or will that mess up the queue state?

**Comment by manast** [comment]
Can you provide more details about your specific use case, do your jobs have many dependencies?

**Comment by Niek** [comment]
In my use-case the jobs are extremely simple. No dependencies at all - jobs get processed by workers, moved to completed, and I have a cron running to persist jobs data from completed to a database after which I remove the jobs from completed. The last step is very slow, as explained above.

**Comment by manast** [comment]
Do you mean that deleting 1 job without dependencies is very slow?

**Comment by Niek** [comment]
Well, in this case deleting thousands - but yes, around 60ms per job deletion. Since there is no way to batch-delete jobs, deleting thousands of jobs takes very long.

**Comment by manast** [comment]
Why can't you use ```removeOnComplete``` or ```clean```? also, removing many in parallel or just one by one?

**Comment by Niek** [comment]
Because I want to persist the job data to a DB after completion (in my case, I put the complete job data in ElasticSearch for aggregation and searchability). I assume that is a very common use-case - no-one wants to keep all job info in Redis/memory for a long time.

With `removeOnComplete` or `clean` the jobs get removed immediately, and I have no chance to persist the job data.

I tried a `queue.on('completed')` event listener earlier but the performance is too low - hence I settled on batch-selecting chunks of 10k jobs with `queue.getCompleted()`, persisting them and then deleting the jobs.

I remove in parallel with `Promise.all(jobs.map(j => j.remove())`.

**Comment by Niek** [comment]
Here's a reproducible script to show the issue:
```js
// Save as bench.js
const { Queue } = require('bullmq');

(async() => {
  const queue = new Queue('test', { connection: { host: 'localhost' } });
  let numJobs = 100_000;

  let time = performance.now();
  for (let i = 0; i < numJobs; i++) {
    await queue.add(`test-${i}`, {});
  }
  console.log(`Adding ${numJobs} jobs took ${(performance.now() - time) / 1000} secs`);


  numJobs = 10_000;
  time = performance.now();
  const jobs = await queue.getJobs(0, numJobs);
  console.log(`Retrieving ${numJobs} jobs took ${(performance.now() - time) / 1000} secs`);

  time = performance.now();
  await Promise.all(jobs.map(j => j.remove()))
  console.log(`Removing ${numJobs} jobs took ${(performance.now() - time) / 1000} secs`);

  process.exit(0);
})();
```

To run:
```bash
docker run --rm -it -v $(pwd)/bench.js:/root/bench.js alpine:latest \
   ash -c 'cd ~ && apk add nodejs npm redis && npm i bullmq && redis-server --daemonize yes && node bench.js'
```

Output:
```
Adding 100000 jobs took 11.48454329700768 secs
Retrieving 10000 jobs took 2.142358958989382 secs
Removing 10000 jobs took 181.4702094170004 secs
```

This shows that removing jobs gets really slow when there are many jobs in the queue. If you change the initial `numJobs` number to be 10k instead of 100k, thing are MUCH faster:
```bash
Adding 10000 jobs took 1.335047292008996 secs
Retrieving 10000 jobs took 0.001063166007399559 secs
Removing 10000 jobs took 0.000004540994763374328 secs
```

In other words: performance of removing jobs gets exponentially worse when the number of jobs in the queue increases.

**Comment by Niek** [comment]
With some further digging, I was able to pin-point the release where this issue was introduced. BullMQ 1.76.4 is the latest version that is still fast, 1.76.5 and every version after it is slow. Results of the same script above with 1.76.4:
```bash
$ docker run --rm -it -v $(pwd)/bench.js:/root/bench.js alpine:latest \
   ash -c 'cd ~ && apk add nodejs npm redis && npm i bullmq@1.76.4 && redis-server --daemonize yes && node bench.js'
# -snip-
Adding 100000 jobs took 11.354796755999327 secs
Retrieving 10000 jobs took 0.0018426250070333482 secs
Removing 10000 jobs took 0.000005125001072883606 secs
```
This is the diff between the two versions: https://github.com/taskforcesh/bullmq/compare/v1.76.4...v1.76.5

The only meaningful difference seems to be the `sanitizeJobTypes()` introduction.

**Comment by rosslavery** [comment]
My guess from the above diff would be the `[...new Set()]` calls (not sure which) being slow with high job counts.

**Comment by Niek** [comment]
Unfortunately I found the issue why 1.76.4 was so much faster - not providing a `JobType` to `getJobs()` caused it to return no jobs. The issue remains in all versions - `remove()` is very slow if the queue size is large.

**Comment by Niek** [comment]
Digging further into the lua scripts, i found that `removeJobFromAnyState` is causing the slowdown. This is because `LREM` and `ZREM` are very expensive calls that grow (exponentially) with the size of the queue. Some ideas:
* `LREM` -> limit the count to `1`, since I assume entries are not added more than once to the list
* `ZREM` -> do a `ZSCORE` call before doing `ZREM`, since the first one is O(1)
