### ISSUE TITLE
Error cleanall completed jobs: user_script:20: attempt to compare number with nil

### ISSUE THREAD

**Issue by dcolley** [taskforcesh/bullmq#1608]
> bulmq 4.9.0 on node v18.7.0 on mac M1

For completed jobs, clicking the 
![image](https://user-images.githubusercontent.com/1845970/209820291-c02cc490-ee55-4238-95a2-a43dd0b243cd.png)
produces this error

```json
{
"error":"Internal server error",
"message":"ERR Error running script (call to f_7d10323fcf64aca8477befc77ef3483697c335d4): @user_script:20: user_script:20: attempt to compare number with nil",
"details":"ReplyError: ERR Error running script (call to f_7d10323fcf64aca8477befc77ef3483697c335d4): @user_script:20: user_script:20: attempt to compare number with nil\nat parseError (/Users/derek/bullmq/node_modules/redis-parser/lib/parser.js:179:12)\nat parseType (/Users/derek/bullmq/node_modules/redis-parser/lib/parser.js:302:14)"
}
```
... and the completed jobs are not cleared.

Deleting one job at a time is working

**Comment by roggervalf** [comment]
hi @dcolley, we currently are in version 3.5.1, we dont' have any 4.9.0 version :thinking:

**Comment by dcolley** [comment]
understood, it must be with bull-board
```
    "@bull-board/express": "^4.9.0",
    "bullmq": "^3.5.1",
```
thanks, this can be closed

**Comment by dcolley** [comment]
Follow the conversation here: https://github.com/felixmosh/bull-board/issues/509
