### ISSUE TITLE
Surprising non-corresponding id listed under the active key on delayed jobs

### ISSUE THREAD

**Issue by Shahor** [taskforcesh/bullmq#1615]
Hello 👋🏽 

We are migrating to bullmq from agenda and we noticed something quite surprising today.

We work on a documentation solution and each time a user navigates to a document we enqueue a job to track a few metrics on said document. 

This job is scheduled for a second later and it works quite fine, we see them running perfectly as we'd expect. 

When we look at the keys stored in redis though, we have this kind of thing: 

![image](https://user-images.githubusercontent.com/204561/210752820-0c9a4c0b-86ad-4bbe-a97e-a6a0a1cb202d.png)

It doesn't prevent our jobs from running but those stay around for a bit and when we try to look at the active jobs through https://www.npmjs.com/package/bull-arena the UI just crashes, which seems to indicate a badly formed payload. 

I can't find informations on the code about what would explain these values, could you help understanding what this is? If it is expected? And if we should worry about them? (We have 10s of thousands of those in some jobs, so we're concerned a bit)

Looking at the stream events key, there's no mention of those `0:1000` jobs, so we're quite confused.
![image](https://user-images.githubusercontent.com/204561/210753275-693e5831-3047-4bf1-827f-e433996b8028.png)

**Comment by roggervalf** [comment]
hi @Shahor, these kind of jobs, 0:1000 are special marker that are added when we have delayed jobs added, so when a worker pick this value, it will know how much time should wait until the delayed job is ready to be consumed, and from bull-arena side, it looks similar to https://github.com/bee-queue/arena/issues/600. I'm curious how you get 3 of those markers on your active list :thinking:

**Comment by Shahor** [comment]
> hi @Shahor, these kind of jobs, 0:1000 are special marker that are added when we have delayed jobs added, so when a worker pick this value, it will know how much time should wait until the delayed job is ready to be consumed, and from bull-arena side, it looks similar to [bee-queue/arena#600](https://github.com/bee-queue/arena/issues/600). I'm curious how you get 3 of those markers on your active list 🤔

Hello @roggervalf 👋🏽 
Thanks for your reply!

We have a class that extends bullmq.Class and doing a few little things, but basically I got to this situation by doing this: 

```ts
const queue = new trackUserShowNoteQueue()
await queue.add('trackUserShowNote', undefined /* no payload */, {
  repeat: {
    every: 1_000
  }
})
```

I could paste more of the code we have but it basically does this. 
This job is repeated every second, and although I have noticed the active jobs with special markers disappearing they do so after much longer than 1s so ultimately the pile grows up.

**Comment by Shahor** [comment]
Thank you @roggervalf !

**Comment by Shahor** [comment]
I've noticed something new though, since the upgrade to that latest version 🤔 
Some jobs fail but they're really just jobs with the marker that are being picked up to be ran, when they most likely shouldn't.

See here: 

![image](https://user-images.githubusercontent.com/204561/211348928-cb6f799b-532f-4ac4-bc93-fe19ad05a881.png)

**Comment by Shahor** [comment]
@roggervalf I've noticed something new though, since the upgrade to that latest version 🤔 
Some jobs fail but they're really just jobs with the marker that are being picked up to be ran, when they most likely shouldn't.

See here: 

![image](https://user-images.githubusercontent.com/204561/211348928-cb6f799b-532f-4ac4-bc93-fe19ad05a881.png)

**Comment by manast** [comment]
We think these are old markers due to the issue you had before. You should not get any new failed jobs like this anymore.

**Comment by Shahor** [comment]
> We think these are old markers due to the issue you had before. You should not get any new failed jobs like this anymore.

Sadly I don't think so, I had removed all keys manually from my redis storage to start clean again so those are new markers that popped up.

**Comment by manast** [comment]
@Shahor do you have some test snippet that reproduces it?

**Comment by Shahor** [comment]
> @Shahor do you have some test snippet that reproduces it?

Not really, I've seen it a few times in production but it's not systematic and easy to reproduce.

We used to instanciate a new queue to add new jobs so maybe that could be linked?
We are switching to having the queue built once and reused directly to avoid the overhead of instanciating a new one every time we need it. 

I'll keep you posted if we keep on seeing this happen.

**Comment by roggervalf** [comment]
hey @Shahor could you please try version 3.5.7, there is a fix about this case

**Comment by Shahor** [comment]
> hey @Shahor could you please try version 3.5.7, there is a fix about this case

@roggervalf Sure, I'll upgrade and will let you know. Thanks for the update and hard work 🙇🏽

**Comment by Shahor** [comment]
@roggervalf It seems to have done the deed, I'll update if necessary.
Thank you
