### ISSUE TITLE
events in Events in Redis keeps growing

### ISSUE THREAD

**Issue by BartTactick** [taskforcesh/bullmq#1625]
In one of our projects we are using BullMQ.
We have noticed that BullMQ has an events log and we wonder if this can either be disabled or automaticly removed.
![image](https://user-images.githubusercontent.com/77833517/212306395-adc4fd36-fbfd-4532-ae63-f0a669e46012.png)

**Comment by manast** [comment]
You can define as an option how many events to keep using the ```streams.events.maxLength``` option: https://api.docs.bullmq.io/interfaces/QueueOptions.html#streams the default is 10k events.

You can use the option when instantiating a new Queue to limit the number of events stored:
```
const myQueue = new Queue("test", { connection, streams: { events: { maxLength: 100 } }});
```

**Comment by BartTactick** [comment]
> You can define as an option how many events to keep using the `streams.events.maxLength` option: https://api.docs.bullmq.io/interfaces/QueueOptions.html#streams the default is 10k events.
> 
> You can use the option when instantiating a new Queue to limit the number of events stored:
> 
> ```ts
> const myQueue = new Queue("test", { connection, streams: { events: { maxLength: 100 } }});
> ```

Thank you very much! seems to work.

**Comment by GitVitor** [comment]
But what's the impact behind change this stream max length?

**Comment by roggervalf** [comment]
hey @GitVictor, it allows you to modify the quantity of events that will be saved, older events will be deleted and maxLength values are goint Ro be kept

**Comment by manast** [comment]
@GitVitor if you do not use the events for anything that needs to be exact once, then there is no impact.

**Comment by GitVitor** [comment]
Oh sure, many thanks for your responses.

I believe that this events could be useful for the @nestjs/bullmq implementation, when I subscribe to the decorator "completed", for example.

Anyway, thanks for the answer again.
