### ISSUE TITLE
bug: Concurrency set to 1 , Actives jobs 3 , delayed for days 

### ISSUE THREAD

**Issue by lukepolo** [taskforcesh/bullmq#1626]
In our production environemnt we ran into a odd issue where we have a queue set to a concurrency 1 , somehow it grabbed 3 jobs and set them to active.

They seem to then been stuck for days, because they have been delayed (but not moved to the delayed group) 
![image](https://user-images.githubusercontent.com/2066668/212347903-16c3cbe0-f904-424d-95c9-7c778a1ee071.png)

```
workerOptions: {
  [Queues.MediaProfileRecordingsPopulationGateway]: {
    concurrency: 1,
  },
  ```

```
{
  "attempts": 3,
  "delay": 30000,
  "removeOnFail": 500,
  "backoff": {
    "delay": 1000,
    "type": "exponential"
  },
  "removeOnComplete": 500
}
```

BullMQ Pro

```
"@taskforcesh/bullmq-pro@^2.4.2":
  version "2.7.1"
  resolved "https://npm.taskforce.sh/@taskforcesh/bullmq-pro/-/@taskforcesh/bullmq-pro-2.7.1.tgz#cb180a12c4c699341e1d4350d08fe31d2e4bc4db"
  integrity sha512-uHTECFT4/dFzKq6oBnGCsOhVLWurr/b3PUJl90e5B4Sakxn55gMVuXWNBXEJQIKUJjk8cCTSXaddQxTMGI+oKw==
  dependencies:
    bullmq "1.91.1"
    lodash "^4.17.21"
    msgpackr "^1.5.1"
    rxjs "^6.6.7"
    tslib "^2.3.1"
    uuid "^8.3.2"
```

All other queues seem to be working fine and have ran without issue. 

Let me know if i can provide any more information (cant supply all our code)

**Comment by lukepolo** [comment]
im sorry i read everything wrong in  the dashboard

**Comment by manast** [comment]
Ok, great, let us know if you find something wrong. By the way, seems like you are on a quite old version, the latest one is v5.1.11.
