### ISSUE TITLE
How to notify an user that the job is done and return the results

### ISSUE THREAD

**Issue by zefexdeveloper** [taskforcesh/bullmq#163]
I'm planning on creating a real time application where the user can send an image and this image will be processed and returned to the user when it's done, something really similar to what [convertio.co](convertio.co/) does but I don't know how can I get access to the connected socket that requested the image manipulation in the job so I can notify when it's done. I want to notify the user using socket when the job was added to the queue, it's being processed and it's done (with the results).

**Comment by manast** [comment]
Sorry for the late response.
You will need to create your own backend socket infrastructure for this, there are many ways to solve this problem but it is not something Bullmq will help you with. When a job emits progress events or finishes a job you have to find which sockets that are connected to your server are relevant to be notified and send them the notifications. 
Maybe you ca get some inspiration from this package: https://www.npmjs.com/package/wing

**Comment by zefexdeveloper** [comment]
@manast That is okay, thank you for your response. I see what you did on wing, it's really nice. I was reading the socket.IO docs and I saw this: https://github.com/socketio/socket.io-redis

 > By running socket.io with the socket.io-redis adapter you can run multiple socket.io instances in different processes or servers that can all broadcast and emit events to and from each other.

So maybe I can like pass somehow an id (like a room id) to the job so I can have it on the worker to notify the right socket? Is that the same thing as you did but in a different way?

**Comment by manast** [comment]
yes, it is the same concept. All clients that care about a given resource ID can join a room and then you broadcast to them the result or the progress of the job.

**Comment by zefexdeveloper** [comment]
@manast Thank you for the help, I will be doing that way.
