### ISSUE TITLE
Global Concurrency

### ISSUE THREAD

**Issue by adrian-goe** [taskforcesh/bullmq#1635]
Hey, so we use bull with nestJs and have multiple processors on this instance.

We want to maximise the usage of the available database connections. so I know, I can add concurrency per queue. But for the given example, this world not be a great fit:

* Allowed DB connections: 20;
* queue 1: 
* * 100 fast jobs
* queue 2: 
* * 20 long running jobs

So currently I could say queue 2: concurrency 5; queue 1: concurrency 15. 

If queue 2 is finished, it would optimal, to run queue 1 with 20 parallel jobs.

I guess, if there is a job in queue 2 again, they would be prioritise queue 2. Also, if a queue also has set a concurrency, the queue don't exceed this.

**Comment by marbemac** [comment]
Related: #2496

**Comment by roggervalf** [comment]
Global concurrency is available since v5.9.0
