### ISSUE TITLE
FlowJob queuesOptions not working

### ISSUE THREAD

**Issue by tomeof** [taskforcesh/bullmq#1639]
### Bug description:
Simply the options passed have no effect in Redis database. Unless i am misusing the interface.
### Environment:
bullmq: 3.5.5
redis-server: 6.2.6

### Code sample:
```js    
flowProducer.add({
      name: "flowJob",
      queueName: "flowQueue",
      data: { whatever },
      children: children,
      opts: {
        queuesOptions: {
           flowQueue: {
             defaultJobOptions: { removeOnComplete: 10, removeOnFail: true },
           },
           childrenQueue: {
             defaultJobOptions: { removeOnComplete: 100, removeOnFail: true },
           },
         },
      },
    });
```

**Comment by roggervalf** [comment]
hi @tomeof, opts is the second argument, it is not part of the first one, please check https://api.docs.bullmq.io/classes/FlowProducer.html#add
