### ISSUE TITLE
Use uuid instead of node-uuid (deprecated)

### ISSUE THREAD

**Issue by zefexdeveloper** [taskforcesh/bullmq#164]
node-uuid has been deprecated. https://www.npmjs.com/package/node-uuid

**Comment by wenq1** [comment]
It can simply be removed.
https://www.npmjs.com/package/bullmq-lite

**Comment by manast** [comment]
@wenq1 wouldn't be better to submit a PR than keep a separate fork?

**Comment by zefexdeveloper** [comment]
Thank you @wenq1, you are right, just updating the package works out. And as @wenq1 it would be nice to have this as a PR.
