### ISSUE TITLE
queue.obliterate() doesn't properly clean up orphaned keys

### ISSUE THREAD

**Issue by hyperair** [taskforcesh/bullmq#1644]
We ended up with some orphaned keys in our bullmq redis instance recently, where:
 - the job key exists in redis: ``` `${queue.opts.prefix}:${queue.name}:${jobId}` ```
 - the jobId doesn't exist anywhere in any of the queue's state keys (`active`, `waiting`, ...))

This results in some issues:
- `queue.add` with the same jobId no longer does anything, the job just gets stuck in limbo forever,
- `queue.obliterate()` doesn't seem to clean up these jobs either, as it only touches jobs that bullmq directly knows about through the queue's state keys

I'm not sure how it occurred exactly, but I suspect it might have been due to a race condition with `queue.drain(true)`.

I see that at some point [in the past](https://github.com/taskforcesh/bullmq/commit/90ffe9684e6b154e47d62df84792885d9ce983de), `queue.obliterate()` would have cleaned up those keys, but after https://github.com/taskforcesh/bullmq/commit/82f571f2548c61c776b897fd1c5050bb09c8afca, it no longer scans through all keys with the pattern, and so we don't have a good way of cleaning this up short of manually doing a redis scan and delete ourselves.

Is it possible to have the old obliterate behaviour back?

**Comment by roggervalf** [comment]
@hyperair thanks for reporting. It would be nice with a small test snippet that reproduces the issue

**Comment by hyperair** [comment]
It's a little hard to reproduce since I think orphaned jobs aren't supposed to happen at all in BullMQ.

However, relying on an existing bug in BullMQ:
- If you first run the testcase in [this bug](https://github.com/taskforcesh/bullmq/issues/1676), it will leave behind an orphaned job at redis key `bull:test-queue:test-job`,  note how `job.getState()` returns `"unknown"` despite the job's key itself existing
- If you then run `queue.obliterate({ force: true });`, the entire queue's keys disappear, but the redis key `bull:test-queue:test-job` gets left behind.

**Comment by hyperair** [comment]
Shorter test case:

<details>
<summary>Code</summary>

```typescript
import { Job, Queue } from 'bullmq';
import { Redis } from 'ioredis';

async function main()
{
    const jobId = "test-job-id";

    const connection = new Redis(6379);
    const queue = new Queue("demo-obliterate-unclean", { connection });

    const addJob = (): Promise<Job> => {
        console.log(`Adding job ${jobId} with delay of 10000`);
        return queue.add("test-job", {}, { jobId, delay: 10000 });
    }

    const checkJob = async (): Promise<void> => {
        const queriedJob = await queue.getJob(jobId);
        if (queriedJob) {
            console.log(
                `Job ${jobId} exists, and has state `
                    + `"${await queriedJob.getState()}"`
            );
        } else {
            console.log(`Job ${jobId} does not exist`);
        }
    }
    const showRedisKeys = async (): Promise<void> => {
        const keys = await connection.keys(queue.toKey('') + '*');

        if (keys.length == 0) {
            console.log('No redis keys found');
        } else {
            console.log(
                'Current redis keys:\n'
                    + keys.map(k => ` - ${k}`).join('\n')
            );
        }
    }

    await addJob();
    await checkJob();

    const delayedKey = queue.keys.delayed;
    const number = await connection.zrem(delayedKey, [jobId]);
    console.log(`Removed ${number} jobs from ${delayedKey} directly in redis`);

    await checkJob();
    await showRedisKeys();

    console.log(`Obliterating queue ${queue.name}`);
    await queue.obliterate({ force: true });

    await showRedisKeys();

    console.log('Resuming queue');
    await queue.resume();
    await addJob();
    await checkJob();
}

main().then(() => process.exit());
```

</details>

<details>
<summary>Output</summary>

```
% ts-node index.ts
Adding job test-job-id with delay of 10000
Job test-job-id exists, and has state "delayed"
Removed 1 jobs from bull:demo-obliterate-unclean:delayed directly in redis
Job test-job-id exists, and has state "unknown"
Current redis keys:
 - bull:demo-obliterate-unclean:meta
 - bull:demo-obliterate-unclean:test-job-id
 - bull:demo-obliterate-unclean:events
 - bull:demo-obliterate-unclean:wait
 - bull:demo-obliterate-unclean:id
Obliterating queue demo-obliterate-unclean
Current redis keys:
 - bull:demo-obliterate-unclean:test-job-id
Resuming queue
Adding job test-job-id with delay of 10000
Job test-job-id exists, and has state "unknown"
```

</details>

Note how even after obliterating the queue, the `test-job-id` jobId is no longer usable without an explicit `job.remove()`

**Comment by roggervalf** [comment]
Removing the jobId in a manual way directly from redis doesn't look like a good test, by the way, the fix for #1676 is merged, you could try version 3.6.6

**Comment by hyperair** [comment]
> Removing the jobId in a manual way directly from redis doesn't look like a good test, by the way, the fix for https://github.com/taskforcesh/bullmq/issues/1676 is merged, you could try version 3.6.6

Yeah I realize that it's not something that would happen ordinarily, it's just that we noticed that there were cases of jobs getting orphaned somehow, and we're not entirely sure whether all of the cases were caused by #1676, or whether there are other bugs that cause this. Either way, once it happens, we need to manually scan all redis keys matching the queue's redis key prefix to find them since `queue.obliterate()` doesn't quite do the job here.

I was thinking that if we could have another argument to `obliterate()` that did the scanning and deleting of keys for us, that would probably be quite helpful.

**Comment by renarsvilnis** [comment]
> It's a little hard to reproduce since I think orphaned jobs aren't supposed to happen at all in BullMQ.
> 
> However, relying on an existing bug in BullMQ:
> 
> * If you first run the testcase in [this bug](https://github.com/taskforcesh/bullmq/issues/1676), it will leave behind an orphaned job at redis key `bull:test-queue:test-job`,  note how `job.getState()` returns `"unknown"` despite the job's key itself existing
> * If you then run `queue.obliterate({ force: true });`, the entire queue's keys disappear, but the redis key `bull:test-queue:test-job` gets left behind.

This still seems an issue as of `"bullmq": "5.1.11",` where I run `queue.obliterate()` but still see queue appearing on bull-board.

**Comment by manast** [comment]
I am closing this is AFAICS there is no issue unless the contrary is proven with a test case.

**Comment by nrathi** [comment]
@hyperair did you ever figure out what was causing your orphaned jobs?

**Comment by manast** [comment]
@nrathi there is no known issue that would create orphaned jobs. If you found some issue please create a new issue report as this one is already closed.
