### ISSUE TITLE
removeRepeatableByKey does not remove the next repeatable job

### ISSUE THREAD

**Issue by deeptechllc** [taskforcesh/bullmq#165]
```js
  async removeRepeatableByKey(repeatJobKey: string) {
    const client = await this.client;

    const data = this._keyToData(repeatJobKey);
    const queueKey = this.keys[''];

    return (<any>client).removeRepeatable(
      this.keys.repeat,
      this.keys.delayed,
      data.id,
      repeatJobKey,
      queueKey,
    );
  }
```
The "data.id" is always null, and it can not remove the last delayed job. When after call "removeRepeatableByKey", the job will be processed once again.

I think it will be fixed when change to the following code.

```js
  async removeRepeatableByKey(repeatJobKey: string) {
    const client = await this.client;

    const data = this._keyToData(repeatJobKey);
    const repeatJobId = getRepeatJobId(data.name, '', md5(repeatJobKey));
    const queueKey = this.keys[''];

    return (<any>client).removeRepeatable(
      this.keys.repeat,
      this.keys.delayed,
      repeatJobId,
      repeatJobKey,
      queueKey,
    );
  }
```

**Comment by manast** [comment]
We have a test case that pass https://github.com/taskforcesh/bullmq/blob/master/src/test/test_repeat.ts#L437-L446

**Comment by deeptechllc** [comment]
> https://github.com/taskforcesh/bullmq/blob/master/src/test/test_repeat.ts#L437-L446

Well, repeatable Jobs had been removed. BUT the last delayed job is still in the queue. 
You can put the following code at the end of the above test case :

          const delayedJobs = await queue.getDelayed();
          expect(delayedJobs.length).to.be.eql(0);

**Comment by manast** [comment]
This must be a duplicated of this one: https://github.com/OptimalBits/bull/issues/1680

**Comment by deeptechllc** [comment]
> This must be a duplicated of this one: [OptimalBits/bull#1680](https://github.com/OptimalBits/bull/issues/1680)

Yes, it's the same.

**Comment by nemphys** [comment]
How come this has been closed when the issue definitely exists and has not been addressed?
Also, this seems to have been fixed in 3.x, but still persists in 4.x

**Comment by Xiphe** [comment]
I'm still experiencing this issue in `v1.64.0`

**Comment by manast** [comment]
@Xiphe could you open a new issue with code that reproduces it, please?

**Comment by Xiphe** [comment]
Sorry I currently don't have the time for that. But my code is pretty much similar to the code in the original issue.

I worked around the issue so no need to invest time here only for me.

**Comment by ZeChArtiahSaher** [comment]
Issue still persists with `v1.82.2`

**Comment by JCMais** [comment]
was anyone able to figure out a workaround for this?

My use case is simply calling `removeRepeatableByKey(job.key)` from inside a sandboxed job itself. The idea is to remove it from the queue when some condition happens.

The current behavior is that the delayed job stays in the queue and runs one more time after the `removeRepeatableByKey` call.

**Comment by manast** [comment]
@JCMais Do you have a test case that reproduces the issue?

**Comment by JCMais** [comment]
unfortunately I don't have one available, I will try to come up with something later this week.

**Comment by nate265** [comment]
This is still happening. Easy to test. Add a repeat job on a cron format. Delete it. Then, check the delayed size. It's > 0 .

**Comment by manast** [comment]
@nate265 we have tests that checks this scenario, like this one: https://github.com/taskforcesh/bullmq/blob/master/tests/test_repeat.ts#L1169
If you can create a new one that shows that it is not working we will surely look into it.

**Comment by annieTechno** [comment]
The problem with your test case is that it removes the repeatable job right after creation and the job was not run to create a delayed job for the next runs. So if the same test would wait for the job to be executed at least once then the remove will still leave on delayed job.

**Comment by annieTechno** [comment]
@manast Please see comments above

**Comment by osfa** [comment]
this is still an issue. only way to resolve this for me was to completely kill the redis instance and start it again.

**Comment by tea-artist** [comment]
This is still an issue, is there any workaround?

**Comment by manast** [comment]
@tea-artist please create a new issue where you can show the problem so that we can look into it.

**Comment by nhayhoc** [comment]
same here

**Comment by abbykrish** [comment]
We are also experiencing this same issue - deleting directly from Redis is also not working for us...

**Comment by roggervalf** [comment]
hi @abbykrish, which version are you using?
