### ISSUE TITLE
Question: pass binary files to Bull.

### ISSUE THREAD

**Issue by stoplion** [taskforcesh/bullmq#166]
We are migrating a long running image processing route to use BullMQ. 

The route works on a zip file full of images. Is there a way to pass the zip file as part of the Job/Queues payload? 

Or is the preferred way to upload the zip to S3 first, and return the S3 URLs? The only issue is that ½ the uploading to S3/returning of URLs takes quite long, and looking for ways to handle it asynchronously.

**Comment by manast** [comment]
I recommend you store in S3 and keep the payload to the jobs small. Since uploading files is mostly IO you will be able to increase the concurrency a lot so even if every job is slower you will be able to run many more in parallel.

**Comment by stoplion** [comment]
Ok. So what your saying is..
1. The endpoint would have to first upload files to S3.
2. The returned S3 URLs would then be passed to `Queue.add(<S3 urls>)` 
?

**Comment by manast** [comment]
yes, thats correct.

**Comment by manast** [comment]
In a video transcoder application we connected the express route directly to S3 via a stream, so you do not need any local storage, it will upload directly and efficiently. Not sure if this applies in your use case though.

**Comment by stoplion** [comment]
Excellent. Thanks for the tip.
