### ISSUE TITLE
Possible memory leak in workers.

### ISSUE THREAD

**Issue by Crazy-kun** [taskforcesh/bullmq#167]
Steps to reproduce:

1. Create worker.
`    const worker = new Worker("Test", resolve(__dirname, "./Test.js"), {
        connection: redisConfig
    });`
2. Create jobs.
`const queue = new Queue("Test", { connection: redisConfig });
 const promises = [];
        for (let i = 0; i < 10000; i++) {
            promises.push(
                queue.add(
                    "Test",
                    {
                        test: "test"
                    }
                )
            );
        }
        await Promise.all(promises);
        await queue.close();`

Test.js

`import { Job } from "bullmq";
import { redisConfig } from "../config";

export default (job: Job, done: any) => {
        let { test } = job.data;
        console.log(test);
        done();
};`

Application used memroy before worker starts processing jobs: ~100MB.
Application used memory during processing: ~600MB.

3. Removing worker after all jobs done.
`await worker.close();
`
Application used memory after worker removing: ~600MB.

Memory, used inside workers, do not disposes.

**Comment by wenq1** [comment]
Memory not being freed not necessarily mean there's a leak. Could be that GC has not yet kicked in.

**Comment by manast** [comment]
as @wenq1 is pointing out, you cannot prove there is a memory leak by a code like that, you need to make sure GC has run before you compare the memory. 
https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html

**Comment by Crazy-kun** [comment]
Well, if i repeat this worker several times, memory doesn't allocates over ~600MB. Ok, maybe it's really GC feature. Thanks for explanation!
