### ISSUE TITLE
Jobs are not being ordered by delay time

### ISSUE THREAD

**Issue by MarcusDias-r** [taskforcesh/bullmq#1680]
I have a problem ordering delayed jobs, because when I initially add a job with a delay of 6 hours, the next one, which would be 5 minutes, will wait the delay time of the previous one (6 hours), making my program unfeasible. Therefore, no task added after the initial one will run before it.

Strangely, when I restart my server the jobs with the shortest delay time are executed.

```
import { Worker, ConnectionOptions, Queue, QueueEvents } from 'bullmq'

const connection: ConnectionOptions = {
	port: Number(process.env.REDIS_PORT),
	host: process.env.REDIS_HOST as string,
}

const queue = new Queue('SEND_FLOW_MESSAGE_TO_LEAD_JOB', {
	connection: {
		...connection,
		enableOfflineQueue: false,
	},
})

    await queue.add('SEND_FLOW_MESSAGE_TO_LEAD_JOB',{},{delay: 21600000})
    await queue.add('SEND_FLOW_MESSAGE_TO_LEAD_JOB',{},{delay: 60000})
    await queue.add('SEND_FLOW_MESSAGE_TO_LEAD_JOB',{},{delay: 1000})
    
const worker = new Worker<SendFlowMessageToLeadJobParams>(
          'SEND_FLOW_MESSAGE_TO_LEAD_JOB',
          async (params) => {},
          {
		connection,
		concurrency: 30,
	  },
)
```
Bullmq version: 2.3.2

![Screenshot 2023-02-10 225359](https://user-images.githubusercontent.com/67759528/218233691-6df3c3e9-6944-4124-9f0f-40d28cc3b6aa.png)

**Comment by manast** [comment]
Please provide a complete test without any external dependencies, secondly, you wrote Bull 2.3.2, is this the correct version? besides being very old is another repo, please clarify.

**Comment by MarcusDias-r** [comment]
Sorry, I edited the example above and updated the lib to the most current version: 3.6.5. The error persisted.
