### ISSUE TITLE
[Bug]: incorrect typing for worker's "failed" event?

### ISSUE THREAD

**Issue by okovpashko** [taskforcesh/bullmq#1690]
### Version

v3.4.2

### Platform

NodeJS

### What happened?

The [type](https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L95) for the "failed" event handler states that the `job` argument can be `undefined` but in the [docs](https://docs.bullmq.io/guide/events) (see screenshot) and in the source code of the worker [here](https://github.com/taskforcesh/bullmq/blob/42be85bf339615c9cd6ec6a92e3d1cc11f030228/src/classes/worker.ts#L863) (notice types of the filter's callback) and [here](https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L664) (notice the job's method call in the previous line), the job seems can not be `undefined`.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/6490265/219371082-1a667254-bbd7-470e-8180-645f47a8f379.png">

The possible `undefined` in types causes developers to use type guards in the event's handler with the useless alternative branch that I suppose would never be executed.

Could you please consider fixing the types in case I am right or highlighting the cases when the `job` can be undefined in the docs?

### How to reproduce.

N/A

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by okovpashko** [comment]
UPD: the API reference also [tells us](https://api.docs.bullmq.io/interfaces/WorkerListener.html#failed) that the job is not optional.
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/6490265/220148878-7f1b06f5-dd11-4204-8863-463f2092d984.png">

**Comment by manast** [comment]
@roggervalf do you remember why the job can be undefined? I have a vague recollection there was a case where it could be indeed undefined.

**Comment by manast** [comment]
But actually, even if that could be the case, it is a bit pointless since you cannot do anything with the event at all.

**Comment by roggervalf** [comment]
hey guys, it could be undefined when the job is stalled and it reaches the limit of stalled jobs, if this job has an option to be removed, the worker does not get the instance of the job on the failed event https://github.com/taskforcesh/bullmq/compare/v1.81.1...v1.81.2
