### ISSUE TITLE
[Bug]: Workers will not pull jobs from a queue named `topQueueName`

### ISSUE THREAD

**Issue by mattgif** [taskforcesh/bullmq#1691]
### Version

v3.6.6

### Platform

NodeJS

### What happened?

The queue name 'topQueueName' seems to be restricted in some way. Following the Flow documentation, I tried to create a flow with a `queueName` of `'topQueueName'`. All of its children (on different queues) would complete, but the flow never left the waiting status.

Any other queue name works as expected. 

I also tried this with a simple Queue / Worker pattern and was able to reproduce.

### How to reproduce.

1. Add a job to a queue named `topQueueName`
2. Add a worker on the queue 
3. Check the job status; it will be 'waiting'. Expected to be 'completed'

Minimal code sample:

```javascript
  const queueName = 'topQueueName'
  const w = new Worker( queueName, j => { console.log( j.name ) }, { connection } )
  
  const q = new Queue( queueName, { connection } )
  q.add( 'job1', { foo : 'bar' } )
```
The log statement will not print.

Change the value of the `queueName` variable to 'topQueueName1' or `topQueueNam` (or anything else?), and you will see the log.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
If I have to guess, you have another rogue worker consuming jobs from this same queue that you maybe created in some other test or something.

**Comment by mattgif** [comment]
Well this is deeply embarrassing. I'd set the queue to a pause state in a process yesterday and never unpaused it. 

Thanks for your response!
