### ISSUE TITLE
[Bug]: Repeat job not run

### ISSUE THREAD

**Issue by TIMMLOPK** [taskforcesh/bullmq#1701]
### Version

v3.7.0

### Platform

NodeJS

### What happened?

It is a simple case that the work should be run at 04:00 every day.However I have experience this bug for two weeks, it worked as expected sometimes for two/one day(s) and then the job won't run in the third days.I tried to do something such as flush Redis data but the bug is still here.In the last time, I tried to check Redis that I found the job only add once that mean it isn't added to the next day(or it is a design?) I have another repeated job that run every 5 mins, it is working as expected.

If I can provide more information, I'm more than welcome

### How to reproduce.

I have the code: 

```js
const queue = new Queue("task", { connection: redis });
    await queue.add(
      "checkIn",
      {},
      {
        repeat: {
          pattern: "0 0 4 * * *",
          offset: new Date().getTimezoneOffset(),
          tz: "Asia/Hong_Kong",
          limit: 1,
        },
      }
    );
    
    new Worker(
      "task",
      async (job: Job) => {
        switch (job.name) {
          case "checkIn":
            await claimRewards(client);
            break;
          default:
            break;
        }
      },
      { connection: redis }
)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
What happened, did you find out the issue?
