### ISSUE TITLE
queue.close() kills all processes (jobs) running in all queues

### ISSUE THREAD

**Issue by Gustav0ar** [taskforcesh/bullmq#172]
Firstly, I'd like to congratulate you for this awesome library, it helped me a lot.
I've encountered an issue in my app when I create separate Queues (with different names) to execute a single job and when the job finishes I close the queue.
There is a bug when doing queue.close() that will kill every job running in separate processes in all queues, not just the one I'm closing.
I traced the bug to [child-pool.ts](https://github.com/taskforcesh/bullmq/blob/88ef30b1ff2ec0a037bf2cd69e8558687bbeb70e/src/classes/child-pool.ts#L98) on line 98, it will get all the processes running in this.retained and kill them. It should filter out to only get the processes linked to that specific queue.

The steps to reproduce are the following:

1. Create queue A
2. Run job on queue A
3. Create queue B
4. Run a job on queue B
5. Execute queue.close() on either one while both jobs are running
6. It will kill both processes, not just the one for the queue that you executed

**Comment by manast** [comment]
but the child pool is not global so killing the retained processes should only kill the ones belonging to a given queue. Can you provide a complete test case so that I can run it myself?

**Comment by Gustav0ar** [comment]
@manast Thanks for the response. I'm using Queue3, that might be the issue. Here is the example with the bug: https://github.com/Gustav0ar/bullmqQueueBug
