### ISSUE TITLE
[Bug]: @Processor('', {concurrncy:0}) in 3.10.0 cause app to stuck

### ISSUE THREAD

**Issue by tomgrossman** [taskforcesh/bullmq#1723]
### Version

v3.10.0

### Platform

NodeJS

### What happened?

Since version `3.10.0` when using `@Processor('some queue name', { concurrency: 0 })`, the node application is stuck.
This exact config is working just fine with `3.9.0` or with `concurrency: 1`.
It also looks like the node process is stuck with 100% CPU.

***
Looks like it might be related to [this](https://github.com/taskforcesh/bullmq/commit/0d94e35e805b09c3b4c7404b8a2eeb71a1aff5c4#diff-be671ade8a436a3aabf4d745b4a17479e52a43147bd52282a9b543f7ec6f6e09R388) change
***

Node v18.12.1
@nestjs/bullmq ^1.1.0
bullmq ^3.10.0

### How to reproduce.

```javascript
import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Injectable, Logger } from '@nestjs/common';
import { Job } from 'bullmq';

@Injectable()
@Processor('queue name', { concurrency: 0 })
export default class OnboardingFlowWorker extends WorkerHost {
  private logger = new Logger(OnboardingFlowWorker.name);

  // eslint-disable-next-line class-methods-use-this
  async process(_job: Job): Promise<any> {
    return 'test';
  }
}
```

**The nestjs application doesn't start.**

When changing `concurrency` to `1` or downgrading to `bullmq@3.9.0`, everything is fine.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
ok, what would be the expected behavior of having concurrency 0?

**Comment by tomgrossman** [comment]
> ok, what would be the expected behavior of having concurrency 0?

@manast not to stuck 🤔 or at least mark it as a breaking change...
I changed it to `autorun: false` and it works fine now, but it took my some time to figure out what is going on

**Comment by manast** [comment]
Ok, so passing 0 as concurrency was an error. I do not think this is a breaking change, as 0 had an undefined behavior before. I will change the code so that it throws an exception though.

**Comment by tomgrossman** [comment]
@manast sounds reasonable, an error would have helped a lot 😄 
thanks!
