### ISSUE TITLE
[Bug]: `removeOnComplete` (and other object options) not passed correctly to Redis

### ISSUE THREAD

**Issue by olivermrbl** [taskforcesh/bullmq#1724]
### Version

v3.5.6

### Platform

NodeJS

### What happened?

Passing `KeepJobs` options to `removeOnComplete` does not work without stringifying them.

The following does not work:
```
add("some-event", data, { removeOnComplete: { age: 10 } })
```

The following works:
```
add("some-event", data, { removeOnComplete: JSON.stringify({ age: 10 }) })
```

In the former, it seems that the options are passed from Bull as `[object Object]` to Redis. 

I can do the stringifying myself, but I would expect Bull to handle this under the hood, as the documentation does not mention the need to stringify options. Or at least I couldn't find it. If there is, I'd appreciate it if you could link to it.

**Important note:** Nor does this work in `bull`. Even when stringifying the options.

### How to reproduce.

Emit event:
```
add("some-event", data, { removeOnComplete: { age: 10 } })
```

And observe that the job is never removed from Redis. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I am confused, why are you using ```emit``` ?

There are many tests here for the case where ```keepJobs``` is passed as an object, as it should be. https://github.com/taskforcesh/bullmq/blob/4cb5250886f8f454a7ee4ee4d2b1754cd83df59b/tests/test_worker.ts

**Comment by olivermrbl** [comment]
@manast Sorry, I meant to add `queue.add` - updating the issue description. We have an event bus abstraction around Bull where the call to `add` is in an `emit` method.

**Comment by manast** [comment]
As you can see we have tests that cover that simple scenario. You will need to write a complete test where the scenario does not work as expected.

**Comment by olivermrbl** [comment]
Got it - I'll try to get around to that.

Have I missed something about when completed jobs are removed when `{ age: x }` is used? 

Reading the documentation makes it seem as if jobs are automatically removed after x seconds, but I might have missed an important detail.

**Comment by manast** [comment]
They are *lazily* removed. A queue that is continuously processing jobs will remove the jobs when the "age" is older than the specified age.

**Comment by olivermrbl** [comment]
Got it, thanks. 

Can you confirm that this also works in `bull`? We are yet to upgrade to `bullmq`.

**Comment by olivermrbl** [comment]
Thanks for the quick response on my initial filing. I indeed have the expected behavior with `bullmq`. Though, I can't seem to use `KeepJobs` options in `bull`. 

I'll close this issue, but I'd love your reaction on this issue when time allows for it.

**Comment by manast** [comment]
The behaviour of ```keepJobs``` is documented here: https://docs.bullmq.io/guide/queues/auto-removal-of-jobs#keep-a-certain-number-of-jobs
