### ISSUE TITLE
QueueEvents don't trigger using remote Redis

### ISSUE THREAD

**Issue by OlivierNguyen** [taskforcesh/bullmq#173]
I'm trying to implement a queue but i have some issues in production when trying to use a remote Redis (Heroku Redis or Redis Cloud).

In local, everything work well but when i try to use a **REDIS_URL**, a job is created but events doesn't work.

Here is the code:

```javascript
// test_job.js
import { Queue, Worker, QueueEvents } from "bullmq";
import IORedis from "ioredis";

import Dotenv from "dotenv";
Dotenv.config();

// Good
const connection = new IORedis(process.env.REDIS_URL || 6379);

// Good
const queue = new Queue("Paint", { connection });

// Good
const worker = new Worker(
  "Paint",
  async job => {
    if (job.name === "cars") {
      console.log(job.data.color);
    }
  },
  { connection }
);

/**
 * BUG HERE: Events is triggered correctly in local but not when using a remote Redis (REDIS_URL)
 */
const queueEvents = new QueueEvents("Paint");
queueEvents.on("completed", jobId => {
  console.log("done painting");
});

queue.add("cars", { color: "blue" });

```

**Comment by Gustav0ar** [comment]
I haven't tested, but QueueEvents accepts QueueEventsOptions which inherent QueueBaseOptions which accepts a connection, try passing a connection to QueueEvents instance, that might be your issue.

**Comment by OlivierNguyen** [comment]
I tried but seems that it doesn't work too :( (But still work in local)

```javascript
const queueEvents = new QueueEvents("Stats", { connection });
```

**Comment by zhennann** [comment]
should `duplicate` connection just as follows:
`const queueEvents = new QueueEvents("Stats", { connection:connection.duplicate() });`

**Comment by OlivierNguyen** [comment]
@zhennann Thank you ! It works like a charm with `.duplicated()` !

**Comment by jmcantrell** [comment]
@zhennann Can you explain why `connection.duplicate()` was necessary?

**Comment by zhennann** [comment]
<img width="758" alt="WX20200502-083459@2x" src="https://user-images.githubusercontent.com/24246985/80850751-17a23480-8c50-11ea-9f7e-8109cd780be3.png">
