### ISSUE TITLE
[Bug]: Error trying to close queue after adding repeatable job

### ISSUE THREAD

**Issue by otaviosoares** [taskforcesh/bullmq#1733]
### Version

v3.10.1

### Platform

NodeJS

### What happened?

I need to manually close my queue after running a cronjob so the process is released. However, if my code adds a repeatable job before I try to close it, it fails with `Connection is closed.`.

Contrived example:

```js
const { Queue } = require("bullmq");

async function init() {
  const queue = new Queue("test", {
    host: "localhost",
    port: 6379,
  });

  queue.add(
    "test",
    {
      data: 1,
    },
    {
      repeat: {
        every: 5 * 60 * 1000,
      },
    }
  );

  await queue.close();
}

init();

```

Please note that if it's a normal job the error doesn't happen:

```js
// This works
const { Queue } = require("bullmq");

async function init() {
  const queue = new Queue("test", {
    host: "localhost",
    port: 6379,
  });

  queue.add(
    "test",
    {
      data: 1,
    }
  );

  await queue.close();
}

init();
```

I've taken a look at the code and it looks like when a repeatable job is added it reuses the queue connection. Given that, the condition to close the `this._repeat` instance seems redundant, as the connection will be closed in `super.close()`. Can someone please clarify if this is intended or a bug? 

```js
 async close(): Promise<void> {
    if (!this.closing) {
      if (this._repeat) {
        await this._repeat.close();
      }
    }
    return super.close();
  }
```

Thanks

### How to reproduce.

- create a queue
- add a repeatable job
- try to close the queue

### Relevant log output

```shell
/Users/otaviosoares/Projects/test-bullmq/node_modules/ioredis/built/redis/event_handler.js:189
        self.flushQueue(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
                        ^
Error: Connection is closed.
    at close (/Users/otaviosoares/Projects/test-bullmq/node_modules/ioredis/built/redis/event_handler.js:189:25)
    at Socket.<anonymous> (/Users/otaviosoares/Projects/test-bullmq/node_modules/ioredis/built/redis/event_handler.js:156:20)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:322:12)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
Looks like you are missing an await statement when adding the job

**Comment by otaviosoares** [comment]
Omg, you're right. Thank you
