### ISSUE TITLE
[Bug]: attempt to perform arithmetic on local 'rangeStart' (a nil value)

### ISSUE THREAD

**Issue by Ponkhy** [taskforcesh/bullmq#1734]
### Version

BullMQ: v3.10.1
Redis: 7.0.9

### Platform

NodeJS: v18.12.1

### What happened?

I got the following error when I tried to use `start` and `end` to get a specific range of jobs.

### How to reproduce.

Pretty much any code that uses `start` and `end`.

I've tried: 
`getJobs(['active'], 5, 15)`
`getActive(5, 15)`
`getActive({ start: 5, end: 15})`

### Relevant log output

```shell
ReplyError: ERR user_script:23: attempt to perform arithmetic on local 'rangeStart' (a nil value) script: 20a2b757f485defbc4f7ba321e80c6c110388255, on @user_script:23.
    at parseError (/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      '20a2b757f485defbc4f7ba321e80c6c110388255',
      '1',
      'bull:PAGE:',
      '[object Object]',
      '-1',
      '1',
      'wait',
      'paused'
    ]
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Can you provide a complete test case, please? currently we have tests that cover all these cases so there must be something else.
