### ISSUE TITLE
How to change repeatable job payload (data)?

### ISSUE THREAD

**Issue by ElFisherMan** [taskforcesh/bullmq#1735]
I want to use BullMQ as a scheduling solution for all our services. Meaning - each service can register a repeateable job with the following fields: ID, pattern (cron), data.
I would like to allow changing the data, while keeping the current scheduling.
AFAIK this is not possible in BullMQ (right?).
So the second best option - tell them to remove and re-add the reapeatable job with different data.
Having said that - I would like to have a check that checks if the data is different from the one configured for the repeatable job (with the same id and cron) and throw an error in such case.
Is this possible?

(When I call getRepeatableJobs, I only get the following fields (data is missing):
key, name, id, endDate, tz, pattern, next)

**Comment by manast** [comment]
Removing and adding a new updated repeatable job is currently the only viable option. We could add an atomic API that makes this for you though, I will mark it as an enhancement.

**Comment by manast** [comment]
Basically a "updateRepeatable" that atomically removes and creates a new repeatable with the new options.

**Comment by ElFisherMan** [comment]
Sounds great - I think it will be great if you could also add a check that verifies if no relevant field was changed.
In such case - it can ignore the update request.
It will help us a lot (when scaling out takes place and a new service will try upsert the same scheduled task, it won't have to worry for the existance of the same task [id, pattern, payload])

**Comment by abarbosa-godaddy** [comment]
@manast are you working on that already? This feature would be great in a project I am working on. I could open a pr for if there's no objection.

**Comment by roggervalf** [comment]
Hey @abarbosa-godaddy, there is no work in progress about this new feature, still working on changes on the pro version, but you can open a pr for it if you have time and we can take a look.

**Comment by abarbosa-godaddy** [comment]
Will do @roggervalf . Thank you,

**Comment by geeksilva97** [comment]
Btw, I'm `abarbosa` as well (I just didn't want to change account three days ago :see_no_evil: )

**Comment by manast** [comment]
With the new API "upsertJobScheduler" you can update the data payload of your repeatable jobs: https://docs.bullmq.io/guide/job-schedulers
