### ISSUE TITLE
QueueScheduler appear to create lag when using the shared connection

### ISSUE THREAD

**Issue by willoughby** [taskforcesh/bullmq#174]
I've been tracking an issue where when reusing the connection across Queueschedules it causes a block.

In my application a job can be started by a user posting details to an express endpoint, however, it has been taking over a minute in some cases before the job is picked up by the worker. 

Running this example locally the addJob call is taking over 20's
```
const options = { host: 'localhost', port: 6379 };
const connection = new Redis(options);
const newsQueue = new Queue('news', { connection });
const newsQueueScheduler = new QueueScheduler('news', { connection });
const strategyTestQueue = new Queue('strategy-tester', { connection });

async addJob(uid, args) {
        console.log('Queued test strategy', args);
        console.time('addingJob');
        const job = await strategyTestQueue.add(
            'test',
            { uid, ...args },
            { removeOnComplete: true, removeOnFail: true }
        );
        console.timeEnd('addingJob');
        console.log(job);
    },
```

```Queued test strategy
addingJob: 20660.016ms
```

I did not notice this locally because I was not passing in a connection into the Queue and QueueScheduler (was using default connection), One thing I noticed is if I give the QS a new IORedis instance the lag stops.
```const newsQueueScheduler = new QueueScheduler('news', { connection: new Redis(options) });```
```Queued test strategy
addingJob: 1.477783203125ms
```

**Comment by manast** [comment]
yes, this is because QueueScheduler is establishing a blocking connection to Redis. The solution would be to internally duplicate the connection, i.e. same thing you are doing as a workaround but internally. When some class in BullMQ requires a blocking connection there is no other solution than duplicating connections to avoid these delays.
