### ISSUE TITLE
[Bug]: BullMQ: DEPRECATION WARNING! Your redis options maxRetriesPerRequest must be null. On the next versions having this settings will throw an exception

### ISSUE THREAD

**Issue by sehrish30** [taskforcesh/bullmq#1744]
### Version

3.10.1

### Platform

NodeJS

### What happened?

Console throws this error. 
<img width="574" alt="226644736-c50c7429-3282-4efe-b2de-fd14bf4e01f9" src="https://user-images.githubusercontent.com/66527974/226809439-c6f54c03-2b2a-40c1-ad60-9130e6bf2b73.png">

### How to reproduce.

Start the nodejs server it throws this error.
bullmq Verion: 3.10.1
Nodejs version: 19.3.0
ioredis version: 5.3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
It is a warning, please make sure you set ```maxRetriesPerRequest``` to null to avoid it and please read this: https://docs.bullmq.io/guide/going-to-production#maxretriesperrequest
