### ISSUE TITLE
[Bug]: Error completing job

### ISSUE THREAD

**Issue by rsalazar-jelp** [taskforcesh/bullmq#1754]
### Version

0.1.0

### Platform

Python

### What happened?

when a worker job is complete i got this error trying to calling the "removeOnComplete" script:
"user_script:97: attempt to perform arithmetic on local 'maxDataPoints' (a nil value) script: 853b3088fff863a738a6d231b444bdfcab2cb649, on @user_script:97."

![jpeg](https://user-images.githubusercontent.com/60919261/227818849-ddf58613-240f-4049-b5a7-43c12cec040e.jpeg)

then when the error is crashed in the "removeOnFail" and send this error: 
"Error moving job to failed Missing key for job 69.finished"

![Screenshot 2023-03-26 at 6 13 06 p m](https://user-images.githubusercontent.com/60919261/227818976-7d650acb-a877-48cb-a3ab-c69a28cec9d7.png)

and thanks for your great work with this dependency

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
The new release of BullMQ for python (0.2.0) is ready: https://pypi.org/project/bullmq/

**Comment by rsalazar-jelp** [comment]
thank you guys, i appreciate it a lot
