### ISSUE TITLE
ability to recur a job starting from a later date.

### ISSUE THREAD

**Issue by RafiuJaman** [taskforcesh/bullmq#1760]
**Is your feature request related to a problem? Please describe.**
my use case is to send emails, i need to be able to schedule them for a later date and also make then recur starting from that particular date
i have tried a combination of delay and every parameters in job opts but it is not helping.

**Describe the solution you'd like**
Having a `startDate` for `every` parameter. So both can be used together to solve this problem. startDate can be optional.

**Additional context**
a detailed description of my problem is also given here [https://github.com/OptimalBits/bull/issues/2572](url)

**Comment by manast** [comment]
I am not sure what you mean. You may find this blog post useful though: https://blog.taskforce.sh/implementing-mail-microservice-with-bullmq/

**Comment by manast** [comment]
Ok, sorry, I do understand now. Why don't you just use ```startDate``` and ```pattern```, as "every" can mostly be simulated with a cron expression anyway?

**Comment by RafiuJaman** [comment]
> Ok, sorry, I do understand now. Why don't you just use `startDate` and `pattern`, as "every" can mostly be simulated with a cron expression anyway?

That would be good solution. Thanks. :)

One reason why i didnt want to use cron was because it is difficult to construct cron from an abstracted user input .
for example if the user selects some options like he wants an email to be repeated everyday , twice, starting from 01/01/2023.

it is a bit complicated to construct the cron of these programatically.
