### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fernandodevelon** [taskforcesh/bullmq#1763]
### Version

v3.10.0

### Platform

NodeJS

### What happened?

I have a service that runs in a Kubernetes pod. 
Upon startup, this service creates repeatable tasks with fixed IDs if they are not already present. 

Additionally, it adds 2 tasks not repeatable and without id,  with a delay of 15000 and 20000. Finally, the worker is started for task consumption.

The two tasks with delay are not always started. Sometimes only one of the two is started, and sometimes neither of them. I have to restart the container multiple times to ensure that they are processed.

Why do you think they are not always processed? 
Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Unfortunately, you are not providing enough information for us to give you any hints on what could be wrong. One thing you could do is to use a front-end where you can see the statuses of the queues, that may give you some hints.

**Comment by fernandodevelon** [comment]
Thank you for the support. Unfortunately, there are no error logs or other information available. I tried running Bull-board in production, but it was unable to detect the queues because they are located within a more complex key: production:tenant:bull:cronjob.

In addition, I'm having difficulty replicating it locally as it happens only occasionally
