### ISSUE TITLE
[Bug]: DelayedError no longer exists: Process steps example cannot be implemented

### ISSUE THREAD

**Issue by mividtim** [taskforcesh/bullmq#1767]
### Version

3.6.5

### Platform

NodeJS

### What happened?

I'm trying to implement the Delaying section of the Process Steps Job example https://docs.bullmq.io/patterns/process-step-jobs#delaying

It says that you need to return a DelayedError, but this does not seem to exist in recent versions of BullMQ. My real use-case here is that I have multiple concurrently-running tests that use the same queue, and each has a worker on that queue. I need only the test that added the job to handle the job, so I'm trying to use `moveToDelayed(1, token)` to let another handler pick up the job, effectively ignoring it. I can't simply use separate queues because these are end-to-end tests which don't control the code that places the jobs on the queue.

If I simply `return` from the handler after calling `moveToDelayed`, I get the `Missing lock for job` error, presumably because the handler that moved it to delayed retains the lock. Since DelayedError was removed, what is the proper way for a worker to pass up its chance to process a job? This seems like a simple use case: If I'm not the right worker for this job (inspecting the data), place it back on the queue for someone else.

Thanks in advance!

### How to reproduce.

Just attempt to implement the Delaying section of the Process Steps Job example:
https://docs.bullmq.io/patterns/process-step-jobs#delaying

### Relevant log output

```shell
Mar 30 10:10:46 AM          code: 'ERR_UNHANDLED_ERROR',
Mar 30 10:10:46 AM            at Worker.retryIfFailed (/opt/render/project/src/node_modules/bullmq/src/classes/worker.ts:809:16)
Mar 30 10:10:46 AM            at new NodeError (node:internal/errors:393:5)
Mar 30 10:10:46 AM          context: Error: Missing lock for job 60. failed
Mar 30 10:10:46 AM              at Scripts.finishedErrors (/opt/render/project/src/node_modules/bullmq/src/classes/scripts.ts:337:16)
Mar 30 10:10:46 AM              at Job.moveToFailed (/opt/render/project/src/node_modules/bullmq/src/classes/job.ts:637:26)
Mar 30 10:10:46 AM              at processTicksAndRejections (node:internal/process/task_queues:95:5)
Mar 30 10:10:46 AM              at handleFailed (/opt/render/project/src/node_modules/bullmq/src/classes/worker.ts:663:11)
Mar 30 10:10:46 AM              at Worker.retryIfFailed (/opt/render/project/src/node_modules/bullmq/src/classes/worker.ts:809:16)
Mar 30 10:10:46 AM              at Worker.run (/opt/render/project/src/node_modules/bullmq/src/classes/worker.ts:392:34)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
It does exist: https://github.com/taskforcesh/bullmq/blob/master/src/classes/delayed-error.ts

**Comment by mividtim** [comment]
Not in the release:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/15264802/228893159-a855730c-0c6f-4e53-bc6e-b5baad4f7785.png">

**Comment by mividtim** [comment]
Okay, next issue. Throwing an error causes the test system to fail the test. This isn't really a good pattern, to use exception throwing for normal behavior. I noticed some old threads that mentioned an autoComplete feature. With that, presumably I would have to manually call moveToComplete or moveToFailed, but it might be able to work around this issue... Except that presumably the worker would retain the lock.

**Comment by mividtim** [comment]
Okay, I believe I found a way to work around this. For posterity (for anyone looking at this in the future), here's the solution in Jest:
```
              expect(() => {
                throw new DelayedError('Not my job')
              }).toThrowError(DelayedError)
```
