### ISSUE TITLE
[Bug]: Error: Unknown backoff strategy undefined.

### ISSUE THREAD

**Issue by apmcodes** [taskforcesh/bullmq#1769]
### Version

^3.10.2

### Platform

NodeJS

### What happened?

If I give a backoff in the New Queue via defaultJobOptions, and a **different backoff** in the Job.add then get the following error. 
Tried creating a custom startegy named 'jitter' and add it to the Job but still get the same error. 

`
**Error: Unknown backoff strategy undefined.**
      If a custom backoff strategy is used, specify it when the queue is created.
    at lookupStrategy (/xxx/node_modules/bullmq/dist/cjs/classes/backoffs.js:44:15)
    at Backoffs.calculate (/xxx/node_modules/bullmq/dist/cjs/classes/backoffs.js:18:30)
    at Job.moveToFailed (/xxx/node_modules/bullmq/dist/cjs/classes/job.js:374:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (xxx/node_modules/bullmq/dist/cjs/classes/worker.js:331:21)
`

### How to reproduce.

Below the delay in Queue defaultJobOptions is 1000 while the delay Job.add is 60000. If the same value is used for both the delay the error do not occur. 

**Queue config**
```
...
            "defaultJobOptions": {
                "attempts": 3,
                "backoff": {
                    "type": "exponential",
                    "delay": **1000**
                },
                "removeOnComplete": false,
                "removeOnFail": false,
                "stackTraceLimit": 1
            },
            "settings": {
                "lockDuration": 60000,
                "lockRenewTime": 30000,
                "stalledInterval": 60000,
                "maxStalledCount": 1,
                "guardInterval": 5000,
                "retryProcessDelay": 5000,
                "drainDelay": 5
            }
...
```

**Queue add**
```
  const testQueue = new Queue(test-queue, {
    connection: redisConfig,
    defaultJobOptions: config.defaultJobOptions,
    settings: config.settings
  })
```

**Job add** 
```
  const taskOpts = {
    jobId: test-job, 
    attempts: 10, 
    backoff: {
      type: 'exponential',
      delay: **60000**
    },
    priority: 1
  }

  try {
    await testQueue.add(taskType, taskData, taskOpts)
    // return 'next expiry created'
    return context
  } catch (error) {
    logger.error('next expiry', error)
    throw error
  }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by apmcodes** [comment]
Had to declare the backoff strategy in the backoffStrategies of the Worker and mention the backoff name in the Job.add 

**Job add**
```
  const taskOpts = {
    ...
    backoff: 'jitter',
  }
  await testQueue.add(taskType, taskData, taskOpts)
```

**New Worker**
```
const testWorker = new Worker(options.name, consume, {
    ...
    settings: {
      backoffStrategies: {
        jitter(attempts) {
          return attempts * 1000
        }
      }
```

**Comment by roggervalf** [comment]
hi @apmcodes, it seems that you are following bull docs https://docs.bullmq.io/bull/patterns/custom-backoff-strategy and no bullmq docs https://docs.bullmq.io/guide/retrying-failing-jobs#custom-back-off-strategies, using typescript should mark that backoffStrategies is not a proper attribute for setting, it should be in singular **backoffStrategy**

**Comment by apmcodes** [comment]
@roggervalf thank you very much for clearing the confusion. It works now.
