### ISSUE TITLE
Feature Request: bulk add jobs across multiple queues

### ISSUE THREAD

**Issue by radicaled** [taskforcesh/bullmq#1772]
**Is your feature request related to a problem? Please describe.**
FlowProvider is a bit too complex to handle for my use-case  -- most of my workflow needs are sequential, not tree-like -- so I was attempting to build out a more simple Workflow system built on top of BullMQ using parent/child jobs to control the flow of steps. 

BullMQ doesn't expose public APIs to atomically add several jobs with different queues in one go, but FlowProvider internally does just that.

**Describe the solution you'd like**
I'd like to be able to bulk add jobs that span multiple queues, just like FlowProvider does internally!

**Describe alternatives you've considered**
Modifying each job so that it enqueues the next job on the proper queue after it's done, but that's brittle and makes it difficult to track where a workflow is and what it's doing. Being able to define all of the jobs atomically, in a single shot, would be best.

**Comment by roggervalf** [comment]
hi @radicaled, I think we do. We currently have addBulk method https://api.docs.bullmq.io/classes/FlowProducer.html#addBulk from FlowProducer, so you can add many jobs from different queues. Please take a look, hope it could help you

**Comment by radicaled** [comment]
I think you're telling me to add every job as a single Flow, using the parent job option to link them together so they can be executed sequentially, yeah?

If so, it seems that doesn't work. The following code snippet seems to only submits the first job in the list, "step1"; the other 2 jobs don't make it in unless I remove the "parent" option.

I used a single queue below for the sake of demonstrating the core problem:

```typescript
  const flow = new FlowProducer();

  // nanoid generates a unique id
  const step1Id = nanoid();
  const step2Id = nanoid();
  const step3Id = nanoid();

  flow.addBulk([
    {
      name: 'step1',
      queueName: 'default',
      opts: {
        jobId: step1Id,
      },
    },
    {
      name: 'step2',
      queueName: 'default',
      opts: {
        jobId: step2Id,
        parent: {
          id: step1Id,
          queue: 'default',
        },
      },
    },
    {
      name: 'step3',
      queueName: 'default',
      opts: {
        jobId: step3Id,
        parent: {
          id: step2Id,
          queue: 'default',
        },
      },
    },
  ]);
```

```typescript
const worker = new Worker('default', async (job) => {
    logger.info(`Received job ${job.name} on queue ${job.queueName}`);
  });
```

```
2023-03-31T17:52:51.693Z info:     Created Bull Queue 'default'
2023-03-31T17:53:44.778Z info:     Received job step1 on queue default
```

I use `bull-board` in my local development environment, and don't see the `step2` or `step3` there either.

**Comment by roggervalf** [comment]
hey @radicaled, I was thinking on the solution you wrote:

> Describe the solution you'd like
I'd like to be able to bulk add jobs that span multiple queues, just like FlowProvider does internally!

So in this case to add jobs in multiple queues, you only need to use addBulk method in this way:

```ts
const trees = await flow.addBulk([
  {
    name: 'job1',
    queueName: 'queue1'
  },
  {
    name: 'job2',
    queueName: 'queue2'
  },
  {
    name: 'step3',
    queueName: 'queue3',
  },
]);
```

If you don't provide parent options, these jobs will be added atomically on different queues

**Comment by roggervalf** [comment]
Now, about your example

> If so, it seems that doesn't work. The following code snippet seems to only submits the first job in the list, "step1"; the other 2 jobs don't make it in unless I remove the "parent" option.

there are some changes that you may need to do:

```ts
const flow = new FlowProducer();

// nanoid generates a unique id
const step1Id = nanoid();
const step2Id = nanoid();
const step3Id = nanoid();

flow.addBulk([
    {
      name: 'step1',
      queueName: 'default',
      opts: {
        jobId: step1Id,
      },
    },
    {
      name: 'step2',
      queueName: 'default',
      opts: {
        jobId: step2Id,
        parent: {
          id: step1Id,
          queue: 'bull:default',
        },
      },
    },
    {
      name: 'step3',
      queueName: 'default',
      opts: {
        jobId: step3Id,
        parent: {
          id: step2Id,
          queue: 'bull:default',
        },
      },
    },
]);
```
As in the link I provided about the example of chaining flows, queue is set using queueQualifiedName https://api.docs.bullmq.io/classes/Job.html#queueQualifiedName, that means prefix:queueName. In this way you will get the other jobs executed, but you should be aware that step1 and step2 could get errors if their children are not finished before them (because of pending dependencies), you can check this parent for waiting children https://docs.bullmq.io/patterns/process-step-jobs#waiting-children. Please check it when have some chance

**Comment by radicaled** [comment]
Thanks for all the information!

I can use it to solve my implementation problem now.
