### ISSUE TITLE
[Bug]: Intermittent Failure on Remote Redis

### ISSUE THREAD

**Issue by mcharawi** [taskforcesh/bullmq#1785]
### Version

v3.10.3

### Platform

NodeJS

### What happened?

We have a project (github.com/laudspeaker/laudspeaker) that uses BullMQ + Nest.js to enqueue messages for sending, and when we run the project using a local Redis docker container, jobs are enqueued and executed successfully, and all of the expected logging happens correctly. However, when we run the project using a remote Redis instance (hosted by Redis Labs), the jobs will intermittently be only partially executed; for example the message will send but there won't be any logging from `@OnWorkerEvent('completed')`, or some of the job's data will be ignored.

### How to reproduce.

Code for the processor:
```
import { OnWorkerEvent, Processor, WorkerHost } from '@nestjs/bullmq';
import { Inject, } from '@nestjs/common';
import { Job } from 'bullmq';
import { Injectable } from '@nestjs/common';
import Mailgun from 'mailgun.js';
import formData from 'form-data';

@Injectable()
@Processor('message')
export class MessageProcessor extends WorkerHost {
  constructor() {
    super();
  }

  async process(job: Job<any, any, string>): Promise<any> {
    const mailgun = new Mailgun(formData);
    const mg = mailgun.client({ username: 'api', key: job.data.key });
    const mailgunMessage = await mg.messages.create(job.data.domain, {
      from: `${job.data.from} <${job.data.email}@${job.data.domain}>`,
      to: job.data.to,
      subject: "subject",
      html: "",
    });
  }

  @OnWorkerEvent('error')
  onError() {
    console.log("There was an error...")
  }

    @OnWorkerEvent('completed')
  onCompleted() {
    console.log("Job Completed...")
  }
}

```

Code for the Producer:
```
import { Injectable } from '@nestjs/common';
import { Queue, QueueEvents } from 'bullmq';
import { InjectQueue } from '@nestjs/bullmq';

@Injectable()
export class Service {
  private queueEvents: QueueEvents;

  constructor(@InjectQueue('message') private readonly messageQueue: Queue) {
    this.queueEvents = new QueueEvents('messages', {
      connection: {
        host: process.env.REDIS_HOST ?? 'localhost',
        port: parseInt(process.env.REDIS_PORT),
        password: process.env.REDIS_PASSWORD,
      },
    });
  }

  async queueMessage(): Promise<string | undefined> {
    const job = await this.messageQueue.add('email', {
      domain: "example.com",
      email: "example",
      from: "example@example.com",
      key: process.env.MAILGUN_API_KEY,
      subject: "Test",
      text: "Hello",
      to: "test@example.com",
    });
    return Promise.resolve(job?.id);
  }
}

```

### Relevant log output

```shell
Job Completed...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Have you tried in a dashboard such as Taskforce.sh to check what is going on with the jobs? are they being processed or failed? Also, which Redis hosting are you using? There are some important pieces to consider for production here that may be to use for you: https://docs.bullmq.io/guide/going-to-production

**Comment by renrael-yzal** [comment]
Hey @mcharawi! I'm facing same issue, could you please tell me, how does it resolved?
