### ISSUE TITLE
queue#clean is undocumented

### ISSUE THREAD

**Issue by mikebridge** [taskforcesh/bullmq#1787]
Although [queue.clean](https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue.ts#L373-L402) is a legitimate function, it is no longer documented:

[https://docs.bullmq.io/guide/queues/removing-jobs](https://docs.bullmq.io/guide/queues/removing-jobs)

**Comment by manast** [comment]
Hmm, I agree the documentation is not so extensive, but it is documented: https://docs.bullmq.io/guide/queues/removing-jobs#clean 🤔
