### ISSUE TITLE
What's the relationship with https://github.com/OptimalBits/bull

### ISSUE THREAD

**Issue by mattwynne** [taskforcesh/bullmq#179]
Forgive my ignorance, but I got confused between the two projects, as they seem to be so similar.

Can you explain the relationship?

**Comment by mattwynne** [comment]
Aha! I found https://github.com/OptimalBits/bull#bullmq-4-beta in the bull docs.

So this is v4 of Bull? I think it would be helpful to make that clear in the README.

**Comment by dotob** [comment]
it would also be helpful to know what the idea behind the new version is. complete rewrite? why? improvements?

thanks for your work and the great bull v3 that i am using happily

**Comment by manast** [comment]
maybe this can shed som light: https://medium.com/@rockstudillo/beta-release-of-bullmq-4-0-867960aec51

**Comment by matjaeck** [comment]
How come "taskforcesh" sells tech support with remote access but have neither a company address, nor any business information or representatives on their site https://taskforce.sh/ and Terms, Privacy & Security, Status, Blog links are all not working? Doesn't really make a trustworthy impression tbh...
