### ISSUE TITLE
returning super.close () breaks compatibility, hence should bump major version

### ISSUE THREAD

**Issue by wenq1** [taskforcesh/bullmq#180]
As bullmq previously have bug in worker.close () - it sets a this.closing, which is never awaited, my application code manually awaits it:

````
workermq.close (true);
await workermq.closing (); // to make sure the promise is awaited
````

Now with the fix in 06d3d4f476444a2d2af8538d60cb2561a1915868, I have to change application code to 

````
await workermq.close (true);
````

This breaks the app compatibility, I think with sementic versioning you should bump the version to 1.9.0 rather than 1.8.6.

**Comment by wenq1** [comment]
Also in worker.close (), super.close () is no longer called?

What's the rational behind that? worker.close just closes the blocking connection, not the default one in QueueBase that should be closed by super.close ().

**Comment by manast** [comment]
if it breaks backwards compatibility it should be a major release, a miss from our side. The rationale behind not calling super.close is explained in this PR: https://github.com/taskforcesh/bullmq/pull/154

**Comment by manast** [comment]
however you are right, we are currently not closing properly the base client in the worker, this needs to be fixed asap.

**Comment by wenq1** [comment]
Thanks for taking care on this.

#154 is long standing. However, the fix is not satisfying.

I would suggest in the name of "defensive programming", use this.closing as a boolean flag rather than a promise. Your code already runs on the main event loop, hence single-threaded. There's little need to use the `this.closing = new Promise` style defence.

To be more specific, change

```
async close(force = false) {
    if (!this.closing) {
      this.closing = new Promise(async (resolve, reject) => {
        resolve();
      });
    }
    return this.closing;
  }
```

to 
```
async close(force = false) {
   if (this.closing)  return;
   
   this.closing = true;

    await closingJobs ()
```

**Comment by wenq1** [comment]
This should do the job. Please review and merge.

````
  async close(force = false) {
    if (this.closing) {
      return;
    }
    this.closing = true;

    this.emit('closing', 'closing queue');

    try {
      const client = await this.blockingConnection.client;

      await this.resume();
      if (!force) {
        await this.whenCurrentJobsFinished(false);
      } else {
        await client.disconnect();
      }
    } finally {
      this.timerManager.clearAllTimers();
      this.childPool && this.childPool.clean();
    }
    this.emit('closed');
  }
````

**Comment by lricoy** [comment]
This is probably not the place, but it seems somewhat related. 

I have an abstraction on `Bull.Queue` that I use to enqueue jobs. After upgrading to `bullmq` I've run into the problem that calling `queue.close()` would not release the Redis connection, ending up in a memory leak. There fore I had to also call `queue.disconnect()`. 

The same code using `bull` would not have this problem. Is this the expected API?

**Comment by wenq1** [comment]
You are correct. This is why this issue is marked as "bug"

**Comment by lricoy** [comment]
Thanks @wenq1! I just wasn't sure it would be the same for Worker and Queue classes :)

**Comment by wenq1** [comment]
I guess your best chance is to work around the issue by closing redis connection manually. In the worker, there's a "blocking connection" in Worker class and a "non-blocking" connection in the BaseQueue class. The non-blocking one is the issue.

**Comment by lricoy** [comment]
> I guess your best chance is to work around the issue by closing redis connection manually. There's a "blocking connection" in Worker class and a "non-blocking" connection in the BaseQueue class. The non-blocking one is the issue.
> 
> Also make sure lock your bullmq version in package.json. Semantic versioning won't protect you from this repo in this case.

Yeah. I am calling `disconnect` directly now. Thanks for the explanation and suggestions!

**Comment by manast** [comment]
Closing as this is an old issue that is not relevant anymore.
