### ISSUE TITLE
tsc error

### ISSUE THREAD

**Issue by wenq1** [taskforcesh/bullmq#181]
Running tsc for testing results in the following errors. Would you please take a look?

![image](https://user-images.githubusercontent.com/110781/79432637-ad0db980-7ffe-11ea-92ee-d390d5171532.png)

**Comment by wenq1** [comment]
This is reported in order to allow for other people to contribute to the code base. I find it extremely annoying when working with these sort of "linting errors" that should indeed be warnings, making any code fixes unwelcome despite the author's intention otherwise.

**Comment by manast** [comment]
But how did you run the compiler? we compile and lint all code before merging to master so there should not be any erros.

**Comment by wenq1** [comment]
Just downloading the code and tsc should do the job. 

However I tried it on node 10, 12, both will show these linting issue.

**Comment by manast** [comment]
works both on travis and locally for me:
![image](https://user-images.githubusercontent.com/95200/79446713-f9e19800-7fde-11ea-90bc-034c7542d9e6.png)

**Comment by wenq1** [comment]
Ummm. Let me have a check later again.

**Comment by wenq1** [comment]
![image](https://user-images.githubusercontent.com/110781/79462083-a34d7b80-8029-11ea-80e8-eaf22d758c7d.png)

Can you show me your tsc version by running `npx tsc`?

my yarn has version v1.19.1 (as in the image), a bit newer than yours.

**Comment by manast** [comment]
The yarn version does not matter. The tsc version should be the one installed in bullmq:
![image](https://user-images.githubusercontent.com/95200/79467878-910a1800-7ffe-11ea-96f1-746332a765ab.png)

**Comment by manast** [comment]
Check that your yarn.lock has the correct version of typescript:

![image](https://user-images.githubusercontent.com/95200/79468053-c44ca700-7ffe-11ea-9ffd-df5557e8b2e5.png)

**Comment by wenq1** [comment]
OK. marked as resolved. Difference between yarn and npm as package manager.
