### ISSUE TITLE
Latest bullmq is not supporting Eviction policy as  volatile-lru of Redis 

### ISSUE THREAD

**Issue by divyesh565** [taskforcesh/bullmq#1827]
### Version

3.10.4

### Platform

NodeJS

### What happened?

A bug happened!

On the start-up of the NodeJS server, BullMQ throws the below warning.

IMPORTANT! Eviction policy is volatile-lru. It should be "noeviction"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
https://docs.bullmq.io/guide/going-to-production#max-memory-policy
