### ISSUE TITLE
Fails to process any jobs when `keyPrefix` Redis option is set

### ISSUE THREAD

**Issue by queicherius** [taskforcesh/bullmq#183]
When the `ioredis` option `keyPrefix` is set ([see here](https://github.com/luin/ioredis/blob/master/API.md#new-redisport-host-options)), trying to process any job fails with `Missing lock for job 1 failed`. 

Reproduction Repo: https://github.com/queicherius-error-reporting/bullqm-keyprefix-problem

As far as I can tell this was working with Bull v3.

This also runs into an infinite loop of the job processing if the `attempts` of the job is > 1, likely because it errors before it can increase the count of the current attempt.

**Comment by manast** [comment]
In Bull v3 we basically removed the prefix, I think even better would be to actually raise an exception since it is an unsupported feature, specially problematic if you are reusing connections. But I am open to other suggestions.

**Comment by queicherius** [comment]
Oh I wasnt aware that Bull 3 stripped the prefix. In that case, I would agree that throwing an exception during initialization is the best way to handle this.

Since bull prefixes the key anyway it's not a big deal functionality-wise, I just stumbled into the issue when I copied over some configuration from my cache service that contained the prefix.

**Comment by wenq1** [comment]
My suggestion is to remove this feature all together, as it is not supported.

**Comment by brianschardt** [comment]
Im getting the same error, if I have attempts > 1. Any solutions?

**Comment by manast** [comment]
@brianschardt can you open a new issue with code that reproduces the issue, because attempts and prefix are unrelated settings.

**Comment by manast** [comment]
We raise an exception now if keyPrefix is used on a IORedis instance
