### ISSUE TITLE
[Bug]: Closing of queue when no jobs present

### ISSUE THREAD

**Issue by erdzan12** [taskforcesh/bullmq#1834]
### Version

v0.2.0

### Platform

Python

### What happened?

Why do we close the queue in this section when there are no more jobs in https://github.com/taskforcesh/bullmq/blob/master/python/bullmq/worker.py#L126 ?

I taught the worker should run in the background until we close it ourselves?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erdzan12** [comment]
I also notice now the code from the installed version is not the same as on master 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/32931186/232333369-e573aaa0-de11-4495-aa63-40345a05f1bd.png">

**Comment by manast** [comment]
It seems like a parenthesis is missing. We will do a new release tomorrow with the latest fixes.

**Comment by manast** [comment]
Let me know if it works as expected with version 0.3.0: https://pypi.org/project/bullmq/0.3.0/

**Comment by erdzan12** [comment]
yes it works now, thanks
