### ISSUE TITLE
Manually controlling the start of an job

### ISSUE THREAD

**Issue by SwenVogel** [taskforcesh/bullmq#1854]
Hi,

i would like to add jobs to an queue but prevent the automatic excecution of an job.
Instead i would prefer to manually start the job. 

I know that it is possible to set an delay of the job. Can i set the delay in some
way to infinite and update it later to start the job?

Does anybody know an solution for this requirement?

**Comment by SwenVogel** [comment]
Hi thank you for the quick response. I am using NestJS for my application. To use the changeDelay method i have to use the package @nestjs/bullmq. My question is this package production ready and stable as the @nestjs/bull package?

Because @nestjs/bullmq is not mentioned in the NestJS documentation.

**Comment by manast** [comment]
@SwenVogel it is documented, but maybe it is not updated in all places where Bull is mentioned: https://github.com/nestjs/bull
As a nest plugin is a thin layer on top of BullMQ I do not think the bullmq version is any less stable than the bull one.
