### ISSUE TITLE
JobsOptions `timeout` is in the interface but currently unsupported

### ISSUE THREAD

**Issue by queicherius** [taskforcesh/bullmq#186]
`timeout?: number;` is currently included in the `JobsOptions` interface, but has no effect, since it is commented out in the `worker` [here](https://github.com/taskforcesh/bullmq/blob/a15b1a1824c6863ecf3e5132e22924fc3ff161f6/src/classes/worker.ts#L308-L314).

What's the best way to handle timeouts right now? I used to wrap Bull v3 and throw my own error on timeout, which seems to suggest that it was not working great in there either. And of course, the promise is not actually aborted but continues in the background (even in the way I wrapped it).

**Comment by wenq1** [comment]
#136

**Comment by wenq1** [comment]
Wrap in a timeout promise yourself.

**Comment by queicherius** [comment]
Closing as duplicate of #136 (thanks @wenq1!)
