### ISSUE TITLE
Support for Redis 5 on GCP

### ISSUE THREAD

**Issue by marforon** [taskforcesh/bullmq#187]
I'm not able to establish a connection for my worker. Getting this error:
```
ReplyError: ERR unknown command `client`, with args beginning with: `setname`, `bull:Y29s`, 
    at parseError (/var/www/html/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/www/html/node_modules/redis-parser/lib/parser.js:302:14) {
"
```
Seems like it's a blocked command in GCP https://cloud.google.com/memorystore/docs/reference/redis-configs#blocked

Is there something I can do about it? Thanks in advance!

**Comment by marforon** [comment]
I found out that you are using client command only for tests to identify a worker connection. Could we not depend on it?

**Comment by manast** [comment]
maybe we can have an option that disables it, but by default it should be there so that we can ask for the workers that are currently active on a queue.

**Comment by willoughby** [comment]
Do they support Redis 5 when I looked a week ago it was Redis 4, I used a bitnami deployment instead

**Comment by marforon** [comment]
@willoughby Yes, they do. Currently it's in beta stage, but should be stable soon https://cloud.google.com/memorystore/docs/redis/supported-versions. 

The optional option for worker would be great. Ability to ask for a worker which is active on a queue is great, but until it's needed for actual run it shall not be a mandatory. I believe this will be a disabled command on most of managed memorystores.

**Comment by lricoy** [comment]
Hi @manast and @marforon  I've also encountered the same issue using GCP. Having an option to disable the commands so we can rely on GCP's MemoryStore would be great.

I am not sure what the implications of "ask for the workers that are currently active on a queue" are. How would this affect the queue failover ability? Does that mean that jobs would not have the `exactly-once` delivery?

I would be glad to help on this issue or others that may be more appropriate to first-time contributors to this project.

Could you give me any directions?

**Comment by jakedolan** [comment]
Somewhat of a side question related to this, but do you see GCP's MemoryStore lack of support for persistence an issue with using it for queuing with BullMQ?  
https://cloud.google.com/memorystore/docs/redis/redis-overview

That gave me pause to investigate it further. Would love to hear from others with more experience than myself in this area.

**Comment by david-wb** [comment]
Hello, I see this issue has been open several months, but I'm facing the exact same problem on GCP with Redis 5. How did you get around it?

**Comment by JosephScript** [comment]
Doesn't look like it's possible at all. Not until GCP adds the `client` command to supported commands, which there is no mention of. You're going to need to either choose another provider or roll your own via docker/k8/compute engine/bitnami, or some other method.

**Comment by marcjlyoung** [comment]
This was fixed inside of vanilla bull :) while we wait for the commit you can use the work around I posted to get the worker to connect. 

The [fix](https://github.com/taskforcesh/bullmq/issues/323)

**Comment by david-wb** [comment]
@marcjlyoung Thank you, yes that's exactly what I did actually. I hope it is fixed in bullmq soon.

**Comment by marcjlyoung** [comment]
This issue was fixed in the latest [release](https://github.com/taskforcesh/bullmq/commit/9aba722f41b390b5a5eeeeeba7c51b4f87cd87c7)
