### ISSUE TITLE
what is the best way to manually process a job with id?

### ISSUE THREAD

**Issue by ckxddd0324** [taskforcesh/bullmq#1870]
I am trying to build a queue with the worker (concurrency = 5). And the job will get updated by a callback(API request) from a 3rd party API. The job is pretty much in idle status and is waiting for the callback to come back and update the job status. It would be either to be completed or failed.

it seems like I can't call `moveToCompleted` or `moveToFailed` since it is required the next job and there are 5 concurrency 

I am building this queue with nest.js. 

**Test step/use case-**
1. create a queue with 5 concurrency processor
2. for sanity-wise, add a 10min timeout on the process function
3. add 7 jobs to queue
4. 5 of the jobs should be in active state
5. the other 2 of jobs are in waiting state
6. call the endpoint to update one of the job with the jobId
7. the number of active jobs is 4 and the number of the waiting jobs remains 2

- The expectation of this case would be 5 and number of waiting job should be 1

**Comment by manast** [comment]
Please read the documentation here: https://docs.bullmq.io/
You have a bunch of tutorials with working code examples here: https://blog.taskforce.sh/
