### ISSUE TITLE
[Bug]: error TS2305: Module '"cron-parser"' has no exported member 'ParserOptions'.

### ISSUE THREAD

**Issue by pedrodbaptista** [taskforcesh/bullmq#1875]
### Version

v3.12.0

### Platform

NodeJS

### What happened?

I'm getting this error `TS2305: Module '"cron-parser"' has no exported member 'ParserOptions'.` in the new version 3.12.0.
After some search i noticed that you have the same issue in a previous version (https://github.com/taskforcesh/bullmq/issues/1708). Probably should be something similar.
Please double check it.

### How to reproduce.

build: tsc -w (for example) you will noticed that the error occur. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @pedrodbaptista, I executed `tsc -w` and no errors were shown:
`Found 0 errors. Watching for file changes.`

**Comment by pedrodbaptista** [comment]
Hello @roggervalf . Thank you for the reply. Did you tried to delete all node_modules and yarn install again and try it?

**Comment by roggervalf** [comment]
hey @pedrodbaptista. I received the same result, no errors. Also I removed yarn.lock file when installing dependencies again
