### ISSUE TITLE
Job.createBulk  doesnt not obey custom jobID

### ISSUE THREAD

**Issue by willoughby** [taskforcesh/bullmq#189]
I have a set of jobs which I only ever want to be queued once at most.
``` javascript
const queue = [];

const services = await Services.find({
    uid: {
        $in: activeIds
    },
    active: true
});

for (const service of services) {
    try {
        queue.push({
            name: 'sync',
            data: {
                id: service._id.toString()
            },
            opts: {
                jobId: service._id.toString(),
                connection,
                priority: 1,
                removeOnComplete: true,
                removeOnFail: true,
                timeout: 30000,
            },
        });
    } catch (e) {
        console.log('Error Queueing services', e, e.stack);
    }
```

I have traced in createBulk in job.ts 88 its missing the 5th argument which allows the custom jobId

``` javascript
const jobInstances = jobs.map(
      job => new Job<T, R>(queue, job.name, job.data, job.opts, opts && opts.jobId),
);
```

**Comment by willoughby** [comment]
Pull request #190

**Comment by manast** [comment]
As I comment in the PR, it seems really strange to have job id as a fifth argument when it is already passed in the job options, I think this is what we need to improve and remove the fifth parameter alltogether, I do not have a valid explanation on to why it looks this way, maybe some copy/paste error from bull v3 but I am not sure.

**Comment by roggervalf** [comment]
passing a customId should be possible now as in this test case https://github.com/taskforcesh/bullmq/blob/master/tests/test_bulk.ts#L108-L139
