### ISSUE TITLE
Regarding a problem related to concurency

### ISSUE THREAD

**Issue by Riveer01** [taskforcesh/bullmq#1893]
Hello,
Just would like to ask one question: on a machine with multi-core CPUs, if I set concurrency=3,  does  bullmq allocate the jobs to only one CPU, or possibly to  different CPUs？Great thanks.
```
import { Worker, Job } from 'bullmq';

const worker = new Worker(
  queueName,
  async (job: Job) => {
    // Do something with job
    return 'some value';
  },
  { concurrency: 3 },
);
```

**Comment by manast** [comment]
The answer to this question is that it does not allocate jobs to different CPUs unless using sandboxed processors: https://docs.bullmq.io/guide/parallelism-and-concurrency
