### ISSUE TITLE
[Bug]: Process is crashed when an error in the worker happens in some cases

### ISSUE THREAD

**Issue by AlessioGr** [taskforcesh/bullmq#1895]
### Version

3.13.4

### Platform

NodeJS

### What happened?

Got this code for my worker:
```ts
  const worker = new Worker(
    queueName,
    async (job: Job, token: string) => {
      console.log(Date.now() + ' - Worker is processing a summaries job...');

      let putBackInQueue = false;
      try {
        // SOME CODE
...
      } catch (e) {
        console.warn('Error generating summaries. Retrying later.', e);
        putBackInQueue = true;
      }

      if (putBackInQueue) {
        console.log('Delaying job...');
        await job.moveToDelayed(Date.now() + 10000, token);
        console.log('Job delayed!');
        throw new DelayedError('Error generating summaries. Delaying job.');
        return;
      }
    

      return;
    },
    {
      autorun: true,
      connection: redisConnection,
      limiter: {
        max: 8,
        duration: 1000 * 10, // 10 seconds
      },
      concurrency: 4,
      removeOnComplete: {
        count: 2,
      },
      removeOnFail: {
        count: 10,
      },
      maxStalledCount: 10000000,
    },
  );
  worker.on('failed', (job: Job, error: Error) => {
    console.log('Summarize job failed. Error:', error);
  });
  worker.on('completed', async (job: Job, returnvalue) => {
    console.log('Summarize job completed.');
  });
}
```

Now, it could happen that there is an error in the try catch block. In this case, I wanna put the job back into the queue and try it again later!
The problem: when the error happens, while it is caught by the catch, once I run `await job.moveToDelayed(Date.now() + 10000, token);`, the error is thrown AGAIN and it crashes the entire node process. This is what then gets outputted into the console:

> 1684017408274 - Worker is processing a summaries job...
>   Creating summary for title xxx ... ...
> Error generating summaries. Retrying later. Error: Request failed with status code 429
>     at createError (/Users/alessio/Documents/GitHub/payload-plugin-ai-impl/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/Users/alessio/Documents/GitHub/payload-plugin-ai-impl/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/Users/alessio/Documents/GitHub/payload-plugin-ai-impl/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
>     at IncomingMessage.emit (node:events:525:35)
>     at IncomingMessage.emit (node:domain:489:12)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
> **(^This is the caught error)**
> 
> Delaying job...
> Error: Request failed with status code 429
>     at createError (/Users/alessio/Documents/GitHub/payload-plugin-ai-impl/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
>     at settle (/Users/alessio/Documents/GitHub/payload-plugin-ai-impl/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (/Users/alessio/Documents/GitHub/payload-plugin-ai-impl/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
>     at IncomingMessage.emit (node:events:525:35)
>     at IncomingMessage.emit (node:domain:489:12)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at processTicksAndRejections (node:internal/process/task_queues:82:21)
> **(^ when moveToDelayed is run, the same error is thrown again and the node process crashes). The "Job delayed!'" console log afterwards is NOT reached**

### How to reproduce.

I sadly do not have a minimal reproduction, but I can provide access to my project so you can test it out.

We're also willing to pay for one-off support on this matter, as it's important for us to get it resolved and we know that it's more work for you without a minimal reproduction.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Why aren't you using the built-in retry mechanism? 🤔

**Comment by manast** [comment]
Btw, I doubt the unhandled exception has "crashed the whole node process". Unhandled errors are caught automatically by the worker and the job moved to the failed status.

**Comment by AlessioGr** [comment]
> Why aren't you using the built-in retry mechanism? 🤔

So that I have more control over what I do with the job if an error happens in the future. E.g. if there's a rate-limit error, I'd delay it like that & implement some logic in the future to delay all future jobs as well (is that possible, by the way?).
If it's a different kind of error, e.g. some kind of misformatted request sent to an API, I'd like to fail the job immediately without it retrying in the future (#1894)

> Btw, I doubt the unhandled exception has "crashed the whole node process". Unhandled errors are caught automatically by the worker and the job moved to the failed status.

I'm using:
```ts
process.on('uncaughtException', function (error) {
  console.log(error.stack);
  console.log('Node NOT Exiting...');
})
```
to prevent it from crashing currently (very dirty & bad solution, I know), and it's triggering exactly that. Without it, it would crash the process.
It always happens right after the "Delaying job..." console log and does not run the "job delayed!" console log, so it must have something to do with the `await job.moveToDelayed(Date.now() + 10000, token);`.

**Comment by AlessioGr** [comment]
@manast I've just tried removing my try{}catch{} constellation and just let the error happen. No throwing DelayedError, no moveToDelayed, and it still happens.

I feel like, this might be related to the openai/langchain library's errors - maybe it has a problem catching those kinds of errors.

I'll try creating a reproduction

**Comment by AlessioGr** [comment]
@manast I've just created a reproduction here: https://github.com/AlessioGr/bullmq-repro

Especially take note of this line: https://github.com/AlessioGr/bullmq-repro/blob/main/src/Job.ts#L27

It seems that BullMQ might have an issue handling code with awaits like here, as removing this line fixes it.

Could you take a look? It's a minimal express server - you can test it locally using `yarn run dev`

**Comment by AlessioGr** [comment]
Okay, so specifically this seems to happen because the `const response = chat.call([` call is not awaited. Thus, the error is not caught by the try catch here: https://github.com/AlessioGr/bullmq/blob/master/src/classes/worker.ts#L673

Not sure if there's any way to get BullMQ to handle that as well?

**Comment by adicco** [comment]
@AlessioGr Are you sure that you are not having an exception thrown in an event handler? (i.e. `worker.on(...)`)

**Comment by manast** [comment]
> Okay, so specifically this seems to happen because the `const response = chat.call([` call is not awaited. Thus, the error is not caught by the try catch here: https://github.com/AlessioGr/bullmq/blob/master/src/classes/worker.ts#L673 as the error is probably thrown after the worker function itself has been processed.
> 
> Not sure if there's any way to get BullMQ to handle that as well?

This is how javascript works, if an asynchronous call throws an exception but you are not awaiting it, then that exception will be unhandled by definition.

**Comment by manast** [comment]
Seems like this can be closed now. Reopen if the issue actually was caused by a bug in BullMQ.
