### ISSUE TITLE
[Bug]: Error: Missing lock for job xxx. delayed when trying to move Job to failed

### ISSUE THREAD

**Issue by AlessioGr** [taskforcesh/bullmq#1896]
### Version

3.13.4

### Platform

NodeJS

### What happened?

(Follow-up on #1894)
Running

```ts
await job.moveToFailed(e, token);
throw new UnrecoverableError(e.response.data.detail);
```

Causes

Error: Missing lock for job xxx. delayed 

### How to reproduce.

https://github.com/AlessioGr/bullmq-repro/tree/repro-2

1. Clone
2. yarn install
3. yarn run dev

Make sure you are in the repro-2 branch of my reproduction. The main branch is a reproduction for a different issue, #1895

### Relevant log output

```shell
1684077272002 - Worker is processing a summaries job...
error, removing job
Error: Missing lock for job 170. delayed
    at Scripts.finishedErrors (/Users/alessio/Documents/GitHub/bullmq-repro/node_modules/bullmq/src/classes/scripts.ts:332:16)
    at Job.moveToFailed (/Users/alessio/Documents/GitHub/bullmq-repro/node_modules/bullmq/src/classes/job.ts:648:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (/Users/alessio/Documents/GitHub/bullmq-repro/node_modules/bullmq/src/classes/worker.ts:658:11)
    at async Worker.retryIfFailed (/Users/alessio/Documents/GitHub/bullmq-repro/node_modules/bullmq/src/classes/worker.ts:874:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
This works as designed. If you first move to failed and then throw an exception, the worker will try once again to move to failed and it fails since the jobs has already failed. You normally do not need to call moveToFailed, etc, this is handled automatically in the worker. Here some information on ```UnrecoverableError``` that you are using: https://docs.bullmq.io/guide/retrying-failing-jobs#stop-retrying-jobs

**Comment by AlessioGr** [comment]
> This works as designed. If you first move to failed and then throw an exception, the worker will try once again to move to failed and it fails since the jobs has already failed. You normally do not need to call moveToFailed, etc, this is handled automatically in the worker. Here some information on `UnrecoverableError` that you are using: https://docs.bullmq.io/guide/retrying-failing-jobs#stop-retrying-jobs

Ahhh, I see, thank you!
So, that means: use the moveToXXX methods only outside of workers, and inside a worker, throw the errors-only?

Does the same apply to `moveToDelayed` and `throw new DelayedError();` as well?

**Comment by manast** [comment]
There is no need to use moveToXXX methods for the vast majority of the cases. If you are new to BullMQ most likely you do not need them. Check the examples in the docs and in the blog https://blog.taskforce.sh/
