### ISSUE TITLE
Retrieving/deleting/updating the repeatable jobs

### ISSUE THREAD

**Issue by d-ivashchuk** [taskforcesh/bullmq#1910]
Hey @manast! thanks a lot for working on Bull 🙌 I am new to the library and had a question about it, I hope it's just my conceptual misunderstanding here.

When my user creates a job in my postgres database I want to add the repeatable job to Bull and associate this job with that postgres id:

```js
  async addJob(job: Job) {
    try {
      this.logger.log(`"addJob" runs: ${job.id}`);

      const bullJob = await this.jobQueue.add('crawl', job, {
        jobId: job.id,
        repeat: {
          cron: job.schedule,
        },
      });

      this.logger.log(
        `Job ${JSON.stringify(bullJob, null, 2)} has been added.`
      );
    } catch (error) {
      this.logger.error(error);
    }
  }
```

as you see this is pretty simple example here:

that's what's being logged for the newly created job:

```
Job {
  "id": "repeat:f298747f4cfe92a743bcd93b23404ebf:1684600200000",
  ...
```

as far as I get the id of the repeatalbe job is an ever changing thing. 

So back to my question - how can I make ensure I can retrieve a particular job at any given point in time to update/delete it? now I can't find the way to just use my postgres id to somehow fetch the job :/ 

To make it super clear what I want:

```js
async deleteJob(jobId: string) {
    try {
      // jobId is my postgres id that I used previously via job.id
      this.logger.log(`"deleteJob" runs: ${jobId}`);

      const job = await this.jobQueue.getJob(jobId);

      if (job) {
        await job.remove();
        this.logger.log(`Job ${jobId} has been removed.`);
      } else {
        this.logger.log(`Job ${jobId} does not exist.`);
      }
    } catch (error) {
      this.logger.error(error);
    }
  }
```

Thanks a lot for any tips!

**Comment by d-ivashchuk** [comment]
found this seemingly weird way to achieve what I want, so if it's a satisfactory option for delete I can use it:

```js
 async deleteJob({ jobId, schedule }: { jobId: string; schedule: string }) {
    try {
      this.logger.log(`"deleteJob" runs: ${jobId}`);

      const job = await this.jobQueue.removeRepeatableByKey(
        `crawl:${jobId}:::${schedule}`
      );
      this.logger.log(`Job ${job} has been deleted.`);
    } catch (error) {
      this.logger.error(error);
    }
  }
```

when it comes to updating I can probably delete and recreate the same job with new data

**Comment by ramiloif** [comment]
There is an api to get all the cron jobs in a queue

```
import { Queue } from 'bullmq';

const myQueue = new Queue('Paint');

const repeatableJobs = await myQueue.getRepeatableJobs();
```

https://docs.bullmq.io/guide/jobs/repeatable

And then you can filter in code .
Unless you have very large amount of them may not be officient

**Comment by roggervalf** [comment]
pls folks try last refactorization of repeatable jobs and let us know
