### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'bullmq.types'

### ISSUE THREAD

**Issue by shahafa** [taskforcesh/bullmq#1920]
### Version

v0.4.0

### Platform

Python

### What happened?

I'm working with python and trying to install `bullmq` with `poetry`
I ran the following command to install `bullmq`
`poetry add bullmq`

After importing bullmq in my application I get the following exception
```
2023-05-25 09:46:10     self.loader.exec_module(module)
2023-05-25 09:46:10   File "/root/.cache/pypoetry/virtualenvs/api-service-MATOk_fk-py3.10/lib/python3.10/site-packages/bullmq/__init__.py", line 10, in <module>
2023-05-25 09:46:10     from bullmq.queue import Queue
2023-05-25 09:46:10   File "/root/.cache/pypoetry/virtualenvs/api-service-MATOk_fk-py3.10/lib/python3.10/site-packages/ddtrace/internal/module.py", line 216, in _exec_module
2023-05-25 09:46:10     self.loader.exec_module(module)
2023-05-25 09:46:10   File "/root/.cache/pypoetry/virtualenvs/api-service-MATOk_fk-py3.10/lib/python3.10/site-packages/bullmq/queue.py", line 2, in <module>
2023-05-25 09:46:10     from bullmq.types import QueueOptions, RetryJobsOptions, JobOptions
2023-05-25 09:46:10 ModuleNotFoundError: No module named 'bullmq.types'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maretodoric** [comment]
This is true. 'types' folder is also missing when bullmq is installed from pip repo.
Workaround:
- git clone this repo
- copy folder `bullmq/python/bullmq/types` to `/root/.cache/pypoetry/virtualenvs/api-service-MATOk_fk-py3.10/lib/python3.10/site-packages/bullmq`

Not sure why this folder was not included in repo.

**Comment by manast** [comment]
@maretodoric do you know how to make pip to include this folder when building the package?

**Comment by maretodoric** [comment]
Sure i can and I'll make a PR as soon as i can to make it easier for developers, but that's the only issue, unfortunately.
It seems that some new version of lua scripts exist that are not put into package at all. From what i can see, those scripts (commands folder) are not in python/bullmq directory so i can only assume they are built by pipeline.

Workaround for that is completely manual at this point, by running "generateRawScripts.ts" typescript on src/commands as source folder.

But it would be good if that could be fixed.

I'm not at the PC at the moment, but error is something like "reprocessJob-6.lua missing" but reprocessJob-6
4.luais physically present on disk.

From this commit: https://github.com/taskforcesh/bullmq/commits/master/src/commands/reprocessJob-6.lua
We can se file is renamed but old file is still in pip repo.

**Comment by manast** [comment]
@maretodoric yes, I can fix the lua scripts, I guess we missed to update the list of scripts that should be included or something like that.

**Comment by maretodoric** [comment]
@manast great! you do that, in meantime I've created PR for missing types directory.

**Comment by manast** [comment]
The new release 0.4.1 should have resolved this issue: https://pypi.org/project/bullmq/0.4.1/

**Comment by maretodoric** [comment]
Awesome! This is fixed but new issue popped up unfortunately.
'semver' package is not listed in 'install_requires'. Looks like I've previously tested this on environment where i had it installed, now when i tested version 4.0.1 in freshly installed venv i get the error message.

I've created PR #1927 for this.

**Comment by roggervalf** [comment]
pr was merged, we can close this issue
