### ISSUE TITLE
putting tasks back in the queue

### ISSUE THREAD

**Issue by gWOLF3** [taskforcesh/bullmq#193]
is there an easy way or recommended way to put tasks back in the queue? 

Let's say a worker grabs a task but then finds that it cannot process it yet, is there a function just to drop it, or push back to bottom of queue. It would be kind of like a retry but thrown to bottom of queue stack, you could even add a minimum time for it to be allowed to be reprocessed. 

Any recommendations for how to handle this situation or something similar? If not, I think this would be a great feature.

**Comment by gWOLF3** [comment]
the simplest way I can think about doing this right now is actually connecting back as a Client inside of the Worker in the case that I want to add the task back into the queue - but this seems like a bad pattern.

**Comment by manast** [comment]
I do not think there is any robust workaround for something like this, so I will add it as an enhancement proposal.

**Comment by gWOLF3** [comment]
@manast As a workaround, I'm trying to add jobs back into the queue with a `delay`. 

However, this does not seem to be working as expected. If I add delay field in this case, the job is never added back to the queue. It seems as though if the delay is called the worker does not get a new job event, even after the delay is over. 

However, I believe when another job comes in, the worker does notice that there is the other job. This seems like not good behavior, bc there could be the case that, you add a job to a queue with a delay, and what happens if another job never comes in, then the job you added with the delay is lost forever. Either way something seems wrong here. 

code:
```
...
const worker = new Worker('Example', async job => {
console.log('hit job')
// process ....
  if (isNotReady) {
    await queue.add('job', { a: 'example' }, { delay: 5000 })
   console.log(`job not yet ready to be processed. added back to queue`)
  }
}
```
logs: 
```
hit job
job not yet ready to be processed. added back to queue.
job was completed
worker queue has been drained
```

**However** if I add the job back without a delay, it works as expected and the worker keeps iterating over the queue. It seems as though the delay field is somehow causing the job to never get added back to the queue. I've even tried with { delay: 1 }, and it still does not behave as expected. 

Am I missing something here?

**Comment by gWOLF3** [comment]
@manast - Nevermind - I realized I was missing a QueueScheduler to move the delayed jobs back into waiting mode.  Would be great if this was documented along with the delay functionality - had no idea I needed this for it to work!

**Comment by spearmootz** [comment]
this would be amazing.

**Comment by manast** [comment]
@gWOLF3 it is documented, I do not know how to make it more clear :/. https://docs.bullmq.io/guide/jobs/delayed

**Comment by spearmootz** [comment]
@manast i think it is more like a polling kind of a thing.

like, a job fired to do something, but the job itself checks something and says oh i cant do this yet.  At this time you can queue another job to check at a later time but i think what @gWOLF3 meant was something like 

job.delaySelf(arbitraryAmountOfTime)

**Comment by manast** [comment]
@spearmootz sounds like a useful feature, also in the case you are calling an external api and you get rate limited, you could delay yourself and try later. So basically we need to implement a special "completion" state that is not completing just delaying, similar to when a job fails and must be retried with some backoff delay.

**Comment by roggervalf** [comment]
this behavior is documented here https://docs.bullmq.io/patterns/process-step-jobs#delaying
