### ISSUE TITLE
I cannot pass a function to the Queue data

### ISSUE THREAD

**Issue by ThalyssonLeite** [taskforcesh/bullmq#1933]
### Version

v3.14.1

### Platform

NodeJS

### What happened?

I cannot pass a function to the Queue data, the data is stringifyed by JSON. But i need to pass a function to it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
Hi @ThalyssonLeite, job data is stringified in order to save it in redis. Instead of trying to pass an actual function, what about just the name of the function to know what execute later

**Comment by ThalyssonLeite** [comment]
after frying my brains i got on this, thank you.

Em qui., 1 de jun. de 2023 às 14:32, Rogger Valverde <
***@***.***> escreveu:
