### ISSUE TITLE
[Bug]: Certain Lua scripts are missing and semver not installed

### ISSUE THREAD

**Issue by felixDT** [taskforcesh/bullmq#1934]
### Version

v0.4.1

### Platform

Python

### What happened?

First part of the problem: 
As the title suggests, when installs version 0.4.1, 2 lua files are missing and those are: reprocessJob-6.lua and saveStacktrace-1.lua.
I manually downloaded them from the repo and added them to the bullmq > commands folder. After adding the missing lua files, everything worked without problem. It's as if when downloading the package with pip some files are lost during the installation

Second part:
The second issue is related to the semver not being installed with the other requirements when installing bullmq I know a PR as opened for this and from what I have seen it also as been merged, but the error is still present #1927.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Please try with version 0.4.2: https://pypi.org/project/bullmq/0.4.2/
