### ISSUE TITLE
Easy way to start a service in "worker mode" or "non-worker mode"

### ISSUE THREAD

**Issue by mjborys** [taskforcesh/bullmq#1935]
**Is your feature request related to a problem? Please describe.**
Maybe there is a best practice for this out there, but I couldn't find it and it seems like a common enough use case: We started our application with a single API cluster with BullMQ. As we scale, we notice latency in overall HTTP traffic service when jobs are being processed, so we want to deploy a separate cluster of job workers that can process the jobs while the main API cluster can handle the usual HTTP traffic. They would use the same code, but one would be behind the load balancer (the HTTP server) and one would not (the job worker). The HTTP server can still enqueue jobs, but should not process them.

**Describe the solution you'd like**
I would like a simple configuration option to turn off all job processors/workers on startup for an application. If it makes a difference, we're using NestJS.

**Describe alternatives you've considered**
My best idea for an implementation right now is leveraging the `autorun` option, but I think I need to do this on each Processor. I've wrapped the Processor decorator like below to make this a little easier, but we still need to remember to use `@CustomProcessor` everywhere to ensure the expected behavior: 

```
export function CustomProcessor(
  queueName: string,
  workerOptions: WorkerOptions,
): ClassDecorator {
  return Processor(queueName, {
    ...workerOptions,
    autorun: asBoolean(process.env.WORKER_MODE),
  });
}
```

**Comment by manast** [comment]
> **Is your feature request related to a problem? Please describe.**
> Maybe there is a best practice for this out there, but I couldn't find it and it seems like a common enough use case: We started our application with a single API cluster with BullMQ. As we scale, we notice latency in overall HTTP traffic service when jobs are being processed, so we want to deploy a separate cluster of job workers that can process the jobs while the main API cluster can handle the usual HTTP traffic. They would use the same code, but one would be behind the load balancer (the HTTP server) and one would not (the job worker). The HTTP server can still enqueue jobs, but should not process them.

This is the standard way of using BullMQ and indeed its main use case, i.e. offloading some service from heavy job processing.
However, I do not understand why you would need to turn off the job processors when starting the application 🤔

**Comment by mjborys** [comment]
@manast We would like to use a single code base (a NestJS app), as both our Job worker and an HTTP API. So the idea is that the same code could start up in "worker mode" (for the job server) or "non-worker mode" for the HTTP server. It seems to me an easy way to accomplish this would be to set something like `disableWorkers: true` on startup for the non-worker.

**Comment by manast** [comment]
For the workers part you do not need NestJS, it would be a very simple module, just instantiate a Worker class from BullMQ and you are all set.

**Comment by mjborys** [comment]
That is a fine conclusion for me, I'll close it out. 

Just to elaborate further, the reason we want to contain the workers within the existing NestJS app is:
1. Time to refactor and set up a whole new repo vs just a quick modification.
2. Easier for code reuse (shared types, utils and common functionality, configuration, etc).
