### ISSUE TITLE
[Bug]: Jobs stuck in waiting with sandbox processes

### ISSUE THREAD

**Issue by imdadahad** [taskforcesh/bullmq#1938]
### Version

v3.10.1

### Platform

NodeJS

### What happened?

We have recently setup a sandbox process to handle longer-running jobs. We are running an express app in TS using bullmq and redis. However, it seems as though the jobs are kept waiting. I've gathered this by seeing that the number of queue items `await queue.count()` is > 0 on the `queue.on("waiting")` listener.

The queue is setup as follows:

```
    const queue = new Queue(_c.BULLMQ_QUEUE_TASKS, {
        connection: {
            host: "localhost",
            port: 6379,
        },
    })
```

The sandbox worker sits in a file called `sandbox_worker.ts` which at the moment has some boilerplate code for debugging purposes:

```
const sandboxedWorkerHandler = async (job: SandboxedJob) => {
    setTimeout(() => {
        logger.info("FirstTask")
    }, 10000)
}

export default sandboxedWorkerHandler
```

The worker uses redis which is running locally:

```
    const worker = new Worker(
        _c.BULLMQ_QUEUE_TASKS,
        `${__dirname}/sandbox_worker.ts`,
        connection: {
            host: "localhost",
            port: 6379,
        },
    )
```

We have the `ready`, `error`, `failed`, `active` and `completed` listeners setup for the worker but none of these are triggered. This makes me question if the worker is indeed running. I've verified redis is running. 

Is there anything I am missing here with this setup?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I think that if you use the latest version (3.15.0) you would get an error telling you that the file is not supported or a syntax error, as you are trying to use directly a typescript file which is not compatible with node. You will need to compile the file first, then you can load it with the worker. This article may be of use to you: https://blog.taskforce.sh/using-typescript-with-bullmq/

**Comment by imdadahad** [comment]
Thank you, I've upgraded the library and made the necessary changes. Appreciate the help!
