### ISSUE TITLE
[Bug]: not exists reprocessJob-6.lua 

### ISSUE THREAD

**Issue by gonzafirewall** [taskforcesh/bullmq#1941]
### Version

v0.4.2

### Platform

Python

### What happened?

A bug happened!

FileNotFoundError: [Errno 2] No such file or directory: '<PATH>/.venv/lib/python3.10/site-packages/bullmq/commands/reprocessJob-6.lua'

I investigate a little and efectivelly in the code was trying to get the 6 but in the commands folder only exists the 4.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
same as https://github.com/taskforcesh/bullmq/issues/1952
