### ISSUE TITLE
delay should throw if its not a number

### ISSUE THREAD

**Issue by gWOLF3** [taskforcesh/bullmq#196]
i came across a scenario where `delay` was failing silently. 

it took a while to debug bc i was not seeing any errors. 

i saw that the library was being rewritten in TypeScript, maybe consider adding a type check for the delay field. In my case, I was accidentally passing in a string and it seems like the queue schduler did not even know how to handle that.

**Comment by manast** [comment]
where you using the library from typescript? if so the compiler should take care of it, did't it?

**Comment by roggervalf** [comment]
As @manast mentioned, I think would be sufficient to have typescript type checking
