### ISSUE TITLE
[stalled jobs] QueueScheduler is deprecated, then need feature for prevent stalled jobs

### ISSUE THREAD

**Issue by wlr-dev** [taskforcesh/bullmq#1976]
Hey!
I have a problem: I am using manual job processing, and when a worker crashes, the job gets stuck in the active status.

According to the documentation (https://docs.bullmq.io/guide/jobs/stalled), it states that "Stalled job checks will only work if there is at least one configured instance of QueueScheduler in the Queue."

 I would like to request the addition of a new feature for handling stalled jobs manually, given that QueueScheduler has been deprecated.

**Comment by roggervalf** [comment]
hi @wlr-dev, this is available in https://docs.bullmq.io/patterns/manually-fetching-jobs#checking-for-stalled-jobs manual-fetching-jobs pattern, please take a look
