### ISSUE TITLE
Get repeatable job by job key

### ISSUE THREAD

**Issue by ElFisherMan** [taskforcesh/bullmq#1977]
We are trying to be as much resilient as possible and to allow re-registering jobs (from mongoDB backup we keep since our redis can fail and we need to make sure we can recover from this).

Our solution is to have a re-registering code when redis is UP again. So we want to go over each job we kept in mongo collection backup and ask if it already exists in BullMQ.

But we can only get all the repeatable jobs and can't fetch them by job key.

We do see that there is a removeRepeatableByKey function so we want to be able to fetch a repeatable job by key.
Can you please add this ability?

**Comment by geeksilva97** [comment]
I can work on a pr if that makes sense.

**Comment by roggervalf** [comment]
base on last refactorization of repeatable jobs, it should be possible
