### ISSUE TITLE
[Bug]: Trouble with index.ts exports?

### ISSUE THREAD

**Issue by theDanielJLewis** [taskforcesh/bullmq#1992]
### Version

3.15.8

### Platform

NodeJS

### What happened?

Strap in! This is a weird one!

I can't run `next build` on a Next.js 13.4 project that imports destructured modules from an index, but `tsc` reports no errors!

Let's see if I can explain this well.

I have some files like this:

```
modules
  saveRatings.ts
  saveReviews.ts
  index.ts
worker.ts
```

saveRatings.ts looks like this:

```js
export async function saveRatings() {
// ...
}
```

saveReviews.ts looks like this:

```js
export async function saveReviews() {
// ...
}
```

index.ts looks like this:

```js
export * from './saveRatings';
export * from './saveReviews';
```

And then worker.ts looks like this:

```js
import { Worker, Job } from 'bullmq';
import { saveRatings, saveReviews } from '@/modules'; // This is the problematic line!
import { connection } from './queues';

const saveDataWorker = new Worker(
	'Save Data',
	async (job: Job) => {

		await Promise.all([
			saveRatings(results.ratings),
			saveReviews(results.reviews),
		]);

		return;
	},
	{
		connection,
	}
);
```

I use that `import { saveRatings, saveReviews } from '@/modules'` pattern just fine in other places and `next build` (with webpack) works fine. But using it inside this BullMQ worker file gives me the error on build (but not `tsc`):

```
./src/worker.ts + 5 modules
Cannot get final name for export 'saveRatings' of ./modules/index.ts
```

I can change that import pattern to skip index.ts:

```js
import { saveReviews } from '@/modules/saveReviews';
import { saveRatings } from '@/modules/saveRatings';
```

And then it builds just fine! HUH?

But I have the index.ts pattern in other places of my code and it works just fine!

And there is no difference whether I'm importing one module or several. It's importing from a file with `export * from …` that gives me trouble, but odly only inside the BullMQ `Worker` constructor.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I think this has long been resolved, so closing now.
