### ISSUE TITLE
Port sandbox processing from Bull 3.x

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq#2]
Sandbox processing is an important feature in bull 3 that allows processors to run on independent nodejs processes, this allows usage of multi-cpu deployments as well as protects the main process from crashing if one of the processors crash.

Sandboxed processors are implemented in bull 3 in 3 files:
- child-pool.js
- master.js
- sandbox.js

These should be ported to typescript and the old tests should pass:
- test_child_pool.js
- test_sandboxed_process.js

The port can be in an initial version identical in feature set, but for the final 4.0 version we would like to change something, namely the concurrency setting for sandboxed processors. Currently it can only be specified the concurrency per processors, meaning that only 1 nodejs process is used per processor, but it should also be possible to specify the concurrency per nodejs process, so that you could have for example 4 nodejs processes running 10 jobs in parallel.

**Comment by stansv** [comment]
https://github.com/taskforcesh/bullmq/pull/3
