### ISSUE TITLE
[Bug]: My worker does not get updated

### ISSUE THREAD

**Issue by abarbosa-godaddy** [taskforcesh/bullmq#2007]
### Version

v3.5.6

### Platform

NodeJS

### What happened?

Maybe it's more of a general question. But the behavior is causing some weird issues.

We have an application in Kubernetes and sometimes when e deploy a new version the worker doesn't get the most recent processor code. It keeps running as if it was the old version.

Is the processor code cached or something like that? I noticed when I retry all - from the bull board it usually gets the newer version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
But this is not really related to BullMQ but to your Kubernetes cluster. BullMQ is just a library, it does not have logic to handle processor code versions or anything like that.

**Comment by abarbosa-godaddy** [comment]
great. just to confirm. thank you. I think I found the issue.
