### ISSUE TITLE
Provide ESM

### ISSUE THREAD

**Issue by arlac77** [taskforcesh/bullmq#201]
As node now supports ESM natively. Can You please provide ESM directly.

By compiling ts into es2015

```
tsc --module es2015 --target es2015
```

```sh
  import { Queue, Worker } from "bullmq";
           ^^^^^
  SyntaxError: The requested module 'bullmq' does not provide an export named 'Queue'
```

**Comment by manast** [comment]
How can we do that without breaking older versions of node?

**Comment by arlac77** [comment]
[Conditional Exports](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_conditional_exports)
