### ISSUE TITLE
[Bug]: setTimeout is not a function

### ISSUE THREAD

**Issue by oanguenot** [taskforcesh/bullmq#2014]
### Version

v4.1.0

### Platform

NodeJS

### What happened?

Since verison v4.0.0 (this bug as been reproduced with version 4.1.0 too), and after a while, I encounter a crash in the bullMQ libraries.

### How to reproduce.

This happens on my mac with NodeJS/Redis where I have scheduled some jobs (repeatable).After a night without activity on the mac, I had this crash when I unlock my computer.

MacOs: 13.4
NodeJS: v18.15.0
BullMQ: 4.1.0

### Relevant log output

```shell
/Users/mac/github/myProject/node_modules/bullmq/dist/cjs/classes/worker.js:472
                this.extendLocksTimer = setTimeout(async () => {
                                        ^

TypeError: setTimeout is not a function
    at Worker.startLockExtenderTimer (/Users/mac/myProject/node_modules/bullmq/dist/cjs/classes/worker.js:472:41)
    at Timeout.<anonymous> (/Users/mac/github/myProject/node_modules/bullmq/dist/cjs/classes/worker.js:495:26)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.15.0
error Command failed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
It is quite difficult to believe this is an issue with BullMQ. We do not override any globals, so I do not think this is a bug that comes from our code. In any case, not a lot to go for unless we can get some code that reproduces it.

**Comment by oanguenot** [comment]
Thank for you quick comment, I will analyze deeper on my side to see from which components this issue could come

**Comment by oanguenot** [comment]
Closed as problem was not from bullmq
