### ISSUE TITLE
Queue job counts

### ISSUE THREAD

**Issue by ginesortizgs** [taskforcesh/bullmq#207]
Is there any way to get the jobCounts from a given queue? Like in the prev. version of bullmq
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queuegetjobcounts

Thanks

**Comment by manast** [comment]
There is a getJobCounts in the Queue class, you should get autocompletion with VSCode.

**Comment by roggervalf** [comment]
https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.queuegetters.getjobcounts.md is part of the api docs
