### ISSUE TITLE
[Bug]: Prioritized vs Normal Jobs

### ISSUE THREAD

**Issue by tatejones** [taskforcesh/bullmq#2081]
### Version

4.5

### Platform

NodeJS

### What happened?

Are prioritized jobs mutually exclusive from normal jobs (priority not specified)?

1. I have a FlowProducer that creates thousands of calculation jobs that do not have a priority set.  
2. A user can request a single calculation and this has a priority set.

The priority job does not take priority over the normal jobs and is executed last.

This previously work prior the introduction of the Prioritized job type.

### How to reproduce.

Will create a sample test case based on feedback.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tatejones** [comment]
Example test,

    it.only('should process a prioritized job according to its priority', async function () {
      this.timeout(5000);
      const completed: string[] = [];
      const worker = new Worker(
        queueName,
        job => {
          completed.push(job.id!);
          return delay(200);
        },
        { connection, autorun: false },
      );
      await worker.waitUntilReady();

      const completing = new Promise<void>(resolve => {
        worker.on(
          'completed',
          after(4, () => {
            expect(completed).to.be.eql(['d', 'a', 'b', 'c']);
            resolve();
          }),
        );
      });

      await queue.add('test', {}, { jobId: 'a' } );
      await queue.add('test', {}, { jobId: 'b' });
      await queue.add('test', {}, { jobId: 'c' });
      await queue.add('test', {}, { jobId: 'd', priority: 1 });

      worker.run();

      await completing;
    });


Result

  actual: [ 'a', 'b', 'c', 'd' ],
  expected: [ 'd', 'a', 'b', 'c' ],

jobs a, b and c don't have a priority.  c is executed last even though it has a priority.

**Comment by roggervalf** [comment]
hi @tatejones, the expected order in this case is correct [ 'a', 'b', 'c', 'd' ], this behavior is better explained in https://bullmq.io/news/062123/faster-priority-jobs/

> Jobs without specified priority now gain maximum priority. In the previous version, a job without priority was added at the end of the waitlist, requiring it to wait for all prioritized jobs to be processed first. Now, with priority jobs existing only in the priority set, any job added to the waitlist (i.e., jobs without priority) will be processed immediately. This adjustment actually brings more consistency if we consider priority 0 as the highest priority, implying it is logical for a job without assigned priority to be processed before any other job.

**Comment by tatejones** [comment]
ok.  Does it make sense to keep these jobs without priority?  Why not rename Prioritized to Waiting and have a default for jobs without priority?  In essence job without a priority actually has a priority of zero as you have indicated.  This will resolve the issue of not seeing these job is bullmq dashboard as Prioritized jobs are not visible.

**Comment by tatejones** [comment]
What I am trying to say, is there a use case for this old style jobs without priority?  why not replace them with the new prioritized jobs

**Comment by tatejones** [comment]
Thanks.  I will make the changes to our configuration.  

It means the bulk processing of the jobs will be slower as they will need a priority to allow the user submitted jobs to be prioritised with no priority (or provided a high priority).   Maybe a { priority: 0 } treats it as a normal job O(1).  Having this decoupling due to performance (non-functional requirements) is confusing for the developer. It could have been hidden under the hood.  eg. waiting and prioritized schema and metrics are a union.

The documentation will need to be clear that normal jobs without a priority have a default priority of 0 and will be processed at O(1).  Jobs with priority are slower and will take O(log(n)) and can never be priority above a normal job.

Hopefully bullmq Dashboard can start displaying these prioritised jobs.

**Comment by manast** [comment]
@tatejones the new changes make it faster not slower in all scenarios. If you do not use priorities the jobs will be picked from the wait list with O(1), and if you use priorities they will be picked with O(logN) instead of O(N) as it was before, there is no case that is slower now.
