### ISSUE TITLE
Idea: Skip uniqueness check

### ISSUE THREAD

**Issue by tayclark** [taskforcesh/bullmq#2086]
We've been using bullmq for some time now and have added our own implementation for handling unique jobs. 
- If a jobs wants to ensure it is added as unique, on the job definition we specify the properties passed as job _data_ that should be included in the uniqueness check (eg UNIQUE_BY = ['ownerId', 'customerId'])
- Optionally if a job wants to skip the uniqueness check we allow for that. If a job skips the uniqueness check and is allowed to bypass and be enqueued it is still consider in any future job add uniqueness check (ie `skipUniqueCheck: true`)

Our initial implementation paginated using `queue.getJobs` to check for uniqueness. This quickly didn't scale once we added jobs that had high volume or unpredictable volume
We've since move our uniqueness check outside of bull by adding the key to redis directly on job add and removing on job complete/failure. To handle for skipping the unique check we use a counter via incr/decr
This has quickly shown to not be feasible so we're looking at how we can potentially contribute to bull to add this functionality

With bullmq's uniqueness option via `jobId` we're able to solve for the first point but aren't able to solve for the second

Is there any existing feature or upcoming feature that may help us solve for this?

**Comment by manast** [comment]
This is a very specific requirement so I do not think it would fit in BullMQ unless there are more users in need of this feature. What would be needed is some kind of uniqueness test before calling the "addJob" lua script, but it must be done atomically, I am trying to think how we could allow to compose this script with the uniqueness check in such a way that we do not need to add it as a new feature to the library. 🤔

**Comment by jamesholcomb** [comment]
This request sounds similar in scope to the one I proposed in https://github.com/taskforcesh/bullmq/issues/240.  Even going back to the original bull issue from 2018 https://github.com/OptimalBits/bull/issues/1034, which at one time had a funding bounty on it.

**Comment by roggervalf** [comment]
as debounce logic is available since v5.11.0 I can close this issue
