### ISSUE TITLE
[Flows] How to have multiple parents depend on the same child ?

### ISSUE THREAD

**Issue by pbell23** [taskforcesh/bullmq#2087]
**Is your feature request related to a problem? Please describe.**

I am implementing a flow in order to have an orderly execution of several jobs but I am facing a problem. I need the end of a child job to trigger the execution of several parents. How to do that ?

**Describe the solution you'd like**

I'll describe my problem with an example from the doc : 

```javascript
import { FlowProducer } from 'bullmq';
const flowProducer = new FlowProducer();

const queueName = 'assembly-line';
const chain = await flowProducer.add({
  name: 'car',
  data: { step: 'engine' },
  queueName,
  children: [
    {
      name: 'car',
      data: { step: 'wheels' },
      queueName,
      children: [{ name: 'car', data: { step: 'chassis' }, queueName }],
    },
  ],
});
```
The order of processing would be: 'chassis', 'wheels' and finally 'engine'.

Now let's say I want to add the job 'doors' that needs to start once 'chassis' is done at the same time 'wheels' starts. How am I suppose to make both 'wheels' and 'doors' depend on the same child 'chassis' ?

**Comment by roggervalf** [comment]
hi @pbell23, from the title, looks like a duplicate from https://github.com/taskforcesh/bullmq/issues/1021, but for your use case, you said you need to add a new job (doors) after chassis is done, you just need to add this doors job just before finishing chassis process as a workaround:
```ts
const worker = new Worker(
  'queueName',
  async (job: Job, token: string) => {
          //... some work
          await queueName.add(
            'car',
            { step: 'doors' }
          );
          return; // here you can return some result
  },
  { connection },
);
```

**Comment by pbell23** [comment]
hi @roggervalf this is indeed a duplicate. Thanks for linking it. As for the workaround, I think it will work but it takes away all the point of using flows because there is no longer a parent child relationship with the doors job.

I'll close this issue and follow #1021 .
