### ISSUE TITLE
Pause issue

### ISSUE THREAD

**Issue by wenq1** [taskforcesh/bullmq#209]
When worker.pause () is [called](https://github.com/taskforcesh/bullmq/blob/75eeef2031fb862fd35b769cf81d12642bad811c/src/classes/worker.ts#L326), worker.paused is set to a Promise that is resolved when resume () is called.

This promise is [NEVER](https://github.com/taskforcesh/bullmq/blob/75eeef2031fb862fd35b769cf81d12642bad811c/src/classes/worker.ts#L130) returned in the runloop in getNextJob (). Note that getNextJob () is an async function which should be awaited!

It should be
```return this.paused```

rather than
```await this.paused```

in your code.

#155 is the earlier issue that you have ignored.

**Comment by manast** [comment]
I don't think you are correct in your analysis. Can you please provide a code that reproduces the issue?

**Comment by wenq1** [comment]
@manast  thanks for taking time on this.

Please take a look at [this line] (https://github.com/taskforcesh/bullmq/blob/75eeef2031fb862fd35b769cf81d12642bad811c/src/classes/worker.ts#L364) first.

pause () alone does not trigger the issue. After you pause, the line above does not reconnect the blocking connection (await Promise.all () will clear this.waiting flag). Hence when you resume () afterwards, you get infinite loop (and hence the crash) in your app.

I don't think your testcase correctly reproduce that. You pause () too early. You should wait until you get no job in the queue and getNextJob returns a blocking brpoplpush promise before you pause () to reproduce the issue.


```
    shouldReconnect = false;
    if (this.waiting) {
        await this.blockingConnection.disconnect());
        shouldReconnect = true;
    }

    if (this.processing) {
      await Promise.all(this.processing.keys());
    }

    if (shouldReconnect) await this.blockingConnection.reconnect();
```

**Comment by wenq1** [comment]
The ```return this.paused``` line mentioned in this issue is another matter, TBD later.
