### ISSUE TITLE
[Question] how to skip an instance of a repeatable job?

### ISSUE THREAD

**Issue by Valahaar** [taskforcesh/bullmq#2095]
Hi! I've searched through FAQs/docs/issues but I did not find anything related to this. If there was, I apologize.

I have some recurring jobs that occur, say, once a week. 
At any point in time, I would like to be able to tell BullMQ to skip the job coming in two weeks, for example (so not necessarily the next one).
Is there a preferred solution to do that? 

I thought of using a custom repeat strategy, but if I understood it correctly, it only gets invoked when the job is scheduled for the first time and then every time a worker completes a repeatable job.
Is the only solution to schedule a removal of the repeatable job by its key at any time before the job we want to skip and then add another one that starts after that? Does cron / rrule support any of these cases? I am not aware of the standards, unfortunately.

Thanks!

**Comment by Valahaar** [comment]
Sorry to bump and mention, but is there any chance you could give me some feedback about this? @manast maybe?

**Comment by manast** [comment]
There is no built-in solution to do this. If I had to implement this myself I would add the skip login in the job itself: just do nothing if this iteration is not supposed to run.

**Comment by Valahaar** [comment]
I see, thanks for your answer!
