### ISSUE TITLE
job.moveToDelayed is not a function

### ISSUE THREAD

**Issue by ashishnetworks** [taskforcesh/bullmq#2118]
### Version

3.15.1 and 4.7.0

### Platform

NodeJS

### What happened?

I'm not sure if it's a bug or what but I'm trying to use the `moveToDelayed` method but it's giving me the error that `job.moveToDelayed is not a function`  I tried checking if the method is written in the code and found that its written but somehow during the runtime, the method is not available. Is there any option that needs to be activated before using the method?

Here is the sample code

> const delayMs = 1000 * 10;
            const delayedTimestamp = Date.now() + delayMs;
            try {
                const delayResult = await job.moveToDelayed(delayedTimestamp, token);
                console.log({ delayresult: delayResult })
            } catch (err) {
                console.log('There was an error in calling delay method', err)
            }
            throw new DelayedError()

And it gives me following ourput

> There was an error in calling delay method TypeError: job.moveToDelayed is not a function

I also tried printing the entire job object and here is the output of the entire job object

> {
  job: {
    id: 'xBqj7gxBrK/874K63AGA6',
    name: '874K63AGA6',
    data: { userContext: [Object], request: [Object], headers: [Object] },
    opts: {
      attempts: 0,
      delay: 0,
      priority: 2,
      jobId: 'xBqj7gxBrK/874K63AGA6',
      timestamp: 1691249682619
    },
    progress: 0,
    attemptsMade: 1,
    processedOn: 1691249712474,
    timestamp: 1691249682619,
    stacktrace: '[]',
    returnvalue: 'null',
    queueName: 'reportQueue',
    prefix: 'bull',
    returnValue: null,
    updateProgress: [AsyncFunction: updateProgress],
    log: [AsyncFunction: log],
    updateData: [AsyncFunction: updateData]
  }
}

It can be clearly seen the method is not available in the object. But the question is why?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @ashishnetworks, we have a test case where moveToDelayed is part of job instance https://github.com/taskforcesh/bullmq/blob/master/tests/test_worker.ts#L2372, if you can provide a minimal reproducible test case that shows your issue we can take a look.

**Comment by ashishnetworks** [comment]
- I could not build the project locally so was not able to run test cases but yeah I tried running a similar code locally with installed bullMq version (just like your UTs) and I see that moveToDelayes method is working prefectly in normal function workers.
- Is it possible that moveTodelayed method is not working in my project code because we are using saboxed worker? if yes is there any workaround to move the received job to delayed queue for sometime>

**Comment by roggervalf** [comment]
hi @ashishnetworks, moveToDelayed is not available for sandboxed workers, also other methods are not available, but in case of this specific method I think could be possible, I opened a pr for it

**Comment by ashishnetworks** [comment]
thank you @roggervalf, I hope the PR works.

**Comment by aliscott** [comment]
Thanks @roggervalf 🙏. I was having a similar issue trying to use `moveToDelayed` in a Sandboxed Job. I tested #2122 for our use-case and it's working well for me 😄. Any ETA on when this will get into a release?

**Comment by roggervalf** [comment]
Hey guys, it should be part of v4.8.0
