### ISSUE TITLE
[Bug]: Queue.clean on `delayed` job is not working

### ISSUE THREAD

**Issue by felixmosh** [taskforcesh/bullmq#2124]
### Version

v4.x.0

### Platform

NodeJS

### What happened?

Cleaning all delayed jobs is not working, it returns an empty array (which should contain removed job ids).

Related to https://github.com/felixmosh/bull-board/issues/615

### How to reproduce.

1. Create a job with a delay of `1 min`
2. Call ` queue.clean(500, 1000, 'delayed')` on the queue after few secs.
3. Nothing happens, the waiting job is still in the queue, an empty array returned.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I think this works as designed actually, has to do with the grace period: https://github.com/taskforcesh/bullmq/blob/master/tests/test_clean.ts#L202

**Comment by manast** [comment]
Can you write a test case that does not pass? this one does:
https://github.com/taskforcesh/bullmq/blob/master/tests/test_clean.ts#L192C2-L200

**Comment by felixmosh** [comment]
https://github.com/taskforcesh/bullmq/pull/2130
