### ISSUE TITLE
[Bug]: Raise exception in try/except does not move job to failed

### ISSUE THREAD

**Issue by felixDT** [taskforcesh/bullmq#2126]
### Version

v1.10.0

### Platform

Python

### What happened?

Basically, if the processor for the worker, catches the exception, the job itself will not be moved to fail and will assume the job is just complete, here is some code that will clarify what I am trying to say!

 if an error is catch by this try/except block, the job will be marked as completed after doing the error handling inside the except block:
![image](https://github.com/taskforcesh/bullmq/assets/59975265/fda6d2d8-1d58-46b1-87d6-3346d78e40bd)

But, if the error is thrown as is, and not catch by any  try/except block, now the job will be moved to failed:
![image](https://github.com/taskforcesh/bullmq/assets/59975265/ba3bb375-e371-4563-86ed-adab6f344b42)

Another thing, If I try to use the function moveToFail from within the except block, I will this error:
`Error processing job Missing lock for job 28.finished`
`Error moving job to failed Missing lock for job 28.moveToFailed`
I think that, what is happening is, BullMQ trying to mark the job as complete, but I try to move it to the failed section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
This works as a design unless I am missing something. If you catch the errors yourself, then by all means the job has not failed, the worker can only detect exceptions if they are thrown by the processor function.

**Comment by felixDT** [comment]
I see, my bad, I went to check back how I used try catches in javascript with bullmq and realized I was throwing the error to bullmq from the catch block!

Thank you for the fast reply!
