### ISSUE TITLE
Priority is ignored when using the rate limiter

### ISSUE THREAD

**Issue by gcox** [taskforcesh/bullmq#214]
When jobs are delayed due to rate limiting, they are not processed in priority order. This is the same problem described in [Bull #1053](https://github.com/OptimalBits/bull/issues/1053), specifically [this comment](https://github.com/OptimalBits/bull/issues/1053#issuecomment-427430408).

Here is a full test case that can be added to the `test_rate_limiter.ts` test suite to demonstrate the problem: 
```typescript
  it('should obey priority', async function() {
    this.timeout(20000);

    const numJobs = 100;
    const priorityBuckets: { [key: string]: number } = {
      '1': 0,
      '2': 0,
      '3': 0,
      '4': 0,
    };

    await queue.pause();

    for (let i = 0; i < numJobs; i++) {
      const opts = (() => {
        if (i % 5 == 0) {
          return { priority: 1 };
        } else if (i % 4 == 0) {
          return { priority: 2 };
        } else if (i % 3 == 0) {
          return { priority: 3 };
        } else {
          return { priority: 4 };
        }
      })();

      priorityBuckets[opts.priority.toString()] =
        priorityBuckets[opts.priority.toString()] + 1;

      await queue.add('priority test', { id: i }, opts);
    }

    const priorityBucketsBefore = { ...priorityBuckets };
    const queueScheduler = new QueueScheduler(queueName);
    await queueScheduler.waitUntilReady();

    const worker = new Worker(
      queueName,
      async job => {
        const priority = job.opts.priority;

        priorityBuckets[priority.toString()] =
          priorityBuckets[priority.toString()] - 1;

        for (let p = 1; p < priority; p++) {
          if (priorityBuckets[p.toString()] > 0) {
            const before = JSON.stringify(priorityBucketsBefore);
            const after = JSON.stringify(priorityBuckets);
            throw new Error(
              `Priority was not enforced, job with priority ${priority} was processed before all jobs with priority ${p} were processed. Bucket counts before: ${before} / after: ${after}`,
            );
          }
        }

        return Promise.resolve();
      },
      {
        limiter: {
          max: 1,
          duration: 150,
        },
      },
    );
    await worker.waitUntilReady();

    await queue.resume();

    const result = new Promise((resolve, reject) => {
      queueEvents.on('failed', async err => {
        await worker.close();
        reject(err);
      });

      queueEvents.on(
        'completed',
        after(numJobs, () => {
          try {
            expect(every(priorityBuckets, value => value === 0)).to.eq(true);
            resolve();
          } catch (err) {
            reject(err);
          }
        }),
      );
    });

    await result;
    await worker.close();
    await queueScheduler.close();
  });
```

**Comment by manast** [comment]
thanks for the test case, I am looking into it.

**Comment by manast** [comment]
after some study of the problem, I concluded it is not really a bug, but more of a limitation. The way the rate limiter is implemented the priorities are not guaranteed, they are tried to be preserved in a best effort way. In order to guarantee priorities we would need to reimplement the rate limiter so that it works in a slightly different way, where no new jobs are processed from the queue until the rate limited jobs have been all processed. I have a enhancement story for this in legacy bull that I would like to work on as soon as possible.

**Comment by gcox** [comment]
Glad you pointed that out because that's another behavior I would never expect...jobs that are delayed due to being rate limited being processed *after* a new job is added to the queue. 

The reimplementation you're considering, do you intend to make it preserve FIFO/LIFO ordering as well as priority ordering? That would be a significant improvement over the current situation and may be what most people actually expect.

Besides the `moveToActive` script, are there any other major components to the rate limiting implementation?

**Comment by manast** [comment]
Basically the rate limited is implemented by reusing the delayed functionality, in order to solve the above issues it needs to be a separated ZSET for rate limited jobs with its own logic specific for rate limited. It will also be much better performance wise, etc. I had this issue planned for some time but have not found time to work on it.

**Comment by GeorgeWillaman** [comment]
Any estimation on when a possible fix will be? Just curious, no rush :)

**Comment by manast** [comment]
I actually back with this on the drawing board because the "grouped" rate limiter implemented recently makes my previous design worthless. It is actually so hard that maybe I will have to implement the new system without grouped rate limiters support and leave grouping with the old behaviour :/

**Comment by manast** [comment]
I merged a PR in bull since it suffers of the same issue, not backported to BullMQ yet: https://github.com/OptimalBits/bull/issues/1053

**Comment by jesusvalle** [comment]
Hello! As far as I can see, the priorities with limiter with groupKey are still messed up. Is there any alternative method to be able to execute them in an orderly way?

Thank you!

**Comment by manast** [comment]
@jesusvalle we are working on a permanent solution for this.

**Comment by jesusvalle** [comment]
> @jesusvalle we are working on a permanent solution for this.

Thank you so much.

**Comment by roggervalf** [comment]
As part of version 3, global rate limit and priority should work as expected, as groups is only supported in pro version, this issue could be solved in favor of https://github.com/taskforcesh/bullmq-pro-support/issues/23 that is still in progress
