### ISSUE TITLE
[Bug]: Is it an alpha version?

### ISSUE THREAD

**Issue by kfpo** [taskforcesh/bullmq#2147]
### Version

v4.7.3

### Platform

NodeJS

### What happened?

1. `log()` method of job instance doesn't work when called in processor fn
2. `stalled-check` has `bull` prefix regardless that queue has specified `prefix` option (`bull:some-queue-name:stalled-check`, and no, I don't use ioredis' `keyPrefix`)
3. `Queue#addBulk` method doesn't work with `repeat` + `pattern` option
4. Documentation looks like was written by copywriter:
	  - this
	    ```ts
	    /**
	     * Specify if the connection is shared.
	     */
	    sharedConnection?: boolean;
	    ```
	    What's the default value? Why does it matter? (& it does, with `true` all of mine jobs are stuck in `wait` stack)
	  - or this
	    ```
	    class Worker {
	      constructor(name: string, ...)
	    }
	    ```
	    `name` of what? Worker? No, turns out it needs to be the queue. But in [doc](https://docs.bullmq.io/guide/connections) it's just a `myqueue`/`myworker`. 
	    ```ts
		const myQueue = new Queue('myqueue', { connection: {
		  host: "myredis.taskforce.run",
		  port: 32856
		}});
		
		const myWorker = new Worker('myworker', async (job)=>{}, { connection: {
		  host: "myredis.taskforce.run",
		  port: 32856
		}});
	    ```

And that's just a start.

I know that it should be 1 github issue per bug/problem. That's not my question, I want to know if it's an alpha version or what?

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @kfpo,
1. we can use job.log in processor function https://github.com/taskforcesh/bullmq/blob/master/tests/test_worker.ts#L172, if it's not working in your case, a test case could help us to take a look
2.  it would be great if you can provide a test case where stalled-check is not working
3. addBulk method is not intended to work with repeatable jobs as [reference](https://github.com/OptimalBits/bull/issues/1731)
4. sharedConnection doesn't have a default value as it depends on what kind of connection you pass (if you pass a redis connection instance, it will be set as true, if is a object with redis options, it will be set as false)
5. yeah we should change that part of our documentation, queue and worker should have the same name

bullmq is not in alpha version, also consider that issues can be better organized if they include only one topic

**Comment by kfpo** [comment]
@roggervalf, thank you
1. Ok, I'll open new issue if I'll confirm it (this one was more like a butthurt, sorry for that, can't help myself)
2. `stalled-check` key didn't have the prefix because prefix wasn't specified for worker opts. Was using `queue.name` prop which won't contain prefix.
3. My bad, haven't this ts error since was doing it as `{ connection, ...restOpts }` so ts ignores extra opts
4. Got it, thanks
