### ISSUE TITLE
Skip Redis version check when passing in a Redis object 

### ISSUE THREAD

**Issue by hdoan741** [taskforcesh/bullmq#2148]
**Is your feature request related to a problem? Please describe.**
Hi, we're passing in a redis connection to the Queue/Worker constructor in order to reuse the connection. There is no way to pass in the `skipVersionCheck` flag with this. We're using Azure as the redis provider. They only support Redis 6.0.2. Our log 
system is being polluted with the version check.   

https://github.com/taskforcesh/bullmq/blob/1020376dd7144ac432642e3ba19aa056e85b1baf/src/classes/redis-connection.ts#L185-L205

**Describe the solution you'd like**
A way to skip version check when passing in a redis connection,

e.g. `new Queue(name, { connection: sharedRedis, skipVersionCheck: true })`

**Describe alternatives you've considered**
Upgrade Redis, but Azure only provide supports for Redis 4 and Redis 6.0

**Additional context**

**Comment by roggervalf** [comment]
hi @hdoan741, sounds like we are missing this option for redis instances that are passed as connection. I'll take a look.

**Comment by hdoan741** [comment]
Thank you @roggervalf !
