### ISSUE TITLE
How to handle and restart worker on Missing lock for job xx failed error

### ISSUE THREAD

**Issue by willoughby** [taskforcesh/bullmq#215]
My job has a maximum timeout of 1 minute and this has been tripped on production a few times but is noticeable when breakpointing code in development. My problem is once this error is logged the worker just sits there idle i'm not sure if this is a bug or misconfiguration on my part but I do have to reboot workers in production. It would be helpfull if the error was not just logged but thrown.

```
            return Queue.add(
                'sync',
                { id: entity._id },
                {
                    jobId: entity._id,
                    connection,
                    removeOnComplete: true,
                    removeOnFail: true,
                    timeout: 60000,
                }
            );
```
```
 //worker.ts 81
   this.run().catch(error => {
      console.error(error);
    });
```

```
Error: Missing lock for job 5eca7d8094604b3844de26af failed
worker.ts:82
message:"Missing lock for job 5eca7d8094604b3844de26af failed"
stack:"Error: Missing lock for job 5eca7d8094604b3844de26af failed
    at Function.finishedErrors (/Users/nathan/Documents/GitHub/workers/node_modules/bullmq/dist/classes/scripts.js:135:24)
    at Job.moveToFailed (/Users/nathan/Documents/GitHub/workers/node_modules/bullmq/dist/classes/job.js:197:41)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
```

**Comment by zhennann** [comment]
<img width="1202" alt="1" src="https://user-images.githubusercontent.com/24246985/83258301-986d3580-a1e8-11ea-8161-803baab18ae5.png">

**Comment by manast** [comment]
@willoughby seems like a bug, but I am not sure without complete test code. So basically you mean that when the timeout is hit you get the error on the missing lock?

**Comment by willoughby** [comment]
Yeah its logged to the console, and the worker pretty much turns into a lemon and does nothing more until a reboot.

**Comment by zhennann** [comment]
@manast 
<img width="843" alt="1" src="https://user-images.githubusercontent.com/24246985/83315248-3a286d00-a251-11ea-827d-69722b132748.png">
<img width="639" alt="2" src="https://user-images.githubusercontent.com/24246985/83315252-3eed2100-a251-11ea-8c81-2c55a567dcb8.png">

When the error of `missing lock for job` occurred, `this.emit('error', e);` will be performed, and which will caused the `this.run().catch(error ...`

**Comment by willoughby** [comment]
okay great, but shouldn't the worker be able to recover itself. Im using the workers in kubernets so can throw an error to get them to reboot

**Comment by manast** [comment]
@willoughby if you listen to the error event then no exception will be raised so the loop should not break. It is a bit unfortunate that nodejs throws an exception when emitting an error if no listener is listening to it.

**Comment by willoughby** [comment]
Oh thats perfect thanks

**Comment by deman4ik** [comment]
@manast @willoughby 
Hello. 
I have same issue

```
2020-10-19T04:45:15.322934182Z Error: Missing lock for job edfaa200-8617-4541-b0b2-dd481b4a2ded failed
2020-10-19T04:45:15.322985283Z     at Function.finishedErrors (/usr/src/app/node_modules/bullmq/dist/classes/scripts.js:136:24)
2020-10-19T04:45:15.322989346Z     at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/classes/job.js:198:41)
2020-10-19T04:45:15.322992603Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-10-19T04:45:15.322995641Z     at async handleFailed (/usr/src/app/node_modules/bullmq/dist/classes/worker.js:208:17)
```

worker just hangs after that.

How to correctly catch that exception?

**Comment by manast** [comment]
@deman4ik the correct way was to attach a listener for the error event, but we do this internally now so it is not needed anymore, however the release has not been performed yet, fixing the automatic release procedure using github actions, as soon as it works it will be released automatically.

**Comment by kodeine** [comment]
@manast was this fixed? i am still getting this on latest version!

**Comment by manast** [comment]
@kodeine what exactly are you still getting on the last version?

**Comment by Sedatb23** [comment]
@manast The issue regarding 'Missing lock for job xx', still exists. You mentioned that there should be an internal listener now, I can't however seem to find it?

**Comment by manast** [comment]
@Sedatb23 I am not sure what issue you are referring to. It is best that you open a new issue with code that demonstrates a bug so that I can look into it.
