### ISSUE TITLE
Make sure repeatableJob gets removed

### ISSUE THREAD

**Issue by rileyai-dev** [taskforcesh/bullmq#2153]
**Is your feature request related to a problem? Please describe.**
I would like to make sure a repeatable job has been removed. Right now, when calling removeRepeatableJob, I only get true or false. It is not clear to me if it failed because it couldn't find the repeatable job or for another reason. Therefore it is hard to know if there was a job that couldn't be removed or if there is no job.

**Describe the solution you'd like**
Two options:
- If it returns false only when it couldn't find it then specify this in the doc
- If it returns false for other reasons, maybe throw an error in other cases so we can handle all the cases.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by manast** [comment]
The current documentation should be clear enough now: https://docs.bullmq.io/guide/job-schedulers/manage-job-schedulers#remove-job-scheduler
Reopen if that is not the case.
