### ISSUE TITLE
[Bug]: Job doesn't complete and doesn't mark as stalled, can't add same job with same id

### ISSUE THREAD

**Issue by zshnb** [taskforcesh/bullmq#2154]
### Version

v3.10.1

### Platform

NodeJS

### What happened?

A bug happened!
i have enqueue a job with custom id, the worker done the job and return to the queue, and the queue's handle function doesn't complete, so i can't add again with this jobId, it seems this job is retain in the queue forever, how can i fix this problem?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @zshnb, we may need a test case to reproduce your it

**Comment by zshnb** [comment]
> hi @zshnb, we may need a test case to reproduce it

yes, i can give you some code
```
// worker
function doSomething() {
  ....
  return 'ok'
}
// queue
function handleComplete(args: {jobId, data}) {
  ....
  sleep(5000)
  exit(-1)
  .....
}
```
after exit, you can try add job with same id again to see if worker receive the job

**Comment by manast** [comment]
@zshnb we need a minimal test case but something that we can run, what you posted above is not enough.
