### ISSUE TITLE
How can i know if i job is ignored when add into the queue

### ISSUE THREAD

**Issue by zshnb** [taskforcesh/bullmq#2155]
**Is your feature request related to a problem? Please describe.**
i have some operation depends on jobs' add result, when a job add into queue, i will set a status in the redis. The job will be added multi times with same id, but i only want to set status once. so if the job add is success, i can set the status, otherwise i do nothing.

**Describe the solution you'd like**
so i want to get some result when add job, like `const status = await queue.add('queue', {}, {})`

**Describe alternatives you've considered**

**Additional context**

**Comment by roggervalf** [comment]
hi @zshnb, for now we only have the duplicated event to differenciate https://api.docs.bullmq.io/interfaces/v4.QueueEventsListener.html#duplicated

**Comment by zshnb** [comment]
yes i see this event too, i will try use this event, thank you
