### ISSUE TITLE
Easy way to get the job result from the queue?

### ISSUE THREAD

**Issue by queicherius** [taskforcesh/bullmq#216]
I am trying to get the result of a job from the process that queued the job. I tried the following:

```js
const { Queue, QueueEvents } = require('bullmq')

const myQueue = new Queue('foo')
const queueEvents = new QueueEvents('foo')

async function addJobs() {
  const job = await myQueue.add('myJobName', { qux: 'baz' })
  console.log('Queued')

  await job.waitUntilFinished(queueEvents)
  console.log('Done') // This correctly waits until the job is done :)

  console.log(job.returnvalue) // This is always `null`, and I cant see any other way to get the result :(
}

addJobs()
```

Is this use-case supported by this module?

**Comment by manast** [comment]
In a distributed system that is not a robust way to pass results from one subsystem to another. You should use queues for passing data, so just create another queue and send the result back with it.

**Comment by queicherius** [comment]
So would you say that a feature like this is out of scope for BullMQ?

If a job is queued with the option `passReturnValue` the following interface is enabled:

```js
const job = await myQueue.add('myJobName', { qux: 'baz' }, { passReturnValue: true })
await job.waitUntilFinished(queueEvents)
const returnValue = await job.getReturnValue()
```

The following would happen internally:

1. If `passReturnValue` is set, a random ID is generated and attached to the job options, as `passReturnValueId`
2. On completion, the worker serializes & writes the return value into Redis with the key `passReturnValueId`, possibly with a short expiry time
3. `getReturnValue` just reads out the result from Redis via the ID & deserializes it

Some background why I would like that interface: sometimes I would like to have an API call stall until the result of a function is available, but without blocking the thread / using the cycles of the API with the actual work of the function (so it has to run on a worker server). This enables queueless processing APIs like for example https://screenshotlayer.com/

**Comment by manast** [comment]
In order to get the return value of a job you just need to read the job again:

```ts
(await Job.fromId(job.id)).returnvalue
```

**Comment by queicherius** [comment]
Oh sweet, that is exactly what I was looking for.

For other people that might find this issue, this is the code:

```js
async function addJobs() {
  const job = await myQueue.add('myJobName', { qux: 'baz' })
  console.log('Queued')

  await job.waitUntilFinished(queueEvents)
  console.log('Done') // This correctly waits until the job is done :)
  
  // This gets the job return data :)
  const xxx = await Job.fromId(myQueue, job.id)
  console.log(xxx)
  console.log(xxx.returnvalue)
}
```

Also it only works with `removeOnComplete: false` (as you would expect).

---

@manast I also want to say thank you for the amazing library, I use it over at https://gw2efficiency.com/ to process 18 million jobs / month and never had any issues 💯

**Comment by gajus** [comment]
Would be nice for this to be documented here https://docs.bullmq.io/guide/returning-job-data (or at least link to this issue while the docs are being written).

**Comment by gajus** [comment]
> In a distributed system that is not a robust way to pass results from one subsystem to another. You should use queues for passing data, so just create another queue and send the result back with it.

Is there any downside to the method described by @queicherius?

**Comment by antirek** [comment]
without waitUntilFinished #294

**Comment by darrylcousins** [comment]
Brilliant.

As @gajus mentioned. It would be nice for this to be documented here https://docs.bullmq.io/guide/returning-job-data 

Ngā mihi. Darryl

**Comment by bartoszhernas** [comment]
> > In a distributed system that is not a robust way to pass results from one subsystem to another. You should use queues for passing data, so just create another queue and send the result back with it.
> 
> Is there any downside to the method described by @queicherius?

I would imagine that the best way is that you schedule JobA, then the process can finish and exit (return http response for example). JobA when done can then pass the data to JobB etc. Waiting for JobA to finish, get the data and then to send it to JobB is wasteful (one more process is stuck keeping tabs/watching the jobs). 

I believe now it got even nicer with Flow of Jobs
https://docs.bullmq.io/guide/flows

**Comment by manast** [comment]
Also: https://blog.taskforce.sh/do-not-wait-for-your-jobs-to-complete/
