### ISSUE TITLE
When does a retry occur? Next in queue or End of Queue

### ISSUE THREAD

**Issue by brendann993** [taskforcesh/bullmq#2162]
I can't seem to find a clear answer to when a job is set to retry on failure does the retry occur

- Immediately e.g. using the same worker instance.
- Next Job in queue (pending any delay set).
- End of queue.

I thought I found something saying it gets re-added back the end beginning of queue however my job sits there in waiting status and other jobs in the queue continue to start and be processed.
I checked in Redis in the waiting status and can see the job is there and listed as id 1 but id 2 is the last job in my queue so I assume that means the job is retried after all other jobs?

If the retry occurs after all other jobs, is there a way to push it to the front of the queue? If I set the queue to LIFO will the retry occur before other jobs? (The order of the jobs is not important, just that retries occur next)

**Comment by roggervalf** [comment]
hi @brendann993, I'll try to answer your questions:
1. if you have more than 1 worker, there is no guarantee that your retried job will be picked by the same worker. it can be picked by a different worker.
2. Retried jobs will be moved to delay (when the backoff strategy returns a number greater than 0), after the delay they are added to wait or prioritized states, it will depend if your jobs use priorities or not.
3. Jobs are re-added back to the end of the queue (wait state) when they don't have priority (by default is 0)
There is a way to retry your job and place it at the head of wait state, lifo option should be provided as true and your backoff strategy should return 0, that's a way to allow that behavior.

**Comment by brendann993** [comment]
Thanks for the information @roggervalf with that knowledge I can will try lifo or maybe setting priorty on job if it fails
