### ISSUE TITLE
[Bug]: Expiry time not getting applied to flow job 

### ISSUE THREAD

**Issue by Roundaround** [taskforcesh/bullmq#2165]
### Version

4.8.0

### Platform

NodeJS

### What happened?

I am spinning up a large number of jobs using a FlowProducer and have noticed that my Redis store is filling up with old job data. I tried setting a max age inside the `removeOnComplete` options for the worker, the flow producer, the flow producer's queue/default job options, and on the flow's children, but none of them set an expiry date for the data.

### How to reproduce.

I'm using simple async functions for the processors, and queuing up a flow that basically just compiles all the children results together. I run them in separate queues with a worker instantiated for both. Finally I'm setting removeOnComplete props on everything I possibly can.

```typescript
const connection = {
  // ...
};

const parentWorker = new Worker('parent', async (job: Job) => {
  return Object.values(await job.getChildrenValues());
}, {
  connection,
  removeOnComplete: {
    age: 60 * 60,
  },
);

const childWorker = new Worker('child', async (job: Job) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(job.data);
    }, 1000);
  });
}, {
  connection,
  removeOnComplete: {
    age: 60 * 60,
  },
);

const flowProducer = new FlowProducer({ connection });
flowProducer.add({
  name: 'parent',
  queueName: 'parent',
  opts: {
    removeOnComplete: {
      age: 60 * 60,
    },
  },
  children: [
    {
      name: 'child',
      queueName: 'child',
      data: {num: 1},
      opts: {
        removeOnComplete: {
          age: 60 * 60,
        },
      },
    },
    {
      name: 'child',
      queueName: 'child',
      data: {num: 2},
      opts: {
        removeOnComplete: {
          age: 60 * 60,
        },
      },
    },
    {
      name: 'child',
      queueName: 'child',
      data: {num: 3},
      opts: {
        removeOnComplete: {
          age: 60 * 60,
        },
      },
    },
  ],
}, {
  queuesOptions: {
    parent: {
      defaultJobOptions: {
        removeOnComplete: {
          age: 60 * 60,
        },
      },
    },
    child: {
      defaultJobOptions: {
        removeOnComplete: {
          age: 60 * 60,
        },
      },
    },
  },
});
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @Roundaround, I created a test case that is working good, also I noticed that you are not passing removeOnComplete option in a right way on queuesOptions, ts can detect this can of errors I suppose you are using only js syntax. You can change that option to:
```
queuesOptions: {
  parent: {
    defaultJobOptions: {
      removeOnComplete: {
        age: 60 * 60
      }
    }
  },
  child: {
    defaultJobOptions: {
      removeOnComplete: {
        age: 60 * 60
      }
    }
  }
}
```

**Comment by Roundaround** [comment]
> hi @Roundaround, I created a test case that is working good, also I noticed that you are not passing removeOnComplete option in a right way on queuesOptions, ts can detect this can of errors I suppose you are using only js syntax. You can change that option to:
> 
> ```
> queuesOptions: {
>   parent: {
>     defaultJobOptions: {
>       removeOnComplete: {
>         age: 60 * 60
>       }
>     }
>   },
>   child: {
>     defaultJobOptions: {
>       removeOnComplete: {
>         age: 60 * 60
>       }
>     }
>   }
> }
> ```

Sorry, that was a typo. I was trying to simplify my code into the minimum block necessary for the bug report. My original code has the queue names defined as strings so I was originally doing a `[manifestImportQueueName]: {...}` kind of thing. Seems I accidentally removed too much. I've updated the snipit in my original question

**Comment by roggervalf** [comment]
hey @Roundaround, the test that I merge is following the same pattern but it's working fine, maybe you can try to update my test case and see if you can reproduce your issue

**Comment by Roundaround** [comment]
I peeked through the lua scripts and I understand now that even though I set a max age it lazily removes keys the next time I queue up a job. Is there any way I could rely on Redis's built-in TTL infrastructure instead to keep my memory footprint as low as possible? Not to mention this lazy removal puts the performance hit at the time of adding jobs to the queue, whereas Redis's built-in mechanisms would run it in the background after the job is done

**Comment by manast** [comment]
Redis provides only the EXPIRE command for keys and it cannot be used in BullMQ, as even though a job is represented by a key, there are references to it in different places that also would need to be cleaned up. Furthermore, Redis EXPIRE works in the same way, i.e. is lazy. In any case, you can combine max age with max number of kept jobs so in practice you can manage pretty well the maximum memory consumption.

**Comment by manast** [comment]
another thing regarding performance, auto-removing a job is pretty fast, better to do it incrementally when needed instead of having a "stop-the-world" clean-up method, but with the current BullMQ API you could easily implement your own clean-up function that runs when you want.

**Comment by Roundaround** [comment]
I understand. Thanks for taking the time to explain!
