### ISSUE TITLE
[Bug]: jobs updateProgress doesn't work

### ISSUE THREAD

**Issue by zshnb** [taskforcesh/bullmq#2186]
### Version

v4.8.0

### Platform

NodeJS

### What happened?

I call jobs.updateProgress in a interval callback, which period is 2s. But after some trigger in the QueueEvent, i can't see remain's trigger callback happen, it looks like `progress` event has some limitation on it.

### How to reproduce.

worker.ts
```
  await execFfmpeg(ffmpegCmd, {
    override: true,
    onProgress: (data: FfmpegExecProgress) => {
      logger.info(`frames: ${data.frames}, speed: ${data.speed}`)
      job.updateProgress({
        frames: data.frames,
        speed: data.speed,
        totalFrames: getFrames(),
        index
      })
    }
  })

```
queue.ts
```
    handleProgressEvent: async (args: { jobId: string, data: number | object }, id: string) => {
      const {frames, speed, totalFrames} = args.data as TranscodeProgressData
      const taskId = getTaskIdByJobId(args.jobId)
      const index = getTranscodeIndex(args.jobId)
      await setTranscodeCache(taskId, index, {
        progress: {
          totalFrames,
          frames,
          speed
        }
      })
    },

```

### Relevant log output

```shell
the last queue event receive log is
0|scheduler  | [18:35:44.641] INFO (create-queue): job: 230919-P6z:transcode:0 has progress update in the transcode
0|scheduler  | [18:35:44.646] INFO (task-store): hset 230919-P6z transcode {"0":{"state":"active","progress":{"totalFrames":36029,"frames":9854,"speed":1.12},"videoFile":""},"1":{"state":"completed","progress":{"totalFrames":7338,"frames":7250,"speed":1.2},"videoFile":"tmp/230919-P6z/transcode/1.mp4"}}

but the last worker log is
2|transcoder  | [18:39:21.874] DEBUG (childProcessUtil): ffmpeg stderr: frame=35811 fps= 98 q=31.0 size=  195584kB time=00:09:57.87 bitrate=2679.9kbits/s speed=1.64x

you can see the timestamp's gap between two log has 4 minutes
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
The code is not sufficient for reproducing the issue on our side. I wonder, can you reproduce the issue without ffmpeg? it could be related to using ffmpeg if it is consuming the CPU and not letting Node's event loop to iterate.

**Comment by zshnb** [comment]
i don't think it's releted to ffmpeg, because at the beginning all looks fine, `progress` event is triggered normally, after serveral seconds, `progress` event can't be triggered, and ffmpeg process is running normally, ffmpeg doesn't make the nodejs event loop starved

**Comment by zshnb** [comment]
@manast Hi i just find this root cause is some bugs in my code that doesn't trigger job.updateProgress, it's not bullMQ issue. Appreciate for your answer
