### ISSUE TITLE
[Bug]: Running BullMQ in a docker container with bun fails with code 9 (SIGKILL)

### ISSUE THREAD

**Issue by vicpara** [taskforcesh/bullmq#2207]
### Version

^4.12.0

### Platform

NodeJS

### What happened?

I can run the code successfully on my local device. When I run it inside a docker container the app fails to start with a cryptic:
`error: script "start" exited with code 9 (SIGKILL)` 

No additional logs or errors are provided. Through elimination i managed to trace it to the BullMQ workers and queues attempting to connect to redis. The redis instance is available as I could connenct to it via redis-cli.

I know 'bun' is not supported yet the code runs well on my local machine. I was wondering why it crashes in docker without at least logging more useful info. Is it a package dependency that's missing?

### How to reproduce.

Run `docker-compose up`  in this repo: https://github.com/vicpara/reproducebmq

Then run the code locally outside the docker environment.

### Relevant log output

```shell
bmqtest-redis-service-1  | 1:C 03 Oct 2023 09:48:28.434 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
bmqtest-redis-service-1  | 1:C 03 Oct 2023 09:48:28.434 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
bmqtest-redis-service-1  | 1:C 03 Oct 2023 09:48:28.434 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
bmqtest-redis-service-1  | 1:M 03 Oct 2023 09:48:28.434 * monotonic clock: POSIX clock_gettime
bmqtest-redis-service-1  | 1:M 03 Oct 2023 09:48:28.435 * Running mode=standalone, port=6379.
bmqtest-redis-service-1  | 1:M 03 Oct 2023 09:48:28.435 * Server initialized
bmqtest-redis-service-1  | 1:M 03 Oct 2023 09:48:28.435 * Ready to accept connections tcp
bmqtest-bmq-1            | $ bun run ./src/app.ts
bmqtest-bmq-1            | error: script "start" exited with code 9 (SIGKILL)
bmqtest-bmq-1 exited with code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I think it would be worth testing with Node to rule out it is not an issue with bun, which I think has quite a lot of odds to be the case.

**Comment by shariqh** [comment]
I'm having the same issue. I can run the code the just fine with NPM and the `node:lts-alpine` image from docker. When trying the same with Bun, I have the exact same error when trying to instantiate a new queue.

```
const redisOptions = { host: "redis", port: 6379 }

const myQueue = new Queue('foo', {
    connection: redisOptions
});
```
 
my logs print:

```
bullmq_bull-board_redis_docker_starter-server-1  | $ bun server.ts
bullmq_bull-board_redis_docker_starter-server-1  | error: script "start" exited with code 9 (SIGKILL)
bullmq_bull-board_redis_docker_starter-server-1 exited with code 1
```

**Comment by manast** [comment]
Last time I checked there were over 1800 open issues in Bun repo. I am very excited about this new runtime, but we need to keep our expectations realistically. So let's close this issue and re-open if it can be reproduced with Node.
