### ISSUE TITLE
[Bug]: updateProgress in Sandboxed processors not update job.progress proprialy

### ISSUE THREAD

**Issue by stefanozaccaria-centropaghe** [taskforcesh/bullmq#2213]
### Version

v4.12.0

### Platform

NodeJS

### What happened?

Hi buddies, thanks in advance

When I update job progress in a Sandboxed processors 

```
export default async function (job: Job) {
  await job.updateProgress(42);
 // here job.progress != 42, it remains 0
}
```
the 'progress' property of job instance not update

while if I do the same things in normal worker, the 'progress' property is updated as expected

```
const worker = new Worker(queueName, async (job: Job) => {
  await job.updateProgress(42);
// here job.progress == 42, it change as expected
});
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Thanks for the report. I guess we overlooked updating the progress property for the sandbox case.
