### ISSUE TITLE
How to connect to a Redis cluster and actually run some tasks on it.

### ISSUE THREAD

**Issue by vicpara** [taskforcesh/bullmq#2217]
**Is your feature request related to a problem? Please describe.**
How to correctly run BullMQ on a Redis cluster. Just explain what we have to do. So many tricks are buried in the documentation . Can we have a proper page with examples?
* Redis cluster config requirements
* TLS
* Configure connections / nodes
* FlowProducer? Worker? Queue ? Prefixes?
* How do we test locally?

**Describe the solution you'd like**
Improve the documentation with a full blown example how to connect to a Redis Cluster a Queue, Worker and FlowProducer.

**Describe alternatives you've considered**
Trotting up and down the BullMQ, RedisIO and AWS MemoryDB and Elasticache.

**Additional context**
It's just stupid and inefficient to spend days trying to figure out the best possible combination mix of properties to just be on your way and write the code that matters.

Just provide examples and go through all the caveats. It's super simple. The code is already written.

**Comment by manast** [comment]
There are tons of documentation and examples. Here you have a complete one for example including a repo for you to use as a starting point: https://blog.taskforce.sh/implementing-a-webhook-system-with-bullmq/
If you are completely new to Redis, then that may be a hurdle, but with patience and perseverance you will be able to get everything working.

**Comment by manast** [comment]
This may be even easier to start with actually: https://blog.taskforce.sh/implementing-mail-microservice-with-bullmq/

**Comment by vicpara** [comment]
Thanks for the articles. I think I'm past that point. 

I got my code working locally with one single redis server. It's so beautiful I don't want to switch from BullMQ.

Now I'm trying to deploy it to the cloud and use a managed Redis in AWS, something like Redis MemoryDB. It comes in a cluster configuration. I'm using for start a cluster with one single node. 
The trouble I'm facing is setting up the Queues, Workers and FlowProducers to use the cluster connection and replicate the local results. That pesky 'ioredis' cluster connection...

I can't seem to get it right. I can even get Lua to crash but not to work. Please point me in the right direction.

So far I have a code similar to the excerpts below :

```typescript
CONFIG.db.redis.connectionOpts =       connectionOpts: [{
        host: 'localhost',
        port: 7000,
      },{
        host: 'localhost',
        port: 7001,
      },{
        host: 'localhost',
        port: 7002,
      }]

export function createRedisConn() {
  if (CONFIG.db.redis.clusterMode) {

    return new Redis.Cluster([...CONFIG.db.redis.connectionOpts], {
      enableAutoPipelining: true,
      lazyConnect: false,
      slotsRefreshInterval: 60000,
      slotsRefreshTimeout: 10000,
      enableReadyCheck: true,
      dnsLookup: (address, callback) => callback(null, address),
      redisOptions: {
        tls: {
          checkServerIdentity: (/*host, cert*/) => {
            console.log('Checking ServerIdentity/tls')
            return undefined
          },
        },
        enableAutoPipelining: true,
        commandTimeout: 10000,
        connectTimeout: 10000,
        lazyConnect: false,
        enableReadyCheck: true,
        noDelay: true,
        keepAlive: 1000,
      },
    })
  }

  console.log('Creating Redis - Single Node ')
  return new Redis(CONFIG.db.redis.connectionOpts[0])
}


const primaryQ =   new Queue('primary', {
    prefix: '{primary}',
    connection: createRedisConn(),
  })

const primaryWorker = new Worker('primary', (j:Job)=>{}, {
  concurrency: 1,
  prefix: `{primary}`,
  connection: createRedisConn(),
})

const flowProducer = new FlowProducer({ prefix: '${flowProducer}', connection: createRedisConn() })

```


I've been jiggling with the config for 2 days now and cannot get it right. I get either of the following:
1. No errors at all, but the workers cannot connect to the queue and the queues cannot publish tasks. Somehow they silently don't work. TLS?
2. I managed to connect via redis-cli to the cluster and cand see with some config the queues can publish a few events but then they go silent. Workers cannot consume.
3. Worker.on('error' / 'failed' gets triggered with an empty/null error.
4. Crashes : 


---


 WORKER ERROR {"lastNodeError":{}} ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/app/code/node_modules/ioredis/built/cluster/index.js:308:31)
    at /app/code/node_modules/ioredis/built/cluster/index.js:325:21
    at Timeout.<anonymous> (/app/code/node_modules/ioredis/built/cluster/index.js:662:24)
    at Timeout.run (/app/code/node_modules/ioredis/built/utils/index.js:117:22)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  lastNodeError: Error: timeout
      at timeout (/app/code/node_modules/ioredis/built/utils/index.js:120:38)
      at EventEmitter.getInfoFromNode (/app/code/node_modules/ioredis/built/cluster/index.js:659:67)
      at tryNode (/app/code/node_modules/ioredis/built/cluster/index.js:314:19)
      at EventEmitter.refreshSlotsCache (/app/code/node_modules/ioredis/built/cluster/index.js:333:9)
      at /app/code/node_modules/ioredis/built/cluster/index.js:167:22
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


----


ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/app/code/node_modules/ioredis/built/cluster/index.js:308:31)
    at /app/code/node_modules/ioredis/built/cluster/index.js:325:21
    at Timeout.<anonymous> (/app/code/node_modules/ioredis/built/cluster/index.js:662:24)
    at Timeout.run (/app/code/node_modules/ioredis/built/utils/index.js:117:22)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  lastNodeError: Error: timeout
      at timeout (/app/code/node_modules/ioredis/built/utils/index.js:120:38)
      at EventEmitter.getInfoFromNode (/app/code/node_modules/ioredis/built/cluster/index.js:659:67)
      at tryNode (/app/code/node_modules/ioredis/built/cluster/index.js:314:19)
      at EventEmitter.refreshSlotsCache (/app/code/node_modules/ioredis/built/cluster/index.js:333:9)
      at /app/code/node_modules/ioredis/built/cluster/index.js:167:22
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}

----

{"command":{"name":"eval","args":["--[[\n Move stalled jobs to wait.\n Input:\n KEYS[1] 'stalled' (SET)\n KEYS[2] 'wait', (LIST)\n KEYS[3] 'active', (LIST)\n KEYS[4] 'failed', (ZSET)\n KEYS[5] 'stalled-check', (KEY)\n KEYS[6] 'meta', (KEY)\n KEYS[7] 'paused', (LIST)\n KEYS[8] 'event stream' (STREAM)\n ARGV[1] Max stalled job count\n ARGV[2] queue.toKey('')\n ARGV[3] timestamp\n ARGV[4] max check time\n Events:\n 'stalled' with stalled job id.\n]] -- Includes\n--[[\n Move stalled jobs to wait.\n Input:\n stalledKey 'stalled' (SET)\n waitKey 'wait', (LIST)\n activeKey 'active', (LIST)\n failedKey 'failed', (ZSET)\n stalledCheckKey 'stalled-check', (KEY)\n metaKey 'meta', (KEY)\n pausedKey 'paused', (LIST)\n eventStreamKey 'event stream' (STREAM)\n maxStalledJobCount Max stalled job count\n queueKeyPrefix queue.toKey('')\n timestamp timestamp\n maxCheckTime max check time\n Events:\n 'stalled' with stalled job id.\n]]\nlocal rcall = redis.call\n-- Includes\n--[[\n Function to loop in batches.\n Just a bit of warning, some commands as ZREM\n could receive a maximum of 7000 parameters per call.\n]]\nlocal function batches(n, batchSize)\n local i = 0\n return function()\n local from = i * batchSize + 1\n i = i + 1\n if (from <= n) then\n local to = math.min(from + batchSize - 1, n)\n return from, to\n end\n end\nend\n--[[\n Function to check for the meta.paused key to decide if we are paused or not\n (since an empty list and !EXISTS are not really the same).\n]]\nlocal function getTargetQueueList(queueMetaKey, waitKey, pausedKey)\n if rcall("HEXISTS", queueMetaKey, "paused") ~= 1 then\n return waitKey, false\n else\n return pausedKey, true\n end\nend\n--[[\n Function to remove job.\n]]\n-- Includes\n--[[\n Check if this job has a parent. If so we will just remove it from\n the parent child list, but if it is the last child we should move the parent to "wait/paused"\n which requires code from "moveToFinished"\n]]\n--[[\n Functions to destructure job key.\n Just a bit of warning, these functions may be a bit slow and affect performance significantly.\n]]\nlocal getJobIdFromKey = function (jobKey)\n return string.match(jobKey, ".:(.)")\nend\nlocal getJobKeyPrefix = function (jobKey, jobId)\n return string.sub(jobKey, 0, #jobKey - #jobId)\nend\nlocal function moveParentToWait(parentPrefix, parentId, emitEvent)\n local parentTarget = getTargetQueueList(parentPrefix .. "meta", parentPrefix .. "wait", parentPrefix .. "paused")\n rcall("RPUSH", parentTarget, parentId)\n if emitEvent then\n local parentEventStream = parentPrefix .. "events"\n rcall("XADD", parentEventStream, "", "event", "waiting", "jobId", parentId, "prev", "waiting-children")\n end\nend\nlocal function removeParentDependencyKey(jobKey, hard, parentKey, baseKey)\n if parentKey then\n local parentDependenciesKey = parentKey .. ":dependencies"\n local result = rcall("SREM", parentDependenciesKey, jobKey)\n if result > 0 then\n local pendingDependencies = rcall("SCARD", parentDependenciesKey)\n if pendingDependencies == 0 then\n local parentId = getJobIdFromKey(parentKey)\n local parentPrefix = getJobKeyPrefix(parentKey, parentId)\n local numRemovedElements = rcall("ZREM", parentPrefix .. "waiting-children", parentId)\n if numRemovedElements == 1 then\n if hard then\n if parentPrefix == baseKey then\n removeParentDependencyKey(parentKey, hard, nil, baseKey)\n rcall("DEL", parentKey, parentKey .. ':logs',\n parentKey .. ':dependencies', parentKey .. ':processed')\n else\n moveParentToWait(parentPrefix, parentId)\n end\n else\n moveParentToWait(parentPrefix, parentId, true)\n end\n end\n end\n end\n else\n local missedParentKey = rcall("HGET", jobKey, "parentKey")\n if( (type(missedParentKey) == "string") and missedParentKey = "" and (rcall("EXISTS", missedParentKey) == 1)) then\n local parentDependenciesKey = missedParentKey .. ":dependencies"\n local result = rcall("SREM", parentDependenciesKey, jobKey)\n if result > 0 then\n local pendingDependencies = rcall("SCARD", parentDependenciesKey)\n if pendingDependencies == 0 then\n local parentId = getJobIdFromKey(missedParentKey)\n local parentPrefix = getJobKeyPrefix(missedParentKey, parentId)\n local numRemovedElements = rcall("ZREM", parentPrefix .. "waiting-children", parentId)\n if numRemovedElements == 1 then\n if hard then\n if parentPrefix == baseKey then\n removeParentDependencyKey(missedParentKey, hard, nil, baseKey)\n rcall("DEL", missedParentKey, missedParentKey .. ':logs',\n missedParentKey .. ':dependencies', missedParentKey .. ':processed')\n else\n moveParentToWait(parentPrefix, parentId)\n end\n else\n moveParentToWait(parentPrefix, parentId, true)\n end\n end\n end\n end\n end\n end\nend\nlocal function removeJob(jobId, hard, baseKey)\n local jobKey = baseKey .. jobId\n removeParentDependencyKey(jobKey, hard, nil, baseKey)\n rcall("DEL", jobKey, jobKey .. ':logs',\n jobKey .. ':dependencies', jobKey .. ':processed')\nend\n--[[\n Functions to remove jobs by max age.\n]]\n-- Includes\nlocal function removeJobsByMaxAge(timestamp, maxAge, targetSet, prefix)\n local start = timestamp - maxAge * 1000\n local jobIds = rcall("ZREVRANGEBYSCORE", targetSet, start, "-inf")\n for i, jobId in ipairs(jobIds) do\n removeJob(jobId, false, prefix)\n end\n rcall("ZREMRANGEBYSCORE", targetSet, "-inf", start)\nend\n--[[\n Functions to remove jobs by max count.\n]]\n-- Includes\nlocal function removeJobsByMaxCount(maxCount, targetSet, prefix)\n local start = maxCount\n local jobIds = rcall("ZREVRANGE", targetSet, start, -1)\n for i, jobId in ipairs(jobIds) do\n removeJob(jobId, false, prefix)\n end\n rcall("ZREMRANGEBYRANK", targetSet, 0, -(maxCount + 1))\nend\n--[[\n Function to trim events, default 10000.\n]]\nlocal function trimEvents(metaKey, eventStreamKey)\n local maxEvents = rcall("HGET", metaKey, "opts.maxLenEvents")\n if maxEvents = false then\n rcall("XTRIM", eventStreamKey, "MAXLEN", "", maxEvents)\n else\n rcall("XTRIM", eventStreamKey, "MAXLEN", "", 10000)\n end\nend\n-- Check if we need to check for stalled jobs now.\nlocal function checkStalledJobs(stalledKey, waitKey, activeKey, failedKey,\n stalledCheckKey, metaKey, pausedKey,\n eventStreamKey, maxStalledJobCount,\n queueKeyPrefix, timestamp, maxCheckTime)\n if rcall("EXISTS", stalledCheckKey) == 1 then return {{}, {}} end\n rcall("SET", stalledCheckKey, timestamp, "PX", maxCheckTime)\n -- Trim events before emiting them to avoid trimming events emitted in this script\n trimEvents(metaKey, eventStreamKey)\n -- Move all stalled jobs to wait\n local stalling = rcall('SMEMBERS', stalledKey)\n local stalled = {}\n local failed = {}\n if (#stalling > 0) then\n rcall('DEL', stalledKey)\n local MAX_STALLED_JOB_COUNT = tonumber(maxStalledJobCount)\n -- Remove from active list\n for i, jobId in ipairs(stalling) do\n if string.sub(jobId, 1, 2) == "0:" then\n -- If the jobId is a delay marker ID we just remove it.\n rcall("LREM", activeKey, 1, jobId)\n else\n local jobKey = queueKeyPrefix .. jobId\n -- Check that the lock is also missing, then we can handle this job as really stalled.\n if (rcall("EXISTS", jobKey .. ":lock") == 0) then\n -- Remove from the active queue.\n local removed = rcall("LREM", activeKey, 1, jobId)\n if (removed > 0) then\n -- If this job has been stalled too many times, such as if it crashes the worker, then fail it.\n local stalledCount =\n rcall("HINCRBY", jobKey, "stalledCounter", 1)\n if (stalledCount > MAX_STALLED_JOB_COUNT) then\n local rawOpts = rcall("HGET", jobKey, "opts")\n local opts = cjson.decode(rawOpts)\n local removeOnFailType = type(opts["removeOnFail"])\n rcall("ZADD", failedKey, timestamp, jobId)\n local failedReason =\n "job stalled more than allowable limit"\n rcall("HMSET", jobKey, "failedReason", failedReason,\n "finishedOn", timestamp)\n rcall("XADD", eventStreamKey, "", "event",\n "failed", "jobId", jobId, 'prev', 'active',\n 'failedReason', failedReason)\n if removeOnFailType == "number" then\n removeJobsByMaxCount(opts["removeOnFail"],\n failedKey, queueKeyPrefix)\n elseif removeOnFailType == "boolean" then\n if opts["removeOnFail"] then\n removeJob(jobId, false, queueKeyPrefix)\n rcall("ZREM", failedKey, jobId)\n end\n elseif removeOnFailType ~= "nil" then\n local maxAge = opts["removeOnFail"]["age"]\n local maxCount = opts["removeOnFail"]["count"]\n if maxAge ~= nil then\n removeJobsByMaxAge(timestamp, maxAge,\n failedKey, queueKeyPrefix)\n end\n if maxCount ~= nil and maxCount > 0 then\n removeJobsByMaxCount(maxCount, failedKey,\n queueKeyPrefix)\n end\n end\n table.insert(failed, jobId)\n else\n local target =\n getTargetQueueList(metaKey, waitKey, pausedKey)\n -- Move the job back to the wait queue, to immediately be picked up by a waiting worker.\n rcall("RPUSH", target, jobId)\n rcall("XADD", eventStreamKey, "", "event",\n "waiting", "jobId", jobId, 'prev', 'active')\n -- Emit the stalled event\n rcall("XADD", eventStreamKey, "", "event",\n "stalled", "jobId", jobId)\n table.insert(stalled, jobId)\n end\n end\n end\n end\n end\n end\n -- Mark potentially stalled jobs\n local active = rcall('LRANGE', activeKey, 0, -1)\n if (#active > 0) then\n for from, to in batches(#active, 7000) do\n rcall('SADD', stalledKey, unpack(active, from, to))\n end\n end\n return {failed, stalled}\nend\nreturn checkStalledJobs(KEYS[1], KEYS[2], KEYS[3], KEYS[4], KEYS[5], KEYS[6],\n KEYS[7], KEYS[8], ARGV[1], ARGV[2], ARGV[3], ARGV[4])\n","8","bull:primary:stalled","bull:primary:wait","bull:primary:active","bull:primary:failed","bull:primary:stalled-check","bull:primary:meta","bull:primary:paused","bull:primary:events","1","bull:primary:","1696509656121","30000"]}}

**Comment by manast** [comment]
It seems like the issue comes from IORedis. For some reason, it is not properly configured to work with MemoryDB. I have tested it before and I know it works, but another alternative that works pretty well is elasticache. You do not need cluster mode, the best is to have 1 single instance and 1 replica for high availability. The only downside with that setup is that you will not have backups, you have to rely on that 1 replica if the main instance fails, but in the unlikely event both the main and the replica fail you will lose all the data stored in Redis. Otherwise, you can also use Redis.com instances, they work pretty well and are easier to configure. Cluster once again is seldom needed. Btw, you do not need to change the prefix in BullMQ, it is enough if the names of the queues are wrapped in curly braces, so for your example above it will be 
```ts
const primaryQ =   new Queue('{primary}', {
    connection: createRedisConn(),
})
```

**Comment by manast** [comment]
ah, one more thing, if you use flows, then you will need to use the prefix approach, as otherwise the queues used in the flows will end in different slots and it will not work, but this is only an issue in Redis cluster mode.

**Comment by vicpara** [comment]
Thanks for the advice regarding clusters. Would you be able to share the connection settings of the `ioredis` object if you have it at hand?

I'm heavily relying on Flows. They are fantastic. Once I have a tree/ DAG of tasks it just executes like magic.

So if I have two Queues i can use the name wrapped in curly brackets but the flow needs to use the prefix? What confuses me is what prefix to use for the Flow. The documentation says : '* Prefix for all queue keys.'

```
const primaryQ =  new Queue('{primary}', {
    connection: createRedisConn(),
})
const secondaryQ =  new Queue('{secondary}', {
    connection: createRedisConn(),
})

const flowProducer = new FlowProducer({ prefix: '${flowProducer}', connection: createRedisConn() })
```

or you're suggesting to use the prefix property for all objects Workers, Queues and FlowProduces.

Do I need to include the prefix for Workers too ?

**Comment by vicpara** [comment]
Sorry, closed the issue by mistake. 

For a 'flowProducer' how do i chose the prefix? Is it the prefix that matches the queue's prefix for the last job (the parent that aggregates the last child?)

```
Tn(Q2) : Task n that runs on Queue2


T1(Q2) <-- T2(Q1) <-- T3(Q2) <-- T4(Q1)
              ^-----  T5(Q2)
```

* Do worker's prefix matters? Does each woker's prefix need to match the queue it processeS?

**Comment by manast** [comment]
Ok, you only need to use the curly-based names or prefixes when using Redis cluster mode.
All the keys that are used by BullMQ have this pattern: ```prefix:queuename:*```. The curly braces are used by Redis cluster to calculate a hash, and that hash is used to determine on which node of the cluster a given key is going to be stored. As all the keys belonging to one queue must be on the same node (as BullMQ needs to read and write to the queue keys atomically), using curly braces to wrap the name of the queue or the prefix do the trick. However, if you wrap the prefix and use the same prefix for all the queues, then all the queues will end in the same cluster node. If you want to spread the load to different nodes you can choose to wrap the queue name instead of the prefix. When using flows however, since a flow can use several queues, you must wrap the prefix and not the queue names, so that all the queues belonging to one flow ends in the same node. If you have several independent flows you can use different prefixes so that the flows are distributed among the nodes evenly...
I hope this explanation makes it clear. 

Regarding MemoryDB, unfortunately, I removed the connection some months ago after verifying it worked, but this is IORedis stuff, if the connection works for IORedis it will work for BullMQ. One thing for sure, it was quite straightforward, I did not use as many settings as you have and it worked without issues.

**Comment by vicpara** [comment]
Thank you so much. This explanation is makes it clearer on how to use the prefixes. For sure it won't hurt going to the documentation :)
It also starts to provide clues for me regarding the lua crashes for key hashes computation. I'll give it a go.

**Comment by vicpara** [comment]
Ok. I got it working. For the others struggling with it I'm adding below my settings for workers, queues, flow and connections. Perhaps the connection can be simplified and set up with less options. Here's what works for me.

In my case the FlowProduce creates tasks with dependent tasks on queue1 and queue2 therefore they all need to be in the same shard.

```typescript

const connectionOpts = [{
        host: 'localhost',
        port: 7000,
      },{
        host: 'localhost',
        port: 7001,
      },{
        host: 'localhost',
        port: 7002,
      }]

export function createRedisConn() {
  let redisOptions = {}
  if (CONFIG.db.redis.tlsEnabled) {
    redisOptions = {
      showFriendlyErrorStack: true,
      enableAutoPipelining: true,
      slotsRefreshTimeout: 10000,
      tls: {
        checkServerIdentity: (servername, cert) => {
          return undefined
        },
      },
    }
  }

// the hostname needs to be the AWS url for the node not the config cluster endpoint
  if (CONFIG.db.redis.clusterMode) {
    return new Redis.Cluster(connectionOpts, {
      slotsRefreshInterval: 60000,
      slotsRefreshTimeout: 10000,
      enableReadyCheck: true,
      dnsLookup: (address, callback) => callback(null, address),
      redisOptions,
    })
  }
  return new Redis(connectionOpts[0])
}

const q1 = new Queue(nameQ1, {
   prefix: '{exec}',
    connection: createRedisConn(),
  })

const q2 = new Queue(nameQ2, {
   prefix: '{exec}',
    connection: createRedisConn(),
  })

const primaryWorker = new Worker(nameQ1, Transformer.transform, {
  concurrency: 1,
   prefix: '{exec}',
  connection: createRedisConn(),
})

const secondaryWorker = new Worker(nameQ2, Transformer.transform, {
  concurrency: 1,
   prefix: '{exec}',
  connection: createRedisConn(),
})

export const flowProducer = new FlowProducer({ prefix: '{exec}', connection: createRedisConn() })

```

**Comment by manast** [comment]
Btw, concurrency 1 is quite slow, you would normally want to crank it up to 100 or something like that.
