### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Alserda** [taskforcesh/bullmq#222]
The documentation contains a lot of empty pages, or subjects that are briefly explained (like 'Retrying failing jobs'). Is there a plan as to when these pages will be filled? I'm actually very much interested in reading about the patterns so I can understand the library better. 

The library it self is pretty straight-forward, so it's not a blockage, but a lack of documentation makes me more hesitant to prefer bull over bullmq

**Comment by manast** [comment]
During summer I will finalize the documentation.
