### ISSUE TITLE
Clarify guarantees on message delivery

### ISSUE THREAD

**Issue by gl-jkeys** [taskforcesh/bullmq#2222]
**Is your feature request related to a problem? Please describe.**

I do not see any description of the guarantees about message re-delivery.

If I attach an event listener to my worker, and the worker node crashes in the middle of processing a message, will the message get re-delivered to another worker? Or is that message lost forever?

**Describe the solution you'd like**

Please add some documentation around message delivery guarantees. 

If messages _are_ lost forever if the worker node crashes in the middle of message processing, this should be clearly documented and there should be recommendations for how to recover from missing messages. 

Ideally, there should be an optional (if configured) synchronous `ack` method on the message, and the message should redeliver if this ack function is not called within the configured message lock period.

**Describe alternatives you've considered**

- enqueueing messages to a separate dead letter queue for re-processing if necessary
  - not a "correct" solution, because the message handler might throw between the time that the message is received and the call to enqueue to the dead letter message. This minimizes the problem but does not remove it.

**Additional context**
N/A

Edit: to clarify, when I say messages, I mean the job event messages that are emitted to the worker or QueueEvents event listeners. I'm not referring to Job redelivery, which is documented.

**Comment by gl-jkeys** [comment]
Hi, can you cite the passage that answers my questions? I don't think they are documented.

**Comment by gl-jkeys** [comment]
If you are saying that event messages -- e.g. `worker.on('failed', msg => {/*...*/})` -- shares the same semantics as `new Worker(namespace, handler, opts)`, then that's great, but it's not documented anywhere.

It's also not documented whether any re-delivered message would be re-delivered to _any_ worker, or only workers attached to the same namespace.

**Comment by manast** [comment]
Events, as any events in Node, do not provide any guarantees. The processor in the workers is what gives you the mechanism to achieve at-least-one semantics. This is documented if you really care to look into it. There are also loads of tutorials with much more information here: https://blog.taskforce.sh/
