### ISSUE TITLE
Can't clean queue

### ISSUE THREAD

**Issue by jaschaio** [taskforcesh/bullmq#223]
Not sure what I am doing wrong, it was working on `Bull:v3`.

```javascript
// Lets take as a given that I have added 800 jobs without defining a Worker before so all jobs should be "waiting"
const jobs = await queue.getJobCounts( 'waiting' );
console.log( `There are ${ jobs.waiting } jobs to clean` );
    
const wait = await queue.clean( 0, 0, 'wait' );
console.log( `cleaned ${ wait.length } wait jobs` );
```

This outputs:

```
There are 800 jobs to clean
cleaned 0 wait jobs
```

I thought that maybe the second parameter `limit` shouldn't be 0, but I tried with a high number instead and still no jobs are being removed. Using `waiting` instead of `wait` leads to the same result.

What am I doing wrong?

**Comment by jaschaio** [comment]
`queue.drain()` works as expected removing all waiting jobs. So am I supposed to use that method instead of `queue.clean( 0, 0, 'wait' )`?

**Comment by roggervalf** [comment]
hi @jaschaio, this case is a little weird since there is a test case that covers what you are mentioning https://github.com/taskforcesh/bullmq/blob/master/src/test/test_clean.ts#L97-L105

**Comment by jaschaio** [comment]
I have moved on so can't really give more input on this. Thanks anyway
