### ISSUE TITLE
connection option ignored

### ISSUE THREAD

**Issue by jaschaio** [taskforcesh/bullmq#224]
The lack of documentation is quite frustrating and improving it could probably avoid a lot of issues. Anyway, I am trying to connect to a redis instance available under the host `redis` as [told in the documentation](https://docs.bullmq.io/guide/connections).

But unfortunately I get the same error as #191 

```javascript
new Queue( 'queue', {
    connnection: {
        host: 'redis',
        port: 6379
    }
} );
```

The error I get is `Error: connect ECONNREFUSED 127.0.0.1:6379`

So it's not using the host parameter but just the default localhost.

Some context: I am running this node app in a docker container and redis is running within another docker container. I have double checked that the other container is reachable via `ping redis` and `telnet redis 6379`. This worked as well before using `bull:v3` and a simple connection string like `redis://redis:6379`. Unfortunately I can't get it to work in `bullmq`. 

```
ping redis
PING redis (10.0.4.29) 56(84) bytes of data.
64 bytes from 10.0.4.29 (10.0.4.29): icmp_seq=1 ttl=64 time=0.094 ms
64 bytes from 10.0.4.29 (10.0.4.29): icmp_seq=2 ttl=64 time=0.108 ms
```

```
telnet redis 6379
Trying 10.0.4.29...
Connected to redis.
Escape character is '^]'
```

**Comment by jaschaio** [comment]
Apparently this doesn't work any longer as in `bull:v3`, but I need to pass the connection to every class `Queue`, `Worker` and `QueueScheduler`. This could be a lot clearer in the documentation or maybe it would help tremendously if [the Migration 3.x documentation would actually say something](https://docs.bullmq.io/bull-3.x-migration/migration).

**Comment by paulisloud** [comment]
> Apparently this doesn't work any longer as in `bull:v3`, but I need to pass the connection to every class `Queue`, `Worker` and `QueueScheduler`. This could be a lot clearer in the documentation or maybe it would help tremendously if [the Migration 3.x documentation would actually say something](https://docs.bullmq.io/bull-3.x-migration/migration).

This was the end of a 4 hour search for me

**Comment by manast** [comment]
I know in many cases it is not possible but I strongly recommend you to use typescript, then you will get a compiler error if you pass the wrong arguments. I am sorry you lost time with this issue, but it is actually documented in the api reference:  https://github.com/taskforcesh/bullmq/blob/3a8873b6453405e6f8e57331f6cee30977406670/docs/gitbook/api/bullmq.queuebaseoptions.md

**Comment by manast** [comment]
@giovanni-bertoncelli https://api.docs.bullmq.io/interfaces/v5.QueueOptions.html

**Comment by giovanni-bertoncelli** [comment]
Thank you, @manast. I was also wondering: this page https://docs.bullmq.io/bull/patterns/reusing-redis-connections is still valid? Since I can't see the `createClient` option documented anywhere inside the full API documentation... Is it a option viable only for the `Queue` constructor or also for other components?

**Comment by manast** [comment]
@giovanni-bertoncelli that pages refers to Bull, not BullMQ, the legacy version of the library.

**Comment by giovanni-bertoncelli** [comment]
oh shut, thanks!
