### ISSUE TITLE
How can this be done with BullMQ?

### ISSUE THREAD

**Issue by vicpara** [taskforcesh/bullmq#2244]
# Firstly, this is such an awesome library. Fantastic work! Well done and thank you!

**This is not a bug, just checking if an execution model is possible.**

### The Question
I have a flow that runs on three different queues. At some point during a child task execution, the worker has access to the information that the work required to do for that one job it has "in hand" is tremendously big.  It has the knowledge how to break it into smaller jibs and execute it, just like in the example provided at: https://blog.taskforce.sh/splitting-heavy-jobs-using-bullmq-flows/  .
However this child job is part of a Flow and it must return the result within the Flow.

Are there any mechanisms where this child job, once it detects it's a big job, can create children task of his own? Ideally ibce execute these children execute, their aggregated result is return back to the flow as if the overarching flow executed normally?

Can flows be changed dynamically?

In our case, the information on the child task size is not available at the time when the Flow is scheduled.

**Comment by roggervalf** [comment]
Hi @vicpara, probably you need to review https://docs.bullmq.io/patterns/process-step-jobs#waiting-children this pattern to create children jobs dynamically

**Comment by vicpara** [comment]
Indeed, this is the use case I was looking for. Thank you.
