### ISSUE TITLE
Jobs keys never expire.

### ISSUE THREAD

**Issue by immortalx** [taskforcesh/bullmq#225]
Hi,
I noticed that the job keys hashes on redis doesn't have a ttl.
Is this by design to have redis handling the removal of old keys? Any way to change it so the key is removed when the job is completed?

Thank you

**Comment by manast** [comment]
It is by design, but there is a feature request for ephemeral queues that would do what you ask.

**Comment by immortalx** [comment]
Oh thanks for clarifying, in my case i will need to run a dedicated redis server because of this.

Other than that it's running really well, thanks for the amazing work.

**Comment by acro5piano** [comment]
@immortalx 

Hi, thank you for your amazing work.

I also need this feature. Do you know what is the current status of the feature? Thanks

**Comment by acro5piano** [comment]
I've ended up to add `removeOnComplete` to remove completed job's hashes.

```ts
  const queue = new Queue(queueName, {
    connection,
    defaultJobOptions: {
      removeOnComplete: 10,
    },
  })
```

**Comment by spearmootz** [comment]
If a number is passed what is the behavior? Does the job get removed only after completed or failed?

And what does the number represent? Seconds? I tried to look for documentation but i didn't find anything and I looked at code to see that if it's a number a 1 gets added to the number as a string and sent to a client that I couldn't find the code for (i was looking in my phone).

Thanks for this btw! I'm really excited about bullmq

**Comment by acro5piano** [comment]
@spearmootz 
Do you mean what `removeOnComplete` represents? If so, the number is meaning "how many keys saved to Redis per a queue after a queue completed"
So, if set to `100`, the completed job keys will be stored at most 100, and the older keys will be deleted.

Also note you need to run `QueueScheduler` with the option.

**Comment by spearmootz** [comment]
That is exactly what I meant! Thank you!

**Comment by acro5piano** [comment]
I've found `removeOnComplete` also accepts `boolean`, which enables you to delete completed / failed job key immediately.

![image](https://user-images.githubusercontent.com/10719495/113802334-0f008b00-974a-11eb-8d6d-74e4b901e234.png)

However, setting `number` is more practical way because we want to check what was going on the failed job.
