### ISSUE TITLE
[Bug]: Job <xxx> could not be removed because it is locked by another worker

### ISSUE THREAD

**Issue by matpen** [taskforcesh/bullmq#2256]
### Version

v4,12,3

### Platform

NodeJS

### What happened?

We are experiencing this unhandled rejection in our current code
`Job <xxx> could not be removed because it is locked by another worker`

Having examined the code multiple times, I am unsure where it originates because
* there is only one worker in our environment
* we are not sharing the connection to Redis with any other system (not even replicas of the same process)

So I am hoping for a hint on how to debug this, because the search online also turned out unfruitful.

### How to reproduce.

Unsure on how to reproduce. The problem appears randomly, and seems not connected with any special events. Only hypothesis so far is that it is somehow related to https://github.com/taskforcesh/bullmq/issues/2229

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Most likely you are trying to remove an active job. As long as a job is active and locked by a worker it cannot be manually removed.

**Comment by matpen** [comment]
Thank you for the quick reply, @manast. However, I do not see how this could happen in our very simple environment: there is only one worker, only one process, and only one queue. There is also no custom code that removes jobs, apart from the `removeOnFail` / `removeOnSuccess` settings.

My understanding is that, under these conditions, the jobs are run one-by-one, and removed only when they complete. They cannot be locked by something else.

For now, I am investigating interaction with https://github.com/taskforcesh/bullmq/issues/2229, but I appreciate any suggestion that might come to the readers' mind.

**Comment by manast** [comment]
This error can only occur when you manually remove a job with remove. So somewhere in your codebase you are removing jobs manually.
