### ISSUE TITLE
[Bug]: Lock mismatch and Missing lock for job with graceful worker shutdown in Kubernetes environment

### ISSUE THREAD

**Issue by godinja** [taskforcesh/bullmq#2258]
### Version

v4.12.4

### Platform

NodeJS

### What happened?

We are seeing some strange behavior with job locks and double job processing in our Kubernetes environments. We have some jobs, all of which are Sandboxed, that take upwards of 1 hour to complete. We have setup our workers to "gracefully shutdown" by calling `worker.close()`. We can observe that the worker continues to process the job after `worker.close()` has been called, but when it completes it will throw either a `Error: Missing lock for job <jobID>. failed` error or `Error: Lock mismatch for job <jobID>. Cmd failed from active` error.

The pod terminates and the new pod starts processing the job that was just processed.

My understanding is that since we are using Sandboxed jobs, the main event loop is not blocked, therefore updating job locks should not be an issue here.

### How to reproduce.

[Here](https://github.com/godinja/bullmq-graceful-shutdown) is a repository outlining how to reproduce.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
I wonder, is it possible that the Redis instance is closed before the worker actually completed the job?

**Comment by manast** [comment]
Also, here (https://github.com/godinja/bullmq-graceful-shutdown/blob/main/server.ts) I would attach an "error" handler too:
```ts
worker.on("error", (err) => { console.error(err) })
```

**Comment by godinja** [comment]
> I wonder, is it possible that the Redis instance is closed before the worker actually completed the job?

Do you mean the underlying Redis connection that the Worker establishes? From what I can see the Redis pods remain up and running.

> Also, here (https://github.com/godinja/bullmq-graceful-shutdown/blob/main/server.ts) I would attach an "error" handler too:

Adding this handles the error but does not prevent it from happening.

**Comment by manast** [comment]
Yes, I want to see if there is an error that leads to the issue.

**Comment by manast** [comment]
Does it only happen on kubernetes? That would make me suspect that the issue could be that even though the worker is being closed gracefully, the connection to Redis may not be working correctly at the time the worker is closing. I would rather see a test where Kubernetes is not present.

**Comment by godinja** [comment]
> Does it only happen on kubernetes? 

I've just pushed some changes to the [example repo](https://github.com/godinja/bullmq-graceful-shutdown/tree/main) that takes Kubernetes out of the equation, and the error still happens.

I'm running Redis locally in a Docker container, specifically the `bitnami/redis:7.0.10` image.

**Comment by godinja** [comment]
I've noticed that if the job takes under 30 seconds (the `lockDuration` defaults to 30 seconds) this error doesn't happen. This leads me to believe that the worker does not continuously renew the job lock after it has been closed.

**Comment by manast** [comment]
@godinja thanks for the update. Yes, I can see in the code that indeed the lock extender function will stop when closing the worker, so that would be the issue. I will make a fix asap.

**Comment by manast** [comment]
@godinja please let me know if the fix solves your issue.

**Comment by godinja** [comment]
@manast the fix seems to have fixed the issue. Thanks for getting around to this so quickly!
