### ISSUE TITLE
[Other]: Memory(RAM) growing over the period of time with Node + BullMQ

### ISSUE THREAD

**Issue by jimit-raval-sf** [taskforcesh/bullmq#2267]
Hi,

**Observing memory growing issue:**

I'm mentioning all the possible details below to understand the issue:

> **Tech stack :**

```
NodeJS ( 16.18.1 )
BullMQ ( 4.12.7 )
Redis ( 6.2.14 )
```

>**Use-case :**

- We have two processors A & B ( separate projects running with a supervisor ) built with node + typescript.

- We are using Redis with docker.

- Both processors A & B are connected with the same Redis.

> **Working Flow :**

- Processor A will receive the data from the device and push it to the queue as a job.
- Worker will assigned per queue to start processing the job.

- Once the processing is completed, Processor A will send data to Processor B over an API call.
- Processor B will receive the data and push it to the queue as a job.
- Worker will assigned per queue to start processing the job.

> **Notes :**

- We have a unique name for every queue so it won't conflict.
- We are receiving data traffic is around 50 payloads / second.
- While pushing the job we are applying `removeOnComplete: true`
- We have a cron job for 1 minute which will execute the `queue.clean(0, 0,'completed')`

> **Issue :**
- Free memory keeps decreasing
- Buff/cache memory is keep increasing
- After running it constantly for a few days we are seeing that used memory keeps growing.
- At one point our processor was not able to communicate with Redis.
- If I restart the Redis docker container then it starts working again.

Let me know if anything more I can provide.

Thank you for looking into this issue.

**Comment by manast** [comment]
Which memory is increasing? If it is Redis then it is normal, you will need to configure removeOnComplete/Failed settings in your workers to keep memory under some limits.

**Comment by jimit-raval-sf** [comment]
Hi @manast,

system RAM is increasing.

I've added `removeOnComplete: true` and doing `queue.clean(0, 0,'completed')` in 1 min cron.

If you see the memory log, buff/cache is increasing so is it fine or it is problematic?

Start Time 2023-11-06 14:47:01
              total        used        free      shared   buff/cache   available
Mem:      31G        5.0G        15G        89M         10G           25G
Swap:      0B          0B           0B

Current Time 2023-11-07 09:23:01
              total        used        free      shared   buff/cache   available
Mem:     31G        4.9G        9.4G       250M       16G           25G
Swap:     0B          0B           0B

**Comment by jimit-raval-sf** [comment]
Hi @manast ,

System RAM running the Redis and we are using bullMQ workers.

We are not creating any system-level or nodeJS worker.

**Comment by manast** [comment]
If you are running both Redis and NodeJS, the first thing to figure out is which processes are consuming the memory. As far as I know BullMQ does not leak memory.

**Comment by jimit-raval-sf** [comment]
Hi @manast ,

If I just run one processor, either A or B then Redis memory does not grow.

But If I start both the processors together then I can see Redis memory keeps growing and I can see so many jobs are as waiting and it keeps increasing.

**Comment by manast** [comment]
You mean your Redis RAM usage is increasing? So, are the jobs being processed as they should, did you check the contents of Redis to try to figure out where this usage comes from?

**Comment by jimit-raval-sf** [comment]
@manast ,

Waiting jobs are increasing that's why Redis memory is growing.

I don't why starting both processors causing this, If I run a single processor then all things are processing so fast.

I'm sending 40 data per second into the queues so 2400 data per minute.

**Comment by jimit-raval-sf** [comment]
Hi @manast ,

I've created two separate Redis containers just for sanity check and now I'm not able to see pending jobs and memory growth.

**Comment by jimit-raval-sf** [comment]
Hi @manast,

In Redis, I can see the below errors, Redis automatically cleared (flushed) all the jobs from the queues.

I can see these errors after so many jobs are in waiting states.

```
# Error condition on socket for SYNC: Connection refused
1:S 22 Nov 2023 00:45:08.913 # Module /tmp/exp.so failed to load: It does not have execute permissions.

Wrong signature trying to load DB from file
Failed trying to load the MASTER synchronization DB from disk
Reconnecting to MASTER 43.131.225.101:60120 after failure
MASTER <-> REPLICA sync started
Non blocking connect for SYNC fired the event.
Master replied to PING, replication can continue...
Partial resynchronization not possible (no cached master)
Full resync from master: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ:0
MASTER <-> REPLICA sync: receiving 21816 bytes from master to disk
MASTER <-> REPLICA sync: Flushing old data
```

**Comment by manast** [comment]
You are going to need to take this with your Redis hosting provider. Nothing we can help you regarding this issue from the BullMQ team.
