### ISSUE TITLE
[Bug]: The active job count is sometimes wrong

### ISSUE THREAD

**Issue by haqadn** [taskforcesh/bullmq#2268]
### Version

4.11.4

### Platform

NodeJS

### What happened?

The active job count is inflated.

### How to reproduce.

It's not reproducable 100% of the time.

However, it happens when there is 20+ concurrent workers consuming the queue and a prioritized job fails. The `bull:<queue-name>:active` list gets appended with a `0:0` value. The active count would include items with this value.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Actually, this is by design. For a very small amount of time it could happen that a "marker" is moved to the active set, and then quickly removed. We need this marker in order to signal workers that there are  priority jobs available. It should not be off more than 1 AFAIK.

**Comment by haqadn** [comment]
It does go beyond 1. This screenshot is from a live database.
<img width="381" alt="image" src="https://github.com/taskforcesh/bullmq/assets/3737780/3fe875e3-c393-4426-b099-1315364fed82">

It poses a problem in my use-case since we scale up and down the number of workers based on the `active+waiting+prioritized` job count.

**Comment by manast** [comment]
Yeah, we cannot use sets unfortunatelly, since the only command that blocks and moves an item from a list to another is BRPOPLPUSH. But I think it is strange that you get so many markers, that does not look right. By any chance could you create a test where this happens?

**Comment by haqadn** [comment]
Unfortunately, I don't know a sure way of reproducing it. I was trying to find a pattern of it happening but couldn't find any. But, how the queuing is handled in my case is the follows:

1. There is an HTTP server that receives requests and creates jobs.
2. The jobs are pushed to a redis cluster with 1 read/write and a few read-only replicas.
3. Some workers that can horizontally scale. We try to keep the number of workers same as `active+waiting/prioritized` so that the jobs get processed in minimum wait time.
4. If a job fails, it is retried a few times.

Just trying to give you an idea of the architecture in case you can get any clues.



Btw, where does it make sure only one marker gets inserted at a time?

**Comment by roggervalf** [comment]
hi @haqadn, that logic is [here](https://github.com/taskforcesh/bullmq/blob/master/src/commands/includes/addPriorityMarkerIfNeeded.lua#L9-L11) from https://github.com/taskforcesh/bullmq/blob/master/src/commands/includes/addJobWithPriority.lua

**Comment by manast** [comment]
@haqadn I have identified an scenario where this happens. I have a possible solution for this, but it requires some architectural changes, they are not big and they will actually improve the performance overall, but it will take some time to put in place. Maybe by the end of the next week we will have something. A possible workaround if you do not check the count too often is to get all the items in the active list and then count all that are different from 0:0. The key holding the active list is in ```bull:myqueuename:active```.

**Comment by haqadn** [comment]
Thanks @manast for looking into it. I am actually already using this workaround. We do need to check the counts and do it 20-30 times a minute for a few queues. However, this is holding up well so far.

Looking forward to seeing the actual fix implemented!

**Comment by manast** [comment]
This should be resolved now in v5.
