### ISSUE TITLE
docs: add minimum Redis version

### ISSUE THREAD

**Issue by joebowbeer** [taskforcesh/bullmq#227]
Please indicate minimum Redis version in README or the official doc.

Bull v3 clearly states:

> Requirements: Bull requires a Redis version greater than or equal to 2.8.18.

**Comment by manast** [comment]
Should be added a section here: https://docs.bullmq.io/guide/redis-tm-compatibility
And the minimum and recommended Redis versions are currently: https://github.com/taskforcesh/bullmq/blob/master/src/classes/redis-connection.ts#L38
