### ISSUE TITLE
[Bug]: jobs get completed even without workers

### ISSUE THREAD

**Issue by runningman84** [taskforcesh/bullmq#2272]
### Version

v4.13.2

### Platform

NodeJS

### What happened?

We are running redis in cluster mode (aws elasticache) and use bullmq for out setup... Our concept looks like this

- main queue (n worker process events, if additional data is needed a job is placed in the describe queue)
- secondary queue (n worker process events and store results them in redis cache)

The main and secondary worker are running in k8s pods. A lot of times the main worker adds an event to the secondary queue the secondary worker never has the chance to work in the job. Because for some unknown reason the job is marked as complete even if it was never processed by any of our workers. Other times the secondary worker processes the item and everything looks fine.

How can we see who is messing up with our jobs in the second secondary queue? Can we see who is subscribed to the secondary queue?

### How to reproduce.

unclear

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Yeah, most likely you have another worker that you are unaware of that is consuming the jobs. You can call ```getWorkers``` to see, or redis command CLIENT LIST (https://redis.io/commands/client-list/)

**Comment by runningman84** [comment]
It looks like https://github.com/s-r-x/bull-monitor is messing with our queues, stopping the tool solved the issue for us.

**Comment by manast** [comment]
Ok, closing the issue then.
