### ISSUE TITLE
Question: What happens if a repeatable job takes longer to execute than its repeat period?

### ISSUE THREAD

**Issue by danthedaniel** [taskforcesh/bullmq#2285]
For example - what if I have a job scheduled to run every minute but over time it starts to take 2 minutes to execute? Will two jobs of that type get scheduled concurrently? Will the jobs start running every 2 minutes?

**Comment by manast** [comment]
As soon as a repeatable job starts to process, the next iteration of the job is added to the delayed set, so if you have idling workers or a concurrency higher than 1, the next iteration will start before the last iteration ended.

**Comment by ananni13** [comment]
This scenario is also explained in the docs: https://docs.bullmq.io/guide/jobs/repeatable#slow-repeatable-jobs

**Comment by danthedaniel** [comment]
Thanks!

**Comment by MrWang6w** [comment]
> As soon as a repeatable job starts to process, the next iteration of the job is added to the delayed set, so if you have idling workers or a concurrency higher than 1, the next iteration will start before the last iteration ended.

In addition to setting the worker thread to 1, is there any other more convenient solution? I did not find an API to change the execution time of the next repeated task in the worker function. I would like to ask if there is such an API?

In some cases, my work function may take 30 seconds to process an asynchronous task, or it may only take 10 seconds, but my scheduled task interval is uncertain. At this time, I can create a special interval when creating the task. Big, when I call the worker's API internally after executing the asynchronous task to modify the next execution time of the repeated task, I think this problem can be solved elegantly!
