### ISSUE TITLE
`convertExecArgv()` embedded loop not completing before function

### ISSUE THREAD

**Issue by preston-vasquez** [taskforcesh/bullmq#229]
It looks like you're using an async function inside a for loop here:  

https://github.com/taskforcesh/bullmq/blob/master/src/classes/child-pool.ts#L18

`convertExecArgv()` completes before the loop completes.  I'm surprised this hasn't come up before, but I'm dealing with a fairly complex cluster of child processes.  What do you guys think?  It looks like the async loop function is used only for the sake of `getPort()`?  

Maybe this would work better:

```typescript
  for (let arg in execArgv) {
    if (arg.indexOf('--inspect') === -1) {
      standard.push(arg);
    } else {
      const argName = arg.split('=')[0];
      const port = await getPort();
      convertedArgs.push(`${argName}=${port}`);
    }
  };
```

**Comment by manast** [comment]
yes thats definitely better, the older code is incorrect, must have been a copy paste error from Bullv3. 
If you could make this into a PR I would gladly merge it ;).
