### ISSUE TITLE
[Bug]: Job fetching stopped

### ISSUE THREAD

**Issue by urossmolnik** [taskforcesh/bullmq#2290]
### Version

v4.14.0

### Platform

NodeJS

### What happened?

We often end up in scenario (mostly in development) when job fetching is stopped and new scheduled jobs are not processed.
This problem is really visible when you have a long running job(s). In our case, we have one job that is constantly running - for max 30 minutes and then re-schedules itself.

We can optimize our setup and not run a job for that long, but job fetching should still not be blocked by single longer running job.

### How to reproduce.

- Schedule a long running job
- `AsyncFifoQueue` ends up in state where `this.pending.size > 0` and `this.queue.length === 0`
- Worker's call to `job = await asyncFifoQueue.fetch();` ends up waiting forever (until only pending job completes)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by urossmolnik** [comment]
@manast was this problems possibly introduced with #2242? 
[Here](https://github.com/taskforcesh/bullmq/compare/master...linear:bullmq:uros/fix-job-fetch) is a dummy fix that fixes this problem for us. But I am sure I a missing something and a more elegant solution exists.

**Comment by apizzini** [comment]
Hello, I experienced the same issue after upgrading from `4.13.3` to `4.14.0`.

We have several queues, and in particular this issue (job sitting idle in `waiting`) was happening only on a queue that is handling long running jobs.

I've downgraded to `4.13.3` as a temporary solution and so far everything is back to working perfectly :)

**Comment by manast** [comment]
Thanks for reporting this. I will try to  create a test case for it and release a fix asap.

**Comment by manast** [comment]
I have a test case that reproduces this issue and can also confirm that the proposed fix works, however I need to understand better if there are no other side effects with the fix.
