### ISSUE TITLE
[Bug]: AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by ahmed-abdelfata7** [taskforcesh/bullmq#2299]
### Version

bullmq 4.13.0 and "@bull-board/api": "^5.9.1",     "@bull-board/express": "^5.9.1",     "@bull-board/ui": "^5.9.1",

### Platform

NodeJS

### What happened?

All job created status changed from delayed to failed.
<img width="1670" alt="Screenshot 2023-11-25 at 9 03 02 PM" src="https://github.com/taskforcesh/bullmq/assets/31143554/b74a8e84-7d2c-43d1-85cb-fe42d5afe583">

### How to reproduce.

Setup BullMQ with BullMQ UI and once I created scheduled job status changed from delayed to failed and even the worker handler not executed after adding some logs inside it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Seems like the issue is related to a different repo. I will reopen if some test code is provided for reproduction.
