### ISSUE TITLE
[Bug]: Error retrieving Jobs when using String (UUID) as JobId

### ISSUE THREAD

**Issue by hrydi** [taskforcesh/bullmq#2302]
### Version

v4.12.5

### Platform

NodeJS

### What happened?

it throwing an error in my API "Unexpected token 'd', \"dc3223a8-8\"... is not valid JSON" 
and this full error from the service
SyntaxError: Unexpected token 'd', "dc3223a8-8"... is not valid JSON at JSON.parse (<anonymous>) at Job.fromJSON (/app/api/node_modules/bullmq/dist/cjs/classes/job.js:146:29) at Job.fromId (/app/api/node_modules/bullmq/dist/cjs/classes/job.js:202:24) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

## add some job
```javascript
const job  = await queue.add('some job name', {}, { delay: 1000, jobId: uuid() }
```
## get some jobs
```javascript
const jobs = await queue.getJobs()
```
error happen when retrieving jobs from queue

### Relevant log output

```shell
SyntaxError: Unexpected token 'd', "dc3223a8-8"... is not valid JSON at JSON.parse (<anonymous>) at Job.fromJSON (/app/api/node_modules/bullmq/dist/cjs/classes/job.js:146:29) at Job.fromId (/app/api/node_modules/bullmq/dist/cjs/classes/job.js:202:24) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Can you please provide the complete snippet including the uuid dependency and the queue instantiation?

**Comment by hrydi** [comment]
This is my snippet
```javascript
const { v4: uuid } = require('uuid')
const { Queue } = require('bullmq')
const IORedis = require('ioredis').default
const connection = new IORedis({
  host: process.env.REDIS_HOST,
  port: +process.env.REDIS_PORT,
  maxRetriesPerRequest: null,
})
const queue = new Queue('report', { connection })
const job = await queue.add('report ticket', {}, { delay: 1000, jobId: uuid() })
```
Now i just browse the redis using redis client (RedisInsight) and found some interesting, i guess the value of progress should be int / number, but it came the jobId.
![image](https://github.com/taskforcesh/bullmq/assets/10083755/acee433e-b856-43b9-8c46-1377b62fe443)

**Comment by manast** [comment]
The job in the screenshot is a processed job. So the snippet you provide will not be enough to produce that result. So my guess is that your worker is generating an invalid progress value.

**Comment by hrydi** [comment]
i'am sorry @manast the screenshot is just my curiosity
then, what is the continuation of the problem that i experienced?
is it because my worker generating invalid progress value or something else?

**Comment by hrydi** [comment]
### server
```javascript
const host = process.env.HOST
const port = +process.env.PORT
const { v4: uuid } = require('uuid')
const express = require('express')
const app = express()
const server = require('http').Server(app)
const IORedis = require('ioredis').default
const connection = new IORedis({
  host: process.env.REDIS_HOST,
  port: +process.env.REDIS_PORT,
  maxRetriesPerRequest: null,
})

const { Queue } = require('bullmq')
const queue = new Queue('report', { connection })
const { createBullBoard } = require('@bull-board/api');
const { BullMQAdapter } = require('@bull-board/api/bullMQAdapter');
const { ExpressAdapter } = require('@bull-board/express');
const serverAdapter = new ExpressAdapter()
serverAdapter.setBasePath('/queues')
createBullBoard({
  queues: [new BullMQAdapter(queue)],
  serverAdapter,
})

app.enable('trust proxy')
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use('/queues', [ serverAdapter.getRouter() ])

app.get('/', (req, res) => res.send('Hello'))
app.get('/test', async(req, res) => {
  try {
    const job = await queue.add('report ticket', {}, { delay: 1000, jobId: uuid() })
    await queue.clean(10)
    res.json({...job.toJSON()}).end()
  } catch (e) {
    res.json({ error: true, message: e.message }).end()
  }
})

server.listen(port, host)
server.on('listening', () => console.log(`server run http://${host}:${port}`))
server.on('error', e => {
  process.exit(1)
})
```
### worker
```javascript
const { Worker } = require('bullmq')
const IORedis = require('ioredis').default
const connection = new IORedis({
  host: process.env.REDIS_HOST,
  port: +process.env.REDIS_PORT,
  maxRetriesPerRequest: null,
})

const delay = n => new Promise((resolve) => setTimeout(resolve, n*1000))

const options = { 
  connection,
  autorun: false
}

const worker = new Worker('report', async job => {
  try {
    await delay(10)
    await job.updateProgress(45) # if using this the queue.getJobs always failed
    await delay(4)
    await job.updateProgress(100) # if using this the queue.getJobs always failed
    return Promise.resolve({ success: true })
  } catch (e) {
    return Promise.reject(e)
  }
}, options)

worker.run()
```

I hope this could use as reproduce the result,
i just try to remove the job.updateProgress from worker and the queue.getJobs work just fine while using custom jobId

**Comment by manast** [comment]
can you try this version bullmq@4.14.3 instead? it seems like a broken release to some security settings leads to this error.

**Comment by hrydi** [comment]
### Test Create
![image](https://github.com/taskforcesh/bullmq/assets/10083755/4b496a4c-42ff-404c-8351-26801d809e20)

### Test Get
![image](https://github.com/taskforcesh/bullmq/assets/10083755/c845497e-3e1c-405f-8aa1-cafe0203fda2)

### Bull Board Preview
![image](https://github.com/taskforcesh/bullmq/assets/10083755/3486cd1d-b84f-4653-a5ae-d3ac2f63812a)
![image](https://github.com/taskforcesh/bullmq/assets/10083755/1c9b718b-544b-4fcf-9412-9a3deb5fb317)

### Result using v.4.14.3
Everything work as expected, i think it works fine now.
Thankyou @manast and teams
