### ISSUE TITLE
Supprt for BullMQ with AWS MemoryDB

### ISSUE THREAD

**Issue by gauravGupshup** [taskforcesh/bullmq#2308]
**Is your feature request related to a problem? Please describe.**
There is no official mentioning in any of the documents that bullMQ support AWS MemoryDB instead of Redis. We like to explore BullMQ with AWS MemoryDB.

**Describe the solution you'd like**
Improve the documentation with a full blown example of how to connect to a BullMQ with AWS MemoryDB and that stats the benchmarking.

**Describe alternatives you've considered**
For now only alternative we have is to use AWS MemoryDB.

**Additional context**
Required a proper document with code examples

- AWS MemoryDB config requirements
- TPS Benchmarking
- Configure connections, Worker, and Queue for AWS MemoryDB
- TLS support

**Comment by manast** [comment]
Thanks for the issue.  I will add a "Redis Hosting Alternatives" section to the documentation where I also will include MemoryDB.

**Comment by gauravGupshup** [comment]
@manast Thanks for the prompt response, please help me understand that does BullMQ has official support for MemoryDB or not?
If you have any sample code snippet or example for this then it would be great.

**Comment by manast** [comment]
Working on the documentation right now.

**Comment by manast** [comment]
https://docs.bullmq.io/guide/redis-tm-hosting/aws-memorydb

**Comment by manast** [comment]
Let me know if it works as expected.

**Comment by gauravGupshup** [comment]
Yes sure, will check and update the issue.

**Comment by gauravGupshup** [comment]
@manast Thanks for the support, I've made some changes to the configuration to make it work and the below code snippet works for me

```
const { Queue, Worker } = require("bullmq");
const { Cluster } = require("ioredis");

const connection = new Cluster(
  [
    {
      host: clusterEndpoint,
      port: clusterPort,
    },
  ],
  {
    // skip certificate hostname validation
    dnsLookup: (address, callback) => callback(null, address),
    redisOptions: {
      tls: true,
      username: clusterUsername,
      password: clusterPassword,
    },
  }
);

connection.on("ready", () => {
  console.log("Redis Client Ready");
  // '{myprefix}' is required for cluster mode to handle proper hash key, reference link: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster
  myQueue = new Queue("my-queue", {  prefix: '{myprefix}', connection });

  const worker = new Worker(
    "my-queue",
    async (job) => {
      // Add job execution code here
    },
    { prefix: '{myprefix}', connection, concurrency: 20 }
  );
});
```

**Comment by manast** [comment]
@gauravGupshup is this the most important change to make it work?
```
    dnsLookup: (address, callback) => callback(null, address),

```

**Comment by gauravGupshup** [comment]
> @gauravGupshup is this the most important change to make it work?
> 
> ```
>     dnsLookup: (address, callback) => callback(null, address),
> ```

Without that it was giving the error and was not able to connect so, to skip certificate hostname validation issue I found that workaround https://github.com/redis/ioredis?tab=readme-ov-file#special-note-aws-elasticache-clusters-with-tls. but after that, I found one more alternative to this

```
const connection = new Cluster(
  [
    {
      host: clusterEndpoint,
      port: clusterPort,
    },
  ],
  {
    redisOptions: {
      tls: {
          servername: clusterEndpoint
      },
      username: clusterUsername,
      password: clusterPassword,
    },
  }
);
```

**Comment by gauravGupshup** [comment]
@manast Do you know how can we setup offline queue for Cluster mode?

**Comment by manast** [comment]
I do not have anything more to say in this issue, so please open a new one if something is not completed here.
