### ISSUE TITLE
Decoupling bull app from main node.js into separate app?

### ISSUE THREAD

**Issue by hagginoaks** [taskforcesh/bullmq#232]
I'm thinking of pulling out my bull/taskworker logic from my main node.js app into a separate one, thus having 2 apps. One for interfacing with incoming user requests, db queries, logic, page rendering, etc. The second app would solely accept (through a REST api) requests to my taskworker.

This would allow me to more easily test my taskworker, and if for whatever reason the process of my taskworker app gets a SIGINT/unhandled exception, etc. when redis goes down or node crashes, it won't bring down my main app.

The main downside I can think of is if my taskworker app goes offline, my main node app (interfacing with the DB, serving pages, etc.) won't be able to send any new events to the service, however, I think I can write add some logic to write to a temporary table in my (postgres) database some JSON and then when my taskworker app comes back online, I can query that db table and if there are any new events, process them accordingly.

Would this be a good design pattern?

**Comment by manast** [comment]
I think separating the workers part from the main application is not only a good approach it is the whole point of using BullMQ to begin with. For many reasons, but regarding availability, I would propose that the main app adds jobs directly to redis, and strive after having a redis deployment that is as highly available as possible. If redis is down, then the main app api that ends calling the addJob command will fail, but then you can notify the users in the UI and tell them that there is a temporal error... I do not think there are many other ways to do this better, all services can go down at sometime and it is ok to tell the user that the service is not working properly right now, the important thing is that this does not happens very often of course.

**Comment by hagginoaks** [comment]
@manast thank you very much. You have been so helpful to me. Do you accept donations?
