### ISSUE TITLE
[Bug]: this is undefined in child-processor

### ISSUE THREAD

**Issue by yrigaudeau** [taskforcesh/bullmq#2320]
### Version

v1.13.1

### Platform

NodeJS

### What happened?

Calling updateProgress inside a job make the worker crash. Works correctly until 4.12.1.

When I comment "this.progress = progress" in https://github.com/taskforcesh/bullmq/blob/96adcc90e7e8c75157470ce12bb9fde4b5078228/src/classes/child-processor.ts#L126 it works.
This is due to "this" to be undefined.

### How to reproduce.

Create a Worker instance
```ts
  const worker = new Worker(process.env.QUEUE_NAME, processorFile, {
    connection: {
      host: process.env.REDIS_HOST,
    },
    autorun: false,
    concurrency: 10,
  });

  await worker.run();
```
Call updateProgress inside
```ts
updateProgress({["blablabla"]});
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
What is the error your are getting including callstack?

**Comment by manast** [comment]
Closing due to lack of response.
