### ISSUE TITLE
[Bug]: ESM loader error. Sandbox processor not working

### ISSUE THREAD

**Issue by miroirstudiosrl** [taskforcesh/bullmq#2326]
### Version

4.15.2

### Platform

NodeJS

### What happened?

I've created a queue with a sandbox processor:

```
   const worker = new Worker(
      name,
      join(__dirname, name, `${name}.processor.js`),
      {
        connection: {
          host: this.configService.get('redisHost'),
          port: this.configService.get('redisPort'),
        },
        useWorkerThreads: true,
      },
    );
```

When I try to start the job I get the following error:
```
Error: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:236:11)
    at defaultLoad (node:internal/modules/esm/load:128:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at ModuleLoader.#createModuleJob (node:internal/modules/esm/loader:303:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:23)
```

Node: 20.1.0
OS: Windows 11
Typescript: 5.2.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
This seems to be a windows specific issue. I do not have access to windows, have you tried to address the issue as suggested by the error message?

**Comment by manast** [comment]
Here you can find several suggestions that may help you solve the issue: https://stackoverflow.com/questions/69665780/error-err-unsupported-esm-url-scheme-only-file-and-data-urls-are-supported-by

**Comment by miroirstudiosrl** [comment]
@manast I've tried using the `file://` protocol and using different node versions. The only solution I found (not a real one) is to use a bullmq version prior to `4.15.0`. Actually `4.15` gives me problem also in production, where I'm using a Docker container with node alpine image.

**Comment by manast** [comment]
The error comes from using dynamic imports. What else can you share about your setup? is it windows as suspected, what else, do you use some packaging tool as esbuild, etc?

**Comment by manast** [comment]
Basically BullMQ is just doing this: ```await import(filename)```. If calling this function throws an exception as the one in this issue, then it is most likely that the issue is in the filename (pathname), or something specific to your environment.

**Comment by manast** [comment]
You should try a dummy example where you try to load a js module using a dynamic import, see if it also fails with the same error.

**Comment by miroirstudiosrl** [comment]
> You should try a dummy example where you try to load a js module using a dynamic import, see if it also fails with the same error.

Unluckly a simple example (running in the same application with Nest) works without any issue:
Example ran: `await import(join(__dirname, 'test.js'));`

**Comment by manast** [comment]
You can put a console.log before bullmq's call to await import in child-processor (you can just edit the file in the dist directory), according to the error the file starts with "c:", so thats what we should figure out, where comes that from.

**Comment by miroirstudiosrl** [comment]
> You can put a console.log before bullmq's call to await import in child-processor (you can just edit the file in the dist directory), according to the error the file starts with "c:", so thats what we should figure out, where comes that from.

This is quite funny. I've tried to add the exact same import that's inside `child-processor` in my code and debug it.
As you can see from the image below the import works fine without any exception:
![image](https://github.com/taskforcesh/bullmq/assets/116894178/a4476b58-cd88-4658-86ff-9e3e0767a51c)

However the exact same instruction inside bullmq fails, as you can see from the screenshot below:
![image](https://github.com/taskforcesh/bullmq/assets/116894178/76872ae4-9712-4e67-9948-361ce1d10605)

I've double checked, just to be sure, and I can ensure you that the value of both `processorFile` (mine and the one passed to bull) are exactly the same.

**Comment by manast** [comment]
As you can see the processor file path is incorrect as it starts with C:\\, make sure it starts with file:\\ and I think it will work.

**Comment by x-etienne** [comment]
Same thing here :(

**Comment by manast** [comment]
I find it quite strange that you will get the same error if the processor file does not start with c:/, as that is what the message is literally saying.

**Comment by manast** [comment]
can you try to convert the path to a url using this? https://nodejs.org/api/url.html#url_url_pathtofileurl_path

**Comment by manast** [comment]
@x-etienne you understand the error right? it is not a bug in BullMQ, you need to pass a correct URL, and in windows __dirname starts with c:/ which is not correct. Use https://nodejs.org/api/url.html#url_url_pathtofileurl_path to fix the path.

**Comment by miroirstudiosrl** [comment]
> can you try to convert the path to a url using this? https://nodejs.org/api/url.html#url_url_pathtofileurl_path

The weird thing is that the same instruction (with the path starting with `c:\` is working outside of bull.
Anyway I tried adding `file:\\` protocol using the function you suggested:
`pathToFileURL(join(__dirname, name, `${name}.processor.js`)).href`.

It doesn't find the file (I can confirm the file exists at that location):
![image](https://github.com/taskforcesh/bullmq/assets/116894178/6f9e9945-dd5b-4821-b09f-b71cd6f9dadb)

**Comment by x-etienne** [comment]
Hi @manast and @miroirstudiosrl 

I found some problem with check file in Worker.ts source:

First of all, if in 'windows' system you try this:

```
const nodeurl = require('node:url');
const fs = require('fs');

const path = `${__dirname}\\index.js`;
const url = nodeurl.pathToFileURL(path);
const fileUrl = url.href;

console.log(path);
console.log(url);
console.log(fileUrl);

console.log(`with path, does file exist?: ${fs.existsSync(path)}`); // with path, does file exist?: true
console.log(`with url, does file exist?: ${fs.existsSync(url)}`); // with url, does file exist?: true
console.log(`with fileUrl, does file exist?: ${fs.existsSync(fileUrl)}`); // with fileUrl, does file exist?: false
```
you get this

```
URL {
  href: 'file:///C:/tmp/mono/index.js',
  origin: 'null',
  protocol: 'file:',
  username: '',
  password: '',
  host: '',
  hostname: '',
  port: '',
  pathname: '/C:/tmp/mono/index.js',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
file:///C:/tmp/mono/index.js
with path, file exists?: true
with url, file exists?: true
with fileUrl, file exists?: false
```

So the `fs.existsSync` function needs a `URL` object to evaluate true the existing file test.
In the source of `worker.ts` 

https://github.com/taskforcesh/bullmq/blob/67c3b8b7af266ba8be82fa1e095ac86c8b86e6a1/src/classes/worker.ts#L241 

the program test a `string`. If you look at the costructor

https://github.com/taskforcesh/bullmq/blob/67c3b8b7af266ba8be82fa1e095ac86c8b86e6a1/src/classes/worker.ts#L196

the class needs a path file as `string`

I suspect that this is the problem, the program stop to work because it needs a string path file.

@manast can you change the costructor method of `Worker` class ?

**Comment by x-etienne** [comment]
Hi @manast , Yes I think so

Can you do this change in repo?

thanks!

**Comment by manast** [comment]
Unfortunatelly this will not work for remote URLs, as neither ```fs.existsSync``` nor ```import``` support other than local files.
