### ISSUE TITLE
[DOCS]: Incorrect documentation regarding connection reuse 

### ISSUE THREAD

**Issue by EricDunaway** [taskforcesh/bullmq#2334]
### Version

NA

### Platform

NodeJS

### What happened?

The documentation for BullMQ needs to be corrected.
https://docs.bullmq.io/bull/patterns/reusing-redis-connections
It states that you need to implement code to reuse connections.

#1236 - This issue does state that the page is outdated, but the page should be removed from the BullMQ documentation site as it leads to developer confusion.

### How to reproduce.

Goto to https://docs.bullmq.io/bull/patterns/reusing-redis-connections 
View incorrect documentation

or 
Goto  https://docs.bullmq.io
Search for `Redis Connections`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @EricDunaway this is a bull pattern https://docs.bullmq.io/bull/patterns/reusing-redis-connections, not a bullmq one

**Comment by EricDunaway** [comment]
@roggervalf 
I apologize I didn't realize that the documentation for both packages was on the same site. I was looking at the domain and site header

![Screenshot_20231214-175313.png](https://github.com/taskforcesh/bullmq/assets/4960630/0b7a8408-0f2e-431a-8887-066b518f7202)
