### ISSUE TITLE
waitUntilFinished need listen "removed:jobId" events

### ISSUE THREAD

**Issue by wangkunmeng** [taskforcesh/bullmq#2341]
https://github.com/taskforcesh/bullmq/blob/136e8e7f3f2e69dcf32406ee3513962cedcd13f8/src/classes/job.ts#L988

When you call waitUntilFinished without timeout, and then you manual removed the job. The promise can never return.

**Comment by manast** [comment]
Yeah, not sure what should be done here. We do not recommend to use ```waitUntilFinished``` in production (https://blog.taskforce.sh/do-not-wait-for-your-jobs-to-complete/). I think if the user is not using TTL then there is always a risk it will hang forever, maybe we should enforce it or add a default value for it.

**Comment by wangkunmeng** [comment]
I do not  recommend to use waitUntilFinished in production either. I implement my own logic with reference to waitUntilFinished, and waitUntilFinished is not universal.

1. listen completed/failed/removed events global.
2. add listener before job create. 
3. Promise.race([setTimeout(timeout), jobListener]);

```ts
        this.queueEvents.on('completed', data => this.onJobFinishedOrRemoved(data));
        this.queueEvents.on('failed', data => this.onJobFinishedOrRemoved(data));
        this.queueEvents.on('removed', data => this.onJobFinishedOrRemoved(data));
```
