### ISSUE TITLE
Adding multiple jobs at once?

### ISSUE THREAD

**Issue by VakoNonikashvili** [taskforcesh/bullmq#236]
I have array of users and want to send transactional emails to each user. Is it possible to map users, make array of jobs and add in queue at the same time?

**Comment by manast** [comment]
Yes, you should be able to use the ```addBulk``` method: https://github.com/taskforcesh/bullmq/blob/2da059df47c55074036fdbf347cd5ee38971487c/src/classes/queue.ts#L74
