### ISSUE TITLE
Redis-py v5 support

### ISSUE THREAD

**Issue by lqmanh** [taskforcesh/bullmq#2361]
**Is your feature request related to a problem? Please describe.**
My app requires redis >= 5, but Bullmq only supports [redis >= 4.5.0, < 5](https://github.com/taskforcesh/bullmq/blob/master/python/pyproject.toml#L23).

**Describe the solution you'd like**
If there are not any issues, could you consider loosening this constraint to >= 4.5 only?

**Comment by manast** [comment]
I do not know why we have this constraint, as long as the tests passes then it should be fine I think.

**Comment by roggervalf** [comment]
as we require greater version than 3.10 for python we can try upgrading redis https://github.com/taskforcesh/bullmq/blob/master/python/pyproject.toml#L13, what I can see is that one of the breaking changes about v5 is dropping the support of python 3.7 https://github.com/redis/redis-py/pull/2852
