### ISSUE TITLE
[Bug]: Sandboxed processors not waiting but directly failing when concurrency is already at max

### ISSUE THREAD

**Issue by xavier-villelegier** [taskforcesh/bullmq#2366]
### Version

BullMQ v5.1.1
Node 21.5.0

### Platform

NodeJS

### What happened?

Hey hey !

I'm already using BullMQ without sandboxed processors, and it's been working pretty well so far. But I want to switch to sandboxed processors to avoid memory leaks, and have better performances. I encountered a weird behavior on production, which is that once I already have the max "active" jobs (depending on my `concurrency` settings), all the next ones are **not** going to the `waiting` state but are directly failing, even when using a very dummy setup like this

`worker.ts`
```ts
const processorFile = path.join(__dirname, 'alertRunner', 'test.js')

const worker = new Worker('run-alerts', processorFile, {
  connection: redisConnection,
  removeOnComplete: { count: 250 },
  removeOnFail: { count: 500 },
  concurrency: 3,
  useWorkerThreads: true,
})
```

`alertRunner/test.js`
```js
console.log('evaluating test.js')

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

module.exports = async (job) => {
  console.log('test', job.id)
  await sleep(5000)

  return 'SUCCESS'
}
```

`enqueue.ts` in order to enqueue some jobs to test
```ts
export const alertsQueue = new Queue('run-alerts', {
  connection: redisConnection,
  defaultJobOptions: {
    attempts: 3,
    backoff: {
      type: 'exponential',
      delay: 1000,
    },
  },
})

…

await alertsQueue.add('1', {}, { jobId: uuidv4() })
await alertsQueue.add('2', {}, { jobId: uuidv4() })
await alertsQueue.add('3', {}, { jobId: uuidv4() })
await alertsQueue.add('4', {}, { jobId: uuidv4() })
```

Would you think about anything that could explain this behavior ? As my concurrency is 3 here, the first 3 are going to succeed, and the other ones directly fail with the error linked below without a lot of context. Is there any way to have more details in the error ?

I also tried to not use `useWorkerThreads`, but in this case, nothing happens when I enqueue jobs. 3 of them go to `active`, but `test.js` is never evaluated so nothing happens

Thanks for your help 🙏 

### Relevant log output

The error message that BullMQ is showing:

```shell
Error
    at Child.msgHandler (/app/node_modules/bullmq/src/classes/sandbox.ts:29:25)
    at Child.emit (node:events:514:28)
    at Child.emit (node:domain:488:12)
    at Worker.<anonymous> (/app/node_modules/bullmq/src/classes/child.ts:110:44)
    at Worker.emit (node:events:514:28)
    at Worker.emit (node:domain:488:12)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

A few logs on what is emitted:
```
emitting added [ { jobId: '3260', name: '1' }, '1704634835946-0' ]
emitting added:3260 [ { jobId: '3260', name: '1' }, '1704634835946-0' ]
emitting waiting [ { jobId: '3260' }, '1704634835946-1' ]
emitting waiting:3260 [ { jobId: '3260' }, '1704634835946-1' ]
emitting added [ { jobId: '3261', name: '2' }, '1704634835946-2' ]
emitting added:3261 [ { jobId: '3261', name: '2' }, '1704634835946-2' ]
emitting waiting [ { jobId: '3261' }, '1704634835946-3' ]
emitting waiting:3261 [ { jobId: '3261' }, '1704634835946-3' ]
emitting active [ { jobId: '3260', prev: 'waiting' }, '1704634835947-0' ]
emitting active:3260 [ { jobId: '3260', prev: 'waiting' }, '1704634835947-0' ]
emitting active [ { jobId: '3261', prev: 'waiting' }, '1704634835949-0' ]
emitting active:3261 [ { jobId: '3261', prev: 'waiting' }, '1704634835949-0' ]
emitting failed [ { jobId: '3260', failedReason: '' }, '1704634835952-0' ]
emitting failed:3260 [ { jobId: '3260', failedReason: '' }, '1704634835952-0' ]
emitting retries-exhausted [ { jobId: '3260', attemptsMade: '1' }, '1704634835952-1' ]
emitting retries-exhausted:3260 [ { jobId: '3260', attemptsMade: '1' }, '1704634835952-1' ]
emitting failed [ { jobId: '3261', failedReason: '' }, '1704634835955-0' ]
emitting failed:3261 [ { jobId: '3261', failedReason: '' }, '1704634835955-0' ]
emitting retries-exhausted [ { jobId: '3261', attemptsMade: '1' }, '1704634835955-1' ]
emitting retries-exhausted:3261 [ { jobId: '3261', attemptsMade: '1' }, '1704634835955-1' ]
emitting drained [ '1704634835955-2' ]
```

From what I see when putting console.logs, the jobs is indeed added in `queue.ts` here
https://github.com/taskforcesh/bullmq/blob/0a70f4cf7ba21c18c55390d47069335c305559af/src/classes/queue.ts#L219

But we never reach this this line
https://github.com/taskforcesh/bullmq/blob/0a70f4cf7ba21c18c55390d47069335c305559af/src/classes/worker.ts#L729

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xavier-villelegier** [comment]
If this can help, I noticed that it doesn't happens when pointing to a local redis docker container, but it does when pointing to a remote redis container. All other jobs work fine, only sandboxed jobs are affected.

I can provide the remote redis URL if needed

**Comment by xavier-villelegier** [comment]
Oh wow, dropping the redis container et re-creating it did the job. I guess changing the queue name would've done the job too

Is there anything in BullMQ that would not be retro-compatible when changing a worker from standard function processor to sandboxed processor?

Closing this as it's fixed on my side 👌

**Comment by manast** [comment]
It should be compatible, not sure what happened in your specific case.
