### ISSUE TITLE
Add "abandoned" events for jobs that have exceeded their max retries or stalled out

### ISSUE THREAD

**Issue by ninapavlich** [taskforcesh/bullmq#2369]
**Is your feature request related to a problem? Please describe.**
I am trying to monitor when a job fails and is getting abandoned by the queue. I have observed two ways that a task can be abandoned:
1. If the attempts made exceed the max attempts
2. If the job fails because `job stalled more than allowable limit`

**Describe the solution you'd like**
Instead, it would be more reliable if I could just listen for an abandoned event that has all the relevant info:

```
queue.on("abandoned", (job: Bull.Job<any>) => {
    const { id, name, attemptsMade, failedReason } = job;
    logger.error(`queue:${name}:abandoned for job #${id}: ${failedReason}`);
});
```

**Describe alternatives you've considered**

In order to catch these two cases, this is the solution I'm using:

```
queue.on("failed", (job: Bull.Job<any>) => {

      const { id, name, attemptsMade, failedReason } = job;

      logger.error(
        `queue:${name}:failed for job #${id} attempt ${attemptsMade}/${QUEUE_MAX_ATTEMPTS}: ${failedReason}`,
      );
     
      // A job can be considered abandoned if either the number of attempts is exceeded
      const isAbandoned =
        attemptsMade >= QUEUE_MAX_ATTEMPTS ||
        failedReason?.includes("job stalled");

      if (isAbandoned) {
        logger.error(`queue:${name}:abandoned for job #${id}: ${failedReason}`);
      }
    });
```

This feels unreliable and a little messy to me, and also makes me wonder if there are other situations where a task can be abandoned that I'm just not aware of.

**Additional context**

**Comment by roggervalf** [comment]
hi @ninapavlich, we have https://api.docs.bullmq.io/interfaces/v5.QueueEventsListener.html#retries_exhausted this event for retries exhausted and for failures `like job stalled more than allowable limit` is handled by https://api.docs.bullmq.io/interfaces/v5.QueueEventsListener.html#failed

**Comment by ninapavlich** [comment]
Thanks so much @roggervalf! I had been referencing the events listed in the code (through VS code) which for some reason only listed these events: `error, waiting, active, stalled, progress, completed, failed, paused, resumed, removed, cleaned, drained` - but now I see in the docs that there are way way more. 

Fantastic, thanks for pointing me to the right place!

**Comment by CodingMeSwiftly** [comment]
Will `retries-exhausted` also run if the throw  `UnrecoverableError` in a worker?
Additionally, with the current tools, we still have to make the awkward `if (failedReason.includes("job stalled")` check in the `failed` event handler. What if the event text for a stalled job changes in the future?

I think the original intent behind this issue is still valid.

A dedicated event indicating that a job is considered "failed for good, no more retries will take place" would be very valuable.

**Comment by CodingMeSwiftly** [comment]
There is also the queue event `removed`, which in conjunction with `removeOnFail` could be used for this. But the docs for that event state: This event is triggered when a job has been **manually** removed from the queue.
