### ISSUE TITLE
Code examples of backoff functions

### ISSUE THREAD

**Issue by Alserda** [taskforcesh/bullmq#237]
I'm trying to implement functionality to retry failed jobs, the documentation says:

> BullMQ support retries of failed jobs using backoff functions.

Can you provide code examples so I know how this can be implemented? I've tried adding the `attempts` option, but this fires them without a delay. Adding the `delay` parameter does nothing. 

I've got processors for jobs that send HTTP requests. Using an exponential backoff would seem ideal. 

As of right now I've got:
```
  const queue = new Queue(queueId);

  queue.add(name, data, {
    backoff: 2,
  });
```

This fires a `failed` event on my Worker class instance. Calling the `.retry()` function on the job fires it instantly.
How are the backoff functions intended to be?

**Comment by kai-jacobsen** [comment]
@Alserda Should work like it did in earlier versions:
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd

try: 
```
{
attempts: 5, // you have to set this as well
backoff: 
  {
    type: 'exponential', // or 'fixed' 
    delay: 10000 // first retry after 10s, second retry after 20s, 40s,...
   }
}

**Comment by Alserda** [comment]
@kai-jacobsen I've tried this but it doesn't seem to work as expected. 
```
queue.add(name, data, {
    attempts: 5,
    backoff: {
      type: 'exponential',
      delay: 5000,
    },
  });
```

Afterwards, the `failed` event is fired on my worker, but nothing happens after that. I'm using bullmq version `1.9.0`.

Logging the job returned from `queue.add` would return:

```Job {
  queue: Queue {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    name: 'Game',
    opts: { prefix: 'bull' },
    connection: RedisConnection {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      opts: [Object],
      _client: [Redis],
      initializing: [Promise],
      [Symbol(kCapture)]: false
    },
    keys: {
      '': 'bull:Game:',
      active: 'bull:Game:active',
      wait: 'bull:Game:wait',
      waiting: 'bull:Game:waiting',
      paused: 'bull:Game:paused',
      resumed: 'bull:Game:resumed',
      id: 'bull:Game:id',
      delayed: 'bull:Game:delayed',
      priority: 'bull:Game:priority',
      'stalled-check': 'bull:Game:stalled-check',
      completed: 'bull:Game:completed',
      failed: 'bull:Game:failed',
      stalled: 'bull:Game:stalled',
      repeat: 'bull:Game:repeat',
      limiter: 'bull:Game:limiter',
      drained: 'bull:Game:drained',
      progress: 'bull:Game:progress',
      meta: 'bull:Game:meta',
      events: 'bull:Game:events',
      delay: 'bull:Game:delay'
    },
    token: '175535d3-bce9-488d-b725-628dad95d92e',
    limiter: undefined,
    jobsOpts: undefined,
    [Symbol(kCapture)]: false
  },
  name: 'created',
  data: { gameId: 'test', players: [ 1, 2 ] },
  opts: {
    attempts: 5,
    delay: 0,
    backoff: { type: 'exponential', delay: 5000 },
    jobId: undefined
  },
  id: '45',
  progress: 0,
  returnvalue: null,
  stacktrace: null,
  attemptsMade: 0,
  timestamp: 1595314422992,
  toKey: [Function: bound toKey]
}```

**Comment by kai-jacobsen** [comment]
@Alserda Did you add a 'QueueScheduler' for your Queue? (see: https://docs.bullmq.io/guide/jobs/delayed)

for your example it's like:
```
const queue = new Queue(queueId);
const queueScheduler = new QueueScheduler(queueId);

// inspect queue
await queue.getDelayed() // your failed job with backoff strategy should be here
await queue.getDelayedCount() // return just the number of delayed jobs

// get jobs by type
await queue.getJobs(['completed','failed','delayed','repeat','active','wait','paused'])

**Comment by Alserda** [comment]
@kai-jacobsen No I didn't - but adding a QueueScheduler did solve it.
My expectance would be that a queue scheduler would be instantiated out of the box, when creating a new Queue object. 
Thank you very much!

**Comment by demelvin** [comment]
I spent hours trying to figure out why my jobs were not repeating. This solved my issue.
