### ISSUE TITLE
Add "queued" event to identify when new items have been added to the queue

### ISSUE THREAD

**Issue by ninapavlich** [taskforcesh/bullmq#2370]
**Is your feature request related to a problem? Please describe.**
I am monitoring when items are added to the queue (for observability reasons), and it would be helpful to have an event to listen to identify when new items are added to the queue.

**Describe the solution you'd like**

```
 queue.on("queued", (job: Bull.Job<any>) => {
      const { id, name } = job;
      logger.info(`queue:${name}:queued with job #${id}`);
})
```

**Describe alternatives you've considered**
I currently put that code next to the code that adds items to the queue. This is less than ideal for my code organization, because I'd like to be able to monitor all events from one place.

**Additional context**

**Comment by roggervalf** [comment]
hey @ninapavlich for that purpose we have added event https://api.docs.bullmq.io/interfaces/v5.QueueEventsListener.html#added

**Comment by ninapavlich** [comment]
Amazing, thanks so much for clarifying! (I was looking at an older version of the API.)
