### ISSUE TITLE
Add "queuedOn" (and possibly "startedOn") to job info to allow for measuring queue performance

### ISSUE THREAD

**Issue by ninapavlich** [taskforcesh/bullmq#2371]
**Is your feature request related to a problem? Please describe.**
I am trying to monitor the length that jobs take from the time they are queued or started to the time it completes successfully. Currently I can measure the length of the most recent processing attempt with the `processedOn` and `finishedOn` - but since many of my jobs require retries, it doesn't give me a good estimate of how long jobs are taking to get completely through the queue. Additionally, this doesn't capture how long items may be waiting in the queue.

**Describe the solution you'd like**

Add these two properties to the `Job` object:

```
/**
 * When this job was added to the queue (unix milliseconds)
 */
queuedOn?: number | undefined;

/**
 * When this job was started for the first time (unix milliseconds)
 */
startedOn?: number | undefined;
```    

**Describe alternatives you've considered**
Currently I have to add data to the object, which feels a little messy. I'd prefer to have this data on the event so that I can measure performance in a more generic way. 

```
queue.add("myEvent", {
   queuedOn: Date.now(),
   startedOn: Date.now(),
   ... other data
});
```

**Additional context**

**Comment by roggervalf** [comment]
hey @ninapavlich, timestamp attribute is the same as queuedOn https://api.docs.bullmq.io/classes/v5.Job.html#timestamp, startedOn can be calculated by processedOn when https://api.docs.bullmq.io/classes/v5.Job.html#attemptsStarted is 1

**Comment by ninapavlich** [comment]
That's perfect, thanks so much for clarifying! (I was looking at an older version of the API.)
