### ISSUE TITLE
[Bug]: Priority not working

### ISSUE THREAD

**Issue by void-nick** [taskforcesh/bullmq#2387]
### Version

v4.17.0

### Platform

NodeJS

### What happened?

A job with priority is never being moved to active or is never processed.

### How to reproduce.

Create a queue and add jobs with custom `jobId` (to avoid duplicates) and no priority. Then, add a job with priority (e.g.:1) (still with custom jobId). That job is never prioritized over the others.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by void-nick** [comment]
I believe the issue might be related to moveToActive-10.lua:

```
local rcall = redis.call
local waitKey = KEYS[1]
local activeKey = KEYS[2]
local rateLimiterKey = KEYS[6]
local delayedKey = KEYS[7]
local opts = cmsgpack.unpack(ARGV[4])
--- ...
if jobId then
    return prepareJobForProcessing(KEYS, ARGV[1], target, jobId, ARGV[2],
                                   maxJobs, expireTime, opts)
else
    jobId = moveJobFromPriorityToActive(KEYS[3], activeKey, KEYS[10])
    if jobId then
        return prepareJobForProcessing(KEYS, ARGV[1], target, jobId, ARGV[2],
                                       maxJobs, expireTime, opts)
    end
end
```

**Comment by void-nick** [comment]
> hi @void-nick could you pls provide an example, also providing the format of your custom jobId could help as well

My job IDs are UUIDs. It's like an user, and sometimes I need to prioritize an user over the others.

**Comment by manast** [comment]
> I believe the issue might be related to moveToActive-10.lua:

I think that code is actually correct. ```jobId``` in this case is defined if the next job was prefetched when the previous one completed. But we will investigate it.

**Comment by void-nick** [comment]
To reproduce:
```
import { Queue,Worker } from 'bullmq';
import IORedis from 'ioredis';

const connection = new IORedis();
const myQueue = new Queue('foo', { connection });

async function addJobs() {
    for(let i = 0; i < 20; i++) {
        await myQueue.add('myJobName', { val: i }, { jobId: `id-${i}`, removeOnComplete: true })
    }
}
async function addPriorityJob() {
    await myQueue.add('myJobName', { val: 'PRIORITY' }, { jobId: 'id-x', priority: 1 })
}

const worker = new Worker('foo', async job => {
  console.log(job.data);
  //sleep for 1 second
  await new Promise(resolve => setTimeout(resolve, 1000));
}, { connection });

await addJobs();
await addPriorityJob();

worker.on('drained', async () => {
    //close worker and connection
    await worker.close();
    await connection.quit();
})
```
Logs:
```
{ val: 0 }
{ val: 1 }
{ val: 2 }
{ val: 3 }
{ val: 4 }
{ val: 5 }
{ val: 6 }
{ val: 7 }
{ val: 8 }
{ val: 9 }
{ val: 10 }
{ val: 11 }
{ val: 12 }
{ val: 13 }
{ val: 14 }
{ val: 15 }
{ val: 16 }
{ val: 17 }
{ val: 18 }
{ val: 19 }
{ val: 'PRIORITY' }
```

Should priority be the last?

**Comment by roggervalf** [comment]
hi @void-nick, yes this behavior is expected as explained in our docs https://docs.bullmq.io/guide/jobs/prioritized:

> Note that the priorities go from 1 to 2 097 152, where a lower number is always a higher priority than higher numbers.
Jobs without a `priority`` assigned will get the most priority.

**Comment by void-nick** [comment]
> hi @void-nick, yes this behavior is expected as explained in our docs https://docs.bullmq.io/guide/jobs/prioritized:
> 
> > Note that the priorities go from 1 to 2 097 152, where a lower number is always a higher priority than higher numbers.
> > Jobs without a `priority`` assigned will get the most priority.

Alright. My mistake for not paying to that.
But one question: does it make sense? Jobs **without priority** will get the **most priority**?

**Comment by manast** [comment]
Yes, as the priorities goes from lower to higher numbers, no priority is the same as 0.

**Comment by manast** [comment]
Basically there were 2 options, either to be executed before all other priorities or after all other priorities, we choose the first one, I do not think there is objectively speaking better or worse, in any case we are not going to change this now as it will break for many users that rely on the current behaviour.
