### ISSUE TITLE
[Bug]: Unable to Add Jobs to Queue after 8-9 hr in BullMQ

### ISSUE THREAD

**Issue by Rahul-Prasad-07** [taskforcesh/bullmq#2395]
### Version

^5.1.2

### Platform

NodeJS

### What happened?

A bug happened!

After deploying the consumer and producer components, the system seems to be in a stable state, but jobs are not successfully added to the queue after 8-9 hr, preventing further processing.

### How to reproduce.

I am running my consumer and producer in one aws ec2 instnace with PM2.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by selcukfatihsevinc** [comment]
Same here 🙋‍♂️

**Comment by manast** [comment]
This issue does not include enough information to do any further investigation. Normally, if you add a job to a queue, the call either succeeds or fails, if you have proper error management you would see that. If the call succeeded the job should be in the queue as long a Redis is configured correctly.
