### ISSUE TITLE
[Bug]: BullMQ QueueEvents events are received out of order

### ISSUE THREAD

**Issue by shaunakv1** [taskforcesh/bullmq#2433]
### Version

v5.1.11

### Platform

NodeJS

### What happened?

I have a complex series of jobs which uses flow producer. 

I have a global QueueEvents listener which I use to track statues of various jobs. Problem is when I receive various lifecycle events such as `added` `waiting` `complete` etc,   in quick succession ( same time stamp to second)  the event listener is invoked in incorrect ( seemingly random order ). 

For example I can get `complete` first and then `added` or `waiting` afterwards.  I suppose they are received at same time and then processed by the event loop in wrong order?? How do I fix this problem ? 

I end up with jobs that have a `waiting` status in database when they have actually completed in the database.

### How to reproduce.

Not a full reproducible example, but my Queue processort looks like this:

```js
const { QueueEvents, Queue } = require('bullmq');
const connection = require("../../config/app").redis;
const queueConfig = require("../../config/app").queues;
const logger = require("../../config/logger");
const db = require("../../db");

class DQueueEvents {
    constructor(queueName) {
        const queues = Object.keys(queueConfig.options).map(q => queueConfig.options[q])

        queues.forEach(q => {
            const queueName = q.name;
            const queueType = q.type;

            const queue = new Queue(queueName, { connection });
            const listener = new QueueEvents(queueName, { connection });

            const events = [
                'added',
                'waiting',
                'waiting-children',
                'active',
                'completed',
                'stalled',
                'failed',
                'paused',
                'resumed',
                'removed',
                'delayed',
                'retries-exhausted'
                //'drained',
                //'cleaned',
                //'duplicated',
                //'progress',
            ];

            events.forEach(event => {
                listener.on(event, async ({ jobId, failedReason }) => {
                    const job = await queue.getJob(jobId);

                    const eventDetails = {
                        jobID: job.data.jobID,
                        jobType: queueType,
                        jobName: job.name,
                        queueName: queueName,
                        status: event,
                        failedReason: failedReason
                    }

                    const data = await db.jobTracks.upsert(eventDetails);
                    if (data.error) {
                        logger.error(`Cannot write job track to database from queueEvents.js. Event was ${JSON.stringify(eventDetails)}. Error: ${data.message} `, { jobID: job.data.jobID, type: "bullmq" });
                    }

                    logger.info(`${job.name} is now in ${event} status`, { jobID: job.data.jobID, type: "bullmq" });
                    if (failedReason) logger.error(`Job ${job.name} failed with reason: ${failedReason}`, { jobID: job.data.jobID, type: "bullmq" });
                });
            });
        });

    }
}


module.exports = new DQueueEvents();
``` 

Here's the screenshot of logs:

![image](https://github.com/taskforcesh/bullmq/assets/732604/e17b7421-e4d3-4b79-b0e7-1f11825e9740)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shaunakv1** [comment]
Is there a way to get precise timestamps ( when the status actually changed in redis) from the event?  I am thinking if I have that I can "queue" up my events and execute them on the database in the correct order may be?

**Comment by manast** [comment]
The events are sent in order, however this code will never work in practice:
```ts
listener.on(event, async ({ jobId, failedReason }) => {
                    const job = await queue.getJob(jobId);
```

The reason being that since getJob is asynchronous, there is no guarantee that what happens next will happen in the correct order. In fact, even when you write to your own database you will not be able to guarantee order... async is a bitch yes :).
You will need to think on a different approach if you want to store the latest known job status. The events produced by BullMQ actually returns a stream id as last argument, which is an always increasing ID, you may be able to use that for a more robust approach.

We have in the pipe a "job history" feature that will store all the statuses a job has been during its lifetime, that may be useful in your case, but I have not ETA for this feature yet.

**Comment by manast** [comment]
I am closing since there is no issue in BullMQ, but it is just how async works.

**Comment by shaunakv1** [comment]
@manast  So this mostly works, but like you said the event_id is expected to be  an which is an always increasing ID.  That doesn't seem to be always true! 

Check this log (added spaces to numbers to make sense just here for formatting)

```
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in added status event_id :     1712978 68 065 714
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in waiting status event_id :   1712978 68 065 715
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in active status event_id :    1712978 9 087 691 (smaller than last event)
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in completed status event_id : 1712978 9 330 220
```

The first two events are incremental, then when the active event comes in, it's a lot smaller , and then increments. Not sure what happening here, but it doesn't always happen. Only when a queue has a lot of jobs. 

Any advice? I think we should reopen this issue.

**Comment by manast** [comment]
@shaunakv1 as explained before, this is the nature of asynchronous processing, there is nothing we can do to guarantee the order.

**Comment by shaunakv1** [comment]
@manast  may be I confused what you said,  and thanks for your patience, but in you last comment you mentioned this: 

"The events produced by BullMQ actually returns a stream id as last argument, which is an always increasing ID, you may be able to use that for a more robust approach."

In my last comment I am showing the eventIDs generated by BullMQ and they are not always increasing ID like you said.  I understand that the events might actually be received out of order, but shouldn't the IDs be always incrementing? they are not it seems.

**Comment by manast** [comment]
If I have to guess, something in your id parsing is messing with the numbers, I would suspect that: 1712978 9 087 691 could be 1712978 90 087 691 instead. These IDs come from Redis and they are increasing by definition, if they are not then that would imply an issue in Redis which I find extremely unlikely.  Nota that is not BullMQ who generates the ids, they are generated by the stream as we push events in there. Maybe if you log the ids exactly as they are returned by the events we can see what is going on.

**Comment by shaunakv1** [comment]
@manast  Sorry for causing the confusion. The IDs are exactly as they came in.  I just had them formatted to verify the big numbers is all. Here's the numbers again without spaces. 

```
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in added status event_id  (stream id):    171297868065714
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in waiting status event_id (stream id) :   171297868065715
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in active status event_id    (stream id):   17129789087691  (smaller than last event)
21G_sc2017_geotown_dem_J21158tR5_C1:21158 is now in completed status event_id : 17129789330220
```

The last two IDs in sequence are indeed smaller and exactly as they came in from the event handler.  I have verified and reproduced this on multiple instances and am absolutely sure the IDs are not always incrementing.

**Comment by shaunakv1** [comment]
@manast  So on further investigation I seems like , indeed my parsing of the IDs to remove the dashes is what's causing it, but not in the way you suspected. Here's the another run with raw and parsed IDs: 

```
60m_points_sc2017_cst_counties_J22056tR2_C2:22056 is now in added     status. Raw EventId : 1713324990733-14, Event ID: 171332499073314
60m_points_sc2017_cst_counties_J22056tR2_C2:22056 is now in waiting   status. Raw EventId : 1713324990733-15, Event ID: 171332499073315
60m_points_sc2017_cst_counties_J22056tR2_C2:22056 is now in active    status. Raw EventId : 1713325280097-1,  Event ID: 17133252800971
60m_points_sc2017_cst_counties_J22056tR2_C2:22056 is now in completed status. Raw EventId : 1713325464144-0,  Event ID: 17133254641440
```

As you can see now, the Raw Ids are indeed incrementing, but only before the dash. The digits after the dash seems like a new series that's lower than previous. So may be I can't just remove the dash and parse the whole thing as an Int. 

How do you recommend dealing with this? How should I treat those dashes?  Clearly I can't just drop part after the dash, because sometimes the id before the dash is identical ( added and waiting status).  

I was depending on one eventID to decide if this is the next event. Now do I need to track two part IDs?
