### ISSUE TITLE
Jobs only run sometimes

### ISSUE THREAD

**Issue by enahomurphy** [taskforcesh/bullmq#245]
I have been having issues after I deployed my app using bullmq jobs and worker. Everything works fine locally until I deployed to production. when I call `queue.add(name, data, { delay: 7000 } )` the job gets created, the worker only runs that job sometimes. I have listened for the failed event but nothing gets logged 

I use this same library with another service and it works fine. 
Am I doing something wrong or is there a bug I'm not aware of

```
  const scheduler = new QueueScheduler('conversation', { connection: options });
  const queue = new Queue('conversation', { connection: options });

    await queue.add(events.MESSAGE_CREATED, data, {
      jobId: message.id,
      delay: 5000,
      removeOnComplete: true,
      removeOnFail: true,
    });

  const worker = new Worker(
    'conversation',
    async ({ name, data }) => {
      try {
        switch (name) {
          case events.ORGANIZATION_JOINED:
            joinedOrganization(data);
            break;
          default:
            logger.debug('message broadcast triggered');
            await messageCreated(data);
        }
      } catch (error) {
        reportError(error);
      }
    },
    {
      connection: options,
    },
  );

  worker.on('completed', (job): void => {
    logger.log(job.name);
  });

  worker.on('drained', (): void => {
    logger.log('drained');
  });

  worker.on('failed', (jobId: string, error: Error): void => {
    logger.error(error);
  });

```

**Comment by manast** [comment]
If you do not use delay, does it work then?

**Comment by enahomurphy** [comment]
@manast I still have the same issues without delay. the worker runs sometimes and sometimes it doesn't. I can't even see a pattern.
No failed event is emitted on the queue and worker.

**Comment by manast** [comment]
I recommend you that you setup the simplest possible setup and try again, this is most likely an issue in your code. Maybe the processor is never completing for example.

**Comment by enahomurphy** [comment]
This issue was caused by me. I had another instance picking and processing my Job.

**Comment by manast** [comment]
@enahomurphy thank you for updating the issue.
