### ISSUE TITLE
Tree to DAG - more than one parent to a child task.

### ISSUE THREAD

**Issue by vicpara** [taskforcesh/bullmq#2453]
Is it currently possible to have a child task that is part of a flow that feeds its result into more than one parent tasks? 

The way it works today is that there is a relationship of 1:1 between child tasks and parents (one task can only have one parent). 

I have the situation where a flow is computing a results that is computationally expensive. Then I have about 10 tasks that need to use this result as input. 
It seems that if I add the task definition as dependent child to these 10 tasks then the computation gets repeated 10 times.

**Comment by manuganji** [comment]
Have you set the same id for this child task across all those parent tasks?

**Comment by vicpara** [comment]
Yes. I've tried. 

A,B,C,D1,E1 (D1,E1) execute but the flow stops there . The parent jobs (D2,E2, FinalJob) don't get active.

Just a reminder that this is part of a flow.


Here's the scenario:

```
                        /->D1 -> E1 ->\ 
                       /-> D2 -> E2 -> \
A->B->C(wFixed JobID) /---------------- \-> FinalJob

```

**Comment by manast** [comment]
What about having 1 parent, that what it does is just add 10 new jobs with the results of its children? would't that effectively achieve the same result that you are trying to achieve?

**Comment by vicpara** [comment]
Yes. That's what I'm currently working towards.   
I pass the data to the new jobs via job.data attribute. Is there a way to pass data to the 10 new jobs so that it is retrieved via `job.getChildrenValues()` ?

**Comment by manast** [comment]
you can just call ```job.getChildrenValues```, and pass the result as data to every one of your 10 new jobs.

**Comment by vicpara** [comment]
Thanks. I'm happy that I'm on the right track.
I really like BullMQ and the current design. It's beautiful from so many regards. Well done.

The out-of-the-box support for DAG graphs would make it incredibly powerful at expressing complex computation. I tried to add this myself as PR but it's not trivial.

Thanks again.

**Comment by vicpara** [comment]
Do you have some sort of roadmap that shows where you're going with this library ?

**Comment by manuganji** [comment]
https://github.com/zrwusa/data-structure-typed has an implementation of DAG. I find it useful to achieve this.

**Comment by vicpara** [comment]
BullMQ fows currently run using paradigm of a tree of tasks. I meant running tasks in a DAG fashion.
