### ISSUE TITLE
[Bug]: Sandboxed processor job fails to run on ESM module system

### ISSUE THREAD

**Issue by Lysosome** [taskforcesh/bullmq#2457]
### Version

v5.4.1

### Platform

NodeJS

### What happened?

NodeJS v18.17.0
Ubuntu 22.04 on WSL2

Hello! I'm using BullMQ to handle processing of several CPU-intensive jobs to offload that processing from my main application server. We have recently been running into Job Stalling issues due to the NodeJS event loop being too busy to extend the job locks, as described in the BullMQ documentation [here](https://docs.bullmq.io/guide/workers/sandboxed-processors). We wanted to use Sandboxed processors as a fix, but are having issues getting a minimum viable example up and running.

I downloaded the [example repo](https://github.com/taskforcesh/bullmq-typescript/tree/main) from the [sandboxed worker tutorial](https://blog.taskforce.sh/using-typescript-with-bullmq/) and it worked on my machine, but we haven't been able to get sandbox processes to work on our main repo. The main difference is that our main repo is using ESM modules, not CommonJS - unfortunately, we rely on too many ESM features to switch over, so we will need to stick with that. 

I noticed [this issue thread #1698](https://github.com/taskforcesh/bullmq/issues/1698) where this problem was discussed, and it seemed to end in a [resolution fix #2318](https://github.com/taskforcesh/bullmq/pull/2318) where you can define your processing file using ESM and it would still work. Upgrading from our old BullMQ version before this change (4.10.0) to latest (5.4.1) did indeed fix an error we were seeing related to this: `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`.

Unfortunately, now it seems the job is being picked up and immediately erroring out, without even running the very first line of the job processing function. We are seeing a generic error (via bull-board) on the Job with no other logs, and no other outputs (see Relevant log output below). Would appreciate some help in trying to puzzle this one out.

Other things we tried that didn't work:
- BullMQ versions before and after #2318 : 4.10.0 and 5.4.1
- `export async default` and `module.exports = ` in `process_job.ts`
- SandboxedJob vs. Job in `process_job.ts`
- useWorkerThreads on and off

### How to reproduce.

index.ts:
```typescript
import { Worker } from "bullmq";

const calculateStatsWorker = new Worker(
    "calculateStatsQueue",
    // hardcode file path for testing purposes
    `/hardcoded/path/dist/src/workers/process_job.js`,
    {
      connection: redisConnectionConfig,
      concurrency: 1,
    });
```

process_job.ts:
```typescript
import { SandboxedJob } from "bullmq";

export default async function (job: SandboxedJob) {
  await job.log("Start processing job");
  console.log("Doing something useful...", job.id, job.data);
}
```

package.json:
```json
{
  "name": "rivet-backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "license": "Apache-2.0",
  "scripts": {
    "start": "ts-node src/index.ts",
    "build": "tsc ; tsc-alias",
    // other scripts...
  },
  "type": "module",
  // dependencies & devDependencies...
}
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "outDir": "./dist",
    "target": "ES2020",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,

    "module": "ESNext",
    "moduleResolution": "Bundler",
    
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noImplicitAny": true
  },
    "include": [
    "./**/*"
  ],
  "ts-node": {
    /*
    Allows ts-node (used in dev) to use esm modules
    by setting the module resolution to node
    we make sure we don't need to add .js extensions to our imports
    */
    "esm": true,
    "experimentalSpecifierResolution": "node"
  },
  "tsc-alias": {
    /*
    This library automatically adds .js extensions to our imports
    after the typescript compiler has done its job
    */
    "resolveFullPaths": true,
    "verbose": false
  }
}
```
Run `npm run build`. Start up worker with `ts-node index.ts` or some variant thereof, ensure that worker is up and running. Add a job to the calculateStatsQueue. Job will immediately error out without logging anything.

### Relevant log output

```shell
Error
    at Child.msgHandler (/home/lysosome/rivet/monorepo/backend/node_modules/bullmq/src/classes/sandbox.ts:29:25)
    at Child.emit (node:events:514:28)
    at Child.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/home/lysosome/rivet/monorepo/backend/node_modules/bullmq/src/classes/child.ts:110:44)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Lysosome** [comment]
I'm doing further testing today and it is sometimes working, sometimes not working. Root cause may or may not be related to a bug in the bullmq library. Closing issue for now as I try to figure it out.

**Comment by manast** [comment]
I would suggest not using ts-node for production, it is often easier to debug and avoid obscure errors by first compiling and then use node directly on the plain js file.

**Comment by arthurvanl** [comment]
EDIT: Actually this is a horrible example. My bad for this (it runs everything on the same process)


I am not sure if you still have this problem but I had the problem when using bun:
```
146 |             const onMessageHandler = (msg) => {
147 |                 if (msg.cmd === enums_1.ParentCommand.InitCompleted) {
148 |                     resolve();
149 |                 }
150 |                 else if (msg.cmd === enums_1.ParentCommand.InitFailed) {
151 |                     const err = new Error();
                                          ^
error: undefined
      at C:\Users\minty\Desktop\programs\testing-bullmq\node_modules\bullmq\dist\cjs\classes\child.js:151:37
```

I created this solution:

src/job.ts
```ts
import { SandboxedJob } from "bullmq";
import { sleep } from "bun";

const p = async (job: SandboxedJob) => {

    job.updateProgress('Sleeping 3 seconds...')
    await sleep(3000);

    job.updateProgress('slept 3 seconds')
    job.log("Start processing job");
    console.log("Doing something useful...", job.id, job.data);
}

export default p
```

src/index.ts:
```ts
const workerImport = async (fileName: string) => {

    return await import(`./${fileName}`);
}

const job = await workerImport('job.ts');
console.log(job)
const worker = new Worker('foo', job.default, {connection});
worker.on('completed', job => {
  console.log(`${job.id} has completed!`);
});

worker.on('failed', (job, err) => {
  console.log(`${job?.id} has failed with ${err.message}`);
});
```

<img width="815" height="174" alt="Image" src="https://github.com/user-attachments/assets/35301402-7527-4f0a-bab4-36014de561a6" />

Hope it helps
