### ISSUE TITLE
[Python] How to create a worker to consume tasks ?

### ISSUE THREAD

**Issue by Spoutnik97** [taskforcesh/bullmq#2462]
**Is your feature request related to a problem? Please describe.**
I create task on a queue with my NestJS API. I want ton consume them with python workers because my analysis code is in python.

I wrote this code : 

```
def embedding_process(job: Job, job_token: str):
    return asyncio.ensure_future(create_embedding_from_url(job.data))


def process_one(job: Job, job_token: str):
    return asyncio.ensure_future(
        processor_one(job.data)
    )


async def main():
    print(f"Listening for embedding jobs...")
    embedding_worker = Worker(
        "embedding",
        embedding_process,
        {
            "connection": redis_connection,
            "autorun": False,
        },
    )
    worker_one = Worker(
        "one",
        process_one,
        {
            "connection": redis_connection,
        },
    )

    await embedding_worker.run()


if __name__ == "__main__":
    asyncio.run(main())

```

**Describe the solution you'd like**

Is it the right way to do it ? 

**Additional context**

I launch my workers with the following script : 
```
python ./workers.py > py_output.log 2>&1 &
pnpm dev
```

**Comment by manast** [comment]
I am sorry we do not have a lot of documentation for the Python port, but here you can find one example at least: https://docs.bullmq.io/python/introduction
