### ISSUE TITLE
[Bug]: Using dragonfly causes "script tried accessing undeclared key" when adding to queue

### ISSUE THREAD

**Issue by BolverBlitz** [taskforcesh/bullmq#2463]
### Version

v5.4.1

### Platform

NodeJS

### What happened?

I saw the alternative drop in replacemennt dragonfly mentioned in your docs and wanted to try it out.
The code works fine with the redis (also latest image)
I´m using it within docker: docker.dragonflydb.io/dragonflydb/dragonfly:latest
The exact version is: dragonfly v1.15.0-0c1150956b600f21473eae1d0e338194de6b61bc

### How to reproduce.

const { Queue, QueueEvents } = require('bullmq');

const connection = {
    port: parseInt(process.env.Redis_Port) || 6379,
    host: process.env.Redis_Host || "127.0.0.1",
    username: process.env.Redis_User || "default",
    password: process.env.Redis_Password || "default",
    db: parseInt(process.env.Redis_DB) + 1 || 1,
};

const mail_q = new Queue('q:mail', { connection: connection });
const mail_qEvents = new QueueEvents('q:mail', { connection: connection });

const sendMail = async (emailType, emailResiver, waitForCompletion = false) => {
    const jobId = `${emailType}-${Date.now()}:SOMERANDOMSTRING`;
    await mail_q.add(emailType, emailResiver, { jobId });

    if (!waitForCompletion) {
        // If not waiting for completion, resolve immediately
        return Promise.resolve();
    }

    return new Promise((resolve, reject) => {
        const onCompleted = async (jobIdCompleted) => {
            if (jobIdCompleted === jobId) {
                mail_qEvents.off('completed', onCompleted); // Clean up listener
                resolve();
            }
        };

        mail_qEvents.on('completed', onCompleted);

        mail_qEvents.on('failed', (jobIdFailed, failedReason) => {
            if (jobIdFailed === jobId) {
                mail_qEvents.off('completed', onCompleted); // Clean up listener
                reject(new Error(`Email job ${jobId} failed`));
            }
        });
    });
}

(async () => {
    await sendMail('user:email_verification', 'text@example.com');
})();

### Relevant log output

```shell
ReplyError: ERR Error running script (call to 9b67b263800b6f824ebff3728c865ac78083a12b): @user_script:269: script tried accessing undeclared key
    at parseError (C:\Users\1515\Documents\GitHub\EBG-Webpage\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\1515\Documents\GitHub\EBG-Webpage\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'eval',
    args: [
      '--[[\n' +
        '  Adds a job to the queue by doing the following:\n' +
        '    - Increases the job counter if needed.\n' +
        '    - Creates a new job key with the job data.\n' +
        '    - if delayed:\n' +
        '      - computes timestamp.\n' +
        '      - adds to delayed zset.\n' +
        "      - Emits a global event 'delayed' if the job is delayed.\n" +
        '    - if not delayed\n' +
        '      - Adds the jobId to the wait/paused list in one of three ways:\n' +
        '         - LIFO\n' +
        '         - FIFO\n' +
        '         - prioritized.\n' +
        '      - Adds the job to the "added" list so that workers gets notified.\n' +
        '    Input:\n' +
        "      KEYS[1] 'wait',\n" +
        "      KEYS[2] 'paused'\n" +
        "      KEYS[3] 'meta'\n" +
        "      KEYS[4] 'id'\n" +
        "      KEYS[5] 'completed'\n" +
        '      KEYS[6] events stream key\n' +
        '      KEYS[7] marker key\n' +
        '      ARGV[1] msgpacked arguments array\n' +
        '            [1]  key prefix,\n' +
        '            [2]  custom id (will not generate one automatically)\n' +
        '            [3]  name\n' +
        '            [4]  timestamp\n' +
        '            [5]  parentKey?\n' +
        '            [6]  waitChildrenKey key.\n' +
        '            [7]  parent dependencies key.\n' +
        '            [8]  parent? {id, queueKey}\n' +
        '            [9]  repeat job key\n' +
        '      ARGV[2] Json stringified job data\n' +
        '      ARGV[3] msgpacked options\n' +
        '      Output:\n' +
        '        jobId  - OK\n' +
        '        -5     - Missing parent key\n' +
        ']]\n' +
        'local eventsKey = KEYS[6]\n' +
        'local jobId\n' +
        'local jobIdKey\n' +
        'local rcall = redis.call\n' +
        'local args = cmsgpack.unpack(ARGV[1])\n' +
        'local data = ARGV[2]\n' +
        'local opts = cmsgpack.unpack(ARGV[3])\n' +
        'local parentKey = args[5]\n' +
        'local repeatJobKey = args[9]\n' +
        'local parent = args[8]\n' +
        'local parentData\n' +
        '-- Includes\n' +
        '--[[\n' +
        '  Function to add job in target list and add marker if needed.\n' +
        ']]\n' +
        '-- Includes\n' +
        '--[[\n' +
        '  Add marker if needed when a job is available.\n' +
        ']]\n' +
        'local function addBaseMarkerIfNeeded(markerKey, isPaused)\n' +
        '  if not isPaused then\n' +
        '    rcall("ZADD", markerKey, 0, "0")\n' +
        '  end  \n' +
        'end\n' +
        'local function addJobInTargetList(targetKey, markerKey, pushCmd, isPaused, jobId)\n' +
        '  rcall(pushCmd, targetKey, jobId)\n' +
        '  addBaseMarkerIfNeeded(markerKey, isPaused)\n' +
        'end\n' +
        '--[[\n' +
        '  Function to get max events value or set by default 10000.\n' +
        ']]\n' +
        'local function getOrSetMaxEvents(metaKey)\n' +
        '    local maxEvents = rcall("HGET", metaKey, "opts.maxLenEvents")\n' +
        '    if not maxEvents then\n' +
        '        maxEvents = 10000\n' +
        '        rcall("HSET", metaKey, "opts.maxLenEvents", maxEvents)\n' +
        '    end\n' +
        '    return maxEvents\n' +
        'end\n' +
        '--[[\n' +
        '  Function to check for the meta.paused key to decide if we are paused or not\n' +
        '  (since an empty list and !EXISTS are not really the same).\n' +
        ']]\n' +
        'local function getTargetQueueList(queueMetaKey, waitKey, pausedKey)\n' +
        '  if rcall("HEXISTS", queueMetaKey, "paused") ~= 1 then\n' +
        '    return waitKey, false\n' +
        '  else\n' +
        '    return pausedKey, true\n' +
        '  end\n' +
        'end\n' +
        '--[[\n' +
        '  Function to handle the case when job is duplicated.\n' +
        ']]\n' +
        '-- Includes\n' +
        '--[[\n' +
        "    This function is used to update the parent's dependencies if the job\n" +
        '    is already completed and about to be ignored. The parent must get its\n' +
        '    dependencies updated to avoid the parent job being stuck forever in \n' +
        '    the waiting-children state.\n' +
        ']]\n' +
        '-- Includes\n' +
        '--[[\n' +
        '  Validate and move or add dependencies to parent.\n' +
        ']]\n' +
        '-- Includes\n' +
        '--[[\n' +
        '  Validate and move parent to active if needed.\n' +
        ']]\n' +
        '-- Includes\n' +
        '--[[\n' +
        '  Add delay marker if needed.\n' +
        ']]\n' +
        '-- Includes\n' +
        '--[[\n' +
        '  Function to return the next delayed job timestamp.\n' +
        ']]\n' +
        'local function getNextDelayedTimestamp(delayedKey)\n' +
        '  local result = rcall("ZRANGE", delayedKey, 0, 0, "WITHSCORES")\n' +
        '  if #result then\n' +
        '    local nextTimestamp = tonumber(result[2])\n' +
        '    if (nextTimestamp ~= nil) then \n' +
        '      nextTimestamp = nextTimestamp / 0x1000\n' +
        '    end\n' +
        '    return nextTimestamp\n' +
        '  end\n' +
        'end\n' +
        'local function addDelayMarkerIfNeeded(markerKey, delayedKey)\n' +
        '    local nextTimestamp = getNextDelayedTimestamp(delayedKey)\n' +
        '    if nextTimestamp ~= nil then\n' +
        '        -- Replace the score of the marker with the newest known\n' +
        '        -- next timestamp.\n' +
        '        rcall("ZADD", markerKey, nextTimestamp, "1")\n' +
        '    end\n' +
        'end\n' +
        '--[[\n' +
        '  Function to add job considering priority.\n' +
        ']]\n' +
        '-- Includes\n' +
        'local function addJobWithPriority(markerKey, prioritizedKey, priority, jobId, priorityCounterKey, isPaused)\n' +
        '  local prioCounter = rcall("INCR", priorityCounterKey)\n' +
        '  local score = priority * 0x100000000 + bit.band(prioCounter, 0xffffffffffff)\n' +
        '  rcall("ZADD", prioritizedKey, score, jobId)\n' +
        '  addBaseMarkerIfNeeded(markerKey, isPaused)\n' +
        'end\n' +
        '--[[\n' +
        '  Function to check for the meta.paused key to decide if we are paused or not\n' +
        '  (since an empty list and !EXISTS are not really the same).\n' +
        ']]\n' +
        'local function isQueuePaused(queueMetaKey)\n' +
        '    return rcall("HEXISTS", queueMetaKey, "paused") == 1\n' +
        'end\n' +
        'local function moveParentToWaitIfNeeded(parentQueueKey, parentDependenciesKey,\n' +
        '                                        parentKey, parentId, timestamp)\n' +
        '    local isParentActive = rcall("ZSCORE",\n' +
        '                                 parentQueueKey .. ":waiting-children", parentId)\n' +
        '    if rcall("SCARD", parentDependenciesKey) == 0 and isParentActive then\n' +
        '        rcall("ZREM", parentQueueKey .. ":waiting-children", parentId)\n' +
        '        local parentWaitKey = parentQueueKey .. ":wait"\n' +
        '        local parentPausedKey = parentQueueKey .. ":paused"\n' +
        '        local parentMetaKey = parentQueueKey .. ":meta"\n' +
        '        local parentMarkerKey = parentQueueKey .. ":marker"\n' +
        '        local jobAttributes = rcall("HMGET", parentKey, "priority", "delay")\n' +
        '        local priority = tonumber(jobAttributes[1]) or 0\n' +
        '        local delay = tonumber(jobAttributes[2]) or 0\n' +
        '        if delay > 0 then\n' +
        '            local delayedTimestamp = tonumber(timestamp) + delay\n' +
        '            local score = delayedTimestamp * 0x1000\n' +
        '            local parentDelayedKey = parentQueueKey .. ":delayed"\n' +
        '            rcall("ZADD", parentDelayedKey, score, parentId)\n' +
        '            rcall("XADD", parentQueueKey .. ":events", "*", "event", "delayed",\n' +
        '                  "jobId", parentId, "delay", delayedTimestamp)\n' +
        '            addDelayMarkerIfNeeded(parentMarkerKey, parentDelayedKey)\n' +
        '        else\n' +
        '            if priority == 0 then\n' +
        '                local parentTarget, isParentPaused =\n' +
        '                    getTargetQueueList(parentMetaKey, parentWaitKey,\n' +
        '                                       parentPausedKey)\n' +
        '                addJobInTargetList(parentTarget, parentMarkerKey, "RPUSH", isParentPaused, parentId)\n' +
        '            else\n' +
        '                local isPaused = isQueuePaused(parentMetaKey)\n' +
        '                addJobWithPriority(parentMarkerKey,\n' +
        '                                   parentQueueKey .. ":prioritized", priority,\n' +
        '                                   parentId, parentQueueKey .. ":pc", isPaused)\n' +
        '            end\n' +
        '            rcall("XADD", parentQueueKey .. ":events", "*", "event", "waiting",\n' +
        '                  "jobId", parentId, "prev", "waiting-children")\n' +
        '        end\n' +
        '    end\n' +
        'end\n' +
        'local function updateParentDepsIfNeeded(parentKey, parentQueueKey, parentDependenciesKey,\n' +
        '  parentId, jobIdKey, returnvalue, timestamp )\n' +
        '  local processedSet = parentKey .. ":processed"\n' +
        '  rcall("HSET", processedSet, jobIdKey, returnvalue)\n' +
        '  moveParentToWaitIfNeeded(parentQueueKey, parentDependenciesKey, parentKey, parentId, timestamp)\n' +
        'end\n' +
        'local function updateExistingJobsParent(parentKey, parent, parentData,\n' +
        '                                        parentDependenciesKey, completedKey,\n' +
        '                                        jobIdKey, jobId, timestamp)\n' +
        '    if parentKey ~= nil then\n' +
        '        if rcall("ZSCORE", completedKey, jobId) ~= false then\n' +
        '            local returnvalue = rcall("HGET", jobIdKey, "returnvalue")\n' +
        "            updateParentDepsIfNeeded(parentKey, parent['queueKey'],\n" +
        "                                     parentDependenciesKey, parent['id'],\n" +
        '                                     jobIdKey, returnvalue, timestamp)\n' +
        '        else\n' +
        '            if parentDependenciesKey ~= nil then\n' +
        '                rcall("SADD", parentDependenciesKey, jobIdKey)\n' +
        '            end\n' +
        '        end\n' +
        '        rcall("HMSET", jobIdKey, "parentKey", parentKey, "parent", parentData)\n' +
        '    end\n' +
        'end\n' +
        'local function handleDuplicatedJob(jobKey, jobId, currentParentKey, currentParent,\n' +
        '  parentData, parentDependenciesKey, completedKey, eventsKey, maxEvents, timestamp)\n' +
        '  local existedParentKey = rcall("HGET", jobKey, "parentKey")\n' +
        '  if not existedParentKey then\n' +
        '    updateExistingJobsParent(currentParentKey, currentParent, parentData,\n' +
        '      parentDependenciesKey, completedKey, jobKey,\n' +
        '      jobId, timestamp)\n' +
        '  else\n' +
        '    if currentParentKey ~= nil and currentParentKey ~= existedParentKey\n' +
        '      and (rcall("EXISTS", existedParentKey) == 1) then\n' +
        '      return -7\n' +
        '    end\n' +
        '  end\n' +
        '  rcall("XADD", eventsKey, "MAXLEN", "~", maxEvents, "*", "event",\n' +
        '    "duplicated", "jobId", jobId)\n' +
        '  return jobId .. "" -- convert to string\n' +
        'end\n' +
        '--[[\n' +
        '  Function to store a job\n' +
        ']]\n' +
        'local function storeJob(eventsKey, jobIdKey, jobId, name, data, opts, timestamp,\n' +
        '                        parentKey, parentData, repeatJobKey)\n' +
        '    local jsonOpts = cjson.encode(opts)\n' +
        "    local delay = opts['delay'] or 0\n" +
        "    local priority = opts['priority'] or 0\n" +
        '    local optionalValues = {}\n' +
        '    if parentKey ~= nil then\n' +
        '        table.insert(optionalValues, "parentKey")\n' +
        '        table.insert(optionalValues, parentKey)\n' +
        '        table.insert(optionalValues, "parent")\n' +
        '        table.insert(optionalValues, parentData)\n' +
        '    end\n' +
        '    if repeatJobKey ~= nil then\n' +
        '        table.insert(optionalValues, "rjk")\n' +
        '        table.insert(optionalValues, repeatJobKey)\n' +
        '    end\n' +
        '    rcall("HMSET", jobIdKey, "name", name, "data", data, "opts", jsonOpts,\n' +
        '          "timestamp", timestamp, "delay", delay, "priority", priority,\n' +
        '          unpack(optionalValues))\n' +
        '    rcall("XADD", eventsKey, "*", "event", "added", "jobId", jobId, "name", name)\n' +
        '    return delay, priority\n' +
        'end\n' +
        'if parentKey ~= nil then\n' +
        '    if rcall("EXISTS", parentKey) ~= 1 then return -5 end\n' +
        '    parentData = cjson.encode(parent)\n' +
        'end\n' +
        'local jobCounter = rcall("INCR", KEYS[4])\n' +
        'local metaKey = KEYS[3]\n' +
        'local maxEvents = getOrSetMaxEvents(metaKey)\n' +
        'local parentDependenciesKey = args[7]\n' +
        'local timestamp = args[4]\n' +
        'if args[2] == "" then\n' +
        '    jobId = jobCounter\n' +
        '    jobIdKey = args[1] .. jobId\n' +
        'else\n' +
        '    jobId = args[2]\n' +
        '    jobIdKey = args[1] .. jobId\n' +
        '    if rcall("EXISTS", jobIdKey) == 1 then\n' +
        '        return handleDuplicatedJob(jobIdKey, jobId, parentKey, parent,\n' +
        '       '... 780 more characters,
      '7',
      'bull:q:mail:wait',
      'bull:q:mail:paused',
      'bull:q:mail:meta',
      'bull:q:mail:id',
      'bull:q:mail:completed',
      'bull:q:mail:events',
      'bull:q:mail:marker',
      <Buffer 99 ac 62 75 6c 6c 3a 71 3a 6d 61 69 6c 3a d9 2c 75 73 65 72 3a 65 6d 61 69 6c 5f 76 65 72 69 66 69 63 61 74 69 6f 6e 2d 31 37 30 39 36 37 36 30 34 35 ... 48 more bytes>,
      '{"userId":20,"urlPath":"QaFog7F69206XgdVLd6c9QRf7L08lgQVma9OkYJxB0QtIMf6hw0T8NVKB4PQpx8kd46PZyTRMptMcS1SIO7Kc2UoswRUmD4JDdq7XE1ku2bgEghBOqnZmMMEEgXDY02FvajkqWZyzzBLPy9UcB87qxEEi1dzSRpEayq52WE9VSsgyauQ9gBGcACzwtpaCX2MwUDirVu4eOd7eQw1wHkcKtmmv5Rj0Rk0DpIqH9lawVwd1rfRr94RxEv4ruUbm2Ql","appDomain":"https://localhost"}',
      <Buffer de 00 04 a8 61 74 74 65 6d 70 74 73 00 a5 64 65 6c 61 79 00 a5 6a 6f 62 49 64 d9 2c 75 73 65 72 3a 65 6d 61 69 6c 5f 76 65 72 69 66 69 63 61 74 69 6f ... 31 more bytes>
    ]
  }
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @BolverBlitz could you pls also take a look in this [guide](https://www.dragonflydb.io/docs/integrations/bullmq) as there is also this flag:
`./dragonfly --default_lua_flags=allow-undeclared-keys`

**Comment by BolverBlitz** [comment]
Thanks for pointing out my oversight. I´ve added this parameter to my docker-compose to solve this issue.

```yml
version: '3.8'

services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    command: ["/usr/local/bin/dragonfly", "--default_lua_flags=allow-undeclared-keys"]
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
    environment:
      DRAGONFLY_USERNAME: "default"
      DRAGONFLY_PASSWORD: "example"
      
volumes:
  dragonflydata:
```

**Comment by manast** [comment]
You probably are more interested in using hashtag locking, as this will allow you to get much better performance than using "allow-undeclared-keys": https://www.dragonflydb.io/docs/integrations/bullmq

**Comment by andraz** [comment]
I concur, this is the best combination, you just need to wrap your queue string name in extra { } chars:

```js
const queueName = '{' + 'myName' + '}'
```

Using queue with this config will then work @ max performance:

file `docker-compose.yml`

```yaml
services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    command:
      [
        '/usr/local/bin/dragonfly',
        '--cluster_mode=emulated',
        '--lock_on_hashtags',
      ]
    ulimits:
      memlock: -1
    ports:
      - '6379:6379'
    volumes:
      - dragonflydata:/data
    environment:
      DRAGONFLY_USERNAME: 'default'
      DRAGONFLY_PASSWORD: 'example'

volumes:
  dragonflydata:
```

**Comment by BolverBlitz** [comment]
Thanks for your reply @andraz may i ask you for the technical reason i need the { } chars and why this will make it faster?

**Comment by andraz** [comment]
It is a feature that gets activated when key name contains those characters. Prevents the execution from jumping around all over the cluster, locking it on to the same node, increasing performance.

> Hashtags are a Redis Cluster feature. They involve wrapping a part of a key in curly braces `{}`, which ensures that all keys with the same hashtag are located on the same cluster node. For example, keys `{user1}:name` and `{user1}:email` are guaranteed to reside on the same node, allowing them to be efficiently used together in commands or scripts.
>
> Recognizing that BullMQ already utilizes hashtags for Redis Cluster operations, we adopted this concept for Dragonfly as well. We introduced a new server flag `(--lock_on_hashtags)` where Dragonfly locks based on the hashtag rather than the entire key. This approach allows us to maintain the atomicity and isolation of script executions while avoiding the performance penalties associated with global locks or the complexities of the rollback mechanism.

This blog article explains the details: https://www.dragonflydb.io/blog/running-bullmq-with-dragonfly-part-2-optimization

---

long story short is: **Dragonfly performs ~10x slower than Redis if you are using it with the `allow-undeclared-keys` flag.** So there is no point in using it that way.

I reverted my Dragonfly use back to Redis because of this, as I simply could not get it to work correctly in the new way. Performance benefit is only 120% compared to regular Redis cluster, so there is also the question is it really worth the hassle?

Writes do go in the database, you can see the keys in it, but my workers seem to never get the jobs and execute them.

When I switched server back to Redis, everything works fine. Using `{}` in queue names, also seems to break some of the features in Bull Dashboard (% progress), so monitoring became a lot harder.

**Comment by manast** [comment]
@andraz do you have some numbers comparing Redis Cluster vs Dragonfly? In theory it should be much faster if anything because the latency should be very small in Dragonfly vs Redis Cluster. Regarding workers that do not get the jobs, that's unknown to me, we run all the test suite with the latest Dragonfly and is passing every test, so this is quite strange, maybe there is some other thing affecting the outcome here.

**Comment by andraz** [comment]
Numbers are at the end of the article on link above.

![image](https://github.com/user-attachments/assets/15952c65-933f-4b10-9a3e-d659863a8d80)

It makes sense when it works perfectly, else it runs with global locks at reduced performance. I guess it depends on your env.

**Comment by BolverBlitz** [comment]
I´ve also had the issue with workers suddenly not getting any work but i have not had the time to investigate deeper into the issue. I´ve used sentry to hopefully get more insights but it accours randomly after a couple of days, sometimes hours.
However in my case it appears that dragonfly completly deadlocks itself for some reason because i can´t connect with redisinsight to investigate either. The container needs a full reboot and then i have to delete all keys for it to work again.

For this reason and the extreme cpu usage that dragonfly (CPU: 8-23%) causes i´ve also swiched to redis (CPU: 0-5%) until i find some time to look into the issue. 

I do not expect anyone else to look into my project, 
<details>
I´ll just drop the queue insertion and worker here in case someone is curious.
Might just be a issue on my site since its my first project with BullMQ, before i used RabbitMQ but i thought its a nice thing to reduce external dependencies aka 1 less docker container
[Add Job](https://github.com/Public-Transport-Nuremberg/VAGStatsTracker/blob/e8aafa6a811e6dec2e43fc46dfed589d426bbec7/FahrtenScanner/src/index.js#L56)
[Worker](https://github.com/Public-Transport-Nuremberg/VAGStatsTracker/blob/e8aafa6a811e6dec2e43fc46dfed589d426bbec7/FahrtenProcessor/src/index.js#L21)
And yes, i´m aware that the code leaks keys in db0 but the crashes all happen below 20K total keys and not even 100MB memory usage.
</details>

**Comment by manast** [comment]
> Numbers are at the end of the article on link above.
> 
> ![image](https://private-user-images.githubusercontent.com/8480981/356624084-15952c65-933f-4b10-9a3e-d659863a8d80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTM3NDksIm5iZiI6MTcyMzIxMzQ0OSwicGF0aCI6Ii84NDgwOTgxLzM1NjYyNDA4NC0xNTk1MmM2NS05MzNmLTRiMTAtOWEzZS1kNjU5ODYzYThkODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMTQyNDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU0ODhiNDFiYjE5ZTkxYmJhZDZjYzE3OWRhOTBiZmJlZmVmMGMyNGFlYWEzMmFhNTYxMmRhNGJlNDgxMmJjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UTo2iaSMgluPeBIg_SAM2jo-BBp2fKmjDBSxFoAB6W0)
> 
> It makes sense when it works perfectly, else it runs with global locks at reduced performance. I guess it depends on your env.

Ok, it is worth noting that the Redis Cluster setup is much more difficult (and expensive) to run than the fastest DragonflyDB, so that's also worth considering when comparing.

**Comment by manast** [comment]
> I´ve also had the issue with workers suddenly not getting any work but i have not had the time to investigate deeper into the issue. I´ve used sentry to hopefully get more insights but it accours randomly after a couple of days, sometimes hours. However in my case it appears that dragonfly completly deadlocks itself for some reason because i can´t connect with redisinsight to investigate either. The container needs a full reboot and then i have to delete all keys for it to work again.
> 
> For this reason and the extreme cpu usage that dragonfly (CPU: 8-23%) causes i´ve also swiched to redis (CPU: 0-5%) until i find some time to look into the issue.
> 
> I do not expect anyone else to look into my project,
> 
> I´ll just drop the queue insertion and worker here in case someone is curious. Might just be a issue on my site since its my first project with BullMQ, before i used RabbitMQ but i thought its a nice thing to reduce external dependencies aka 1 less docker container [Add Job](https://github.com/Public-Transport-Nuremberg/VAGStatsTracker/blob/e8aafa6a811e6dec2e43fc46dfed589d426bbec7/FahrtenScanner/src/index.js#L56) [Worker](https://github.com/Public-Transport-Nuremberg/VAGStatsTracker/blob/e8aafa6a811e6dec2e43fc46dfed589d426bbec7/FahrtenProcessor/src/index.js#L21) And yes, i´m aware that the code leaks keys in db0 but the crashes all happen below 20K total keys and not even 100MB memory usage.

I think that the Dragonfly team would be very interested to know more about this case if you happen to have time to provide some way to reproduce it, they are usually super responsible, especially with issues as severe as this one.
