### ISSUE TITLE
[Bug]: Stalled jobs dont fail their parents

### ISSUE THREAD

**Issue by otanriverdi** [taskforcesh/bullmq#2464]
### Version

5.1.1

### Platform

NodeJS

### What happened?

I have a job with a parent and the job is configured with `failParentOnFailure` set to true. This works as expected if the job errors in anyway. But if the jobs stalls more then the allowable limits and ends up in the `job stalled more then allowable limit` state, the parent does not get failed and the flow esentially gets stuck.

### How to reproduce.

- Have a job with a dependency
- Set the `stalledCount` to 1
- Manually kill the dependency job twice to simulate stall

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hey, I'll take a look this week

**Comment by juanjalil** [comment]
Having the same issue when using `ignoreDependencyOnFailure`. Any resolution on this one? Thanks!

**Comment by juanjalil** [comment]
@roggervalf tried the fix, but it looks not to be working with `ignoreDependencyOnFailure`. Child jobs are failed but parent doesn't.

**Comment by roggervalf** [comment]
hi @juanjalil would you pls open a new issue regarding `ignoreDependencyOnFailure`. I can work on that in a separate pr
