### ISSUE TITLE
Wait Unique Job to finished if queue attempt to process duplicate job

### ISSUE THREAD

**Issue by mlazuardy** [taskforcesh/bullmq#2468]
First of all sorry for my bad english.

My question is, is there anyway if we defined unique job but instead stop processing the queue because of duplicate job, it wait until the First in queue finished processing and continue to the next incoming same job id?

**Comment by manast** [comment]
No, it is not possible. But if you need step-jobs you can use flows: https://docs.bullmq.io/guide/flows
In your case basically the next job would be the parent of the first job.
