### ISSUE TITLE
[Python] Add a log method

### ISSUE THREAD

**Issue by Spoutnik97** [taskforcesh/bullmq#2472]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to log a message with the Python API

**Describe the solution you'd like**
Same as the JS API

**Describe alternatives you've considered**
-

**Additional context**
 Useful to debug or track information like time to compute each task

**Comment by roggervalf** [comment]
hi @Spoutnik97 logs methods should be available in version 2.7.0

**Comment by Spoutnik97** [comment]
Great! Thanks!
I already tested it, and every things works fine
