### ISSUE TITLE
Worker reauthentication using AWS IAM

### ISSUE THREAD

**Issue by rahulrkr08** [taskforcesh/bullmq#2485]
**Is your feature request related to a problem? Please describe.**
We are using AWS Elasticache for Redis, which is authenticated using IAM signed password. The issue is that the worker duplicates the Redis connection, and we cannot reset the regenerated password. Below is the sample code snippet we tried, is there any way to reset the password with "blockingConnection" ?

```js
cosnt password = generateIAMSingedPassword();

const redisClient = new Redis({
  host,
  port,
  username,
  passowrd,
});

redisClient.on('reconnecting', () => {
  // regenerate password on reconnection
  redisClient.options.passowrd = generateIAMSingedPassword() 
});

const worker = new Worker({}, () => {}, {connection: redisClient});
```

**Describe the solution you'd like**
- The solution is to emit the Redis event "reconnecting" with the worker object along with "blockingConnection"

```js
worker.on('reconnecting', (client) => {
    client.options.passowrd = generateIAMSingedPassword() 
})
```

**Comment by manast** [comment]
@rahulrkr08 I did not know about this mechanism. Is this something that ioredis recommends to do or it just happens to work?

**Comment by manast** [comment]
Have you tried with https://github.com/redis/ioredis?tab=readme-ov-file#auto-reconnect and/or https://github.com/redis/ioredis?tab=readme-ov-file#reconnect-on-error ? I suppose these callbacks are duplicated as well when duplicating a connection and thus it should work with the workers as well.

**Comment by rahulrkr08** [comment]
Hey @manast , Thank you for your feedback. The approach I'm discussing is not explicitly recommended by ioredis, but rather a workaround for a specific scenario we're encountering.

We're using AWS ElastiCache (Redis) with authentication based on a signed password. This signed password is generated using an IAM Role and expires every hour as per our cloud configuration.

The code below demonstrates how we create a Redis client and handle password regeneration upon reconnection. This approach works well for managing content cache with Elasticache (Redis). 

```js
cosnt password = generateIAMSingedPassword();

const redisClient = new Redis({
  host,
  port,
  username,
  passowrd,
});

redisClient.on('reconnecting', () => {
  // regenerate password on reconnection
  redisClient.options.passowrd = generateIAMSingedPassword() 
});
```
However, we encounter an issue when passing the same Redis client to create a BullMQ worker. Despite the password regeneration logic, the worker class throws a connection error once the signed password expires. This is because each worker class duplicates the Redis client and stores it in a private "blockingConnection" variable, which prevents external access to the client for password replacement.

```js
const worker = new Worker('queueName', () => {}, {connection: redisClient});
```

The challenge we're facing is finding a way to reinitialize the Redis client with the new password once it expires, as we cannot access the client instance from outside the worker class. Is there a recommended approach or workaround to handle password regeneration for the Redis client within the context of BullMQ workers?

This reconnection error issue is not present when initializing the queue. It seems for Queue, it's using the same Redis client instance, whatever we passed.

```js
const queue = new Queue('queueName', {connection: redisClient});
```

**Comment by manast** [comment]
I understand the issue perfectly, but did you try my suggestion?
https://github.com/taskforcesh/bullmq/issues/2485#issuecomment-2016445998

**Comment by rahulrkr08** [comment]
Hey @manast, I tried those, but using `reconnectOnError` and `retryStrategy` callbacks, I could not replace the password for the current connection instance, as shown below. Because the Redis client instance is not available for those callbacks. 
```js
const redisClient = new Redis({
  // This is the default value of `retryStrategy`
  retryStrategy(times) {
    const delay = Math.min(times * 50, 2000);
    redisClient.options.passowrd = generateIAMSingedPassword()
    return delay;
  },
});
```
Is it possible to stop/destroy worker on `reconnect`? and create new worker using new password?

**Comment by manast** [comment]
I think you should be able to access the current redis instance within the callback with "this":
```ts
const redisClient = new Redis({
  // This is the default value of `retryStrategy`
  retryStrategy: function(times) {
    const delay = Math.min(times * 50, 2000);
    this.options.password = generateIAMSingedPassword()
    return delay;
  },
});
```
Note that you misspelled "password" in your code above...

**Comment by rahulrkr08** [comment]
Hey @manast , Sorry for the typo. Yes, I just tried, 

```js
const redisClient = new Redis({
  port: 6379, // Redis port
  host: process.env.REDIS_ELASTIC_CACHE_ENDPOINT, // Redis host
  maxRetriesPerRequest: null,
  password: '123456', // <- Wrong password
  retryStrategy: (times: number) => {
    // const self = this;
    (this as any).options.password = '12345'; // <- Correct password
  },
});
```

Error:

```js
/Users/rradhakr/Documents/workspace/app/src/services/redis-client.service.ts:77
          (this as any).options.password = '12345'; // <- Correct password
                                        ^
TypeError: Cannot set properties of undefined (setting 'password')
    at Object.retryStrategy (/Users/rradhakr/Documents/workspace/app/src/services/redis-client.service.ts:77:41)
    at Socket.<anonymous> (/Users/rradhakr/Documents/workspace/app/node_modules/ioredis/built/redis/event_handler.js:162:41)
```

**Steps:**
- Start Redis in the local system
- Set the password as "12345"
- Initialize the Redis with the wrong password, i.e, "123456" (in the above code)
- On `retryStrategy` to reset the password with "12345"

**Comment by manast** [comment]
It seems like the "this" pointer is actually pointing to "options" as I can see in ioredis source code:
https://github.com/redis/ioredis/blob/ec42c82ceab1957db00c5175dfe37348f1856a93/lib/redis/event_handler.ts#L187

Furthermore, you cannot use the arrow otherwise you will loose the correct binding for this, if you see my example above you will see I used "function". In order to correct the code write it like this:
```ts
const redisClient = new Redis({
  port: 6379, // Redis port
  host: process.env.REDIS_ELASTIC_CACHE_ENDPOINT, // Redis host
  maxRetriesPerRequest: null,
  password: '123456', // <- Wrong password
  retryStrategy: function(times: number) {
    this.password = '12345'; // <- Correct password
  },
});
```
