### ISSUE TITLE
[Bug]: Stacktrace with limit removes the last error stack.

### ISSUE THREAD

**Issue by nocodehummel** [taskforcesh/bullmq#2487]
### Version

5.4.5

### Platform

NodeJS

### What happened?

Our jobs have `stackTraceLimit` set, and we noticed that the error stack is not updated. 

### How to reproduce.

The problem is caused by an incorrect use of slice inside the Job class.

```
this.stacktrace.push(err.stack);
if (this.opts.stackTraceLimit) {
   this.stacktrace = this.stacktrace.slice(0, this.opts.stackTraceLimit);
}
```

Simple reproduction [example](https://codepen.io/nocodehummel/pen/KKYmoYw) to demonstrate the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
yeah, I see, this actually a real bug as we are pushing the new stacks and then slicing them away if the length is larger stackTraceLimit.

**Comment by roggervalf** [comment]
closing as there is a merged fix in v5.4.6

**Comment by xNest** [comment]
hey, the solution does not allow stackTraceLimit to be set to 0, is this the desired behaviour?

**Comment by nocodehummel** [comment]
@xNest how do you mean does not allow?

**Comment by xNest** [comment]
If you pass 0 with the intention of not saving a stack trace, the limit will be ignored. 

`
if (err?.stack) {
      this.stacktrace.push(err.stack);
      if (this.opts.stackTraceLimit) {
        this.stacktrace = this.stacktrace.slice(-this.opts.stackTraceLimit);
      }
    }
`
