### ISSUE TITLE
Full list of events?

### ISSUE THREAD

**Issue by main-kun** [taskforcesh/bullmq#252]
Readme in gitbook points to the guide and api reference, but neither have a comprehensive list of listenable events. In the code i found this list for queues: 
```
"active"
"wait"
"waiting"
"paused,
"resumed"
"id"
"delayed",
"priority"
"stalled-check"
"completed"
"failed"
"stalled"
"repeat"
"limiter"
"drained"
"progress"
"meta"
"events"
"delay"
```
And in workers i see those events emitted:
```
"paused"
"resumed"
"closing"
"closed"
"drained"
"failed"
"completed"
```

Is this a full list? I'd love to do a PR that would add this to the api reference. But i'm not sure when some of the new events are fired:
- wait vs waiting, delayed vs delay
- delayed, priority, repeat when corresponding job types are added?
- limiter
- meta
- events

**Comment by roggervalf** [comment]
@main-kun also you could find docs about those events in:
https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.workerlistener.md
https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.queueschedulerlistener.md
https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.queueeventslistener.md

**Comment by roggervalf** [comment]
and for queue in last version we have https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.queuelistener.md. Sorry for the delay
