### ISSUE TITLE
[Bug]: Documentation - incorrect parameters for queue 'cleaned' and 'waiting' events 

### ISSUE THREAD

**Issue by oanguenot** [taskforcesh/bullmq#2525]
### Version

v5.7.1

### Platform

NodeJS

### What happened?

Documentation is incorrect for the 2 following events:

- `cleaned`: This event returns an array and not an `Object` with a parameter `count`
- `waiting`: This event contains the `Job` that enters the waiting state and not the `jobId`

### How to reproduce.

Listen to these events

queue.on("cleaned", (jobs) => {
    console.log(jobs);
});

queue.on("waiting", (job) => {
   console.log(job);
});

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @oanguenot, I assuming you are confusing QueueListener with QueueEventsListener
https://api.docs.bullmq.io/interfaces/v5.QueueListener.html#cleaned
https://api.docs.bullmq.io/interfaces/v5.QueueListener.html#waiting
https://api.docs.bullmq.io/interfaces/v5.QueueEventsListener.html#cleaned
https://api.docs.bullmq.io/interfaces/v5.QueueEventsListener.html#waiting
QueueListener is for Queue class

**Comment by oanguenot** [comment]
You're right. Thanks for your feedback. I will close this issue
