### ISSUE TITLE
What is the proper setup?

### ISSUE THREAD

**Issue by gajus** [taskforcesh/bullmq#253]
Reading the documentation, it is not clear what is the recommended way to setup queues for real world scenarios, i.e. Do I use one queue for the entire application and then route the tasks based on their names?

```js
const queue = new Queue('main-queue');

await queue.add('email:send-parse');
await queue.add('email:send-email');

```

or am I supposed to use one task per domain, e.g.

```js
const queue = new Queue('email-queue');

await queue.add('send-parse');
await queue.add('send-email');

```

or one queue/worker per task?

```js
await (new Queue('email-queue')).add('email-queue:send-parse');
await (new Queue('email-queue')).add('email-queue:send-email');

```

If it is the latter (as some comments seem to imply), then what is the purpose of the task name?

Some brief explanation of the subject would be tremendously helpful.

**Comment by manast** [comment]
The name has no functional meaning, but it can be useful to classify your processors or by frontends in order to filter, etc.
One queue for many purposes or one queue per purpose depends mostly on your application requirements, there is no right or wrong from BullMQ perspective.

**Comment by gajus** [comment]
Broadly speaking, the question is how do I not shoot myself in the foot in the long term.

I am currently using the first approach (1 queue for all messages).

I cannot see any major limitations of this pattern.

**Comment by manast** [comment]
depends, if one type of message is very common it will delay the other messages for example. As said before it mostly depends on your requirements.

**Comment by manast** [comment]
another example, say you have a bank office, you could have one queue for all the different errands, or one queue per type, one for loans, another for retrieving money, another for advises, etc. In this case I think it is better one queue per type, I do not want to wait for people asking for advice if I just want to retrieve some money from my account.

**Comment by gajus** [comment]
That makes sense. Wouldn't prioritization solve most of this, though?

**Comment by manast** [comment]
not really, if you have a high priority job that occurs very often it could starve the less prioritized jobs.

**Comment by mfrye** [comment]
@manast as an add on to this question, say I have a job already in the queue in a waiting state, and I decide I need to start it immediately and/or be the next job. I initially though job.promote() could do this, but I realized that only works if it's in a delayed state. Is there a way to do this?

Great work on this btw. I've been looking for an updated job queue like this for awhile now and this is really well done.

**Comment by manast** [comment]
currently it is not possible to move a job inside the wait list, however technically it is possible, so if this is an important usecase I could add it as a new feature.

**Comment by roggervalf** [comment]
I think [changePriority](https://docs.bullmq.io/guide/jobs/prioritized#change-priority) method is what you are looking for
