### ISSUE TITLE
Throw custom error class is not propagated properly to the Queue 

### ISSUE THREAD

**Issue by felixmosh** [taskforcesh/bullmq#254]
Hi, my worker throws a custom error class, I do see the error with the relevant class name & stack trace in the Bull-Dashboard.

But when the `failed` event triggered on the queue process I get only the error's `message` field.
https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L375

```javascript
class CustomError extends Error {
  public code: any;
  public details: string[];

  constructor(code, message, details) {
    super(message);

    Error.captureStackTrace(this, this.constructor);

    this.name = this.constructor.name;
    this.message = message;

    this.code = code;
    this.details = details;
  }
}

// worker - a separate process
const worker = new Worker(
  'queueName',
  async (job) => throw new CustomError(4004, 'Message not found', 'more details')
);

// queue - main process
queue = new Queue('queueName');
const job = await queue.add('test', { foo: 'bar' });
try {
  const result = await job.waitUntilFinished(queueEvents);
} catch (error) {
  // error.message will contain "Message not found"
  // here the error doesn't have any fields of the custom error event.  (such as name, code)
}
```

In bull-dashboard I do see the original error object, that means that the info exists in redis.
![image](https://user-images.githubusercontent.com/9304194/90237002-3fe32700-de2c-11ea-8c09-c127423220cb.png)

I hope that the issue is clear, if not, I'm available for more details.

**Comment by mattwynne** [comment]
I guess this is happening because the error is going through a serialization/deserialization process as it comes back through Redis.

I'm also having issues with this as I'd like to be able to raise custom errors in the workers. I'd like a way to be able to hook into the serialization/deserialization so I can control the Error types being returned from the job promise.

**Comment by felixmosh** [comment]
This is the place which copies the `message` property
https://github.com/taskforcesh/bullmq/blob/cef134f7c4d87e1b80ba42a5e06c3877956ff4cc/src/classes/job.ts#L254

**Comment by manast** [comment]
yeah, it is impossible to keep that class since as mentioned above the error has been serialized and deserialiized.

**Comment by felixmosh** [comment]
How about exposing some kind of serialize & deserialize methods, there I can make it to work.

In the serilize it will pass the class obj, there i will retorn a serializable PoJO. An on the other side it will invoke the deserialize method.

WDYT?

**Comment by manast** [comment]
there are plans for custom serializers but this is not so simple, for instance, the UI would need to also know about the serialize you are using so that it can display the jobs data correctly.

**Comment by manast** [comment]
not sure if it would help in your case, but maybe simpler would be if it was possible to add some "type" field to the error that is being thrown, then you could check that for discriminate which error it is.

**Comment by felixmosh** [comment]
> there are plans for custom serializers but this is not so simple, for instance, the UI would need to also know about the serialize you are using so that it can display the jobs data correctly.

This is not an issue because it is possible to implement it as enhancement, at the worse it will fallback to the message of the error (like it is now)

**Comment by felixmosh** [comment]
> not sure if it would help in your case, but maybe simpler would be if it was possible to add some "type" field to the error that is being thrown, then you could check that for discriminate which error it is.

This will be helpful but without the additional info it would be useless.

**Comment by mattwynne** [comment]
@felixmosh FWIW here's how I've worked around it for now: https://github.com/SmartBear/git-en-boite/pull/221

Essentially, it [serializes all the properties and constructor name](https://github.com/SmartBear/git-en-boite/blob/custom-errors-through-the-wire/packages/core/src/git_error.ts#L33) of the custom error in the `message` property of a regular `Error` as it goes through Bull, then when it comes out the other side in the client, we [deserialize it](https://github.com/SmartBear/git-en-boite/blob/custom-errors-through-the-wire/packages/core/src/git_error.ts#L19).

**Comment by felixmosh** [comment]
> @felixmosh FWIW here's how I've worked around it for now: [SmartBear/git-en-boite#221](https://github.com/SmartBear/git-en-boite/pull/221)
> 
> Essentially, it [serializes all the properties and constructor name](https://github.com/SmartBear/git-en-boite/blob/custom-errors-through-the-wire/packages/core/src/git_error.ts#L33) of the custom error in the `message` property of a regular `Error` as it goes through Bull, then when it comes out the other side in the client, we [deserialize it](https://github.com/SmartBear/git-en-boite/blob/custom-errors-through-the-wire/packages/core/src/git_error.ts#L19).

Thanks for sharing your solution, actually I’ve serialized some data in the message as well but it is hacky  :/

**Comment by mattwynne** [comment]
It could be possible to use something like https://github.com/efossas/Javascript-Serializer within Bull to serialize the error (instead of just capturing the `message` and `stack` properties) on the Job.

Perhaps we could do this in a third property on `Job` so other things (like the UI) that already read the `message` and `stack` could continue to rely on them?

**Comment by manast** [comment]
@mattwynne I am not super positive about this idea but I may change my opinion in the future.

**Comment by drone1** [comment]
@mattwynne: What is the suggested pattern for getting at the nature of a failed job? Even a simple job may fail for a variety of reasons.

**Comment by mattwynne** [comment]
@drone1 I don't understand your question, sorry.

What I'm suggesting is to remove the assumption that the error raised in the worker will neccesarily be of type `Error` and support a way to serialize / deserialize custom errror types.

Even if bull were opinionated about using a particular framework / library for custom errors, I think that would be fine.

**Comment by drone1** [comment]
@mattwynne I've got a worker failing on a job. The worker's ``failed`` event callback has receiving an ``err`` value that is an object.

```
		.on('failed', (job, err) => {
			// A job failed with reason `err`!
			console.log(`Job "${job.id}" failed.`)
			console.log(err)   // **prints out an object with keys 'response', 'config', 'code', 'errors' **, thrown by my code
		})
```

Great.

But then, my ``queueEvents`` ``failed`` callback receives a ``failedReason`` is the value of ``err.response`` -- the rest of the object seems to get lost somehow. 

Is there a best practice for getting around this now? I'm using BullMQ v3.5.11.

I want my job to be able to fail and pass the full context back to queueEvents, if possible.

**Comment by manast** [comment]
You must throw an Error, not an arbitrary object.

**Comment by drone1** [comment]
Thank you! I’ll try this.

Perhaps BullMq could print an error message if the user throws a non-Error
object?

**Comment by manast** [comment]
In general, you should never throw anything that is not an Error object. There is an eslint rule for that if you want to enforce it: https://eslint.org/docs/latest/rules/no-throw-literal

**Comment by drone1** [comment]
if not an error, perhaps it could be mentioned in the
documentation/examples if it isn’t already. I lost a lot of time on this.
Thank you.

**Comment by kibertoad** [comment]
@manast Can we maybe get a simpler solution, where if there is an extra field (e. g. `details`), it will get JSON.stringify and included together with message and stacktrace? And then UI would just display it as-is. Then you don't need to support any fancy serializer/deserializer logic, but instead put it on user to ensure that what is there is serializable during the usual flow.

**Comment by manast** [comment]
@kibertoad honestly I am confused on what this issue is all about. I can see errors perfectly in Taskforce.sh, can you give me an example on how does it look like know, and how you would like it to look like?

**Comment by kibertoad** [comment]
@manast Imagine that you are throwing an aggregate error ValidationError that under-the-hood has an array of specific ZodError instances, e. g. within the field details.errors
Currently these would not be displayed at all.

**Comment by manast** [comment]
I will have to think more about it...

**Comment by jderose9** [comment]
This is causing a problem for me as well because I have custom types that extend Error with additional fields and that data is lost when I call job.getChildrenValues().

It's stuff like a user friendly message, fields that failed validation, a process or request id that the error was associated with.

I used to handle this with the worker failed event, which allowed access to the full object thrown by the job, but since re-working things to use the Flows feature, I have to now stuff all information into the Error.message field and parse it back out if the parent job wants to bubble those details out to the job initiator when all of the children have completed.

I know there's some talk about custom serialization above but I would think JSON serialization would work on a specific property and be a little simpler implementation. So for example, bullmq could define a JobError class with a details attribute that a failing job could attach JSON serializable content to and throw.

**Comment by felixmosh** [comment]
`JobError` sounds an great idea!

**Comment by drone1** [comment]
@manast any thoughts or progress on this subject? Thank you.
