### ISSUE TITLE
TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by chiragmewada** [taskforcesh/bullmq#255]
I am trying to add bullmq in reactjs project.

yarn add bullmq

import IORedis from 'ioredis'
import { load, Queue } from 'bullmq'

const connection = new IORedis()

connection.once('ready', async () => {
  await load(connection)
  const queue = new Queue('name', { connection })
  // ...
})

**Comment by roggervalf** [comment]
pretty old issue, also we are not exposing any load function
