### ISSUE TITLE
Inaccurate Queue job status?

### ISSUE THREAD

**Issue by afallon02** [taskforcesh/bullmq#260]
I am trying to get the full list of jobs my queue has processed via the following code;

```javascript
  async statuses(req, res) {
    const complete = await fileQueue.getCompleted();
    const active = await fileQueue.getActive();
    const failed = await fileQueue.getFailed();
    res
      .status(200)
      .json({ complete: complete, active: active, failed: failed });
  },
```

For some reason I only ever get the **exactly the last 2 jobs** from the getCompleted function and I'm not entirely sure why. Can't really find anything in the documentation. 

I assume I am being very silly and messing something simple up - but I can't tell what.

Attaching an image of what Redis thinks it has seen;

<img width="1440" alt="Screenshot 2020-08-19 at 20 12 38" src="https://user-images.githubusercontent.com/20660987/90679818-a3b88600-e258-11ea-87c3-df38aac61147.png">

**Comment by manast** [comment]
can you provide a complete example where you add the jobs, process them and then the getCompleted does not return what you expect?

**Comment by afallon02** [comment]
Sure here - So I call this code on app start-up to create the queue and the worker. So this queue and worker are global - but couldn't really tell from the doc's if that was a good idea or not. It seems to do everything I want except actually reporting the jobs in the queue.

```javascript
const fileQueue = new Queue("file-uploads", {
  connection: {
    host: "host.docker.internal",
    port: 6379,
  },
});

const worker = new Worker(
  "file-uploads",
  async (job) => {
    if (job.name === "FILE_UPLOAD_TEXT") {
      console.log(job);
      const data = await readFile(job.data.file.tempFilePath);
      const newReq = {
        index: "oswald_dev",
        body: {
          id: uuid.v1(),
          type: "text-document",
          owner: job.data.owner,
          links: [],
          text: data,
          title: job.data.file.name,
        },
      };

      try {
        await Elastic.putFile(newReq);
        job.data.status = "complete";
      } catch (e) {
        job.data.status = "failed";
        job.moveToFailed(e);
      }
    }
  },
  {
    connection: {
      host: "host.docker.internal",
      port: 6379,
    },
  }
);
```

Then there is an express route I call that takes some stuff from the body, creates a job and passes in the file to be processed:

```javascript
const FileUpload = {
  textFile(req, res) {
    Auth.verifyToken(req.token, (noToken, token) => {
      if (noToken) {
        return res.sendStatus(403);
      } else if (token) {
        QueueManager.addFileJob("FILE_UPLOAD_TEXT", {
          status: "started",
          owner: req.body.owner,
          file: req.files.txtFile,
        });

        res.status(200).json({ response: "OK" });
      }
    });
  },
};
```

**Comment by manast** [comment]
A couple of things, this is not needed:
```ts
try {
        await Elastic.putFile(newReq);
        job.data.status = "complete";
      } catch (e) {
        job.data.status = "failed";
        job.moveToFailed(e);
      }
```

The worker will handle the exceptions and mark those jobs as failed. 
The other thing:
```ts
  addFileJob(jobName, job) {
    fileQueue.add(jobName, job);
  },
```
The "add" method returns a promise, please make sure you return that and handle potential exceptions accordingly.

Other than that I cannot see any other major problems. For the problem you are reporting, if you could write a "test case" that I can run and that reproduces the issue I can take a deeper look into it.

**Comment by afallon02** [comment]
Hey thanks for the quick reply - 

I will write one soon and update this PR - might take a while though - feel free to close and I can open a new issue with a repro if that helps you clean your queue.

Quick question before that though - Is it advised to avoid handle failures in the code running in your worker yourself? The only reason I wanted to do it was because I want to set a specific piece of data on the job to show in the frontend - e.g; I was planning on the job.data.status holding a human readable reason for failure, so I can show it in the frontend.

I get pretty meaningful errors from Elastic.putFile that would help the user understand what was wrong with their file so was doing the try/catch inside the worker like I showed in the example. 

Should I really not be manipulating the job as its processing? It seem's like a handy feature if I could do that.

Fair point handling errors from add the job to the queue - thanks for that advice.

**Comment by manast** [comment]
You can throw any error you want from the processor and you will get that information in the failed job, so you do not loose anything by letting bull handle it.

**Comment by afallon02** [comment]
I've resolved this issue - I noticed the `getCompleted()` takes in a start and an end param, if I called `getCompleteCount()` and pass in 0, completeCount as params to the `getComplete()` function I get the correct number of jobs. It seems to default to just returning 2 jobs for some reason, but never mind - its fixed now!
