### ISSUE TITLE
[Docs]: Minor wrong information in docs

### ISSUE THREAD

**Issue by stouch** [taskforcesh/bullmq#2602]
### Version

latest

### Platform

NodeJS

### What happened?

In this docs section : ["Retrying failing jobs"](https://docs.bullmq.io/guide/retrying-failing-jobs) : 

> The code below shows how to specify the built-in "exponential" backoff function with a 1-second delay as a seed value, so it will retry at most 3 times spaced after 1 second, 2 seconds, and 4 seconds respectively:

should be : 
> The code below shows how to specify the built-in "exponential" backoff function with a 1-second delay as a seed value, so it will retry 2 times (after the first attempt, reaching a total 3 attempts) spaced after 1 second and 2 seconds respectively:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
thank you @stouch
