### ISSUE TITLE
Sandboxed processors automatically close the Node window 

### ISSUE THREAD

**Issue by PDB6912** [taskforcesh/bullmq#2604]
In Windows, running a job in a Sandboxed processors pops up a new Node window. Can't it automatically close the Node window after the job completes?

**Comment by manast** [comment]
BullMQ keeps processes to be reused by the next jobs to be processed. I guess windows wants to have a window associated to the NodeJS process, I am not familiar with windows so I don't really know...

**Comment by PDB6912** [comment]
@manast 
Thank you. It was my fault; I used pm2, which causes node windows to appear when using sandbox mode in Windows.
