### ISSUE TITLE
[Bug]: Bull is processing two jobs simultaneously even with concurrency equals to 1

### ISSUE THREAD

**Issue by fccoelho7** [taskforcesh/bullmq#2606]
### Version

v5.8.0

### Platform

NodeJS

### What happened?

Bull is processing two jobs simultaneously, even with concurrency equal to 1.

<img width="597" alt="image" src="https://github.com/taskforcesh/bullmq/assets/4829072/5ac65b1b-2976-400e-9e45-17a342f4377a">

I also can't set concurrency = 0 due to the following issue:

```sh
Error: concurrency must be a finite number greater than 0
```

I'm using Bun to run the worker.

### How to reproduce.

```ts
const worker = new Worker(
  "Main",
  async (job) => inject(ExecuteWorkflow).execute(job.data),
  {
    connection,
    concurrency: 1,
  }
);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
What is the proof that the jobs were executed simultaneously? It is extremely unlikely that this is the case btw...

**Comment by fccoelho7** [comment]
Hey @manast, thanks for reaching out. I'm logging on to DB every execution. As you can see in the image, the left column is the startedAt, and the right one is finishedAt. I got two events almost simultaneously. I got the same behavior if checking on BullMQ UI.

**Comment by fccoelho7** [comment]
<img width="1093" alt="image" src="https://github.com/taskforcesh/bullmq/assets/4829072/315632b5-7b59-4a56-90ee-89f48ec20768">

**Comment by manast** [comment]
But if the jobs are processed very fast then it is normal they are executed in the same second.

**Comment by fccoelho7** [comment]
I added a delay of 30s to each execution.
