### ISSUE TITLE
List all queues and jobs

### ISSUE THREAD

**Issue by kevinresol** [taskforcesh/bullmq#261]
Is there an API to list all current queues and jobs (and their statuses)?

**Comment by clouedoc** [comment]
Hi,
I'm searching for this API too

**Comment by vmp-mark** [comment]
Is there any way to get a list of all jobs without knowing the queue names beforehand?

**Comment by ccollie** [comment]
@vmp-mark You can use something like the [following](https://github.com/graphql-compose/graphql-compose-bullmq/blob/7b1a955b548c11eadedc337fb7e47c9d63218c83/src/helpers/queueTitles.ts) to get a list of queues, then use code like above to iterate jobs.

**Comment by vmp-mark** [comment]
Thanks @ccollie, I'll take a look!!

**Comment by Dylaaaan** [comment]
i had the same problem. Have you solved your problem? Can you provide some examples? @ccollie

**Comment by manast** [comment]
@andrisi thoughts on what?

**Comment by andrisi** [comment]
@manast sorry... so listing all queues. Thanks!

**Comment by manast** [comment]
You can use something like this: https://github.com/taskforcesh/taskforce-connector/blob/master/lib/queue-factory.ts#L46

**Comment by faaiz-backend-II** [comment]
Update on this issue ?

**Comment by manast** [comment]
@faaiz-backend-II I am not really sure what should be updated, as far as I can see we have responded to the issue, I think this should be close now. For requesting new features, please create a new issue.

**Comment by andrisi** [comment]
@manast while I'm sure the code suggested does it's job, but it's not a good idea (recepie for disaster?) to hack into internals of a library, instead of adding your code as a method, and maintaining it along with other relevant code. Your code is written with "insider knowledge".

**Comment by manast** [comment]
This issue is a question, and the question AFAIK has been responded... not sure what else it is supposed to be done here.

**Comment by andrisi** [comment]
I'd treat it as a feature suggestion. If it's an administrative issue, I'd be happy to do that. Thanks!

**Comment by manast** [comment]
It is not administrative at all. 

This issue is a question, which I think has been responded appropriately. If a new feature request is to be made, for starters it would need to have a proper specification on what this new feature would be about.

Furthermore it is not at all obvious if such a feature would be important enough to be implemented in the first place. As this issue was formulated and after the answers given there are no other actions to be taken by us.
