### ISSUE TITLE
[Bug]: removeOnComplete fails when set on worker

### ISSUE THREAD

**Issue by TStrongCircle** [taskforcesh/bullmq#2620]
### Version

5.8.2

### Platform

NodeJS

### What happened?

When setting `removeOnCompleted` to true on the worker, it fails due to a missing lock. It works fine if it is set on the queue as a default setting for jobs.

Working Code:
<img width="392" alt="Working code" src="https://github.com/taskforcesh/bullmq/assets/122602500/d7e51dff-857b-4ffb-b7fa-d12fdb388bce">
Working Output:
<img width="481" alt="Working output" src="https://github.com/taskforcesh/bullmq/assets/122602500/72b87c91-20f1-410c-8451-f3d98007b221">

### How to reproduce.

```
import { Queue, Worker } from 'bullmq';

const queue = new Queue('testQueue', {
    connection: {
        host: 'localhost',
        port: 6379,
    },
    settings: {
        lockDuration: 10000,
    },
    defaultJobOptions: {
        //removeOnComplete: true, // setting this works
    },
});

const worker = new Worker(
    'testQueue',
    async (job) => {
        console.log(`Processing job ${job.id}`);
        // Simulate a running job
        await new Promise((resolve) => setTimeout(resolve, 2000));
    },
    {
        connection: {
            host: 'localhost',
            port: 6379,
        },
        removeOnComplete: true, // setting this doesn't work
    }
);

queue.add('testJob', { foo: 'bar' }, { repeat: { every: 5000 } });

worker.on('completed', (job) => {
    console.log(`Completed job ${job.id}`);
});

worker.on('failed', (job, err) => {
    console.log(`Failed job ${job.id} with error ${err.message}`);
});

```

### Relevant log output

```shell
Processing job repeat:35df57a2b46812900ab83bf27597d155:1719223590000
Error: Missing lock for job repeat:35df57a2b46812900ab83bf27597d155:1719223590000. moveToFinished
    at Scripts.finishedErrors (/home/user/test-project/node_modules/bullmq/dist/cjs/classes/scripts.js:308:24)
    at Job.moveToFailed (/home/user/test-project/node_modules/bullmq/dist/cjs/classes/job.js:448:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (/home/user/test-project/node_modules/bullmq/dist/cjs/classes/worker.js:425:21)
    at async Worker.retryIfFailed (/home/user/test-project/node_modules/bullmq/dist/cjs/classes/worker.js:629:24)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Thanks for the bug report. I can confirm that I can reproduce the issue. Debugging now...

**Comment by manast** [comment]
Ok, so the issue is that the argument passed to removeOnComplete is incorrect, it does not accept a boolean but a KeepJobs object: https://api.docs.bullmq.io/interfaces/v5.WorkerOptions.html#removeOnComplete
I really encourage to use Typescript as it would find this kind of issue at the compiling stage.
