### ISSUE TITLE
[Bug]: getGroupsJobsCount always returns 0

### ISSUE THREAD

**Issue by billoneil** [taskforcesh/bullmq#2624]
### Version

5.7.14 (bullmq) 7.9.1 (bullmq-pro) 3.0.0 nestjs-bullmq-pro

### Platform

NodeJS

### What happened?

We are currently evaluating upgrading to BullMQ Pro and are hitting one blocker from moving forward. We have an interval job that reports metrics per bullmq queue to datadog every 10 seconds. When using groups I noticed from other issues to get counts of jobs from groups you need to use `getGroupJobsCount` or `getGroupsJobsCount`. `getGroupJobsCount` seems to work for us when passing the group id but `getGroupsJobsCount` will always return 0.

### How to reproduce.

We have extended both WorkerPro and WorkerHost to get APM tracing and some default behavior we want all workers to have. Everything seems to work except `getGroupsJobsCount` always returns 0.

Here is the rough code but can try to get a better example if needed (Unsure if nestJS is involved or just an issue with queue.getGroupsJobsCount.

TracedWorker
```ts
import { wrapWithAsyncContext } from "@regal-voice/nest-logger/lib/request.context";
import { WorkerPro, JobPro } from "@taskforcesh/bullmq-pro";
import tracer from "dd-trace";

export class TracedWorker<DataType = any, ResultType = any, NameType extends string = string> extends WorkerPro<
    DataType,
    ResultType,
    NameType
> {
    async callProcessJob(job: JobPro<DataType, ResultType, NameType>, token: string): Promise<ResultType> {
        return tracer.trace(
            "bullmq.worker.process",
            {
                resource: `${this.name} [${job.name}]`,
                tags: {
                    jobName: job.name,
                    opts: job.opts,
                },
            },
            () => {
                return wrapWithAsyncContext(() => super.callProcessJob(job, token));
            }
        );
    }
}
```

TracedWorkerHost
```ts
import { getQueueToken, OnWorkerEvent, WorkerHost } from "@taskforcesh/nestjs-bullmq-pro";
import { ConfigService } from "@nestjs/config";
import { ModuleRef } from "@nestjs/core";
import { Logger } from "@regal-voice/nest-logger";
import { JobPro, QueuePro, WorkerListener } from "@taskforcesh/bullmq-pro";

import { MetricsService } from "@app/metrics/metrics.service";
import { normalizeError } from "@app/shared/error.utils";
import { TracedWorker } from "@app/metrics/bullmq/traced-worker";
import { BulkJobOptions } from "bullmq";
import tracer from "dd-trace";

export abstract class TracedWorkerHost<
    DataType,
    ResultType,
    NameType extends string = string,
> extends WorkerHost<TracedWorker> {
    constructor(
        readonly logger: Logger,
        readonly moduleRef: ModuleRef
    ) {
        super();
    }
    abstract processTraced(job: JobPro<DataType, ResultType, NameType>, token: string | undefined): Promise<ResultType>;

    process(job: JobPro<DataType, ResultType, NameType>, token?: string): Promise<ResultType> {
        return this.processTraced(job, token);
    }

    // Could not figure out a way to extend the bull Queue class to enable metrics.
    // This should be good enough because every Queue also has a Worker.
    onModuleInit(): void {
        const metricsService = this.moduleRef.get(MetricsService, { strict: false });
        const configService = this.moduleRef.get(ConfigService, { strict: false });
        const ddApiKey = configService.get<string>("DD_API_KEY");
        if (ddApiKey) {
            // We are dynamically fetching the Queue instance based on the workers name.
            // strict: false is required because queues are created in a more global module.
            const queue: QueuePro = this.moduleRef.get(getQueueToken(this.worker.name), { strict: false });
            const interval = setInterval(() => {
                void (async () => {
                    await tracer.trace(
                        "node.service",
                        {
                            resource: "TracedWorkerHost.trackMetrics",
                        },
                        async () => await this.trackMetrics(metricsService, queue)
                    );
                })();
            }, 10000);
            interval.unref();
            this.logger.info(`Starting TracedQueue.trackPoolMetrics for queue: ${queue.name}`);
        } else {
            this.logger.info(
                `DD_API_KEY is not set not starting TracedQueue.trackPoolMetrics for queue: ${this.worker.name}`
            );
        }
    }

    async trackMetrics(metricsService: MetricsService, queue: QueuePro): Promise<void> {
        const counts = await queue.getJobCounts("active", "completed", "delayed", "failed", "paused", "waiting");
        for (const [jobType, count] of Object.entries(counts)) {
            const tags = {
                queue: queue.name,
                jobType,
            };
            metricsService.gauge(`bullmq.queue.length`, count, tags);
        }

        const waitingGroupJobsdev01 = await queue.getGroupJobsCount("square-dev01");
        this.logger.info(`Waiting group jobs dev01: ${waitingGroupJobsdev01}`, { queue: queue.name });

        // Count pending jobs across groups
        const waitingGroupJobs = await queue.getGroupsJobsCount(500);
        this.logger.info(`Waiting group jobs: ${waitingGroupJobs}`, { queue: queue.name });
        const tags = {
            queue: queue.name,
            jobType: "waiting-group",
        };
        metricsService.gauge(`bullmq.queue.length`, waitingGroupJobs, tags);

        const groupInfo = await queue.getGroupsCountByStatus();
        for (const [groupStatus, count] of Object.entries(groupInfo)) {
            const tags = {
                queue: queue.name,
                groupStatus,
            };
            metricsService.gauge(`bullmq.queue.group.status`, count, tags);
        }
    }

    @OnWorkerEvent("failed")
    ... // lots of default logging
    
}
```

We have a class that extends `WorkerHost` that adds some default logging as well as using nestjs' `onModuleInit` to set up an interval that tracks metrics. All of the metrics work for `queue.getJobCounts`, `queue.getGroupJobsCount`, and `queue.getGroupsCountByStatus` but `queue.getGroupsJobsCount` always returns 0 even when fetching all jobs for a specific group returns a count.

Logs showing a `getGroupJobsCount` returns job count but using `getGroupsJobsCount` returns 0.
<img width="827" alt="image" src="https://github.com/taskforcesh/bullmq/assets/5205330/2f399160-c22e-43aa-b8ff-71ab614750c3">

<img width="1529" alt="image" src="https://github.com/taskforcesh/bullmq/assets/5205330/c94a13c4-81f6-416b-8d89-3fae7374c40f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Sorry for the late response, I missed this issue. 
It would be great if you could isolate the problem in a code that does not have all the dependencies and complexities of the code that you have provided. We can't reproduce the issue in this way, also it could be that the issue comes from some side effect of the other user code. We have full tests that cover these APIs so we will need a concise and specific case where ```getGroupsJobsCount``` does not work as expected.

**Comment by roggervalf** [comment]
hi @billoneil are you also using max or rate limit features for your group?

**Comment by billoneil** [comment]
@roggervalf we are using concurrency and group concurrency. I will see if I can get a more minimal working example.

**Comment by roggervalf** [comment]
I think I know which is the issue I created an issue for issue to cover that edge case

**Comment by manast** [comment]
I think this would be the proper api to use if you want to know the counts of any particular status:
https://api.bullmq.pro/classes/v7.Queue.html#getGroupsCountByStatus

**Comment by billoneil** [comment]
@manast ok I see, I'm going to double check what I am looking for but I believe that will give me what I want. I think I misunderstood and thought all jobs would be waiting until completed but it seems like they are broken up into various data structures for the different statuses.

Is there anything in the documentation similar to https://docs.bullmq.io/guide/architecture for how the groups and their jobs flow?

I'll close this for now since it sounds like its working correctly and I was looking at the wrong metrics for what I wanted.

**Comment by roggervalf** [comment]
Hi @billoneil I talked with @manast about your issue and there was an issue in getGroupsJobsCount that was not considering other states apart of waiting, it's fixed since v7.10.1

**Comment by billoneil** [comment]
Thanks @roggervalf I'll update to the newest version. Out of curiosity is there a performance difference between `getGroupsJobsCount` and `getGroupsCountByStatus`? Our groups will have a pretty high cardinality (a unique identifier for a user).

I'm assuming under the hood `getGroupsJobsCount` will need to scan all keys which is why it takes an iteration size? Will `getGroupsCountByStatus` also do the same under the hood or is it accessing the counts in a different way?

I only really need to know if our queue is backing up with jobs that we are not processing fast enough. The count per group would be nice but I could run the separately to diagnose which group is having an issue once we know there is an issue.

**Comment by roggervalf** [comment]
hey @billoneil, the difference between those method is that getGroupsJobsCount will return how many jobs are in waiting across all groups independently if those groups are in waiting, paused, maxed or limited state. We allow passing a limit value as we need to go through each group to get how many jobs are added into them, there could be many groups. Better to have an iterator just to prevent a long running calculation.
getGroupsCountByStatus does no need a limit value because this method is only for counting how many groups are in each state (waiting, paused, maxed and limited). This one is not counting jobs.

**Comment by billoneil** [comment]
@roggervalf tested with v7.10.1 and it looks good to me thanks!
