### ISSUE TITLE
Repeatable jobs do not check for existence

### ISSUE THREAD

**Issue by pc-jedi** [taskforcesh/bullmq#263]
In the docs it says:
> Bull is smart enough not to add the same repeatable job if the repeat options are the same.

But there is even a test that this should work:
https://github.com/taskforcesh/bullmq/blob/master/src/test/test_repeat.ts#L373-L386

I guess the issue is that [`skipCheckExists`](https://github.com/taskforcesh/bullmq/blob/f52a33a3f4dddc83c5146018b645d5873f63b87a/src/classes/repeat.ts#L12) is hardcoded to [`true`](https://github.com/taskforcesh/bullmq/blob/f52a33a3f4dddc83c5146018b645d5873f63b87a/src/classes/queue.ts#L53)

I see two ways to fix this:
1. Remove the sentence from the docs.
2. Expose the `skipCheckExists` via `JobsOptions` and do not hardcoded it to `true`.

**Comment by pc-jedi** [comment]
Ping @manast

**Comment by manast** [comment]
The documentation is correct. The test is not testing what you highlighted, it is testing, maybe clumsily so, what the documentation says.

**Comment by roggervalf** [comment]
#769 tries to add more context on repeatable configs, please @pc-jedi when you get a chance, take a look.
