### ISSUE TITLE
Repeated job not rescheduled

### ISSUE THREAD

**Issue by RobertIgn** [taskforcesh/bullmq#2643]
In our application, we have several node containers that process jobs from a queue inside redis. All containers have a stall timer of 1 minute, and a maxStalledCount of 0. The large majority of jobs do not take too long, maybe a few seconds, with a few exceptions.  It can happen sometimes that a job takes longer than the stalled timer.

Recently, we encountered a strange issue: we had some repeated jobs, scheduled for every 5 minutes, that stopped being executed at all (several days passed).

From what we gathered from our logs, all of the jobs that stopped repeating were last handled by the same container. Around a second before the repeated jobs were added, a job that took around 90 seconds was started by the container, there is a possibility that this job was blocking. 

Interestingly, the problem jobs had an 'added' event triggered for them, but didn't have a 'waiting' or 'active' one. In other words, it seems that the jobs were picked up from the queue, but not actually processed.

Since I saw that the explanation of repeated jobs is that the next instance is added right before processing the current one, I figured that our jobs might not have gotten rescheduled because they got picked form the queue, but not processed due to the container being blocked.

My question is:
Is the scenario that I described above possible, or did we misdiagnose the issue? And if we did not, then is there a way to prevent this in the future, other than just ensuring that our containers don't get blocked, or crash at the wrong time?

Thank you in advance for looking into this.

Kind regards,
Robert

**Comment by roggervalf** [comment]
hi @RobertIgn, a test case would help us to understand and investigate it. Pls if you can provide one

**Comment by manast** [comment]
Closing as there is no code to reproduce it. Furthermore this issue probably does not exist anymore with the new upsertJobScheduler method.
