### ISSUE TITLE
[FR] broadcast job

### ISSUE THREAD

**Issue by Diluka** [taskforcesh/bullmq#2651]
**Is your feature request related to a problem? Please describe.**
I want a job that can be processed by all workers at the same time

**Describe the solution you'd like**
Add a job to the queue, and each worker can pick and process it. and collect each worker's result. Working like QueueEvents.
Results are how many workers are there when adding job, each worker's job status(result, reason, attempts...)

**Describe alternatives you've considered**
Like EventEmitter but cross nodes and keep status.

**Additional context**

**Comment by manast** [comment]
I think standard Redis Pubsub basically does this already, does it not work for your use case?

**Comment by manast** [comment]
Closing as no actions to do here.
