### ISSUE TITLE
[Bug]: I can't use anything with rate-limiting

### ISSUE THREAD

**Issue by jtapeg** [taskforcesh/bullmq#2653]
### Version

v5.9.0

### Platform

NodeJS

### What happened?

I can't use anything with rate-limiting that is on this page https://docs.bullmq.io/guide/rate-limiting

![Screenshot_5](https://github.com/user-attachments/assets/7f403dae-cb99-4c6f-9610-a607f4a0a135)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @jtapeg, as the warning that is above of queue example:
`From BullMQ 3.0 and onwards, group keys support is removed to improve global rate limit, so the information below is only valid for older versions.`
limiter options is no longer available in queue instance, it was moved into worker options as the first example in https://docs.bullmq.io/guide/rate-limiting
