### ISSUE TITLE
[Bug]: worker doesn't call error event when throw a Error in worker

### ISSUE THREAD

**Issue by 850036165** [taskforcesh/bullmq#2654]
### Version

v5.8.7

### Platform

NodeJS

### What happened?

I used bullmq in nest and，worker doesn't call error event when throw a Error in worker, the failed event was called but no error event

### How to reproduce.

    const queue = new Queue('testQueue')
    const worker = new Worker(
      'testQueue',
      async (job: Job) => {
        console.log('job', job.id)
        throw new Error('error')
        // Do something with job
        return 'some value'
      }
    )
    worker.on('failed', (job) => {
      console.log('failed', job.id)
    })
    worker.on('error', (e) => {
      console.log('err', e)
    })
    worker.on('completed', (job) => {
      console.log('completed', job.id)
    })

### Relevant log output

```shell
job 13
failed 13
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
Hi @850036165, error event from worker is for errors coming from failures when running lua scripts for example https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L772, in your case you should just use failed event

**Comment by 850036165** [comment]
> Hi @850036165, error event from worker is for errors coming from failures when running lua scripts for example https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L772, in your case you should just use failed event

Thanks @roggervalf , I found this tip in the doc , in this case , should i just catch and handle error in failed event will be ok?
![image](https://github.com/user-attachments/assets/144e1b89-ba3b-4a78-875f-5595f8a8639d)

**Comment by manast** [comment]
@850036165 when the processor function in a worker throws an exception it is handled by BullMQ and the job is marked as failed. You do not need to handle this exception in any way. The error handler is for "unexpected" exceptions that may happen internally, for example it could be connection errors or similar.
