### ISSUE TITLE
Redis cluster Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by apoorvans** [taskforcesh/bullmq#266]
## Description
Seeing connection error in the logs continuously when connecting to a redis cluster running in kubernetes. I used a prefix when creating the queue.
`new Queue("thequeuename", { connection: redis(), prefix: "{myqueueprefix}" })`

where redis() is:
`import Redis from 'ioredis';
export default function redis() {
    return new Redis.Cluster(config, { enableReadyCheck: true });
}`

Don't know where to start looking. There was no trouble connecting to a single redis instance in local or stage env (also in k8s).

## Bull version
1.9.0

**Comment by manast** [comment]
Can you provide full stacks of the errors?
also, can you connect to that same cluster with standard ioredis and check if you can issue some commands?

**Comment by apoorvans** [comment]
@manast here is what I have in terms of stack, not sure if this helps:
`[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)`

Btw, I am connecting to a redis 6 cluster, just in case that matters.
To the second question, yes I am connecting to this cluster independently from ioredis for a lot of other caching, using the same connection method, and it's working fine without any errors being logged.

**Comment by manast** [comment]
In that error the address is localhost, I do not think that would be correct, seems like your settings for redis connection are wrong.

**Comment by apoorvans** [comment]
Not sure what was the issue but bumping ioredis version from 4.2.3 to 4.17.3 helped. Not seeing the error anymore and queues seem to be working ok. Thanks for your work @manast
