### ISSUE TITLE
[Bug]: v5.10.0 introducing "ReplyError: CROSSSLOT Keys in request don't hash to the same slot"

### ISSUE THREAD

**Issue by arsonik** [taskforcesh/bullmq#2660]
### Version

3.10.0

### Platform

NodeJS

### What happened?

A bug happened after upgrading to v5.10.0 I get a "ReplyError: CROSSSLOT Keys in request don't hash to the same slot"
When using BullMQ against a redis cluster server configured with a '{my_prefix}' prefix !

### Relevant log output

```shell
ReplyError: CROSSSLOT Keys in request don't hash to the same slot
    at parseError (xxx/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (xxx/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Can you double-check check you are using the proper prefix? from which version where you upgrading?

**Comment by manast** [comment]
As a sidetone, all our test suite runs against using a custom prefix so that we can run DragonflyDBs tests, so it is unlikely we have introduced a regression in this regard.

**Comment by arsonik** [comment]
> As a sidetone, all our test suite runs against using a custom prefix so that we can run DragonflyDBs tests, so it is unlikely we have introduced a regression in this regard.

are the tests running on a cluster with multiples nodes ?
