### ISSUE TITLE
Clarification on BullMQ scalability for large numbers of queues

### ISSUE THREAD

**Issue by JonathanSun** [taskforcesh/bullmq#2664]
I'm looking for conceptual clarification around a statement in the [BullMQ docs](https://docs.bullmq.io/bull/quick-guide#queues-performance) concerning queue performance:

```
Queues are relative cheap, so if you need many of them just create new ones with different names. However having too many queues can become unmanageable. Up to a dozen is normally ok.
```

Assuming the underlying Redis instance has capacity and network leeway, is there any real concern with having a large number of queues?  Why would having more than a dozen queues be undesirable?  For example, if you want to use queues to process a lightweight event system you may have a queue per event type.

**Comment by manast** [comment]
The number of queues does not affect performance, only the amount of jobs added and/or precessed. Having many queues though makes it more difficult to manage, it's analogous to having many tables in a SQL database. Sane number may be in the dozens, not in the hundreds, although it is completely possible to have if you really want to.
