### ISSUE TITLE
Queue actions taking too long

### ISSUE THREAD

**Issue by phrozen** [taskforcesh/bullmq#268]
Hey, I have a service in production that has been working fine, but right now even locally any call to `queue.add()`, `queue.getJob`, `queue.getJobs()` is taking forever (between 5-20 seconds) to complete. It is a single queue with a single worker nothing fancy. The data payloads can be high, but nothing serious.

I'm testing locally with an empty Redis DB and even on my dev environment the numbers are outrageous, even with test payloads (a few strings). I updated dependencies but this seems worse that before. Is there any regression performance any of you have been facing?

Tested with node v12.15 and v12.18
BullMQ v1.6.7 (old), v1.8.14 and v1.9
IOredis v4.17.3 (latest)

**Comment by phrozen** [comment]
Apparently the culprit were the `QueueEvents`, I naively added them for logging purposes on `completed` and `failed`. Removing them fixed all my performance issues.

**Comment by manast** [comment]
Would be interesting to know more about this, was the QueueEvents instance itself that caused the slowdowns or was the logging on the "completed"/"failed" callbacks that caused it?

**Comment by phrozen** [comment]
@manast I think it was the `QueueEvents` instance what caused the problem (or the event handling) the logs were a simple `console.log()` line inside the event handler.
