### ISSUE TITLE
Rate Limiter stops after first duration

### ISSUE THREAD

**Issue by francescov1** [taskforcesh/bullmq#269]
We are trying to setup a rate-limited worker, but are finding that only the first `limiter.duration` is executed. It seems that after the first `limiter.max` jobs are processed, the worker ignores the remainder of the jobs. I am relatively new to BullMQ so apologies if I am missing something!

Here is a simple example:

```
const connection = new IoRedis({
  port,
  host,
  password,
  enableReadyCheck: true
});

const queue = new Queue("testQueue", { connection });

const worker = new Worker(
  "testQueue",
  async job => {
    console.log(`Job ${job.name} with ID ${job.id} has been received`);
  },
  {
    connection,
    limiter: {
      max: 2,
      duration: 3000
    }
  }
);

worker.on("completed", job => {
  console.log(`Job ${job.name} with ID ${job.id} has completed`);
});

worker.on("failed", (job, err) => {
  console.log(
    `Job ${job.name} with ID ${job.id} has failed: ${err.message}`
  );
});

async function test() {
  const arr = [...Array(10).keys()]
  
  console.log("Adding jobs", arr)
  arr.forEach(async () => {
    await queue.add("test", {});
  })
}

test()

```

and here is what gets logged:

```
Job test with ID 56 has been received
Job test with ID 56 has completed
Job test with ID 57 has been received
Job test with ID 57 has completed
```

even tho we added 10 jobs.

**Comment by francescov1** [comment]
I noticed a few extra things:
- when I reran the above script, the subsequent job IDs were 66 and 67, so it seems the queue did increment the job IDs for the jobs that didnt show up

**Comment by manast** [comment]
Rate limiting is based on delayed jobs, so in order to work you need to have a QueueScheduler also: 
https://docs.bullmq.io/guide/queuescheduler
https://docs.bullmq.io/guide/jobs/delayed

**Comment by francescov1** [comment]
Would you be able to provide a working example of this? Do we simply initialize a QueueScheduler object without doing anything with it? The rate limiter section of the docs are still empty.

Our ideal setup is to achieve a "leaky bucket" rate limiter, where the rate limited jobs are processed once other jobs complete, I assume this is what the QueueScheduler allows us to do?

**Comment by manast** [comment]
I updated the documentation, please let me know if this cover your case: https://docs.bullmq.io/guide/rate-limiting

**Comment by francescov1** [comment]
Amazing, exactly what I needed. Thanks so much for the help and timely response!
