### ISSUE TITLE
[Bug]: NextJS/Webpack issue: "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by reissbaker** [taskforcesh/bullmq#2696]
### Version

5.12.1

### Platform

NodeJS

### What happened?

Webpack throws a bunch of warnings about trying to import BullMQ:

```
./node_modules/bullmq/dist/esm/classes/child-processor.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/bullmq/dist/esm/classes/child-processor.js
./node_modules/bullmq/dist/esm/classes/index.js
./node_modules/bullmq/dist/esm/index.js
./app/queues/index.ts
```

I'm pretty sure this is because there's a dynamic import statement that imports the value of an expression in `child-processor.js`, which means Webpack can't figure out what to bundle into the build.

### How to reproduce.

Using NextJS, create a file in the `app/` directory like so:

```typescript
import { Queue } from "bullmq";
export const queue = new Queue("my-queue", {
  connection: {
    // Redis connection details
  }
});
```

Then import that file anywhere else in your NextJS app, and you'll get the issue in your terminal.

### Relevant log output

```shell
Import trace for requested module:
./node_modules/bullmq/dist/esm/classes/child-processor.js
./node_modules/bullmq/dist/esm/classes/index.js
./node_modules/bullmq/dist/esm/index.js
./app/queues/index.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
This is not really a bug as dynamic imports are an actual feature in javascript, so basically the way to overcome this webpack error is within web pack itself, there must be some setting to ignore dynamic imports or things like that. I haven't worked with web pack for years so I cannot help here, maybe chatGPT could give you some hints.

**Comment by reissbaker** [comment]
So, the issue here is that Webpack is trying to tree-shake the dependencies, but it can't do that if there are dynamic imports, since that would involve solving the Halting Problem — it has no way of knowing what dependencies could be imported anymore, since it could be an arbitrary string. It's probably possible to turn off tree-shaking, but I don't think it's possible to both use tree-shaking and dynamic imports.

**Comment by manast** [comment]
It is not really the halting problem, it is just that the import is dynamic based on a string and not know at compile time, or in this case at tree shaking time. But if you just disable tree shaking in dynamic imports it should work I think (if that is possible but it seems like a quite basic feature), I mean instead of just failing completely, ignore the dynamic import.

**Comment by defrex** [comment]
While I understand the principled stance you're taking here, this error is a persistent problem for anyone using BullMQ with Next.js, which I have to assume is a non-trivial percentage of the library's users.

Perhaps it would be worth considering a solution for that reason.

**Comment by whw** [comment]
I'm seeing this also - although interestingly, it only started to happen recently i.e. I was not seeing it in early Sep. 

I'm on version 5.12.19.

**Comment by whw** [comment]
I ended up getting rid of it by adding this to `next.config.mjs`

```
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['bullmq'],
  },
...
```

**Comment by manast** [comment]
> While I understand the principled stance you're taking here, this error is a persistent problem for anyone using BullMQ with Next.js, which I have to assume is a non-trivial percentage of the library's users.
> 
> Perhaps it would be worth considering a solution for that reason.

It is not about taking a stance, is that we need to use a dynamic import or it will break for non ESM users. So if you can propose a solution that solves this issue without breaking for other users I have nothing at all against it.
