### ISSUE TITLE
Where is the API reference?

### ISSUE THREAD

**Issue by kwando** [taskforcesh/bullmq#270]
How do I find the API Reference nowadays? :upside_down_face:
![Skärmavbild 2020-09-03 kl  14 16 57](https://user-images.githubusercontent.com/891566/92113998-717a5d00-edf0-11ea-996f-6dd60c4be81f.png)

**Comment by manast** [comment]
It is not available yet for BullMQ, but I guess you are more interested in old Bull? :) https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md

**Comment by drone1** [comment]
Do you have some idea when it will be available? 

How different is it from bull?

Thank you.
