### ISSUE TITLE
[Bug] : Change rate limiting not working immediately

### ISSUE THREAD

**Issue by vnc4567** [taskforcesh/bullmq#2713]
### Version

v1.86.0

### Platform

NodeJS

### What happened?

Hello, I'm experiencing a specific behavior with BullMQ. I'm not sure if this behavior is intentional.

I have set a rate limiting on my queue, and as a result, I have several jobs that are in delayed status. When I modify the rate limiting, I have to wait for a cycle with the old rate limiting value. Then, the jobs start to dequeue according to the new rate limiting value.

Example:

I have a queue with a rate limiting of 1 job every 10 minutes. I have ten jobs in delayed status due to the rate limiting.

I change the rate limiting to 1 job every 2 minutes. I promote all the jobs that are in delayed status.

I still have to wait 10 minutes for one job to be dequeued. Then, two minutes later, another job is dequeued.

Is this behavior intentional?

P.S.: We are using version 1.86.0 of BullMQ. Perhaps this behavior is no longer present in the latest versions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @vnc4567, this is a pretty old version, could you try our latest versión, we we're improving our rate limit logic along these years

**Comment by vnc4567** [comment]
Hi @roggervalf, thank you for your answer. We'll update to the latest version.
