### ISSUE TITLE
[Bug]: debounced job lock not being removed in extended mode.

### ISSUE THREAD

**Issue by lazaroofarrill-opstalent** [taskforcesh/bullmq#2716]
### Version

5.12.9

### Platform

NodeJS

### What happened?

When debouncing job in extended mode, lock is not being deleted when the job finishes.

<img width="520" alt="image" src="https://github.com/user-attachments/assets/151db8da-e226-4b2d-bd20-2cefa14a0241">

All of the jobs corresponding to those locks have finished, yet they are not deleted.

### How to reproduce.

send a flow with the structure.

```js
 {
    queueName: 'parent_queue'
    children: [
    {
        queueName: 'child_queue',
        opts: {debounce: 'debounce_id'}
     }]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @lazaroofarrill-opstalent, I couldn't reproduce your case, you can maybe take a look at #2717 and change my test case a little bit to reproduce your issue. Btw, using debounce feature could have unexpected behavior as children cannot have more than 1 parent in our current architecture.

**Comment by manast** [comment]
@lazaroofarrill-opstalent I wonder, what is your expected behaviour when using debounce on children?

**Comment by brm-anass** [comment]
Hey guys,
I'm using Taskforce, and when I deleted waiting jobs that had a debounce id, their references in the queue under bull:queue_name:de weren't removed. So it prevented new jobs to be created.
I had to delete them manually in order to create new jobs with similar debounce id.

**Comment by roggervalf** [comment]
hey @brm-anass I'm adding a test case where I cannot reproduce your issue, could you pls take a look?

**Comment by lazaroofarrill** [comment]
> hi @lazaroofarrill-opstalent, I couldn't reproduce your case, you can maybe take a look at #2717 and change my test case a little bit to reproduce your issue. Btw, using debounce feature could have unexpected behavior as children cannot have more than 1 parent in our current architecture.

the only difference I see in that test. Is that the jobs have a parentId key and are also inside the children array. They parentId is for the same job though. Would that affect it?

**Comment by lazaroofarrill** [comment]
> > hi @lazaroofarrill-opstalent, I couldn't reproduce your case, you can maybe take a look at #2717 and change my test case a little bit to reproduce your issue. Btw, using debounce feature could have unexpected behavior as children cannot have more than 1 parent in our current architecture.
> 
> the only difference I see in that test is that my jobs have a parentId key and are also inside the children array. They parentId is for the same job though. Would that affect it?

@roggervalf
Yes. This was the issue. It would seem having the flows in the children array and also declaring a parent key behaves like having two parents. I can work around that, thank you very much.
