### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vishalsabhaya** [taskforcesh/bullmq#2723]
### Version

v5.12.10

### Platform

NodeJS

### What happened?

i don't know what happening.
i am scheduling 10 repeat job every 30 sec.

but all time single job always active & later fail. every 30 sec or 1 minute repeat job is decrease by 1 job.

### How to reproduce.

schedule 10 job
![image](https://github.com/user-attachments/assets/40088732-0239-4895-86d4-6583d6a925eb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishalsabhaya** [comment]
I understand it is not problem of bullmq. might be I run locally take pull from bull-board/ui. it cause problem.

anyone guide me on which is the stable version for monitoring ui?

**Comment by roggervalf** [comment]
hi @vishalsabhaya, our official ui is https://taskforce.sh/. If You can provide which options You are using to create those jobs we can take a look

**Comment by vishalsabhaya** [comment]
@roggervalf 
thank you for answer. is this opensorce? i want to check on my local pc.

**Comment by vishalsabhaya** [comment]
@roggervalf 
i think below? is that correct? 
https://github.com/taskforcesh/taskforce-connector

**Comment by roggervalf** [comment]
hey, no it's not open sorce. But with the connector
you posted, You can test it locally. There is a trial time to test our ui as well.
