### ISSUE TITLE
[Question] How to setup a repeatable job that only has one running instance

### ISSUE THREAD

**Issue by akshay-8d66** [taskforcesh/bullmq#2725]
Is there a way to setup a repeatable job, that only ever has one running instance, when the setup has a worker concurrency of 1+. I tried a repeatable job with debouncing. 

```
  await queue.add('testjob, {}, {
    debounce: { id: 'testjob },
    repeat: { every: 2000 }
  })
```

What I was hoping for was that when the job was running, and if it took longer than the repeat schedule, the next job would be debounced or skipped.

However, I see that new jobs are not created because of the debounce. In my setup, I use a value of `1000` for `removeOnComplete` with one worker with a concurrency of 5..

My goal is to setup a repeatable job with a frequency of 2 minutes, but if the job takes more than 2 minutes, then for the worker/s to wait for the first job to complete, or skip that run instance.

Is there a way to achieve the overall goal here?

Thanks

**Comment by manast** [comment]
What you are describing is the default behaviour of repeatable jobs. With the new API that we just released it is easier to see that so is the case: https://docs.bullmq.io/guide/job-schedulers/repeat-strategies
