### ISSUE TITLE
[Bug]: IMPORTANT! Eviction policy is volatile-lru. It should be "noeviction"

### ISSUE THREAD

**Issue by Syntamin** [taskforcesh/bullmq#2737]
### Version

5.12.10

### Platform

NodeJS

### What happened?

When using BullMQ, I encountered a ReplyError with the message: "IMPORTANT! Eviction policy is volatile-lru. It should be 'noeviction'." However, my Redis service is shared, so I can't change the eviction policy. How can I ignore this error or similar warnings?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pdipax** [comment]
Hi, we encounter the same error.

**Comment by Syntamin** [comment]
> You must use a Redis instance with the proper maxmemory policy, otherwise you will get this warning and the queues will misbehave.

If it's just a warning, is there an option to allow users to control whether the code should be forcefully interrupted? Since we're using a shared Redis cluster across several large services, we can't change the eviction policy for just one service. If I'm okay with the worst-case scenario where Redis starts evicting data, can we handle this as a warning without interrupting the code? Or do you have any other suggestions?

**Comment by Syntamin** [comment]
> > Hi, we encounter the same error.

Yes, I want to use the BullMQ module in Nest.js, but I'm encountering this error. Since I can't change the Redis cluster's eviction policy, if the module can't be used as is, I might need to wrap a custom BullMQ module myself, which seems quite troublesome.

**Comment by manast** [comment]
@Syntamin we cannot guarantee that BullMQ works correctly with a different maxmemory policy.

**Comment by nate-watkins** [comment]
Would you all be willing to accept a PR that makes this warning configurable, similar to `skipVersionCheck`? If it's as straightforward as it seems, I'd be happy to do it. We use a `volatile-lru` policy and set expirations for everything else. It would be nice to use the same Redis cluster as our application.

**Comment by manast** [comment]
@nate-watkins The problem is that with wrong maxmemory policy the queue can misbehave and we do not want intricate bug rapports because of people skipping this warning. The best way to avoid the warning is to actually make sure to use the right memory policy.

**Comment by jderose9** [comment]
> @nate-watkins The problem is that with wrong maxmemory policy the queue can misbehave and we do not want intricate bug rapports because of people skipping this warning. The best way to avoid the warning is to actually make sure to use the right memory policy.

Assuming bullmq doesn't set an expiration on the keys it creates, the behavior of the queues should be identical to `noeviction`. It seems a little odd to refer to those policies as "wrong".

**Comment by manast** [comment]
@jderose9 we use expire in several parts of BullMQ, to hold locks, for rate limiting, etc.

**Comment by manast** [comment]
so yes, they are wrong, we just want the best for our users, so to avoid any expected issues, we must tell them not to use any other maxmemory policy...
