### ISSUE TITLE
Feature parity vs bull v3

### ISSUE THREAD

**Issue by cktang88** [taskforcesh/bullmq#274]
How does this compare feature wise with the current https://github.com/OptimalBits/bull ?
Is there a roadmap for features?

**Comment by manast** [comment]
On the top of my head I think only TTL for jobs is missing on BullMQ.

**Comment by mgan59** [comment]
Stumbled into here as I'm getting alerts for my redis memory filling up.  Realizing that the Jobs/Keys in redis don't have a `TTL` set.  Also saw issue #85 mentioned.  Wanted to clarify if I need to enable something on my end or if it isn't implemented completely.

**Comment by manast** [comment]
@mgan59 TTL here does not refer to keys expiration but on TTL for a given job, i.e. if it takes more than TTL to process it should fail. What you should check to avoid filling up your redis instance is the removeOnComplete/removeOnFailed options: https://docs.bullmq.io/guide/jobs/fifo

**Comment by mgan59** [comment]
@manast aahh perfect, thanks for clarifying.  And the link to the document.  This helps a bunch and should solve my key buildup.  👍

**Comment by adamreisnz** [comment]
@manast any progress on the TTL feature?

**Comment by manast** [comment]
@adamreisnz I created a new issue for it: https://github.com/taskforcesh/bullmq/issues/677
