### ISSUE TITLE
Add or remove cron to/from RepeatOptions type.

### ISSUE THREAD

**Issue by Feelw00** [taskforcesh/bullmq#2743]
I was analyzing RepeatableJob for issue tracking when I came across the following logic.

```typescript
// src/classes/repeat.ts
async addNextRepeatableJob<T = any, R = any, N extends string = string>(
  name: N,
  data: T,
  opts: JobsOptions,
  skipCheckExists?: boolean,
): Promise<Job<T, R, N> | undefined> {
  // HACK: This is a temporary fix to enable easy migration from bullmq <3.0.0
  // to >= 3.0.0. TODO: It should be removed when moving to 4.x.
  const repeatOpts: RepeatOptions & { cron?: string } = { ...opts.repeat };
  repeatOpts.pattern ??= repeatOpts.cron;
  delete repeatOpts.cron;

  ...

}
```

Based on the comments in this logic, it appears to be code that was temporarily added to support the cron parameter in the options for RepeatableJob.

To verify this, I checked previous versions and found that the cron parameter was used up until version 2.4.0, but starting from version 3.0.0, it was changed to use the pattern parameter.

It is expected that in version 3.1.2, the above code was temporarily added to support the cron parameter for compatibility with previous versions.

If the cron parameter is going to be supported continuously, wouldn't it be better to add the cron parameter to the RepeatOptions type and remove the comments instead of keeping the current code?

**Comment by roggervalf** [comment]
hi @Feelw00 it will be removed in v6, as pattern is the option that should be used in new version
