### ISSUE TITLE
follow semver for releases

### ISSUE THREAD

**Issue by croconut** [taskforcesh/bullmq#2755]
**Is your feature request related to a problem? Please describe.**
i recently was unable to perform a patch update due to a breaking change in #2719 following semver would prevent this.

**Describe the solution you'd like**
clear deprecation warnings and/or bumping breaking changes to major version releases. 

**Describe alternatives you've considered**
freezing the version. im updating the code right now, but i would have had an outage if i only used colons on prod. fortunately my dev vs prod is nearly identical wrt this library. that said, now im tempted to add a test suite run with NODE_ENV = production lol

i dont know what else would randomly break on a patch, colons in the queue name was i think the only non-standard thing we do. i would recommend that experimental features not get bugfixes that break other things in a non-major update though.

**Comment by manast** [comment]
We follow semver as carefully as we can, but sometimes as we are humans and it is not trivial to make tests for not breaking backwards compatibility, a breaking change may inadvertently creep in. In fact we have been using "semantic-release" for years. All PRs are manually reviewed and we provide instructions on how to upgrade to new versions: https://docs.bullmq.io/guide/migration-to-newer-versions
