### ISSUE TITLE
Update BullMQ to Support semver 3.0 Compatibility

### ISSUE THREAD

**Issue by Priluka** [taskforcesh/bullmq#2765]
I noticed that BullMQ (2.9.3) still uses semver >= 2.13.0, < 3. With semver 3.0 released in April 2023, this creates conflicts with other libraries requiring semver >= 3.0, causing integration issues.

**Comment by manast** [comment]
How can that be? "semver" is not a peer dependency in BullMQ, so it is private to BullMQ and should not conflict with any other libraries.

**Comment by manast** [comment]
Furthermore the semver version used in BullMQ  is  "^7.5.4"

**Comment by Priluka** [comment]
Thanks for your reply! The issue is with the Python version of BullMQ, which still specifies semver >= 2.13.0, < 3.0.0.

**Comment by Priluka** [comment]
@manast , any comment on this ?

**Comment by manast** [comment]
I guess we need to upgrade the dependency then. If you can you could create a PR with this change and I would gladly merge it.

**Comment by Priluka** [comment]
I attempted to make the necessary changes, but I encountered some issues with running the tests on my local setup. Given your expertise, would it be possible for you or someone on the team to handle the upgrade? I believe this would ensure the changes are properly tested and integrated
