### ISSUE TITLE
[Bug]: processBy field missing in job data despite worker name configuration

### ISSUE THREAD

**Issue by dzmm** [taskforcesh/bullmq#2773]
### Version

5.12.10

### Platform

NodeJS

### What happened?

When creating a new worker with a specified name, the `processBy` field is not being set in the job data stored in Redis. This prevents tracking which specific worker machine processed a job, making it difficult to identify and analyze problematic workers.

### How to reproduce.

1. Create a new worker with a specified name:

```typescript
const worker = new Worker<T, R, N>(queueName, wrappedProcessor, { 
  ...opts, 
  name: workerName,
  metrics: {
    maxDataPoints: MetricsTime.TWO_WEEKS,
  },
});

2. Process jobs using this worker
3. Inspect the job data in Redis

### Relevant log output

```shell
On job data, this is all we got.
name: Ttsv2Config
atm: 1
processedOn: 1726625871379
data: {"text":""}
priority: 0
timestamp: 1726625871371
delay: 0
ats: 1
finishedOn: 1726625881199
returnvalue: {"uploadJobId":"1938","..."}
opts: {"backoff":{"delay":100...}
pb: tts-cosy-RUNPOD-wg5...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dzmm** [comment]
still have no solution for this, we can not see any worker information even from taskforce.sh

![image](https://github.com/user-attachments/assets/6b862fc4-45e6-4007-a458-e01988447fd2)

**Comment by roggervalf** [comment]
hi @dzmm processedBy is saved as pb, looks like taskforce ui is missing to show that value cc: @manast

**Comment by dzmm** [comment]
> hi @dzmm processedBy is saved as pb, looks like taskforce ui is missing to show that value cc: @manast

Hi @roggervalf  I don't think that is the reason, even on redis we cannot see which worker processing/processed it

![image](https://github.com/user-attachments/assets/51f37ea0-da98-433e-9031-52e0f70930f8)

**Comment by manast** [comment]
@dzmm in the code you pasted in the beginning of the issue I can see a "pb" field actually. @roggervalf is right in that this data is still not being shown in Taskforce. Prioritising this up now.

**Comment by dzmm** [comment]
I can confirm pb does exist in Redis date ,it's just not showing up in taskforce UI.  Thank you for helping!

**Comment by manast** [comment]
This has been released now.
