### ISSUE TITLE
[Feature] Do not allow removing a delayed job that is part of a repeatable meta job.

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq#2790]
**Is your feature request related to a problem? Please describe.**
If a delayed job that is representing the next iteration in a repeatable job gets deleted by mistake, the repeatable job will stop repeating with no other solution than re-adding the repeatable job again.

**Describe the solution you'd like**
An exception or error should be raised if we try to remove a delayed job using the method for removing jobs or any other that could indirectly remove a delayed job. The only way to remove a delayed job that is part of a repeatable job should be by removing the repeatable job alltogeher.

**Describe alternatives you've considered**
None

**Additional context**
A user reported that their repeatable jobs stopped working and the delayed job associated to the repeatable job was missing. We should make sure that this does not happen by a mistake of the user in any case.

**Comment by erenkurnaz** [comment]
I was able to reproduce the problem, and I’m sharing the steps I followed below as I think they might help with the solution:

 1. A repeated job was created.
![repeated-job-added](https://github.com/user-attachments/assets/fd2e30f4-ed6d-4858-b1ab-e8e696201e84)
 2. The job was successfully completed 3 times.
![final-result-in-task-force](https://github.com/user-attachments/assets/03aeab95-5a71-4de1-8c51-210d613c32d9)
 3. For a reason we don’t understand, after the 3rd job was completed, a ‘drained’ event occurred. As a result, the repeated job in ‘delayed’ is being deleted. Count of completed jobs changing sometimes it completes 6-10 jobs, but at the end removes repeated job.
![stream-logs-drained](https://github.com/user-attachments/assets/642eb311-454b-4f94-9dd6-93627a8ef925)

Additionally, the situation on the Redis key side is as follows:
![final-result-in-redis](https://github.com/user-attachments/assets/8f5f75db-d547-406c-9a6b-7b6585b77652)

**Comment by manast** [comment]
I wonder, what is the settings you are using for this repeatable job, like what cron expression or every interval?

**Comment by manast** [comment]
btw, the "drained" event is just triggered when there are no jobs left in the queue, it is not the reason for the next delayed job to disappear or to not be created. Furthermore, the next iteration delayed job is created *before* the current job starts processing, so it should not matter what happens to the job that is processed, the next delayed job should be there. It would be interesting to see what repeat options you are using to see if we can spot something there.

**Comment by manast** [comment]
By any chance, can you reproduce this problem locally?

**Comment by manast** [comment]
I also wonder if you are doing things like updating repeatable jobs options or data.

**Comment by manast** [comment]
This is now completed. If you still have an issue lets open a new issue as this feature of not allowing delayed jobs that are part of job scheduler is now ready.
