### ISSUE TITLE
[Bug]: Prioritized jobs doesn't process before non-prioritized ones

### ISSUE THREAD

**Issue by BastienGenin** [taskforcesh/bullmq#2798]
### Version

v3.5.6

### Platform

NodeJS

### What happened?

Hello, I've encountered a problem with prioritized jobs that I can't figure out.

Let's say I have a queue full of many jobs waiting to be processed by the same worker in the same queue, all these jobs have a priority of 2.

When I add a new job to the queue with a non-specified priority (the highest priority possible if I've read the documentation correctly), it doesn't run immediately after the end of the process of a job with a priority of 2. Could you explain why this is?

Is there a connection with the concurrency settings of my worker? I didn't specify a concurrency when I created it.

```ts
// Queue
new Queue(
  "test",
  { connection: { ... } }
)

// Worker
new Worker(
  "test",
  () => { /* my processor code here */ },
  { 
    connection: { ... },
    lockDuration: 300000,
    maxStalledCount: 3,
    stalledInterval: 60000,
  }
)
```

Should I just upgrade to bullMQ 4/5.X.X ?

Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BastienGenin** [comment]
Thanks for your quick response.

I will bump BullMQ to v5, write some test and keep you updated if I encounter this again.

**Comment by roggervalf** [comment]
hi @BastienGenin, prioritized state was separated from wait state since v4 https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/changelogs/changelog-v4.md#400-2023-06-21, the behavior that you are facing is normal in old versiones from 1 to 3

**Comment by manast** [comment]
Closing as this should not be an issue in newer versions.
