### ISSUE TITLE
Feature Request: waitStartedOn

### ISSUE THREAD

**Issue by ccollie** [taskforcesh/bullmq#28]
I've been toying with an admin dashboard for Bull, with the emphasis being performance metrics (specifically latency and wait times).

For the latter, I've been listening to the _**waiting**_ event, then writing the current time to the job's data. Then on the transition to _**active**_ i calculate the difference between the stored time and the current timestamp.

It seems that this and similar use cases would make a _**waitStartedOn**_ job field a useful addition.

**Comment by manast** [comment]
maybe you missed the provided fields?: https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L22-L24

**Comment by ccollie** [comment]
Maybe i'm not understanding. My use case is specifically to find a way to track how long a job is in the queue before being picked up by a worker. Would that mean _**timestamp**_ - _**processedOn**_ when job.state === _'active'_ ?

**Comment by stansv** [comment]
@ccollie yes, there is a `timestamp` field filled with epoch time (milliseconds) by calling Date.now() just before adding job entry into queue (if you didn't provide your own timestamp using job options); processedOn is available once job is taken by a worker to process. So, yes, by calculating `processedOn - timestamp` you'll get exact value of how long job was in the queue.
