### ISSUE TITLE
[Feature / Question] Updating data for next repeatable job iteration

### ISSUE THREAD

**Issue by blhutchings** [taskforcesh/bullmq#2802]
**Is your feature request related to a problem? Please describe.**
The job has rolling data,  a resourceID (static) and a etag (rolling). The job gets the resource from an api with the etag and if its not a 304 (Not Modified), it does something, but now the etag has changed because the resource did. So I would like the next iteration of that job to use the new etag

**Describe the solution you'd like**
job.updateNextJobData or something along those line, where the next delayed job will have the new data

**Describe alternatives you've considered**
Saw the new Job Schedulers api so I am hoping something is helpful in that.
So far I have tried to manually updating the next jobs metadata with scan from within the currently running job, 
Using the normal updateData just updates the current jobs but not the next
Might try to just store the data in the job metadata next

**Comment by manast** [comment]
If you call ```upsertJobScheduler``` with a different job template, then the next job will use that data and options, as in the examples here: https://docs.bullmq.io/guide/job-schedulers/repeat-strategies
Here the API: https://api.docs.bullmq.io/classes/v5.Queue.html#upsertJobScheduler

This should do what you want right?

**Comment by blhutchings** [comment]
Awesome! That worked perfectly! Thank you!
