### ISSUE TITLE
[Bug]: commands folder for Scripts initializing is missing on v2.10.0 install

### ISSUE THREAD

**Issue by abarreaux** [taskforcesh/bullmq#2868]
### Version

v2.10.0

### Platform

Python

### What happened?

Hi everyone, first time posting an issue here, let me know if I can help in making the post better somehow.

When installing v2.10.0 with pip v24.0, the commands files are not included in the bullmq folder and I get 

FileNotFoundError: [Errno 2] No such file or directory: '*****/venv/lib/python3.12/site-packages/bullmq/commands/addStandardJob-8.lua'

Seems to be an old issue (https://github.com/taskforcesh/bullmq/issues/1952) coming back.

### How to reproduce.

Any new install of v2.10.0 on my end ends the same way.

Was fixed by downgrading to v2.9.4.

### Relevant log output

![image](https://github.com/user-attachments/assets/116c84d3-a120-4e0e-8732-37d865777270)

![image](https://github.com/user-attachments/assets/77cce454-98f0-40d9-b70f-b7b2d3980843)

![image](https://github.com/user-attachments/assets/b8c19f39-9ab8-43e7-a9ed-e1189a3a3924)

![image](https://github.com/user-attachments/assets/83bc8b96-d32a-48d4-aa41-2b7d040b6bac)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lanpeisi** [comment]
Same issue here with upgrading to 2.10.0

File "/usr/local/lib/python3.11/site-packages/bullmq/scripts.py", line 78, in getScript
    file = open(f"{basePath}/commands/{name}", "r")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/bullmq/commands/addStandardJob-8.lua'
