### ISSUE TITLE
[Bug]: Duplicate job scheduler tasks

### ISSUE THREAD

**Issue by noe-charmet** [taskforcesh/bullmq#2876]
### Version

5.21.2

### Platform

NodeJS

### What happened?

We use BullMQ Job Scheduler to trigger frequent tasks (multiple per second). We leverage the `schedulerId` to ensure one task is only defined once. We have however observed that on some occasions tasks are not properly deduplicated and we end up with multiple instances of the repeated task. In our specific case we trigger `upsertJobScheduler` at startup and have seen this ocure when having crash loops causing many restarts in a short period of time.

### How to reproduce.

I have written this JS script which pushes BullMQ to its limits. It goes beyond what we expect from it, but provides a reliable way to reproduce the bug that we are reporting here. Run the script and wait a few dozen seconds, you should see the counter for `waiting` tasks  go up (restarting the script seems to help too).

I've tried deep diving into the BullMQ code and debug logging at various places, but I'm yet unsuccessful in identifying the root cause of this duplication.

When there is no `Worker` involved, the duplication does not happen. I'm therefore suspecting that it could be triggered when the task is being processed by the worker when the upsert happens.

```js
const {Worker, Queue} = require('bullmq');
const {setTimeout, setInterval} = require('timers/promises');

const connection = {
  host: '127.0.0.1',
  password: 'password',
};

async function run() {
  const queue = new Queue('test', {
    connection,
  });

  await queue.waitUntilReady();

  const worker = new Worker(
    'test',
    async () => {
      await setTimeout(250);
    },
    {connection},
  );

  await worker.waitUntilReady();

  for await (const _ of setInterval(50)) {
    console.log('###');
    await queue.upsertJobScheduler('test', {
      every: 100,
    });
    console.log('active', await queue.getActiveCount());
    console.log('waiting', await queue.getWaitingCount());
    console.log('delayed', await queue.getDelayedCount());
  }
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noe-charmet** [comment]
Just tested with the deprecated Repeatable job interface using a `key` and the issue does not happen under these conditions.

```js
const {Worker, Queue} = require('bullmq');
const {setTimeout, setInterval} = require('timers/promises');

const connection = {
  host: '127.0.0.1',
  password: 'password',
};

async function run() {
  const queue = new Queue('test', {
    connection,
  });

  await queue.waitUntilReady();

  const worker = new Worker(
    'test',
    async () => {
      await setTimeout(250);
    },
    {connection},
  );

  await worker.waitUntilReady();

  for await (const _ of setInterval(50)) {
    console.log('###');
    await queue.add('test', undefined, {
      repeat: {every: 100, key: 'test'},
    });
    console.log('active', await queue.getActiveCount());
    console.log('waiting', await queue.getWaitingCount());
    console.log('delayed', await queue.getDelayedCount());
  }
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
```

**Comment by paulsc54** [comment]
Hi,
Just a quick update—we’re encountering the same issues after migrating from the repeatable setup. By design, our API can restart regularly, but as @noe-charmet mentioned, if we experience too many restarts in a short timeframe, we end up with multiple delayed jobs for the same repeatable task.

I've attached a screenshot showing a job that frequently duplicates, along with the options for the first two instances below.
<img width="1214" alt="Screenshot 2024-11-05 at 13 40 33" src="https://github.com/user-attachments/assets/549dbfe2-8e08-47bb-a1b1-4097d424e242">

```
{
  "attempts": 5,
  "prevMillis": 1730810589509,
  "removeOnComplete": {
    "age": 600,
    "count": 100
  },
  "removeOnFail": {
    "age": 600,
    "count": 100
  },
  "repeat": {
    "offset": 31500,
    "count": 14,
    "every": 240000
  },
  "jobId": "repeat:rental_partner_confirmation_email:1730810589509",
  "timestamp": 1730810349524,
  "delay": 239985
}

{
  "attempts": 5,
  "prevMillis": 1730810589488,
  "removeOnComplete": {
    "age": 600,
    "count": 100
  },
  "removeOnFail": {
    "age": 600,
    "count": 100
  },
  "repeat": {
    "offset": 36846,
    "count": 114,
    "every": 240000
  },
  "jobId": "repeat:rental_partner_confirmation_email:1730810589488",
  "timestamp": 1730810349510,
  "delay": 239978
}
```

**Comment by jordan-loeser** [comment]
Encountering the same issue here.

**Comment by manast** [comment]
I have a grasp on why this is happening particularly when using very tight repetitions and many distributed calls to upsertJobScheduler. I am designing a solution for this now.

**Comment by Marsup** [comment]
@manast Hi, sorry but how do we fix it when it's already there? I have some of those jobs, and can't remove them using standard remove, it causes `Job X belongs to a job scheduler and cannot be removed directly` errors.

**Comment by manast** [comment]
@Marsup the best is to remove the scheduler and add it again.

**Comment by manast** [comment]
ah ok, I get it. You must remove the job scheduler first, then the delayed jobs that belonged to that job scheduler, then add a new job scheduler.

**Comment by manast** [comment]
> I tried this, but I'm left with orphan jobs, but apparently still attached. Sorry but since I don't know how it got in this state, I don't know how to provide a reproduction. Is there a way to force the removal without using obliterate?

Btw, this should not be able to happen with the latest release, so I assume this happened using an older version.

**Comment by Marsup** [comment]
I get this error even without job schedulers.

Here's the snippet:
```ts
for (const scheduler of await queue.getJobSchedulers()) {
  await this.queue.removeJobScheduler(scheduler.id);
}

for (const job of await queue.getDelayed()) {
  await this.queue.remove(job.id);
}
```

**Comment by manast** [comment]
I see. Seems like the delayed job since it has a reference to the scheduler still thinks it is part of the scheduler... let me think a solution for this.

**Comment by manast** [comment]
Something like this for every job to delete should work:
```ts
for (const job of await queue.getDelayed()) {
  const jobKey = this.queue.toKey(job.id);
  const client = await this.client;
  await client.hdel(jobKey, "rjk");
  await this.queue.remove(job.id);
}
```

**Comment by essensx** [comment]
Why is this closed? I only see workarounds, not an actual fix
