### ISSUE TITLE
[Bug]: Duplicate delayed jobs on repeatable

### ISSUE THREAD

**Issue by samthemagicman** [taskforcesh/bullmq#2889]
### Version

5.23.0

### Platform

NodeJS

### What happened?

There are multiple of the same repeatable job in the delayed set when I only expect there to be one of each. Because of this, jobs can run much more frequently than the desired repeatable time. I expect that, with a repeatable job, the job will repeat at X repeat time.

This behaviour happens when the worker stops and starts. I haven't moved to job schedulers because of #2876 but it was happening before as well.

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/537e7884-2859-4107-984b-f272479eded5">
The expected result is only 1 of each repeatable job with IDs 1 and 2

I thought deduplication might be the fix, but it seems to break stop repeating jobs. I might not be fully understanding deduplication.

Is there something I'm missing? I basically only want each repeatable job to run only every X minutes and no more, but I get a bunch of duplicate delayed jobs when I restart my server.

### How to reproduce.
```javascript
// Replace 'connection' with redis connection.
// Not exactly my prod code, but it ends up doing the undesired behavior.
const queue = new Queue("test", {
  connection,
  defaultJobOptions: {
    removeOnComplete: 100, // Keep 100 completed jobs
    removeOnFail: 200,
    backoff: {
      type: "fixed",
      delay: 10000,
    },
  },
});

export const addJobToQueue = async (
  watchlistId: number,
  repeatTime: number,
  startDate: Date = new Date(),
) => {
  await queue.add(
    "test_" + watchlistId,
    {},
    {
      repeat: {
        every: repeatTime,
        immediately: true,
        startDate,
        key: watchlistId.toString(),
      },
      jobId: watchlistId.toString(),
    },
  );
};

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

type w = Worker;
async function startWorker() {
  const worker = new Worker<{}>(
    queueName,
    async (job) => {
      // delay
      await delay(1000);
      console.log("job completed", job.id);
      return;
    },
    {
      connection,
      concurrency: 4,
    },
  );

  await worker.waitUntilReady();

  return worker;
}

(async () => {
  let worker = await startWorker();
  queue.obliterate({ force: true });
  addJobToQueue(1, 5000);
  addJobToQueue(2, 5000);
  await worker.pause();
  await delay(6000);
  await worker.resume();
  addJobToQueue(1, 5000);
  addJobToQueue(2, 5000);
})();
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
If you upgrade to version [5.25.6](https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/changelog.md#5256-2024-11-11) and use the new api upsertJobScheduler it should work properly. Let me know how it goes.

**Comment by samthemagicman** [comment]
> If you upgrade to version [5.25.6](https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/changelog.md#5256-2024-11-11) and use the new api upsertJobScheduler it should work properly. Let me know how it goes.

Yes, 5.25.6 with upsetJobScheduler fixed it. Thanks!
