### ISSUE TITLE
[Bug]: removeOnComplete doesn't remove jobs form Redis

### ISSUE THREAD

**Issue by fastndead** [taskforcesh/bullmq#2890]
### Version

v5.13.0

### Platform

NodeJS

### What happened?

I see a consistent raise of memory usage in Redis after every run of jobs using Bull. I have all of the queues configured with `removeOnComplete` and `removeOnFail`, but the job data doesn't get removed from the queue

here's the graph of the Redis memory usage:
<img width="298" alt="image" src="https://github.com/user-attachments/assets/6dd3335b-2494-4405-9c95-645bf530b97d">

You can see how data is being added but not being removed. I don't understand what am I doing wrong, removeOnComplete setting seems to be the exact setting that should control it.

I use `@nestjs/bullmq`, and register my queues as such:
```ts
    BullModule.registerQueue(
      {
        name: QUEUE.name,
        defaultJobOptions: {
          removeOnComplete: true,
          removeOnFail: true
        },
      },
```

After one run I see the Bull keys for the completed jobs in Redis with the data just taking space with no usage. 
 

### How to reproduce.

1. Register a queue with removeOnComplete and removeOnFail set to true
2. Run a job with some job data
3. See the keys of a job containing the job data in Redis

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Have you confirmed that the completed and failed jobs are indeed not being removed?  Also, are you using the module correctly? according to the modules documentation you should use "fromRoot" to specify the default job options: https://docs.nestjs.com/techniques/queues#bullmq-installation
Btw, it is more memory efficient to also specify the removeOnComplete/Fail on the workers instead of the producers.

**Comment by fastndead** [comment]
@manast hi! Thank you for your response!

> Have you confirmed that the completed and failed jobs are indeed not being removed

yea, I see that the jobs have "completed" and "failed" in the queue, but the jobs are still there

> Also, are you using the module correctly? 

Yes, the `fromRoot` is needed to init the Bull for the app. I did that for my App module naturally. Have I not done this the Bull would not work in the app at all.

> it is more memory efficient to also specify the removeOnComplete/Fail on the workers instead of the producers.

Thank you for that insight! I didn't know that and thought this could only be configured on the queue. I added `removeOnComplete/removeOnFail` to the Worker options and now the jobs are being deleted.

Couple of things though:

1. Types for workerOptions are weird, they do not support boolean values for `removeOnComplete/removeOnFail`. Idk, maybe it's expected, but they accept KeepJobs type, which could be configured to just remove jobs immediately, I'm just not sure if it's expected behaviour 
2. The jobs in the Flow that have failed children are not being deleted. Not sure if that is expected also.

My concern was the growing memory usage because jobs kept the actual data in Redis and while settings on workers work, the settings on queues don't seem to work, so it's probably still a bug?

**Comment by manast** [comment]
We are not the maintainers of the NestJS module so I don't know about their types, in BullMQ everything is properly typed and documented: https://api.docs.bullmq.io

**Comment by fastndead** [comment]
@manast `WorkerOptions` type is a part of `bullmq`, not NestJS package

I get it that it makes sense that it wouldn't accept boolean though, so that's probably by design.

the real question is why is this setting in `defaultJobOptions` not working?

**Comment by manast** [comment]
> @manast `WorkerOptions` type is a part of `bullmq`, not NestJS package
> 
> I get it that it makes sense that it wouldn't accept boolean though, so that's probably by design.
> 
> the real question is why is this setting in `defaultJobOptions` not working?

Most likely because, as I mentioned above, you are setting it in the wrong place. According to the documentation it is an option of forRoot and not on registerQueue.

**Comment by fastndead** [comment]
@manast Not to be argumentative, but I don't think you either read my reply about `forRoot` and didn't go through NestJS package documentation. 

Default Job options are set on the queues, not on the Bull NestJS Module. This is supported by the typing system and by your own link to nestjs docs. 

Granted, this could ne NestJS/bull bug, I still think it's not very couth to to close the ticket like that without even understanding the problem
