### ISSUE TITLE
[Bug]: cleaning 7m records crash elasticache

### ISSUE THREAD

**Issue by or-opus** [taskforcesh/bullmq#2893]
### Version

v3.6.2

### Platform

NodeJS

### What happened?

Hi
We are using BullBoard with bullMq which is a life saver.

We paused a queue for couple of hours and during that time it got full with 7 million tasks (in paused), so we decided to clean those 7m so we wont have to process them.

Once trying to clean all the paused items, our ElasticChace (AWS redis solution) instance got chocked, all our services were not able to communicate with it, neither redis insight UI as it claims that there is a blocking script thats running.

After 10 min it came back to life, after our entire data got lost/deleted (assuming the EC instance was crashed)

Any idea what can cause that? Any scale limitations you are aware of?

Thx!

### How to reproduce.

gain a lot of paused items to a queue (we got 7 million) and try to clean them using clean method (as bull-board implemented it)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
You should report this issue in the BullBoard repo, as this is a project not maintained by us. You could try to remove using BullMQs api though or our official dashboard https://taskforce.sh

**Comment by manast** [comment]
Closing as the bug is related to how BullBoard removes the jobs.
