### ISSUE TITLE
[Bug]: Delete repeatable job

### ISSUE THREAD

**Issue by fedorstepanovv** [taskforcesh/bullmq#2895]
### Version

5.18.0

### Platform

NodeJS

### What happened?

I create repeatable jobs for users to send daily reminders. If I want to update a repeatable job or simply delete it, it doesnt seem like a straightforward process. Looking at current api, there is a method called removeJobScheduler where i need to pass a schedulerId. It seems like in order to get the correct schedulerId, i need to first call getSchedulers. It doesnt seem efficient, considering the potential amount of jobs. I was wondering if there is a way to delete repeatable jobs easily. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
You just choose your id when you upsert your scheduler https://api.docs.bullmq.io/classes/v5.Queue.html#upsertJobScheduler

**Comment by fedorstepanovv** [comment]
> You just choose your id when you upsert your scheduler https://api.docs.bullmq.io/classes/v5.Queue.html#upsertJobScheduler

Thanks for the suggestion, it works fine. It seems like docs are a little bit outdated when it comes to repeatable jobs. https://docs.bullmq.io/guide/jobs/repeatable

**Comment by manast** [comment]
You can still use the old API so not really outdated in that sense. The guide for the new API is here: https://docs.bullmq.io/guide/job-schedulers
