### ISSUE TITLE
Consider use "$" instead of "0-0" as default lastEventId

### ISSUE THREAD

**Issue by stansv** [taskforcesh/bullmq#29]
Catching any event since the beginning of time would be helpful feature in some cases, but I believe the most users would expect QueueEvents to work very similar to global events in Bull3.

Also, what I found not very obvious is that one should call init() on QueueEvents to start receiving any events.. is there any reason to not to place init() call inside class constrictor?

PS. Looks like instead of `this.client = await this.connection.init();` line in init() method we can just call `super.waitUntilReady()` as it's done in QueueScheduler.

**Comment by manast** [comment]
So the problem is that in constructor you cannot run asynchronous code with async/await, we could use promises but then we cannot throw exceptions...

**Comment by manast** [comment]
btw, we can use $ but then we many tests will fail because then you really need to make sure that you start listening before you start emitting events... but you are right this can be problematic in other cases.

**Comment by stansv** [comment]
I agree that constructor itself cannot throw any exceptions; successful object construction ensures consistency of object's data. Consistency of data does not related to external things like connections. Nothing prevents us to initiate the background connection process in constructor, and provide a callback there to catch connection promise reject (to avoid node warnings; we can even emit 'error' event as it was in Bull3 in case of Redis failures.). Users would still have an ability to await until connection will become ready.

Regarding use of $ as default, maybe it would be better to set explicitly 0-0 in every test where it's needed?

**Comment by manast** [comment]
I can change to $ as default.
I think the constructor should be free of side effects or start side effects, so thats why I prefer to init explicitly the connection. I want to move away from "magic" and make things more explicitly in v4. In my experience, to much magic behind the scenes just creates github issues :).

**Comment by stansv** [comment]
I'd try to enforce consistent initialization strategy in every class. Making constructors not having any side effects is basically a good idea. I think it is good if library user would first wait until bullmq object is ready and only then start call its methods. I know that Bull3 have a couple of places which may fail until you explicitly await for queue.isReady() method first, initially intended for internal use. But now it looks for me that we does not have consistent behavior everywhere.

For example,

- QueueBase constructor is already have such side effects since we call RedisConnection.init() here.
- In constructor of Queue class we also call waitUntilReady() now in your new branch 😃
- Finally, constructor of Worker class calls run(), which also have side effects (i.e. creating Redis connection).

Also I don't feel a good logical distinction between init() and waitUntilReady() methods, both returns promise signaling about ready state.

PS In QueueEvents we can just do super.waitUntilReady() instead of `this.client = await this.connection.init();` in init() method. Like in QueueScheduler, for example.

**Comment by manast** [comment]
so I tested to run the tests having $ as default, and 3 tests fails:
![image](https://user-images.githubusercontent.com/95200/65719621-73975000-e0a6-11e9-98e6-ab8db3e1a713.png)

So maybe better you take care of this issue :)

**Comment by manast** [comment]
Regarding you remarks, you are right, you will notice that one thing is what I say, then I do differently in practice, I make many mistakes :).
But in general I want to follow that pattern, so I will try to make the constructors side effects free.

**Comment by manast** [comment]
I implemented the xtrim now, just a couple of tests and it is ready to go.

**Comment by manast** [comment]
This is done.
