### ISSUE TITLE
[Bug]: Can't apply delay to child jobs in Flow

### ISSUE THREAD

**Issue by ssafayet** [taskforcesh/bullmq#2909]
### Version

5.15.0

### Platform

NodeJS

### What happened?

Hi, I am adding some child jobs to a Flow with delay as an option but delay is not applying. 

Here is a sample Data pass to Flow Producer.

```json
{
   "queueName":"queue1",
   "name":"job1",
   "opts":{
      "removeOnComplete":true
   },
   "children":[
      {
         "name":"child1",
         "queueName":"queue2",
         "opts":{
            "removeOnComplete":true,
            "delay":10000
         }
      }
   ]
}
```

Notice the delay as an option in child job? It is not working and it is executing instantly. How to apply delay to child jobs inside Flow. 

Another follow up question is if I pass delay to parent job's options, child job is still being run instantly - only parent job is being delayed. Is this a desired behavior?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @ssafayet I couldn't reproduce your case, children are added into delayed state. Please try to create a reproducible test case, you can use my pr as a reference. For your second question:
> if I pass delay to parent job's options, child job is still being run instantly - only parent job is being delayed. Is this a desired behavior?

Parents are moved to waiting-children as soon as they are added, but if they contain a delay, after all children are finished, they are moved to delayed. You can refer to our architecture documentation https://docs.bullmq.io/guide/architecture

**Comment by ssafayet** [comment]
Yes, sorry, my bad. The delay was passed as a string instead of an integer, which is why it failed. It was a string because it came from an environment variable. Thanks!
