### ISSUE TITLE
[Bug]: upsertJobScheduler does not publish data

### ISSUE THREAD

**Issue by AhmedSKBHL** [taskforcesh/bullmq#2915]
### Version

v5.27.0

### Platform

NodeJS

### What happened?

Job.data field is an empty object when job is received by processor

### How to reproduce.

await queue.upsertJobScheduler(
			jobId,
			{ pattern: '*/20 * * * * *' },
			data,
		);

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AhmedSKBHL** [comment]
sorry, it was an error from my side

**Comment by manast** [comment]
It works, but you need to pass the correct arguments: ```ts
  it("should return a valid job with the job's options and data passed as the job template", async function () {
    const repeatOpts = {
      every: 1000,
    };

    const job = await queue.upsertJobScheduler('test', repeatOpts, {
      data: { foo: 'bar' },
    });

    expect(job).to.be.ok;
    expect(job!.data.foo).to.be.eql('bar');
    expect(job!.opts.repeat!.every).to.be.eql(1000);
  });
```

Your code above should have given you a compiler error ...

**Comment by AhmedSKBHL** [comment]
@manast, yeah my bad the issue is on my side, sorry i'm working on legacy project, there's a layer on the top of the queue that hided the error,
thanks a lot for fast reaction
