### ISSUE TITLE
How to Delay to jobs, when using "queue.addBulk()"

### ISSUE THREAD

**Issue by App-developer-269** [taskforcesh/bullmq#2916]
### How to add delay to all jobs while using addbulk 
```
const name = 'jobName';
const jobs = await queue.addBulk([
  { name, data: { paint: 'car' } },
  { name, data: { paint: 'house' } },
  { name, data: { paint: 'boat' } },
]);
```

**Comment by manast** [comment]
Yes it does, you need to follow the interface hierarchy from BulkJobOptions -> JobOptions -> BaseJobOptions. Aren't you using typescript? you should get autocompletion and compiling errors.

**Comment by App-developer-269** [comment]
@manast , Thank you.
