### ISSUE TITLE
[Bug]: ExtractNameType helper is failing strict type check error

### ISSUE THREAD

**Issue by sg1705** [taskforcesh/bullmq#2931]
### Version

5.26.1

### Platform

NodeJS

### What happened?

Starting 5.26.1 , Queue.add() method is failing argument type check. Getting this error:

```
Type error: Argument of type 'string' is not assignable to parameter of type 'ExtractNameType<T, string>'.
```

I am using a generic to create a BaseQueue<T> (where T is the job data type). Job name is string and it should all work, but it isn't.

### How to reproduce.

Write a queue wrapper that takes generics, and then try to compile with strict type checking.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Could you please provide the complete code to reproduce it?

**Comment by lukas-becker0** [comment]
@manast 

E.g. this code:

```typescript
import { Queue } from 'bullmq';
import Redis from 'ioredis';

const queueName = 'test';

async function test<JobPayload extends Record<string, any>>() {
  const ioRedis = new Redis({
    host: 'localhost',
    port: 6379,
    enableReadyCheck: false,
    maxRetriesPerRequest: null,
    enableOfflineQueue: false,
  });

  const queue = new Queue<JobPayload>(queueName, {
    connection: ioRedis,
  });

  const jobPayload = {
    foo: 'bar',
  };

  const job = await queue.add('__default__', jobPayload, {
    jobId: queueName + '-cron-worker-job',
    repeat: {
      every: 3000, // every 3 seconds
    },
  });
}

test();


```

**Comment by lukas-becker0** [comment]
It only works when wrapping JobPayload with Job:

```typescript

  const queue = new Queue<Job<JobPayload>, any, string>(queueName, {
    connection: ioRedis,
  });


```

**Comment by manast** [comment]
Unfortunately I think that as you are using a function with a generic (```async function test<JobPayload extends Record<string, any>>() {``` this makes typescript incapable of understanding if you are passing a Job or a JobData as the generic to the queue. So the only way that I know of is to solve it using the workaround that you proposed. I have been trying a couple of hours to find a fix that would resolve it without changes in the code but I have not been able to do so...

**Comment by lukas-becker0** [comment]
Alright fair enough, thanks for your time.
