### ISSUE TITLE
returnvalue on completed event

### ISSUE THREAD

**Issue by antirek** [taskforcesh/bullmq#294]
my worker set returnvalue
`````javascript
const worker = new Worker('validate', async job => {  
  job.returnvalue = 'test';
  console.log('job', job);
});
`````
and I see that job contain 'return value' in console
`````
  id: '6b0cc357-1f24-4725-9396-663a4e561481%1',
  progress: 0,
  returnvalue: 'test',
  stacktrace: [],
  attemptsMade: 0,
`````
but in events, which I try catch so

`````javascript
const qe = new QueueEvents('validate');
qe.on('completed', async job => {
  console.log('job', job, 'validate', 'completed');
})
`````

I see that 'returnvalue' empty
`````
job {
  event: 'completed',
  jobId: '6b0cc357-1f24-4725-9396-663a4e561481%1',
  returnvalue: null
} validate completed

`````
How I can pass 'returnvalue' into completed event?

I use bullmq npm version 1.10.0

**Comment by manast** [comment]
the return value is the value that you return in your process function, you do not need to explicitly set it on the job:
https://docs.bullmq.io/guide/returning-job-data

**Comment by antirek** [comment]
[this commit](https://github.com/taskforcesh/bullmq/commit/b564337cccc1b5e8d7f0734938616674d54fd6da#diff-023d72b1c7ef482b23b7f5afb9762846e480ef5f298dbc0382cdb97cbcfa5d35) is amazing :+1: 

great thanks, Manuel
