### ISSUE TITLE
[Bug]: Issue with updating job template data with upsertJobScheduler

### ISSUE THREAD

**Issue by erkkaha** [taskforcesh/bullmq#2940]
### Version

5.29.1

### Platform

NodeJS

### What happened?

I have problem updating data with upsertJobScheduler. 

With `pattern` the data is not updated. Data stays the same with each run.

With `every` the data is updated but for some reason the value of every is not respected
unless prevMillis is defined.

### How to reproduce.

``` typescript
import { Queue, Worker } from "bullmq";

// Create a new connection in every instance
const myQueue = new Queue("myqueue", { connection: { host: "localhost" } });

const myWorker = new Worker(
  "myqueue",
  async (job: { data: any }) => {
    console.log(job.data);
    return upsert();
  },
  { connection: { host: "localhost" } }
);

const upsert = async () =>
  await myQueue.upsertJobScheduler(
    "my-scheduler-id",
    { pattern: "*/1 * * * *" },
    //{ every: 15000 },
    {
      name: "my-job-name",
      data: { ts: Date.now() },
      opts:{
        // prevMillis: Date.now()
      }
    }
  );

upsert();
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roggervalf** [comment]
hi @erkkaha, for the second case
> With every the data is updated but for some reason the value of every is not respected
unless prevMillis is defined

it's because every option starts the first execution immediately by default when using job-schedulers

**Comment by erkkaha** [comment]
@roggervalf ok, Thanks for the reply. This seems to be the case regardless if `immediately` is used or not. Is this by design?
