### ISSUE TITLE
Documentation: API Reference Page is blank

### ISSUE THREAD

**Issue by drone1** [taskforcesh/bullmq#295]
![image](https://user-images.githubusercontent.com/6324796/96927977-2b6c7c00-14b8-11eb-863e-15880d129ccb.png)

https://docs.bullmq.io/api-reference

**Comment by joeyfigaro** [comment]
Same for most patterns currently listed in the sidebar:

https://docs.bullmq.io/patterns/producer-consumer
https://docs.bullmq.io/patterns/real-time-updates
https://docs.bullmq.io/patterns/sender-receiver
https://docs.bullmq.io/patterns/working-with-batches
https://docs.bullmq.io/patterns/idempotent-jobs

**Comment by manast** [comment]
The API reference is now accessible via the link above and auto-generated after every release. It can of course be improved, but it is there.
