### ISSUE TITLE
Fail a job without throwing an error

### ISSUE THREAD

**Issue by TNonet** [taskforcesh/bullmq#2955]
**Is your feature request related to a problem? Please describe.**
I sometimes want to fail a BQ Job (so it is retried later) without throwing an error (which is caught by my logging). I know you can throw special error types (e.g. [DelayedError](https://docs.bullmq.io/patterns/process-step-jobs#delaying)), but I am wondering if I can a job gracefully shutdown so it can be retried again

**Describe the solution you'd like**
I would want my worker callback to return a status/bool indicating if it should count as a success or failure 

```
const worker = new Worker(
  'queueName',
  async (job: Job, token?: string) => {
    return false; // Job failed but I don't want to throw an error
    },
  { connection },
);

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by manast** [comment]
We are too much invested in the concept that exceptions are what marks jobs fail, so at this point we just cannot change this fundamental behaviour. I am sure there are workarounds that would help you solve you specific use case.
