### ISSUE TITLE
[Bug]: Workers not working after redis reconnecting, even if ioredis is able to reconnect.

### ISSUE THREAD

**Issue by soumilbaldota** [taskforcesh/bullmq#2964]
### Version

v7.8.1

### Platform

NodeJS

### What happened?

When the workers are started, Redis is running.
If Redis goes down, the workers (using ioredis) lose their connection.
When Redis comes back online, ioredis successfully reconnects.

However, the workers do not resume processing jobs afterward.

I suspect that the IoredisListener may not handle events other than ioredis:close, but I am unsure of the exact cause.
Unfortunately, I do not have any stack traces to provide further insight.

### How to reproduce.

Steps to reproduce
---
1. Start Redis 
2. Start Workers (the workers are working at this point)
3. Stop Redis
4. Wait 10s 
5. Start Redis 
6. The workers are not picking up jobs after reconnecting and worker count has become 0.

```sh
 docker run -d --name redis-small \
  --memory=200m -p 6379:6379 \
  redis:latest redis-server \
--maxmemory 200mb \
--maxmemory-policy noeviction \
--enable-debug-command yes
});
```

```ts
import {Queue, Worker} from 'bullmq';
import {Redis} from 'ioredis'
const queue = new Queue('queue-1');
queue.on('error', ()=>{})
const worker = new Worker('queue-1', async (job) => {
    console.log(job.data);
    return job.data;
}, {connection: new Redis({
    maxRetriesPerRequest: null
})})
worker.on("ready", () => {  console.log("🟢 Worker is ready and connected to Redis");})
worker.on("active", (job) => {  console.log(`🚀 Job ${job.id} is now active and being processed`);})
worker.on("completed", (job) => {  console.log(`✅ Job ${job.id} completed successfully`);})
worker.on("failed", (job, error) => {  console.log(`❌ Job ${job.id} failed`, error.stack);})
worker.on("progress", (job, progress) => {  console.log(`⏳ Job ${job.id} progress: ${progress}%`);})
worker.on("stalled", (job) => {  console.log(`⚠️ Job ${job} is stalled`);})
worker.on("ioredis:close", () => {  console.log(`❌ Redis is not reachable`);})
worker.on("error", (error) => {  console.log(`❌ Worker Error ${error}`);})
worker.on("closing", () => {  console.log(`🔴 Worker is closing`);})
worker.on("closed", () => {  console.log(`🔴 Worker is closed`);})
worker.on("drained", () => {  console.log(`🫗 queue is drained`);})
worker.on("paused", () => {  console.log(`⏸ Worker is paused`);})

async function f() {
    console.log(await queue.getWorkersCount())
    // console.log(await queue.getWorkers());
}

setInterval(f, 5000);
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soumilbaldota** [comment]
@manast The workers do not start processing when the redis host is online again.

**Comment by soumilbaldota** [comment]
I can reproduce it with the above given example, only thing is that the redis container must be stopped for **atleast 20 seconds** before restarting redis again.

I am running the above code on 
node v22.4.0
docker - wsl
1. start the redis container
2. use `npx ts-node example.ts` to run the code.
3. stop the redis container.
4. **wait 30s**
5. start the redis container.
6. add to queue, using 
```ts
import {Queue} from 'bullmq'
const queue = new Queue('queue-1')
queue.add("hello", {bye: 'hello'})
```
7. the worker does not start.
8. restart the process using `npx ts-node example.ts` worker consumes no problems.



If you have problems reproducing, I could send a screen recording or hop in a call.

**Comment by Tipfurion** [comment]
I started seeing the same behavior after the update from 5.7.10 to 5.31.1. Rollback to 5.7.10 solves the issue.
it looks like:
```
Error: All sentinels are unreachable. Retrying from scratch after 10ms.
Error: Connection is closed.
```
and after this worker can't handle the job.
after rollback to 5.7.10 normally handles jobs. I see only 
```
Error: All sentinels are unreachable. Retrying from scratch after 10ms.
```
but it's ioredis with sentinel issue https://github.com/redis/ioredis/issues/1390

**Comment by manast** [comment]
![image](https://github.com/user-attachments/assets/03a962bb-a4e6-4b22-9093-07afd6204b23)

**Comment by manast** [comment]
Could you tell me exactly which one you are using?

**Comment by Tipfurion** [comment]
node v16.20.1
But the example given by the author works for me too. I think in my case there is a more complex issue, possibly related to sentinel. I can't yet provide a reproducible example on a local env

**Comment by manast** [comment]
@Tipfurion in your case, first of all you should check if IORedis is reconnecting properly, as BullMQ cannot do better in terms of reconnection than IORedis.

**Comment by soumilbaldota** [comment]
> Could you tell me exactly which one you are using?

I am using node v22.4.0. 
What version works for you @manast ?

**Comment by soumilbaldota** [comment]
The problem is with `@taskforcesh/bullmq-pro@7.8.1` that I was using.

it works perfectly with `bullmq`  latest version.

**Comment by soumilbaldota** [comment]
If anyone is having this problem with the pro version, upgrade your package version to `@taskforcesh/bullmq-pro@7.24.0`
It worked for me. Thank you @manast for your time.

**Comment by Tipfurion** [comment]
> @Tipfurion in your case, first of all you should check if IORedis is reconnecting properly, as BullMQ cannot do better in terms of reconnection than IORedis.

Could my problem be due to [this](https://github.com/taskforcesh/bullmq/commit/2cf12b3622b0517f645971ece8acdcf673bede97) commit? Looks like the connection is closing and not reconnecting, cause sometime i see logs (on version 5.7.10, before this commit)
```
 Error: All sentinels are unreachable. Retrying from scratch after 10ms.
    at connectToNext (/project/node_modules/new-ioredis/built/connectors/SentinelConnector/index.js:64:31)
    at SentinelConnector.connect (/project/node_modules/new-ioredis/built/connectors/SentinelConnector/index.js:120:16)
    at /projectr/node_modules/new-ioredis/built/Redis.js:121:64
    at new Promise (<anonymous>)
    at EventEmitter.connect (/project/node_modules/new-ioredis/built/Redis.js:103:25)
    at RedisConnection.reconnect (/project/node_modules/bullmq/src/classes/redis-connection.ts:298:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Timeout.<anonymous> (/project/node_modules/bullmq/src/classes/worker.ts:635:13)
```
in the stacktrace you can see that sometimes the blocking connection timeout occurs, and redis client successfully reconecting. What will happen in the latest version? Will the connection just close and not try to reconnect?

**Comment by soumilbaldota** [comment]
> > @Tipfurion in your case, first of all you should check if IORedis is reconnecting properly, as BullMQ cannot do better in terms of reconnection than IORedis.
> 
> Could my problem be due to [this](https://github.com/taskforcesh/bullmq/commit/2cf12b3622b0517f645971ece8acdcf673bede97) commit? Looks like the connection is closing and not reconnecting, cause sometime i see logs (on version 5.7.10, before this commit)
> 
> ```
>  Error: All sentinels are unreachable. Retrying from scratch after 10ms.
>     at connectToNext (/project/node_modules/new-ioredis/built/connectors/SentinelConnector/index.js:64:31)
>     at SentinelConnector.connect (/project/node_modules/new-ioredis/built/connectors/SentinelConnector/index.js:120:16)
>     at /projectr/node_modules/new-ioredis/built/Redis.js:121:64
>     at new Promise (<anonymous>)
>     at EventEmitter.connect (/project/node_modules/new-ioredis/built/Redis.js:103:25)
>     at RedisConnection.reconnect (/project/node_modules/bullmq/src/classes/redis-connection.ts:298:19)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Timeout.<anonymous> (/project/node_modules/bullmq/src/classes/worker.ts:635:13)
> ```
> 
> in the stacktrace you can see that sometimes the blocking connection timeout occurs, and redis client successfully reconecting. What will happen in the latest version? Will the connection just close and not try to reconnect?

You can try adding logging and event listeners to verify this behaviour.

**Comment by manast** [comment]
> Could my problem be due to [this](https://github.com/taskforcesh/bullmq/commit/2cf12b3622b0517f645971ece8acdcf673bede97) commit? Looks like the connection is closing and not reconnecting, cause sometime i see logs (on version 5.7.10, before this commit)

That change is just leaving the reconnect to IORedis, so it will also reconnect unless you have configured IORedis to not reconnect.
