### ISSUE TITLE
[Bug]: Last child job keeps getting locked in Flow

### ISSUE THREAD

**Issue by ssafayet** [taskforcesh/bullmq#2968]
### Version

v5.34.0

### Platform

NodeJS

### What happened?

I am facing this weird issue with Flows. I am not sure why, it seems like sometimes one child inside a flow job keeps getting locked without being processed or moved to a stalled state. I can't reproduce this all the time but it happens frequently in the server with our multiple pm2 instances. This is what I have done:

1. Added a flow job with children. 
2. Observing that child jobs keep getting processed one by one.
3. Suddenly last child  job is stuck in a lock state indefinitely. The lock keeps getting renewed (as I can see on Redis with new TTL) but the worker is not processing it, and also it is not getting marked as stalled. So parent job keep waiting indefinitely as last child job is locked. 

These are the options that I use for child jobs:
``
{
  removeOnComplete: true,
  removeOnFail: true,
  ignoreDependencyOnFailure: true
}
``

And for the parent job:
``
{
  removeOnComplete: true,
  removeOnFail: true
}
``

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
A couple things to try, upgrade to version 5.34.1, as we changed a bit how the job that is being lock renewed is removed from the list, and also set some even listeners on the worker, listen for complete and failed events, so see if these events are triggered when this issue happens, output the job id so that you can map the job that gets "stuck" with the events.

**Comment by manast** [comment]
Something to keep in mind is that the process function in a worker could actually never complete, leading to a job that runs forever, here some interesting reading: https://swizec.com/blog/finding-unresolved-promises-in-javascript/
It would be great if there were some mechanism in NodeJS to actually force a promise chain to timeout, but unfortunately this is only posible using observables...

**Comment by ssafayet** [comment]
@manast Thanks for the references and the guidelines. Yes, the job was stuck due to an unresolved promise. Thanks again!

**Comment by younes101020** [comment]
returning unresolved promise from the root job of a flow makes this job unable to be in a completed state.

this parent flow job never reaches the completed state:
```ts
export const build: JobFn<"build"> = async (job) => {
  return job;
};
```

while this works
```ts
export const build: JobFn<"build"> = async (job) => {
  const resolved = await job;
  return resolved;
};
```
