### ISSUE TITLE
How do I only process Jobs with a specific name?

### ISSUE THREAD

**Issue by Clemens-E** [taskforcesh/bullmq#297]
Hi, in Bull you had "Named jobs", so you could give a job a name (like you can in BullMQ) but the difference is, that in Bull you were able to only process jobs with a specific name, e.g.
```js
const myJob = await transcoderQueue.add('image', { input: 'myimagefile' });
transcoderQueue.process('image', processImage);
````
Is this possible in BullMQ as well? 
I looked into the Worker Class and its types, but were not able to find a similar feature, am I overlooking something?

My setup is something like this:
Multiple Workers that run on different processes and each Worker being responsible for one "Shard" (they all do the same but on different resources).
Now other instances calculate what shard has to get the job, and then add that job with the shard id as name, so only the Worker responsible for that Shard would get the Job.
This was possible in Bull, but as it seems isn't in BullMQ.

**Comment by Clemens-E** [comment]
Oh, sorry, I just saw #84
So, I guess there is no way for me to "route" the jobs to a specific set of Workers?

**Comment by manast** [comment]
> This was possible in Bull, but as it seems isn't in BullMQ.

No, this is exactly the same as in Bull. It is now more explicit to avoid confusions. If you need to have different workers for different tasks then you should use different queues.

**Comment by Clemens-E** [comment]
> No, this is exactly the same as in Bull.

Really? The Documentation says 
> A name argument can be provided so that multiple process functions can be defined per queue. **A named process will only process jobs that matches the given name.**

Or am I mixing something up in here?

As said, the Workers all do the same Task, but each worker has access to a different part of a resource, so it's important for each Job to go to the right Worker that has access to the part of the resource the Job is for.
If I start creating a new Queue for every Shard, I would end up with 20-60 (depending on the project scale) Queues.

**Comment by joeyfigaro** [comment]
Any updates here?

**Comment by manast** [comment]
@joeyfigaro there is nothing to update really... Names are just convenience sugar, there are no hidden functionality around them. If you have a specific use-case that cannot be addressed today it is better to create a new feature request.
I will close this issue now to avoid confusion as if there is something more to do in it.

**Comment by Clemens-E** [comment]
What I still don't get, in your documentation it literally says that there is special functionality around it

In this doc it says:
https://optimalbits.github.io/bull/
> It is possible to give names to jobs. This does not change any of the mechanics of the queue but can be used for clearer code and better visualization in UI tools:

But in your reference it says
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueprocess
> A name argument can be provided so that multiple process functions can be defined per queue. A named process will only process jobs that matches the given name.

**Comment by manast** [comment]
The second link is for older bull. This has been slightly changed in BullMQ so that it does not create more confusion.

**Comment by megamindcodex** [comment]
you guys are just causing more confusions for me
