### ISSUE TITLE
queue level concurrency limitation

### ISSUE THREAD

**Issue by Diluka** [taskforcesh/bullmq#2972]
**Is your feature request related to a problem? Please describe.**
I have 10 workers for queues, but one of those queues has api limitations. I can only run 3 jobs at the same time.

**Describe the solution you'd like**
Add max concurrency jobs config to a queue like limiter config.

**Describe alternatives you've considered**
Now I add all jobs with a large delay ensure them not running. And using a scheduler to check and promote jobs ensures less than 3 jobs running at the same time.

**Additional context**
Every job takes approximately 1 to 3 minutes. I want them to finish ASAP.

**Comment by manast** [comment]
Not sure I understand your issue, but BullMQ supports rate-limit: https://docs.bullmq.io/guide/rate-limiting
https://blog.taskforce.sh/rate-limit-recipes-in-nodejs-using-bullmq/

**Comment by roggervalf** [comment]
hi @Diluka pls also take a look in https://docs.bullmq.io/guide/queues/global-concurrency

**Comment by Diluka** [comment]
> hi @Diluka pls also take a look in https://docs.bullmq.io/guide/queues/global-concurrency

It seems to be the function I want. I'll try it first.
