### ISSUE TITLE
[Bug]: useWorkerThreads does not work with typescript

### ISSUE THREAD

**Issue by ionutpopa** [taskforcesh/bullmq#2977]
### Version

5.34.3

### Platform

NodeJS

### What happened?

Having the workers and queue managing in separated processes using worker threads on any worker (by adding useWorkerThreads: true to any Worker) will not work if using Typescript instead of Javascript:

FOR EXAMPLE:
const worker2 = new Worker(queue2Name, path.join(__dirname, "../processors/processor2.ts"), {
    connection: redisConnection,
    concurrency: 10,
    autorun: false,
    lockDuration: 5 * 60 * 1000,
    stalledInterval: 30000,
    useWorkerThreads: true,
})

worker.run()

I expected to see workers getting created like so
![Screenshot 2024-12-19 at 14 53 32](https://github.com/user-attachments/assets/8877b7c9-18f9-41b6-b661-534f13f138e2)

But if I check my VS code debug console I see errors like:
TypeError: Unkown file extension ".ts" for /Users/main/bullmqproject/src/processors/processor2.ts
Or
worker2 failed for job sanboxed-job-7 ... at Child.msgHandler (.../bullmq/src/classes/sandbox.ts:36:31)

What I use to run the code: ts-node and I have this launch.json content:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "main",
            "runtimeArgs": [
                "-r",
                "ts-node/register",
                "--watch-path=${workspaceFolder}/src",
            ],
            "program": "${workspaceFolder}/src/main.ts",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "env": {
                "REDIS_HOST": "127.0.0.1",
                "REDIS_PORT": "6379"
            }
        },
        {
            "type": "node",
            "request": "launch",
            "name": "worker1",
            "runtimeArgs": [
                "-r",
                "ts-node/register",
                "--watch-path=${workspaceFolder}/src/workers",
            ],
            "program": "${workspaceFolder}/src/workers/worker1.ts",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "env": {
                "REDIS_HOST": "127.0.0.1",
                "REDIS_PORT": "6379"
            }
        },
        {
            "type": "node",
            "request": "launch",
            "name": "worker2",
            "runtimeArgs": [
                "-r",
                "ts-node/register",
                "--watch-path=${workspaceFolder}/src/workers",
            ],
            "program": "${workspaceFolder}/src/workers/worker2.ts",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "env": {
                "REDIS_HOST": "127.0.0.1",
                "REDIS_PORT": "6379"
            }
        }
    ]
}`

Where main creates the queues and adds 10 jobs in each one
worker 1 is a worker with a simple processor
worker 2 is a worker with a sandboxed processor

### How to reproduce.

Clone my testing repo: https://github.com/ionutpopa/bullmq-test-with-sandboxed-processors/
Just use VS Code debugger:
shift+command+d
Select main, run
Select worker1, run
Select worker2, run

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
Unfortunately as BullMQ cannot compile .ts on the fly you must provide a .js file, so you will need a compile step before you can use the worker.
