### ISSUE TITLE
Export internal types

### ISSUE THREAD

**Issue by AlexFrontegg** [taskforcesh/bullmq#2983]
**Is your feature request related to a problem? Please describe.
In our project, we are standardizing the usage of external libraries by wrapping them into internal libraries or abstractions. However, the inability to export and reuse types externally creates limitations when integrating these abstractions across the codebase.

**Describe the solution you'd like
It would be highly beneficial to enable the export of types from these internal libraries. This would allow developers to leverage the defined types outside the library, ensuring consistency and reducing duplication across the project.

**Describe the benefits of this feature
Implementing this functionality would not only improve developer productivity but also promote best practices by encouraging the reuse of well-defined abstractions. It would significantly help teams adopting similar approaches to internal library standardization.

**Comment by manast** [comment]
Can you provide an example on what you mean?

**Comment by AlexFrontegg** [comment]
Hey @manast thanks for the prompt reply.

We migrated from v4 to v5 
And wrapped the old implementation like this:

`	public async addJob(name: string, data: T, opts?: BaseJobOptions): Promise<void> {
		try {
			await this.defaultQueue.add(name, data, {
				removeOnComplete: { age: 10, count: 5000 },
				removeOnFail: { age: ONE_DAY_IN_SECONDS, count: 10 },
				...opts
			});
		}` 

But now we have types collision, we can fix it with "as any" but we cannot delegate the types outside.

In our case we need this types:

`type ExtractDataType<DataTypeOrJob, Default> = DataTypeOrJob extends Job<infer D, any, any> ? D : Default;
type ExtractResultType<DataTypeOrJob, Default> = DataTypeOrJob extends Job<any, infer R, any> ? R : Default;
type ExtractNameType<DataTypeOrJob, Default extends string> = DataTypeOrJob extends Job<any, any, infer N> ? N : Default;`

**Comment by manast** [comment]
Which type collision are you getting precisely?

**Comment by AlexFrontegg** [comment]
We cant use our old types anymore 

TS2345: Argument of type string is not assignable to parameter of type ExtractNameType<T, string>
TS2345: Argument of type T is not assignable to parameter of type ExtractDataType<T, T>

.add(name, data

So we thought to use bull's types outside our lib and propagate to the other services, but the types bull use is only internal

**Comment by manast** [comment]
As an example, this is how we extend BullMQ Pro Queue class:
```
export class QueuePro<
  DataType = any,
  ResultType = any,
  NameType extends string = string,
> extends Queue<JobPro<DataType, ResultType, NameType>> {
...
}
```
You should be able to do the same in your abstractions, no?

**Comment by manast** [comment]
But it would also work just like:
```
class MyQueueExtension<DataType, ResultType, NameType> extends Queue<DataType, ResultType, NameType> {
...
}
```

**Comment by AlexFrontegg** [comment]
Emm not sure it helps us,
lets take your example and a bit extend it: 

`class MyQueueExtension<DataType, ResultType, NameType extends string> extends Queue<DataType, ResultType, NameType> {
	async addJobTest(name: NameType, data: DataType): Promise<void> {
		await this.addJob(name, data);
	}
}`

"name: NameType" will give ts error 
TS2345: Argument of type NameType is not assignable to parameter of type ExtractNameType<DataType, NameType>
Type string is not assignable to type ExtractNameType<DataType, NameType>

Our eslint/ team policy requires not to use "any" only when we have no choice. 
In this case cause I cant export types from the package it requires me to wrap / use  "any" and manipulate the types.
It could be nicer if I could use the original types and propagate on higher level.

**Comment by manast** [comment]
You should follow the example above, try with this:
```
NameType extends string = string
```

**Comment by AlexFrontegg** [comment]
![image](https://github.com/user-attachments/assets/84500987-a76a-4671-be7e-79813d15a11f)
Same error.
If ill make it any, I will have similar error on data
![image](https://github.com/user-attachments/assets/da4a9708-9e8a-4e4b-b678-5088cab4fee8)

**Comment by manast** [comment]
Which version are you using anyway? this compiles without errors using BullMQ v5.34.5 and typescript 5.7.2:
```
import { Queue } from "bullmq";

export class MyQueue<
  ResultType,
  DataType,
  NameType extends string = string
> extends Queue<ResultType, DataType, NameType> {
  constructor() {
    super("test", {
      connection: {
        host: "localhost",
        port: 6379,
      },
      defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
      },
    });
  }
}
```

![image](https://github.com/user-attachments/assets/38a2c117-4089-4f0e-a3f1-a9fd02b5d784)

**Comment by AlexFrontegg** [comment]
Yes, it compiles for me too, the problem starts with **addJob** method.
latest with ts 5

**Comment by manast** [comment]
It seems like for this to work you need to define the generics in queue using Job like below:

```import { Queue, Job } from "bullmq";

export class MyQueue<
  DataType,
  ResultType,
  NameType extends string = string
> extends Queue<Job<DataType, ResultType, NameType>> {
  constructor() {
    super("test", {
      connection: {
        host: "localhost",
        port: 6379,
      },
      defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
      },
    });
  }

  addJobTest(name: string) {
    this.add(
      "test" as NameType,
      {
        every: 1000,
        immediately: true,
      } as DataType,
      {
        removeOnComplete: true,
      }
    );
  }
}
```

But you could also define name as NameType:

```
import { Queue, Job } from "bullmq";

export class MyQueue<
  DataType,
  ResultType,
  NameType extends string = string
> extends Queue<Job<DataType, ResultType, NameType>> {
  constructor() {
    super("test", {
      connection: {
        host: "localhost",
        port: 6379,
      },
      defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
      },
    });
  }

  addJobTest(name: NameType) {
    this.add(
      name,
      {
        every: 1000,
        immediately: true,
      } as DataType,
      {
        removeOnComplete: true,
      }
    );
  }
}
```

**Comment by AlexFrontegg** [comment]
Nice! Yes that's did the job for me, working as expected.
`Job<DataType, ResultType, NameType>>`
Thanks a lot :)

**Comment by manast** [comment]
Great. I am closing the issue then.
