### ISSUE TITLE
Exceptions in QueueEvents fail silently

### ISSUE THREAD

**Issue by drone1** [taskforcesh/bullmq#299]
```
    queueEvents.on("completed", job => {
      throw "No indication that there is a problem here"
    });
```

I had a problem in my 'completed' code and no callstack was printed or exception thrown, etc. If you want more info LMK, but this should be straightforward to repro. BullMQ 1.10.0.

**Comment by manast** [comment]
This is the way events works in node, you will need to wrap the code that can fail with try/catch and report the error with logs or similar.

**Comment by drone1** [comment]
Ah OK. Thanks a lot.
