### ISSUE TITLE
Xtrim should be called on event producers, not [only] consumers

### ISSUE THREAD

**Issue by stansv** [taskforcesh/bullmq#30]
My concern here is that I suppose streams would infinitely grow if my setup only consists of a Queue and Worker, whereas trim() functionality is implemented on QueueScheduler/QueueEvents side. Correct me if I'm wrong.

**Comment by manast** [comment]
you are correct. I was just assuming you will have a QueueEvents always, but that is of course not the case. Maybe easiest is to store the trim value in the meta key and read it every time we need to emit an event.

**Comment by manast** [comment]
This should be ready by now.
