### ISSUE TITLE
Port BullMQ to Deno

### ISSUE THREAD

**Issue by evolkmann** [taskforcesh/bullmq#302]
Regarding your question about which languages to port BullMQ to ([Twitter](https://twitter.com/manast/status/1318168684049977345)), I want to make the suggestion to port it to [Deno](https://deno.land).

A few arguments (personal opinion):
- There is already a [redis client for Deno](https://deno.land/x/redis)
- Deno is a natural choice for current node developers who want to evolve with the ecosystem
- Developers form other languages (Python, PHP, Java, ...) will probably first look for queue solutions which are native to their language, and not for an "original node" project which has been ported
- BullMQ encourages a distributed, microservice approach for developing apps; Deno might be the right choice for migrating large node projects towards a distributed architecture while having the ability to reuse most of the code

**Comment by mxzinke** [comment]
You could make a fork and port it to Deno.

**Comment by evolkmann** [comment]
@mxzinke Awesome hint 😃 I am currently "still" running only NodeJS, not because the lack of BullMQ, so there is no real motivation and/or time capacity on my end to work on a port. My main intention was just to maybe have the option "BullMQ" added to the poll on twitter, to have people also vote on that.

**Comment by manast** [comment]
I like Deno and the vision behind it, however I do not think it is worth the effort just yet since Deno is still in early development and it is not gaining traction as fast as Node did when it came out. In the end it is quite difficult to compete against node when you do not provide a vastly better product and developer experience, which with Deno I am afraid is not the case just yet. 
So I will close this for now and reevaluate in the future if it is worth or not.

**Comment by wladiston** [comment]
What about now? ^^

**Comment by manast** [comment]
I don't think so. It is a matter of providing the largest value with the resources we have. Should I spend an unknown amount of hours porting to Deno for a very limited audience, or should I spend those hours making BullMQ better for NodeJS users ( a much much larger audience)?

**Comment by manast** [comment]
In fact, I think it is better Deno gets 100% compatibility with Node than all Node projects get ported to Deno, that is an insane amount of resources for actually a very small benefit.
