### ISSUE TITLE
Documentation : Delay in "Queues" page is misleading

### ISSUE THREAD

**Issue by JeyRathnam** [taskforcesh/bullmq#304]
Link : https://docs.bullmq.io/guide/untitled (Might need URL fix as well?)

Documentation for Queue states delay can be added via the options object. But it doesn't actually specify that delay needs a QueueScheduler instance to work. 
As a suggestion, can add the same prompt from the "Delayed" section to Queue documentation page. 

Something similar to this: 
![image](https://user-images.githubusercontent.com/6557230/97719476-80525880-1a9d-11eb-8426-2473a833b309.png)

I can may be create a PR for this?

**Comment by vasilevich** [comment]
can vouch, I just wasted way too much time breaking my head wondering why it doesn't work. if not for this issue I would have to switch to another library thinking its totally bugged.

**Comment by manast** [comment]
@vasilevich ok, but it is documented in the documentation: https://docs.bullmq.io/guide/jobs/delayed

**Comment by manast** [comment]
I will close this issue btw, since it is in fact documented.

**Comment by JeyRathnam** [comment]
Pardon me for reopening this issue. The issue is not in the delayed page but in "Queues" page. Specifically this portion of the page:
![image](https://user-images.githubusercontent.com/6557230/105072467-d78c1780-5a53-11eb-9da5-f248202dbc75.png)

It mentions options can be used to change behavior of jobs and uses delay as an example. But it doesnt mention that delay needs QueueScheduler to actually work.

**Comment by manast** [comment]
Allright, fixed now too: https://docs.bullmq.io/guide/queues
