### ISSUE TITLE
cron expression error and cron job not working as expected. 

### ISSUE THREAD

**Issue by 5achinJani** [taskforcesh/bullmq#305]
According to the [docs](https://docs.bullmq.io/guide/jobs/repeatable)
![image](https://user-images.githubusercontent.com/23077544/98113804-2fda6100-1eca-11eb-9695-ffa24a40dcac.png)

First thing is the [cron expression](https://www.freeformatter.com/cron-expression-generator-quartz.html) link that you've mentioned in the docs results in error with "Unexpected end of expression."
![image](https://user-images.githubusercontent.com/23077544/98114417-3fa67500-1ecb-11eb-81a0-4151cd0897fa.png)

I used the same cron expression in the code:
![image](https://user-images.githubusercontent.com/23077544/98115273-92ccf780-1ecc-11eb-8087-36a018d729ee.png)

And cron runs every second :
![image](https://user-images.githubusercontent.com/23077544/98115209-7630bf80-1ecc-11eb-9e84-80e3629d4f90.png)

Here's the code for queue, worker and required things : 

![image](https://user-images.githubusercontent.com/23077544/98115600-171f7a80-1ecd-11eb-92fe-c851e47c56bd.png)

![image](https://user-images.githubusercontent.com/23077544/98115673-33231c00-1ecd-11eb-8a09-41e7658afc42.png)

![image](https://user-images.githubusercontent.com/23077544/98115728-4b933680-1ecd-11eb-8ad7-384766904e94.png)

node version : v11.14.0
```json
"bullmq": "^1.9.0",
```
Redis:
![image](https://user-images.githubusercontent.com/23077544/98115892-839a7980-1ecd-11eb-968b-565588e00f46.png)

**Comment by 5achinJani** [comment]
This doesn't look cron expression or [parser](https://www.npmjs.com/package/cron-parser) specific to me cause I even tried this :
```ts
export const registerPointsCronJob = async () => {
  await points_queue.add(
    points_jobs.POINTS_CRON_JOB,
    {
      params: {},
    },
    {
      repeat: {
        // cron: '15 3 * * *',
        every: 30000,
        limit: 10,
      },
    },
  )
  console.log('Points cron job registered')
}
```

And it keeps triggering every second and doesn't stop too.
![image](https://user-images.githubusercontent.com/23077544/98117164-5353da80-1ecf-11eb-9df5-d3d9832c5512.png)

I restarted my redis server and node server for both the cases just to make sure but it is still the same.

**Comment by manast** [comment]
You need to delete the repeatable job in order to stop it, either that or do a "flushall" on redis.

**Comment by 5achinJani** [comment]
Thank you for the response. So the better practice would be to [get](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetrepeatablejobs) the repeatable jobs and [remove](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueremoverepeatable) them then register then cron jobs for every node server deployment or on local node server start/live-reload right?

**Comment by 5achinJani** [comment]
Also the cron expression part error "Unexpected end of expression." can also lead to confusion as it did for me so my suggestion would be to update the docs if you think the confusion concern that I raised is right. 

![cron expression error](https://user-images.githubusercontent.com/23077544/98113804-2fda6100-1eca-11eb-9695-ffa24a40dcac.png)

![cron expression error](https://user-images.githubusercontent.com/23077544/98114417-3fa67500-1ecb-11eb-81a0-4151cd0897fa.png)

**Comment by manast** [comment]
> Thank you for the response. So the better practice would be to get the repeatable jobs and remove them then register then cron jobs for every node server deployment or on local node server start/live-reload right?

Depends on your use case. Often you have some fixed set of cron jobs and then you do not need to do that.

**Comment by sbleon** [comment]
@5achinJani, "15 3 * * *" is definitely a valid cron expression:
![Screen Shot 2020-11-05 at 1 30 20 PM](https://user-images.githubusercontent.com/198711/98281720-19d0ad00-1f6b-11eb-996e-143ae9b1bedc.png)
See also: https://en.wikipedia.org/wiki/Cron

It look like the tool you're using is trying to evaluate the expression using as a "Quartz cron" expression, which is a non-standard format. (In my opinion, it's deeply irresponsible of Quartz to use the word "cron" when their formats are not interoperable.)

**Comment by 5achinJani** [comment]
@sbleon Thanks for the info :) I was following expression evaluator that bullmq has the link of it the docs : https://docs.bullmq.io/guide/jobs/repeatable

https://github.com/taskforcesh/bullmq/issues/305#issuecomment-722154211

**Comment by sbleon** [comment]
Oh, wow! It's pretty bad to have that link in the docs. That should definitely be changed.

**Comment by roggervalf** [comment]
Closing as the docs were changed
