### ISSUE TITLE
Recurring jobs sometimes run immediately when added to queue

### ISSUE THREAD

**Issue by sbleon** [taskforcesh/bullmq#306]
Sometimes, when I add recurring jobs to a queue, starting with a completely empty Redis, an instance of the job is immediately executed. Has anyone else seen this happen?

**Comment by manast** [comment]
Picture this: time is divided in slots separated by your repeating interval, the slots are fixed, the need to be so that all workers are in consensus on when the next repeatable job is supposed to be repeated. If you happen to add the recurring job very close to the next slot it will be executed directly.

**Comment by manast** [comment]
btw, this is also the way standard cron jobs works AFAIK.

**Comment by 5achinJani** [comment]
I did see this in https://github.com/taskforcesh/bullmq/issues/305 but in my case the redis was not empty [flushing](https://github.com/taskforcesh/bullmq/issues/305#issuecomment-721784213) it resolved it.

**Comment by 5achinJani** [comment]
I can confirm this happened with me today when I started my node server. I didn't make any changes in the job config or anything nor in redis. 

npm start: 
You can see the job triggered console log.
![image](https://user-images.githubusercontent.com/23077544/98333612-2c102100-2027-11eb-98f7-840be3db8ad4.png)

After that I did live-reload and killed and restarted the node server it seem to be working fine: 

![image](https://user-images.githubusercontent.com/23077544/98333837-a04ac480-2027-11eb-8004-c86a11da32c0.png)

**Comment by sbleon** [comment]
Thanks, @manast . I somehow missed your timely response!
> If you happen to add the recurring job very close to the next slot it will be executed directly.
If it is currently 12pm, and I schedule a job for 2am every day, that would not count as "very close to the next slot", right?

**Comment by manast** [comment]
@sbleon no, that would not count.
