### ISSUE TITLE
an event where all of the jobs inside the queue are done

### ISSUE THREAD

**Issue by ATheCoder** [taskforcesh/bullmq#312]
My use case is that each worker makes a folder to put their associated data inside and when the worker doesn't have any job to do it will empty that folder on the `drained` event. However when the `drained` event fires, the worker might be doing another job because `concurrency` is set to `30`, so the data for the ongoing jobs get lost because the `drained` event gets called before the worker has finished all the jobs.

Is there any other event that I could use for my use case of emptying the folder after all of the jobs inside the queue have been finished?

**Comment by manast** [comment]
No, there is no such event. However it should be feasible if you setup a new listener for "completed/failed" after the drained event has triggered and in this listener you check if there are any active jobs, if not fire your custom event.

**Comment by ATheCoder** [comment]
@manast 

How would I check if there are any active jobs inside the listener of `completed/failed`?

**Comment by ccollie** [comment]
```javascript
async function hasActive(queue): boolean {
  const counts = await queue.getJobCounts('active');
  return !!counts.active;
}
```

**Comment by manast** [comment]
I will close this since I consider it resolved.
