### ISSUE TITLE
Dependency on @types/ioredis is redundant 

### ISSUE THREAD

**Issue by tylergets** [taskforcesh/bullmq#318]
This package depends on @types/ioredis however this package shouldn't be required as ioredis is written in TypeScript

This prevents me from passing in a native ioredis

https://github.com/taskforcesh/bullmq/blob/master/package.json#L26

**Comment by manast** [comment]
ok. For the record, when I started writing bullmq, ioredis was still plain javascript. If you do not mind you could create a small PR removing that dependency and I will gladly merge it.

**Comment by roggervalf** [comment]
I'm checking that ioredis does not include its type file, so @types/ioredis is still needed. I think we are good to close this issue

**Comment by manast** [comment]
yes, I learnt that ioredis does not ship with typings, closing.
