### ISSUE TITLE
Differences with optimalbits/bull v3

### ISSUE THREAD

**Issue by loris** [taskforcesh/bullmq#32]
Hello @manast,
I am a great fan of the optimalbits/bull library and am very excited with this new repo. I'm wondering if you could share (it might exist, but have not found it) some details on the differences between bull v3 and v4. It looks like a full rewrite in TypeScript, but does it include more new features, or breaking changes? Futhermore can you share why you moved to another github organization instead of a v4 branch on the original repo?

Thanks a lot for the insight and thanks a lot for the awesome work.

**Comment by manast** [comment]
I hope you can get most of your questions answered here:
https://medium.com/@rockstudillo/beta-release-of-bullmq-4-0-867960aec51?sk=45bcd0fb5a9c20bcc9eca1e523a0858c

**Comment by loris** [comment]
Thanks a lot @manast really interesting read, looking forward to first alpha releases :)
