### ISSUE TITLE
GCP Unknown Client Command

### ISSUE THREAD

**Issue by marcjlyoung** [taskforcesh/bullmq#323]
So I use GCP to handle Redis and noticed this error, 

`ERR unknown command `client`, with args beginning with: `setname`,

I believe this was fixed in Bull. Workers do not start at all as long as this error is present. 

I managed to fix it using the shady workaround:
` IORedis.prototype.client = function () {};`

Any better ways of doing this?

**Comment by brianschardt** [comment]
Running into this same issue on GCP.

**Comment by brianschardt** [comment]
How do you fix this in typescript your solution doesnt work for me. I get the error
```
Cannot find name 'IORedis'.
```

**Comment by marcjlyoung** [comment]
> How do you fix this in typescript your solution doesnt work for me. I get the error
> 
> ```
> Cannot find name 'IORedis'.
> ```

So you will need to npm/yarn install IORedis, then import * as IORedis from "IORedis" in the same file you overwrite the prototype and create the worker. 

We need to import the package because we need to override the IORedis package that bull mq uses in order for it to stop calling the blocked client command on gcp. 

It is a silly issue, and has been fixed in the vanilla bull.

**Comment by brianschardt** [comment]
I keep getting this error in gcp: 
```
Missing lock for job 14 failed
```
Do you think it is related to this?

**Comment by marcjlyoung** [comment]
> I keep getting this error in gcp: 
> ```
> Missing lock for job 14 failed
> ```
> Do you think it is related to this?

@brianschardt I think it's unrelated, after my solution the queues are working fine in our production environment.

**Comment by killthekitten** [comment]
The issue that tracks it in the bull repo is here:

https://github.com/OptimalBits/bull/issues/1002

**Comment by marcjlyoung** [comment]
This is issue was fixed in the latest [release](https://github.com/taskforcesh/bullmq/commit/9aba722f41b390b5a5eeeeeba7c51b4f87cd87c7)
