### ISSUE TITLE
Remove client property from QueueBaseOptions

### ISSUE THREAD

**Issue by paeolo** [taskforcesh/bullmq#324]
[QueueBaseOptions](https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/interfaces/queue-options.ts#L11) exposes both a `client` and a `connection` property. The connection property can be either `RedisOptions` or a `Redis` client, so it seems the `client` property is redundant.

And indeed, [looking at the code](https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/classes/queue-base.ts#L22) I noticed the client property is not used (in favor of the connection property), so it can mislead developpers that tries to use the client property.

Suggestion: If the `client` property is not used, and moreover redundant, remove it.

**Comment by manast** [comment]
But the client property is just a convenient getter for connection.client:
https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/classes/queue-base.ts#L57

**Comment by paeolo** [comment]
> But the client property is just a convenient getter for connection.client:
> https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/classes/queue-base.ts#L57

@manast  My point is to remove the client property from [QueueBaseOptions](https://github.com/taskforcesh/bullmq/blob/5e6631e7c3f40b7857d2f73b48abfd3f9d072b35/src/interfaces/queue-options.ts#L11), not the getter from [QueueBase](https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/classes/queue-base.ts#L57) class.
https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/interfaces/queue-options.ts#L13

Indeed, if you leave it like that, then the developer as the opportunity to do that:

```ts
import Redis from 'ioredis';
import { Queue } from 'bullmq';

const redisClient = new Redis();
const queue = new Queue('my-queue', { client: redisClient });
```
If you use auto-completion you are tempted to do so, but what you don't know is that the client property you give to the constructor **will never be used**, since instead the [connection](https://github.com/taskforcesh/bullmq/blob/7372ef16465fdf7d3c803a9cd9c1a25422d53373/src/classes/queue-base.ts#L22) property is used, hence my suggestion to remove this unused property.
