### ISSUE TITLE
Discarded jobs stay in the same state

### ISSUE THREAD

**Issue by grapevineai** [taskforcesh/bullmq#326]
I don't know if it's an intended behavior, but IMHO a discarded job should have a "discarded" state and not stay in the same "delayed" state (I didn't test the other states). There should be an additional type...

**Comment by manast** [comment]
As the documentation states, a discarded jobs just means it will not be retried in the case of failure: https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobdiscard
