### ISSUE TITLE
Jests Tests Hanging

### ISSUE THREAD

**Issue by Migueld37** [taskforcesh/bullmq#329]
Hey Everyone,

I'm having some trouble getting my jest test suite to close. I have a strong feeling it's because I'm not closing the worker and queue properly? What's a good place to do that? This is what I'm doing now:

```
export function initQueue(queueName: string): Queue {
  const queue = new Queue(queueName);

  const queueEvents = new QueueEvents(queueName);

  queueEvents.on('waiting', ({ jobId }: QueueEvent) => {
    logger.debug(`A job with ID ${jobId} is waiting`);
    cacheJobStatus(queueName, jobId, 'waiting');
  });

  queueEvents.on('active', ({ jobId, prev }: QueueEvent) => {
    logger.debug(`Job ${jobId} is now active; previous status was ${prev}`);
    cacheJobStatus(queueName, jobId, 'active');
  });

  queueEvents.on('failed', ({ jobId, failedReason }: QueueEvent) => {
    logger.debug(`${jobId} has failed with reason ${failedReason}`);
    cacheJobStatus(queueName, jobId, 'failed', failedReason);
  });

  queueEvents.on('completed', async ({ jobId, returnvalue }: QueueEvent) => {
    logger.debug(`Job ${jobId} is now complete`);
    await cacheJobStatus(queueName, jobId, 'completed', returnvalue);
  });
  return queue;
}
```

**Comment by ccollie** [comment]
Not sure if this is the issue, but at a glance, you're not disposing of `queueEvents`

**Comment by Migueld37** [comment]
> Not sure if this is the issue, but at a glance, you're not disposing of `queueEvents`

Would I do that in my 'failed' and 'completed' listeners?

**Comment by manast** [comment]
I am going to close this since it is a general nodejs question and affecting a specific use case not directly related to BullMQ. For  generic support questions I recommend stackoverflow.

**Comment by mmahalwy** [comment]
@manast i am having the same problem too. Jest hangs. I can create a repro repo if that helps

**Comment by manast** [comment]
@mmahalwy is this happening with the latest version too?

**Comment by mmahalwy** [comment]
@manast yep. When I export multiple queue instances, this causes a problem. The only solution I found is to instantiate an instance of that queue for when I need to call it. 

Separately though, it'd be great if there are examples. I have no idea if what I am doing is correct but it works 🤷
