### ISSUE TITLE
What is rule of QueueScheduler?

### ISSUE THREAD

**Issue by Glyphack** [taskforcesh/bullmq#330]
according to docs we need a queue scheduler in order to have delayed jobs and from docs example one has to declare it like:
```
import { Queue, QueueScheduler } from 'bullmq'

const myQueueScheduler = new QueueScheduler('Paint');
const myQueue = new Queue('Paint');

// Add a job that will be delayed at least 5 seconds.
await myQueue.add('house', { color: 'white' }, { delay: 5000 });
```
My question is that isn't there any functionality we want from a queue scheduler? as we are working with the basic Queue to add jobs.
so The above example and this one is equivalent:
```
import { Queue, QueueScheduler } from 'bullmq'

new QueueScheduler('Paint');
const myQueue = new Queue('Paint');

// Add a job that will be delayed at least 5 seconds.
await myQueue.add('house', { color: 'white' }, { delay: 5000 });
```

**Comment by marcjlyoung** [comment]
Both examples will work.

I believe you only need to instantiate the queue scheduler so it establishes a connection to Redis in order to setup the delayed jobs.

**Comment by manast** [comment]
@Glyphack somewhere you probably want to have a graceful shutdown and in that place call ```myScheduler.close()```
