### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by tamired** [taskforcesh/bullmq#341]
Hello, we're migrating from Bull to BullMq and during first load testing we started getting this error thrown by the Bullmq instance: Error: EMFILE: too many open files, scandir '/app/node_modules/bullmq/dist/commands'.

Our queue handles very large job amounts (aprox 500K) that are triggered in bulks (1K each bulk). With Bull, we used to run 5 app pods with 100 workers on each pod and tested another version with 10 pods running 10 workers each.

Got the above error on each attempt. any ideas?

**Comment by manast** [comment]
You could debug this issue by figuring out which files are actually being opened, that would be very useful to find the root of the issue:
https://serverfault.com/questions/138297/how-to-track-all-files-a-process-opens-in-its-lifetime

**Comment by Co-sta** [comment]
I'm having the same issue. I've tested and in Bull  4000 queues can be created with no shortage of file descriptors (not that I need so many queues). But whenever I've tried the same test with BullMQ, only 203 queues can be created before this error happens. 
 
Could it be something wrong with BullMQ Queue class?

**Comment by manast** [comment]
I do not think anything is wrong, but lets try by reading the files serially, that should minimize the number of files open at any given time: https://github.com/taskforcesh/bullmq/pull/470

**Comment by Co-sta** [comment]
Don't know if it helps but I'm running in Ubuntu 18.04.5 LTS

**Comment by manast** [comment]
@Co-sta please try with latest version 1.16.2

**Comment by Co-sta** [comment]
I've tested the new version and it seems that I can now create up to 400 queues. It seems that reading the files serially helps preventing the error.

**Comment by manast** [comment]
@Co-sta do you get the error after 400 queues? I guess there is also a limit if you instantiate all the 400 queues at the same time instead of serially. This is mostly a problem with BullMQ itself that loads the files in the constructor instead of explicitly via a "start" method or similar.

**Comment by Co-sta** [comment]
Yes after 400 queues i get "Error: EMFILE: too many open files" error. 

This is my code to create the queues:

""
const Bull = require("bullmq");
const connection = new IORedis();

for (let i = 0; i < queueNames.length; i++) {
  const queue = new Bull.Queue(queueNames[i], { connection });
  queueList[queueNames[i]] = queue;
}
""

queueNames is a list of strings.

**Comment by Co-sta** [comment]
Is Bull3 using a method insead of loading the files in the constructor?

**Comment by manast** [comment]
try this instead:
```ts
for (let i = 0; i < queueNames.length; i++) {
   const queue = new Bull.Queue(queueNames[i], { connection });
   queueList[queueNames[i]] = queue;
   await queue.client;
}
```

**Comment by Co-sta** [comment]
It seems to be working. I will continue to my stress test but so far so good.
 
My only problem now is the maximum number of queues/workers accessible by a single process(.js file) being 70. But I've already created an issue for that #465.

Thanks for the help so far

**Comment by Co-sta** [comment]
It seems that this..

```js
await queue.client;
```

... resolved the problem. I can not find in the documentation what this does though. Could you elaborate or point me in the right direction? Could this also be used in the initialization of Workers and QueueSchedulers like this?:

```js
const scheduler = new Bull.QueueScheduler(queueNames[i]);
await scheduler.client;
```


```js
const worker = new Bull.Worker(queueNames[i],
                                 main.init,
                                 {
                                   connection: connection,
                                   limiter: {
                                              max: queueNames.length-i,
                                              duration: 1000
                                            }
                                 })
await worker.client;
```

**Comment by manast** [comment]
it waits for the connection to be ready.

**Comment by roggervalf** [comment]
@tamired please try last versión, this should be fixed
