### ISSUE TITLE
Global job history limits

### ISSUE THREAD

**Issue by bluecomm42** [taskforcesh/bullmq#347]
I want to prevent my redis database filling up with old jobs. I know that there are the job options `removeOnComplete` and `removeOnFail`, but as far as I can tell those have to be passed *every* time I add a new job. Is there a global option I can specify so that I can cap it to say the last x jobs without having to specify those params every time I add a job?

**Comment by manast** [comment]
Please let me know if this documentation is enough: https://docs.bullmq.io/guide/jobs/fifo#default-job-options

**Comment by bluecomm42** [comment]
@manast it does, but shouldn't the key be `removeOnFail`, not `removeOnFailed`?

**Comment by manast** [comment]
> @manast it is, but shouldn't the key be `removeOnFail`, not `removeOnFailed`?

yes, a typo, I fixed it now.
