### ISSUE TITLE
QUESTION:  Worker class generic type arguments

### ISSUE THREAD

**Issue by norberto-e-888** [taskforcesh/bullmq#349]
The Worker class seems to be able to receive 3 generic type arguments; what are they and what effect does each one have?

**Comment by norberto-e-888** [comment]
I inspected my node_modules and answered my own question

**Comment by norberto-e-888** [comment]
For anyone that might have wondered the same, the first argument is the job.data, second is its return value, and the third is the type of job.name.

**Comment by ccravens** [comment]
@norberto-e-888 yes I actually spent the last hour trying to understand that by looking at the code, thank you for your question and response!
