### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:6379 even if I specify AWS host and port

### ISSUE THREAD

**Issue by StErMi** [taskforcesh/bullmq#352]
Hi all, I've configured the connection to use an AWS Redis instance specifying both port and host in the connection options but when I deploy the docker image I get this error as if it's not using those options.

What could be the problem? The same configuration is used for both the Queue and Worker.

**Comment by manast** [comment]
for some reason you are not passing the host and port correctly in your docker image, I do not think we can provide you any more help about this issue...

**Comment by sgpinkus** [comment]
Just had same issue. @StErMi It could be a versions. The connection interface has changed between BullMQ and Bull. The [Bull API docs](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue) are not compatible with BullMQ and there are no BullMQ API docs (AFAICT, CC @manast). I think you have to read the [guide](https://docs.bullmq.io/guide) to try and the BullMQ API changes.

**Comment by manast** [comment]
The API documentation is coming. Best is to use Typescript of course, then you will never get this kind of errors. I will close this for now since there does not seem to be any bug.

**Comment by StErMi** [comment]
Nope, it was not a bug, it was just me that had updated all the connection config but not in the `QueueEvents` and those logs were not helping to identify who was throwing the error.

**Comment by m-allanson** [comment]
I was running in to a similar issue publishing a project on Heroku. 

It took a while to realise the problem was the missing `connection` option for my `QueueEvents`. This doesn't seem to be mentioned in the docs. It's in the API docs but fairly hidden away. 

I made an example repo for myself while debugging, maybe it will be useful for someone else who runs into this: https://github.com/m-allanson/bullmq-redis-example

**Comment by ChinmayGopal931** [comment]
@m-allanson @manast  facing this same issue. What is bull qm why is my econconnect stating 127.0.0.1:6379 even though I specify aws redis hostname.?
```

'use strict';
var redis = require("redis");


exports.handler = async (event) => {
          
          const redisOptions = {
                  host: "clustercfg.priceservice.aeq8en.memorydb.us-east-1.amazonaws.com",
                   port: 6379
}
          
          var client = new Redis({url: "redis://clustercfg.priceservice.aeq8en.memorydb.us-east-1.amazonaws.com:6379"});
          
          // var client = await redis.createClient({
          //         port: 6379,
          //         host: "----amazonaws.com",
          //         tls: {},
          // });
          
          //await client.connect()
          
          await client.set("foo", "bar");
          let result = await client.get("foo");
          let response = {
                      'statusCode': 200,
                      'body': JSON.stringify({
                                    result: result,
                                  })
                    }
                    client.quit()
          return response
          
          }
          
          ```

**Comment by rgmvisser** [comment]
@ChinmayGopal931  and for other people that also run into this issue. I found what was causing it for me. I had all my Workers and Queues set with the right connection, but forgot the "FlowProducer". 

Check all the BullMQ classes that carry a connection to make sure you set them everywhere.

**Comment by humphd** [comment]
> @ChinmayGopal931 and for other people that also run into this issue. I found what was causing it for me. I had all my Workers and Queues set with the right connection, but forgot the "FlowProducer".
> 
> Check all the BullMQ classes that carry a connection to make sure you set them everywhere.

This was exactly what I hit today, thank you!

**Comment by ortegoncarlos** [comment]
@rgmvisser  how can I use the "FlowProducer"?, can you share some code how can I implement it on a simple Queue,  

```
const connection = connectQueue()

export const calculateStatementQueue = new Queue('calculateStatementQueue', {
  connection,
})

const calculateStatementQueueWorker = new Worker(
  'calculateStatementQueue',
  async (job) => {
    // Do something with job
    return new CalculateInterest().recalculateTableAfterPayIn(job.data)
  },
  { concurrency: 5 }
)

```

**Comment by koyukan** [comment]
@rgmvisser @m-allanson  Thank you! Passing connection options to FlowProducer solved my issue. And I agree, the documentation could be a bit more clear about the connection options.

And @ortegoncarlos 

const connection = {
  host: process.env.REDIS_HOST,
  port: process.env.REDIS_PORT,
  maxRetriesPerRequest: null,
  enableReadyCheck: false,
  retryStrategy(times) {
    const delay = Math.min(times * 500, 300000);
    return delay;
  },
};

**Comment by FSL89** [comment]
> @rgmvisser @m-allanson Thank you! Passing connection options to FlowProducer solved my issue. And I agree, the documentation could be a bit more clear about the connection options.
> 
> And @ortegoncarlos this is how you create and use the flow producer
> 
> const connection = { host: process.env.REDIS_HOST, port: process.env.REDIS_PORT, maxRetriesPerRequest: null, enableReadyCheck: false, retryStrategy(times) { const delay = Math.min(times * 500, 300000); return delay; },
> 
> };
> 
> const flowProducer = new FlowProducer({ connection });
> 
> const job = flowProducer.add({ name: "transcode", queueName: concatQueueName, children: chunks.map((chunk) => ({ name: "transcode-chunk", queueName: transcoderQueueName, data: { videoFile: chunk } as SplitterJob, })), });

**THIS!** This should be a lot clearer in the documentation. I went through my whole setup, tried adding dummy data trying to figure out where the connection settings was ignored.
