### ISSUE TITLE
Repeatedly pausing a worker can cause it to starve the event loop

### ISSUE THREAD

**Issue by airhorns** [taskforcesh/bullmq#359]
This is a weird one, but, in my application I have a reliable reproduction where pausing and resuming a BullMQ worker 3 times almost always prevents the rest of the async application from making any progress by preventing the event loop from making it to the poll phase. See https://snyk.io/blog/nodejs-how-even-quick-async-functions-can-block-the-event-loop-starve-io/ for a breakdown of what's happening.

I'm working on a backend Fastify application that connects to a database via an async adapter, and I use BullMQ to process background jobs. In the tests for my application, I want to pause the worker and make assertions about what jobs have been pushed, and then usually work the queues to then assert on their effects. I have my test system (jest) set up to pause my workers one at a time as they are created, and then a test that wants a queue worked resumes the worker it needs. 

Almost always, my first two test cases that use this technique pass just fine, but the third one enters into an infinite loop in the `while` within `Worker.run()`. I discovered this by adding manual `process.stderr.write` statements to the `worker.js` file in my local `node_modules`. Once the worker enters this loop, any other async calls made outside the worker fail to call back. I proved this by running a bunch of synchronous code after resuming the worker that prints, and saw those print statements, but once I run anything async that talks to the database, the event loop comes back around and never calls back with my database result. 

I am almost sure that this is event loop phase starvation, because the exact same code works fine when run the first two times, or when run in isolation.

Other facts:
 - pausing BullMQ with `doNotWaitActive` prevents the issue, but, that makes it hard to test when jobs might still be in flight
 - BullMQ works fine in production when it's the main process and it's not paused and resumed for me
 - the first few test cases progress just fine and this really does seem to be related to pausing.
 - closing and recreating the worker for each test fixes this issue

To me, all this suggests that pausing causes some internal state to get funky, and for the worker to start racing promises that resolve before the `poll` phase of the event loop where my database results might be sitting. I am going to continue digging, but, can anyone spot an issue in the `pause` code that would cause this condition?

Thanks!

**Comment by manast** [comment]
thanks for the report. I do not think this is related to event loop blocking but with some hazard that appears when pausing/resuming quickly. It would be of great help if you could prepare a test case that reproduces this issue so that I can dig more into the details.

**Comment by airhorns** [comment]
This has been fixed with #389, thanks @manast !
