### ISSUE TITLE
Worker loop does not restore after redis disconnects

### ISSUE THREAD

**Issue by stansv** [taskforcesh/bullmq#36]
Scenario

1) run Redis on `localhost:6379` and create a `Worker` with default options and no-op processing callback
2) Worker call brpoplpush with default rate determined by `drainDelay` (5 secs)
3) Stop redis gracefully or `kill -9`

The `ECONNREFUSED` will appear (I've also added some logging to trace each brpoplpush)

```
BRPOPLPUSH at 2019-10-12T09:22:26.934Z
BRPOPLPUSH at 2019-10-12T09:22:31.950Z
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
<the same message appears again from time to time>
```

3) Start Redis
4) New error messages still appears, Worker doesn't try to take new jobs from queue

UPD. I've spent some more time on debugging this. What's not good is that `brpoplpush()` call does not return control on such error, i.e. the promise returned neither resolves nor rejects.

**Comment by manast** [comment]
so you mean that brpoplpush does never resolve or fail when the connection fails?

**Comment by stansv** [comment]
Yes, brpoplpush() neither resolves nor rejects as I can see.. probably there some hidden timeout so maybe it would be rejected if I'd wait more time. Need to check ioredis implementation.
