### ISSUE TITLE
Update job options on the fly

### ISSUE THREAD

**Issue by grapevineai** [taskforcesh/bullmq#365]
It's currently impossible to update job options after it was added. It would be nice to implement this feature!

**Comment by manast** [comment]
When you say job-options do you mean the job data object or the options? It is easier to only update the data since updating options includes several edge cases, for example, if you change the option "delay" then it should affect the time the job is being delayed in the queue, etc.

**Comment by grapevineai** [comment]
I meant the options such as delay...but I guess it makes sense to delete/recreate
