### ISSUE TITLE
I start the serve by DEBUG=*, Then I see the output every seconds, is that ok?

### ISSUE THREAD

**Issue by suhaotian** [taskforcesh/bullmq#369]
I start the serve by DEBUG=*, Then I see the output every seconds, is that ok:

![image](https://user-images.githubusercontent.com/6512574/104171012-f4659100-543c-11eb-81e1-61ac01b5ef2e.png)

**Comment by manast** [comment]
This is the output from ioredis not from BullMQ, what is your issue?

**Comment by suhaotian** [comment]
Hi, yeah it's from ioredis, but the write comand is from bullmq ..

**Comment by manast** [comment]
That may be normal, depends on how you are using the queue...

**Comment by suhaotian** [comment]
ok thank you for the response
