### ISSUE TITLE
[Feature request] add queue event enum

### ISSUE THREAD

**Issue by xiaoyu-tamu** [taskforcesh/bullmq#373]
for better DX, please add comprehensive list of event name. Currently I have to find these keys in source code.

something like this
```ts
export enum QueueEvent {
  Drained = 'drained',
  // ... and more
}
export enum WorkerEvent {
  Completed = 'completed',
  // ... and more
}
```

**Comment by manast** [comment]
For global events, i.e., using the QueueEvents class you should get intellisense for the events, however for Worker and Queue this feature is missing.

**Comment by roggervalf** [comment]
we already have https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.workerdeclaration.md and https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.queuedeclaration.md
