### ISSUE TITLE
Will reschedule a failed/stalled job put it to the end of the queue?

### ISSUE THREAD

**Issue by alonbilu** [taskforcesh/bullmq#379]
Hey guys
Short question if I may - 

When a job (with a backoff strategy) fails, when is the next time it will be processed?
Immediately after the delay period has passed ?
**OR**
only after all remaining queued jobs completed?

If the later is correct, a follow up question: 
Will a failed job with higher priority (than other reaming jobs) behave differently?

Thanks

**Comment by manast** [comment]
A retried job with a strategy works exactly the same as any delayed job, i.e. when time expires it is moved back to the head/front of the wait queue, meaning that it will be processed as soon as possible. Beware that if you have many delayed jobs and the jobs are slow then it could happen that the new jobs pushes the old ones back so they will indeed need to wait a few other jobs before they actually get processed.

**Comment by alonbilu** [comment]
Awesome. Thanks for the clarfication.
