### ISSUE TITLE
Update debuglog section key and add more debug logging

### ISSUE THREAD

**Issue by stansv** [taskforcesh/bullmq#38]
With `NODE_DEBUG=bull` we can enable debug mode in Bull 3, and see some helpful output in console. Bullmq also have support of this debug mode, but there's only single place where debuglog is called, so in current implementation it's not very usable.

Also, for bullmq it's reasonable to rename section key to match new package name.

**Comment by manast** [comment]
regarding the prefix, one reason to keep it with "bull" is for better backwards compatibility

**Comment by manast** [comment]
As we support telemetry now, no more debug capabilities are planed to be added in the future.
