### ISSUE TITLE
Is there a way for multiple consumers?

### ISSUE THREAD

**Issue by bennyKY** [taskforcesh/bullmq#382]
Hi, Bull uses Redis pubsub so it wont allow multiple consumers.
But Bullmq uses Redis streams so it should be feasible.
Is there a way to do it with Bullmq? If not maybe someone can advise how to achieve it without Rabbit or Kafka?

**Comment by manast** [comment]
Bull and BullMQ both support multiple consumers, just create as many workers as you see fit and they will consume your jobs in parallell.

**Comment by bennyKY** [comment]
@manast 
I think i wasnt clear, sorry for that. Im talking about broadcasting. Multiple services that consume from a queue. As far as i worked with Bull (1 year in production) if 2 services listening to messages from a queue only 1 services will receive the message.

**Comment by manast** [comment]
Ok, so you mean fanout (https://en.wikipedia.org/wiki/Fan-out_(software)), i.e. same job to many consumers. That is not supported and there are no plans for it, in that case using XTREAMS is a really good solution if you do not want to experiment with more complex solutions such as Kafka.

**Comment by manast** [comment]
@bennyKY I meant streams as you wrote on the issue, sorry for the confusion: https://redis.io/commands#stream
