### ISSUE TITLE
Typescript Job.data attribute static typings

### ISSUE THREAD

**Issue by dan003400** [taskforcesh/bullmq#384]
Is there a way to type your job.data attributes using typescript when defining a Job processor?

**Comment by manast** [comment]
Please check this: https://docs.bullmq.io/guide/workers#typescript-typings

**Comment by Slayug** [comment]
It does not to work for me, especially for the data type:

![image](https://user-images.githubusercontent.com/1078777/147374366-9daab6e3-9fe4-4a58-86f9-439e541fb1f5.png)

The only way to make it works is by putting generic information for Job argument:  

![image](https://user-images.githubusercontent.com/1078777/147374371-8247b275-9f15-4e6a-b7b3-ec630a513ee9.png)
Now I have correct definition for `Datatype`.

However when I look into the source code, the DataType sounds well set https://github.com/taskforcesh/bullmq/blob/master/src/classes/worker.ts#L113

Any idea @manast ?

**Comment by manast** [comment]
@Slayug is this still not working for you after @roggervalf latest fix?

**Comment by Slayug** [comment]
@manast Yes it works fine now, thanks :heart:
