### ISSUE TITLE
Bullmq requires being in a node_modules folder, webpack output fails

### ISSUE THREAD

**Issue by danthegoodman1** [taskforcesh/bullmq#392]
If using bullmq and webpack, I get the following error:

```
[Error: ENOENT: no such file or directory, scandir 'node_modules/bullmq/dist/commands'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'node_modules/bullmq/dist/commands'
}
[Error: ENOENT: no such file or directory, scandir 'node_modules/bullmq/dist/commands'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'node_modules/bullmq/dist/commands'
}
[Error: ENOENT: no such file or directory, scandir 'node_modules/bullmq/dist/commands'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'node_modules/bullmq/dist/commands'
}
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'node_modules/bullmq/dist/commands'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'node_modules/bullmq/dist/commands'
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

It seems that bullmq is trying to access the node_modules folder that doesn't exist. Maybe imports should be updated?

A workaround when using webpack (at least with docker) is use the following dockerfile:

```dockerfile
FROM node:lts-alpine

WORKDIR /app/src

COPY build.js .
COPY .env .
RUN npm init -y # added this to fix
RUN npm i bullmq # added this to fix

CMD ["node", "build.js"]

```

I'll also add for anyone looking for the solution to the `TypeError: n.updateDelaySet is not a function` error, you need the following in your webpack `module.exports` since that error preceded this one in getting bullmq working with webpack and docker/kubernetes:

```
node: {
    // required for __dirname to properly resolve
    // Also required for `bull` to work, see https://github.com/OptimalBits/bull/issues/811
    __dirname: true // and for bullmq to work
  }
```
(see https://github.com/OptimalBits/bull/issues/811)

**Comment by mxzinke** [comment]
You should instead `COPY` your package.json and package.lock file and run `RUN npm install` to fetch your packages. Or do I miss understand your problem?

**Comment by danthegoodman1** [comment]
I have my normal `npm install` and `webpack` commands in another part of my ci/cd pipeline, and I keep the `build.js` output to copy into the container.

package.json
```json
{
  "name": "notificationProcessor",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bullmq": "^1.14.3",
    "dotenv": "^8.2.0",
    "pg-format": "^1.0.4",
    "redis": "^3.0.2",
    "socket.io": "^3.1.1",
    "socket.io-redis": "^6.0.1"
  },
  "devDependencies": {
    "webpack": "^5.21.1",
    "webpack-cli": "^4.5.0"
  }
}
```

webpack
```js
const path = require('path')

module.exports = {
  entry: './index.js',
  output: {
    filename: 'build.js',
    path: path.resolve(__dirname)
  },
  mode: 'production',
  target: 'node',
  resolve: {
    alias: {
      'pg-native': path.resolve(__dirname, 'dummy.js') // To prevent pg-native unresolved error since it is optional dependency of pg
    }
  },
  node: {
    // required for __dirname to properly resolve
    // Also required for `bull` to work, see https://github.com/OptimalBits/bull/issues/811
    __dirname: true // and for bullmq to work
  }
}
```

**Comment by lukepolo** [comment]
since your using webpack make sure to add externals

```
 config.externals = ['clear-env'']; 
```

I tried just doing bull but it seems that it didnt like that so i ended up just copying 


```
      shell.mkdir('-p', `dist/node_modules/bullmq/dist`);
      shell.cp('-r', 'node_modules/bullmq/dist/commands', 'dist/node_modules/bullmq/dist');
```

**Comment by danthegoodman1** [comment]
@lukepolo so you are basically just copying in the file, rather an doing another `npm i bullmq` like I am? That's probably a lot faster than what I was doing!

I'm wondering if this would cause issues in some FaaS...

**Comment by lukepolo** [comment]
correct, im using https://github.com/liady/webpack-node-externals , as we dont want the whole node_modules folder while running in production. 

We instead opt to copy over any binaries that are required . In this case bull also has lua scripts

**Comment by prescience-data** [comment]
Similar issue with `esbuild`, both `bull` and `bullmq` are one of the few packages that cannot be bundled 
(Throws `.addJob() is not a function` error when bundle is executed)

**Comment by roggervalf** [comment]
As in new versions we are pre-processing our lua scripts, this case should be solved

**Comment by ranjan-purbey** [comment]
This is still an issue with with bullmq 5.1.9

Minimal example:

package.json
```json
{
  "devDependencies": {
    "bullmq": "^5.1.9",
    "esbuild": "^0.20.0"
  },
  "type": "module"
}
```

index.js
```javascript
import {Queue} from "bullmq"
```

Build and run:
```bash
$ npx esbuild index.js --bundle --platform=node --outfile=bundle.js
$ node bundle.js
```

Output:
```
ReferenceError: require is not defined in ES module scope, you can use import instead
```

Only workaround is to mark `bullmq` as an external dependency so that it is not included in the bundle.

**Comment by manast** [comment]
@ranjan-purbey this is not the same issue as the one discussed in this post, as this was related to the .lua scripts that are part of BullMQ's installation.

**Comment by ranjan-purbey** [comment]
It seems as the same issue as the OP, I just replaced webpack with esbuild. But the gist is bundling bullmq with bundlers like webpack/esbuild fails and thus it needs to be installed as external dependency instead of being part of the bundle.

Anyway I am happy to open a new issue if you feel the need.

**Comment by manast** [comment]
BullMQ works with bundlers. And this issue is not about bundling BullMQ in general, it is about bundling the .lua scripts, so it is unrelated to what you are experiencing.

**Comment by ranjan-purbey** [comment]
Ok, in that case I will create a new issue. Just to make sure, as you said that bullmq does work with bundlers, are you able to build and run the snippet I shared?

**Comment by manast** [comment]
That It works with bundlers does not mean it will work with any possible settings 😅

**Comment by ranjan-purbey** [comment]
IMO this is the most minimal setup with esbuild. Can you share an example of how to make it work with bundlers then?

**Comment by ranjan-purbey** [comment]
Thanks @lukepolo but this didn't work for me. I will open a new issue.

Fyi I am running it in ESM mode (`"type": "module"` in package.json) and here is the error stacktrace:
```
file:///tmp/a/bundle.js:1002
    var path = require("path");
               ^

ReferenceError: require is not defined
    at node_modules/bullmq/dist/cjs/classes/child-pool.js (file:///tmp/a/bundle.js:1002:16)
    at __require (file:///tmp/a/bundle.js:11:50)
    at node_modules/bullmq/dist/cjs/classes/index.js (file:///tmp/a/bundle.js:38581:26)
    at __require (file:///tmp/a/bundle.js:11:50)
    at node_modules/bullmq/dist/cjs/index.js (file:///tmp/a/bundle.js:41625:26)
    at __require (file:///tmp/a/bundle.js:11:50)
    at file:///tmp/a/bundle.js:41636:64
    at async file:///tmp/a/bundle.js:41636:21

Node.js v20.8.0
```
