### ISSUE TITLE
Repeatable jobs need serious work

### ISSUE THREAD

**Issue by nemphys** [taskforcesh/bullmq#396]
I just started using Bull for my new project and I am using repeatable cron jobs for some maintenance tasks.

After implementing the required functionality with Bull v3, I realised that I will definitely need the ability to fetch jobs by key pattern (PR #277 currently pending in this repo), so I decided to switch to BullMQ (seems to be the new, more actively maintained version anyway).

To my surprise, I found out that a lot the repeatable jobs-related functionality has changed here (without any proper documentation), so I am banging my head to figure out how to get things working again.

I have a few repeatable jobs that should always be present, so I check for their existence on each application startup and add them if they are missing (or update them if eg. the cron schedule is wrong/has changed).

With Bull v3, the jobId was what mattered for job identification (though it would be nice to be able to *find* the job by its id, instead of having to retrieve all repeatable jobs and then find it manually) and one could remove the job by its key using removeRepeatableByKey().

In BullMQ, it seems that the jobId is *completely ignored* and I realise that it does not even appear on the documentation anymore; it does not affect the job key on Redis, which apparently is now affected by the job *name* (which is also now required in BullMQ, in contrast to Bull v3, where it is optional) and it does not show up in the job properties when fetching repeatable jobs using getRepeatableJobs(); this is non-intuitive, since the job name is supposed to represent something more like the job "category", not the job "instance".

Furthermore, when a repeatable job is removed using removeRepeatableByKey() (using the key property of the job returned by getRepeatableJobs()), only the *future scheduling* of this job is actually removed, with the next *actual job instance left intact in the queue*. There is already an issue for this, but has been closed(?) as a duplicate in Bull v3 (I don't get this, isn't BullMQ a -apparently very- different project and should handle its issues separately?)

In general, I think that (apart from the fact that the documentation of BullMQ is still very sparse, which I don't judge but makes things very difficult to debug) the whole repeatable jobs thing should either be shown some love or maybe be removed altogether.

**Comment by manast** [comment]
Thanks for the issue, I am working on this today.

**Comment by manast** [comment]
I also added some more documentation: https://app.gitbook.com/@taskforce/s/bullmq/guide/jobs/repeatable
