### ISSUE TITLE
How to update progress of a job?

### ISSUE THREAD

**Issue by franklevasseur** [taskforcesh/bullmq#398]
Hi,

The [documentation](https://docs.bullmq.io/guide/workers) states that you can update the progress of a job calling "job.progress":

"Inside the worker process function it is also possible to emit progress events. Calling "job.progress" you can specify a number or an object if you have more complex needs."

But my compiler seems to tell me that progress is not a function:

![image](https://user-images.githubusercontent.com/25970722/108075470-6599f480-7038-11eb-8164-6e09e648c059.png)

I search you typings (".d.ts") and found nothing to update progress...

How do you do such a thing?

**Comment by franklevasseur** [comment]
Found it!

Guess I didnt look weel enough.

its: `job.updateProgress()`

**Comment by manast** [comment]
thanks. I will update the documentation right away.
