### ISSUE TITLE
Question: Bullmq connection with redis cluster not added in types

### ISSUE THREAD

**Issue by gurbaj5124871** [taskforcesh/bullmq#406]
The types when creating queue accepts connection arg which has the type of RedisOptions or Redis and not the RedisCluser.
```
export declare type ConnectionOptions = RedisOptions | Redis;
```

So the question is does bullmq supports redis cluser or the types are not up to date?

**Comment by manast** [comment]
In theory it should work with redis cluster however there is no benefit by using it since a queue including all its jobs must all be in the same node, you can read more about it here: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster

**Comment by gurbaj5124871** [comment]
> In theory it should work with redis cluster however there is no benefit by using it since a queue including all its jobs must all be in the same node, you can read more about it here: https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster

I have a redis cluster which i wanted to reuse for bull as well. Although the jobs related to a queue will be in same node but its better than having all the queues on the same node in case of non clustered redis.

So this means that the types are not up to date

**Comment by manast** [comment]
> So this means that the types are not up to date

exactly.
