### ISSUE TITLE
Proces one job at time

### ISSUE THREAD

**Issue by Zikoel** [taskforcesh/bullmq#412]
First, Thank you for this `masterpiece`! I very like bull and bullmq!

In my use-case have some very heavy (CPU and memory) and slow jobs! I want to be sure that only one job per worker is executing! What is in your opinion the best way to do that with this library. Exploring the docs I only see a temporary rate limiter not `how many job per worker` limiter! I will try with some tests for sure but I want an opinion from more expert users.

**Comment by manast** [comment]
Just make sure that you are only running 1 workers with concurrency factor 1 at any moment in time.
