### ISSUE TITLE
Sandboxed updateProgress()

### ISSUE THREAD

**Issue by codetheweb** [taskforcesh/bullmq#414]
I think that either the types or the function parameters are messed up for sandboxed processes in regards to `Job.updateProgress()`. The function is available when using non-sandboxed workers, but it's not part of the job object passed to sandboxed processors (however, `Job.progress()` is a thing).

**Comment by manast** [comment]
yes I see what you mean, thanks for reporting!

**Comment by JosephScript** [comment]
It also doesn't have `job.isActive` or any of the other functions:

```js
{
  id: '1',
  name: '1',
  data: {
    id: '1',
  },
  opts: {
    attempts: 10,
    delay: 5000,
    jobId: '1',
    backoff: { type: 'custom' }
  },
  progress: [Function: progress],
  attemptsMade: 0,
  processedOn: 1618000638460,
  timestamp: 1618000573242,
  stacktrace: '[]',
  returnvalue: 'null',
  returnValue: null,
  log: [Function: log]
}
```

**Comment by JosephScript** [comment]
I'm not sure if I should open a new issue or not since it seems related, but the event listeners also do not work on Sandboxed processors:

```js
const processorFile = path.join(__dirname, 'processor.js')

const worker = new Worker(qName, processorFile, {
  limiter: {
    max: 10,
    duration: 1000,
  },
  connection: redis,
  settings: {
    backoffStrategies: {
      //...
    },
  },
})

// None of these are firing:
worker.on('progress', (job, progress) => {
  console.info(`Job Progress: ${progress}`)
})
worker.on('completed', (job) => {
  console.info(`Job Complete: ${job.id} has completed!`)
})

worker.on('stalled', (job) => {
  console.error(`Job Error: ${job.id} has stalled.`)
})

worker.on('failed', (job, err) => {
  console.error(`Job Error: ${job.id} has failed with: ${err.message}\n${err}`)
})
```

**Comment by roggervalf** [comment]
@JosephScript, I'm seeing test cases for completed, failed, progress, and active events for example on https://github.com/taskforcesh/bullmq/blob/master/src/test/test_sandboxed_process.ts#L39, maybe you could check that test file
