### ISSUE TITLE
@user_script:86: user_script:86: too many results to unpack

### ISSUE THREAD

**Issue by hasparus** [taskforcesh/bullmq#422]
Hi! That's my first issue, so firstly I wanted to thank you folks for BullMQ!
We're using it quite a lot with @andreasasprou and this is the first problem I encountered.

After scaling up our workers, we've noticed a new error

```
ERR Error running script (call to f_890be59efdd64a4df5f5121df9680b166a884036): @user_script:86: user_script:86: too many results to unpack
```

I looked around the repository, and found `unpack` in two places

Once in [_updateDelaySet-7.lua_](https://github.com/taskforcesh/bullmq/blob/297ec30086bd0d95b10718c128409e535414180f/src/commands/updateDelaySet-7.lua#L27) with a table at most 1000-elements big, and the second time in [_moveStalledJobsToWait-8.lua in line *86*_](https://github.com/taskforcesh/bullmq/blob/297ec30086bd0d95b10718c128409e535414180f/src/commands/moveStalledJobsToWait-8.lua#L85-L86) with all jobs from `KEYS[3] 'active'`.

https://github.com/taskforcesh/bullmq/blob/297ec30086bd0d95b10718c128409e535414180f/src/commands/moveStalledJobsToWait-8.lua#L85-L86

I'm reading that calling unpack with more than 8k elements is known to crash.
- https://devforum.roblox.com/t/unpack-limit-fix/213862
- https://stackoverflow.com/questions/19202367/how-to-avoid-redis-calls-in-lua-script-limitations

I wanted to ask about limits of bullmq — should we try to scale Bull and Redis instances when dealing tens of thousands of jobs?
Or is this just a software bug, that could be solved with iteration over `active` and calling `unpack` with batches of 7000 (`unpack(active, from_index, to_index)`)?

**Comment by hasparus** [comment]
Here is a diff with a potential solution.

```diff
diff --git a/node_modules/bullmq/src/commands/moveStalledJobsToWait-8.lua b/node_modules/bullmq/src/commands/moveStalledJobsToWait-8.lua
index 0285201..cce3af5 100644
--- a/node_modules/bullmq/src/commands/moveStalledJobsToWait-8.lua
+++ b/node_modules/bullmq/src/commands/moveStalledJobsToWait-8.lua
@@ -81,9 +81,27 @@ if (#stalling > 0) then
     end
 end
 
+-- Divide n into equal size batches
+local function batches(n, batchSize)
+  local i = 0
+
+  return function()
+    local from = i * batchSize + 1
+    i = i + 1
+    if (from <= n) then
+      local to = math.min(from + batchSize - 1, n)
+      return from, to
+    end
+  end
+end
+
 -- Mark potentially stalled jobs
 local active = rcall('LRANGE', KEYS[3], 0, -1)
-if (#active > 0) then rcall('SADD', KEYS[1], unpack(active)) end
+if (#active > 0) then
+  for from, to in batches(#jobs, 7000) do
+    rcall('SADD', KEYS[1], unpack(jobs, from, to))
+  end
+end
 
 local maxEvents = rcall("HGET", KEYS[6], "opts.maxLenEvents")
 if maxEvents then rcall("XTRIM", KEYS[8], "MAXLEN", "~", maxEvents) end
```

**Comment by manast** [comment]
Hello @hasparus. It seems that you indeed have reached a limit in the lua script implementation used by redis.
thanks for the patch, I am studying it, but my first impression is that it could be a bit slow, since iterating arrays in .lua is not super fast. I will check if there is some native lua way to divide arrays in batches.

**Comment by manast** [comment]
ok, so I think it would be more optimal to do use redis LRANGE to get the jobids in batches. So first doing a LLEN will return the total length, if it is larger than 8k start getting in batches with LRANGE until the whole list has been consumed.
I can create a PR for this but I cannot give an ETA. If you have time to do it quickly I would accept the PR if it passes all the tests (would be greate to even have a test for the case where there are more than 8k active jobs at once).

**Comment by hasparus** [comment]
>  but my first impression is that it could be a bit slow, since iterating arrays in .lua is not super fast. I will check if there is some native lua way to divide arrays in batches.

But, I'm not iterating the array?... at least I don't think so, I last wrote Lua a few years ago.
My patch in "pseudocode" should be more or less 
```
window = { from: 0, to: 7000 }
until window.to > active.length
  SADD(KEYS[1], ...take(jobs, from: window.from, to: window.to)
  move window by 7000 to the right
```

I assume `unpack` does some iteration here, but iterating through entire `active` and iterating through `active` in batches of 7000 shouldn't be much different (right? I'm truly not a Lua guy). My code does more `SADD` calls, though, and I admit, I may have overengineered it a bit with that generator.

> If you have time to do it quickly I would accept the PR if it passes all the tests (would be greate to even have a test for the case where there are more than 8k active jobs at once).

I fiddled for a moment with tests and I didn't manage to fail them with tens of thousands jobs :sweat: 
The bug can be reproduced locally on my machine and it happened on our production, so I may have approached it wrongly.

**Comment by manast** [comment]
> But, I'm not iterating the array?... at least I don't think so, I last wrote Lua a few years ago.

ah ok, sorry I did not understand the code completely at a fast glance. So basically it is just unpack consuming different parts of the array which we could presume is fast enough.

> I fiddled for a moment with tests and I didn't manage to fail them with tens of thousands jobs 😓
The bug can be reproduced locally on my machine and it happened on our production, so I may have approached it wrongly.

Could it be the version of redis? Maybe the one you use in production has this limitation but the one running locally doesn't? Btw, the amount of jobs wouldn't be the culprit here if I understand the issue correctly, but rather the amount of jobs plus the amount of concurrent workers (so that you can end having more than 8k active jobs at a given time.

**Comment by hasparus** [comment]
> Maybe the one you use in production has this limitation but the one running locally doesn't?

Well, I can crash it with my app even on locally running Redis, but I failed to crash tests here.
I am familiar with this Lua limitation, and it's quite well known in the internet, so question here is _when can `active` become larger than 8000 items?_

**Comment by manast** [comment]
@hasparus you need to have a number of workers times concurrency per worker > 8000 and a queue that has enough items to keep all the workers busy at max capacity.
Anyway, I think we should merge this fix even if we cannot reproduce it in a test case, because that case would be really heavy to run anyway in a CI system.

**Comment by orgalaf** [comment]
getting this too! 
version 1.15.1
````
scraper-77488cd598-mvpz9 scraper-0 unhandledRejection ReplyError: ERR Error running script (call to f_890be59efdd64a4df5f5121df9680b166a884036): @user_script:86: user_script:86: too many results to unpack
scraper-77488cd598-mvpz9 scraper-0     at parseError (/usr/local/lib/node_modules/@activefence/scraper/node_modules/redis-parser/lib/parser.js:179:12)
scraper-77488cd598-mvpz9 scraper-0     at parseType (/usr/local/lib/node_modules/@activefence/scraper/node_modules/redis-parser/lib/parser.js:302:14) {
scraper-77488cd598-mvpz9 scraper-0   command: {
scraper-77488cd598-mvpz9 scraper-0     name: 'evalsha',
scraper-77488cd598-mvpz9 scraper-0     args: [
scraper-77488cd598-mvpz9 scraper-0       '890be59efdd64a4df5f5121df9680b166a884036',
scraper-77488cd598-mvpz9 scraper-0       '8',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:stalled',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:wait',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:active',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:failed',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:stalled-check',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:meta',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:paused',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:events',
scraper-77488cd598-mvpz9 scraper-0       '1',
scraper-77488cd598-mvpz9 scraper-0       'bull:dc:executions:scraper:extract-media-links:default:',
scraper-77488cd598-mvpz9 scraper-0       '1623472439517',
scraper-77488cd598-mvpz9 scraper-0       '30000'
scraper-77488cd598-mvpz9 scraper-0     ]
scraper-77488cd598-mvpz9 scraper-0   }
scraper-77488cd598-mvpz9 scraper-0 }
````

**Comment by hasparus** [comment]
> Anyway, I think we should merge this fix even if we cannot reproduce it in a test case, because that case would be really heavy to run anyway in a CI system.

Hey @manast, since it's also happening for @orgalaf, should I create a PR with the change I mentioned in https://github.com/taskforcesh/bullmq/issues/422#issuecomment-795809696? We worked around the problem, so it doesn't affect me anymore, but it could save a surprise for other people.

**Comment by manast** [comment]
@hasparus sure, that would be great if it saves time and issues to other users.

**Comment by plus-** [comment]
Hello @hasparus 

Since the issue was not reproduced and the patch merged without testing, it would be amazing if you could confirm the patch did fix your problem.

cheers

**Comment by hasparus** [comment]
hey @plus- , yeah it did. Did you encounter a similar problem?

**Comment by plus-** [comment]
Yes on the Bull library, I've opened a PR with your fix here https://github.com/OptimalBits/bull/pull/2340
