### ISSUE TITLE
add jobs to queues without creating separate Queue object

### ISSUE THREAD

**Issue by andrisi** [taskforcesh/bullmq#423]
Is there a case for a BullMQ class perhaps with a method to add job/jobs to any queue? From the producer side it would simplify clients if we don't need notifications per queue, and even that could be part of this higher level API. I know, I can reuse the connection, so in essence this connection is used as a higher level API, creating/destroying Queue classes using it as we need to add jobs.

**Comment by manast** [comment]
A Queue instance only requires one connection in order to add jobs to the queue. Events are handled in the QueueEvents class so if you don't need them no extra connections needed.

**Comment by andrisi** [comment]
I'd need events too, preferably for all queues in one API (connection) but as you said, redis connections are "cheap" so no problem. Perhaps it is something to think about for the BullMQ module for redis: a not per-queue API. Thanks.

**Comment by manast** [comment]
> I'd need events too, preferably for all queues in one API (connection) but as you said, redis connections are "cheap" so no problem. Perhaps it is something to think about for the BullMQ module for redis: a not per-queue API. Thanks.

In the redis BullMQ module you can use multiple queues with the same connection, however some operations are blocking so while they are blocked you cannot use that same connection for other operations.
