### ISSUE TITLE
Prefix is not consistent 

### ISSUE THREAD

**Issue by rileyai-dev** [taskforcesh/bullmq#424]
@manast OK, after several hours of investigation, I think I know what the problem is...

```js
(async ()=>{

    const { Queue, Worker } = require('bullmq');
    const Redis  = require("ioredis");

    const connection = new Redis(
        {keyPrefix:'myPrefix:'}
    )

    const queue = new Queue('myQueue', {connection});

    await queue.add('test', {hello:'world'});

    new Worker('myQueue', (job)=>{
        return 'processed';
    }, {connection})

})()
```

This simple test fails with: `Error: Missing lock for job 1 failed` and the Redis DB looks like:

1) "myPrefix:bull:myQueue:1"
2) "bull:myQueue:1"
3) "myPrefix:bull:myQueue:events"
4) "myPrefix:bull:myQueue:active"
5) "myPrefix:bull:myQueue:meta"
6) "myPrefix:bull:myQueue:id"
7) "bull:myQueue:1:lock"

The prefix is not added when a job is added to the queue (which leads to the error). I've tested with delayed jobs and it's the same issue.

**Comment by grapevineai** [comment]
@manast Any chance we can have a quick fix here?

**Comment by manast** [comment]
no fix is needed, as I mentioned earlier you must not use the prefix functionality from ioredis, instead use the "prefix" option when creating the connection: 
https://github.com/taskforcesh/bullmq/blob/3a8873b6453405e6f8e57331f6cee30977406670/docs/gitbook/api/bullmq.queuebaseoptions.md

**Comment by grapevineai** [comment]
@manast I understand that...but either BullMQ completely ignore the prefix of IORedis OR it is compatible with it! The current implementation doesn't make sense and is extremely confusing. I have one instance of redis client used throughout the entire app which has a prefix. If I use this instance to initialize the queue, BullMQ will be buggy and won't work. In addition, the documentation doesn't warn the user not to use the keyPrefix of IORedis.

IMHO this is a real bug that should be addressed. Either the IORedis prefix is ignored or it is completely supported by BullMQ, not something in between that makes BullMQ crash...

**Comment by grapevineai** [comment]
Also, what would be the "cost" of supporting keyPrefix when adding a job? This is the only missing part of supporting keyPrefix...

**Comment by manast** [comment]
As I see it, the only bug would be not giving an error if ioredis prefix is defined, and of course improve the documentation as I labeled the issue for that. Supporting ioredis auto-prefix is not compatible with BullMQ... it is a small inconvenience but easy to get  around it.

**Comment by grapevineai** [comment]
So why not just completely ignore it? At least the behavior would be consistent...

**Comment by grapevineai** [comment]
@manast The problem here is that adding a keyPrefix to a unique IORedis client instance is convenient especially if you want to change it. It avoids errors and dev issues by centralizing where the prefix is managed. By ignoring it, it would give us the opportunity to reference the prefix throughout the code `connection.keyPrefix` to add it to everything that is related to BullMQ.

**Comment by grapevineai** [comment]
@manast Would you be interested in opening a reward on Issuehunt to support IORedis auto-prefix? This would tremendously simplify our code.

**Comment by manast** [comment]
> So why not just completely ignore it? At least the behavior would be consistent...

It is ignored, thats why it does not work. When we write to keys inside .lua scripts ioredis cannot auto-prefix the keys.

**Comment by grapevineai** [comment]
@manast It is not completely ignored since it creates default keys with the prefix:

"myPrefix:bull:myQueue:1"
"bull:myQueue:1"
"myPrefix:bull:myQueue:events"
"myPrefix:bull:myQueue:active"
"myPrefix:bull:myQueue:meta"
"myPrefix:bull:myQueue:id"
"bull:myQueue:1:lock"

**Comment by manast** [comment]
check the code if you dont believe me, that setting is completely ignored.

**Comment by manast** [comment]
> @manast Would you be interested in opening a reward on Issuehunt to support IORedis auto-prefix? This would tremendously simplify our code.

why can't you just create a different redis connection for BullMQ instead of reusing it for other operations?

**Comment by grapevineai** [comment]
@manast I believe you but how do you explain the behavior I described? Simply test with the code I provided and you will see...

**Comment by grapevineai** [comment]
> > @manast Would you be interested in opening a reward on Issuehunt to support IORedis auto-prefix? This would tremendously simplify our code.
> 
> why can't you just create a different redis connection for BullMQ instead of reusing it for other operations?

Coherence of code... If the code I wrote was working without prefix, I'd be fine...but it's not! Future dev would probably fall into the same trap and will waste a couple of hours until they figure.

**Comment by manast** [comment]
As mentioned we can throw an exception if you use auto-prefix. But since we need to write to keys inside .lua scripts, and since BullMQ already provides auto-prefix functionality this is a small inconvenience to pay, vs more code to maintain and possible other  bugs.

**Comment by grapevineai** [comment]
@manast Ok, I understand even if I don't really agree. The exception is the minimum a dev would expect so the library works as expected no matter what the configuration is.

**Comment by grapevineai** [comment]
Feel free to close this issue whenever you think it's done

**Comment by manast** [comment]
@fgozdz the thing to do here is to throw an exception in the QueueBase if the passed Redis connection includes a prefix in its options as this not compatible with BullMQ.

**Comment by manast** [comment]
oh, it is actually fixed already: https://github.com/taskforcesh/bullmq/blob/master/src/classes/redis-connection.ts#L88
