### ISSUE TITLE
Doc: Wrong comment on code sample on documentation

### ISSUE THREAD

**Issue by ozanmuyes** [taskforcesh/bullmq#426]
On [FIFO Jobs documentation page](https://docs.bullmq.io/guide/jobs/fifo) the first code sample has wrong comment, it should read "after" not "before". So instead of

```js
// Add a job that will be processed before all others
```

this should be written

```js
// Add a job that will be processed after all others
```

**Comment by manast** [comment]
good catch!. I have updated it now.
