### ISSUE TITLE
Pausing delayed jobs runs immediately after resume

### ISSUE THREAD

**Issue by hsynlms** [taskforcesh/bullmq#427]
I am using `bullmq`  and almost done the integration part. Yes, documentation is a bit poor and so I needed to do a lot of searches. I may be a contributor if possible in the future who knows.

I struggled in pausing delayed jobs. Let's assume that I gave random `delay`'s to the jobs between 0-60 (seconds). And after adding those to the queue I invoked the queue's `pause` method. I waited 60 seconds. Then resumed the queue. All the jobs are processed immediately.

**What did I expect:**
Jobs should have been frozen and stopped calculating delays while being paused and continue to count down after the resume method is invoked.

**Comment by manast** [comment]
The pause method does not affect the delayed jobs. A delayed job is stored as a future timestamp and thats when it will be processed if there are unpaused workers running.

**Comment by hsynlms** [comment]
Do you think it would be a good thing to re-calculate timestamps before resuming the queue? Maybe a feature request?

**Comment by manast** [comment]
sure... it is possible, a matter of atomically storing the pause timestamp and then when unpausing calculating the time the queue was paused and update accordingly all the delayed jobs.

**Comment by roggervalf** [comment]
we didn't prioritize this kind of feature but as a workaround, [changeDelay](https://docs.bullmq.io/guide/jobs/delayed#change-delay) per each delayed job record, calculation could be handled by the user
