### ISSUE TITLE
[Feature request] Function to remove all jobs from Queue including Repeatable

### ISSUE THREAD

**Issue by MurzNN** [taskforcesh/bullmq#430]
With active development very often Queues accumulate many test jobs, especially when experimenting with delayed and repeatable jobs.
But I can't find the easy way to cleanup the Queue (excluding manual removing from Redis), to remove all jobs from Queue, including delayed and repeatable.

At now I see the `drain()` and `clean()` functions, but they didn't remove the repeatable jobs.

Also exists the `removeRepeatable()` and `removeRepeatableByKey()`, but we need to know the name+options or key of each job to delete.

As result, there is not so easy to "cleanup" the queue, to start from scratch.

Will be good to have some function like `cleanAll()` or `deleteQueue()` to make "full cleanup" of named Queue, for remove all records about it jobs in database for this Queue, including delayed, repeatable, finished, etc.

**Comment by MurzNN** [comment]
At now I have this code to cleanup:
```js
const myQueueName = 'foo'
const myQueue = new Queue(myQueueName);

let repeatableJobs = await myQueue.getRepeatableJobs()
repeatableJobs.forEach(async job => {
    await myQueue.removeRepeatableByKey(job.key);
})
myQueue.drain(true);
myQueue.clean();
```
but still see 45 records about this job in redis via mask `bull:foo:`:
```
$ redis-cli --scan --pattern 'bull:foo:*' | wc -l
45
```

**Comment by manast** [comment]
I will prioritize this up since it is a common request!.

**Comment by xiaoyu-tamu** [comment]
@manast  thank you

**Comment by manast** [comment]
I noticed that the implementation is not completely safe if you happen to use queue names with the ':' character as part of its name, so I released a patch for this (https://github.com/taskforcesh/bullmq/pull/435), so please update to version 1.15.1 to eliminate this risk.
