### ISSUE TITLE
Delayed and Repeatable parameters together in one Job not working

### ISSUE THREAD

**Issue by MurzNN** [taskforcesh/bullmq#431]
I need to use both `delay` and `repeat` parameters in BullMQ Job instance, for make a delay of first job execution, so I compose code like this:
```js
import { Queue, QueueScheduler } from 'bullmq';

const myQueueName = 'foo'
const myQueue = new Queue(myQueueName);
const myQueueScheduler = new QueueScheduler(myQueueName);

async function addJobs(){
    await myQueue.add('job_delayed', {}, {
        delay: 20000,
        repeat: {
            every: 5000,
            limit: 10
        }
    });
}

await addJobs();

let timeStart = new Date();

import { Worker } from 'bullmq'

const worker = new Worker(myQueueName, async job => {
    console.log('secs from start: ' + (new Date() - timeStart) / 1000 + ' - ' + job.name);
});
```
And the problem is that the first job launch is happens at 5 sec delay, instead of 20 sec, here is output:
```
$ node ./index.js
secs from start: 4.735 - job_delayed
secs from start: 9.654 - job_delayed
secs from start: 14.67 - job_delayed
secs from start: 19.691 - job_delayed
secs from start: 24.71 - job_delayed
secs from start: 29.732 - job_delayed
```

**Comment by MurzNN** [comment]
If I comment-out the `repeat section`:
```js
async function addJobs(){
    await myQueue.add('job_delayed', {}, {
        delay: 20000,
        // repeat: {
        //     every: 5000,
        //     limit: 10
        // }
    });
}
```
delay works well:
```
$ node ./index.js
Starting worker
secs from start: 20.022 - job_delayed
```

**Comment by manast** [comment]
The delay cannot be combined with repeat, we should definitively throw an exception to avoid misunderstandings. However there is the "startDate" property that you can use, however it only works with "cron" expressions, not with "every". Maybe this is a workaround for your case.

**Comment by MurzNN** [comment]
Thanks for clarification, I need the job that will be started, for example, at 3 hours after start, and repeats unlimited time every 10 minutes. If this cannot be combined, it's better to implement this in worker logic, or you can recommend some better solution?

**Comment by manast** [comment]
Why cant you use a cron expression like * */10 * * * * ?
https://www.npmjs.com/package/cron-parser

**Comment by MurzNN** [comment]
> Why cant you use a cron expression like * */10 * * * * ?
> https://www.npmjs.com/package/cron-parser

Because I need the startup delay for 3 hours, together with `*/10`

**Comment by manast** [comment]
I wrote above you can use "startDate" too.

**Comment by MurzNN** [comment]
Ok, thanks, this is the solution too!
