### ISSUE TITLE
[Feature] Call Worker and QueueScheduler methods without launching the process

### ISSUE THREAD

**Issue by bogdan** [taskforcesh/bullmq#436]
Manually processing jobs like this: https://docs.bullmq.io/patterns/manually-fetching-jobs can cause problems because `new Worker` launches the process instantly. This can cause a lot of unpredictable effects in support scripts if I just want to manually resolve issues in a queue without processing any single job from there.

Is it possible to add a constructor option to prevent the process from being launched instantly. Like:

```
const worker = new Worker(name, () => {}, {autorun: false})
```

Overall, I think calling `run()` in constructor is an anti-pattern: you don't make all the methods of `Worker` class easily accessible this way.

**Comment by manast** [comment]
> Manually processing jobs like this: https://docs.bullmq.io/patterns/manually-fetching-jobs can cause problems because `new Worker` launches the process instantly.

No, it does not. If you do not define a process function the worker will not do anything.


> Overall, I think calling `run()` in constructor is an anti-pattern: you don't make all the methods of `Worker` class easily accessible this way.

I can agree on this. However not the comment above, it does not work as you assumed.

**Comment by bogdan** [comment]
Good to know about missing processor, however this is something that is not very obvious. It probably requires at least documentation.

It is interesting that redis connection is always cloned. Maybe this is required for "launch" mode with processor, but is it required for "support" mode without processor?

**Comment by manast** [comment]
> It is interesting that redis connection is always cloned. Maybe this is required for "launch" mode with processor, but is it required for "support" mode without processor?

yes, that must be an oversight from my part, the connection does not need to be clones in this case at all.

**Comment by bogdan** [comment]
@roggervalf looks good! Can you also add methods I mentioned in https://github.com/taskforcesh/bullmq/issues/436#issuecomment-804891421 or can I open another issue to add them?

**Comment by manast** [comment]
@bogdan regarding my comment above. Although technically you do not need to duplicate the connection, in practice whatever connection you use will be block as soon as you call ```getNextJob```. So I think the duplication makes sense to be performed always to avoid weirs issues where the user expects something to happen but nothing happens because the connection is blocked.
