### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by codetheweb** [taskforcesh/bullmq#442]
I recently have been seeing a large increase in errors like this:

```
Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at processTicksAndRejections (node:internal/process/task_queues:94:5)
-- | -- | -- | --
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at runMicrotasks (<anonymous>)
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at /usr/app/node_modules/bullmq/dist/classes/master.js:91:27
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at bound  (node:internal/util:311:12)
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at new Promise (<anonymous>)
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at node:internal/util:325:7
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at process.target.send (node:internal/child_process:722:19)
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at process.target._send (node:internal/child_process:822:17)
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at writeChannelMessage (node:internal/child_process/serialization:120:20)
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | at stringify (<anonymous>)
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | --- property 'request' closes the circle
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | \|     property 'errored' -> object with constructor 'Object'
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | \|     property '_readableState' -> object with constructor 'ReadableState'
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | --> starting at object with constructor 'Request'
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | TypeError: Converting circular structure to JSON
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | ^
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | throw err;
  | Mar 29 10:45:54.487 | maxkvm-42196.local | backend | /usr/app/node_modules/bullmq/dist/classes/master.js:114
```

It's throwing on this line: https://github.com/taskforcesh/bullmq/blob/c2cfc965a05d1f2292e81b3819426059a7d5795f/src/classes/master.ts#L121

I believe the root cause is an error from [Got](https://www.npmjs.com/package/got). Would it be possible to add some kind of check here so circular structures in errors don't cause Bull to crash?

**Comment by manast** [comment]
Do you have a suggestion on how to implement this? as I understand, this happens because some unhandled exception in user code, it is mostly informing you that you have some unhandled error somewhere.

**Comment by codetheweb** [comment]
Maybe attempt to do `JSON.stringify(err)` and if that throws then it's circular?

As long as it doesn't have any impact on Bull's operation it's not a big deal, but it would be nice to have a more user-friendly error.

**Comment by manast** [comment]
If you are doing an operation that can throw an exception than you should handle that exception, like wrapping it in a try/catch statement. BullMQ wraps your processor in a try/catch already, so topmost exceptions are caught and results in the job failing. My guess is that you are calling that stringify in some callback deeper down the stack, then there is nothing we can do other than what we are already doing, i.e. bring to your attention that you have an unhandled exception somewhere in your code.

**Comment by codetheweb** [comment]
Ah you're probably right, thank you.
