### ISSUE TITLE
Alternative to named processors?

### ISSUE THREAD

**Issue by prescience-data** [taskforcesh/bullmq#448]
Currently migrating from Bull 3, and not certain I understand what the new/alternative implementation of named processors is.

In the existing codebase, there is a server that receives jobs over http, parses the payload and then dispatches the job on a named process _("channel")_. 

```typescript
// Setup job routing.
const { zone, hardware, action, data } = request
// Define channel, eg "us-west:c5.xlarge:process-data" / "us-east:process-data"
const channel = [ zone || "", hardware || "", action || "process-data" ].filter(part => part !== "").join(":")
const options = {  attempts: 1, timeout: 30000 }

// Dispatch job.
const job: BullJob<SocketPayload> = await bullQueue.add(
  channel,
  data,
  options
)

// Await result.
const result = await job.finished()
```

In this case, there are workers running on hot instances that subscribe to a channel stack that represent their capability and scope such as:

```typescript

export class DataProcessor {
 
  public readonly queue: BullQueue = new Queue()
  public readonly channels: string[] = [
    "us-west:c5.xlarge:process-data", 
    "us-west:process-data", 
    "c5.xlarge:process-data", 
    "process-data"
  ]
  // ....
  public async subscribe(hook) {
    for(const channel of this.channels) {
      this.queue.process(channel, 1, hook)
     }
  }
  // ...
}

```

This means I can send a job to the `"us-west:c5.xlarge:process-data"` channel to target a specific region and hardware, or just `"process-data"` if I don't care how the processing is done, all of which run on the on the single `"foo-queue"` queue.

I can't see a way to use individual queues for this, as that would require an individual worker for each "channel as a queue" which breaks my "concurrency of 1" per instance. 

Just want to see what the "new" way to achieve this would be with BullMQ?

> PS: Note that the architecture described is just an abstract shorthand, in this above case there are probably ways to refactor it but for the sake of this problem assume that the use-case is very specific and needs this _"one long-running worker, one queue, many channels, single concurrency per worker"_ pattern.)

> Additionally, naturally the "named processors" in Bull 3 break the "single concurrency" requirement, but currently we immediately set a flag on the Processor class which rejects/returns any intermediate jobs while the worker pauses itself on the queue, so that might be useful for anyone kind enough to give feedback on how to achieve this.

**Comment by manast** [comment]
Functionality wise, Bullv3 and BullMQ provides the same, it just that the syntax is different. In BullMQ you only define 1 processor, and then inside the processor you can choose different code paths depending on the "job.name" property. In your case this will mean a bit more of code, but named processors where causing a lot of confusion so we decided to remove the syntax sugar and made it more explicit.

**Comment by prescience-data** [comment]
Thanks so much for the reply!

So if a job comes in on queue `foo` that matches none of the target job names, wouldn't it just fail?

### factories.ts
```typescript
// ./factories.ts
export const makeWorker = (
  processor,
  { name, connection }: QueueConfig
): BullWorker => {
  return new Worker(parseQueueName(name), processor, {
    connection: connection || config.connection,
    concurrency: 1
  })
}

```
### hooks.ts
**_This is the part I'm not sure I fully understand how to handle?_**
```typescript
// ./hooks.ts
export const processData = (channels: string[]): JobProcessorHook => async (job: Job): Promise<SomeAsyncResult> => {
  if (!channels.includes(job.name)) {
    throw new Error(`Worker not assigned job name ${job.name}`)
  }

  // ... Handle job logic
  return await doSomeAsyncProcessing()
}
```

### worker.ts
```typescript
// ./worker.ts
import { channels } from "./channels"
import { processData } from "./hooks"
import { makeWorker } from "./factories"

const name: string = "foo-queue"
const channels: string[] = [
  "us-west:c5.xlarge:process-data",
  "us-west:process-data",
  "c5.xlarge:process-data",
  "process-data"
]

const myDataWorker = makeWorker(processData, { name, channels, connection })

```

**Comment by acro5piano** [comment]
I had a similar confusion to @prescience-data .

>  In BullMQ you only define 1 processor, and then inside the processor you can choose different code paths depending on the "job.name" property

So single processor (worker) and single queue with full type-safety code should be like this?

```ts
import { Queue } from 'bullmq'

type JobArgument = 
  | { type: 'JOB_A', payload: { foo: string } 
  | { type: 'JOB_B', payload: { bar: number } 

// Create main queue and main worker
const mainQueue = new Queue('main');
const mainWorker = new Worker('main', async (job: Job<JobArgument>) => {
  switch (job.type) {
    case 'JOB_A':
      return processJobA(job)
    case 'JOB_B':
      return processJobB(job)
    default:
      throw new Error(`Invalid job name: ${job.type}`)
  }
}, { concurrency: 50 })

function addTaskToQueue(arg: JobArgument) {
  return mainQueue.add(job.type, arg.payload)
}

// Somewhere in code
await addTaskToQueue({ type: 'JOB_A', payload: { foo: 'pink' } });
```

**Comment by prescience-data** [comment]
My concern is:

>  "If the worker throws an exception during its processing, the job will automatically be moved to the "failed" status."

I don't think that's what I actually want to happen in this case (moving the job to failed), it seems like I need the worker to simply not receive the job in the first place and let and let the correct worker assigned to that job name pick it up?

**Comment by manast** [comment]
> I don't think that's what I actually want to happen in this case (moving the job to failed), it seems like I need the worker to simply not receive the job in the first place and let and let the correct worker assigned to that job name pick it up?

Thats not possible, neither with BullMQ nor Bull v3.

**Comment by prescience-data** [comment]
It seemed to work in Bull 3? 
But I'm definitely not clear on what was actually happening under the hood?
The flow I had was each worker "subscribed" to the named processors it was responsible for, then paused itself locally on the queue immediately after receiving a job.

**Comment by manast** [comment]
> It seemed to work in Bull 3?
> But I'm definitely not clear on what was actually happening under the hood...
> The flow I had was each worker "subscribed" to the named processors it was responsible for, then paused itself locally on the queue immediately after receiving a job.

I think in bull you get an exception but the job does not fail, so the job probably gets stalled and then picked up later. If this mechanism worked for you it was most of pure luck than by bull's design.

**Comment by prescience-data** [comment]
😂
Ok so is there a potential solution by adding more queues? 

I've switched to [manual job fetching](https://docs.bullmq.io/patterns/manually-fetching-jobs), but is there a way to interrupt all the `(await worker.getNextJob(token))` simultaneously? 

My only concern with this approach is it exponentially increases the number of queues, so if I'm understanding the Taskforce.sh pricing it will be `$9.90/m * n queues` (which might make it unfeasible very fast lol)...

**Comment by manast** [comment]
@prescience-data not sure I have a complete picture of your use case. Basically you want to have 1 queue but depending on the type of job process it in one or another worker ? and the question that follows is why is it important that they run in different workers depending on types?

**Comment by prescience-data** [comment]
so the use case in a bit sharper detail is

- a worker represents a specific device in a specific region with a specific role
- (ideally) I can send a job to:
  - a) the fully qualified signature (ie `"hardware-1:region-2:role-5"`)
  - b) a partial of the signature (ie `"hardware-1:role-4"`)
  - c) the global queue (ie `"all"`)
 and the worker should respond to any of those calls (but not `"hardware-4"` if that is not a match)
Currently in Bull 3 I connect to the main "company-name" queue, then subscribe to all the named processors:

```typescript
  /**
   * Connects to the all the required channels and sets a process listener on each queue to handle incoming jobs.
   * Subscriptions are logged as an array of objects showing the channel and the Queue processor.
   *
   * @return {Promise<number>}
   */
  public async subscribeToChannels(): Promise<number> {
    const channels: string[] = await this.getChannels()
    let counter = 0

    channels.forEach((channel) => {
      logger.info(
        `Subscribing device ${this.serial} ${this.instance} to ${channel}`
      )
      try {
        // Do not await.
        queue.process(channel, 1, this._handleJob.bind(this))
        counter++
      } catch (err) {
        logger.error(err.message)
      }
    })

    // Report the to administrator how many queues were connected.
    logger.success(`Subscribed to ${counter} queues.`)
    // Return the number of connect channels.
    return counter
  }

```

**Comment by prescience-data** [comment]
Ok for future reference, I found the way to achieve the desired outcomes in this use case was with the ["Manually Fetch Jobs"](https://docs.bullmq.io/patterns/manually-fetching-jobs) pattern. 

This way you can control the worker "channel" listeners centrally without needing to pause and unpause locally, which turns out to be far cleaner and atomic than the flow I described above.

See this [discussion](https://github.com/taskforcesh/bullmq/discussions/462) for additional context.
