### ISSUE TITLE
Scheduler doesn't close it's connection

### ISSUE THREAD

**Issue by dor272** [taskforcesh/bullmq#451]
After digging and many tests it seems like the scheduler doesn't close doesn't close all connections.

I wrote a class: 
```
class Manager {
  queue: Queue
  resultsQueue: Queue
  worker: Worker
  scheduler: Scheduler

  constuctor(redisOptions: RedisOptions){
    super(redisOptions);
    this.queue = new Queue('queue', { connection: this.redisClient });
    this.resultsQueue= new Queue('resultsQueue', { connection: this.redisClient });
    this.scheduler= new Scheduler('queue', { connection: this.redisClient });
    this.worker= new Queue('resultsQueue', undefined, { connection: this.redisClient });
  }

  get readyPromise() {
    return Promise.all([
      this.queue.waitUntilReady(),
      this.resultsQueue.waitUntilReady(),
      this.worker.waitUntilReady(),
      this.scheduler.waitUntilReady(),
    ]);
  }

  async close() {
    await Promise.all([
      this.queue.close(),
      this.resultsQueue.close(),
      this.worker.close(),
      this.scheduler.close(),
    ]);
    return super.close()
  }
}
```

The idea is to have a managed "subject" as a queue, all in one place.
I pass an existing connection that the class inherits but as expected the `worker` and `scheduler` duplicate it.
When running my tests there was a connection hanging at the end, took me time to isolate that but I suspect in the `scheduler`: when I remove the `scheduler` from my class then there are no connections left open at the end of the tests.

At first I thought it has to do with the way I manage the connections but as I mentioned, the problems goes away when I don't initiate a `scheduler`. the `Queue` and `Worker` seems to work fine as I use the `close` function above.
I expected `scheduler.close()` to return a promise when all of it's connections are disconnected, doesn't it work this way? Am I using it in a wrong way?

Thanks.

**Comment by dor272** [comment]
It's seems like something similar happens with `Worker` as well.
tried a very basic test:
```
 const worker = new Worker('test', undefined);
 await worker.waitUntilReady();
 await worker.close();
```
again, a connection left open. seems like `Worker.close()` closes only the blocking connection it creates and doesn't take care of the redis client created at it parent `QueueBase`. The only option to completely close all connections is to call `worker.disconnect()` which is actually method of `QueueBase` but that doesn't close the connection gracefully.

Seems like `Worker.close` should call `super.close()`.

**Comment by manast** [comment]
I made a PR that fixes the issue with the worker closing the connection from the base class, however I cannot see any issue with the QueueScheduler... If you can provide a minimal test case that demonstrates the issue I can take another look at it.

**Comment by dor272** [comment]
Seems like everything works as expected, thanks.
