### ISSUE TITLE
[Feature request] Assign meaningful names to workers

### ISSUE THREAD

**Issue by Wolvan** [taskforcesh/bullmq#456]
To keep a consistent overview of my current workers, I would like to assign each of them a meaningful name, the hostname of the computer they are running on for example.
That way, when calling `queue.getWorkers()` I can tell which machine the worker is running on.
Trying to set the `worker.name` property changes the entire queue that the worker is listening to, unfortunately.
And checking `queue.getWorkers()...name` returns the name of the queue, which I already know.

**Comment by manast** [comment]
yes, the lack of a feature like this has been itching for a while now.

**Comment by manast** [comment]
We have optional names on workers for a while now, so closing.
