### ISSUE TITLE
Job ID is not preventing duplicates?

### ISSUE THREAD

**Issue by jorgecuesta** [taskforcesh/bullmq#458]
HI People I'm new using BullMQ is my first time with this, is an awesome tool and is working amazing.
My case is a long story but basically I'm generating the job id based on another id of an element that I need to process.
Today using Bull Dashboard I figure out that is I run queue.addBulk with an id that is already added it adds a duplicate.
![Screenshot_2021-04-08_12-41-57](https://user-images.githubusercontent.com/9866992/114065275-7a407f00-9868-11eb-8190-1963d3388091.png)
Here you can see that everything in the job is the same, but the added time is different and the # are both different
#22769 Added at 12:17:37 vs #34939 Added at 12:33:48

So my question is, am I doing something wrong? I maybe miss something important enought that get my jobs repeated?

**Comment by manast** [comment]
Interesting, it seems like jobId is indeed ignored, since I see different ids on the left, #34939 vs #22769. Will take a look at this.

**Comment by manast** [comment]
ok, I found the issue, I will submit a patch soon.

**Comment by jorgecuesta** [comment]
ok @manast please let me know when you be able to fix it. Thanks!

**Comment by manast** [comment]
I was working on this PR so I fixed it here: https://github.com/taskforcesh/bullmq/pull/454
will be released today.

**Comment by jorgecuesta** [comment]
@manast pr is merge so in the latest release is already fixed right?

**Comment by manast** [comment]
not yet sorry. There is an error with the deployment that I need to fix first.

**Comment by manast** [comment]
It is released now.
