### ISSUE TITLE
Missing lock for job 1 finished

### ISSUE THREAD

**Issue by prescience-data** [taskforcesh/bullmq#464]
Hey again @manast ! 👋

I've implemented the flow we discussed for the manual job processing, and now the server is successfully dispatching the job, the worker is successfully completing it, but I've hit the following error:

```
Missing lock for job 1 finished
```

### Existing issues / suggestions

I noticed there is an existing issue open here https://github.com/taskforcesh/bullmq/issues/424 regarding the `ioredis` prefix, but I am not setting any prefix, so I don't believe its due to that.

I also increased the `lockDuration` as suggested in the docs to double (even though the job is completing withing < 1 second):

### Worker
```js

{
  connection: {
    host: "queue.foo.com",
    port: 6379,
    family: 4,
    password: "[***]",
    maxRetriesPerRequest: 2,
    url: "redis://:[***]@queue.foo.com:6379"
  },
  concurrency: 1,
  skipDelayCheck: false,
  drainDelay: 2,
  lockDuration: 60000,
  lockRenewTime: 30000
}
```

### Server (Dispatcher)

```js
{
  connection: {
    host: "queue.foo.com",
    port: 6379,
    family: 4,
    password: "[***]",
    maxRetriesPerRequest: 2,
    url: "redis://:[***]@queue.foo.com:6379"
  },
  defaultJobOptions: {
    attempts: 1,
    backoff: {
      type: "fixed",
      delay: 1000
    },
    timeout: 60000,
    removeOnComplete: 10,
    removeOnFail: 3,
    stackTraceLimit: 3
  }
}
```

### Redis DB

![image](https://user-images.githubusercontent.com/65471523/114259886-b0bafd00-9a14-11eb-93a9-4def3826a2f0.png)

### Taskforce.sh

After the error occurs, the job appears to sit in "active" indefinitely

![image](https://user-images.githubusercontent.com/65471523/114259922-d5af7000-9a14-11eb-82d3-39fe9f8e7bb7.png)
 
![image](https://user-images.githubusercontent.com/65471523/114261643-0eecdd80-9a1f-11eb-8a8a-e3ae80a8e106.png)

**Comment by prescience-data** [comment]
Sorry, disregard - There was a mismatch in the token values 🙈

**Comment by eltoroit** [comment]
Which tokens were mismatched?

**Comment by manast** [comment]
@eltoroit I think he means the token for the connector: https://docs.taskforce.sh/getting-started/taskforce-connector

**Comment by prescience-data** [comment]
@eltoroit @manast 
Ah sorry, to be more specific, it was the manual job token:
https://docs.bullmq.io/patterns/manually-fetching-jobs

In this particular case I had migrated some code that looked like this:

```typescript
export class Foo {

  public uuid: string = uuid()
  public instance: string = hash(12)

  public async processJob() {
    const job = await worker.getNextJob(this.uuid)
    // Business logic...
   // This was supposed to be this.uuid ! 🙈
    await job.moveToCompleted('bar', this.instance)
  }
}

```
