### ISSUE TITLE
Implement job locking mechanism

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq#47]
As in Bull 3 we need a locking mechanism where a worker needs to pick a lock everytime it starts processing a job. Every worker and every concurrent processor withing a worker needs to have a uuid that will be stored in the lock, by doing this we can also know which worker that is processing a given job and also if a worker has lost the lock  (which in the future should imply a cancellation).

**Comment by ccollie** [comment]
Had you considered using `XREADGROUP` and have workers as a group ? Workers would then call `XACK` after completion. 

The benefit is that `redis` handles much of the mechanics already, and you'd only need to write code to handle recovery (inspect the `PEL` using `XPENDING` to claim messages which have been stale for a given period)

  Done this way, we could assume that any active job is locked (and possibly stalled)

**Comment by manast** [comment]
We are being a bit conservative with changing the underlying redis structures so that we can keep backwards compatibility, maybe for the next major version we could consider an improvement like the one you are suggesting.

**Comment by manast** [comment]
Btw, using ```XREADGROUP``` you can only XACK when you are done with the job, but then you will also need to define a max duration of the job, and when inspecting the PEL you need to claim the messages that have been processing for too long. In BullMQ you do not have such a limitation, workers can work on a job as long as they want, as long as they can keep updating the job LOCK... not sure if this is currently possible using redis streams...
