### ISSUE TITLE
Release 1.0.0 not yet in visible in NPM

### ISSUE THREAD

**Issue by ccollie** [taskforcesh/bullmq#48]
<eot/>

**Comment by manast** [comment]
We are experimenting with semantic-release and it seems that the actual release to npm did not complete :/

**Comment by MichielDeMey** [comment]
Looks like v1.0.1 and v1.1.0 are available on NPM: https://www.npmjs.com/package/bullmq
So I guess we can close this issue?

**Comment by manast** [comment]
yes, it can be closed.
