### ISSUE TITLE
Error: Missing lock for job 84 failed 

### ISSUE THREAD

**Issue by ujwaldhakal** [taskforcesh/bullmq#489]
Hello i am using 2 node process one main and one for queue in supervisor with docker where i have set autorestart and start to true. When some job takes longer time I get . I was little confused on where to start and if anyone has similar issue that would be great. 

A 2021-04-21T23:36:04.598667Z Error: Missing lock for job 84 failed
    at Function.finishedErrors (/var/www/node_modules/bullmq/dist/classes/scripts.js:135:24)
    at Job.moveToFailed (/var/www/node_modules/bullmq/dist/classes/job.js:207:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handleFailed (/var/www/node_modules/bullmq/dist/classes/worker.js:220:17)
    at async Worker.run (/var/www/node_modules/bullmq/dist/classes/worker.js:99:34) 
A 2021-04-21T23:37:54.192317Z Error: Missing lock for job 85 failed
    at Function.finishedErrors (/var/www/node_modules/bullmq/dist/classes/scripts.js:135:24)
    at Job.moveToFailed (/var/www/node_modules/bullmq/dist/classes/job.js:207:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handleFailed (/var/www/node_modules/bullmq/dist/classes/worker.js:220:17)
    at async Worker.run (/var/www/node_modules/bullmq/dist/classes/worker.js:99:34)

**Comment by manast** [comment]
Probably due to this: https://docs.bullmq.io/guide/jobs/stalled

**Comment by ujwaldhakal** [comment]
@manast but there is no stalled flag in my current queue job .. yep my some of the background task take long time and they are processed even though i get this issue. And once i get this error the job will be still there and no one will proceed i am running sandbox processor that is running function in different file

**Comment by manast** [comment]
You should provide a minimal test case that reproduces the issue so we can help better.

**Comment by ujwaldhakal** [comment]
Ok sure i will provide with some codes that will replicate.Thank you !

**Comment by ujwaldhakal** [comment]
https://github.com/OptimalBits/bull/issues/1591

I got it fixed by increasing the lockDuration from 30 sec to the 5 mins max and it is working great

**Comment by edisoncpp** [comment]
I'm getting this error after 30 minutes even if I set the lockDuration to 90 minutes, AND the worker has async requests and database calls in it freeing up the event loop.

**Comment by hgeldenhuys** [comment]
I suspect that when bull does the stalled check, Redis might not be available for a moment due to swapping out something, the timestamp is then null, which results in a 1970 date, so Bull thinks the job has been stalling for 53+ years. 

![image](https://github.com/taskforcesh/bullmq/assets/179999/2ba55f15-aa02-41f4-9aaa-136cdc4cd11a)

**Comment by reymon359** [comment]
> I suspect that when bull does the stalled check, Redis might not be available for a moment due to swapping out something, the timestamp is then null, which results in a 1970 date, so Bull thinks the job has been stalling for 53+ years.
> 
> ![image](https://private-user-images.githubusercontent.com/179999/251244057-faf0363e-c0a8-4fd6-861f-bf46d0682edd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY0NjUsIm5iZiI6MTcyNTcxNjE2NSwicGF0aCI6Ii8xNzk5OTkvMjUxMjQ0MDU3LWZhZjAzNjNlLWMwYTgtNGZkNi04NjFmLWJmNDZkMDY4MmVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QxMzM2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2EwOGI5Y2M1MjFlYjA5ZmE3OTNiODdmYzI3M2Q3YTU1MDc3OGVmZTI5OWFlNGI4MTMxZTg0ZjM5MzI2ZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FXYc3pUD8QVlVhZ3pAf_KA0CqcGaMQRO03zQMsbMbic)

Hey @hgeldenhuys , what is that interface from your screenshot?
