### ISSUE TITLE
token mandatory?

### ISSUE THREAD

**Issue by japrescott** [taskforcesh/bullmq#490]
1.6.0 broke our system as we now need to pass a mandatory token. I saw the discussion in https://github.com/taskforcesh/bullmq/pull/484 where the token was originally optional but @roggervalf suggested it shall be mandatory.
There is no reference to an issue or any detail for what this token could/shall be used for. It seems totally useless. Anyone care to elaborate what the idea behind it is?

**Comment by manast** [comment]
ahh, ok. This is my fault. I was not thinking correctly here. I will make it optional and make a new release, sorry for the mistake.

**Comment by japrescott** [comment]
@manast wow, didnt expect this to be fixed. I was more wondering what the use-case for this token is? So one can pass "secret" information to a job?

**Comment by manast** [comment]
We are working on a use case where you can move the job to a different state from within the processor, and for that you need the token of that worker. But this is optional and will be explained in the documentation when it is ready.
