### ISSUE TITLE
worker.close leaks connection

### ISSUE THREAD

**Issue by m-ronchi** [taskforcesh/bullmq#493]
Hi,

the `worker.close()` method keeps a redis connection open, which in turn doesn't let nodeJS exit.

if you run this code:
```
import { Worker } from "bullmq";
import * as wtfnode from "wtfnode";
(async () => {
  const worker = new Worker("q", async job => {});
  await worker.waitUntilReady();
  await worker.close();
  console.log("should exit node");
  wtfnode.dump();
})();
```
the process remains running forever. `wtfnode` prints a connection to redis still active.

I can workaround this by doing an additional `await worker.disconnect();`, but it's not mentioned anywhere in the docs

**Comment by manast** [comment]
are you using the latest BullMQ version? because this precise issue was fixed a couple of days ago.

**Comment by m-ronchi** [comment]
I had 1.18.2, updating to 1.20.3 fixed this.
