### ISSUE TITLE
Create a benchmarks suite

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq#5]
In order to keep competitive and not create performance regressions we need a simple benchmark suite, ideally that can be run in the CI pipeline too.

**Comment by lricoy** [comment]
Any direction on this one? Would love to lend a hand if possible.

**Comment by manast** [comment]
It is actually in a separate repo: https://github.com/taskforcesh/bullmq-bench

**Comment by lricoy** [comment]
Thanks! I will take a look
