### ISSUE TITLE
Add a public method to Worker for starting polling job manually

### ISSUE THREAD

**Issue by purefun** [taskforcesh/bullmq#50]
`Worker` will process the job immediately when it is instantiated. Is it possible to add a public method like `start()`? Then add a boolean option such as `autostart` to constructor arguments. Of course It's default value will be true. Thank you.

**Comment by jaredjj3** [comment]
+1 to this idea. I think it's generally better to leave side effects outside of constructors.

**Comment by roggervalf** [comment]
currently there is an autorun option to be passed into Worker constructor to handle this https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.workeroptions_2.autorun.md
