### ISSUE TITLE
Flow task removed doesn't remove data relative

### ISSUE THREAD

**Issue by koiszzz** [taskforcesh/bullmq#504]
```javascript

const worker1 = new Worker('test1', async job => {
       return 1;
});
const worker2 = new Worker('test2', async job => {
       return 2;
});
const flowPro = new FlowProducer();

(async() => {
    await flowPro.add({
            name: 'parent-task', data: {}, queueName: 'test1', opts: {removeOnComplete: true},
            children: [{name: 'children-task', data: {}, queueName: 'test2', opts: {removeOnComplete: true}}]
    });
})();
```

After running these codes, the redis still remain some data that named <pid:processed> and  <pid:event>.

**Comment by manast** [comment]
not sure if it was a typo in your exampel code but you wrote: ```removeIOnComplete``` instead of ```removeOnComplete```. Let me know if still does not work and I will take a look into it.

**Comment by koiszzz** [comment]
Please ignore that. I have spelled wrongly when I post this issue. In my code , it was spelled correctly. The parent job and child job were removed after running this code, but there still remains a hash type data named parent-job-id:process and a stream type data named parent-job-id:events.

**Comment by roggervalf** [comment]
@manast one doubt, the parent events stream should also be removed?

**Comment by manast** [comment]
the events are for the queue not for the job so they should not be removed.

**Comment by manast** [comment]
but why are there event streams for "jobs", I think there is a bug that is making the events end in the wrong key actually.
