### ISSUE TITLE
missing types for Worker event listeners

### ISSUE THREAD

**Issue by m-ronchi** [taskforcesh/bullmq#523]
`Worker` class does not have signatures for its event listeners, therefore it always defaults to `EventEmitter`'s `on(event: string | symbol, listener: (...args: any[]) => void): this;`.

for comparison, both bull 3 queue (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bull/index.d.ts#L797 / https://github.com/taskforcesh/bullmq/blob/master/src/classes/compat.ts#L430) and `QueueEvents` (https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-events.ts#L6) have them

**Comment by roggervalf** [comment]
@m-ronchi please try the last version, it should have event listener typing
