### ISSUE TITLE
[Interface change] attribute failedReason  alter type to Object | string

### ISSUE THREAD

**Issue by paulocwb** [taskforcesh/bullmq#537]
Locally I've did it and is running with no problem, but I would like to know if is viable to change the failedReason attribute of the Job Interface, when working with Typescript always have to manually convert using JSON.stringify when rejecting a job, this ain't needed when working with JavaScript.
My suggestion is to accept the Object and stringify direct on the Job class (If the value is a Object).
I can do the PR with this little tweak, just wanna know if this is desired or allowed to change.
Best regards.

**Comment by manast** [comment]
failedReason is normally the err.message property. Why do you need that BullMQ considers that property as an object too?

**Comment by paulocwb** [comment]
Well, when an unexpected error occur tottaly make sense that failed reason be the error. message that by default is a string.
But in some cases when the job successfully completes the task, but the return value is unnaceptable or different that expected (payment declined, run out of stock, etc..) so we throw a Promise.reject, and in some cases is needed to return an object with additional details.
When running on a micro service architecture the services don't know each other and the only bridge between then are Bull is a limit to just sending a string, we have to provide maximum information possible, obviously that is pretty simple to work around with JSON.stringify, but I think that Bull should accept an object too and convert it internally if needed.

**Comment by manast** [comment]
yes I understand, but since it is quite easy to just JSON.stringify the message in user code I think it is better to keep BullMQ simpler... every feature adds in complexity and maintaining efforts so in order to save resources I will close this issue for now.
