### ISSUE TITLE
Docs: wrong type used in sandboxed processors page

### ISSUE THREAD

**Issue by TheoHertz** [taskforcesh/bullmq#539]
in [this guide](https://docs.bullmq.io/guide/workers/sandboxed-processors), the example given uses the type `Job` for a sandboxed processors but it should be `SandboxedJob` instead

**Comment by javiercr** [comment]
I'm a bit confused, the guide references a blog post that uses `Job` not `SandboxesJob`. Is that article outdated?

> If you are looking for a tutorial with code examples on how to use sandboxed processors using typescript you can find one [here](https://blog.taskforce.sh/using-typescript-with-bullmq/).
