### ISSUE TITLE
Latest changelog not preset at https://docs.bullmq.io/changelog

### ISSUE THREAD

**Issue by thegedge** [taskforcesh/bullmq#549]
I'm seeing this one: https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/changelog.md
But the latest is in: https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/CHANGELOG.md

These also cause problems on case-insensitive filesystems, where git always thinks the file has changes (I was still having problems after enabling the `core.ignorecase` option in git).

**Comment by manast** [comment]
aha, now I see the problem, I was being hunted by this but since I am working in MacOS I only see one of the files.

**Comment by manast** [comment]
Should be fixed now.
