### ISSUE TITLE
FlowProducer: parent job does not contain dependencies if I set jobId

### ISSUE THREAD

**Issue by fivemru** [taskforcesh/bullmq#552]
If I set jobId:
```javascript
const parentQueue = new Queue('parent-queue');
const flowProducer = new FlowProducer();

const flow = await flowProducer.add({
  name: 'p1',
  queueName: 'parent-queue',
  opts: { jobId: 'my-parent-job-id' },
  children: [
    { name: 'c1', queueName: 'child-queue' },
    { name: 'c2', queueName: 'child-queue' },
    { name: 'c3', queueName: 'child-queue' },
  ],
});

console.log('create flow job', flow.job.id);
const parentJob = await parentQueue.getJob(flow.job.id);
// or const parentJob = await parentQueue.getJob('my-parent-job-id');
console.log('deps', await parentJob.getDependencies());
```

Output:
```
create flow job my-parent-job-id         
deps { processed: {}, unprocessed: [] }  
```

Everything is fine without jobId:
```javascript
const flow = await flowProducer.add({
  name: 'p1',
  queueName: 'parent-queue',
  children: [
    { name: 'c1', queueName: 'child-queue' },
    { name: 'c2', queueName: 'child-queue' },
    { name: 'c3', queueName: 'child-queue' },
  ],
});

console.log('create flow job', flow.job.id);
const parentJob = await parentQueue.getJob(flow.job.id);
console.log('deps', await parentJob.getDependencies());
```

Output: 
```
create flow job 389cc496-336f-4748-a978-6cbaf95335a2                               
deps {                                                                             
  processed: {},                                                                   
  unprocessed: [ 'bull:child-queue:1', 'bull:child-queue:3', 'bull:child-queue:2' ]
}
```

I want to set the jobId to the parent in order to avoid re-adding the same parent task if it is already in the queue and track its progress.
The parent task is formed on the basis of 2 parameters that come from the user: `p1` and `p2`. These are short text strings, I planned to use them as ```const jobId = `${p1}:${p2}`;```

Workers of both queues process tasks, but for the given `jobId` of the parent I cannot get neither children nor dependencies.

**Comment by manast** [comment]
@fivemru after the fix @roggervalf did, it should work for your use case, however keep in mind that even the children needs to have the same jobIds as in the previous call to ```add``` otherwise what will happen is that the children will be added again to the initial parent, which depending in which status the parent is will have different effects. For example if the parent has already completed nothing will happen and you will have some dangling children, but if the parent is still waiting for children to complete, then the children will run twice.

**Comment by fivemru** [comment]
@manast thank you for the answer, in my case the situations mentioned should not happen.
The parent `jobId` I set manually helps me to track the progress and the existence of the parent job in the queue via 
```const parentJob = await parentQueue.getJob('my-parent-job-id');``` before adding a task.

The parent job processor creates a cache in redis that is checked after checking for the existence of the parent `jobId` and before adding the job to the queue.

**Comment by manast** [comment]
@fivemru you do not need to do that, BullMQ will ignore adding the job a second time if the job is already in the queue with that same jobId: https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.jobsoptions.md

**Comment by oyatek** [comment]
> @fivemru you do not need to do that, BullMQ will ignore adding the job a second time if the job is already in the queue with that same jobId: https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.jobsoptions.md

What if I have a job with custom jobID (no parent) and then I try to add the same job (same jobID) in a flow, and this time I add it as a child? Will BullMQ update existing job parent ID, or will new job be ignored completely?
