### ISSUE TITLE
Cannot read property 'returnvalue' of undefined in waitUntilFinished

### ISSUE THREAD

**Issue by Embraser01** [taskforcesh/bullmq#555]
After upgrading from `bullmq@1.10.0` to `1.14.7` (same with `1.26.0`), a new error started to pop:

```
Cannot read property 'returnvalue' of undefined
TypeError: Cannot read property 'returnvalue' of undefined
                               at onCompleted (/code/node_modules/bullmq/dist/classes/job.js:308:30)
                                            at /code/node_modules/bullmq/dist/classes/job.js:338:21
at runMicrotasks (<anonymous>)
                               at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
This error is in an UnhandledPromiseRejectionWarning and the call to `waitUntilFinished` doesn't fail at all (correctly return the data).

After some research, I suspect https://github.com/taskforcesh/bullmq/pull/383 to be the cause of the problem but I'm not 100% sure. I tried to reproduce the bug in local but without success.
Is there a way that the change would create a new race condition (where the event would be sent twice maybe?)

**Comment by manast** [comment]
yes, you are right there is a potential hazard in the new code, I wrote a comment: https://github.com/taskforcesh/bullmq/pull/383/files#r634292149

**Comment by manast** [comment]
but I wonder, do you have "removeOnCompleted" enabled? otherwise it should not be possible to reproduce this hazard.

**Comment by Embraser01** [comment]
> but I wonder, do you have "removeOnCompleted" enabled? otherwise it should not be possible to reproduce this hazard.

Not really as it caused https://github.com/taskforcesh/bullmq/issues/85 but I made a function that do almost the same thing:

```js
const runOnWorker = async (
  jobName,
  data,
  options = {},
  { queue, queueEvents, waitTTL },
) => {
  const job = await queue.add(jobName, data, options);

  try {
    return await job.waitUntilFinished(queueEvents, waitTTL);
  } catch (err) {
    throw new BadRequest(err);
  } finally {
    job.remove().catch(noop); // <-- Should (almost) always remove the job
  }
};
```

**Comment by manast** [comment]
hmm, I wonder how the hazard is triggered by that code then. Anyway, fixing #85 will require to get rid of the hazard as well so fixing that one will even also resolve this issue.

**Comment by Embraser01** [comment]
FYI, I used a workaround: `setTimeout(() => job.remove().catch(noop), 500)` to "fix" my issue.
