### ISSUE TITLE
No Docs for Working with Batches

### ISSUE THREAD

**Issue by ilias-t** [taskforcesh/bullmq#557]
Really curious to learn more about [working with batches](https://docs.bullmq.io/patterns/working-with-batches), is there anywhere one can find documentation for this? Thanks!

**Comment by timosg** [comment]
Any updates on this ?

**Comment by manast** [comment]
@timosg what specifically would you like to do? maybe I can write something if I better know your expectations.

**Comment by timosg** [comment]
So basically i have a lot of jobs, which i have to process. Therefore i need to do an API call to insert the data of job in a database. Doing a API call for every single job is obviously not performant and a bad way to do it.

The solution i am searching for is the following:

1. Adding jobs to a queue and do not process them.
2. If a specific amount of jobs have registered in the queue or a defined time expires, process all jobs of the queue in a batch
3. Mark all jobs processed in the batch as done

With this i am able to do one API call for my database to insert a batch of data.

**Comment by ilias-t** [comment]
@timosg This is the same scenario I was looking to implement. Hopefully aspects of the solution I devised might be helpful to you. I basically used a timeout to run a worker job after a given amount of time expires. If you want to do it after the queue has built up to a certain size, you could theoretically poll the size on an interval, which isn't ideal but could also work.

At that point once we're ready to perform batch processing, we `await worker.close()` on the worker that is operating on the queue.

**Comment by manast** [comment]
@timosg this will require a new functionality. As bullmq is designed now, this feature would only work using manual processing of jobs, but it can be added as a new feature.

**Comment by manast** [comment]
@timosg thats just that you can store the data already in batches and process every batch as a single job.
