### ISSUE TITLE
Using the "prefix" option

### ISSUE THREAD

**Issue by omen-x** [taskforcesh/bullmq#560]
```javascript
  const connection = new Redis(6389);
  const queue = new Queue('foo', { connection, prefix: "PF" });

  new Worker('foo', (job)=>{
      return 'bar';
  }, { connection })

  queue.add('foo', {});
```
Redis keys created:
```
1) "PF:foo:id"
2) "PF:foo:meta"
3) "PF:foo:wait"
4) "bull:foo:events"
5) "PF:foo:1"
6) "PF:foo:events"
```
1. Is it expected to have some keys not prefixed?
2. Also, the job in this case is not processed (waiting). Works without the "prefix" option.

bullmq version - 1.26.5

**Comment by manast** [comment]
that is definitely a bug, thanks for reporting it.

**Comment by omen-x** [comment]
@manast investigated the problem a bit. All core classes - `Worker`, `QueueScheduler`, `QueueEvents` extend `QueueBase`, which have the following code in the constructor:
```javascript
    this.opts = {
      prefix: 'bull',
      ...opts,
    };
```
So, if we don't specify "prefix" option for this classes - "bull" will be used.
Seems like "prefix" should be synced somehow between all classes.

As a workaround we can specify the same prefix for all core classes instances - works as expected.

**Comment by manast** [comment]
ah ok, I missed that you did not specify the prefix on the Worker class, then it works as expected.
