### ISSUE TITLE
Job is still there after processing

### ISSUE THREAD

**Issue by ujwaldhakal** [taskforcesh/bullmq#580]
My configs 
`defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
      },
`

I have jobs that take around 5 minutes and I have 15 minutes lock duration. when debugged the state at first the job lock remained for some time then the lock was removed and the job was still there on Redis with the following key-value

`
processedOn:  1622804032898
opts: {"attempts":0,"delay":0,"removeOnComplete":true,"removeOnFail":true}
timestamp: 1622804032896
priority: 0
name processData
delay: 0
data: {id: 123124124}`

**Comment by roggervalf** [comment]
hi @ujwaldhakal I can take a look, could you please provide a test case to reproduce this issue?

**Comment by ujwaldhakal** [comment]
Processor File
```
 async processQueue(job: Job): Promise<void> {
    try {
      const data: IPlaidWebhookPayload = job.data.payload;
      switch (data.webhook_type) {
        case 'TRANSACTIONS':
          await this.commandBus.execute(
            new StoreStripeData(
              data.item_id,
              data.webhook_code,
            ),
          );
          break;
      }
    } catch (error) {
      this.logger.error('error processing plaid webhook', error);
    }
  } 
```
and inside command there is http api request to stripe server which might make few minutes


Below is worker initialization


```

const worker = new Worker('collect-stripe-data', 'path/to.processQueueMethod`,' {
      connection: connectionResolver.resolve(
        ConnectionResolver.CONNECTION_QUEUE_PUBLISHER,
      ),
      lockDuration: 300000,
    });
    
    
```

**Comment by roggervalf** [comment]
just curious, you are adding your jobs using the queue.add method (queue that has the defaultJobOptions)?

**Comment by ujwaldhakal** [comment]
Sorry, these are my configs
`{
      connection:// redis connection payload,
      defaultJobOptions: {
        removeOnComplete: true,
        removeOnFail: true,
      },
    }`

**Comment by ujwaldhakal** [comment]
And I am running both main node process & queue process on same container but on different process by supervisor

[program:queue]
directory=/var/www
command=npm run start:consumer:dev
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

**Comment by manast** [comment]
@ujwaldhakal you should provide a standalone test case that we can run to reproduce the issue.

**Comment by ujwaldhakal** [comment]
@manast i actually dont knw the case when it comes it is quite strange some jobs are processed without any issue while some jobs are getting issue. I will need to spend sometime to reproduce this issue so that it could be helpful for building a fix. Let me spend some time the best guess i could make is the node server might getting restart and i find if the process exit the job will have problem

**Comment by ujwaldhakal** [comment]
@manast i was able to reproduce the case

```
this.logger.info('job data', job.data);
    await new Promise((resolve) => {
      setTimeout(() => {
        this.logger.info(`Job processed with id ${process.pid}`);
        resolve(true);
      },30000)
    });
```

suppose this is my worker file where I wait 30 seconds and resolve. Now, whenever I quit the terminal and restart again the job won't gets process and the lock gets removed. So whenever I did the deployment the job that has lock was stopped for some time and  it could not process back

**Comment by manast** [comment]
Do you have a queue scheduler instance in place?

**Comment by manast** [comment]
https://docs.bullmq.io/guide/queuescheduler

**Comment by ujwaldhakal** [comment]
Thank you @manast so I need to place a queue scheduler and I have to handle duplicates by myself to prevent duplicate processing right?

**Comment by manast** [comment]
Not sure what you mean  with duplicates. But the queue scheduler is necessary for your case to work, one instance is enough but you can have more for redundancy.

**Comment by ujwaldhakal** [comment]
Thank you @manast  looks like my jobs is getting processed at least once and it could process 2-3 times depending on my retry config. But sometime i am getting issue missing job key ? What could cause those issue?

**Comment by manast** [comment]
@ujwaldhakal don't know, maybe a zombie worker trying to do stuff with a job that has already been processed, but without code that reproduces the issue is just a wild guess...

**Comment by ujwaldhakal** [comment]
The cases can be replicate by above code. 

```
this.logger.info('job data', job.data);
    await new Promise((resolve) => {
      setTimeout(() => {
        this.logger.info(`Job processed with id ${process.pid}`);
        resolve(true);
      },30000)
    });
```

**Comment by manast** [comment]
@ujwaldhakal If I run that code I will get errors.
