### ISSUE TITLE
What happens if removeOnComplete is true but a job is repeating?

### ISSUE THREAD

**Issue by adamreisnz** [taskforcesh/bullmq#597]
As per the title; what happens if by default I have `removeOnComplete: true` for my job options (set at queue level using `defaultJobOptions`), but I add some infinitely repeating jobs?

Will it remove the jobs once completed, or will they keep repeating?

Some better documentation around removal of completed jobs and best practices for managing a queue would be appreciated.

**Comment by manast** [comment]
In theory the job for every iteration should be deleted after completion. The repeatable job itself will continue to repeat according to its options.

**Comment by adamreisnz** [comment]
Ok thanks, that's sensible.

**Comment by loris** [comment]
@adamreisnz FYI you can face some issues in that specific case, have a look at https://github.com/taskforcesh/bullmq/issues/515

**Comment by manast** [comment]
Will close this since AFAIK there is no issue with "removeOnComplete".

**Comment by abdullahEmumba** [comment]
I am using bullmq with removeOnComplete but for some reason, it is not working for repeating jobs. I only want to keep the last 5 triggers and delete the older ones automatically but that is not happening in my case. Works fine for non-repeating jobs.
