### ISSUE TITLE
Job data is saved as redis key and job does not run

### ISSUE THREAD

**Issue by quanhv94** [taskforcesh/bullmq#604]
This bug happen on my production server only.
Whole job name and job data is saved as redis key. So every jobs does not run.
It still work fine on local.

<img width="759" alt="Screen Shot 2021-06-19 at 09 30 16" src="https://user-images.githubusercontent.com/14907061/122628608-43e17480-d0e1-11eb-8063-e5fd15b11d44.png">
<img width="1008" alt="Screen Shot 2021-06-19 at 09 32 06" src="https://user-images.githubusercontent.com/14907061/122628613-4b088280-d0e1-11eb-90e7-dda7318da338.png">

**Comment by manast** [comment]
That is very strange... can you isolate the problem in a small use case and test it on production?
