### ISSUE TITLE
Rate limiting behaviour

### ISSUE THREAD

**Issue by peteraw77** [taskforcesh/bullmq#613]
Hi, I have been having an issue while rate limiting jobs that themselves use an external rate-limited API. Even when using aggressive rate limits in the worker, the external API is throwing rate-limit exceptions when a large number of jobs is added to the queue at once. To reproduce the issue I conducted the following test:
- created a worker that takes `rateLimit` jobs/s and a job that waits `Math.random() * 1000` ms before executing an "API call" (which simply returns `process.hrtime()`)
- add `rateLimit+1` jobs to queue
- validate that the first and last "API calls" do not execute within 1 second of each other

About 5% of the time the test fails. I think that if there was a way to dequeue rate-limited jobs based on the completion time of previous jobs rather than start time this issue could be avoided, is such a feature available? Or is there another way around this? Any help would be much appreciated!

**Comment by manast** [comment]
This should work, there is a counter that expires so in theory it should be impossible to exceed the limit. If you can provide a minimal case that shows this behaviour I could look into it.

**Comment by nguyenvudao** [comment]
Hi @manast, rate limiting is messing up the order of jobs, are there any possible ways to keep the order of jobs when we add it into delayed queue?

**Comment by manast** [comment]
> About 5% of the time the test fails. I think that if there was a way to dequeue rate-limited jobs based on the completion time of previous jobs rather than start time this issue could be avoided, is such a feature available? Or is there another way around this? Any help would be much appreciated!

I think that you should have a worker that does nothing else than calling the rate limit API, in that case you should not get this 5% error. If you need to do other things before the rate limited call then you should divide the jobs in two different queues, so in the first queue the jobs do the non rate limited work, and the second queue processes the rate limited API calls.

**Comment by roggervalf** [comment]
we are supporting manual rate-limit https://docs.bullmq.io/guide/rate-limiting#manual-rate-limit
