### ISSUE TITLE
Staying in sync with optimalbits/bull

### ISSUE THREAD

**Issue by gabegorelick** [taskforcesh/bullmq#62]
Apologies if this is already documented somewhere, but what is the plan to keep taskforcesh/bullmq in sync with fixes from optimalbits/bull? Are PRs manually cherry-picked?

**Comment by manast** [comment]
we are cherry picking right now. And we are not investing in major features on the old codebase. In any case, BullMQ is mostly backwards compatible with Bull 3 queues, so migration is not very complicated.

**Comment by gabegorelick** [comment]
> And we are not investing in major features on the old codebase.

Perhaps this should be added to optimalbits/bull's README and CONTRIBUTING?

**Comment by kvenn** [comment]
Hello! I wasn't able to find any official documentation.

If I migration from optimalbits/bull (version 3) to bullmq, are all the keys the same? Will existing jobs still work?

Thanks!

**Comment by manast** [comment]
There are small differences in the data structures so upgrading old queues to BullMQ is not recommended anymore.

**Comment by kvenn** [comment]
Thank you for your response! 

Last questions
- Is that true for version 4 of optimalbits/bull as well? I realize we're actually on 4
- Is there any documentation or source files I should look into for the difference in the data structures? We have a pretty vanilla use-case so want to make sure I'm not missing out on bullmq if I don't have to!

Thanks again

**Comment by manast** [comment]
Unfortunately, such a document does not exist. We have been documenting breaking changes in the changelog with articles to help with migration when it was needed, but jumping from Bull to the latest BullMQ could result in issues. The biggest change I think is in how priority jobs are represented, but there could be other smaller ones that matter... for example repeatable jobs is probably using a different internal format, and such small differences here and there.
https://docs.bullmq.io/changelog

**Comment by manast** [comment]
Probably the biggest changes came in v5 of BullMQ: https://bullmq.io/news/231204/better-queue-markers/
