### ISSUE TITLE
Promise rejection error in waitForJob

### ISSUE THREAD

**Issue by stevelacy** [taskforcesh/bullmq#623]
We are running redis on AWS in cluster mode, which is returning this redis error when it swaps master/replica:
```
UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
```
That is then causing an error to throw in our bullmq services, full error:
```
ReplyError: UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
    at parseError (/code/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/code/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'brpoplpush',
    args: [
      'bull:task:jobs:wait',
      'bull:task:jobs:active',
      '5'
    ]
  }
}
```

It seems that this try/finally is missing a catch causing this error to bubble up, would that be correct?
https://github.com/taskforcesh/bullmq/blob/220b4f619b30a8f04979e9abd0139e46d89b424d/src/classes/worker.ts#L241

**Comment by manast** [comment]
The fix you made may help but we should definitely report the error to the user, and also check what happens when the error is ignored so that we for example do not end in some "infinite loop" of errors and trying again the fetch the next job, etc.

**Comment by manast** [comment]
So probably if the error is just "emitted" we should wait a delay of a couple of seconds before returning to avoid said infinite loops.
