### ISSUE TITLE
Document BackoffFunction behaviour

### ISSUE THREAD

**Issue by clouedoc** [taskforcesh/bullmq#629]
Currently, there is no documentation on `BackoffFunction`'s behaviour. (meaning TSDoc comment)

Behaviour I read from the code: 

Returning -1 will not retry the job (move it to failed)
Returning 0 will retry the job immediately 
Returning > 0 will retry the job after the given amount of time

This should be documented in the comments of `BackoffFunction` so that consumers can understand what return values does what.

**Comment by clouedoc** [comment]
Example comment:

![image](https://user-images.githubusercontent.com/13921610/124355104-d3257680-dc0f-11eb-9e43-8efcb498aedf.png)

**Comment by clouedoc** [comment]
See: https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L429-L451

**Comment by roggervalf** [comment]
This piece should be documented [here](https://docs.bullmq.io/guide/retrying-failing-jobs#custom-back-off-strategies)
