### ISSUE TITLE
Support for UI

### ISSUE THREAD

**Issue by dennyabrain** [taskforcesh/bullmq#63]
Hey I could not find it in the doc or code but is there Support for a UI built into BullMQ?

If not could you guide me a bit on how I could start to build a basic UI that lets me see all the jobs and its associated parameters?

**Comment by ccollie** [comment]
The api is similar enough to `v3` that you could probably start with `Arena` and have something basic with a few days (hours?) of hacking.

FWIW i'm working on a dashboard specifically for `v4` that should be available shortly, modulo vacations

**Comment by manast** [comment]
Until https://taskforce.sh supports BullMQ you can use something like https://github.com/joeferner/redis-commander
It will nicely show all the queues in folders and the jobs inside them.

**Comment by dennyabrain** [comment]
Thank you for the response everyone. Sounds promising.
will follow thread for progress on this or if I make any progress.

**Comment by maketa521** [comment]
I found that bull-board already supports bullMQ, but the current version of NPM is not the latest, you have to build it yourself

https://github.com/vcapretz/bull-board

**Comment by talkl** [comment]
@ccollie did you finish the ui?

also https://www.datadoghq.com/blog/monitor-sidekiq-with-datadog/

what about talking with datadog so they build something that gets people to buy their services?

**Comment by manast** [comment]
@talkl this is what we are building in https://taskforce.sh, which btw is now compatible with BullMQ.

**Comment by talkl** [comment]
will have a look. you should advertise it more, since it's not the first thing that comes to mind @manast

**Comment by manast** [comment]
@talkl it is mentioned on the README. Do you have any suggestion where you think it would be more visible?

**Comment by talkl** [comment]
@manast   Taskforce.sh sponsors BullMQ development, please consider using it for your front end and/or hosting needs.
doesn't say what Taskforce.sh is. When i looked at this phrase i thought it is some kind of a cloud provider for hosting websites. Be more precise what do they offer. Also "...please consider..." doesn't sound very promising, i would put the points of strength that the service offers, with testimonials.

**Comment by ccollie** [comment]
Like most people, the current wetware bug has stalled progress on the UI, but I've been working heavily on monitoring/alerting functionality (I took some inspiration from Datadog and others). All this is exposed with over GraphQL.

 I'm investing in tests at the moment, and as soon as the code is presentable I'll post some news.

**Comment by abenhamdine** [comment]
> @talkl this is what we are building in [taskforce.sh](https://taskforce.sh), which btw is now compatible with BullMQ.

I subscribed to Taskforce.sh to monitor our bullmq jobs, and I confirm it works fine : 

![image](https://user-images.githubusercontent.com/7466144/96334803-b0e4cc00-1073-11eb-81db-4cadf4e95329.png)

**Comment by manast** [comment]
Closing as there are no actions to do here.

**Comment by jotapepinheiro** [comment]
https://bullmq.io/
https://github.com/emirce/bullstudio
