### ISSUE TITLE
Request to update Docs - Cron Task

### ISSUE THREAD

**Issue by hemangd** [taskforcesh/bullmq#634]
Ref: https://docs.bullmq.io/guide/jobs/repeatable

`// Repeat job once every day at 3:15 (am)
await myQueue.add('submarine', { color: 'yellow' }, 
  {
    repeat: {
      cron: '* 15 3 * * *'
    }
  });`

The example given above runs the corn task every second of 3:15 am. Correct corn should be `15 3 * * *`

**Comment by manast** [comment]
No, because we support seconds, which no all cron expressions do.
