### ISSUE TITLE
Support env variables when using sandbox mode

### ISSUE THREAD

**Issue by aaronjhoffman** [taskforcesh/bullmq#640]
When using sandbox mode, the child process is being created with a copy of the current process execArgv, but not with the env variable of the current process.

The env variables are usually the way to send sensitive data, like the redis connection, but also it's easier option to change the configuration for the child process.

**Comment by roggervalf** [comment]
hi @aaronjhoffman, you could check #793, it's working as expected, so I'll close this issue. Even though if you could reproduce your case in a test case, feel free to reopen this issue or create a new one.
