### ISSUE TITLE
Changelog is not updated

### ISSUE THREAD

**Issue by roggervalf** [taskforcesh/bullmq#641]
https://docs.bullmq.io/changelog changelog is not updated, it seems that there are 2 changelog diles, CHANGELOG.md is the one that receives the latest versions from semantic-release

**Comment by manast** [comment]
hmm, I thought I had fixed this problem once and for all but it is back.

**Comment by roggervalf** [comment]
Seems that is working now 🎉  but as the changelog does not have Changelog title, the last version is not showed in https://docs.bullmq.io/changelog xd so only the change description
