### ISSUE TITLE
[Flow] - waitUntilFinished of any children not fails when the job fails

### ISSUE THREAD

**Issue by felixmosh** [taskforcesh/bullmq#644]
In my server I have API server & separate process for workers.

in my API end-point i'm adding a new flow:
```js
// api
import { FlowProducer, QueueEvents } from 'bullmq';

const queueEvents = new QueueEvents('renovate');
const flowProducer = new FlowProducer();

async function addNewRenovateFlow() {
  const flow = await flowProducer.add({
    name: 'renovate-interior',
    queueName: 'renovate',
    children: [
      { name: 'paint', data: { place: 'ceiling' }, queueName: 'steps' },
      { name: 'paint', data: { place: 'walls' }, queueName: 'steps' },
      { name: 'fix', data: { place: 'floor' }, queueName: 'steps' },
    ],
  });

  return {
    waitUntilFinished(ttl = ms('1min')) {
      return Promise.all(
        [flow.job]
          .concat(flow.children.map((node) => node.job))
          .map((job) => job.waitUntilFinished(queueEvents, ttl))
      );
    },
  };
}
```

```js
// worker
import { Worker } from "bullmq"

const stepsQueue = new Worker('steps', async (job) => {
  await performStep(job.data);

  if(job.name === 'paint') {
    throw new Error(`Can't paint today`);
    return 2500;
  } else if( job.name === 'fix' ) {
    return 1750;
  }
});
```

When I  in my API server `await waitUntilFinished()` it not fails when `paint` job processes but fails due to TTL timeout.

I do see that at the worker side the `paint` job fails, but it is not reflected on the api side.

Any help will be much appreciated

**Comment by manast** [comment]
not sure I understand your issue here, are you asking why your implementation of waitUntilFinished does not work as you expect or some issue in BullMQ?

**Comment by felixmosh** [comment]
I've asking why `BullMQ`'s `waitUntilFinished` is not fails when the relevant children job fails

**Comment by manast** [comment]
Because it waits until the job finishes, if the job completes or fails there is no reason to throw an exception, a job failing is a valid outcome when processing a job.

**Comment by felixmosh** [comment]
Ha, I understand, thank you 🙏🏼
