### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by sir4ju1** [taskforcesh/bullmq#65]
Node: 12.12
Platform: Mac OS 10.14.6, Windows 10 (1903)

Problem: Installed `bullmq` thourgh npm into a fresh project. Trying to run sample code and facing `Error: Cannot find module 'tslib'`
Should `tslib` need to be installed manually in the project? Or is there any other suggested way?

**Comment by manast** [comment]
can you try to use yarn instead of npm?

**Comment by sir4ju1** [comment]
I tried yarn as well, the problem is solved if I manually install `tslib` into my project.

**Comment by arkhamRejek** [comment]
same issue whether yarn or npm is used, adding tslib fixes the issue

**Comment by digitalmio** [comment]
Same, it looks like you have `tslib` in your package lock, but not as dependency.

**Comment by stankaraban** [comment]
@manast any update of this bug?
