### ISSUE TITLE
RedisClient.waitUntilReady never resolves 

### ISSUE THREAD

**Issue by 10xjs** [taskforcesh/bullmq#656]
In the event that `RedisClient` fails to connect due to `ECONNREFUSED`, it remains stuck in an undetectable unresolved state. All other methods (including `close`) that internally depend on `_client` become inoperable. This makes it impossible to gracefully shut down an app that has failed to connect to redis.

This issue is related to this change https://github.com/taskforcesh/bullmq/commit/fb3377280b3bda04a15a62d2901bdd78b869e08c, where `waitUntilReady` was updated to simply ignore `ECONNREFUSED` errors.

**Comment by 10xjs** [comment]
Looks like the test for this was disabled some time ago https://github.com/taskforcesh/bullmq/commit/19dfd78ecf034df06032bbf6b805d8114ac7c182

**Comment by manast** [comment]
> Looks like the test for this was disabled some time ago [19dfd78](https://github.com/taskforcesh/bullmq/commit/19dfd78ecf034df06032bbf6b805d8114ac7c182)

Yes. Because it should not fail if redis is not available at the time we instantiate a queue.

**Comment by 10xjs** [comment]
@manast I opened a [PR that addresses this](https://github.com/taskforcesh/bullmq/pull/657) (and fixed the disabled test).
