### ISSUE TITLE
Problem Rate-Limiting a Worker

### ISSUE THREAD

**Issue by mikebridge** [taskforcesh/bullmq#667]
I'm not seeing my rate limits being applied with BullMQ 1.40.1.  I'm following [this](https://docs.bullmq.io/guide/rate-limiting) documentation, and I think this should process one job every 10 seconds, but it seems to process them all as fast as it can:  

```javascript
const queue = new Queue(queueName, REDIS_CON);

const queueScheduler = new QueueScheduler(queueName, REDIS_CON);

const worker = new Worker(queueName, processJob, REDIS_CON, {
  concurrency: 1,
  limiter: { 
    max: 1,
    duration: 10000,
  },
});

```

**Comment by manast** [comment]
Can you extend the issue with a code snippet that reproduces the issue?

**Comment by mikebridge** [comment]
Sorry, I think this is an error in the constructor arguments.   `REDIS_CON` is

```javascript
const REDIS_CON = {
  connection: {
    host: redisHost,
    port: redisPort,
  },
};
```

So it should be:

```javascript
const worker = new Worker(queueName, processJob, {
  ...REDIS_CON,
  concurrency: 1,
  limiter: { 
    max: 1,
    duration: 10000,
  },
});
```
