### ISSUE TITLE
How to get jobs from getNextJob() continuously?

### ISSUE THREAD

**Issue by StanleyAM** [taskforcesh/bullmq#679]
How to get jobs from getNextJob() continuously when there have multiple jobs at the waiting state in the queue?

Below is the sample code:

```
const worker = new Worker('foo', null, { connection });
const token = 'the-token';

setInterval(async () => {
    const job = (await worker.getNextJob(token)) as Job;
    if (job) {
        console.log(job.data);
        await job.moveToCompleted('the result', token);
    }
}, 1000);
```

But there is always getting only one job in the loop. What is the proper way to get jobs from getNextJob() continuously?

Thanks!

**Comment by manast** [comment]
Let me know if this piece of documentation is of any help: 
https://docs.bullmq.io/patterns/manually-fetching-jobs#looping-through-jobs

**Comment by StanleyAM** [comment]
Oh! I omit there is also returning the next job in the waiting queue at the API "moveToCompleted".
Thank you @manast !

**Comment by manast** [comment]
@StanleyAM yes that is an optimization to save one roundtrip per job, you can disable this behaviour passing false as the third argument of ```moveToCompleted```.
