### ISSUE TITLE
Debounce example is confusing / misleading

### ISSUE THREAD

**Issue by dobesv** [taskforcesh/bullmq#689]
Looking at https://docs.bullmq.io/patterns/debounce-jobs

This doesn't seem to be a debounce.  With a debounce, the timer is reset every time a new job is added.  However, in the example it would run a single job after 1 seconds.

Also, the example says in the comment that the job would be delayed at least 5 seconds but the delay is set to 1 second for each job that is added, which is also confusing

Possible fixes:

- Update title to say "Throttling jobs"
- Update comments to say "delay at least one second"

**Comment by roggervalf** [comment]
Related to #950

**Comment by manast** [comment]
@dobesv Yes you are definitively right about the terminology, this is not a debounce but a throttle.
