### ISSUE TITLE
Job data field is doubly serialized

### ISSUE THREAD

**Issue by jbr** [taskforcesh/bullmq#70]
[This](https://github.com/taskforcesh/bullmq/blob/master/src/classes/job.ts#L151) seems to be the line in question. As a result of this, `JSON.parse(JSON.stringify(job)).data` is always a string, which was quite surprising. My particular use case is sending a Job over a socket serialized as json. It's easy enough to work around this, but since this is still an early release it seemed worth mentioning that this might surprise others as well.

**Comment by manast** [comment]
Yes, the problem is that toJSON should be called something different, because it is not really meant to be used by JSON.stringify.
