### ISSUE TITLE
getJob does not find repeatable job

### ISSUE THREAD

**Issue by Kimblis** [taskforcesh/bullmq#707]
As we can see from the photo, in the console, we have a job with id `checkForUpcomingMeetings`, however when I try to getJob from the queue it returns null (it did not find it )
![image](https://user-images.githubusercontent.com/46688616/130782063-1de153fe-f57e-4f8f-a186-23384e3d440c.png)

Expected behaviour: It is still a job even if it is a repeatable, getJob should be able to find it

**Comment by manast** [comment]
We have a new API that solves this kind of issues: https://docs.bullmq.io/guide/job-schedulers
