### ISSUE TITLE
"Missing lock" error will cause an uncaught exception

### ISSUE THREAD

**Issue by tmcgannon** [taskforcesh/bullmq#71]
While the worker is processing a job that is delayed (or node process is stalling the event loop > lockDuration) and attempts to call handleCompleted(), an "Error: Missing lock for job 778 finished" error is thrown on line 303, is caught, and handleFailed() is called on line 305. 

https://github.com/taskforcesh/bullmq/blob/ad1fc3c19d5c02382989a7e1cb72b807b743465c/src/classes/worker.ts#L298-L308

However, in handleFailed, it attempts to move the job to failed state on line 293.

https://github.com/taskforcesh/bullmq/blob/ad1fc3c19d5c02382989a7e1cb72b807b743465c/src/classes/worker.ts#L284-L295

moveToFailed will also throw an "Error: Missing lock for job 778 finished" exception which will not be caught and will exit the node process.

I think the logic for these types of errors could be handled more gracefully.  But, at the very least, a try catch block should be put around line 293 (await job.moveToFailed()) so that the node process does not exit and the emit('failed') will be executed.

**Comment by Embraser01** [comment]
Hi,

I just stumbled on this issue. I'd like to make a PR for this, is this the right way to do this @manast?
>  But, at the very least, a try catch block should be put around line 293 (await job.moveToFailed()) so that the node process does not exit and the emit('failed') will be executed.

**Comment by manast** [comment]
@Embraser01 I think it sounds as a good approach to me. It is an unrecoverable error and the only thing we can do at this point is to report it to a local event listener.
