### ISSUE TITLE
Jobs get error when using Redis Cluster

### ISSUE THREAD

**Issue by lchrennew** [taskforcesh/bullmq#748]
```javascript
import './utils/env.js'
import { createRedis } from "./utils/redis.js";
import { Job, Queue, QueueScheduler, Worker } from 'bullmq'


const start = async () => {
    const schedulerConnection = createRedis()
    const queueConnection = createRedis()
    const workerConnection = createRedis()


    const scheduler = new QueueScheduler('q', { connection: schedulerConnection, prefix: '{bull}' })
    const queue = new Queue('q', { connection: queueConnection, prefix: '{bull}' })


    await queue.add('myjob', { hello: 'world' }, { repeat: { every: 1000 } })
    const worker = new Worker('q', async (job: Job) => {
        console.log(await job.getState());
        return 'hello'
    }, { connection: workerConnection, prefix: '{bull}' })
}


start()

```

Redis URL:
```
redis-cluster://127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005?enableAutoPipelining=true
```

![image](https://user-images.githubusercontent.com/1522365/133093957-25b52a8a-3932-4787-b112-a7355734e68a.png)

**Comment by lchrennew** [comment]
"bullmq": "^1.46.5",

**Comment by lchrennew** [comment]
@manast I traced this problem, it seems caused by the worker.ts, the `completed` Job object doesn't have `id` which is used by `moveToFinished` script.
```
const job = await completed;   //
```

**Comment by manast** [comment]
Hmm, at least in my codebase the line 427 in job.ts looks like this
```
    this.failedReason = err.message;
```
So it seems that the err object is undefined, we could check err exists before trying to access its property message, but I wonder why is it undefined in the first place.

**Comment by lchrennew** [comment]
> Hmm, at least in my codebase the line 427 in job.ts looks like this
> 
> ```
>     this.failedReason = err.message;
> ```
> 
> So it seems that the err object is undefined, we could check err exists before trying to access its property message, but I wonder why is it undefined in the first place.

Well, the lua script command `moveToFinished` returns `-1`, then the `err` is undefined

**Comment by manast** [comment]
So which line of code that you pasted above is the one producing the exception? This one? 
```
        console.log(await job.getState());
```

**Comment by lchrennew** [comment]
> So which line of code that you pasted above is the one producing the exception? This one?
> 
> ```
>         console.log(await job.getState());
> ```

The exception comes from inside of the Worker, not raised from `job.getState`. In another word, when you remove the `console.log`, the exceptions will be still thrown.

**Comment by lchrennew** [comment]
The exception comes from `ioredis/commander/generateScriptingFunction`

**Comment by lchrennew** [comment]
I tracked the stack down:
--> worker.js `handleCompleted`
--> job.js `moveToCompleted`
--> ioredis/commander.js `generateScriptingFunction`
--> ioredis/script.js `executed`  // Here returns `-1`

**Comment by lchrennew** [comment]
@manast Does this issue have been described clearly?

**Comment by manast** [comment]
Could you please try with version 1.47.0 (latest) ?

**Comment by lchrennew** [comment]
> Could you please try with version 1.47.0 (latest) ?

Yea, let me have a try, thank you, I will give you feedbacks soon.

**Comment by lchrennew** [comment]
I tried the latest version, the exception is still there

**Comment by lchrennew** [comment]
Here's my code to reproduct the issue. 
[demo.zip](https://github.com/taskforcesh/bullmq/files/7180890/demo.zip)

I uses redis 6.2.5, you can create a redis cluster same as mine by running `start.sh` in the `redis-cluster-conf.zip`.
[redis-cluster-conf.zip](https://github.com/taskforcesh/bullmq/files/7180911/redis-cluster-conf.zip)

**Comment by manast** [comment]
Can you provide a .env with the needed env variables? otherwise I get this error:
```ts
/demo/src/utils/redisUrl.js:60
    } = urlPattern.exec(url).groups;
                            ^

TypeError: Cannot read properties of null (reading 'groups')
    at new RedisURL (/Users/manuelastudillo/Downloads/demo/src/utils/redisUrl.js:26:48)
    at Object.<anonymous> (/Users/manuelastudillo/Downloads/demo/src/utils/redis.js:3:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/manuelastudillo/Downloads/demo/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/manuelastudillo/Downloads/demo/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
```

**Comment by lchrennew** [comment]
> Can you provide a .env with the needed env variables? otherwise I get this error:
> 
> ```ts
> /demo/src/utils/redisUrl.js:60
>     } = urlPattern.exec(url).groups;
>                             ^
> 
> TypeError: Cannot read properties of null (reading 'groups')
>     at new RedisURL (/Users/manuelastudillo/Downloads/demo/src/utils/redisUrl.js:26:48)
>     at Object.<anonymous> (/Users/manuelastudillo/Downloads/demo/src/utils/redis.js:3:25)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Module._compile (/Users/manuelastudillo/Downloads/demo/node_modules/pirates/lib/index.js:99:24)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Object.newLoader [as .js] (/Users/manuelastudillo/Downloads/demo/node_modules/pirates/lib/index.js:104:7)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:94:18)
> ```
just one line:
```
REDIS_URL=redis-cluster://127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005?showFriendlyErrorStack=true&autoPipelining=true
```

**Comment by lchrennew** [comment]
> > Can you provide a .env with the needed env variables? otherwise I get this error:
> > ```ts
> > /demo/src/utils/redisUrl.js:60
> >     } = urlPattern.exec(url).groups;
> >                             ^
> > 
> > TypeError: Cannot read properties of null (reading 'groups')
> >     at new RedisURL (/Users/manuelastudillo/Downloads/demo/src/utils/redisUrl.js:26:48)
> >     at Object.<anonymous> (/Users/manuelastudillo/Downloads/demo/src/utils/redis.js:3:25)
> >     at Module._compile (node:internal/modules/cjs/loader:1101:14)
> >     at Module._compile (/Users/manuelastudillo/Downloads/demo/node_modules/pirates/lib/index.js:99:24)
> >     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> >     at Object.newLoader [as .js] (/Users/manuelastudillo/Downloads/demo/node_modules/pirates/lib/index.js:104:7)
> >     at Module.load (node:internal/modules/cjs/loader:981:32)
> >     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> >     at Module.require (node:internal/modules/cjs/loader:1005:19)
> >     at require (node:internal/modules/cjs/helpers:94:18)
> > ```
> 
> just one line:
> 
> ```
> REDIS_URL=redis-cluster://127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005?showFriendlyErrorStack=true&autoPipelining=true
> ```

works?

**Comment by manast** [comment]
I can reproduce the issue, however it is not related to cluster. It is related to the way the ioredis instance is instantiated with this class ```RedisURL```, I can reproduce the issue even with 1 single non-cluster redis server.
I am investigating to see if I can understand the root of the problem.

**Comment by manast** [comment]
This option:

```
option.stringNumbers = this.entries.get("stringNumbers") !== "true";
```

 breaks BullMQ. Remove it and it will work.
