### ISSUE TITLE
job.moveToFailed creates unhandled exception

### ISSUE THREAD

**Issue by ianjkaplan** [taskforcesh/bullmq#754]
In the following code I noticed that jobMoveTofailed 1) returns a promise and 2) moveToFailed has two required parameters according to the typings. the token here has not been provided.

```javascript
        new Worker(
            'mailer',
            async (job) => {

                try {

                    return await mailerService.sendMail({ ...context, ...job.data, year: (new Date()).getFullYear() });
                }
                catch (e) {

                    job.moveToFailed(e);
                }
            });
```

when i console log the error thrown by moveJobFailed (when i await it actually) i get something like 'Error: Missing lock for job 11. failed`. can someone explain why this implementation mistake results in a missing lock error. Thanks in advance for helping me understand better

**Comment by manast** [comment]
Probably because the token is missing, I guess the error message is incorrect, it should be something like "invalid token for lock". 
But why not write the code like this instead:
```ts
   new Worker(
            'mailer',
            async (job) => mailerService.sendMail({ ...context, ...job.data, year: (new Date()).getFullYear() })
        );
```

**Comment by ikaplan20** [comment]
that makes sense. would it be appropriate to throw a missing token error if no token is provided?
