### ISSUE TITLE
RedisCluster Support?

### ISSUE THREAD

**Issue by elucidsoft** [taskforcesh/bullmq#77]
Will this rewrite support RedisCluster natively?  We really want to add redundancy to our Redis instance, but based on testing with Bull 3 it was just completely unreliable with a Redis cluster based on our testing. Was curious if this is going to be resolved in this version?

**Comment by manast** [comment]
Bull uses lua scripts that need to create keys dynamically, so it will probably never take advantage of cluster setups, at least within one queue. For redundancy on the other hand its better to use replication, for instance you can have one master instance and a fallback replica.

**Comment by insanehong** [comment]
Any plan to support redis-cluster? I use 3.x bull with redis cluster.

**Comment by manast** [comment]
it is supported in the same way as in bull, you need to follow this instructions:
https://github.com/OptimalBits/bull/blob/30791047bffd1f5714fae82bbd247bfe4cc2009e/PATTERNS.md#redis-cluster

**Comment by Askadias** [comment]
@manast it doesn't.
There is no more config option:
createClient: (type, opts) => {
    return redisClientInstance;
  }

**Comment by joebowbeer** [comment]
@Askadias You need to pass a Cluster instance in the QueueOptions:

`connection: clusterClient`
