### ISSUE TITLE
Docs: wrong example 'Returning job data'

### ISSUE THREAD

**Issue by igolskyi** [taskforcesh/bullmq#781]
I was looking for ways to get the result of worker processing and probably found the wrong example in the [documentation](https://docs.bullmq.io/guide/returning-job-data)
```js
// here is args -- jobId as a string
queueEvents.on('completed', async (jobId: string) => {
```

But I checked if this was the case in the source code [here](https://github.com/taskforcesh/bullmq/blob/master/src/classes/queue-events.ts#L54) and [here](https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.queueevents.on_2.md)

There are two questions:

1 - Do I understand correctly that it is possible to replace an outdated example in the documentation with the following:
```js
...
const { id } = await queue.add('queueName', data, options)

queueEvents.on('completed', async ({ jobId, returnvalue }) => {
    if (jobId === id) {
        // here is our job
        console.log(returnvalue)
    }
}
```

2 - whether it is possible to receive in `returnvalue` a **stream** from a worker?

Controller:
```js
...
...
app.get('/', async (req, res) => {
    const { id } = await queue.add('queueName', data, options)

    queueEvents.on('completed', async ({ jobId, returnvalue }) => {
        if (jobId === id) {
           // here is our job
           ...            
           // need to stream to response
           returnvalue.pipe(res)
           ...
        }
    }
```

Service:
```js
const PDFDocument = require('pdfkit')
...
...
const worker = new Worker('queueName', async job => {
    // generate document and stream it https://pdfkit.org/docs/getting_started.html
    const doc = new PDFdocument()

   // return stream to controller for --> doc.pipe(res)
   // or for example const doc = fs.createReadStream(filePath, 'utf-8')
    
    return doc
})

```

Or if this is not possible, then I can implement it as recommended here: https://github.com/taskforcesh/bullmq/issues/216#issuecomment-636656718

As far as I understand, I need to write in a queue the generated file as a buffer and to return to the controller of the id of this record in queue. Then in the controller on id to receive the result from a queue and already then stream it in a response.

Or create a temporary file in a worker and return filePath to the controller, and stream file to response with `fs.createReadStream(filePath, 'utf-8)`. And then delete the file.

**Comment by manast** [comment]
Thanks for the remark on outdated documentation, still the old example works.
I see from your questions that you have not yet grasp the correct way to separate queue producers from consumers, I recommend you that you check some of the tutorials I wrote here: https://blog.taskforce.sh/
That should give you some idea on how to implement your solution.
