### ISSUE TITLE
Bullmq connection issue docker

### ISSUE THREAD

**Issue by SalmanK81099** [taskforcesh/bullmq#782]
Hi, I'm making an app using bullmq with nodejs, now i want to dockerize it. Every time i run docker compose up it says ECONNREFUSED address: 127.0.0.1. How do i resolve this? How do i change the host name for redis used by bullmq so i can connect it to a redis image inside docker.

**Comment by manast** [comment]
Please check the documentation regarding connections: https://docs.bullmq.io/guide/connections

**Comment by SalmanK81099** [comment]
Tried it already, not working still gives me the same error

**Comment by manast** [comment]
@SalmanK81099 this is unrelated to BullMQ, but to how to properly configure docker-compose.
