### ISSUE TITLE
TypeError: client.addJob is not a function

### ISSUE THREAD

**Issue by DeadcatDev** [taskforcesh/bullmq#79]
I have so problem with my code, cannot find the reason: 

```
UnhandledPromiseRejectionWarning: TypeError: client.addJob is not a function
    at Function.addJob (C:\...\node_modules\bullmq\dist\classes\scripts.js:38:23)
    at Job.addJob (C:\...\node_modules\bullmq\dist\classes\job.js:323:34)
    at Function.create (C:\...\node_modules\bullmq\dist\classes\job.js:32:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Will be gratefull for any advice

My code: 
```
import { Queue, QueueEvents, Worker } from 'bullmq';
import { posix } from 'path';
import IORedis from 'ioredis';

const connection = new IORedis({
  port: 6363,
  host: 'localhost',
  password: 'some-password'
});

let queues: {
  [key: string]: Queue
} = {};
let queueEvents: {
  [key: string]: QueueEvents
} = {};
let queueWorkers: {
  [key: string]: Worker
} = {};

export function addToQueue(queueName: string, data: any): void {
  queues[queueName].add(queueName, data);
}

export function setQueue(queueName: string): void {

  queues[queueName] = new Queue(
    queueName,
    { connection }
  );
  queueWorkers[queueName] = new Worker(
    queueName,
    async job => {
      console.log(job.data);
    },
    { connection }
  );

  queueEvents[queueName] = new QueueEvents(
    queueName,
    { connection }
  );
  queueEvents[queueName].on('completed', (job, result) => {
    console.log('completed job => ', job);
    console.log('completed result => ', result);
  });
  queueEvents[queueName].on('failed', function(job, err) {
    console.log('completed job => ', job);
    console.log('completed err => ', err);
  });

  queues[queueName].add(queueName, { text: 'foo' });
  queues[queueName].add(queueName, { text: 'bar });
```

**Comment by manast** [comment]
try with this change:
```ts
export async function addToQueue(queueName: string, data: any): void {
  await queues[queueName].waitUntilReady();
  return queues[queueName].add(queueName, data);
}
```

**Comment by manast** [comment]
I will leave this open because ```waitUntilReady``` should not be necessary, we overlooked it.

**Comment by MichielvdVelde** [comment]
I'm getting the same error. I believe I have traced it to `RedisConnection.waitUntilReady()`:

https://github.com/taskforcesh/bullmq/blob/b96f5ba3e9c36182174300af629b34fe43c62ecd/src/classes/redis-connection.ts#L41-L50

I am providing the queue with a connected and ready connection. As such, the scripts are never loaded as `handleReady()` (and thus `load`) is never executed. Instead the connection is returned as-is if the connection status is already `ready`. I'm imagining what is required is some way of determining whether the scripts are loaded, and if not, load them before returning the connection.

The only two workarounds I have discovered so far are using a fresh Redis connection for every queue, or I will need to manually call `load` on the connection before passing it on. Not a major hassle, but possibly unexpected behavior nonetheless.

**Comment by mgan59** [comment]
I got jammed up by this issue, my implementation has a `generator` that fans out my tasks.  Worked fine locally.  But my deployment has a limit on redis-connections which blew up my worker.  I figured I'd just share the redis connection which is when I started having error.  The solution on issue #59 helped get me over the bump.  Just an FYI to anyone else that lands here.
