### ISSUE TITLE
unable to run cron jobs?

### ISSUE THREAD

**Issue by arkhamRejek** [taskforcesh/bullmq#81]
```javascript

const cronQueue = new Queue(obj.name, { connection: connectionConfig });
  
const worker = new Worker(obj.name, processor, {
  connection: connectionConfig,
 });

const  result = await cronQueue.add(obj.name, {test: 'ol'},{   repeat: {
   every: 10000,
   limit: 5
 }} );

```

when i run  await cronQueue.getRepeatableJobs() i get

```javascript
[
  {
    key: 'get-token::::10000',
    name: 'get-token',
    id: null,
    endDate: null,
    tz: null,
    cron: '10000',
    next: 1575414520000
  }
]
```

however the processor never fires, I'm not sure if i'm misunderstanding how repeat job works but i figured that it would run once and then rerun at the allotted repeat param ? in this case run max 5 times every 10 seconds?

this works fine if i remove repeat thoughts ?

**Comment by manast** [comment]
in BullMQ you need to have an instance of a QueueScheduler which takes care of scheduling the repeatable jobs: https://docs.bullmq.io/guide/jobs/repeatable

**Comment by arkhamRejek** [comment]
@manast thank you, i don't know how I missed that in the docs thank you, this rewrite is amazing by the way everything is just working flawlessly. Once you guys get UI support it'll be hard to go to any other library
