### ISSUE TITLE
Missing key for parent

### ISSUE THREAD

**Issue by dotMortis** [taskforcesh/bullmq#811]
Hey, when I try to use `job.create` with an existing parent key, I get "Missing key for parent job" `<QueueName>:<JobId>`, what is missing is the prefix I am using.
If I change `getParentKey` in `utils.js` to add the prefix to the key `<Prefix>:<QueueName>:<JobId>`, it works as expected.

**Comment by dturton** [comment]
I have the same issue, whats the workaround?

**Comment by manast** [comment]
@dturton the workaround is to manually add the queue prefix to the key ("bull" is the default).

**Comment by roggervalf** [comment]
Added in https://api.docs.bullmq.io/interfaces/BaseJobOptions.html#parent
