### ISSUE TITLE
[PR Discussion] Removing lodash

### ISSUE THREAD

**Issue by prescience-data** [taskforcesh/bullmq#815]
Looking through the uses of `lodash` in the lib, there doesn't seem to be any obvious advantage in pulling in such a heavy dependency for a handful of utility functions that are quite easy to replicate natively in ES2020+ TypeScript.

Obvious counterpoint is that the implementations are using tree-shaking which only pulls in the functions used - however just by dent of having `bullmq` as a dependency of a project, it means that `lodash` comes along for the ride indirectly which increases container size. 

More importantly, conventional wisdom is that less dependencies is better - so given the null impact of replacing the functions with native calls, it seems prudent. 

I'm very happy to do this PR - but just want to make sure @manast is happy with the idea in general prior to spending time migrating it all over.

Let me know what you think? 😄

**Comment by manast** [comment]
I do not have anything against it as long as the replacements do not incur in a noticeable performance penalty. I usually test with jsperf to see how my replacement performs against lodash.

**Comment by roggervalf** [comment]
lodash was removed, we can close this issue
