### ISSUE TITLE
Accept/reject jobs by job name?

### ISSUE THREAD

**Issue by kevinejohn** [taskforcesh/bullmq#84]
Is there a way to make a worker not accept and process a job based on the job name? This would be if you have specific workers that process different job names but use the same queue instead of creating completely separate queues.

It seem like this is possible from the readme example but it doesn't function that way:
```
const worker = new Worker('Paint', async job => {
  if (job.name === 'cars') {
    await paintCar(job.data.color);
  }
});
```
https://github.com/taskforcesh/bullmq#the-gist

**Comment by manast** [comment]
I think we can improve the documentation. We want to get rid from legacy bull way of handling named jobs which was actually confusing people. So the answer to your question is no, you need to handle all the job "names" in your processor.

**Comment by frct1** [comment]
@manast 
Hi
But what is will be proper way to handle specified jobs and add processors without a lot of boilerplate "if-based" code ?

**Comment by phrozen** [comment]
Can we confirm what is `job.name` doing in 4.0?

**Comment by ccollie** [comment]
`ping`. I'm writing a management app and supporting `job.name` adds a bit of complexity which I'm happy to deal with only if this feature is useful and being officially supported going forward.

**Comment by manast** [comment]
```job.name``` is just a convenience attribute that can be used for UIs, tools, or whatever. But there are no other magic things happening behind the curtains with the name attribute.

**Comment by ccollie** [comment]
Understood. I just wanted to make sure that this attribute is a stable part of the `api`.

**Comment by roggervalf** [comment]
This should be covered in our documentation https://docs.bullmq.io/patterns/named-processor
