### ISSUE TITLE
waitUntilFinished hang if removeOnComplete is set without TTL

### ISSUE THREAD

**Issue by Embraser01** [taskforcesh/bullmq#85]
When using the `removeOnComplete` option on a job, calling the `waitUntilFinished` will have an undefined behavior (unless ttl has been set).

If it's called before the job is cleared from the queue, it will work as intended but if the job is already removed, it will just hang indefinitely.

I think the `waitUntilFinished` function should warn the user if `removeOn...` is set as it may never resolve.

**Comment by manast** [comment]
ok, seems like a bug to me. Would you mind to provide a small snippet that reproduces the issue that we can use as a test case?

**Comment by Embraser01** [comment]
Here is a reproduction repo I made to check: https://github.com/Embraser01/bullmq-issue-85

It gives the percentage of jobs that hit the TTL with and without `removeOnCompleted` (I got 4% of failed jobs with it enabled).

**Comment by antoniusostermann** [comment]
Just found this - @Embraser01 did you find any way to work around this? If you set `removeOnComplete` to false, how do you avoid exceeding your redis' memory?

`job.waitUntilFinished()` is super helpful in some cases imho, but this really seems like an issue for me.

**Comment by Embraser01** [comment]
> Just found this - @Embraser01 did you find any way to work around this? If you set `removeOnComplete` to false, how do you avoid exceeding your redis' memory?
> 
> `job.waitUntilFinished()` is super helpful in some cases imho, but this really seems like an issue for me.

I added a recurrent job that just clean jobs that have completed from more than X seconds (like 15/30s)

**Comment by andrisi** [comment]
waitUntilFinished() would be super useful indeed but it's not mentioned in the docs. Imeant to use it to wait for a flow to finish.
