### ISSUE TITLE
Could you kindly add a section in your documentation on how to setup bullmq testing with Jest?

### ISSUE THREAD

**Issue by slidenerd** [taskforcesh/bullmq#850]
Huge fan of your efforts to keep this library maintained. I am trying to run jest tests and currently running into the open handles problem
- A simple thought would be get rid of redis completely and stub it with an in-memory mock redis instance, [however your documentation clearly says here, that QueueScheduler and QueueInstance will create a connection internally.](https://docs.bullmq.io/guide/connections)
- Could you kindly add a section on how to actually test code that uses Bull Queues using Jest

**Comment by manast** [comment]
So are you closing all the queues and queueschedulers after every test? There is no know issue regarding open handles if you close all the instances.

**Comment by slidenerd** [comment]
I have managed to fix this, I had to stub the queue worker and scheduler and now it works

**Comment by skizzo** [comment]
> I have managed to fix this, I had to stub the queue worker and scheduler and now it works

Hi, could you explain how you achieved this? Thanks!

**Comment by manast** [comment]
@skizzo what is specifically not working for you? I think it would be best if you write some code in a new issue that does not work as expected when using Jest and then we can look into it.
