### ISSUE TITLE
Repeatable Flows - only parent job get's repeated

### ISSUE THREAD

**Issue by humont** [taskforcesh/bullmq#851]
# Problem

I seem to be having an issue with repeatable flows where only the parent job will repeat, but any dependencies get lost and never run again.

# Ideal solution

Ideally, I think we should be able to set the entire flow to repeat as a complete unit, all dependencies included.

# Code Example

I have tried the code below with the repeat set on only the child, only the parent, or both child and parent jobs, and in all cases, on the parent job repeats.

```typescript
const flowProducer = new FlowProducer({connection: redisConn);

flowProducer.add({
  name: 'parent job',
  queueName: '...somename',
  data: 'someData',
  opts: {repeat: {cron: "10 * * * * *"}},
  children: [
    {name: 'child job',
    queueName: '...somename',
    data: 'someData',
    opts: {repeat: {cron: "10 * * * * *"}}}
  ]
});
```

**Comment by manast** [comment]
This not supported att the moment, and it is going to be quite complex to implement actually so probable will not be supported in the foreseeable future.

**Comment by manast** [comment]
@roggervalf the best would be to remove "repeat" option at least from the children and maybe throw an exception if using both repeat opts in the parent and the children option at the same time.

**Comment by manast** [comment]
Even better maybe it is possible to use this https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html instead of throwing an exception in runtime.

**Comment by humont** [comment]
Thanks for the quick answers.

My solution has been to create a Job which queues up the flow. The job itself has a cron schedule. So far this seems to be working fine in my testing.

I would agree that `repeat` options should be removed from flows (parent *and* children) - since their entire purpose is to have conditional task completion, having the ability to re-run _just_ the parent seems confusing!

**Comment by manast** [comment]
> My solution has been to create a Job which queues up the flow. The job itself has a cron schedule. So far this seems to be working fine in my testing.

That is a perfectly fine solution and I have used it myself aswell.
