### ISSUE TITLE
Job property finishedOn is undefined

### ISSUE THREAD

**Issue by Seldonari** [taskforcesh/bullmq#863]
When subscribing to the `completed` event on the worker with `worker.on('completed', async (job) => { })`, `job.finishedOn` is `undefined`.
But when I subscribe to the `completed` event through `QueueEvents`, the `finishedOn` property is set after getting the job with the job id.
Is there any explanation to this behaviour ?

**Comment by roggervalf** [comment]
hi @Seldonari, I couldn't reproduce your case, I'm seeing that worker is working as expected, I modify some test cases to check this

**Comment by neemanjabu** [comment]
Hi @roggervalf,
this also happens once stalled job is updated to "failed" after stalled attempts/counts are exhausted.
In this case, the "finishedOn" timestamp is not set.

**Comment by roggervalf** [comment]
Thanks @neemanjabu,
now a fix version was released with this change
