### ISSUE TITLE
Rate limiting does not work properly when worker has random delay

### ISSUE THREAD

**Issue by cl-vladislavl** [taskforcesh/bullmq#868]
🙋‍♂️ Hi!
Recently I started to use Bullmq to throttle requests to external API. But after writing some integration tests, I noticed that requests are not executed in the exact window that was specified in the worker configuration.

Here is the script to reproduce the issue with a simple setup(1 queue / 1 worker) : 
```
const { Queue, Worker, QueueScheduler } = require('bullmq');

// Delay will simulate latency on network to external API.
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// 1. Setup
const queue = new Queue('test-queue');
const worker = new Worker('test-queue', async (job) => handleJob(job), {
    concurrency: 1, // = limiter.max
    limiter: {
        max: 1,
        duration: 10000
    }
});
const scheduler = new QueueScheduler('test-queue');

// 2. Worker function
const handleJob = async (job) => {
    // hm, static value for delay = works fine
    // await delay(5000); 
    
     // random delay to be closer to real network latency = unpredictable cross limit window
    await delay(Math.round(Math.random() * 1000));
    
    // here I even can add: 'await limiter.consume(id);'
    // from rate-limiter-flexible npm package with same config to highlight that limit crossed.
    
    return job.id;
};


// 3. Push task to queue
require('http')
    .createServer()
    .listen(8125)
    .on('listening', async () => {
        await Promise.all(
            new Array(3)
                .fill(null)
                .map(() => queue.add('task-one', {}))
        );
    });

```
    
More examples + rate-limiting with `rate-limiter-flexible` you can find in [my test repo](https://github.com/vladLazurenko/bull-rate-limit-issue).

First of all, if we try to add logs, use static delay(5s) in config: 1 req per 10 sec - you will notice that tasks are limited in next timeline: 
- (~1s) 1st task started
- (~6s) 1st task finished
- (~11s) 2nd task started
- (~16s) 2nd task finished  
- ....

But I expect that Bull will refresh the duration window only when the task is completed(not grabbed by worker):
- (~1s) 1st task started
- (~6s) 1st task finished // starting from now, Bull will count 10-sec duration window
- (~16s) 2nd task started
- (~21s) 2nd task finished  
- (~31s) 3rd task started  
- ...

And here I supposed is a key to **random** delay issue - if the delay will be different(small in last task -> and huge in next) it will produce that in 10 seconds duration window frame there will be more than 1(`limiter.max`) task. So even if we don't have any async functions(call to db, etc) before we request our external API, we still have random network latency before request reached to external API rate-limit.

Possible solutions that I see: 
 - 🤔 (not for our case) if it's not so critical, anyway call external API - catch 429 and backoff task again to queue.
 - 🤷‍♂️ place +1 redis based rate-limit solution(`rate-limiter-flexible`) before calling external API and do backoff if limit reached.
 - 🧙‍♂️ choose magic number N(not less than 1s) and define duration window as = duration + N will not 100% reliable.
 - 💡 if its possible to fix it through PR, I will glad to learn lua script and help to contribute this fix.
 
 
 I tried to find a similar issue on bull github as well, but seems like only #613 more close to what I mentioned.
 Thank you, for your attention 🙌.

**Comment by manast** [comment]
I understand the issue but as I wrote previously I do not think the solution is to base the rate limiter in completed jobs since then you will get the same issue in reverse. I think for most use cases the way it works now is fine, however for other cases the best would be to be able to rate limit the job manually from within the processor function, as you mention, when getting status 429 we rate limit the queue for some time. That would solve many issues, however it requires a different rate limit implementation than the one we have today, so therefore this would only end as a new feature in BullMQ Pro.

**Comment by cl-vladislavl** [comment]
@manast Thank you for your answer,
for me, it's still not clear why I will get the same issue in reverse. 

If someone is interesting in our solution for this: for requests that are free to call for us we choose 1st strategy, but for ones that are costly(proxy services) to call and critical to omit possible rate-limit errors, we trigger rate-limiter library based on Redis as first step in processor function

**Comment by manast** [comment]
Ok, so I re-read your issue, and now I understand better what you want. Basically, that would imply a suboptimal use of the resources. As it is now if your worker only performs the call to the rate-limited API it should work independently on the time it takes to make the call. Of course, if you have a random delay before the call the rate limiter will not work. And I am not sure your proposal would solve that case either in general actually. A counterexample is if the random delay in the first job is 10 seconds, but on the second is 0 seconds, then you will end calling the API 2 times directly after each other and not once every 10 seconds.

**Comment by roggervalf** [comment]
this feature is currently available in  https://docs.bullmq.io/guide/rate-limiting#manual-rate-limit and https://docs.bullmq.io/bullmq-pro/groups/rate-limiting#manual-rate-limit

**Comment by cl-vladislavl** [comment]
@roggervalf Wow, that seems cool! Thanks 

Initially, I expected that original worker schedule will respect the limit configuration, but this feature still makes sense
