### ISSUE TITLE
Rename main branch to main?

### ISSUE THREAD

**Issue by arbourd** [taskforcesh/bullmq#869]
`master` has been replaced with `main` in most cases / repos. Although not required, perhaps this project should also consider abiding by that community change?

It should update open pull-requests.

**Comment by manast** [comment]
For new projects makes sense, but I wont spend time on a change that will not bring any value other than potentially break something for one or two users. I understand there are political issues behind things like this, but in my view there is no room for politics in a software project. Please respect it my view on this.
