### ISSUE TITLE
Job data should be properly typed

### ISSUE THREAD

**Issue by lemiesz** [taskforcesh/bullmq#87]
In BullQ3 you could supply interface to your jobs, to describe what kind of data can be passed. 
In BullMQ I do not see this option. 

I propose that when you create a Queue you can supply a interface describing allowed job parameters. 

```
   interface SomeJobParams {
      name: string,
      objectId: string 
   }

 const queue = new Queue<SomeJobParams>("my-queue"); 
 queue.add("do-some-stuff", {name: "rob', objectId: "1234"})
```

**Comment by manast** [comment]
Not sure I understand exactly what you mean, but what we can (and should do), is to make the Queue class a generic, so that you can instantiate it like this:
```ts
const queue = new Queue<MyJobInterface>("my-queue");
```
so that you will get static typing on the data parameters for the job.

**Comment by lemiesz** [comment]
That is what I was asking, sorry my formatting got screwed up I will edit my original post.

**Comment by lemiesz** [comment]
Thanks!

**Comment by manast** [comment]
@rcfrias as the data object is serialized and sent via Redis, you cannot use functions on it.
