### ISSUE TITLE
get status of the job

### ISSUE THREAD

**Issue by majidsajadi** [taskforcesh/bullmq#875]
Hi

I have a question. is there any other way to get the status of a job other than `getStatus` method? 

for example, I want to fetch all jobs but there is no property that shows the status of the job other than looping through all jobs and calling the async method `getStatus` which may cause performance issues. isn't there any better way to get this field? for example a getter?

**Comment by ccollie** [comment]
There's no getter, unfortunately. My attempt at doing this is something like the following in `lua`

https://github.com/ccollie/toro-api/blob/outliers/src/server/commands/getJobState-7.lua

For multiple jobs, you can do this in a `pipeline`. I'd still be cautious about handling too many jobs in the same call though.

**Comment by ccollie** [comment]
Some clarification: `bull` has similar code that's used by `getStatus`, so you can use that, but for your use-case the important thing is to bypass the `getStatus` call and `pipeline` calls using the `redis` client directly.

**Comment by manast** [comment]
Closing since we have no plans to implement this feature in BullMQ right now.
