### ISSUE TITLE
The count of completed job always is 1800

### ISSUE THREAD

**Issue by Peatechen** [taskforcesh/bullmq#876]
The count of completed job always is 1800 when use getJobCounts

**Comment by Peatechen** [comment]
> @Peatechen Is it possible that you are using "removeOnComplete" with a value of 1800? If that is the case, then thats why. However I agree that it could be useful to know all the completed jobs ever and get that as a count too.

As you said,I have set removeOnComplete: ms("30m") / 1000

**Comment by JCMais** [comment]
I suppose queue.getMetrics does not have this issue right? as it does not use the value from the list of jobs, instead it uses from internal metrics data structure

**Comment by Peatechen** [comment]
> I suppose queue.getMetrics does not have this issue right? as it does not use the value from the list of jobs, instead it uses from internal metrics data structure

Sorry, my mistake, I misunderstood the 'removeOnComplete' parameter and thought it was a parameter for delayed deletion.
