### ISSUE TITLE
Redis 4.x support

### ISSUE THREAD

**Issue by anchan828** [taskforcesh/bullmq#89]
I want to use bullmq with Google Cloud Memorystore for Redis, however hullmq supports only 5.0 higher.
https://github.com/taskforcesh/bullmq/blob/master/src/classes/redis-connection.ts#L8

Google Cloud Memorystore for Redis supports 3.2 or 4.0
https://cloud.google.com/memorystore/docs/redis/supported-versions

So bullmq throw RedisConnection error
```
Error: Redis version needs to be greater than 5.0.0 Current: 4.0.14 at RedisConnection.init
```
Is it possible to support 4.0?

**Comment by manast** [comment]
No, it is not possible because we use redis streams and that is only available on 5.0 and higher. 5.0 has been out for a couple of years now, so I hope google cloud will upgrade their instances very soon.

**Comment by robertop87** [comment]
@anchan828 hey do you know if google will support Redis 5 soon?

**Comment by manast** [comment]
I have no idea actually... redis 5.0 has been out for a while now so it should be released any moment now, AWS has supported it for many months.

**Comment by samtsai15** [comment]
note : Google Cloud Memorystore for Redis already supported 5.0 on June 03, 2020

**Comment by framled** [comment]
I have the same issue in Azure...
They have Redis in version 4 as stable and 6 as preview :/

**Comment by manast** [comment]
@framled you can use previous version of Bull instead: https://github.com/optimalbits/bull
