### ISSUE TITLE
unexpected behavior: if worker process exit due to stalled, job will not get retried or moved to delayed, even if it has more attempts.

### ISSUE THREAD

**Issue by gWOLF3** [taskforcesh/bullmq#892]
scenario:

let's say i create a queue with a default number of attempts, say 10, as well as a queue scheduler and a worker. 

if the worker grabs a job off that queue, then the worker process gets exited (for example with crtl-c) - then, after restart -the job will sit in active queue for a while, but eventually, as expected, the job will eventually fail with failed reason: "job stalled more than allowable limit"

however, the problem arises because, when this job fails - even if this was the first attempt - the queue scheduler does not move this job back into the 'delayed' queue - rather - it stays in failed. this happens despite the default attempts attached to that queue. 

what causes this behavior? is this expected or by design? if so - how to make sure that these jobs are thrown back onto the delayed queue as expected? 

a hacky fix would be to listen to failedReason == 'job stalled more than allowable limit' and check to see if the attempts are less than certain number, if so throw it back.

**Comment by manast** [comment]
In the QueueScheduler there is an option ```maxStalledCount``` which by default is 1, so it will retry at least once then it will fail with said reason, the rationale being that it is unlikely that the same job would be killed more than once due to a process dying, however, you can increase this number if you want.

**Comment by gWOLF3** [comment]
@manast - out of curiosity - shouldn't this parameter be attached to the queue level default options or job level options - rather than queue scheduler? 

assuming that you could have multiple queue schedulers attached to a work queue -> this would result in inconsistent behaviors depending on the scheduler - rather than being able to set a consistent maxStalledCount per job.

**Comment by manast** [comment]
> @manast - out of curiosity - shouldn't this parameter be attached to the queue level default options or job level options - rather than queue scheduler?
> 
> assuming that you could have multiple queue schedulers attached to a work queue -> this would result in inconsistent behaviors depending on the scheduler - rather than being able to set a consistent maxStalledCount per job.

Yes, it would be better to have the options persisted in the queue itself, and in time it will be probably moved there.
