### ISSUE TITLE
Mocha types are not included as part of bullmqs dependencies (But are needed?)

### ISSUE THREAD

**Issue by zkldi** [taskforcesh/bullmq#894]
Relevant error:
```
node_modules/.pnpm/bullmq@1.54.4/node_modules/bullmq/dist/utils.d.ts:2:23 - error TS2688: Cannot find type definition file for 'mocha'.

2 /// <reference types="mocha" />
```

Looks like `@types/mocha` isnt a dependency of `bullmq` but code won't compile unless you have those types set. Should `@types/mocha` be part of the dependencies?

**Comment by manast** [comment]
Thanks for reporting this, will take a look asap.

**Comment by zkldi** [comment]
Thanks for such a fast fix!
