### ISSUE TITLE
How to achieve Producer to Consumer(s) pattern? (Kafka like)

### ISSUE THREAD

**Issue by SorooshMerajiyan** [taskforcesh/bullmq#898]
Hey, We are planning on using BullMQ for our notification system.

Consider the following example:
```ts
await notificationQueue.add('new-notification', notificationData);

new Worker('email-notification', emailProcessor);
new Worker('whatsapp-notification', whatsappProcessor);
new Worker('push-notification', pushProcessor);
// And many more...
```

How to achieve this? adding an event and processing it in multiple workers? something like Kafka consumer groups

**Comment by manast** [comment]
This maybe? https://docs.bullmq.io/bullmq-pro/groups

**Comment by SorooshMerajiyan** [comment]
Yes, that addresses my question, Thank you.
