### ISSUE TITLE
Support Redis connections reuse

### ISSUE THREAD

**Issue by stansv** [taskforcesh/bullmq#9]
This is achieved with `createClient` option which is defined but ignored now.

Also, we should accept RedisOptions for this to work.

PS Moreover, it's a bit confusing that we accept IORedis instance in two places but no usual RedisOptions at all

```
// very simplified version of RedisOptions
export interface RedisOpts {
  skipVersionCheck?: boolean;
  port: number;
  host: string;
}

export type ConnectionOptions = RedisOpts | IORedis.Redis; // [1]

export interface QueueBaseOptions {
  connection?: ConnectionOptions;
  client?: IORedis.Redis; // [2]
  ...
}
```

**Comment by manast** [comment]
should be fixed with this one: https://github.com/taskforcesh/bullmq/pull/40
Difference between Bull3 and 4 is that there is no createClient method, you just pass a ioredis instance instead.
