### ISSUE TITLE
add default option values to api reference

### ISSUE THREAD

**Issue by gWOLF3** [taskforcesh/bullmq#902]
would be very helpful to be able to see the default values listed in the API reference documentation:

for example:  
https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/api/bullmq.jobsoptions.md

**Comment by manast** [comment]
This seems to be possible to do with api-extractor, so i will mark this as an enhancement: https://api-extractor.com/pages/tsdoc/tag_defaultvalue/

**Comment by roggervalf** [comment]
Our new api documentation is showing the defaultValue param https://api.docs.bullmq.io/interfaces/JobsOptions.html, please @gWOLF3  take a look when have some chance
