### ISSUE TITLE
bullmq@1.56.0: SyntaxError: Named export 'Queue' not found

### ISSUE THREAD

**Issue by Niek** [taskforcesh/bullmq#917]
Upgrading BullMQ from 1.55.1 to 1.16.0 results in this error:

```js
import { Queue } from 'bullmq'
         ^^^^^
SyntaxError: Named export 'Queue' not found. The requested module 'bullmq' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'bullmq';
const { Queue } = pkg;
```

Changing my code to this worked indeed, but it's not ideal:
```js
import bull from 'bullmq'
const { Queue } = bull;
```

I can't find which commit caused it, but it would be nice to have this fixed.

**Comment by Niek** [comment]
It might be related to the TS 3->4 bump in https://github.com/taskforcesh/bullmq/commit/d2897ee7bbf4aee5251ac4fb28705f2bebbe7bfe

**Comment by manast** [comment]
Interesting... did you test by upgrading your local typescript version too? Could it be that typescript introduced an incompatibility between version 3 and 4?

**Comment by Niek** [comment]
> Interesting... did you test by upgrading your local typescript version too? Could it be that typescript introduced an incompatibility between version 3 and 4?

This is in a project not using TS at all, but ES imports.

**Comment by manast** [comment]
@roggervalf maybe it is related to this line in tsconfig.json:
```
    "esModuleInterop": false,
```

**Comment by daeschlerdavid** [comment]
Same for me.
Mixing commonJS and ESM is so much pain...
Lot of my dependency already did the switch to ESM, why not bullmq ?

**Comment by manast** [comment]
@daeschlerdavid not sure what you mean. In BullMQ we only use ESM when importing modules.

**Comment by manast** [comment]
Or put in another way. I do not know why your compiler is complaining that BullMQ is not an ESM module.

**Comment by manast** [comment]
You can ignore my two last comments. It is properly done now, hope it works for you now.

**Comment by daeschlerdavid** [comment]
still getting this error after TS compilation

```
import { QueueEvents, Job } from 'bullmq';
                      ^^^
SyntaxError: Named export 'Job' not found. The requested module 'bullmq' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'bullmq';
const { QueueEvents, Job } = pkg;
```

**Comment by Niek** [comment]
I can confirm I still have the same issue on 1.59.1. Here is a minimal example:

`package.json`:
```json
{
  "dependencies": {
    "bullmq": "^1.59.1"
  },
  "type": "module"
}
```
`index.js`:
```js
import { Queue } from 'bullmq'
```

**Comment by daeschlerdavid** [comment]
```
root@win11 ~/testbull [1]# node -v
v17.2.0
root@win11 ~/testbull# cat index.js 
import { Queue } from "bullmq";
root@win11 ~/testbull# cat package.json 
{
  "type": "module",
  "dependencies": {
    "bullmq": "^1.59.1"
  }
}
root@win11 ~/testbull# node index.js 
file:///root/testbull/index.js:1
import { Queue } from "bullmq";
         ^^^^^
SyntaxError: Named export 'Queue' not found. The requested module 'bullmq' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'bullmq';
const { Queue } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v17.2.0
```

**Comment by spiffytech** [comment]
I'm getting this error when moving from bull 1.55.1 (no error) to 1.56.0 or greater.

```js
import { Job } from "bullmq";

// SyntaxError: Named export 'Job' not found. The requested module 'bullmq' is 
// a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by manast** [comment]
@spiffytech have you tried with 1.59.0 or higher? we are following the best-known conventions in Node for this to work correctly now.

**Comment by manast** [comment]
@Niek if you can create a package.json + index.js that reproduces the issue I would gladly dig in more into it. Seems like we are doing everything as good as it can be done in Node so I do not understand why it would not work for you.

**Comment by manast** [comment]
> @Niek if you can create a package.json + index.js that reproduces the issue I would gladly dig in more into it. Seems like we are doing everything as good as it can be done in Node so I do not understand why it would not work for you.

I am getting old, missed your example in the comment 🤦

**Comment by manast** [comment]
ok, after a lot of frustration and testing I had finally nailed down this to actually typescript 4. It just breaks the module system, I do not understand how this is possible but downgrading to 3.9.10 solves the issue nicely and no matter what I try with version 4+ it just does-not-work...

**Comment by spiffytech** [comment]
> @spiffytech have you tried with 1.59.0 or higher? we are following the best-known conventions in Node for this to work correctly now.

Yep, I tried with 1.59. Sorry, I meant that as "1.56.0 introduced the bug", but I see you've spotted the issue already.

I've pulled down 1.59.4 and don't get the error there.

**Comment by Niek** [comment]
> ok, after a lot of frustration and testing I had finally nailed down this to actually typescript 4. It just breaks the module system, I do not understand how this is possible but downgrading to 3.9.10 solves the issue nicely and no matter what I try with version 4+ it just does-not-work...

I can confirm it's fixed now, thanks @manast! Still weird that TS4 breaks these imports, there should be a workaround/fix on TS4.

**Comment by soulchild** [comment]
@manast I'm seeing this again after upgrading bullmq from 1.87.2 to 1.88.1 in my ESM application (w/o TypeScript). Could this have something to do with the recently introduced [experimental ESM support](https://github.com/taskforcesh/bullmq/commit/ed0faff3c67c436116eb625ffacb03e435caee3f)?

**Comment by manast** [comment]
Not sure, but I will revert because ESM is just broken and trying to enable it just hurts current users. For anybody wanting to use ESM this is the only known way to do it properly: https://blog.taskforce.sh/using-typescript-with-bullmq/

**Comment by soulchild** [comment]
Yeah, esm already gave me hours of pure joy… 😫 I'll let you know if it works. Thanks for the quick fix!

**Comment by soulchild** [comment]
Strangely, 1.89.0 is still broken:

```bash
$ npm ls bullmq
└── bullmq@1.89.0
```

```ts
import { Queue, Worker, QueueScheduler } from 'bullmq';
         ^^^^^
SyntaxError: Named export 'Queue' not found. The requested module 'bullmq' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'bullmq';
const { Queue, Worker, QueueScheduler } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

I tried all intermediate versions and 1.87.2 is the last one working.

**Comment by mikemoooo** [comment]
Can confirm, that 1.89.0 is giving me the same issue.

**Comment by roggervalf** [comment]
hi guys, could you please try version 1.89.1 when have some chance

**Comment by soulchild** [comment]
@roggervalf 1.89.1 did the trick. Thanks! 🙏
