### ISSUE TITLE
Throw exception if trying to use a redis instance with a different eviction policy than "noeviction"

### ISSUE THREAD

**Issue by manast** [taskforcesh/bullmq#921]
This can be achieved by issuing the "info" command just after connecting and checking the line [1]:
```
maxmemory_policy:allkeys-lru
```

[1] https://redis.io/commands/info
[2] https://redis.io/topics/lru-cache

**Comment by kingston** [comment]
Is there a reason why volatile-*, e.g. volatile-lfu, policies should not be allowed? They behave like noeviction unless the key is set to expire (useful for caches where they can be evicted if memory pressure requires) and as far as I can tell, BullMQ does not use expiring keys. https://redis.io/docs/manual/eviction/

**Comment by manast** [comment]
BullMQ does use expiring keys for several things actually, for example, locks on jobs. We have however relaxed this requirement on the library since some hosting providers do not allow us to gather the maxmemory policy, still, it is highly recommended to use noeviction to avoid strange behaviours down the road.
