### ISSUE TITLE
ECONNREFUSED on initial Queue creation

### ISSUE THREAD

**Issue by ocdinvstr** [taskforcesh/bullmq#930]
Hi, I'm trying to test the possible failing cases for BullMQ while working with Redis. I met a bug on BullMQ that I couldn't figured out why it's being stuck at that state. If I stop my Redis instance before creating the Queue (before app startup) normally it's giving "ECONNREFUSED" error while trying to connect to non-existing Redis instance. The problem is not with it, which is a normal error, but after a time even when I start the Redis instance it looks like BullMQ is stuck at initiating, which instead of trying to re-create a new Redis connection or trying to reconnect the existing one set to queue's connection, it's still giving the existing initiate promise and this is causing the BullMQ never to connect the Redis instance.

**Comment by manast** [comment]
Automatic reconnection has been improved a lot in latests releases so I am quite sure this issue does not exist anymore. Reopen if you can provide a case that states otherwise.
