### ISSUE TITLE
Clarify what happens when adding job with duplicate id

### ISSUE THREAD

**Issue by imaGuru** [taskforcesh/bullmq#941]
## Description
Hi, I'm having trouble understanding documentation about duplicate jobIds.
The documentation has a giant red warning notice:

> Jobs that are removed from the queue, either manually or when using settings such as removeOnComplete/Failed will not be considered as duplicates meaning that you can add the same job id many times over as long as the previous job has already been removed from the queue.

Isn't it tautological? Of course a job that is already removed will not be considered as a duplicate because it doesn't exist (duh!). But what happens when the job exists? If I understand correctly: when the job is in active/waiting state the new job to be added will be ignored, otherwise if the current job is failed it will not be considered as a duplicate, and a new job will replace it?

Or is it just me totally missing the mark?
Thanks!

## Bull version
1.54.4

**Comment by manast** [comment]
As long as there is a key in Redis with the jobId that job will not be added to the queue independently in which state said job is in. The reason for the warning is to make it cristal clear that jobs that have been removed will not be affected by this.

**Comment by imaGuru** [comment]
Ok, thanks for the clarification. 

As for the warning, for it was more confusing than helpful. It seemed redundant so I assumed it was just spelled out incorrectly and its meaning was supposed to be different.
If you think the warning is fine, then we can close this issue.

Anyway very nice library!

**Comment by roggervalf** [comment]
From https://github.com/taskforcesh/bullmq/blob/master/docs/gitbook/guide/jobs/job-ids.md it should be fine

**Comment by giovanni-bertoncelli** [comment]
Is there a way to replace the job by the jobId?
