### ISSUE TITLE
v1.57.4 client.moveToActive is not a function

### ISSUE THREAD

**Issue by jamesjjk** [taskforcesh/bullmq#946]
Series issue with change client.moveToActive is not a function on recent upgrade.

TypeError: client.moveToActive is not a function
16/12/2021 13:32:26    at Function.moveToActive (/lokl/node_modules/bullmq/src/classes/scripts.ts:684:40)
16/12/2021 13:32:26    at processTicksAndRejections (internal/process/task_queues.js:95:5)

We have had to rollback our servers.

**Comment by jamesjjk** [comment]
Update this is with version v1.58.0

**Comment by andrisi** [comment]
me too, with 1.58, tough on only on windows, and not on all machines

**Comment by jamesjjk** [comment]
We use Unix based operating systems, reverting to versions 1.57.3 fixed the issue. However the latest release is no backwards compatible, we also noted the CI tests have been skipped.

**Comment by JonasHiltl** [comment]
I'm also getting the error. I'm running my application through Docker containers in the same network.

**Comment by manast** [comment]
Thanks for reporting. Looking into this. There should not be any non-backward compatible changes and the CI tests are always green when we merge.

**Comment by manast** [comment]
Ok, so it seems like this PR introduced the "bug": https://github.com/taskforcesh/bullmq/pull/933. Now, it seems like it is not actually a new bug, but rather an old bug that is being exposed now. Before this PR, the calls to ```moveToActive``` could end in an exception that was silently ignored, now on the other hand it is being reported.

**Comment by lukepolo** [comment]
guessing this is also linked https://github.com/taskforcesh/bullmq-pro-support/issues/5

**Comment by fillon** [comment]
Same with v1.59.2
