### ISSUE TITLE
Add Health Check Call

### ISSUE THREAD

**Issue by elucidsoft** [taskforcesh/bullmq#95]
Lot's of people are using this in Kubernetes, as it's a perfect environment for this framework.  Would be really nice to be able to have a method called isHealthy() or something similar to call on a queue to see if the connection to redis, and everything is working properly.  

Couple of things to note:
- Health checks are called very often in Kubernetes, around every 5 seconds typically.  They usually need to return back very quickly.
- If a health check fails Kubernetes will retry by default up to 3 times.
- If it fails it restarts the container.

This needs to cover the scenario mentioned in #83 where blocking and non-blocking calls behave differently so the health check needs to perform both types.

I would not suggest using the redis healthcheck code available online, as I am already using that as part of my healthcheck and it returns true even though I get errors, this is related to #83.

**Comment by manast** [comment]
Closing as I do not think this is something BullMQ should care about, health checks can be implemented on top of it or on top of some Redis client.

**Comment by y-nk** [comment]
understood. thanks for the prompt repsonse.

**Comment by y-nk** [comment]
@manast i think there's a bug? when passing an `ioredis` instance as `connection` in options:

```
Error: BullMQ: Your redis options maxRetriesPerRequest must be null.
    at RedisConnection.checkBlockingOptions (./node_modules/.pnpm/bullmq@5.41.8/node_modules/bullmq/src/classes/redis-connection.ts:143:15)
    at new RedisConnection (./node_modules/.pnpm/bullmq@5.41.8/node_modules/bullmq/src/classes/redis-connection.ts:113:12)
    at new QueueBase (./node_modules/.pnpm/bullmq@5.41.8/node_modules/bullmq/src/classes/queue-base.ts:66:23)
    at new QueueEvents (./node_modules/.pnpm/bullmq@5.41.8/node_modules/bullmq/src/classes/queue-events.ts:198:5)
```

i've checked what's passed in `QueueEvents` and it's a valid redis instance (as per the `isRedisInstance` check validating `connect`, `disconnect` and `duplicate` methods). Would you like me to open a separate ticket?
