### ISSUE TITLE
How to add Job to multiple queues atomically?

### ISSUE THREAD

**Issue by SorooshMerajiyan** [taskforcesh/bullmq#957]
We want to add jobs to multiple queues at once, meaning either all of them or none of them should be queued.

Is it possible to add jobs in a transaction with BullMQ?

**Comment by ccollie** [comment]
The `api` is not setup to do this directly,  but roughly you would have to use `client.multi()` to run all operations in a [transaction](https://redis.io/topics/transactions). Off-hand I don't know how to do this cleanly but if it's a hard requirement it's possible.

**Comment by SorooshMerajiyan** [comment]
Thanks, exactly what I was thinking.

**Comment by manast** [comment]
@SorooshMerajiyan indeed it is possible but you will need to dig in a bit under the hood. Basically, you need to use ```client.multi()``` and then use the "addJob" command that is defined on the client that you passed to BullMQ when you initialize a Queue instance, you will need to instantiate said Queue with the same redis connection of course. Coincidentally this will only work after this fix is merged: https://github.com/taskforcesh/bullmq/pull/959
If you need more info I can provide it to you.
