### ISSUE TITLE
Possible bug? Bullmq says my Redis version is <5.0.0 even though it isn't

### ISSUE THREAD

**Issue by goldflag** [taskforcesh/bullmq#970]
I get this error: 
`Error: Redis version needs to be greater than 5.0.0 Current: 3.0.504`

When I check my Redis version: 
```
root@tomato2:~# redis-server -v
Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=636cde3b5c7a3923
root@tomato2:~# redis-cli -v
redis-cli 5.0.7
```

**Comment by roggervalf** [comment]
this is a little weird, are you sure that you don't have more than one redis version running?

**Comment by goldflag** [comment]
I'm sure it's the only version running. The server is only one year old and Redis 5 has been around for longer than that. I also spun up a digital ocean managed Redis instance on Redis v6 and it gave me the exact same Error too.

**Comment by roggervalf** [comment]
Could you also try INFO command https://github.com/taskforcesh/bullmq/blob/master/src/classes/redis-connection.ts#L199 that's the one we are using to check the redis version

**Comment by manast** [comment]
Pretty sure this is not a bug in BullMQ, most certainly you are connecting to a different instance, especially when you mentioned that you tried with a digital ocean instance, they work very well with BullMQ, I use them myself.
