### ISSUE TITLE
Stalled/Failed Jobs Stay in Queue

### ISSUE THREAD

**Issue by DanielNetzer** [taskforcesh/bullmq#977]
Hi everyone, first I would like to say that this is a FANTASTIC library! so kudos on that.

BullMQ V: `1.63.0`
Redis V: `6.X.X`, AWS Elasticache Cluster

We are experiencing an edge case where Stalled jobs that pass the max stalled count are considered as failed jobs but remain in Redis, disabling the option to re-trigger the same job.

Adding a job is as follows:

```
 const queue = new Queue(distributionQueue, {
          connection,
          sharedConnection: true,
        });

        const job = await queue.add(jobItem.path, jobItem, {
          jobId: jobItem.id,
          removeOnComplete: true,
          removeOnFail: true,
        });
```

We have a queueScheduler on an orchestrator microservice (100 instances running):

```
        const queueSchedulerInstance = new QueueScheduler(queueName, {
          connection: connection,
          sharedConnection: true,
          maxStalledCount: 0,
        });
```

On the workers end we have a few thousands of them, each handling a single job at a time, configured as follows:

```    this.worker = new Worker(
      this.bullCfg.queueName,
      async (job: Job<JobItem, void>) => {
        return await this.handleItem(job);
      },
      {
        connection: {
          host: this.bullCfg.host,
          port: this.bullCfg.port,
        },
      }
    );
```
Workers also utilize the `job.updateProgress` to, well obviously update the job progress.

What we experience is that usually during deployment of the Workers microservices, some jobs become stalled, eventually fail (I think, maybe not?) but they still exist in Redis, and since we utilize JobID which are UUID's and identical so we can't retrigger that job.

The job is in the following state in Redis:

```
{
  "keyName": "bull:{BlackWidow.caf76460-582e-47b3-bede-4a8d00178706.2c1e49e8-5063-42d0-8cc5-d3f512daf76d}:8e9d35f3-ac4d-4e27-84ba-0d74f05787c7",
  "total": 11,
  "fields": [
    {
      "field": "processedOn",
      "value": "1640968887935"
    },
    {
      "field": "stalledCounter",
      "value": "1"
    },
    {
      "field": "progress",
      "value": "{\"status\":\"Item received at bridge.\",\"hostname\":\"some-hostname\",\"updatedAt\":\"2021-12-31T16:41:27.937Z\"}"
    },
    {
      "field": "priority",
      "value": "0"
    },
    {
      "field": "data",
      "value": "{\"id\":\"8e9d35f3-ac4d-4e27-84ba-0d74f05787c7\",\"path\":\"#/AC/B1/C1/D8/E112929919/F3/I7/P^1002/Q^69258165/O^40/\"}"
    },
    {
      "field": "name",
      "value": "#/AC/B1/C1/D8/E112929919/F3/I7/P^1002/Q^69258165/O^40/"
    },
    {
      "field": "timestamp",
      "value": "1640968855798"
    },
    {
      "field": "opts",
      "value": "{\"removeOnFail\":true,\"jobId\":\"8e9d35f3-ac4d-4e27-84ba-0d74f05787c7\",\"removeOnComplete\":true,\"delay\":0,\"attempts\":0}"
    },
    {
      "field": "failedReason",
      "value": "job stalled more than allowable limit"
    },
    {
      "field": "finishedOn",
      "value": "1640969008977"
    },
    {
      "field": "delay",
      "value": "0"
    }
  ],
  "nextCursor": 0
}
```

There is something I've observed that caused lots of jobs to get into this state, and that's due to the `updateProgress` that sometimes happens after the job failed/succeeded and somehow reinsert it into the Redis, hence locking that key and not allowing to re-process the same job.

It seems like that the QueueScheduler is working properly in terms of detecting stalled jobs and causing them to fail, but a very big piece is missing which is acting upon this transition, which in our application is defined as `removeOnFailed: true`, which just doesn't happen.

as a workaround I've added a manual job removal on every iteration that just checks the queue's for `Failed` jobs and if any is found it's removed manually.

**Comment by roggervalf** [comment]
Thank you @DanielNetzer, we should not allow to update progress if the job key is missing instead, throw an error

**Comment by manast** [comment]
@DanielNetzer has the issue been resolved? if not please let us know so that we can dig deeper into it.

**Comment by DanielNetzer** [comment]
@manast Actually it's still not behaving as expected, #1171 for reference.
